function mpc = npcc_ny_lite_s7_seven_interface_perform_tieline_candidate
%NPCC_NY_LITE_S7_SEVEN_INTERFACE_PERFORM_TIELINE_CANDIDATE
%   Full-NPCC S4 case with three direct PERFORM corridor equivalents fitted
%   against seven scaled public NYISO interfaces. Scenario loads, external
%   schedules, and frozen zonal generation targets are applied by the S7
%   benchmark runner before PF.

case_dir = fileparts(mfilename('fullpath'));
helper_dir = fullfile(case_dir, 'NY_Lite');
addpath(case_dir); addpath(helper_dir);

mpc = loadcase('npcc_ny_lite_s4_cost_calibration_candidate_v2');
params = struct('mode', "perform_scaled", ...
    'gilboa_leeds_scale', 2.0, ...
    'pleasant_wood_scale', 0.85, ...
    'wood_millwood_scale', 1.0, ...
    'lower_hudson_b_fraction', 1.0);
[mpc, report] = apply_perform_tieline_calibration(mpc, params);

mpc.userdata.ny_lite.s7_seven_interface_calibration = struct( ...
    'source_case', 'npcc_ny_lite_s4_cost_calibration_candidate_v2', ...
    'public_interface_count', 7, ...
    'training_scenario_count', 4, ...
    'holdout_scenario_count', 2, ...
    'selected_candidate_id', 'PERF_GL2_PV0p85_WM1_B1', ...
    'train_interface_objective', 0.124349392466313, ...
    'holdout_interface_objective', 0.104067386715993, ...
    'all_interface_objective', 0.228416779182306, ...
    'parameter_report', report, ...
    'status', ['Seven-interface calibrated candidate; standard PF improves ' ...
    'on training and holdout scenarios, but shoulder Q-limit PF still fails. ' ...
    'Exact PERFORM is preferred because it has better holdout, minimum-voltage, ' ...
    'and maximum-residual diagnostics.']);
end
