function mpc = npcc_ny_lite_s5_perform_referenced_candidate
%NPCC_NY_LITE_S5_PERFORM_REFERENCED_CANDIDATE
%   Experimental full-NPCC sensitivity with PERFORM-referenced direct
%   corridors and within-zone generation shift keys. The PF benchmark did
%   not support promoting this case over S4 v2. Scenario PG values are
%   applied by apply_perform_generation_allocation before running PF.

case_dir = fileparts(mfilename('fullpath'));
helper_dir = fullfile(case_dir, 'NY_Lite');
addpath(case_dir); addpath(helper_dir);

mpc = loadcase('npcc_ny_lite_s4_cost_calibration_candidate_v2');
[mpc, tie_report] = apply_perform_tieline_alignment(mpc, 'perform_rx');
[gsk, ~] = build_perform_npcc_generation_shift_keys(mpc);
[mpc, capacity_report] = align_npcc_generation_capacity_to_perform_gsk(mpc, gsk);

mpc.userdata.ny_lite.perform_generation_shift_keys = gsk;
mpc.userdata.ny_lite.perform_capacity_alignment_report = capacity_report;
mpc.userdata.ny_lite.s5_perform_reference = struct( ...
    'source_case', 'npcc_ny_lite_s4_cost_calibration_candidate_v2', ...
    'tieline_mode', 'perform_rx', ...
    'aligned_direct_corridor_count', height(tie_report), ...
    'capacity_aligned_bus_count', height(capacity_report), ...
    'generation_shift_key_source', ...
    'PERFORM 2019 on-peak native online PG mapped to retained NPCC buses', ...
    'status', ...
    ['Experimental structural sensitivity; scenario zonal totals and bus PG ' ...
     'must be applied before PF. Do not use as the default calibrated case.']);
mpc.userdata.ny_lite.s5_status = ...
    ['Experimental only: direct PERFORM capacity/GSK and tie alignment ' ...
     'worsened the fixed-scale interface objective; retain S4 v2 as default.'];
end
