function mpc = npcc_ny_lite_s13_npcc_augmented_2019
%NPCC_NY_LITE_S13_NPCC_AUGMENTED_2019 Unpromoted Phase 1A S13 candidate.
%   Full 143-bus S7 NPCC structural parent
%     + ratings-only Phase 0 corrections
%     + four source PERFORM E-G terminals
%     + seven source PERFORM physical branches.
%
%   This 147-bus/253-branch/62-generator case is not promoted. Passive
%   residualization of overlapping NPCC aggregates, paired S12 response
%   validation, and the six public-hour gates remain mandatory.

case_dir = fileparts(mfilename('fullpath'));
helper_dir = fullfile(case_dir, 'NY_Lite');
addpath(case_dir); addpath(helper_dir);

mpc = loadcase('npcc_ny_lite_s7_seven_interface_perform_direct_candidate');
[mpc, phase0_report] = apply_ny_core_phase0_corrections(mpc, struct( ...
    'fit_reactance', false, 'verbose', false));
[mpc, phase1a_report] = add_npcc_perform_eg_corridor(mpc, struct( ...
    'write_registers', false, 'verbose', false));

mpc.userdata.s13 = struct( ...
    'target_name', 'npcc_ny_lite_s13_npcc_augmented_2019', ...
    'status', 'unpromoted_phase1a_candidate', ...
    'structural_parent', ...
        'npcc_ny_lite_s7_seven_interface_perform_direct_candidate', ...
    'phase0_report', phase0_report, ...
    'phase1a_report', phase1a_report, ...
    'promotion_eligible', false, ...
    'promotion_blockers', {{ ...
        'passive residual equivalents pending', ...
        'same-snapshot S12 comparison pending', ...
        'held-out response validation pending', ...
        'six-hour public operating gates pending'}});
end
