function mpc = npcc_ny_lite_s7_seven_interface_perform_direct_candidate
%NPCC_NY_LITE_S7_SEVEN_INTERFACE_PERFORM_DIRECT_CANDIDATE
%   Current full NPCC-derived structural parent for pending S13. Uses direct
%   PERFORM parameters for the three supported corridors. It improves both
%   training and held-out seven-interface PF consistency without fitting away
%   from PERFORM values. S7 is not itself the promoted operating case.

case_dir = fileparts(mfilename('fullpath'));
helper_dir = fullfile(case_dir, 'NY_Lite');
addpath(case_dir); addpath(helper_dir);

mpc = loadcase('npcc_ny_lite_s4_cost_calibration_candidate_v2');
params = struct('mode', "perform_scaled", ...
    'gilboa_leeds_scale', 1.0, ...
    'pleasant_wood_scale', 1.0, ...
    'wood_millwood_scale', 1.0, ...
    'lower_hudson_b_fraction', 1.0);
[mpc, report] = apply_perform_tieline_calibration(mpc, params);

mpc.userdata.ny_lite.s7_seven_interface_calibration = struct( ...
    'source_case', 'npcc_ny_lite_s4_cost_calibration_candidate_v2', ...
    'public_interface_count', 7, ...
    'training_scenario_count', 4, ...
    'holdout_scenario_count', 2, ...
    'selected_candidate_id', 'PERF_GL1_PV1_WM1_B1', ...
    'train_interface_objective', 0.129454184180544, ...
    'holdout_interface_objective', 0.103848450581776, ...
    'all_interface_objective', 0.233302634762320, ...
    'parameter_report', report, ...
    'model_hierarchy_role', 'structural_parent_pending_s13', ...
    'promotion_eligible', false, ...
    'status', ['S7 structural parent: direct PERFORM corridor parameters ' ...
    'improve training and holdout interface consistency. Shoulder Q-limit PF ' ...
    'still requires reactive-model repair.']);
end
