function mpc = npcc_ny_lite_s4_generation_capability_aligned_uncalibrated
%NPCC_NY_LITE_S4_GENERATION_CAPABILITY_ALIGNED_UNCALIBRATED
%   S4 = S3 feasibility repair plus first-pass NYISO zonal capability
%   alignment. This is still uncalibrated against public interface flows.

case_dir = fileparts(mfilename('fullpath'));
helper_dir = fullfile(case_dir, 'NY_Lite');
addpath(case_dir); addpath(helper_dir);

mpc = loadcase('npcc_ny_lite_s1_acopf_feasible_uncalibrated');
[mpc, ~] = add_ny_downstate_delivery_spine(mpc, 'full');
[mpc, ~] = add_s4_zonal_capability_equivalents(mpc, ...
    struct('include_zone_j', true, ...
    'zone_j_total_pmax_mw', 3000, ...
    'zone_j_cost_c1', 250, ...
    'zone_j_cost_c2', 0.02, ...
    'equiv_cost_c1', 180, ...
    'equiv_cost_c2', 0.02, ...
    'q_abs_ratio', 0, ...
    'apply_upstate_participation_caps', false, ...
    'reclassify_ce_ug', true));

mpc.userdata.ny_lite.s4_case_id = ...
    'npcc_ny_lite_s4_generation_capability_aligned_uncalibrated';
mpc.userdata.ny_lite.s4_status = ...
    'Capability-aligned first pass; feasible behavior and interface calibration must be verified by diagnostics.';
mpc.userdata.ny_lite.s4_zone_j_default_pmax_mw = 3000;
mpc.userdata.ny_lite.s4_generation_alignment_source = ...
    'User-provided NYISO 2025 Gold Book zonal capability summary plus S3 diagnostic findings.';
end
