function mpc=npcc_ny_2025_source_generation(scenario_id)
%NPCC_NY_2025_SOURCE_GENERATION Optional source-estimated 2025 research case.
% Default: S1_2025_SUMMER_PEAK_PUBLIC. Only electrically qualified 2025
% snapshots are loadable. The campaign, executable/source fingerprints,
% allocation rules and fresh AC replay are checked on every successful load.
% Generation is estimated from independent sources; interfaces were never fit.
% This loader makes no exact-public-interface or thermal/DLR qualification.
if nargin<1,scenario_id="S1_2025_SUMMER_PEAK_PUBLIC";end
assert((ischar(scenario_id)&&isrow(scenario_id))||(isstring(scenario_id)&&isscalar(scenario_id)), ...
    'npcc_source_generation:Scenario','Select one registered eligible 2025 scenario ID.');
scenario_id=string(scenario_id);
assert(~ismissing(scenario_id)&&strlength(scenario_id)>0, ...
    'npcc_source_generation:Scenario','A nonempty 2025 scenario ID is required.');
root=fileparts(fileparts(mfilename('fullpath')));
addpath(root);addpath(fullfile(root,'System Matpower Format','NY_Lite'));
folder=fullfile(root,'output','compact_ny_2025','generation_reconstruction');
manifest_file=fullfile(folder,'campaign_manifest.csv');file=fullfile(folder,'campaign.mat');
assert(isfile(manifest_file)&&isfile(file),'npcc_source_generation:MissingArtifact','Saved independent generation campaign is missing.');
manifest=readtable(manifest_file,'TextType','string');
assert(height(manifest)==1&&manifest.artifact=="campaign.mat" ...
    &&manifest.sha256==ny_reference_file_sha256(file), ...
    'npcc_source_generation:Fingerprint','Saved generation campaign fingerprint changed.');
loaded=load(file,'out');o=loaded.out;
k=find(o.inputs.snapshots.scenario_id==scenario_id&o.inputs.snapshots.vintage==2025);
assert(isscalar(k),'npcc_source_generation:Scenario','Select one registered 2025 scenario; historical and unknown IDs are unsupported.');
sc=o.case_summary(k,:);c=o.cases{k};
assert(sc.scenario_id==scenario_id&&sc.input_coverage_qualified&&sc.electrical_baseline_qualified ...
    &&~isempty(c)&&c.electrical_baseline_qualified, ...
    'npcc_source_generation:Qualification','Selected snapshot lacks complete inputs or electrical qualification.');
assert(~o.internal_interface_targets_used&&~o.interface_scoring_performed&&~c.internal_interface_fit_used ...
    &&all(isnan(c.snapshot.interface_targets.target_flow_mw)) ...
    &&all(isnan(o.inputs.interfaces.actual_flow_mw))&&all(isnan(o.inputs.interfaces.target_flow_mw)), ...
    'npcc_source_generation:Leakage','Saved reconstruction must not contain or fit interface targets.');
verification=replay_compact_generation_reconstruction(folder);
v=verification.records(verification.records.scenario_id==scenario_id,:);
assert(verification.passed&&verification.code_manifest_verified&&verification.source_manifest_verified ...
    &&height(v)==1&&v.passed&&ny_reference_file_sha256(file)==manifest.sha256, ...
    'npcc_source_generation:Replay','Independent saved-source and AC verification failed.');
mpc=c.result;
assert(size(mpc.bus,1)==66&&size(mpc.branch,1)==125&&size(mpc.gen,1)==37 ...
    &&nnz(mpc.branch(:,11)>0)==112&&all(ismember((37:82)',mpc.bus(:,1))), ...
    'npcc_source_generation:Identity','The saved case does not have the registered compact 2025 inventory.');
mpc.userdata.ny2025_source_generation=struct('scenario_id',scenario_id, ...
    'campaign_role',string(sc.campaign_role),'timestamp_utc',string(sc.timestamp_utc), ...
    'campaign_sha256',manifest.sha256,'electrical_baseline_qualified',true, ...
    'all_registered_snapshots_electrically_qualified',o.all_registered_snapshots_electrically_qualified, ...
    'generation_prior_source_estimated',true,'observed_generator_dispatch_validated',false, ...
    'observed_zonal_generation_validated',false,'interface_calibrated',false, ...
    'internal_interface_targets_used',false,'exact_public_interface_operators',false, ...
    'source_and_code_fingerprints_verified',true,'fresh_ac_replay_passed',true, ...
    'generator_keys',c.snapshot.generator_keys,'branch_keys',c.snapshot.branch_keys, ...
    'thermal_validation_separate',true,'dlr_ready',false);
end
