function mpc = npcc_ny_lite_s13_npcc_augmented_2019
%NPCC_NY_LITE_S13_NPCC_AUGMENTED_2019 Phase 1A S13-FULL construction parent.
%   Full 143-bus S7 NPCC structural parent
%     + ratings-only Phase 0 corrections
%     + four source PERFORM E-G terminals
%     + seven source PERFORM physical branches.
%
%   This 147-bus/253-branch/62-generator full-NPCC case is not a DLR delivery
%   model. It supplies construction and validation evidence for the future
%   S14 NYISO retention plus external AC multi-port operating model.

case_dir = fileparts(mfilename('fullpath'));
helper_dir = fullfile(case_dir, 'NY_Lite');
addpath(case_dir); addpath(helper_dir);

mpc = loadcase('npcc_ny_lite_s7_seven_interface_perform_direct_candidate');
[mpc, phase0_report] = apply_ny_core_phase0_corrections(mpc, struct( ...
    'fit_reactance', false, 'verbose', false));
[mpc, phase1a_report] = add_npcc_perform_eg_corridor(mpc, struct( ...
    'write_registers', false, 'verbose', false));

mpc.userdata.s13 = struct( ...
    'metadata_schema_version', 2, ...
    'target_name', 'npcc_ny_lite_s13_npcc_augmented_2019', ...
    'status', 'phase1a_s13_full_construction_parent', ...
    'model_role', 'unpromoted_s13_candidate', ...
    'governing_hierarchy_role', 's13_full_construction_validation_parent', ...
    'downstream_operating_model', ...
        'npcc_ny_lite_s14_nyiso_dlr_operating_model', ...
    'dlr_delivery_eligible', false, ...
    'current_phase', 'phase1a', ...
    'structural_parent', ...
        'npcc_ny_lite_s7_seven_interface_perform_direct_candidate', ...
    'phase0_report', phase0_report, ...
    'overlay_report', phase1a_report, ...
    'phase_reports', struct('phase1a', phase1a_report), ...
    'phase1a_report', phase1a_report, ...
    'construction_source_qualified', false, ...
    'promotion_eligible', false, ...
    'construction_blockers', {{ ...
        'Phase 1B physical overlay pending', ...
        'Phase 1C physical overlay pending', ...
        'passive residual equivalents pending', ...
        'frozen solved S14 reduction-source state pending'}}, ...
    'promotion_blockers', {{ ...
        'S13-FULL role is permanently ineligible for DLR-model promotion'}});
end
