function mpc=npcc_ny_2025_partial_spc(scenario_id)
%NPCC_NY_2025_PARTIAL_SPC Optional nominal late-2025 infrastructure variant.
% Earlier 2025 source-estimated operating inputs stress a fixed 2025-12-31
% topology. These are revisited counterfactual diagnostics, not historical
% as-operated reconstructions or fresh held-out validation. No interface fit.
% Only the nominal topology is exposed; parameter sensitivities stay separate.
if nargin<1,scenario_id="S1_2025_SUMMER_PEAK_PUBLIC";end
assert((ischar(scenario_id)&&isrow(scenario_id))||(isstring(scenario_id)&&isscalar(scenario_id)), ...
    'npcc_partial_spc:Scenario','Select one registered nominal 2025 scenario ID.');
scenario_id=string(scenario_id);
assert(~ismissing(scenario_id)&&strlength(scenario_id)>0,'npcc_partial_spc:Scenario','A nonempty scenario ID is required.');
root=fileparts(fileparts(mfilename('fullpath')));addpath(root);addpath(fullfile(root,'System Matpower Format','NY_Lite'));
folder=fullfile(root,'output','compact_ny_2025','partial_spc');
file=fullfile(folder,'campaign.mat');manifest_file=fullfile(folder,'campaign_manifest.csv');
assert(isfile(file)&&isfile(manifest_file),'npcc_partial_spc:MissingArtifact','Saved partial-SPC campaign is missing.');
manifest=readtable(manifest_file,'TextType','string');
assert(height(manifest)==1&&manifest.artifact=="campaign.mat"&&manifest.sha256==ny_reference_file_sha256(file), ...
    'npcc_partial_spc:Fingerprint','Saved partial-SPC campaign fingerprint changed.');
d=load(file,'out');o=d.out;
k=find(o.case_summary.variant_id=="nominal"&o.case_summary.scenario_id==scenario_id);
assert(isscalar(k),'npcc_partial_spc:Scenario','Only registered nominal 2025 cases are loadable; skipped, historical and sensitivity selections are unsupported.');
row=o.case_summary(k,:);c=o.cases{k};
assert(row.electrically_qualified&&~isempty(c)&&c.electrical_baseline_qualified, ...
    'npcc_partial_spc:Qualification','Selected nominal operating state is unqualified.');
assert(~o.internal_interface_targets_used&&~o.interface_parameters_fitted&&~c.internal_interface_fit_used ...
    &&~o.historical_as_operated_reconstruction&&~o.fresh_holdout_validation ...
    &&o.topology_as_of=="2025-12-31"&&all(isnan(c.snapshot.interface_targets.target_flow_mw)), ...
    'npcc_partial_spc:Scope','Saved state must preserve its target-free year-end counterfactual scope.');
verification=replay_compact_2025_partial_spc(folder);
v=verification.records(verification.records.variant_id=="nominal"&verification.records.scenario_id==scenario_id,:);
assert(verification.passed&&verification.parent_and_code_verified&&verification.source_manifest_verified ...
    &&height(v)==1&&v.passed&&ny_reference_file_sha256(file)==manifest.sha256, ...
    'npcc_partial_spc:Replay','Saved parent, code, sources, topology or fresh AC replay failed verification.');
mpc=c.result;
assert(size(mpc.bus,1)==71&&size(mpc.gen,1)==37&&all(ismember((37:82)',mpc.bus(:,1))) ...
    &&size(mpc.branch,1)==row.branch_records&&nnz(mpc.branch(:,11)>0)==row.active_branches, ...
    'npcc_partial_spc:Identity','The selected result differs from the registered compact variant inventory.');
mpc.userdata.ny2025_partial_spc=struct('scenario_id',scenario_id,'variant_id',"nominal", ...
    'topology_as_of',"2025-12-31",'campaign_role',"revisited_counterfactual_diagnostic", ...
    'operating_timestamp_utc',string(c.snapshot.snapshot.timestamp_utc),'campaign_sha256',manifest.sha256, ...
    'electrical_baseline_qualified',true,'approximate_infrastructure',true, ...
    'year_end_topology_counterfactual',true,'historical_as_operated_reconstruction',false, ...
    'fresh_holdout_validation',false,'generation_prior_source_estimated',true, ...
    'observed_generator_dispatch_validated',false,'observed_zonal_generation_validated',false, ...
    'internal_interface_targets_used',false,'interface_parameters_fitted',false,'exact_public_interface_operators',false, ...
    'source_prior_vectors_unchanged',row.source_prior_vectors_unchanged, ...
    'parent_code_source_and_topology_verified',true,'fresh_ac_replay_passed',true, ...
    'generator_keys',c.snapshot.generator_keys,'branch_keys',c.snapshot.branch_keys, ...
    'thermal_validation_separate',true,'dlr_ready',false);
end
