function mpc = npcc_ny_lite_s4_cost_calibration_candidate_v2
%NPCC_NY_LITE_S4_COST_CALIBRATION_CANDIDATE_V2
%   Fixed-interface-scale S4 behavioral candidate.
%
%   This is selected from the S4 cost/participation sweep after replacing
%   missing per-scenario P-32 limit scales with fixed interface scales.
%   It is still candidate-level, not a final calibrated case.

case_dir = fileparts(mfilename('fullpath'));
helper_dir = fullfile(case_dir, 'NY_Lite');
addpath(case_dir); addpath(helper_dir);

mpc = loadcase('npcc_ny_lite_s1_acopf_feasible_uncalibrated');
[mpc, ~] = add_ny_downstate_delivery_spine(mpc, 'full');
[mpc, ~] = scale_ny_downstate_delivery_spine_impedance(mpc, 1.0, ...
    struct('include_gilboa_leeds', false));
[mpc, ~] = add_s4_zonal_capability_equivalents(mpc, ...
    struct('include_zone_j', true, ...
    'zone_j_total_pmax_mw', 3000, ...
    'zone_j_cost_c1', 180, ...
    'zone_j_cost_c2', 0.02, ...
    'equiv_cost_c1', 180, ...
    'equiv_cost_c2', 0.02, ...
    'q_abs_ratio', 0, ...
    'apply_upstate_participation_caps', true, ...
    'abc_cap_factor', 0.8, ...
    'reclassify_ce_ug', true));

mpc.userdata.ny_lite.s4_cost_calibration_candidate_v2 = struct( ...
    'case_id', 'S4_COST_main_grid_J180_E180_F180_G180_K180_CAP0p8_X1', ...
    'selection_basis', 'minimum fixed-interface-scale objective after rescore', ...
    'sum_fixed_scale_interface_objective', 4.33453830248985, ...
    'sum_classic_interface_objective', 132.033930484814, ...
    'mean_zone_j_equiv_pg_mw', 1392.44675097601, ...
    'mean_s4_equiv_pg_mw', 2150.84656269268, ...
    'abc_cap_factor', 0.8, ...
    'x_spine_multiplier', 1.0);
mpc.userdata.ny_lite.s4_status = ...
    'Fixed-scale S4 cost-calibration candidate; not final calibrated case.';
end
