function mpc = npcc_ny_lite_s3_interface_calibration_candidate
%NPCC_NY_LITE_S3_INTERFACE_CALIBRATION_CANDIDATE
% Auto-generated candidate from the first S3 interface calibration sweep.
% Feasible behavior candidate, not final interface calibration.

case_dir = fileparts(mfilename('fullpath'));
helper_dir = fullfile(case_dir, 'NY_Lite');
addpath(case_dir); addpath(helper_dir);

mpc = loadcase('npcc_ny_lite_s1_acopf_feasible_uncalibrated');
[mpc, ~] = add_ny_downstate_delivery_spine(mpc, 'full');
[mpc, ~] = scale_ny_downstate_delivery_spine_impedance(mpc, 0.75, ...
    struct('include_gilboa_leeds', false));
[mpc, ~] = add_zone_j_equivalent_supply(mpc, ...
    struct('total_pmax_mw', 3000, 'q_abs_ratio', 0, ...
    'cost_c1', 250, 'cost_c2', 0.5));

mpc.userdata.ny_lite.interface_calibration_candidate = struct( ...
    'case_id', 'COMBINED_RHO_X_3GW_RHO_0p5_X_0p75', ...
    'case_group', 'combined_rho_x', ...
    'zone_j_total_pmax_mw', 3000, ...
    'zone_j_cost_c1', 250, ...
    'rho_j_cost_c2', 0.5, ...
    'x_spine_multiplier', 0.75, ...
    'x_gl_multiplier', 1.0, ...
    'success_count', 6, ...
    'scenario_count', 6, ...
    'sum_interface_objective', 882.255172855455);
mpc.userdata.ny_lite.interface_calibration_note = ...
    'First behavior-calibration candidate selected by minimum public interface residual objective.';
end
