function [mpc,thermal]=npcc_ny_2025_partial_spc_dlr(weather_scenario)
%NPCC_NY_2025_PARTIAL_SPC_DLR Saved synthetic partial-SPC electrothermal case.
% Default static_reference. Four synthetic weather scenarios share the
% nominal 71-bus year-end topology and independently estimated S1 source
% dispatch inputs. No as-built, as-operated or fresh-holdout claim is made.
% Every successful load verifies the source chain and fresh AC/heat replay.
if nargin<1,weather_scenario="static_reference";end
assert((ischar(weather_scenario)&&isrow(weather_scenario)) ...
    ||(isstring(weather_scenario)&&isscalar(weather_scenario)), ...
    'npcc_partial_spc_dlr:WeatherScenario','Select one registered synthetic weather scenario.');
weather_scenario=string(weather_scenario);
assert(~ismissing(weather_scenario)&&strlength(weather_scenario)>0, ...
    'npcc_partial_spc_dlr:WeatherScenario','A nonempty weather scenario is required.');
root=fileparts(fileparts(mfilename('fullpath')));addpath(root);addpath(fullfile(root,'System Matpower Format','NY_Lite'));
contract=compact_partial_spc_dlr_contract;
assert(nnz(contract.weather.scenario_id==weather_scenario)==1, ...
    'npcc_partial_spc_dlr:WeatherScenario','Unknown synthetic weather scenario.');
folder=fullfile(root,'output','compact_ny_2025','partial_spc_thermal');
file=fullfile(folder,'campaign.mat');mf=fullfile(folder,'campaign_manifest.csv');
assert(isfile(file)&&isfile(mf),'npcc_partial_spc_dlr:MissingArtifact','Saved partial-SPC thermal campaign is missing.');
manifest=readtable(mf,'TextType','string');
assert(height(manifest)==1&&manifest.artifact=="campaign.mat"&&manifest.sha256==ny_reference_file_sha256(file), ...
    'npcc_partial_spc_dlr:Fingerprint','Thermal campaign fingerprint changed.');
d=load(file,'out');o=d.out;k=find(o.weather.scenario_id==weather_scenario);
assert(isscalar(k)&&isequal(o.contract,contract)&&isequal(o.weather,contract.weather), ...
    'npcc_partial_spc_dlr:Contract','Saved weather conditions or research contract changed.');
v=o.cases{k};
assert(o.research_thermal_baseline_qualified&&v.synthetic_electrothermal_qualified ...
    &&~o.weather_observed&&~o.physical_conductor_verified&&~o.interface_targets_used ...
    &&~o.historical_as_operated_reconstruction&&~o.fresh_holdout_validation, ...
    'npcc_partial_spc_dlr:Qualification','Saved synthetic thermal qualification or claim scope is invalid.');
verification=replay_compact_partial_spc_dlr(folder);
row=verification.records(verification.records.weather_scenario==weather_scenario,:);
assert(verification.passed&&verification.source_and_code_verified&&verification.electrical_source_replayed ...
    &&height(row)==1&&row.passed&&ny_reference_file_sha256(file)==manifest.sha256, ...
    'npcc_partial_spc_dlr:Replay','Fresh source, hardware, current or thermal replay failed.');
mpc=v.result;
assert(size(mpc.bus,1)==71&&size(mpc.gen,1)==37&&height(o.realizations)==25 ...
    &&all(ismember((37:82)',mpc.bus(:,1))),'npcc_partial_spc_dlr:Identity','Unexpected compact inventory.');
mpc.userdata.ny2025_partial_spc_dlr=struct('weather_scenario',weather_scenario, ...
    'electrical_scenario_id',contract.electrical_scenario_id,'electrical_variant_id',"nominal", ...
    'campaign_sha256',manifest.sha256,'topology_as_of',contract.topology_as_of, ...
    'synthetic_electrothermal_qualified',true,'research_thermal_baseline_qualified',true, ...
    'year_end_topology_counterfactual',true,'approximate_infrastructure',true, ...
    'weather_observed',false,'physical_conductor_verified',false,'as_built_network_validated',false, ...
    'historical_as_operated_reconstruction',false,'fresh_holdout_validation',false, ...
    'observed_generator_dispatch_validated',false,'exact_public_interface_operators',false, ...
    'internal_interface_targets_used',false,'fresh_ac_and_heat_replay_passed',true,'dlr_ready',false);
thermal=struct('realizations',o.realizations,'selection',o.selection,'conductors',o.conductors, ...
    'weather',o.weather(k,:),'temperature_c',v.temperature_c, ...
    'ampacity_subconductor_amp',v.ampacity_subconductor_amp,'current_audit',v.current_audit, ...
    'thermal_audit',v.thermal_audit,'contract',contract,'campaign_sha256',manifest.sha256, ...
    'research_thermal_baseline_qualified',true,'synthetic_electrothermal_qualified',true, ...
    'fresh_replay',row,'physical_conductor_verified',false,'weather_observed',false,'dlr_ready',false);
end
