function out=replay_ny_only_regional_candidate(folder)
%REPLAY_NY_ONLY_REGIONAL_CANDIDATE Independent Package B fixed-input replay.
% Rebuild topology and source accounting from immutable source files and the
% authoritative frozen Package A reference. The optimizer is never called.
root=fileparts(mfilename('fullpath'));
addpath(fullfile(root,'System Matpower Format','NY_Lite'));
if nargin<1,folder=fullfile(root,'output','ny_only_package_b');end
file=fullfile(folder,'ny_regional_candidate.mat');
manifest_path=fullfile(folder,'candidate_input_manifest.csv');
assert(isfile(file)&&isfile(manifest_path), ...
    'replay_ny_only_regional_candidate:InputFingerprint','Frozen candidate or manifest is missing.');
manifest=readtable(manifest_path,'TextType','string');
assert(all(ismember({'artifact','sha256'},manifest.Properties.VariableNames)) ...
    && height(manifest)==1 && manifest.artifact=="ny_regional_candidate.mat" ...
    && manifest.sha256==ny_reference_file_sha256(file), ...
    'replay_ny_only_regional_candidate:InputFingerprint', ...
    'Saved candidate input differs from its frozen manifest.');
d=load(file);
required={'mpc','generator_keys','branch_keys','expected_qualified','source_manifest', ...
    'replacement_zones','build'};
assert(all(isfield(d,required)),'replay_ny_only_regional_candidate:Schema', ...
    'Candidate artifact is missing a required replay input.');
assert(isequal(d.expected_qualified,true), ...
    'replay_ny_only_regional_candidate:Unqualified','Saved candidate was not qualified.');
zones=string(d.replacement_zones(:));
assert(isequal(zones,unique(zones)) && all(ismember(zones,string(('A':'K')'))) ...
    && all(ismember(string(('G':'K')'),zones)), ...
    'replay_ny_only_regional_candidate:Policy','Replacement zones are not a canonical NY region containing G-K.');
n=normalize_perform_ny_source;
assert(isequal(d.source_manifest,n.source_manifest), ...
    'replay_ny_only_regional_candidate:SourceManifest','Immutable original source manifest differs.');

% A self-consistent embedded foundation is insufficient: it must equal the
% independently stored, manifest-checked, freshly replayed Package A input.
foundation_folder=fullfile(root,'output','ny_only_package_a');
foundation_file=fullfile(foundation_folder,'ny_foundation_reference.mat');
foundation_manifest_path=fullfile(foundation_folder,'reference_input_manifest.csv');
assert(isfile(foundation_file)&&isfile(foundation_manifest_path), ...
    'replay_ny_only_regional_candidate:FoundationMissing','Authoritative Package A reference is missing.');
fm=readtable(foundation_manifest_path,'TextType','string');
assert(all(ismember({'artifact','sha256'},fm.Properties.VariableNames)) && height(fm)==1 ...
    && fm.artifact=="ny_foundation_reference.mat" ...
    && fm.sha256==ny_reference_file_sha256(foundation_file), ...
    'replay_ny_only_regional_candidate:FoundationFingerprint','Frozen Package A reference fingerprint differs.');
foundation=load(foundation_file);
assert(isfield(d.build,'foundation') && same_foundation(d.build.foundation,foundation), ...
    'replay_ny_only_regional_candidate:FoundationMismatch', ...
    'Embedded Package A inputs differ from the authoritative frozen reference.');
foundation_replay=replay_ny_only_foundation(foundation_folder);
assert(foundation_replay.passed,'replay_ny_only_regional_candidate:FoundationFailed', ...
    'The authoritative Package A input does not independently replay.');

fresh=build_ny_regional_candidate(n,foundation,struct('replacement_zones',zones));
v=validate_ny_region_replacement(n.source,fresh.parent,fresh,struct());
assert(v.passed,'replay_ny_only_regional_candidate:FreshBuild','Fresh source reconstruction failed validation.');
assert(isequal(string(d.generator_keys(:)),string(fresh.generator_keys(:))) ...
    && isequal(string(d.branch_keys(:)),string(fresh.branch_keys(:))) ...
    && numel(unique(string(d.generator_keys)))==numel(d.generator_keys) ...
    && numel(unique(string(d.branch_keys)))==numel(d.branch_keys), ...
    'replay_ny_only_regional_candidate:KeyMapping','Saved generator or branch identities differ from the fresh construction.');

% Audit the saved construction record independently of its self-reported
% validation/conservation flags. Numerical source data, device registers and
% every source-to-model allocation must equal a fresh default-parent build.
assert(isfield(d.build,'source_inventory'), ...
    'replay_ny_only_regional_candidate:SourceAccounting','Saved source inventory is absent.');
same_fields(d.build.source_inventory,n,{'source','source_manifest','bus_inventory', ...
    'branch_inventory','generator_inventory','shunt_inventory','control_inventory', ...
    'boundary_reconciliation','source_to_model_mapping'},'SourceAccounting');
same_fields(d.build,fresh,{'source_bus_map','anchor_register','source_branch_map', ...
    'retired_branch_register','retained_parent_branch_map','parent_branch_disposition', ...
    'region_source_buses','source_boundary_ports','replacement_zones','allocation', ...
    'branch_keys','generator_keys','retired_legacy_bus_injections','retired_legacy_generators'}, ...
    'SourceAccounting');
assert(isfield(d.build,'parent')&&isfield(d.build,'candidate')&&isfield(d.build,'row235'), ...
    'replay_ny_only_regional_candidate:FrozenBuild','Saved default-parent construction is missing.');
same_fields(d.build.parent,fresh.parent,{'baseMVA','bus','branch','gen','gencost','bus_name'},'FrozenBuild');
same_fields(d.build.candidate,fresh.candidate,{'baseMVA','bus','branch','gen','gencost','bus_name'},'FrozenBuild');
same_fields(d.build.row235,fresh.row235,{'disposition_register','bus_map','source_branch_register', ...
    'affected_region_register','local_admittance'},'FrozenBuild');
saved_validation=validate_ny_region_replacement(n.source,fresh.parent,d.build,struct());
assert(saved_validation.passed,'replay_ny_only_regional_candidate:FrozenBuild','Saved construction does not validate.');

% Only PG/QG/VG and bus VM/VA are bounded operating variables. The original
% OPF input types, reference selection, limits, shunts, ratings and controls
% remain part of the exact frozen hardware contract.
m=d.mpc;c=fresh.candidate;
bus_cols=[1 2 3 4 5 6 7 10 11 12 13];gen_cols=setdiff(1:21,[2 3 6]);
prior=fresh.allocation.Pg_prior_mw;sigma=fresh.allocation.Pg_sigma_mw;ng=numel(prior);
expected_cost=[2*ones(ng,1),zeros(ng,2),3*ones(ng,1), ...
    1./sigma.^2,-2*prior./sigma.^2,(prior./sigma).^2];
assert(isstruct(m)&&all(isfield(m,{'baseMVA','bus','branch','gen','gencost'})) ...
    && size(m.bus,1)==size(c.bus,1) && size(m.bus,2)>=13 && size(m.branch,1)==size(c.branch,1) ...
    && size(m.branch,2)>=13 && size(m.gen,1)==size(c.gen,1) && size(m.gen,2)>=21 ...
    && m.baseMVA==c.baseMVA && isequal(m.bus(:,bus_cols),c.bus(:,bus_cols)) ...
    && isequal(m.branch(:,1:13),c.branch(:,1:13)) ...
    && isequal(m.gen(:,gen_cols),c.gen(:,gen_cols)) && isequal(m.gencost,expected_cost), ...
    'replay_ny_only_regional_candidate:FrozenHardware', ...
    'Saved hardware, demand/shunts, status, capability or reference policy differs from the fresh build.');
assert(all(isfinite(m.bus(:,[8 9])),'all')&&all(isfinite(m.gen(:,[2 3 6])),'all'), ...
    'replay_ny_only_regional_candidate:FrozenState','Frozen operating variables must be finite.');
ref=m.bus(m.bus(:,2)==3,1);gm=fresh.allocation.generator_map;
native=startsWith(string(gm.source_device_role),"native_");on=m.gen(:,8)>0;
assert(isscalar(ref)&&ref==fresh.allocation.reference_bus ...
    && any(on&native&m.gen(:,1)==ref&m.gen(:,9)>m.gen(:,10)), ...
    'replay_ny_only_regional_candidate:Reference','Reference must retain declared native balancing capability.');
support=string(d.generator_keys(:))=="RESEARCH2019:Q_SUPPORT:1263:MARCY";
assert(nnz(support)==1&&all(m.gen(support,[2 9 10])==0,'all'), ...
    'replay_ny_only_regional_candidate:Support','Declared reactive support cannot supply active power.');

% Fresh PF and physical audit calculate terminal flows from the frozen input.
% Stored branch-flow columns and previous solver success flags are not proof.
pf_input=without_solver_objects(m);
pf=runpf(pf_input,mpoption('verbose',0,'out.all',0,'pf.enforce_q_lims',1,'pf.tol',1e-10));
% Q-limit enforcement may turn a non-reference PV bus into PQ. Its temporary
% demand bookkeeping must restore the same demand (apart from roundoff), and
% it cannot alter the hardware limits or silently select another reference.
fixed_bus_cols=[1 5 6 7 10 11 12 13];
assert(pf.baseMVA==m.baseMVA && size(pf.bus,1)==size(m.bus,1) ...
    && size(pf.branch,1)==size(m.branch,1) && size(pf.gen,1)==size(m.gen,1) ...
    && isequal(pf.bus(:,fixed_bus_cols),m.bus(:,fixed_bus_cols)) ...
    && max(abs(pf.bus(:,[3 4])-m.bus(:,[3 4])),[],'all')<1e-9 ...
    && isequal(pf.branch(:,1:13),m.branch(:,1:13)) ...
    && isequal(pf.gen(:,gen_cols),m.gen(:,gen_cols)) ...
    && isequal(pf.bus(pf.bus(:,2)==3,1),ref), ...
    'replay_ny_only_regional_candidate:FrozenPFHardware', ...
    'Fresh PF altered a frozen load, shunt, branch, capability, status or reference input.');
a=audit_ny_ac_reference(pf,struct('generator_keys',d.generator_keys,'branch_keys',d.branch_keys));
dp=max(abs(pf.gen(on,2)-m.gen(on,2)));dv=max(abs(pf.bus(:,8)-m.bus(:,8)));
out=struct('result',pf,'audit',a,'passed',a.passed&&dp<1e-3&&dv<1e-4, ...
    'max_dispatch_adjustment_mw',dp,'max_voltage_adjustment_pu',dv, ...
    'source_manifest',n.source_manifest,'candidate_input_manifest',manifest, ...
    'foundation_input_manifest',fm,'foundation_replay_passed',foundation_replay.passed, ...
    'fresh_build_validation',v,'saved_build_validation',saved_validation, ...
    'replacement_zones',zones,'reconstruction_performed',false, ...
    'source_accounting_verified',true,'frozen_hardware_verified',true, ...
    'fresh_pf_hardware_verified',true, ...
    'qualification_scope',"one_assumed_2019_fixed_input_candidate_only",'dlr_ready',false);
assert(out.passed,'replay_ny_only_regional_candidate:Failed', ...
    'Independent fixed-input PF, declared limits, or adjustment gates failed.');
disp(a.summary);
end

function yes=same_foundation(saved,authoritative)
yes=isstruct(saved)&&isfield(saved,'mpc');
if ~yes,return;end
% These MATPOWER handle objects contain transient solver caches. Loading the
% identical bytes twice creates distinct object identities. No cached object
% is an electrical input, and neither is admitted to the independent PF.
saved.mpc=without_solver_objects(saved.mpc);
authoritative.mpc=without_solver_objects(authoritative.mpc);
yes=isequaln(saved,authoritative);
end

function m=without_solver_objects(m)
m=rmfield(m,intersect(fieldnames(m),{'task','om'}));
end

function same_fields(saved,fresh,fields,id)
assert(isstruct(saved)&&all(isfield(saved,fields)), ...
    ['replay_ny_only_regional_candidate:' id],'Saved construction is missing required fields.');
for k=1:numel(fields)
    assert(isequaln(saved.(fields{k}),fresh.(fields{k})), ...
        ['replay_ny_only_regional_candidate:' id], ...
        'Saved construction field %s differs from the independent source build.',fields{k});
end
end
