function out=replay_ny_only_foundation(folder)
%REPLAY_NY_ONLY_FOUNDATION Fresh fixed-input PF, without reconstructing again.
root=fileparts(mfilename('fullpath'));addpath(fullfile(root,'System Matpower Format','NY_Lite'));
if nargin<1,folder=fullfile(root,'output','ny_only_package_a');end
manifest=readtable(fullfile(folder,'reference_input_manifest.csv'),'TextType','string');
assert(height(manifest)==1&&manifest.artifact=="ny_foundation_reference.mat"&& ...
    manifest.sha256==ny_reference_file_sha256(fullfile(folder,'ny_foundation_reference.mat')), ...
    'replay_ny_only_foundation:InputFingerprint','Saved reference input differs from its frozen manifest.');
data=load(fullfile(folder,'ny_foundation_reference.mat'));define_constants;
assert(isequal(data.expected_qualified,true),'replay_ny_only_foundation:Unqualified','Saved input was not qualified.');
n=normalize_perform_ny_source;
assert(isequal(data.source_manifest,n.source_manifest),'replay_ny_only_foundation:SourceManifest','Original source manifest differs.');
m=data.mpc;
g=n.generator_inventory;keep=g.native_generation_member;native=g(keep,:);ng=height(native);
assert(size(m.bus,1)==size(n.source.bus,1)&&size(m.gen,1)==ng+1);
assert(isequal(m.bus(:,[BUS_I GS BS BASE_KV VMIN VMAX]),n.source.bus(:,[BUS_I GS BS BASE_KV VMIN VMAX]))&& ...
    isequal(m.branch(:,1:13),n.source.branch(:,1:13))&& ...
    isequal(m.gen(1:ng,[GEN_BUS PMIN PMAX QMIN QMAX GEN_STATUS]),n.source.gen(keep,[GEN_BUS PMIN PMAX QMIN QMAX GEN_STATUS]))&& ...
    isequal(string(data.generator_keys(:)),[string(native.device_key);"RESEARCH2019:Q_SUPPORT:1263:MARCY"])&& ...
    isequal(string(data.branch_keys(:)),string(n.branch_inventory.device_key))&& ...
    isequal(m.gen(end,[GEN_BUS PMIN PMAX QMIN QMAX GEN_STATUS]),[1263 0 0 -900 900 1])&& ...
    isequal(m.bus(m.bus(:,BUS_TYPE)==REF,BUS_I),847), ...
    'replay_ny_only_foundation:FrozenHardware','Frozen source hardware, capability, support or reference policy differs.');
assert(isequal(m.bus(:,BUS_I),data.gross_boundary_ledger.source_bus));
l=data.gross_boundary_ledger;
assert(isequal([l.pd_gross_mw l.qd_gross_mvar],n.source.bus(:,[PD QD])), ...
    'replay_ny_only_foundation:GrossLoad','Original gross loads differ.');
b=data.boundary_register;external=g(g.source_device_role=="external_boundary_proxy",:);
[known,gi]=ismember(string(b.device_key),string(external.device_key));
assert(height(b)==height(external)&&all(known)&&numel(unique(gi))==height(external)&& ...
    isequal(b.source_gen_row,external.source_gen_row(gi))&& ...
    isequal(b.source_bus,external.source_bus(gi))&& ...
    isequal(b.canonical_status,external.canonical_status(gi))&& ...
    all(b.source_device_role=="external_boundary_proxy")&&all(b.is_external_exchange)&& ...
    all(b.p_injection_mw(b.canonical_status<=0)==0&b.q_injection_mvar(b.canonical_status<=0)==0), ...
    'replay_ny_only_foundation:BoundaryIdentity','Boundary identities, roles or statuses differ from source.');
[found,pos]=ismember(b.source_bus,m.bus(:,BUS_I));assert(all(found));
bp=accumarray(pos,b.p_injection_mw,[size(m.bus,1) 1]);bq=accumarray(pos,b.q_injection_mvar,[size(m.bus,1) 1]);
assert(isequal(bp,l.p_boundary_mw)&&isequal(bq,l.q_boundary_mvar), ...
    'replay_ny_only_foundation:BoundaryLedger','Declared fixed boundary schedules differ from effective loads.');
assert(max(abs(m.bus(:,PD)+l.p_boundary_mw-l.pd_gross_mw))<1e-9&& ...
    max(abs(m.bus(:,QD)+l.q_boundary_mvar-l.qd_gross_mvar))<1e-9,'Frozen gross/boundary accounting mismatch.');
pf=runpf(m,mpoption('verbose',0,'out.all',0,'pf.enforce_q_lims',1,'pf.tol',1e-10));
a=audit_ny_ac_reference(pf,struct('generator_keys',data.generator_keys,'branch_keys',data.branch_keys));
on=m.gen(:,GEN_STATUS)>0;pg=max(abs(pf.gen(on,PG)-m.gen(on,PG)));vm=max(abs(pf.bus(:,VM)-m.bus(:,VM)));
out=struct('result',pf,'audit',a,'max_dispatch_adjustment_mw',pg,'max_voltage_adjustment_pu',vm, ...
    'passed',a.passed&&pg<1e-3&&vm<1e-4,'source_manifest',data.source_manifest);
assert(out.passed,'replay_ny_only_foundation:Failed','Independent fixed-input reference replay failed.');
disp(a.summary);
end
