function out=replay_compact_npcc_ny_testbed(folder)
%REPLAY_COMPACT_NPCC_NY_TESTBED Independent compact benchmark input replay.
% Rebuild the S7/Phase-0 corridor construction, check its frozen reference,
% rederive NY boundary PQ, and run fresh full and NY power flows. No optimizer
% or Package A operating artifact is used. Qualification is one assumed
% benchmark electrical point, with no thermal or external-response claim.
root=fileparts(mfilename('fullpath'));
addpath(fullfile(root,'System Matpower Format','NY_Lite'));
if nargin<1,folder=fullfile(root,'output','compact_npcc_ny');end
file=fullfile(folder,'compact_npcc_ny_reference.mat');
manifest_path=fullfile(folder,'compact_input_manifest.csv');
assert(isfile(file)&&isfile(manifest_path), ...
    'replay_compact_npcc_ny_testbed:InputFingerprint','Frozen input or manifest is missing.');
manifest=readtable(manifest_path,'TextType','string');
assert(all(ismember({'artifact','sha256'},manifest.Properties.VariableNames)) && height(manifest)==1 ...
    && manifest.artifact=="compact_npcc_ny_reference.mat" ...
    && manifest.sha256==ny_reference_file_sha256(file), ...
    'replay_compact_npcc_ny_testbed:InputFingerprint','Frozen input differs from its manifest.');
d=load(file);
assert(all(isfield(d,{'mpc','full_reference','build','assembly','source_manifest','expected_qualified'})), ...
    'replay_compact_npcc_ny_testbed:Schema','Required replay inputs are missing.');
assert(isequal(d.expected_qualified,true), ...
    'replay_compact_npcc_ny_testbed:Unqualified','Saved compact input was not qualified.');

fresh=build_compact_npcc_corridors(struct('write_outputs',false));
assert(fresh.validation.pass,'replay_compact_npcc_ny_testbed:FreshBuild','Fresh construction failed.');
assert(isequal(d.source_manifest,fresh.source_manifest), ...
    'replay_compact_npcc_ny_testbed:SourceManifest','Pinned source manifest differs.');
% Absolute checkout paths and transient solver objects are not source inputs.
same_fields(d.build,fresh,{'source_manifest','bus_map','physical_branch_register', ...
    'source_branch_map','parent_branch_disposition','source_device_exclusion_register', ...
    'source_connection_omission_register', ...
    'local_identity_tests','functional_replacement_comparison','ny_bus_ids','ny_bus_mask', ...
    'ny_branch_mask','ny_generator_mask','branch_keys','generator_keys','retired_parent_rows', ...
    'power_scale','electrical_baseline_qualified','dlr_ready'},'SourceAccounting');
assert(isfield(d.build,'source_inventory'), ...
    'replay_compact_npcc_ny_testbed:SourceAccounting','Source inventory is missing.');
same_fields(d.build.source_inventory,fresh.source_inventory,{'source','source_manifest', ...
    'canonical_sha256','bus_inventory','branch_inventory','generator_inventory','shunt_inventory', ...
    'control_inventory','shunt_alias_inventory','boundary_reconciliation','unresolved_records', ...
    'source_to_model_mapping','source_immutable','electrical_parameters_modified', ...
    'source_vintage','power_scale'},'SourceAccounting');
for name=["parent","candidate","full_candidate"]
    assert(isfield(d.build,name),'replay_compact_npcc_ny_testbed:FrozenBuild','Saved construction is missing.');
    same_fields(d.build.(name),fresh.(name), ...
        {'version','baseMVA','bus','gen','branch','gencost','bus_name'},'FrozenBuild');
    check_zones(d.build.(name),fresh.(name),'FrozenBuild');
end
assert(numel(unique(fresh.branch_keys))==numel(fresh.branch_keys) && ...
    numel(unique(fresh.generator_keys))==numel(fresh.generator_keys), ...
    'replay_compact_npcc_ny_testbed:KeyMapping','Source identities are not unique.');

full=d.full_reference;
check_hardware(full,fresh.full_candidate,'FullHardware',true);
% The delivered reference uses the declared dispatch-prior objective. It is
% checked for provenance even though a PF does not use cost coefficients.
c=fresh.full_candidate;p=c.gen(:,2);sigma=max(50,.25*(c.gen(:,9)-c.gen(:,10)));ng=size(c.gen,1);
cost=[2*ones(ng,1),zeros(ng,2),3*ones(ng,1),1./sigma.^2,-2*p./sigma.^2,(p./sigma).^2];
assert(isequal(full.gencost,cost),'replay_compact_npcc_ny_testbed:FullHardware', ...
    'Full reference objective differs from the declared benchmark dispatch prior.');
check_zones(full,c,'FullHardware');
same_fields(full,c,{'bus_name'},'FullHardware');
full_audit=audit_ny_ac_reference(full,struct('generator_keys',fresh.generator_keys,'branch_keys',fresh.branch_keys));
assert(full_audit.passed,'replay_compact_npcc_ny_testbed:FullReference', ...
    'Stored full reference fails independently recomputed AC equations or declared limits.');
[full_pf,full_pf_audit,full_dp,full_dv]=fresh_pf(full,fresh.generator_keys,fresh.branch_keys,'FullReplay');

derived=extract_compact_ny_boundary(full,fresh);
same_fields(d.assembly,derived,{'boundary_register','bus_injection_ledger','generator_register', ...
    'branch_map','generator_keys','branch_keys','reference_bus','ny_bus_mask','full_gen_rows', ...
    'full_branch_rows','boundary_response_equivalence_established','electrical_baseline_qualified', ...
    'dlr_ready'},'BoundaryAccounting');
assert(isfield(d.assembly,'candidate'),'replay_compact_npcc_ny_testbed:BoundaryAccounting', ...
    'Saved NY assembly candidate is missing.');
same_fields(d.assembly.candidate,derived.candidate, ...
    {'version','baseMVA','bus','gen','branch','gencost','bus_name','userdata'},'BoundaryAccounting');

m=d.mpc;check_hardware(m,derived.candidate,'NYHardware',false);
same_fields(m,derived.candidate,{'gencost','bus_name','userdata'},'NYHardware');
contract=compact_npcc_model_contract(m);
% A NY PF may make tiny slack/reactive adjustments, but cannot quietly
% redispatch the fixed full-reference benchmark before it is replayed.
assembly_dp=max(abs(m.gen(:,2)-derived.candidate.gen(:,2)));
assembly_dv=max(abs(m.bus(:,8)-derived.candidate.bus(:,8)));
assert(assembly_dp<1e-3 && assembly_dv<1e-4, ...
    'replay_compact_npcc_ny_testbed:NYOperatingState', ...
    'Saved NY dispatch or voltage differs materially from the matched full reference.');
[pf,a,dp,dv]=fresh_pf(m,derived.generator_keys,derived.branch_keys,'NYReplay');
out=struct('result',pf,'audit',a,'full_reference_result',full_pf, ...
    'full_reference_audit',full_audit,'full_reference_replay_audit',full_pf_audit, ...
    'passed',true,'full_reference_replay_passed',true, ...
    'max_dispatch_adjustment_mw',dp,'max_voltage_adjustment_pu',dv, ...
    'full_max_dispatch_adjustment_mw',full_dp,'full_max_voltage_adjustment_pu',full_dv, ...
    'max_assembly_dispatch_difference_mw',assembly_dp,'max_assembly_voltage_difference_pu',assembly_dv, ...
    'source_manifest',fresh.source_manifest,'compact_input_manifest',manifest, ...
    'fresh_build_validation',fresh.validation,'source_accounting_verified',true, ...
    'frozen_hardware_verified',true,'fresh_pf_hardware_verified',true, ...
    'boundary_accounting_verified',true,'boundary_register',derived.boundary_register, ...
    'bus_injection_ledger',derived.bus_injection_ledger,'model_contract',contract, ...
    'reconstruction_performed',false,'optimizer_called',false,'package_a_dependency',false, ...
    'qualification_scope',"one_assumed_NPCC_benchmark_fixed_input_electrical_point", ...
    'boundary_response_equivalence_established',false,'contemporary_validated',false,'dlr_ready',false);
disp(a.summary);
end

function check_hardware(m,c,id,allow_q_limited_type)
assert(isstruct(m)&&all(isfield(m,{'version','baseMVA','bus','gen','branch','gencost'})) ...
    && ~any(isfield(m,{'userfcn','A','dcline'})), ...
    ['replay_compact_npcc_ny_testbed:' id],'Unsupported or missing electrical inputs.');
bc=[1 3 4 5 6 7 10 11 12 13];gc=setdiff(1:21,[2 3 6]);
assert(isequal(m.version,c.version)&&m.baseMVA==c.baseMVA ...
    && size(m.bus,1)==size(c.bus,1)&&size(m.bus,2)>=13 ...
    && size(m.gen,1)==size(c.gen,1)&&size(m.gen,2)>=21 ...
    && size(m.branch,1)==size(c.branch,1)&&size(m.branch,2)>=13 ...
    && isequal(m.bus(:,bc),c.bus(:,bc))&&isequal(m.gen(:,gc),c.gen(:,gc)) ...
    && isequal(m.branch(:,1:13),c.branch(:,1:13)), ...
    ['replay_compact_npcc_ny_testbed:' id], ...
    'Frozen demand, shunts, branch parameters, status, capability, or bus identities differ.');
types=m.bus(:,2)==c.bus(:,2);
if allow_q_limited_type
    % Q-limit enforcement is permitted only for a former PV bus with every
    % online regulating record at a declared Q limit. REF cannot move.
    changed=find(~types);
    for k=changed(:)'
        at=m.gen(:,1)==m.bus(k,1)&m.gen(:,8)>0;
        qbound=abs(m.gen(at,3)-m.gen(at,4))<=1e-3|abs(m.gen(at,3)-m.gen(at,5))<=1e-3;
        types(k)=c.bus(k,2)==2&&m.bus(k,2)==1&&any(at)&&all(qbound);
    end
end
assert(all(types),'replay_compact_npcc_ny_testbed:ReferencePolicy','Bus type or reference policy changed.');
assert(all(isfinite(m.bus(:,[8 9])),'all')&&all(isfinite(m.gen(:,[2 3 6])),'all'), ...
    'replay_compact_npcc_ny_testbed:FrozenState','Operating variables must be finite.');
end

function [pf,a,dp,dv]=fresh_pf(m,gkeys,bkeys,id)
% Solver objects are transient; custom electrical extensions were rejected.
m=rmfield(m,intersect(fieldnames(m),{'task','om'}));
pf=runpf(m,mpoption('verbose',0,'out.all',0,'pf.enforce_q_lims',1,'pf.tol',1e-10));
bc=[1 5 6 7 10 11 12 13];gc=setdiff(1:21,[2 3 6]);
assert(pf.baseMVA==m.baseMVA&&size(pf.bus,1)==size(m.bus,1) ...
    && size(pf.gen,1)==size(m.gen,1)&&size(pf.branch,1)==size(m.branch,1) ...
    && isequal(pf.bus(:,bc),m.bus(:,bc)) ...
    && max(abs(pf.bus(:,[3 4])-m.bus(:,[3 4])),[],'all')<1e-9 ...
    && isequal(pf.gen(:,gc),m.gen(:,gc))&&isequal(pf.branch(:,1:13),m.branch(:,1:13)) ...
    && isequal(pf.bus(pf.bus(:,2)==3,1),m.bus(m.bus(:,2)==3,1)), ...
    ['replay_compact_npcc_ny_testbed:' id], ...
    'Fresh PF changed a frozen load, shunt, branch, capability, status, or reference.');
a=audit_ny_ac_reference(pf,struct('generator_keys',gkeys,'branch_keys',bkeys));
on=m.gen(:,8)>0;dp=max(abs(pf.gen(on,2)-m.gen(on,2)));dv=max(abs(pf.bus(:,8)-m.bus(:,8)));
assert(a.passed&&dp<1e-3&&dv<1e-4,['replay_compact_npcc_ny_testbed:' id], ...
    'Fresh PF fails declared physical limits or requires excessive dispatch/voltage adjustment.');
end

function check_zones(saved,fresh,id)
assert(isfield(saved,'userdata')&&isfield(saved.userdata,'nyiso_physical_zone') ...
    && isequal(saved.userdata.nyiso_physical_zone,fresh.userdata.nyiso_physical_zone), ...
    ['replay_compact_npcc_ny_testbed:' id],'Physical zone attribution changed.');
if isfield(fresh.userdata,'compact_npcc')
    same_fields(saved.userdata,fresh.userdata,{'compact_npcc'},id);
end
end

function same_fields(saved,fresh,fields,id)
assert(isstruct(saved)&&all(isfield(saved,fields)), ...
    ['replay_compact_npcc_ny_testbed:' id],'Saved construction is missing required fields.');
for k=1:numel(fields)
    assert(isequaln(saved.(fields{k}),fresh.(fields{k})), ...
        ['replay_compact_npcc_ny_testbed:' id], ...
        'Saved field %s differs from the independent construction.',fields{k});
end
end
