function outputs = run_handoff_reproduction(options)
%RUN_HANDOFF_REPRODUCTION Rebuild and verify the NPCC-preserving hierarchy.
%   Run from the package root:
%       outputs = run_handoff_reproduction;
%
%   The default path regenerates public targets from the included cache,
%   reruns the legacy S6/S7 regressions, applies ratings-only Phase 0 to the
%   full S7 parent, and validates the unpromoted Phase 1A S13 candidate's
%   structural provenance. Set run_s8_operational_closure=true to
%   rerun the iterative AC dispatch diagnostic. The S8.1 capability certificate
%   S9a reactive-control diagnostic, S9b feasibility restoration, and the
%   S10a control-preserving PERFORM benchmark can be enabled independently.
%   S8.1/S9a/S9b refresh their S8 prerequisite. Set
%   run_full_calibration=true to
%   rerun the broad 226-candidate S7 parameter sweep (several minutes).
%   S12 remains a reference oracle and is not promoted by this runner.

if nargin < 1, options = struct(); end
if ~isfield(options, 'rebuild_public_targets'), options.rebuild_public_targets = true; end
if ~isfield(options, 'run_full_calibration'), options.run_full_calibration = false; end
if ~isfield(options, 'run_s8_operational_closure')
    options.run_s8_operational_closure = false;
end
if ~isfield(options, 'run_s8_1_capability_certificate')
    options.run_s8_1_capability_certificate = false;
end
if ~isfield(options, 'run_s9a_q_support_diagnostic')
    options.run_s9a_q_support_diagnostic = false;
end
if ~isfield(options, 'run_s9b_feasibility_restoration')
    options.run_s9b_feasibility_restoration = false;
end
if ~isfield(options, 'run_s9b_reference_audit')
    options.run_s9b_reference_audit = false;
end
if ~isfield(options, 'run_s10a_control_benchmark')
    options.run_s10a_control_benchmark = false;
end
if ~isfield(options, 'run_s13_phase1a_smoke')
    options.run_s13_phase1a_smoke = true;
end
if ~isfield(options, 'run_s12_reference_comparison')
    options.run_s12_reference_comparison = false;
end
if options.run_s12_reference_comparison
    error('run_handoff_reproduction:S12PairedComparisonNotImplemented', ...
        ['The paired S12/S13 same-snapshot comparison is not implemented. ' ...
        'The option is rejected rather than silently returning a standalone ' ...
        'S12 refresh as a comparison.']);
end

root = fileparts(mfilename('fullpath'));
case_dir = fullfile(root, 'System Matpower Format');
helper_dir = fullfile(case_dir, 'NY_Lite');
addpath(root); addpath(case_dir); addpath(helper_dir);

if options.rebuild_public_targets
    public = build_nyiso_public_targets;
    scales = build_s4_interface_objective_scales;
else
    public = struct();
    scales = struct();
end

targets = readtable(fullfile(helper_dir, 'nyiso_public_interface_targets.csv'), ...
    'TextType', 'string', 'VariableNamingRule', 'preserve');
assert(height(targets) == 42, 'Expected 42 public target rows (7 interfaces x 6 scenarios).');
assert(numel(unique(targets.interface_name)) == 7, 'Expected seven public interfaces.');

s6 = run_s6_nyiso_net_injection_pf_benchmark;
assert(s6.scenario_count == 6 && s6.pf_success_count == 6, ...
    'S6 standard PF must converge for all six scenarios.');

direct = struct('gl_scales', 1, 'pv_wood_scales', 1, ...
    'wood_millwood_scales', 1, 'b_fractions', 1, ...
    'grid_file', fullfile(helper_dir, 's7_perform_direct_grid.csv'), ...
    'run_file', fullfile(helper_dir, 's7_perform_direct_pf_runs.csv'), ...
    'residual_file', fullfile(helper_dir, 's7_perform_direct_all_residuals.csv'), ...
    'summary_file', fullfile(helper_dir, 's7_perform_direct_comparison_summary.csv'), ...
    'selected_run_file', fullfile(helper_dir, 's7_perform_direct_pf_results.csv'), ...
    'selected_residual_file', fullfile(helper_dir, 's7_perform_direct_interface_residuals.csv'), ...
    'selected_parameter_file', fullfile(helper_dir, 's7_perform_direct_parameters.csv'), ...
    'selected_tie_file', fullfile(helper_dir, 's7_perform_direct_branch_parameters.csv'), ...
    'q_diagnostic_file', fullfile(helper_dir, 's7_perform_direct_q_diagnostics.csv'));
s7 = run_s7_seven_interface_perform_tieline_calibration(direct);
assert(s7.pf_run_count == 12 && s7.pf_success_count == 12, ...
    'Current and direct-PERFORM standard PF runs must all converge.');

mpc = loadcase('npcc_ny_lite_s7_seven_interface_perform_direct_candidate');
assert(size(mpc.bus, 1) == 143 && size(mpc.branch, 1) == 246 && ...
    size(mpc.gen, 1) == 62, 'Unexpected recommended S7 case dimensions.');

% Phase 0 must be topology-neutral and ratings-only by default.
[phase0_parent, phase0_report] = apply_ny_core_phase0_corrections(mpc, ...
    struct('fit_reactance', false, 'verbose', false));
assert(isequal(size(phase0_parent.bus), size(mpc.bus)) && ...
    isequal(size(phase0_parent.branch), size(mpc.branch)) && ...
    isequal(phase0_parent.bus(:, 1), mpc.bus(:, 1)) && ...
    isequal(phase0_parent.branch(:, 1:2), mpc.branch(:, 1:2)), ...
    'Ratings-only Phase 0 changed S7 topology or row identity.');
assert(max(abs(phase0_parent.branch(:, 3:5) - mpc.branch(:, 3:5)), [], 'all') == 0, ...
    'Ratings-only Phase 0 changed branch R/X/B.');

s13_candidate = loadcase('npcc_ny_lite_s13_npcc_augmented_2019');
s13_validation = validate_s13_structural_preservation(struct( ...
    'candidate_case', s13_candidate, ...
    'candidate_name', 'npcc_ny_lite_s13_npcc_augmented_2019', ...
    'write_outputs', false, 'fail_on_structural', true));
assert(s13_validation.all_structural_gates_pass, ...
    'The pending S13 candidate failed a structural preservation gate.');
assert(~s13_validation.promotion_eligible, ...
    'Phase 1A must remain unpromoted until residual and operating gates pass.');

s13_smoke = struct();
if options.run_s13_phase1a_smoke
    s13_smoke = validate_s13_phase1a_smoke(struct('write_outputs', false));
    assert(s13_smoke.standard_pf_both_pass, ...
        'The inherited-snapshot standard PF smoke test must pass for S7 and S13.');
end

full_calibration = struct();
if options.run_full_calibration
    full_calibration = run_s7_seven_interface_perform_tieline_calibration;
end

s8 = struct();
needs_s8 = options.run_s8_operational_closure || ...
    options.run_s8_1_capability_certificate || ...
    options.run_s9a_q_support_diagnostic || ...
    options.run_s9b_feasibility_restoration || options.run_s9b_reference_audit;
if needs_s8
    s8 = run_s8_iterative_ac_injection_closure;
    assert(s8.scenario_count == 6 && s8.standard_pf_success_count == 6, ...
        'S8 standard PF must converge for all six scenarios.');
end

voltage_references = struct();
if options.run_s9b_feasibility_restoration || options.run_s9b_reference_audit
    voltage_references = build_ny_voltage_reference_sets;
    provenance = voltage_references.s1_provenance;
    refs = voltage_references.references;
    perform_controls = voltage_references.perform_controls;
    ce_s1 = refs(refs.reference_set == "S1_OPF_SOLVED_REFERENCE" & ...
        refs.model_bus == 78, :);
    ce_original = refs(refs.reference_set == "ORIGINAL_NPCC_VG_REFERENCE" & ...
        refs.model_bus == 78, :);
    assert(height(provenance) == 48 && all(provenance.changed), ...
        'All 48 S1 VG fields should be identified as OPF-solved changes.');
    assert(height(ce_s1) == 1 && height(ce_original) == 1 && ...
        abs(ce_s1.voltage_reference_pu - 0.974721326) < 1e-8 && ...
        abs(ce_original.voltage_reference_pu - 1.02) < 1e-8, ...
        'CE UG voltage-reference provenance changed unexpectedly.');
    online_internal_controls = perform_controls.status > 0 & ...
        perform_controls.mapped_to_nyiso_zone;
    assert(height(perform_controls) == 649 && ...
        sum(online_internal_controls) == 417 && ...
        numel(unique(perform_controls.source_bus(online_internal_controls))) == 179 && ...
        sum(online_internal_controls & perform_controls.reactive_only_QS) == 34 && ...
        sum(online_internal_controls & ...
            perform_controls.positive_active_capability) == 381 && ...
        sum(online_internal_controls & perform_controls.fixed_negative_active) == 2 && ...
        sum(online_internal_controls & perform_controls.remote_regulation) == 1 && ...
        sum(isfinite(perform_controls.converted_gen_index)) == 615 && ...
        all(perform_controls.regulated_bus_found(online_internal_controls)), ...
        'PERFORM RAW control extraction or device classification changed unexpectedly.');
    assert(~any(contains(perform_controls.source_file, ":")), ...
        'Packaged voltage-control provenance must use relative paths.');
end

s9b = struct();
if options.run_s9b_feasibility_restoration
    s9b = run_s9b_ac_feasibility_restoration;
    restoration = s9b.summary;
    at_080 = restoration(abs(restoration.reference_weight - 0.80) < 1e-9, :);
    at_100 = restoration(abs(restoration.reference_weight - 1.00) < 1e-9, :);
    assert(height(restoration) == 27 && all(restoration.opf_success), ...
        'S9b must return 27 successfully solved restoration cases.');
    assert(all(string(at_080.termination_class) == "hard_feasible_zero_slack"), ...
        'S9b should find hard feasibility at S1 reference weight 0.80.');
    assert(all(string(at_100.termination_class) == "restored_nonzero_slack"), ...
        'S9b should quantify nonzero restoration slack at S1 reference weight 1.00.');
    assert(all(restoration.branch_slack_mva < 1e-6), ...
        'S9b should not require branch-flow restoration slack.');
    assert(all(restoration.requested_reference_bus_count == ...
        restoration.applied_reference_bus_count + ...
        restoration.skipped_pq_reference_bus_count), ...
        'Every requested S9b reference must be applied or identified as PQ-skipped.');
    assert(max(restoration.max_ac_balance_component_residual_mw_or_mvar) < 0.01 && ...
        max(restoration.max_complex_power_mismatch_mva) < 0.01, ...
        'S9b AC balance residuals exceed the numerical acceptance threshold.');
end

s9b_audit = struct();
if options.run_s9b_reference_audit
    s9b_audit = run_s9b_reference_continuation_audit;
    brackets = s9b_audit.onset_brackets;
    refined = brackets(brackets.audit_group == "S1_REFINED_BIDIRECTIONAL" & ...
        brackets.boundary_q_mode == "present_limited_q", :);
    assert(height(s9b_audit.summary) == 182 && ...
        all(s9b_audit.summary.opf_success), ...
        'S9b reference/continuation audit must solve all 182 cases.');
    assert(height(refined) == 1 && ...
        abs(refined.highest_weight_with_any_hard_success - 0.8075) < 1e-9 && ...
        abs(refined.lowest_weight_with_any_nonzero_restoration - 0.8100) < 1e-9, ...
        'S9b refined S1 numerical-reference onset bracket changed.');
    assert(all(s9b_audit.summary.requested_reference_bus_count == ...
        s9b_audit.summary.applied_reference_bus_count + ...
        s9b_audit.summary.skipped_pq_reference_bus_count), ...
        'Every audited reference must be applied or identified as PQ-skipped.');
    assert(max(s9b_audit.summary.max_ac_balance_component_residual_mw_or_mvar) < 0.01 && ...
        max(s9b_audit.summary.max_complex_power_mismatch_mva) < 0.01, ...
        'S9b audit AC balance residuals exceed the numerical acceptance threshold.');
end

s8_1 = struct();
if options.run_s8_1_capability_certificate
    s8_1 = run_s8_1_capability_feasibility_certificate;
    cap = s8_1.summary;
    strict_08 = cap(string(cap.envelope_name) == "ABC_CAP_0p8" & ...
        string(cap.solution_type) == "strict_min_eta", :);
    strict_10 = cap(string(cap.envelope_name) == "ABC_CAP_1" & ...
        string(cap.solution_type) == "strict_min_eta", :);
    assert(height(strict_08) == 1 && strict_08.minimum_eta > 1, ...
        'S8.1 must show local linear incompatibility under the inherited 0.8 cap.');
    assert(height(strict_10) == 1 && strict_10.minimum_eta <= 1, ...
        'S8.1 must recover linear compatibility at the 1.0 cap.');
end

s9a = struct();
if options.run_s9a_q_support_diagnostic
    s9a = run_s9a_minimum_q_support_diagnostic;
    qsummary = s9a.summary;
    free_vm = qsummary(string(qsummary.case_id) == ...
        "PERFORM_Q_TEMP_SUPPORT_FREE_VM", :);
    vg_090 = qsummary(string(qsummary.case_id) == ...
        "PERFORM_Q_TEMP_SUPPORT_VG0p90", :);
    fixed_vg = qsummary(string(qsummary.case_id) == ...
        "PERFORM_Q_TEMP_SUPPORT_FIXED_VG_IPOPT", :);
    assert(height(free_vm) == 1 && free_vm.opf_success == 1 && ...
        free_vm.absolute_q_support_mvar < 1e-3, ...
        'S9a free-voltage OPF should require no temporary Q support.');
    assert(height(vg_090) == 1 && vg_090.opf_success == 1 && ...
        vg_090.absolute_q_support_mvar > 800, ...
        'S9a 0.90 voltage-setpoint continuation result is inconsistent.');
    assert(height(fixed_vg) == 1 && ...
        ismember(string(fixed_vg.termination_class), ...
        ["feasible_success", "solver_nonconvergence", "solver_exception"]), ...
        'S9a fixed-voltage run must have an explicit termination class.');
end

s10a = struct();
if options.run_s10a_control_benchmark
    s10a = run_s10a_perform_same_snapshot_benchmark;
    summary = s10a.summary;
    metric = @(name) summary.value(summary.metric == string(name));
    control_map = s10a.build_report.mapping_outputs.control_mapping;
    pq_audit = s10a.build_report.mapping_outputs.pq_audit;
    converted = control_map.converted_gen_index(isfinite(control_map.converted_gen_index));
    assert(s10a.reduced_pf.success == 1 && ...
        metric('reduced_voltage_violation_count') == 0 && ...
        metric('reduced_q_violation_count') == 0 && ...
        metric('reduced_branch_overload_count') == 0, ...
        'S10a reduced PF must be hard-feasible under the benchmark controls.');
    assert(metric('voltage_rmse_pu') < 0.01 && ...
        metric('voltage_max_error_pu') < 0.03, ...
        'S10a retained/pilot voltage benchmark changed unexpectedly.');
    assert(height(control_map) == 649 && numel(converted) == 615 && ...
        numel(unique(converted)) == 615 && ...
        sum(control_map.raw_converted_status_mismatch) == 6 && ...
        sum(control_map.snapshot_effective_status > 0 & ...
            strlength(control_map.source_zone) > 0) == 411, ...
        'S10a source-control identity or status mapping changed unexpectedly.');
    assert(height(pq_audit) == 10 && ...
        all(pq_audit.s10a_diagnostic_pv_enabled), ...
        'S10a must audit all ten previously skipped PQ control locations.');
    fixed = s10a.boundary_q_sensitivity( ...
        s10a.boundary_q_sensitivity.boundary_q_mode == "fixed_source_q", :);
    limited = s10a.boundary_q_sensitivity( ...
        s10a.boundary_q_sensitivity.boundary_q_mode == "limited_source_q", :);
    assert(fixed.pf_success == 1 && fixed.external_q_total_abs_error_mvar < 1e-6 && ...
        limited.pf_success == 1 && limited.external_q_total_abs_error_mvar > 1000, ...
        'S10a boundary-Q mode sensitivity changed unexpectedly.');
end

outputs = struct('root', root, 'public_targets', public, ...
    'objective_scales', scales, 's6', s6, 's7_direct_validation', s7, ...
    'phase0_structural_parent', phase0_parent, ...
    'phase0_report', phase0_report, ...
    's13_candidate', s13_candidate, ...
    's13_validation', s13_validation, ...
    's13_phase1a_smoke', s13_smoke, ...
    'full_calibration', full_calibration, 's8_operational_closure', s8, ...
    'voltage_references', voltage_references, ...
    's8_1_capability_certificate', s8_1, ...
    's9a_q_support_diagnostic', s9a, ...
    's9b_feasibility_restoration', s9b, ...
    's9b_reference_audit', s9b_audit, ...
    's10a_control_benchmark', s10a, ...
    'structural_parent', 'npcc_ny_lite_s7_seven_interface_perform_direct_candidate', ...
    'structural_parent_size', [size(mpc.bus, 1), size(mpc.branch, 1), size(mpc.gen, 1)], ...
    'promoted_operating_case', 'pending_s13_npcc_augmented_2019', ...
    'diagnostic_reduced_case', 'npcc_ny_lite_s11_dlr_pf_base', ...
    'reference_oracle', 'npcc_ny_lite_s12_perform_retention_core', ...
    'source_dataset', 'full_PERFORM_2019_case', ...
    's12_reference_comparison', struct('status', ...
        'pending_paired_s13_s12_implementation'), ...
    'reproduction_status', ...
        'structural_pass_s13_operating_and_promotion_gates_incomplete');
fprintf(['Structural handoff reproduction passed: S7 structural parent = %d buses, ' ...
    '%d branches, %d generators; S13 Phase 1A candidate = %d/%d/%d and ' ...
    'remains unpromoted.\n'], size(mpc.bus, 1), size(mpc.branch, 1), ...
    size(mpc.gen, 1), s13_validation.candidate_size(1), ...
    s13_validation.candidate_size(2), s13_validation.candidate_size(3));
if options.run_s13_phase1a_smoke
    fprintf(['S13 inherited-snapshot smoke: standard PF passes 2/2; ' ...
        'Q-limit PF passes %d/2. This is a diagnostic limitation, not a ' ...
        'promotion gate or a 2019 validation result.\n'], ...
        sum(s13_smoke.summary.q_limit_pf_success));
end
end
