function outputs = run_handoff_reproduction(options)
%RUN_HANDOFF_REPRODUCTION Rebuild and verify the NPCC/NYISO hierarchy.
%   Run from the package root:
%       outputs = run_handoff_reproduction;
%
%   The default path regenerates public targets from the included cache,
%   reruns the legacy S6/S7 regressions, applies ratings-only Phase 0 to the
%   full S7 provenance case, and validates the cumulative Phase 1B S13-FULL
%   construction parent's structural provenance. S14-NYISO is the pending
%   promoted DLR operating model and is not built by this runner. Set
%   run_s8_operational_closure=true to
%   rerun the iterative AC dispatch diagnostic. The S8.1 capability certificate
%   S9a reactive-control diagnostic, S9b feasibility restoration, and the
%   S10a control-preserving PERFORM benchmark can be enabled independently.
%   S8.1/S9a/S9b refresh their S8 prerequisite. Set
%   run_full_calibration=true to
%   rerun the broad 226-candidate S7 parameter sweep (several minutes).
%   S12 remains a reference oracle and is not promoted by this runner.

if nargin < 1, options = struct(); end
if ~isfield(options, 'rebuild_public_targets'), options.rebuild_public_targets = true; end
if ~isfield(options, 'run_full_calibration'), options.run_full_calibration = false; end
if ~isfield(options, 'run_s8_operational_closure')
    options.run_s8_operational_closure = false;
end
if ~isfield(options, 'run_s8_1_capability_certificate')
    options.run_s8_1_capability_certificate = false;
end
if ~isfield(options, 'run_s9a_q_support_diagnostic')
    options.run_s9a_q_support_diagnostic = false;
end
if ~isfield(options, 'run_s9b_feasibility_restoration')
    options.run_s9b_feasibility_restoration = false;
end
if ~isfield(options, 'run_s9b_reference_audit')
    options.run_s9b_reference_audit = false;
end
if ~isfield(options, 'run_s10a_control_benchmark')
    options.run_s10a_control_benchmark = false;
end
if ~isfield(options, 'run_s13_phase1a_smoke')
    options.run_s13_phase1a_smoke = true;
end
if ~isfield(options, 'run_s13_phase1a_oracle_preflight')
    options.run_s13_phase1a_oracle_preflight = true;
end
if ~isfield(options, 'run_s13_phase1b_validation')
    options.run_s13_phase1b_validation = true;
end
if ~isfield(options, 'run_s12_reference_comparison')
    options.run_s12_reference_comparison = false;
end
if options.run_s12_reference_comparison
    error('run_handoff_reproduction:S12PairedComparisonNotImplemented', ...
        ['The requested paired S12/S13-FULL diagnostic is not executable ' ...
        'because the common full-NPCC operating baseline remains fail-closed. ' ...
        'Use the default S13.1 preflight for the exact local identity and ' ...
        'readiness evidence.']);
end

root = fileparts(mfilename('fullpath'));
case_dir = fullfile(root, 'System Matpower Format');
helper_dir = fullfile(case_dir, 'NY_Lite');
addpath(root); addpath(case_dir); addpath(helper_dir);
hierarchy_policy = readtable(fullfile(root, 'LATEST_MODEL_CONFIGURATION.csv'), ...
    'TextType', 'string', 'VariableNamingRule', 'preserve');
assert_unique_policy_row(hierarchy_policy, "model", ...
    "structural_provenance_case", ...
    "npcc_ny_lite_s7_seven_interface_perform_direct_candidate");
assert_unique_policy_row(hierarchy_policy, "model", ...
    "construction_validation_parent", ...
    "npcc_ny_lite_s13_npcc_augmented_2019");
assert_unique_policy_row(hierarchy_policy, "model", ...
    "promoted_operating_case", ...
    "pending_npcc_ny_lite_s14_nyiso_dlr_operating_model");
assert_unique_policy_row(hierarchy_policy, "model", "reference_oracle", ...
    "npcc_ny_lite_s12_perform_retention_core");
assert_unique_policy_row(hierarchy_policy, "s14_nyiso", ...
    "promotion_eligible", "false");

if options.rebuild_public_targets
    public = build_nyiso_public_targets;
    scales = build_s4_interface_objective_scales;
else
    public = struct();
    scales = struct();
end

targets = readtable(fullfile(helper_dir, 'nyiso_public_interface_targets.csv'), ...
    'TextType', 'string', 'VariableNamingRule', 'preserve');
assert(height(targets) == 42, 'Expected 42 public target rows (7 interfaces x 6 scenarios).');
assert(numel(unique(targets.interface_name)) == 7, 'Expected seven public interfaces.');

s6 = run_s6_nyiso_net_injection_pf_benchmark;
assert(s6.scenario_count == 6 && s6.pf_success_count == 6, ...
    'S6 standard PF must converge for all six scenarios.');

direct = struct('gl_scales', 1, 'pv_wood_scales', 1, ...
    'wood_millwood_scales', 1, 'b_fractions', 1, ...
    'grid_file', fullfile(helper_dir, 's7_perform_direct_grid.csv'), ...
    'run_file', fullfile(helper_dir, 's7_perform_direct_pf_runs.csv'), ...
    'residual_file', fullfile(helper_dir, 's7_perform_direct_all_residuals.csv'), ...
    'summary_file', fullfile(helper_dir, 's7_perform_direct_comparison_summary.csv'), ...
    'selected_run_file', fullfile(helper_dir, 's7_perform_direct_pf_results.csv'), ...
    'selected_residual_file', fullfile(helper_dir, 's7_perform_direct_interface_residuals.csv'), ...
    'selected_parameter_file', fullfile(helper_dir, 's7_perform_direct_parameters.csv'), ...
    'selected_tie_file', fullfile(helper_dir, 's7_perform_direct_branch_parameters.csv'), ...
    'q_diagnostic_file', fullfile(helper_dir, 's7_perform_direct_q_diagnostics.csv'));
s7 = run_s7_seven_interface_perform_tieline_calibration(direct);
assert(s7.pf_run_count == 12 && s7.pf_success_count == 12, ...
    'Current and direct-PERFORM standard PF runs must all converge.');

mpc = loadcase('npcc_ny_lite_s7_seven_interface_perform_direct_candidate');
assert(size(mpc.bus, 1) == 143 && size(mpc.branch, 1) == 246 && ...
    size(mpc.gen, 1) == 62, 'Unexpected recommended S7 case dimensions.');
assert(~mpc.userdata.ny_lite.s7_seven_interface_calibration.promotion_eligible, ...
    'S7 must remain ineligible for DLR-model promotion.');
s12_role_check = loadcase('npcc_ny_lite_s12_perform_retention_core');
assert(~s12_role_check.userdata.promotion_eligible, ...
    'S12 must remain an oracle-only case.');

% Phase 0 must be topology-neutral and ratings-only by default.
[phase0_parent, phase0_report] = apply_ny_core_phase0_corrections(mpc, ...
    struct('fit_reactance', false, 'verbose', false));
assert(isequal(size(phase0_parent.bus), size(mpc.bus)) && ...
    isequal(size(phase0_parent.branch), size(mpc.branch)) && ...
    isequal(phase0_parent.bus(:, 1), mpc.bus(:, 1)) && ...
    isequal(phase0_parent.branch(:, 1:2), mpc.branch(:, 1:2)), ...
    'Ratings-only Phase 0 changed S7 topology or row identity.');
assert(max(abs(phase0_parent.branch(:, 3:5) - mpc.branch(:, 3:5)), [], 'all') == 0, ...
    'Ratings-only Phase 0 changed branch R/X/B.');

s13_candidate = loadcase('npcc_ny_lite_s13_npcc_augmented_2019');
s13_validation = validate_s13_structural_preservation(struct( ...
    'candidate_case', s13_candidate, ...
    'candidate_name', 'npcc_ny_lite_s13_npcc_augmented_2019', ...
    'write_outputs', false, 'fail_on_structural', true));
assert(s13_validation.all_structural_gates_pass, ...
    'The S13-FULL construction parent failed a structural preservation gate.');
assert(~s13_validation.promotion_eligible, ...
    'S13-FULL must remain permanently ineligible for DLR-model promotion.');

s13_artifact_consistency = validate_s13_artifact_consistency(struct( ...
    'candidate_case', s13_candidate, 'artifact_dir', helper_dir, ...
    'fail_on_mismatch', true));
assert(s13_artifact_consistency.all_artifacts_match, ...
    'A committed S13 register or structural ledger differs from rebuilt evidence.');
s13_adversarial_validation = test_s13_structural_validator_adversarial(struct( ...
    'write_outputs', false, ...
    'output_file', fullfile(helper_dir, ...
    's13_structural_adversarial_results.csv')));
assert(s13_adversarial_validation.all_expected_gates_observed, ...
    'The S13 adversarial harness did not observe every expected hard-gate failure.');
s12_interface_snapshot_test = test_s12_interface_snapshot_sums(struct( ...
    'verbose', false));
assert(s12_interface_snapshot_test.pass && ...
    s12_interface_snapshot_test.total_east_circuit_count == 8, ...
    'The S12 oracle sidecar is stale or Total East no longer has eight circuits.');

s13_phase1b_local = struct();
s13_phase1b_operator = struct();
s13_phase1b_artifacts = struct();
s13_phase1b_adversarial = struct();
s13_phase1b_smoke = struct();
if options.run_s13_phase1b_validation
    s13_phase1b_local = run_s13_phase1b_local_identity(struct( ...
        's13_case', s13_candidate, 'write_outputs', false, ...
        'fail_on_gate', true, 'verbose', false));
    assert(s13_phase1b_local.pass && ...
        s13_phase1b_local.phase1a_report_exact_match && ...
        s13_phase1b_local.phase1a_physical_rows_bit_identical && ...
        ~s13_phase1b_local.residual_fit_performed && ...
        ~s13_phase1b_local.promotion_performed, ...
        'Phase 1B local identity or Phase 1A immutability failed.');
    s13_phase1b_operator = validate_s13_phase1b_upny_operator(struct( ...
        'candidate_case', s13_candidate, 'write_outputs', false, ...
        'fail_on_gate', true, 'verbose', false));
    assert(s13_phase1b_operator.pass && ...
        ~s13_phase1b_operator.exact_public_operator && ...
        ~s13_phase1b_operator.promotion_eligible, ...
        'The Phase 1B UPNY-ConEd proxy gate or fail-closed role changed.');
    s13_phase1b_artifacts = ...
        validate_s13_phase1b_artifact_consistency(struct( ...
        'candidate_case', s13_candidate, 'artifact_dir', helper_dir, ...
        'write_outputs', false, 'fail_on_mismatch', true, ...
        'verbose', false));
    assert(s13_phase1b_artifacts.all_artifacts_match, ...
        'One or more committed Phase 1B artifacts are stale.');
    s13_phase1b_adversarial = ...
        test_s13_phase1b_validator_adversarial(struct( ...
        'write_outputs', false, 'verbose', false));
    assert(s13_phase1b_adversarial.all_expected_gates_observed, ...
        'A Phase 1B adversarial mutation escaped its expected gate.');
    s13_phase1b_smoke = validate_s13_phase1b_smoke(struct( ...
        'write_outputs', false, 'verbose', false));
    assert(s13_phase1b_smoke.standard_pf_all_pass, ...
        'The inherited-snapshot standard PF must pass through Phase 1B.');
end

s13_oracle_preflight = struct();
s13_oracle_artifacts = struct();
if options.run_s13_phase1a_oracle_preflight
    s13_oracle_preflight = run_s13_phase1a_oracle_comparison(struct( ...
        'write_outputs', false, 'verbose', false, ...
        'fail_on_incomplete', false));
    assert(s13_oracle_preflight.stage_a_pass && ...
        ~s13_oracle_preflight.promotion_eligible && ...
        ~s13_oracle_preflight.electrically_validated, ...
        ['The S13.1 local identity must pass while the unavailable common ' ...
        'system diagnostic remains fail-closed.']);
    s13_oracle_artifacts = ...
        validate_s13_phase1a_oracle_artifact_consistency(struct( ...
        'oracle_result', s13_oracle_preflight, ...
        'artifact_dir', helper_dir, 'fail_on_mismatch', true, ...
        'verbose', false));
    assert(s13_oracle_artifacts.all_artifacts_match, ...
        'One or more committed S13.1 oracle/preflight artifacts are stale.');
end

structural_mask = s13_validation.gates.mandatory_for_structure;
construction_validation_mask = ...
    s13_validation.gates.mandatory_for_construction_qualification & ...
    ~s13_validation.gates.mandatory_for_structure;
s13_gate_counts = struct( ...
    'mandatory_structural_total', nnz(structural_mask), ...
    'mandatory_structural_passed', ...
        nnz(structural_mask & s13_validation.gates.pass), ...
    'construction_validation_total', nnz(construction_validation_mask), ...
    'construction_validation_fail_closed', ...
        nnz(construction_validation_mask & ~s13_validation.gates.pass), ...
    'promotion_only_total', 0, ... % deprecated: S13 has no promotion gates
    'promotion_only_fail_closed', 0);
assert(s13_gate_counts.mandatory_structural_passed == ...
    s13_gate_counts.mandatory_structural_total, ...
    'Not all mandatory S13 structural gates passed.');

s13_smoke = struct();
if options.run_s13_phase1a_smoke
    s13_smoke = validate_s13_phase1a_smoke(struct('write_outputs', false));
    assert(s13_smoke.standard_pf_both_pass, ...
        'The inherited-snapshot standard PF smoke test must pass for S7 and S13.');
end

full_calibration = struct();
if options.run_full_calibration
    full_calibration = run_s7_seven_interface_perform_tieline_calibration;
end

s8 = struct();
needs_s8 = options.run_s8_operational_closure || ...
    options.run_s8_1_capability_certificate || ...
    options.run_s9a_q_support_diagnostic || ...
    options.run_s9b_feasibility_restoration || options.run_s9b_reference_audit;
if needs_s8
    s8 = run_s8_iterative_ac_injection_closure;
    assert(s8.scenario_count == 6 && s8.standard_pf_success_count == 6, ...
        'S8 standard PF must converge for all six scenarios.');
end

voltage_references = struct();
if options.run_s9b_feasibility_restoration || options.run_s9b_reference_audit
    voltage_references = build_ny_voltage_reference_sets;
    provenance = voltage_references.s1_provenance;
    refs = voltage_references.references;
    perform_controls = voltage_references.perform_controls;
    ce_s1 = refs(refs.reference_set == "S1_OPF_SOLVED_REFERENCE" & ...
        refs.model_bus == 78, :);
    ce_original = refs(refs.reference_set == "ORIGINAL_NPCC_VG_REFERENCE" & ...
        refs.model_bus == 78, :);
    assert(height(provenance) == 48 && all(provenance.changed), ...
        'All 48 S1 VG fields should be identified as OPF-solved changes.');
    assert(height(ce_s1) == 1 && height(ce_original) == 1 && ...
        abs(ce_s1.voltage_reference_pu - 0.974721326) < 1e-8 && ...
        abs(ce_original.voltage_reference_pu - 1.02) < 1e-8, ...
        'CE UG voltage-reference provenance changed unexpectedly.');
    online_internal_controls = perform_controls.status > 0 & ...
        perform_controls.mapped_to_nyiso_zone;
    assert(height(perform_controls) == 649 && ...
        sum(online_internal_controls) == 417 && ...
        numel(unique(perform_controls.source_bus(online_internal_controls))) == 179 && ...
        sum(online_internal_controls & perform_controls.reactive_only_QS) == 34 && ...
        sum(online_internal_controls & ...
            perform_controls.positive_active_capability) == 381 && ...
        sum(online_internal_controls & perform_controls.fixed_negative_active) == 2 && ...
        sum(online_internal_controls & perform_controls.remote_regulation) == 1 && ...
        sum(isfinite(perform_controls.converted_gen_index)) == 615 && ...
        all(perform_controls.regulated_bus_found(online_internal_controls)), ...
        'PERFORM RAW control extraction or device classification changed unexpectedly.');
    assert(~any(contains(perform_controls.source_file, ":")), ...
        'Packaged voltage-control provenance must use relative paths.');
end

s9b = struct();
if options.run_s9b_feasibility_restoration
    s9b = run_s9b_ac_feasibility_restoration;
    restoration = s9b.summary;
    at_080 = restoration(abs(restoration.reference_weight - 0.80) < 1e-9, :);
    at_100 = restoration(abs(restoration.reference_weight - 1.00) < 1e-9, :);
    assert(height(restoration) == 27 && all(restoration.opf_success), ...
        'S9b must return 27 successfully solved restoration cases.');
    assert(all(string(at_080.termination_class) == "hard_feasible_zero_slack"), ...
        'S9b should find hard feasibility at S1 reference weight 0.80.');
    assert(all(string(at_100.termination_class) == "restored_nonzero_slack"), ...
        'S9b should quantify nonzero restoration slack at S1 reference weight 1.00.');
    assert(all(restoration.branch_slack_mva < 1e-6), ...
        'S9b should not require branch-flow restoration slack.');
    assert(all(restoration.requested_reference_bus_count == ...
        restoration.applied_reference_bus_count + ...
        restoration.skipped_pq_reference_bus_count), ...
        'Every requested S9b reference must be applied or identified as PQ-skipped.');
    assert(max(restoration.max_ac_balance_component_residual_mw_or_mvar) < 0.01 && ...
        max(restoration.max_complex_power_mismatch_mva) < 0.01, ...
        'S9b AC balance residuals exceed the numerical acceptance threshold.');
end

s9b_audit = struct();
if options.run_s9b_reference_audit
    s9b_audit = run_s9b_reference_continuation_audit;
    brackets = s9b_audit.onset_brackets;
    refined = brackets(brackets.audit_group == "S1_REFINED_BIDIRECTIONAL" & ...
        brackets.boundary_q_mode == "present_limited_q", :);
    assert(height(s9b_audit.summary) == 182 && ...
        all(s9b_audit.summary.opf_success), ...
        'S9b reference/continuation audit must solve all 182 cases.');
    assert(height(refined) == 1 && ...
        abs(refined.highest_weight_with_any_hard_success - 0.8075) < 1e-9 && ...
        abs(refined.lowest_weight_with_any_nonzero_restoration - 0.8100) < 1e-9, ...
        'S9b refined S1 numerical-reference onset bracket changed.');
    assert(all(s9b_audit.summary.requested_reference_bus_count == ...
        s9b_audit.summary.applied_reference_bus_count + ...
        s9b_audit.summary.skipped_pq_reference_bus_count), ...
        'Every audited reference must be applied or identified as PQ-skipped.');
    assert(max(s9b_audit.summary.max_ac_balance_component_residual_mw_or_mvar) < 0.01 && ...
        max(s9b_audit.summary.max_complex_power_mismatch_mva) < 0.01, ...
        'S9b audit AC balance residuals exceed the numerical acceptance threshold.');
end

s8_1 = struct();
if options.run_s8_1_capability_certificate
    s8_1 = run_s8_1_capability_feasibility_certificate;
    cap = s8_1.summary;
    strict_08 = cap(string(cap.envelope_name) == "ABC_CAP_0p8" & ...
        string(cap.solution_type) == "strict_min_eta", :);
    strict_10 = cap(string(cap.envelope_name) == "ABC_CAP_1" & ...
        string(cap.solution_type) == "strict_min_eta", :);
    assert(height(strict_08) == 1 && strict_08.minimum_eta > 1, ...
        'S8.1 must show local linear incompatibility under the inherited 0.8 cap.');
    assert(height(strict_10) == 1 && strict_10.minimum_eta <= 1, ...
        'S8.1 must recover linear compatibility at the 1.0 cap.');
end

s9a = struct();
if options.run_s9a_q_support_diagnostic
    s9a = run_s9a_minimum_q_support_diagnostic;
    qsummary = s9a.summary;
    free_vm = qsummary(string(qsummary.case_id) == ...
        "PERFORM_Q_TEMP_SUPPORT_FREE_VM", :);
    vg_090 = qsummary(string(qsummary.case_id) == ...
        "PERFORM_Q_TEMP_SUPPORT_VG0p90", :);
    fixed_vg = qsummary(string(qsummary.case_id) == ...
        "PERFORM_Q_TEMP_SUPPORT_FIXED_VG_IPOPT", :);
    assert(height(free_vm) == 1 && free_vm.opf_success == 1 && ...
        free_vm.absolute_q_support_mvar < 1e-3, ...
        'S9a free-voltage OPF should require no temporary Q support.');
    assert(height(vg_090) == 1 && vg_090.opf_success == 1 && ...
        vg_090.absolute_q_support_mvar > 800, ...
        'S9a 0.90 voltage-setpoint continuation result is inconsistent.');
    assert(height(fixed_vg) == 1 && ...
        ismember(string(fixed_vg.termination_class), ...
        ["feasible_success", "solver_nonconvergence", "solver_exception"]), ...
        'S9a fixed-voltage run must have an explicit termination class.');
end

s10a = struct();
if options.run_s10a_control_benchmark
    s10a = run_s10a_perform_same_snapshot_benchmark;
    summary = s10a.summary;
    metric = @(name) summary.value(summary.metric == string(name));
    control_map = s10a.build_report.mapping_outputs.control_mapping;
    pq_audit = s10a.build_report.mapping_outputs.pq_audit;
    converted = control_map.converted_gen_index(isfinite(control_map.converted_gen_index));
    assert(s10a.reduced_pf.success == 1 && ...
        metric('reduced_voltage_violation_count') == 0 && ...
        metric('reduced_q_violation_count') == 0 && ...
        metric('reduced_branch_overload_count') == 0, ...
        'S10a reduced PF must be hard-feasible under the benchmark controls.');
    assert(metric('voltage_rmse_pu') < 0.01 && ...
        metric('voltage_max_error_pu') < 0.03, ...
        'S10a retained/pilot voltage benchmark changed unexpectedly.');
    assert(height(control_map) == 649 && numel(converted) == 615 && ...
        numel(unique(converted)) == 615 && ...
        sum(control_map.raw_converted_status_mismatch) == 6 && ...
        sum(control_map.snapshot_effective_status > 0 & ...
            strlength(control_map.source_zone) > 0) == 411, ...
        'S10a source-control identity or status mapping changed unexpectedly.');
    assert(height(pq_audit) == 10 && ...
        all(pq_audit.s10a_diagnostic_pv_enabled), ...
        'S10a must audit all ten previously skipped PQ control locations.');
    fixed = s10a.boundary_q_sensitivity( ...
        s10a.boundary_q_sensitivity.boundary_q_mode == "fixed_source_q", :);
    limited = s10a.boundary_q_sensitivity( ...
        s10a.boundary_q_sensitivity.boundary_q_mode == "limited_source_q", :);
    assert(fixed.pf_success == 1 && fixed.external_q_total_abs_error_mvar < 1e-6 && ...
        limited.pf_success == 1 && limited.external_q_total_abs_error_mvar > 1000, ...
        'S10a boundary-Q mode sensitivity changed unexpectedly.');
end

outputs = struct('root', root, 'public_targets', public, ...
    'hierarchy_policy', hierarchy_policy, ...
    'objective_scales', scales, 's6', s6, 's7_direct_validation', s7, ...
    'phase0_structural_parent', phase0_parent, ...
    'phase0_report', phase0_report, ...
    's13_candidate', s13_candidate, ...
    's13_validation', s13_validation, ...
    's13_artifact_consistency', s13_artifact_consistency, ...
    's13_adversarial_validation', s13_adversarial_validation, ...
    's12_interface_snapshot_test', s12_interface_snapshot_test, ...
    's13_phase1a_oracle_preflight', s13_oracle_preflight, ...
    's13_phase1a_oracle_artifacts', s13_oracle_artifacts, ...
    's13_phase1b_local_identity', s13_phase1b_local, ...
    's13_phase1b_operator_validation', s13_phase1b_operator, ...
    's13_phase1b_artifact_consistency', s13_phase1b_artifacts, ...
    's13_phase1b_adversarial_validation', s13_phase1b_adversarial, ...
    's13_phase1b_smoke', s13_phase1b_smoke, ...
    's13_gate_counts', s13_gate_counts, ...
    's13_phase1a_smoke', s13_smoke, ...
    'full_calibration', full_calibration, 's8_operational_closure', s8, ...
    'voltage_references', voltage_references, ...
    's8_1_capability_certificate', s8_1, ...
    's9a_q_support_diagnostic', s9a, ...
    's9b_feasibility_restoration', s9b, ...
    's9b_reference_audit', s9b_audit, ...
    's10a_control_benchmark', s10a, ...
    'structural_provenance_case', 'npcc_ny_lite_s7_seven_interface_perform_direct_candidate', ...
    'structural_provenance_size', [size(mpc.bus, 1), size(mpc.branch, 1), size(mpc.gen, 1)], ...
    'structural_parent', 'npcc_ny_lite_s7_seven_interface_perform_direct_candidate', ... % deprecated alias
    'structural_parent_size', [size(mpc.bus, 1), size(mpc.branch, 1), size(mpc.gen, 1)], ... % deprecated alias
    'construction_validation_parent', 'npcc_ny_lite_s13_npcc_augmented_2019', ...
    'promoted_operating_case', 'pending_npcc_ny_lite_s14_nyiso_dlr_operating_model', ...
    'diagnostic_reduced_case', 'npcc_ny_lite_s11_dlr_pf_base', ...
    'reference_oracle', 'npcc_ny_lite_s12_perform_retention_core', ...
    'source_dataset', 'full_PERFORM_2019_case', ...
    's12_reference_comparison', struct('status', ...
        'pending_common_s13_full_diagnostic_baseline'), ...
    's14_nyiso_status', struct('status', 'not_built', ...
        'promotion_eligible', false, ...
        'required_network_form', 'nyiso_retention_plus_external_ac_multiport_equivalent'), ...
    'reproduction_status', ...
        's13_full_structural_pass_s14_nyiso_not_built');
fprintf(['Structural handoff reproduction passed: S7 provenance case = %d buses, ' ...
    '%d branches, %d generators; S13-FULL Phase 1B construction checkpoint = ' ...
    '%d/%d/%d. All %d mandatory structural gates pass; %d remaining ' ...
    'construction-validation gates stay fail-closed. All %d committed register ' ...
    'artifacts and the structural ledger match the rebuilt candidate.\n'], ...
    size(mpc.bus, 1), size(mpc.branch, 1), ...
    size(mpc.gen, 1), s13_validation.candidate_size(1), ...
    s13_validation.candidate_size(2), s13_validation.candidate_size(3), ...
    s13_gate_counts.mandatory_structural_total, ...
    s13_gate_counts.construction_validation_fail_closed, ...
    s13_artifact_consistency.matched_register_artifact_count);
if options.run_s13_phase1b_validation
    fprintf(['S13 Phase 1B: local identity %d/%d and UPNY proxy %d/%d ' ...
        'mandatory gates pass; %d public operator gaps remain fail-closed; ' ...
        'all committed Phase 1B artifacts match. S14-NYISO remains unbuilt.\n'], ...
        nnz(s13_phase1b_local.gate_ledger.pass & ...
        s13_phase1b_local.gate_ledger.mandatory), ...
        nnz(s13_phase1b_local.gate_ledger.mandatory), ...
        s13_phase1b_operator.mandatory_proxy_pass_count, ...
        s13_phase1b_operator.mandatory_proxy_gate_count, ...
        s13_phase1b_operator.public_gap_gate_count);
end
if options.run_s13_phase1a_smoke
    fprintf(['S13 inherited-snapshot smoke: standard PF passes 2/2; ' ...
        'Q-limit PF passes %d/2. This is a diagnostic limitation, not a ' ...
        'S14 promotion gate or a 2019 validation result.\n'], ...
        sum(s13_smoke.summary.q_limit_pf_success));
end

if options.run_s13_phase1a_oracle_preflight
    fprintf(['S13.1 no-fit preflight: local identity passes; oracle gates ' ...
        '%d/%d pass; all %d committed evidence artifacts match. The paired ' ...
        'S12/S13-FULL system diagnostic and held-out runs remain fail-closed. ' ...
        'S14-NYISO is not built or promoted.\n'], ...
        s13_oracle_preflight.passing_gate_count, ...
        s13_oracle_preflight.gate_count, ...
        s13_oracle_artifacts.artifact_count);
end
end

function assert_unique_policy_row(policy, category, setting, expected_value)
scope = policy.category == string(category) & ...
    policy.setting == string(setting);
matches = scope & policy.value == string(expected_value);
if nnz(scope) ~= 1 || nnz(matches) ~= 1
    error('run_handoff_reproduction:HierarchyPolicyMismatch', ...
        'Expected exactly one %s/%s row with value %s.', ...
        category, setting, expected_value);
end
end
