function out=run_compact_ny_2025_sensitivities(options)
%RUN_COMPACT_NY_2025_SENSITIVITIES Eight declared S1 assumption variants.
% No topology/parameter selection is performed. Every variant uses the same
% fixed-year-peak S1 observations and default dispatch-fitting objective.
% MIPS is attempted first; an unchanged-input IPOPT fallback is retained.
if nargin<1,options=struct();end
root=fileparts(mfilename('fullpath'));h=fullfile(root,'System Matpower Format','NY_Lite');
addpath(h,fullfile(root,'System Matpower Format'));
d=struct('output_dir',fullfile(root,'output','compact_ny_2025','sensitivities'), ...
    'write_outputs',true,'allow_ipopt_fallback',true);
assert(all(ismember(fieldnames(options),fieldnames(d))),'compact_sens:Options','Unknown sensitivity option.');
for f=string(fieldnames(d))',if ~isfield(options,f),options.(f)=d.(f);end,end
assert(islogical(options.write_outputs)&&isscalar(options.write_outputs) ...
    &&islogical(options.allow_ipopt_fallback)&&isscalar(options.allow_ipopt_fallback), ...
    'compact_sens:Options','Output/fallback flags must be scalar logical values.');
folder=char(java.io.File(options.output_dir).getCanonicalPath());
allowed=char(java.io.File(fullfile(root,'output','compact_ny_2025','sensitivities')).getCanonicalPath());
assert(strcmpi(folder,allowed)||startsWith(lower(folder),[lower(allowed) filesep]), ...
    'compact_sens:OutputPath','Sensitivity artifacts must stay in their dedicated output subtree.');
if options.write_outputs&&~isfolder(folder),mkdir(folder);end
code_manifest=source_code_manifest(root,h);
scenario_id="S1_2025_SUMMER_PEAK_PUBLIC";
inputs=build_compact_nyiso_snapshot_inputs(struct('scenario_ids',scenario_id,'scale_policy','fixed_year_peak'));
assert(height(inputs.snapshots)==1&&all(inputs.interfaces.training_target) ...
    &&inputs.snapshots.vintage==2025&&inputs.snapshots.dataset_split=="training", ...
    'compact_sens:TrainingOnly','Sensitivity fitting may only use the registered S1 training hour.');
variants=variant_register;parent=build_compact_npcc_corridors;
fits=cell(height(variants),1);attempt_evidence=cell(height(variants),1);
attempts=table();summary=table();interface_comparison=table();branch_changes=table();generator_changes=table();
nominal=[];
for k=1:height(variants)
    v=variants(k,:);
    infrastructure_options=struct('impedance_scale',v.impedance_scale,'charging_scale',v.charging_scale, ...
        'include_announced_2025_rcc',v.include_announced_2025_rcc);
    generation_options=struct('include_assumed_astoria_retirement',v.include_assumed_astoria_retirement, ...
        'south_fork_available_fraction',v.south_fork_available_fraction);
    build=apply_compact_2025_generation(apply_compact_2025_infrastructure(parent,infrastructure_options),generation_options);
    snapshot=build_compact_nyiso_operating_snapshot(build,inputs,scenario_id);
    if k==1,nominal=snapshot;end
    assert(isequal(snapshot.branch_keys,nominal.branch_keys)&&isequal(snapshot.generator_keys,nominal.generator_keys) ...
        &&isequal(snapshot.candidate.bus,nominal.candidate.bus) ...
        &&isequal(snapshot.interface_targets,nominal.interface_targets) ...
        &&isequal(snapshot.boundary_register,nominal.boundary_register), ...
        'compact_sens:FixedEvidence','Variant changed bus/load/boundary evidence or device identity.');
    [bc,gc]=hardware_changes(snapshot,nominal,v.variant_id);
    branch_changes=[branch_changes;bc];generator_changes=[generator_changes;gc]; %#ok<AGROW>
    sf=fullfile(folder,char(v.variant_id));if options.write_outputs&&~isfolder(sf),mkdir(sf);end
    solvers="MIPS";if options.allow_ipopt_fallback&&have_feature('ipopt'),solvers(end+1)="IPOPT";end
    evidence=cell(0,1);
    for j=1:numel(solvers)
        fit=fit_compact_nyiso_operating_snapshot(snapshot,struct('solver',char(solvers(j))));
        assert(fit.internal_interface_fit_used&&~fit.heldout_interface_leakage ...
            &&~fit.bounds_relaxed&&fit.fictitious_active_injection_mw==0, ...
            'compact_sens:FitPolicy','Only unchanged-bound training reconstruction is authorized.');
        evidence{end+1,1}=fit; %#ok<AGROW>
        a=fit.bounded_audit.summary;pa=fit.audit.summary;
        row=table(v.variant_id,scenario_id,j,solvers(j),fit.opf_start,fit.mips_cost_multiplier, ...
            fit.prior_weight,fit.interface_scale_mw,fit.electrical_baseline_qualified, ...
            fit.network_and_injections_frozen,a.pf_converged,a.all_limits_passed,pa.pf_converged,pa.all_limits_passed, ...
            a.max_nodal_p_mismatch_mw,a.max_nodal_q_mismatch_mvar, ...
            fit.independent_replay_dispatch_adjustment_mw,fit.independent_replay_voltage_adjustment_pu, ...
            fit.mean_absolute_proxy_error_mw,fit.max_absolute_proxy_error_mw,fit.solver_error,fit.replay_error, ...
            'VariableNames',{'variant_id','scenario_id','attempt','solver','opf_start','mips_cost_multiplier', ...
            'prior_weight','interface_scale_mw','electrical_baseline_qualified','hardware_frozen', ...
            'bounded_solver_success','bounded_audit_passed','fresh_pf_success','fresh_pf_audit_passed', ...
            'bounded_P_residual_mw','bounded_Q_residual_mvar','fresh_pf_P_adjustment_mw','fresh_pf_VM_adjustment_pu', ...
            'proxy_MAE_mw','proxy_max_error_mw','solver_error','replay_error'});
        attempts=[attempts;row]; %#ok<AGROW>
        if options.write_outputs
            save(fullfile(sf,"attempt_"+j+"_"+solvers(j)+".mat"),'fit','-v7');
            save_audit(sf,"attempt_"+j+"_"+solvers(j)+"_bounded",fit.bounded_audit);
            save_audit(sf,"attempt_"+j+"_"+solvers(j)+"_fresh_pf",fit.audit);
        end
        if fit.electrical_baseline_qualified,break;end
    end
    fits{k}=fit;attempt_evidence{k}=evidence;
    t=fit.residuals;t.variant_id=repmat(v.variant_id,height(t),1);
    t.scenario_id=repmat(scenario_id,height(t),1);t.scale_factor_gamma=repmat(inputs.snapshots.scale_factor_gamma,height(t),1);
    t.actual_observed_flow_mw=t.target_flow_mw./t.scale_factor_gamma;
    t.model_proxy_observation_scale_mw=t.model_flow_mw./t.scale_factor_gamma;
    t.observation_scale_residual_mw=t.residual_mw./t.scale_factor_gamma;
    t.model_observation_scale_is_mathematical_rescaling=true(height(t),1);
    t.electrical_baseline_qualified=repmat(fit.electrical_baseline_qualified,height(t),1);
    interface_comparison=[interface_comparison;t]; %#ok<AGROW>
    m=snapshot.candidate;on=m.gen(:,8)>0;nomon=nominal.candidate.gen(:,8)>0;
    a=fit.audit.summary;
    row=table(v.variant_id,fit.solver,numel(evidence),size(m.bus,1),size(m.branch,1),nnz(m.branch(:,11)>0), ...
        size(m.gen,1),nnz(on),sum(m.gen(on,9)),sum(m.gen(on,9))-sum(nominal.candidate.gen(nomon,9)), ...
        height(bc),height(gc),sum(snapshot.bus_injection_ledger.pd_gross_mw), ...
        sum(snapshot.boundary_register.p_injection_mw),fit.electrical_baseline_qualified, ...
        mean(t.absolute_residual_mw),sqrt(mean(t.residual_mw.^2)),max(t.absolute_residual_mw), ...
        a.max_nodal_p_mismatch_mw,a.max_nodal_q_mismatch_mvar,a.max_voltage_violation_pu, ...
        a.max_generator_p_violation_mw,a.max_generator_q_violation_mvar,a.max_branch_overload_mva, ...
        a.branch_loss_mw,min(fit.result.bus(:,8)),max(fit.result.bus(:,8)), ...
        false,false,false,'VariableNames',{'variant_id','reported_solver','attempt_count','ny_bus_count','branch_records', ...
        'active_branch_count','generator_records','online_generator_count','online_pmax_mw','pmax_change_from_nominal_mw', ...
        'changed_branch_records','changed_generator_records','gross_load_mw','net_scheduled_import_mw', ...
        'electrical_baseline_qualified','proxy_MAE_mw','proxy_RMSE_mw','proxy_max_error_mw', ...
        'fresh_pf_P_residual_mw','fresh_pf_Q_residual_mvar','max_voltage_violation_pu', ...
        'max_generator_P_violation_mw','max_generator_Q_violation_mvar','max_branch_overload_mva', ...
        'branch_loss_mw','min_vm_pu','max_vm_pu','heldout_targets_used','automatic_parameter_selection','dlr_ready'});
    summary=[summary;row]; %#ok<AGROW>
    if options.write_outputs
        save(fullfile(sf,'sensitivity_case.mat'),'build','snapshot','fit','v','-v7');
        write(sf,'interface_comparison',t);write(sf,'branch_changes_from_nominal',bc);write(sf,'generator_changes_from_nominal',gc);
        write(sf,'infrastructure_assumptions',build.assumption_register);write(sf,'infrastructure_branch_register',build.infrastructure_branch_register);
        write(sf,'infrastructure_source_manifest',build.infrastructure_source_manifest);
        write(sf,'inherited_construction_source_manifest',build.source_manifest);
        write(sf,'generation_events',build.generation_change_register);write(sf,'bus_injection_ledger',snapshot.bus_injection_ledger);
        write(sf,'boundary_register',snapshot.boundary_register);
    end
    fprintf('%s qualified=%d solver=%s MAE=%.3f MW Pmax_delta=%.3f MW\n',v.variant_id, ...
        fit.electrical_baseline_qualified,fit.solver,mean(t.absolute_residual_mw),row.pmax_change_from_nominal_mw);
end
code_manifest_after=source_code_manifest(root,h);
assert(isequal(code_manifest,code_manifest_after),'compact_sens:CodeChanged','Numerical implementation changed during the sensitivity campaign.');
% Protocol checks assess the experiment definition, independently of success.
gates=table(["eight_prespecified_variants";"only_2025_S1_training_observations";"same_fixed_peak_scale_and_gross_load"; ...
    "all_original_46_NY_buses_retained_and_below200";"only_R_X_B_or_Rcc_status_or_registered_Pmax_changes"; ...
    "all_solver_attempts_retained";"no_automatic_parameter_selection";"no_generation_or_public_operator_validation_claim"], ...
    [height(summary)==8;all(interface_comparison.scenario_id==scenario_id)&all(interface_comparison.used_in_optimizer); ...
    max(abs(summary.gross_load_mw-10902.2197987))<1e-8; ...
    all(summary.ny_bus_count<=200)&&all(cellfun(@(f)all(ismember((37:82)',f.snapshot.candidate.bus(:,1))),fits)); ...
    protocol_hardware_checks(branch_changes,generator_changes,summary); ...
    height(attempts)==sum(summary.attempt_count);~any(summary.automatic_parameter_selection); ...
    all(cellfun(@(f)~f.public_operator_exact&&~f.dlr_ready,fits))], ...
    'VariableNames',{'metric','passed'});
assert(all(gates.passed),'compact_sens:Protocol','Sensitivity protocol failed.');
out=struct('variants',variants,'inputs',inputs,'summary',summary,'attempts',attempts, ...
    'fits',{fits},'attempt_evidence',{attempt_evidence},'interface_comparison',interface_comparison, ...
    'branch_changes',branch_changes,'generator_changes',generator_changes,'code_manifest',code_manifest, ...
    'protocol_gates',gates,'all_variants_electrically_qualified',all(summary.electrical_baseline_qualified), ...
    'automatic_parameter_selection',false,'heldout_targets_used',false,'observed_generation_validated',false, ...
    'public_operators_exact',false,'thermal_model_evaluated',false,'dlr_ready',false,'options',options);
if options.write_outputs
    for field=["variants","summary","attempts","interface_comparison","branch_changes","generator_changes","code_manifest","protocol_gates"]
        write(folder,field,out.(field));
    end
    for field=["snapshots","loads","interfaces","boundary_channels","external_records","source_manifest"]
        write(folder,"source_"+field,inputs.(field));
    end
    save(fullfile(folder,'compact_ny_2025_sensitivity_campaign.mat'),'out','-v7');
    write_report(folder,out);publish_source_audit(root);
end
end

function v=variant_register
v=table(["nominal";"impedance_075";"impedance_125";"charging_zero";"charging_150"; ...
    "RCC_announced_paths_off";"Astoria_retirement_not_assumed";"South_Fork_zero_available"], ...
    [1;.75;1.25;1;1;1;1;1],[1;1;1;0;1.5;1;1;1],logical([1;1;1;1;1;0;1;1]), ...
    logical([1;1;1;1;1;1;0;1]),[1;1;1;1;1;1;1;0], ...
    'VariableNames',{'variant_id','impedance_scale','charging_scale','include_announced_2025_rcc', ...
    'include_assumed_astoria_retirement','south_fork_available_fraction'});
v.selection_policy=repmat("prespecified_one_assumption_at_a_time_no_model_selection",8,1);
end

function [b,g]=hardware_changes(s,n,id)
bm=s.candidate.branch;bn=n.candidate.branch;gm=s.candidate.gen;gn=n.candidate.gen;
changed=find(any(bm~=bn,2));fields=["r_pu","x_pu","b_pu","rate_a_mva","status"];
b=table(repmat(id,numel(changed),1),s.branch_keys(changed),changed,'VariableNames',{'variant_id','branch_key','model_branch_row'});
cols=[3 4 5 6 11];
for k=1:numel(cols),b.("nominal_"+fields(k))=bn(changed,cols(k));b.("variant_"+fields(k))=bm(changed,cols(k));end
allowed=bn;allowed(:,[3 4 5 11])=bm(:,[3 4 5 11]);
assert(isequal(allowed,bm),'compact_sens:BranchChange','Unregistered branch fields changed.');
changed=find(any(gm(:,[1 4:21])~=gn(:,[1 4:21]),2));
g=table(repmat(id,numel(changed),1),s.generator_keys(changed),changed, ...
    gn(changed,9),gm(changed,9),gm(changed,9)-gn(changed,9),'VariableNames', ...
    {'variant_id','generator_key','model_generator_row','nominal_pmax_mw','variant_pmax_mw','pmax_delta_mw'});
allowed=gn;allowed(:,[2 3 9])=gm(:,[2 3 9]);
assert(isequal(allowed,gm),'compact_sens:GeneratorChange','Only registered Pmax and consequent prior operating values may change.');
end

function yes=protocol_hardware_checks(b,g,s)
yes=all(s.changed_branch_records(1)==0)&&all(s.changed_generator_records(1)==0) ...
    &&~any(b.variant_id=="Astoria_retirement_not_assumed"|b.variant_id=="South_Fork_zero_available") ...
    &&~any(ismember(g.variant_id,["impedance_075","impedance_125","charging_zero","charging_150","RCC_announced_paths_off"]));
r=s(s.variant_id=="RCC_announced_paths_off",:);
yes=yes&&r.active_branch_count==s.active_branch_count(1)-2;
yes=yes&&abs(s.pmax_change_from_nominal_mw(s.variant_id=="Astoria_retirement_not_assumed")-528*.355758660106238)<1e-8;
yes=yes&&abs(s.pmax_change_from_nominal_mw(s.variant_id=="South_Fork_zero_available")+132*.355758660106238)<1e-8;
end

function t=source_code_manifest(root,h)
files=[string(fullfile(root,'run_compact_ny_2025_sensitivities.m')); ...
    string(fullfile(h,["build_compact_npcc_corridors.m";"apply_compact_2025_infrastructure.m"; ...
    "apply_compact_2025_generation.m";"build_compact_nyiso_snapshot_inputs.m"; ...
    "build_compact_nyiso_operating_snapshot.m";"fit_compact_nyiso_operating_snapshot.m"; ...
    "compact_nyiso_interface_operators.m";"add_compact_interface_cost.m";"compact_interface_ac_cost.m"; ...
    "nyiso_bus_zone_map.m";"attach_nyiso_zone_metadata.m";"audit_ny_ac_reference.m"]))];
sha=strings(size(files));for k=1:numel(files),sha(k)=file_sha(files(k));end
t=table(erase(files,string(root)+filesep),sha,'VariableNames',{'relative_path','sha256'});
end
function s=file_sha(path)
f=fopen(path,'rb');assert(f>=0);cleanup=onCleanup(@()fclose(f)); %#ok<NASGU>
bytes=fread(f,inf,'*uint8');md=java.security.MessageDigest.getInstance('SHA-256');md.update(bytes);
s=lower(string(reshape(dec2hex(typecast(md.digest(),'uint8'),2).',1,[])));
end
function save_audit(folder,prefix,a)
for field=["summary","bus","generator","branch"],write(folder,prefix+"_"+field,a.(field));end
end
function write(folder,name,t)
ny_lite_writetable_lf(t,fullfile(folder,string(name)+".csv"));
end
function write_report(folder,o)
f=fopen(fullfile(folder,'SENSITIVITY_RESULTS.md'),'w');assert(f>=0);cleanup=onCleanup(@()fclose(f)); %#ok<NASGU>
fprintf(f,'# Compact NY 2025 S1 electrical assumption sensitivities\n\n');
fprintf(f,'%d of 8 prespecified variants pass bounded AC reconstruction and independent fixed-input power flow. These are S1 training fits; no held-out observations or automatic parameter selection are used.\n\n',nnz(o.summary.electrical_baseline_qualified));
fprintf(f,'Every case uses the same 2025-07-29 18:00 public evidence, year-peak gamma %.15g, gross benchmark demand 10,902.2198 MW, and ten-channel boundary policy. MIPS start0 is tried first; unchanged-input IPOPT fallback is retained where required. All successful and failed attempts have full independent bus, generator and branch audits.\n\n',o.inputs.snapshots.scale_factor_gamma);
fprintf(f,'| Variant | AC qualified | Solver | MAE MW | Maximum error MW | Pmax change MW | Active branches |\n|---|---:|---|---:|---:|---:|---:|\n');
for k=1:height(o.summary)
    s=o.summary(k,:);fprintf(f,'| %s | %d | %s | %.3f | %.3f | %.3f | %d |\n', ...
        s.variant_id,s.electrical_baseline_qualified,s.reported_solver,s.proxy_MAE_mw,s.proxy_max_error_mw,s.pmax_change_from_nominal_mw,s.active_branch_count);
end
fprintf(f,'\nImpedance/charging factors apply only to the infrastructure overlay fields declared by its builder; they do not modify every inherited NPCC branch. RCC-off opens the two announced cable through paths while retaining zero-injection station stubs. The Astoria case restores an assumed retired share in a generic aggregate; it does not identify an original physical machine. South Fork zero availability changes the assumed upper bound, not observed wind output.\n\n');
fprintf(f,'Interface operators remain model proxies, generation dispatch is reconstructed, and inherited aggregate reactive limits remain assumptions. A low training error cannot validate the operator mapping, dispatch, physical parameter values, or thermal ratings. A failed variant is a solver/electrical outcome under that assumption, not a proof of global infeasibility. No DLR qualification follows from this campaign.\n');
end

function publish_source_audit(root)
folder=fullfile(root,'output','compact_ny_2025','sources');if ~isfolder(folder),mkdir(folder);end
tmp=fullfile(root,'tmp','nygrid_source_audit');source=fullfile(tmp,'NYGRID_GENERATION_SOURCE_AUDIT.md');
assert(isfile(source),'compact_sens:SourceAudit','Completed source-audit prose is missing.');
copyfile(source,fullfile(folder,'NYGRID_GENERATION_SOURCE_AUDIT.md'));
ids=["NYGRID_PAPER_FINAL";"NYGRID_PINNED_CODE";"NYISO_2025_JULY_FUELMIX_ARCHIVE";"NYISO_2025_S1_FUELMIX_MEMBER"; ...
    "NYISO_PUBLIC_MENU";"NYISO_P63_ARCHIVE_INDEX";"NYISO_P61_SCOPE";"EPA_EIA_CROSSWALK";"EIA_923_SCOPE";"NRC_2025_STATUS"];
urls=["https://sustainable-power-energy-research.media.uconn.edu/wp-content/uploads/sites/3441/2023/11/An-Open-Source-Representation-for-the-NYS-Electric-Grid-to-Support-Power-Grid-and-Market-Transition-Studies.pdf"; ...
    "https://github.com/AndersonEnergyLab-Cornell/NYgrid/tree/47698b6c7823ae7b1bc6935e5601d5b64b8f918e"; ...
    "https://mis.nyiso.com/public/csv/rtfuelmix/20250701rtfuelmix_csv.zip"; ...
    "https://mis.nyiso.com/public/csv/rtfuelmix/20250701rtfuelmix_csv.zip"; ...
    "https://mis.nyiso.com/public/menu.htm";"https://mis.nyiso.com/public/P-63list.htm"; ...
    "https://mis.nyiso.com/public/P-61list.htm";"https://www.epa.gov/power-sector/power-sector-data-crosswalk"; ...
    "https://www.eia.gov/electricity/data/eia923/";"https://www.nrc.gov/reading-rm/doc-collections/event-status/reactor-status/2025/index"];
roles=["published_DC_model_generation_reconstruction_method_not_zonal_telemetry"; ...
    "pinned_author_code_generation_and_external_accounting";"official_statewide_fuelmix_month_archive"; ...
    "official_S1_schema_has_no_zonal_generation_field";"bounded_public_product_inventory"; ...
    "2019_and2025_fuelmix_archive_availability";"aggregate_dispatch_deviation_not_zonal_generation"; ...
    "hourly_combustion_source_vs_EIA_generator_identity_cautions";"monthly_annual_generation_not_hourly"; ...
    "daily_reactor_status_not_hourly_net_dispatch"];
paths=["Liu_2023_TPWRS_NYgrid.pdf";"tree.json";"20250701rtfuelmix_csv.zip";"20250729rtfuelmix.csv";repmat("",6,1)];
sha=strings(10,1);local=strings(10,1);
for k=1:4,sha(k)=file_sha(fullfile(tmp,paths(k)));local(k)="tmp/nygrid_source_audit/"+paths(k);end
t=table(ids,urls,roles,repmat("2026-09-08",10,1),local,sha,false(10,1), ...
    'VariableNames',{'source_id','source_url','evidence_role','checked_date','local_reference_evidence', ...
    'retrieved_file_sha256','source_file_redistributed_in_output'});
t.code_revision=repmat("",10,1);t.code_revision(2)="47698b6c7823ae7b1bc6935e5601d5b64b8f918e";
t.scope=repmat("source_availability_audit_not_generation_observation_input",10,1);
write(folder,'primary_source_manifest_summary',t);
end
