function [mpc, report] = add_npcc_perform_upny_coned_detail(mpc, options)
%ADD_NPCC_PERFORM_UPNY_CONED_DETAIL Append the source-backed Phase 1B overlay.
%   This function requires the 147-bus/253-branch S13 Phase 1A candidate.
%   It appends two zero-injection 345-kV terminals and nine direct PERFORM
%   physical branches. Existing NPCC/S7/S13 rows are not modified.
%
%   The resulting physical proxy is deliberately unpromoted. It excludes
%   unresolved public UPNY-ConEd elements and leaves overlapping aggregate
%   NPCC branches unchanged pending the Phase 1D passive residual fit.

if nargin < 2, options = struct(); end
if ~isfield(options, 'verbose'), options.verbose = true; end
if ~isfield(options, 'neutral_angle_bounds')
    options.neutral_angle_bounds = true;
end

helper_dir = fileparts(mfilename('fullpath'));
case_dir = fileparts(helper_dir);
root = fileparts(case_dir);
perform_dir = fullfile(root, 'PERFORM', ...
    'On Peak 2019 v23_Perform_NY', 'On Peak 2019 v23');
addpath(case_dir); addpath(helper_dir); addpath(perform_dir);
define_constants;

validate_parent(mpc);
src = nyiso_On_Peak_v23_shunts_as_z_load;

source_case = "PERFORM/On Peak 2019 v23_Perform_NY/On Peak 2019 v23/" + ...
    "nyiso_On_Peak_v23_shunts_as_z_load.m";
source_name = "full_PERFORM_2019_case";

% Existing physical-terminal mappings. Pleasant Valley uses the explicit
% NPCC abbreviation alias; all other names must match exactly.
attachment_model = [73; 9002; 77; 74; 76];
attachment_source = [651; 902; 900; 897; 1519];
attachment_zone = ["G"; "G"; "H"; "H"; "G"];
validate_attachments(mpc, src, attachment_model, attachment_source, ...
    attachment_zone);

added_source_buses = [858; 774];
added_zones = ["G"; "G"];
if any(ismember(added_source_buses, mpc.bus(:, BUS_I)))
    error('add_npcc_perform_upny_coned_detail:AlreadyPresent', ...
        'One or more Phase 1B PERFORM bus IDs already exist in the case.');
end

% Preserve source within-path phasor differences while aligning each new
% terminal to its existing NPCC attachment reference. These are initial
% values only; no operating-state or source-dispatch claim is made.
reference_model = [73; 76];
reference_source = [651; 1519];
first_bus_row = size(mpc.bus, 1) + 1;
for k = 1:numel(added_source_buses)
    si = find(src.bus(:, BUS_I) == added_source_buses(k), 1);
    mi = find(mpc.bus(:, BUS_I) == reference_model(k), 1);
    ri = find(src.bus(:, BUS_I) == reference_source(k), 1);
    if isempty(si) || isempty(mi) || isempty(ri)
        error('add_npcc_perform_upny_coned_detail:MissingSourceBus', ...
            'Missing Phase 1B source/reference bus for source bus %d.', ...
            added_source_buses(k));
    end
    if any(abs(src.bus(si, [PD QD GS BS])) > 1e-12)
        error('add_npcc_perform_upny_coned_detail:SourceInjection', ...
            'Source bus %d is not a zero-injection physical terminal.', ...
            added_source_buses(k));
    end
    new_bus = zeros(1, size(mpc.bus, 2));
    ncopy = min([13, size(src.bus, 2), size(mpc.bus, 2)]);
    new_bus(1:ncopy) = src.bus(si, 1:ncopy);
    new_bus([PD QD GS BS]) = 0;
    new_bus(BUS_TYPE) = PQ;
    new_bus(BUS_AREA) = mpc.bus(mi, BUS_AREA);
    new_bus(VA) = src.bus(si, VA) + ...
        (mpc.bus(mi, VA) - src.bus(ri, VA));
    new_bus(VM) = src.bus(si, VM) * ...
        (mpc.bus(mi, VM) / src.bus(ri, VM));
    mpc.bus = [mpc.bus; new_bus];
    mpc = append_bus_name(mpc, strtrim(src.bus_name{si}));
end

% Stable source order: Pleasant Valley/East Fishkill/Wood Street mesh,
% followed by the Ramapo/Ladentown/Buchanan path.
source_branch_rows = [1389; 1390; 1391; 1392; 1689; 1690; ...
    1577; 1576; 1738];
source_from = [651; 651; 651; 651; 858; 858; 1519; 774; 1519];
source_to = [858; 858; 902; 902; 902; 902; 774; 900; 900];
model_from = [73; 73; 73; 73; 858; 858; 76; 774; 76];
model_to = [858; 858; 9002; 9002; 9002; 9002; 774; 77; 77];
circuit_id = ["1"; "2"; "1"; "2"; "1"; "2"; "1"; "1"; "1"];
overlay_path_id = [repmat("phase1b_pv_wood_mesh", 6, 1); ...
    repmat("phase1b_ramapo_buchanan_path", 3, 1)];
expected = [ ...
    0.00035 0.00527 0.13611 1216 2454 1804 0 0 1; ...
    0.00035 0.00527 0.13612 1216 2454 1804 0 0 1; ...
    0.00081 0.01237 0.31971 1216 2454 1804 0 0 1; ...
    0.00081 0.01237 0.31972 1216 2454 1804 0 0 1; ...
    0.00047 0.00713 0.18428 1216 2454 1804 0 0 1; ...
    0.00047 0.00713 0.18426 1216 2454 1804 0 0 1; ...
    0.00018 0.00276 0.07125 1216 2454 1804 0 0 1; ...
    0.00035 0.00541 0.13993 1725 1725 2500 0 0 1; ...
    0.00054 0.00824 0.21288 1725 1725 2500 0 0 1];
source_cols = [BR_R BR_X BR_B RATE_A RATE_B RATE_C TAP SHIFT BR_STATUS];
for k = 1:numel(source_branch_rows)
    sr = source_branch_rows(k);
    if sr > size(src.branch, 1) || ...
            src.branch(sr, F_BUS) ~= source_from(k) || ...
            src.branch(sr, T_BUS) ~= source_to(k)
        error('add_npcc_perform_upny_coned_detail:SourceBranchIdentity', ...
            'PERFORM row %d no longer matches %d-%d CKT %s.', ...
            sr, source_from(k), source_to(k), circuit_id(k));
    end
    if any(abs(src.branch(sr, source_cols) - expected(k, :)) > 1e-12)
        error('add_npcc_perform_upny_coned_detail:SourceBranchParameter', ...
            'PERFORM row %d no longer matches its audited parameters.', sr);
    end
end

first_branch_row = size(mpc.branch, 1) + 1;
for k = 1:numel(source_branch_rows)
    sr = source_branch_rows(k);
    new_branch = zeros(1, size(mpc.branch, 2));
    ncopy = min([13, size(src.branch, 2), size(mpc.branch, 2)]);
    new_branch(1:ncopy) = src.branch(sr, 1:ncopy);
    new_branch(F_BUS) = model_from(k);
    new_branch(T_BUS) = model_to(k);
    if options.neutral_angle_bounds && size(mpc.branch, 2) >= ANGMAX
        new_branch(ANGMIN) = -360;
        new_branch(ANGMAX) = 360;
    end
    mpc.branch = [mpc.branch; new_branch];
end
physical_rows = (first_branch_row:size(mpc.branch, 1))';

mpc = install_overlay_zone_metadata(mpc, added_source_buses, added_zones);
mpc = attach_nyiso_zone_metadata(mpc);

[bus_map, branch_map, residual_register, physical_register, operator_map, ...
    residual_shunt_register, path_register, operator_detail, ...
    generation_audit, terminal_reuse_audit] = build_registers( ...
    mpc, src, source_name, ...
    source_case, added_source_buses, added_zones, source_branch_rows, ...
    source_from, source_to, model_from, model_to, circuit_id, ...
    overlay_path_id, physical_rows);

register_files = struct( ...
    'bus_map', 'npcc_perform_overlay_bus_map.csv', ...
    'branch_map', 'npcc_perform_overlay_branch_map.csv', ...
    'residual_register', 'npcc_residual_equivalent_register.csv', ...
    'residual_shunt_register', 'npcc_residual_shunt_register.csv', ...
    'path_register', 'npcc_overlay_path_register.csv', ...
    'physical_register', 'npcc_added_physical_circuit_register.csv', ...
    'interface_operator_map', 'npcc_2019_interface_operator_map.csv');

% Update only cumulative overlay identity metadata. The caller owns the
% cumulative table assembly and canonical artifact write transaction.
overlay = mpc.userdata.npcc_perform_overlay;
overlay.current_phase = 'phase1b';
overlay.added_bus_rows = append_unique(overlay.added_bus_rows, ...
    (first_bus_row:size(mpc.bus, 1))');
overlay.added_bus_ids = append_unique(overlay.added_bus_ids, ...
    added_source_buses);
overlay.physical_branch_rows = append_unique(overlay.physical_branch_rows, ...
    physical_rows);
overlay.source_branch_rows = append_unique(overlay.source_branch_rows, ...
    source_branch_rows);
overlay.phase1b_added_bus_rows = (first_bus_row:size(mpc.bus, 1))';
overlay.phase1b_added_bus_ids = added_source_buses;
overlay.phase1b_physical_branch_rows = physical_rows;
overlay.phase1b_source_branch_rows = source_branch_rows;
overlay.phase1b_status = 'implemented_unpromoted_local_validation_pending';
overlay.residualization_status = ...
    'pending_phase1d_passive_multi_terminal_fit';
overlay.dlr_eligible = false;
overlay.dlr_delivery_eligible = false;
overlay.construction_source_qualified = false;
overlay.promotion_eligible = false;
mpc.userdata.npcc_perform_overlay = overlay;

if isfield(mpc.userdata, 's13')
    mpc.userdata.s13.current_phase = 'phase1b';
    mpc.userdata.s13.residualization_status = ...
        'pending_phase1d_passive_multi_terminal_fit';
    mpc.userdata.s13.dlr_delivery_eligible = false;
    mpc.userdata.s13.construction_source_qualified = false;
    mpc.userdata.s13.promotion_eligible = false;
end

report = struct( ...
    'phase_id', 'phase1b', ...
    'report_role', 'phase_specific_overlay_evidence', ...
    'buses_added', numel(added_source_buses), ...
    'branches_added', numel(source_branch_rows), ...
    'case_size', [size(mpc.bus, 1), size(mpc.branch, 1), size(mpc.gen, 1)], ...
    'added_bus_rows', (first_bus_row:size(mpc.bus, 1))', ...
    'added_bus_ids', added_source_buses, ...
    'physical_branch_rows', physical_rows, ...
    'source_branch_rows', source_branch_rows, ...
    'bus_map', bus_map, ...
    'branch_map', branch_map, ...
    'residual_register', residual_register, ...
    'residual_shunt_register', residual_shunt_register, ...
    'path_register', path_register, ...
    'physical_register', physical_register, ...
    'operator_map', operator_map, ...
    'operator_detail', operator_detail, ...
    'operator_status', ...
        'source_realizable_nonintersecting_345kv_proxy_with_public_gaps', ...
    'is_exact_public_operator', false, ...
    'generation_audit', generation_audit, ...
    'terminal_reuse_audit', terminal_reuse_audit, ...
    'register_files', register_files, ...
    'residualization_status', ...
        'pending_phase1d_passive_multi_terminal_fit', ...
    'dlr_eligible', false, ...
    'construction_source_qualified', false, ...
    'promotion_eligible', false, ...
    'promotion_blocker', ...
        "S13-FULL is a construction parent and is never the DLR delivery model");

if options.verbose
    fprintf(['Phase 1B source-backed UPNY-ConEd detail: %d buses, ' ...
        '%d branches, %d generators.\n'], size(mpc.bus, 1), ...
        size(mpc.branch, 1), size(mpc.gen, 1));
    fprintf(['  Added 2 terminals and 9 direct physical rows; the six-row ' ...
        'operator is a nonintersecting 345-kV proxy with public gaps.\n']);
end
end

function validate_parent(mpc)
define_constants;
if size(mpc.bus, 1) ~= 147 || size(mpc.branch, 1) ~= 253 || ...
        size(mpc.gen, 1) ~= 62
    error('add_npcc_perform_upny_coned_detail:ParentDimensions', ...
        'Phase 1B requires the 147-bus/253-branch/62-generator Phase 1A case.');
end
required = [(1:140)'; 9001; 9002; 9003; 1228; 1222; 1567; 772];
if ~all(ismember(required, mpc.bus(:, BUS_I)))
    error('add_npcc_perform_upny_coned_detail:ParentIdentity', ...
        'The complete S7 parent and Phase 1A terminal identities are required.');
end
if ~isfield(mpc, 'userdata') || ...
        ~isfield(mpc.userdata, 'npcc_perform_overlay')
    error('add_npcc_perform_upny_coned_detail:ParentMetadata', ...
        'The Phase 1A cumulative overlay metadata is missing.');
end
overlay = mpc.userdata.npcc_perform_overlay;
if ~isfield(overlay, 'current_phase') || ...
        string(overlay.current_phase) ~= "phase1a"
    error('add_npcc_perform_upny_coned_detail:ParentPhase', ...
        'The input must be the Phase 1A candidate.');
end
expected_source_rows = [2137; 2131; 2154; 2133; 1567; 1568; 1571];
expected_model_rows = (247:253)';
if ~isfield(overlay, 'source_branch_rows') || ...
        ~isequal(overlay.source_branch_rows(:), expected_source_rows) || ...
        ~isfield(overlay, 'physical_branch_rows') || ...
        ~isequal(overlay.physical_branch_rows(:), expected_model_rows)
    error('add_npcc_perform_upny_coned_detail:ParentPhase1AIdentity', ...
        'The Phase 1A physical/source branch register changed.');
end
if isfield(overlay, 'promotion_eligible') && ...
        (~isscalar(overlay.promotion_eligible) || ...
        logical(overlay.promotion_eligible))
    error('add_npcc_perform_upny_coned_detail:ParentPromotion', ...
        'The Phase 1A parent must remain explicitly unpromoted.');
end
end

function validate_attachments(mpc, src, model_bus, source_bus, expected_zone)
define_constants;
for k = 1:numel(model_bus)
    mi = find(mpc.bus(:, BUS_I) == model_bus(k), 1);
    si = find(src.bus(:, BUS_I) == source_bus(k), 1);
    if isempty(mi) || isempty(si)
        error('add_npcc_perform_upny_coned_detail:MissingAttachment', ...
            'Missing model/source attachment %d/%d.', model_bus(k), ...
            source_bus(k));
    end
    model_name = normalize_attachment_name(mpc.bus_name{mi});
    source_name = normalize_attachment_name(src.bus_name{si});
    if model_name ~= source_name
        error('add_npcc_perform_upny_coned_detail:AttachmentName', ...
            'Attachment %d/%d does not satisfy the registered name alias.', ...
            model_bus(k), source_bus(k));
    end
    if abs(mpc.bus(mi, BASE_KV) - src.bus(si, BASE_KV)) > 1e-12 || ...
            abs(src.bus(si, BASE_KV) - 345) > 1e-12
        error('add_npcc_perform_upny_coned_detail:AttachmentVoltage', ...
            'Attachment %d/%d is not a matching 345-kV terminal.', ...
            model_bus(k), source_bus(k));
    end
    if model_physical_zone(mpc, mi) ~= expected_zone(k) || ...
            source_zone(src.bus(si, BUS_AREA)) ~= expected_zone(k)
        error('add_npcc_perform_upny_coned_detail:AttachmentZone', ...
            'Attachment %d/%d does not have the expected physical zone.', ...
            model_bus(k), source_bus(k));
    end
    if mpc.bus(mi, BUS_TYPE) ~= PQ || ...
            ~any(mpc.branch(:, F_BUS) == model_bus(k) | ...
            mpc.branch(:, T_BUS) == model_bus(k))
        error('add_npcc_perform_upny_coned_detail:AttachmentRole', ...
            'Attachment bus %d is not the expected connected PQ terminal.', ...
            model_bus(k));
    end
    if any(abs(src.bus(si, [PD QD GS BS])) > 1e-12)
        error('add_npcc_perform_upny_coned_detail:SourceTerminalRole', ...
            'Source bus %d is not the audited zero-bus-injection terminal.', ...
            source_bus(k));
    end
end

% The retained full-NPCC Pleasant Valley terminal must still connect to the
% external network. This distinguishes it from the PERFORM boundary proxy.
pv = find(mpc.bus(:, BUS_I) == 73, 1);
incident = find(mpc.branch(:, F_BUS) == 73 | mpc.branch(:, T_BUS) == 73);
neighbor = zeros(numel(incident), 1);
for k = 1:numel(incident)
    row = incident(k);
    neighbor(k) = mpc.branch(row, F_BUS);
    if neighbor(k) == 73, neighbor(k) = mpc.branch(row, T_BUS); end
end
neighbor_names = strings(numel(neighbor), 1);
for k = 1:numel(neighbor)
    ni = find(mpc.bus(:, BUS_I) == neighbor(k), 1);
    neighbor_names(k) = normalize_attachment_name(mpc.bus_name{ni});
end
if isempty(pv) || ~any(neighbor_names == "SOUTHINGTEN")
    error('add_npcc_perform_upny_coned_detail:PleasantValleyRole', ...
        'Pleasant Valley no longer has its retained full-NPCC external tie.');
end
end

function [bus_map, branch_map, residual, physical, operators, ...
        residual_shunt, path_register, operator_detail, generation_audit, ...
        terminal_reuse_audit] = ...
        build_registers(mpc, src, source_name, source_case, ...
        added_source_buses, added_zones, source_branch_rows, source_from, ...
        source_to, model_from, model_to, circuit_id, overlay_path_id, ...
        physical_rows)
define_constants;

% Phase 1B owns these five mapped terminals. Ramapo remains owned by Phase
% 1A; Millwood is audited below but is not part of an appended Phase 1B row.
model_bus = [73; 9002; 77; added_source_buses];
source_bus = [651; 902; 900; added_source_buses];
physical_zone = ["G"; "G"; "H"; added_zones];
model_action = ["retained_existing_npcc_attachment_proxy"; ...
    "retained_existing_npcc_attachment"; ...
    "retained_existing_npcc_attachment_proxy"; ...
    repmat("appended_physical_terminal", 2, 1)];
terminal_electrical_policy = [ ...
    "retained_npcc_control_and_injection_not_source_copied"; ...
    "retained_npcc_unchanged"; ...
    "retained_npcc_control_and_injection_not_source_copied"; ...
    "pq_zero_injection_source_limits"; ...
    "pq_zero_injection_source_limits"];
overlay_path_id_bus = ["phase1b_pv_wood_mesh"; ...
    "phase1b_pv_wood_mesh"; "phase1b_ramapo_buchanan_path"; ...
    "phase1b_pv_wood_mesh"; ...
    "phase1b_ramapo_buchanan_path"];
npcc_attachment_bus = [73; 9002; 77; 73; 76];
source_attachment_bus = [651; 902; 900; 651; 1519];
mapping_confidence = [ ...
    "high_registered_pleasant_valley_alias_voltage_zone_role"; ...
    "high_exact_name_voltage_zone_role"; ...
    "high_exact_name_voltage_zone_topology_role"; ...
    "high_exact_source_identity"; "high_exact_source_identity"];
implementation_status = repmat("implemented_unpromoted_phase1b", 5, 1);

model_bus_name = strings(5, 1); source_bus_name = strings(5, 1);
source_base_kv = zeros(5, 1); source_area = zeros(5, 1);
model_area = zeros(5, 1); source_vm_pu = zeros(5, 1);
source_va_deg = zeros(5, 1); source_pd_mw = zeros(5, 1);
source_qd_mvar = zeros(5, 1); source_gs_mw = zeros(5, 1);
source_bs_mvar = zeros(5, 1);
for k = 1:5
    mi = find(mpc.bus(:, BUS_I) == model_bus(k), 1);
    si = find(src.bus(:, BUS_I) == source_bus(k), 1);
    model_bus_name(k) = string(strtrim(mpc.bus_name{mi}));
    source_bus_name(k) = string(strtrim(src.bus_name{si}));
    source_base_kv(k) = src.bus(si, BASE_KV);
    source_area(k) = src.bus(si, BUS_AREA);
    model_area(k) = mpc.bus(mi, BUS_AREA);
    source_vm_pu(k) = src.bus(si, VM);
    source_va_deg(k) = src.bus(si, VA);
    source_pd_mw(k) = src.bus(si, PD);
    source_qd_mvar(k) = src.bus(si, QD);
    source_gs_mw(k) = src.bus(si, GS);
    source_bs_mvar(k) = src.bus(si, BS);
end
bus_map = table(model_bus, model_bus_name, model_action, ...
    terminal_electrical_policy, overlay_path_id_bus, ...
    npcc_attachment_bus, source_attachment_bus, ...
    repmat(source_name, 5, 1), repmat(source_case, 5, 1), source_bus, ...
    source_bus_name, source_base_kv, source_area, model_area, physical_zone, ...
    source_vm_pu, source_va_deg, source_pd_mw, source_qd_mvar, ...
    source_gs_mw, source_bs_mvar, mapping_confidence, implementation_status, ...
    'VariableNames', {'model_bus','model_bus_name','model_action', ...
    'terminal_electrical_policy','overlay_path_id','npcc_attachment_bus', ...
    'source_attachment_bus','source_model','source_case','source_bus', ...
    'source_bus_name','source_base_kv','source_area','model_area', ...
    'physical_zone','source_vm_pu','source_va_deg','source_pd_mw', ...
    'source_qd_mvar','source_gs_mw','source_bs_mvar', ...
    'mapping_confidence','implementation_status'});

n = numel(source_branch_rows);
source_r_pu = src.branch(source_branch_rows, BR_R);
source_x_pu = src.branch(source_branch_rows, BR_X);
source_b_pu = src.branch(source_branch_rows, BR_B);
source_rate_a_mva = src.branch(source_branch_rows, RATE_A);
source_rate_b_mva = src.branch(source_branch_rows, RATE_B);
source_rate_c_mva = src.branch(source_branch_rows, RATE_C);
branch_classification = repmat("physical_circuit", n, 1);
construction_method = repmat( ...
    "direct_perform_electrical_copy_neutral_angle_bounds", n, 1);
dlr_eligible = false(n, 1);
dlr_data_status = repmat("pending_conductor_and_weather_mapping", n, 1);
branch_confidence = repmat("high", n, 1);
residual_overlap_status = repmat("pending_phase1d_passive_fit", n, 1);
branch_status = repmat("implemented_unpromoted_phase1b", n, 1);
npcc_attachment_from_bus = [repmat(73, 6, 1); repmat(76, 3, 1)];
npcc_attachment_to_bus = [repmat(9002, 6, 1); repmat(77, 3, 1)];
branch_map = table(physical_rows, model_from, model_to, ...
    overlay_path_id, npcc_attachment_from_bus, npcc_attachment_to_bus, ...
    repmat(source_name, n, 1), repmat(source_case, n, 1), ...
    source_branch_rows, source_from, source_to, circuit_id, source_r_pu, ...
    source_x_pu, source_b_pu, source_rate_a_mva, source_rate_b_mva, ...
    source_rate_c_mva, branch_classification, construction_method, ...
    dlr_eligible, dlr_data_status, branch_confidence, ...
    residual_overlap_status, branch_status, ...
    'VariableNames', {'model_branch_row','model_from_bus','model_to_bus', ...
    'overlay_path_id','npcc_attachment_from_bus','npcc_attachment_to_bus', ...
    'source_model','source_case','source_branch_row','source_from_bus', ...
    'source_to_bus','source_circuit_id','source_r_pu','source_x_pu', ...
    'source_b_pu','source_rate_a_mva','source_rate_b_mva', ...
    'source_rate_c_mva','branch_classification','construction_method', ...
    'dlr_eligible','dlr_data_status','mapping_confidence', ...
    'residual_overlap_status','implementation_status'});

residual_rows = [94; 235];
original_from_bus = mpc.branch(residual_rows, F_BUS);
original_to_bus = mpc.branch(residual_rows, T_BUS);
original_r_pu = mpc.branch(residual_rows, BR_R);
original_x_pu = mpc.branch(residual_rows, BR_X);
original_b_pu = mpc.branch(residual_rows, BR_B);
classification = repmat("physical_overlap_residual_candidate", 2, 1);
overlap_scope = ["Ramapo-Ladentown-Buchanan/Y94 physical overlay"; ...
    "Pleasant Valley-East Fishkill/Wood Street physical overlay"];
adjustment_evidence_requirement = repmat( ...
    "source_topology_overlap_and_passivity", 2, 1);
adjustment_evidence_status = repmat( ...
    "source_topology_overlap_registered", 2, 1);
regularization_policy = repmat("passive_residual_fit", 2, 1);
fitted_r_pu = nan(2, 1); fitted_x_pu = nan(2, 1);
fitted_b_pu = nan(2, 1); fit_objective = nan(2, 1);
residual_resistance_nonnegative = false(2, 1);
passivity_min_eigenvalue = nan(2, 1);
passivity_gate_pass = false(2, 1);
fit_status = repmat("pending_phase1d_multi_terminal_fit", 2, 1);
passivity_status = repmat("not_yet_tested", 2, 1);
dlr_eligible_residual = false(2, 1);
freeze = false(2, 1);
residual = table(residual_rows, original_from_bus, original_to_bus, ...
    original_r_pu, original_x_pu, original_b_pu, classification, ...
    overlap_scope, adjustment_evidence_requirement, ...
    adjustment_evidence_status, regularization_policy, fitted_r_pu, ...
    fitted_x_pu, fitted_b_pu, fit_objective, ...
    residual_resistance_nonnegative, passivity_min_eigenvalue, ...
    passivity_gate_pass, fit_status, passivity_status, ...
    dlr_eligible_residual, freeze, ...
    'VariableNames', {'model_branch_row','from_bus','to_bus', ...
    'original_r_pu','original_x_pu','original_b_pu','classification', ...
    'overlap_scope','adjustment_evidence_requirement', ...
    'adjustment_evidence_status','regularization_policy','fitted_r_pu', ...
    'fitted_x_pu','fitted_b_pu','fit_objective', ...
    'residual_resistance_nonnegative','passivity_min_eigenvalue', ...
    'passivity_gate_pass','fit_status','passivity_status','dlr_eligible', ...
    'freeze'});

residual_shunt = table(zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), false(0, 1), ...
    'VariableNames', {'model_bus','original_gs_mw_at_v1', ...
    'original_bs_mvar_at_v1','fitted_gs_mw_at_v1', ...
    'fitted_bs_mvar_at_v1','fit_status','passivity_status','provenance', ...
    'passivity_gate_pass'});

path_register = table(["phase1b_pv_wood_mesh"; ...
    "phase1b_ramapo_buchanan_path"], repmat("phase1b", 2, 1), ...
    [73; 76], [9002; 77], [651; 1519], [902; 900], ...
    ["G"; "G"], ["G"; "H"], ...
    repmat("implemented_unpromoted_phase1b", 2, 1), ...
    ["high_physical_identity_operator_membership_mixed"; ...
    "high_physical_identity_operator_membership_medium"], ...
    'VariableNames', {'overlay_path_id','phase_id', ...
    'npcc_attachment_from_bus','npcc_attachment_to_bus', ...
    'source_attachment_from_bus','source_attachment_to_bus', ...
    'from_zone','to_zone','implementation_status','mapping_confidence'});

physical = branch_map(:, {'model_branch_row','model_from_bus','model_to_bus', ...
    'overlay_path_id','npcc_attachment_from_bus','npcc_attachment_to_bus', ...
    'source_model','source_case','source_branch_row','source_from_bus', ...
    'source_to_bus','source_circuit_id','source_r_pu','source_x_pu', ...
    'source_b_pu','source_rate_a_mva','source_rate_b_mva', ...
    'source_rate_c_mva','branch_classification','construction_method', ...
    'residual_overlap_status','dlr_eligible','dlr_data_status', ...
    'mapping_confidence','implementation_status'});

selected_source = [1389; 1390; 1391; 1392; 1576; 1738];
selected_index = zeros(numel(selected_source), 1);
for k = 1:numel(selected_source)
    selected_index(k) = find(source_branch_rows == selected_source(k), 1);
end
interface_name = repmat("UPNY_ConEd_proxy", 6, 1);
component_name = ["Pleasant_Valley_East_Fishkill_F36"; ...
    "Pleasant_Valley_East_Fishkill_F37"; ...
    "Pleasant_Valley_Wood_Street_F30"; ...
    "Pleasant_Valley_Wood_Street_F31"; ...
    "Ladentown_Buchanan_Y88"; "Ramapo_Buchanan_Y94"];
model_branch_row = physical_rows(selected_index);
operator_sign = ones(6, 1);
source_branch_row = source_branch_rows(selected_index);
source_circuit_id = circuit_id(selected_index);
is_exact_public_operator = false(6, 1);
operator_status = repmat( ...
    "source_realizable_nonintersecting_345kv_proxy_with_public_gaps", 6, 1);
notes = repmat( ...
    "From-end upstream-to-downstream proxy; unresolved RFK305/BK1/BK2 public elements remain absent", ...
    6, 1);
operators = table(interface_name, component_name, model_branch_row, ...
    operator_sign, source_branch_row, source_circuit_id, ...
    is_exact_public_operator, operator_status, notes);

% The detail order is the six proxy members followed by the three support
% rows. Its first 15 columns are the stable validator contract.
detail_index = [1; 2; 3; 4; 8; 9; 5; 6; 7];
detail_model_branch_row = physical_rows(detail_index);
detail_source_branch_row = source_branch_rows(detail_index);
detail_source_from_bus = source_from(detail_index);
detail_source_to_bus = source_to(detail_index);
detail_source_circuit_id = circuit_id(detail_index);
detail_model_from_bus = model_from(detail_index);
detail_model_to_bus = model_to(detail_index);
detail_path_id = overlay_path_id(detail_index);
physical_circuit_key = ["PERFORM_651_858_CKT_1"; ...
    "PERFORM_651_858_CKT_2"; "PERFORM_651_902_CKT_1"; ...
    "PERFORM_651_902_CKT_2"; "PERFORM_774_900_CKT_1"; ...
    "PERFORM_1519_900_CKT_1"; "PERFORM_858_902_CKT_1"; ...
    "PERFORM_858_902_CKT_2"; "PERFORM_1519_774_CKT_1"];
operator_membership = [true(6, 1); false(3, 1)];
cutset_from_side = [repmat("U", 6, 1); "D"; "D"; "U"];
cutset_to_side = [repmat("D", 8, 1); "U"];
meter_bus = nan(n, 1);
meter_bus(operator_membership) = ...
    detail_model_from_bus(operator_membership);
meter_end = repmat("none", n, 1);
meter_end(operator_membership) = "from";
detail_sign = zeros(n, 1);
detail_sign(operator_membership) = 1;
detail_operator_status = repmat( ...
    "source_realizable_nonintersecting_345kv_proxy_with_public_gaps", n, 1);
detail_operator_status(~operator_membership) = ...
    "proxy_topology_support_not_operator_member";
detail_is_exact_public_operator = false(n, 1);
public_label = ["F36"; "F37"; "F30"; "F31"; "Y88"; "Y94"; ...
    repmat("not_public_operator_member", 3, 1)];
effective_date_evidence = repmat( ...
    "2022-06-23_NYISO_Operating_Study_Appendix_E", n, 1);
effective_date_evidence(~operator_membership) = "PERFORM_v23_source_topology";
evidence_source = repmat( ...
    "NYISO_Operating_Study_Appendix_E_plus_PERFORM_v23_mapping", n, 1);
evidence_source(~operator_membership) = "PERFORM_v23_RAW_topology_support";
detail_confidence = [repmat("physical_high_operator_low", 2, 1); ...
    repmat("physical_high_operator_medium", 4, 1); ...
    repmat("physical_high", 3, 1)];
exclusion_reason = [repmat("", 6, 1); ...
    repmat("same_downstream_side_topology_support", 2, 1); ...
    "same_upstream_side_topology_support"];
operator_detail = table(detail_model_branch_row, detail_source_branch_row, ...
    detail_source_from_bus, detail_source_to_bus, ...
    detail_source_circuit_id, physical_circuit_key, operator_membership, ...
    cutset_from_side, cutset_to_side, meter_bus, meter_end, detail_sign, ...
    detail_path_id, detail_operator_status, ...
    detail_is_exact_public_operator, public_label, detail_model_from_bus, ...
    detail_model_to_bus, effective_date_evidence, evidence_source, ...
    detail_confidence, exclusion_reason, ...
    'VariableNames', {'model_branch_row','source_branch_row', ...
    'source_from_bus','source_to_bus','source_circuit_id', ...
    'physical_circuit_key','operator_membership','cutset_from_side', ...
    'cutset_to_side','meter_bus','meter_end','operator_sign','path_id', ...
    'operator_status','is_exact_public_operator','public_circuit_label', ...
    'model_from_bus','model_to_bus','effective_date_evidence', ...
    'evidence_source','mapping_confidence','exclusion_reason'});

generation_audit = build_generation_audit(src, source_name, source_case);
terminal_reuse_audit = build_terminal_reuse_audit(mpc, src);
end

function audit = build_terminal_reuse_audit(mpc, src)
define_constants;
model_bus = [73; 9002; 77; 74; 76];
source_bus = [651; 902; 900; 897; 1519];
n = numel(model_bus);
model_bus_name = strings(n, 1); source_bus_name = strings(n, 1);
model_bus_type = zeros(n, 1); source_bus_type = zeros(n, 1);
model_pd_mw = zeros(n, 1); source_pd_mw = zeros(n, 1);
for k = 1:n
    mi = find(mpc.bus(:, BUS_I) == model_bus(k), 1);
    si = find(src.bus(:, BUS_I) == source_bus(k), 1);
    model_bus_name(k) = string(strtrim(mpc.bus_name{mi}));
    source_bus_name(k) = string(strtrim(src.bus_name{si}));
    model_bus_type(k) = mpc.bus(mi, BUS_TYPE);
    source_bus_type(k) = src.bus(si, BUS_TYPE);
    model_pd_mw(k) = mpc.bus(mi, PD);
    source_pd_mw(k) = src.bus(si, PD);
end
physical_zone = ["G"; "G"; "H"; "H"; "G"];
reuse_classification = ["conditional_attachment_proxy"; ...
    "exact_zero_injection_transit_match"; ...
    "conditional_attachment_proxy"; "audited_not_used_in_phase1b_rows"; ...
    "conditional_attachment_proxy_owned_by_phase1a"];
control_injection_policy = [ ...
    "retain_full_npcc_external_tie_and_controls"; ...
    "retain_npcc_zero_injection_transit"; ...
    "retain_npcc_controls_generation_qualification_pending"; ...
    "retain_npcc_aggregate_load_exclude_from_local_interior"; ...
    "retain_npcc_controls_phase1a_attachment"];
audit_status = repmat("audited_no_source_dispatch_or_load_copied", n, 1);
audit = table(model_bus, model_bus_name, source_bus, source_bus_name, ...
    physical_zone, model_bus_type, source_bus_type, model_pd_mw, ...
    source_pd_mw, reuse_classification, control_injection_policy, ...
    audit_status);
end

function audit = build_generation_audit(src, source_name, source_case)
define_constants;
source_gen_row = [292; 332; 357; 358];
expected_bus = [651; 774; 900; 900];
expected_status = [1; 0; 0; 0];
if any(src.gen(source_gen_row, GEN_BUS) ~= expected_bus) || ...
        any(src.gen(source_gen_row, GEN_STATUS) ~= expected_status)
    error('add_npcc_perform_upny_coned_detail:GenerationAuditIdentity', ...
        'A Phase 1B source generation record changed identity or status.');
end
source_bus = src.gen(source_gen_row, GEN_BUS);
source_bus_name = strings(4, 1);
for k = 1:4
    bi = find(src.bus(:, BUS_I) == source_bus(k), 1);
    source_bus_name(k) = string(strtrim(src.bus_name{bi}));
end
raw_generator_id = ["x"; "C1"; "1"; "2"];
device_role = ["ny_only_boundary_proxy"; "offline_combined_cycle"; ...
    "offline_nuclear_steam"; "offline_nuclear_steam"];
gen_status = src.gen(source_gen_row, GEN_STATUS);
pg_mw = src.gen(source_gen_row, PG);
qg_mvar = src.gen(source_gen_row, QG);
pmin_mw = src.gen(source_gen_row, PMIN);
pmax_mw = src.gen(source_gen_row, PMAX);
qmin_mvar = src.gen(source_gen_row, QMIN);
qmax_mvar = src.gen(source_gen_row, QMAX);
transfer_policy = [ ...
    "do_not_copy_full_npcc_external_network_retained"; ...
    repmat("do_not_activate_pending_operating_source_qualification", 3, 1)];
audit_status = repmat("source_recorded_not_transferred", 4, 1);
notes = [ ...
    "Fixed negative generation is a PERFORM NY-only boundary artifact"; ...
    "Offline source record does not justify commitment"; ...
    "Buchanan/Indian Point unit 1 is offline in the source snapshot"; ...
    "Buchanan/Indian Point unit 2 is offline in the source snapshot"];
audit = table(repmat(source_name, 4, 1), repmat(source_case, 4, 1), ...
    source_gen_row, source_bus, source_bus_name, raw_generator_id, ...
    device_role, gen_status, pg_mw, qg_mvar, pmin_mw, pmax_mw, ...
    qmin_mvar, qmax_mvar, transfer_policy, audit_status, notes, ...
    'VariableNames', {'source_model','source_case','source_gen_row', ...
    'source_bus','source_bus_name','raw_generator_id','device_role', ...
    'gen_status','pg_mw','qg_mvar','pmin_mw','pmax_mw','qmin_mvar', ...
    'qmax_mvar','transfer_policy','audit_status','notes'});
end

function mpc = append_bus_name(mpc, name)
if ~isfield(mpc, 'bus_name'), return; end
if iscell(mpc.bus_name)
    mpc.bus_name{end + 1, 1} = name;
elseif isstring(mpc.bus_name)
    mpc.bus_name(end + 1, 1) = string(name);
else
    mpc.bus_name = [cellstr(mpc.bus_name); {name}];
end
end

function mpc = install_overlay_zone_metadata(mpc, bus_ids, zones)
if ~isfield(mpc, 'userdata'), mpc.userdata = struct(); end
if ~isfield(mpc.userdata, 'ny_lite'), mpc.userdata.ny_lite = struct(); end
existing = struct([]);
if isfield(mpc.userdata.ny_lite, 'transit_zone_metadata')
    existing = mpc.userdata.ny_lite.transit_zone_metadata;
end
for k = 1:numel(bus_ids)
    entry = struct('bus_id', bus_ids(k), 'physical_zone', char(zones(k)), ...
        'load_allocation_group', char(zones(k)), ...
        'nyiso_zone_name', 'HUD VL', 'nyiso_zone_id', 7, ...
        'perform_zone_code', 71);
    existing = append_struct(existing, entry);
end
mpc.userdata.ny_lite.transit_zone_metadata = existing;
end

function values = append_unique(values, additions)
values = values(:);
for k = 1:numel(additions)
    if ~ismember(additions(k), values)
        values(end + 1, 1) = additions(k); %#ok<AGROW>
    end
end
end

function out = append_struct(out, entry)
if isempty(out), out = entry; else, out(end + 1) = entry; end
end

function name = normalize_attachment_name(value)
name = upper(strtrim(string(value)));
name = regexprep(name, '\s+', ' ');
if name == "PLEASANT VLY", name = "PLEASANT VALLEY"; end
end

function zone = model_physical_zone(mpc, row)
if ~isfield(mpc, 'userdata') || ...
        ~isfield(mpc.userdata, 'nyiso_physical_zone')
    error('add_npcc_perform_upny_coned_detail:ZoneMetadata', ...
        'NYISO physical-zone metadata is missing.');
end
values = mpc.userdata.nyiso_physical_zone;
if iscell(values), zone = string(values{row}); else, zone = string(values(row)); end
zone = upper(strtrim(zone));
end

function zone = source_zone(area)
switch area
    case 71
        zone = "G";
    case 73
        zone = "H";
    otherwise
        zone = "";
end
end
