function [mpc, report] = add_npcc_perform_eg_corridor(mpc, options)
%ADD_NPCC_PERFORM_EG_CORRIDOR Append the source-backed Phase 1A E-G overlay.
%   This function is for the full 143-bus S7/Phase-0 structural parent, not
%   the 49-bus S11 diagnostic core. It appends four retained PERFORM buses and
%   seven physical PERFORM branches while preserving every existing row.
%
%   Existing exact-name attachments:
%       model 43 EDIC   <-> PERFORM 1233 EDIC,   345 kV, Zone E
%       model 76 RAMAPO <-> PERFORM 1519 RAMAPO, 345 kV, Zone G
%
%   Added PERFORM terminals: 1228 FRASER, 1222 COOPERS CORNER,
%   1567 MARCY, and 772 ROCK TAVERN. No synthetic attachment impedance is
%   introduced. The result is 147 buses, 253 branches, and 62 generators.
%
%   The overlay is an unpromoted Phase 1A candidate. Overlapping aggregate
%   NPCC rows still require a passive multi-terminal residual fit, followed by
%   same-snapshot, held-out response, and public-hour validation.

if nargin < 2, options = struct(); end
if ~isfield(options, 'write_registers'), options.write_registers = false; end
if ~isfield(options, 'register_dir')
    options.register_dir = fileparts(mfilename('fullpath'));
end
if ~isfield(options, 'verbose'), options.verbose = true; end
if ~isfield(options, 'neutral_angle_bounds'), options.neutral_angle_bounds = true; end

helper_dir = fileparts(mfilename('fullpath'));
case_dir = fileparts(helper_dir);
root = fileparts(case_dir);
perform_dir = fullfile(root, 'PERFORM', ...
    'On Peak 2019 v23_Perform_NY', 'On Peak 2019 v23');
addpath(case_dir); addpath(helper_dir); addpath(perform_dir);
define_constants;

validate_parent(mpc);
src = nyiso_On_Peak_v23_shunts_as_z_load;

source_case = "PERFORM/On Peak 2019 v23_Perform_NY/On Peak 2019 v23/" + ...
    "nyiso_On_Peak_v23_shunts_as_z_load.m";
source_name = "full_PERFORM_2019_case";

attachment_model = [43; 76];
attachment_source = [1233; 1519];
attachment_zone = ["E"; "G"];
added_source_buses = [1228; 1222; 1567; 772];
added_zones = ["E"; "E"; "E"; "G"];

if any(ismember(added_source_buses, mpc.bus(:, BUS_I)))
    error('add_npcc_perform_eg_corridor:AlreadyPresent', ...
        'One or more Phase 1A PERFORM bus IDs already exist in the case.');
end

for k = 1:numel(attachment_model)
    mi = find(mpc.bus(:, BUS_I) == attachment_model(k), 1);
    si = find(src.bus(:, BUS_I) == attachment_source(k), 1);
    if isempty(mi) || isempty(si)
        error('add_npcc_perform_eg_corridor:MissingAttachment', ...
            'Missing model/source attachment pair %d/%d.', ...
            attachment_model(k), attachment_source(k));
    end
    if abs(mpc.bus(mi, BASE_KV) - src.bus(si, BASE_KV)) > 1e-9
        error('add_npcc_perform_eg_corridor:AttachmentVoltage', ...
            'Attachment pair %d/%d does not have matching base kV.', ...
            attachment_model(k), attachment_source(k));
    end
end

% Preserve source within-zone voltage/angle differences while aligning the
% source reference frame to the existing EDIC and Ramapo attachment buses.
e_model = find(mpc.bus(:, BUS_I) == 43, 1);
e_source = find(src.bus(:, BUS_I) == 1233, 1);
g_model = find(mpc.bus(:, BUS_I) == 76, 1);
g_source = find(src.bus(:, BUS_I) == 1519, 1);
va_offset = struct('E', mpc.bus(e_model, VA) - src.bus(e_source, VA), ...
    'G', mpc.bus(g_model, VA) - src.bus(g_source, VA));
vm_scale = struct('E', mpc.bus(e_model, VM) / src.bus(e_source, VM), ...
    'G', mpc.bus(g_model, VM) / src.bus(g_source, VM));

first_bus_row = size(mpc.bus, 1) + 1;
for k = 1:numel(added_source_buses)
    si = find(src.bus(:, BUS_I) == added_source_buses(k), 1);
    if isempty(si)
        error('add_npcc_perform_eg_corridor:MissingSourceBus', ...
            'PERFORM bus %d was not found.', added_source_buses(k));
    end
    new_bus = zeros(1, size(mpc.bus, 2));
    ncopy = min([13, size(src.bus, 2), size(mpc.bus, 2)]);
    new_bus(1:ncopy) = src.bus(si, 1:ncopy);
    new_bus([PD QD GS BS]) = 0;
    new_bus(BUS_TYPE) = PQ;
    z = char(added_zones(k));
    if z == 'E'
        new_bus(BUS_AREA) = mpc.bus(e_model, BUS_AREA);
    else
        new_bus(BUS_AREA) = mpc.bus(g_model, BUS_AREA);
    end
    new_bus(VA) = src.bus(si, VA) + va_offset.(z);
    new_bus(VM) = src.bus(si, VM) * vm_scale.(z);
    mpc.bus = [mpc.bus; new_bus];
    mpc = append_bus_name(mpc, strtrim(src.bus_name{si}));
end

source_branch_rows = [2137; 2131; 2154; 2133; 1567; 1568; 1571];
source_from = [1228; 1228; 1233; 1567; 772; 772; 772];
source_to = [1233; 1222; 1567; 1222; 1222; 1222; 1519];
model_from = [1228; 1228; 43; 1567; 772; 772; 772];
model_to = [43; 1222; 1567; 1222; 1222; 1222; 76];
circuit_id = ["1"; "1"; "1"; "1"; "1"; "2"; "1"];

first_branch_row = size(mpc.branch, 1) + 1;
for k = 1:numel(source_branch_rows)
    sr = source_branch_rows(k);
    if sr > size(src.branch, 1) || ...
            src.branch(sr, F_BUS) ~= source_from(k) || ...
            src.branch(sr, T_BUS) ~= source_to(k)
        error('add_npcc_perform_eg_corridor:SourceBranchIdentity', ...
            'PERFORM branch row %d no longer matches %d-%d CKT %s.', ...
            sr, source_from(k), source_to(k), circuit_id(k));
    end
    new_branch = zeros(1, size(mpc.branch, 2));
    ncopy = min([13, size(src.branch, 2), size(mpc.branch, 2)]);
    new_branch(1:ncopy) = src.branch(sr, 1:ncopy);
    new_branch(F_BUS) = model_from(k);
    new_branch(T_BUS) = model_to(k);
    if options.neutral_angle_bounds && size(mpc.branch, 2) >= ANGMAX
        new_branch(ANGMIN) = -360;
        new_branch(ANGMAX) = 360;
    end
    mpc.branch = [mpc.branch; new_branch];
end

physical_rows = (first_branch_row:size(mpc.branch, 1))';
mpc = install_overlay_zone_metadata(mpc, added_source_buses, added_zones);
mpc = attach_nyiso_zone_metadata(mpc);

[bus_map, branch_map, residual_register, physical_register, operator_map, ...
    residual_shunt_register, path_register] = ...
    build_registers(mpc, src, source_name, source_case, attachment_model, ...
    attachment_source, attachment_zone, added_source_buses, added_zones, ...
    source_branch_rows, source_from, source_to, model_from, model_to, ...
    circuit_id, physical_rows);

register_files = struct( ...
    'bus_map', 'npcc_perform_overlay_bus_map.csv', ...
    'branch_map', 'npcc_perform_overlay_branch_map.csv', ...
    'residual_register', 'npcc_residual_equivalent_register.csv', ...
    'residual_shunt_register', 'npcc_residual_shunt_register.csv', ...
    'path_register', 'npcc_overlay_path_register.csv', ...
    'physical_register', 'npcc_added_physical_circuit_register.csv', ...
    'interface_operator_map', 'npcc_2019_interface_operator_map.csv');

if options.write_registers
    if ~isfolder(options.register_dir)
        error('add_npcc_perform_eg_corridor:RegisterDirectory', ...
            'Register output directory does not exist: %s', options.register_dir);
    end
    ny_lite_writetable_lf(bus_map, ...
        fullfile(options.register_dir, register_files.bus_map));
    ny_lite_writetable_lf(branch_map, ...
        fullfile(options.register_dir, register_files.branch_map));
    ny_lite_writetable_lf(residual_register, ...
        fullfile(options.register_dir, register_files.residual_register));
    ny_lite_writetable_lf(residual_shunt_register, ...
        fullfile(options.register_dir, register_files.residual_shunt_register));
    ny_lite_writetable_lf(path_register, ...
        fullfile(options.register_dir, register_files.path_register));
    ny_lite_writetable_lf(physical_register, ...
        fullfile(options.register_dir, register_files.physical_register));
    ny_lite_writetable_lf(operator_map, ...
        fullfile(options.register_dir, register_files.interface_operator_map));
end

if ~isfield(mpc, 'userdata'), mpc.userdata = struct(); end
if ~isfield(mpc.userdata, 'ny_lite'), mpc.userdata.ny_lite = struct(); end
mpc.userdata.ny_lite.phase0_protected_branch_rows = unique([ ...
    get_optional_rows(mpc.userdata.ny_lite, 'phase0_protected_branch_rows'); ...
    physical_rows]);
mpc.userdata.npcc_perform_overlay = struct( ...
    'target_model', 'npcc_ny_lite_s13_npcc_augmented_2019', ...
    'model_role', 'unpromoted_phase1a_candidate', ...
    'structural_parent', ...
        'npcc_ny_lite_s7_seven_interface_perform_direct_candidate', ...
    'source_model', char(source_name), ...
    'source_case', char(source_case), ...
    'added_bus_rows', (first_bus_row:size(mpc.bus, 1))', ...
    'added_bus_ids', added_source_buses, ...
    'physical_branch_rows', physical_rows, ...
    'source_branch_rows', source_branch_rows, ...
    'register_files', register_files, ...
    'residualization_status', 'pending_phase1d_passive_multi_terminal_fit', ...
    'same_snapshot_status', 'pending', ...
    'heldout_response_status', 'pending', ...
    'public_hour_status', 'pending', ...
    'promotion_eligible', false);

report = struct( ...
    'buses_added', numel(added_source_buses), ...
    'branches_added', numel(source_branch_rows), ...
    'case_size', [size(mpc.bus, 1), size(mpc.branch, 1), size(mpc.gen, 1)], ...
    'physical_branch_rows', physical_rows, ...
    'source_branch_rows', source_branch_rows, ...
    'bus_map', bus_map, ...
    'branch_map', branch_map, ...
    'residual_register', residual_register, ...
    'residual_shunt_register', residual_shunt_register, ...
    'path_register', path_register, ...
    'physical_register', physical_register, ...
    'operator_map', operator_map, ...
    'register_files', register_files, ...
    'promotion_eligible', false, ...
    'promotion_blocker', ...
        "Phase 1D residualization and operating-response gates are pending");

if options.verbose
    fprintf(['Phase 1A source-backed E-G overlay: %d buses, %d branches, ' ...
        '%d generators.\n'], size(mpc.bus, 1), size(mpc.branch, 1), ...
        size(mpc.gen, 1));
    fprintf(['  Added 4 PERFORM terminals and 7 direct physical rows; ' ...
        'promotion remains blocked pending residualization and response gates.\n']);
end
end

function validate_parent(mpc)
define_constants;
required_original = (1:140)';
required_transit = [9001; 9002; 9003];
if size(mpc.bus, 1) ~= 143 || size(mpc.branch, 1) ~= 246 || ...
        size(mpc.gen, 1) ~= 62
    error('add_npcc_perform_eg_corridor:ParentDimensions', ...
        'Phase 1A requires the 143-bus/246-branch/62-generator S7 parent.');
end
if ~all(ismember(required_original, mpc.bus(:, BUS_I))) || ...
        ~all(ismember(required_transit, mpc.bus(:, BUS_I)))
    error('add_npcc_perform_eg_corridor:ParentIdentity', ...
        'The full original NPCC buses and all S7 transit buses are required.');
end
end

function mpc = append_bus_name(mpc, name)
if ~isfield(mpc, 'bus_name'), return; end
if iscell(mpc.bus_name)
    mpc.bus_name{end + 1, 1} = name;
elseif isstring(mpc.bus_name)
    mpc.bus_name(end + 1, 1) = string(name);
else
    mpc.bus_name = [cellstr(mpc.bus_name); {name}];
end
end

function mpc = install_overlay_zone_metadata(mpc, bus_ids, zones)
if ~isfield(mpc, 'userdata'), mpc.userdata = struct(); end
if ~isfield(mpc.userdata, 'ny_lite'), mpc.userdata.ny_lite = struct(); end
existing = struct([]);
if isfield(mpc.userdata.ny_lite, 'transit_zone_metadata')
    existing = mpc.userdata.ny_lite.transit_zone_metadata;
end
for k = 1:numel(bus_ids)
    if zones(k) == "E"
        zone_name = 'MHK VL'; zone_id = 5; code = 69;
    else
        zone_name = 'HUD VL'; zone_id = 7; code = 71;
    end
    entry = struct('bus_id', bus_ids(k), 'physical_zone', char(zones(k)), ...
        'load_allocation_group', char(zones(k)), ...
        'nyiso_zone_name', zone_name, 'nyiso_zone_id', zone_id, ...
        'perform_zone_code', code);
    existing = append_struct(existing, entry);
end
mpc.userdata.ny_lite.transit_zone_metadata = existing;
end

function [bus_map, branch_map, residual, physical, operators, ...
        residual_shunt, path_register] = ...
        build_registers(mpc, src, source_name, source_case, attachment_model, ...
        attachment_source, attachment_zone, added_source_buses, added_zones, ...
        source_branch_rows, source_from, source_to, model_from, model_to, ...
        circuit_id, physical_rows)
define_constants;

model_bus = [attachment_model; added_source_buses];
source_bus = [attachment_source; added_source_buses];
physical_zone = [attachment_zone; added_zones];
model_action = [repmat("retained_existing_npcc_attachment", 2, 1); ...
    repmat("appended_physical_terminal", 4, 1)];
terminal_electrical_policy = [repmat("retained_npcc_unchanged", 2, 1); ...
    repmat("pq_zero_injection_source_limits", 4, 1)];
overlay_path_id_bus = repmat("phase1a_e_g_edic_ramapo", 6, 1);
npcc_attachment_bus = [43; 76; 43; 43; 43; 76];
source_attachment_bus = [1233; 1519; 1233; 1233; 1233; 1519];
implementation_status = repmat("implemented_unpromoted_phase1a", 6, 1);
mapping_confidence = repmat("high_exact_name_voltage_zone", 6, 1);
model_bus_name = strings(6, 1); source_bus_name = strings(6, 1);
source_base_kv = zeros(6, 1); source_area = zeros(6, 1);
model_area = zeros(6, 1);
source_vm_pu = zeros(6, 1); source_va_deg = zeros(6, 1);
for k = 1:6
    mi = find(mpc.bus(:, BUS_I) == model_bus(k), 1);
    si = find(src.bus(:, BUS_I) == source_bus(k), 1);
    model_bus_name(k) = string(strtrim(mpc.bus_name{mi}));
    source_bus_name(k) = string(strtrim(src.bus_name{si}));
    source_base_kv(k) = src.bus(si, BASE_KV);
    source_area(k) = src.bus(si, BUS_AREA);
    model_area(k) = mpc.bus(mi, BUS_AREA);
    source_vm_pu(k) = src.bus(si, VM);
    source_va_deg(k) = src.bus(si, VA);
end
bus_map = table(model_bus, model_bus_name, model_action, ...
    terminal_electrical_policy, overlay_path_id_bus, ...
    npcc_attachment_bus, source_attachment_bus, ...
    repmat(source_name, 6, 1), repmat(source_case, 6, 1), source_bus, ...
    source_bus_name, source_base_kv, source_area, model_area, physical_zone, ...
    source_vm_pu, source_va_deg, mapping_confidence, implementation_status, ...
    'VariableNames', {'model_bus','model_bus_name','model_action', ...
    'terminal_electrical_policy', ...
    'overlay_path_id','npcc_attachment_bus','source_attachment_bus', ...
    'source_model','source_case','source_bus','source_bus_name', ...
    'source_base_kv','source_area','model_area','physical_zone','source_vm_pu', ...
    'source_va_deg','mapping_confidence','implementation_status'});

n = numel(source_branch_rows);
source_r_pu = src.branch(source_branch_rows, BR_R);
source_x_pu = src.branch(source_branch_rows, BR_X);
source_b_pu = src.branch(source_branch_rows, BR_B);
source_rate_a_mva = src.branch(source_branch_rows, RATE_A);
source_rate_b_mva = src.branch(source_branch_rows, RATE_B);
source_rate_c_mva = src.branch(source_branch_rows, RATE_C);
branch_classification = repmat("physical_circuit", n, 1);
construction_method = repmat( ...
    "direct_perform_electrical_copy_neutral_angle_bounds", n, 1);
dlr_eligible = false(n, 1);
dlr_data_status = repmat("pending_conductor_and_weather_mapping", n, 1);
mapping_confidence = repmat("high", n, 1);
residual_overlap_status = repmat("pending_phase1d_passive_fit", n, 1);
implementation_status = repmat("implemented_unpromoted_phase1a", n, 1);
overlay_path_id = repmat("phase1a_e_g_edic_ramapo", n, 1);
npcc_attachment_from_bus = repmat(attachment_model(1), n, 1);
npcc_attachment_to_bus = repmat(attachment_model(2), n, 1);
branch_map = table(physical_rows, model_from, model_to, ...
    overlay_path_id, npcc_attachment_from_bus, npcc_attachment_to_bus, ...
    repmat(source_name, n, 1), repmat(source_case, n, 1), ...
    source_branch_rows, source_from, source_to, circuit_id, source_r_pu, ...
    source_x_pu, source_b_pu, source_rate_a_mva, source_rate_b_mva, ...
    source_rate_c_mva, branch_classification, construction_method, ...
    dlr_eligible, dlr_data_status, mapping_confidence, ...
    residual_overlap_status, implementation_status, ...
    'VariableNames', {'model_branch_row','model_from_bus','model_to_bus', ...
    'overlay_path_id','npcc_attachment_from_bus','npcc_attachment_to_bus', ...
    'source_model','source_case','source_branch_row','source_from_bus', ...
    'source_to_bus','source_circuit_id','source_r_pu','source_x_pu', ...
    'source_b_pu','source_rate_a_mva','source_rate_b_mva', ...
    'source_rate_c_mva','branch_classification','construction_method', ...
    'dlr_eligible','dlr_data_status','mapping_confidence', ...
    'residual_overlap_status','implementation_status'});

residual_rows = [34; 36; 40; 42];
original_from_bus = mpc.branch(residual_rows, F_BUS);
original_to_bus = mpc.branch(residual_rows, T_BUS);
original_r_pu = mpc.branch(residual_rows, BR_R);
original_x_pu = mpc.branch(residual_rows, BR_X);
original_b_pu = mpc.branch(residual_rows, BR_B);
classification = repmat("aggregate_residual_candidate", 4, 1);
overlap_scope = ["New Scotland-Leeds/Fraser mesh"; ...
    "New Scotland-Marcy-EDIC mesh"; "E-F aggregate sensitivity"; ...
    "E-F aggregate sensitivity"];
fit_status = repmat("pending_phase1d_multi_terminal_fit", 4, 1);
passivity_status = repmat("not_yet_tested", 4, 1);
dlr_eligible_residual = false(4, 1);
freeze = false(4, 1);
fitted_r_pu = nan(4, 1); fitted_x_pu = nan(4, 1);
fitted_b_pu = nan(4, 1); fit_objective = nan(4, 1);
residual_resistance_nonnegative = false(4, 1);
passivity_min_eigenvalue = nan(4, 1);
passivity_gate_pass = false(4, 1);
residual = table(residual_rows, original_from_bus, original_to_bus, ...
    original_r_pu, original_x_pu, original_b_pu, classification, ...
    overlap_scope, fitted_r_pu, fitted_x_pu, fitted_b_pu, fit_objective, ...
    residual_resistance_nonnegative, passivity_min_eigenvalue, ...
    passivity_gate_pass, fit_status, passivity_status, ...
    dlr_eligible_residual, freeze, ...
    'VariableNames', {'model_branch_row','from_bus','to_bus','original_r_pu', ...
    'original_x_pu','original_b_pu','classification','overlap_scope', ...
    'fitted_r_pu','fitted_x_pu','fitted_b_pu','fit_objective', ...
    'residual_resistance_nonnegative','passivity_min_eigenvalue', ...
    'passivity_gate_pass','fit_status','passivity_status','dlr_eligible','freeze'});

residual_shunt = table(zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), false(0, 1), ...
    'VariableNames', {'model_bus','original_gs_mw_at_v1', ...
    'original_bs_mvar_at_v1','fitted_gs_mw_at_v1', ...
    'fitted_bs_mvar_at_v1','fit_status','passivity_status','provenance', ...
    'passivity_gate_pass'});

path_register = table("phase1a_e_g_edic_ramapo", "phase1a", ...
    attachment_model(1), attachment_model(2), attachment_source(1), ...
    attachment_source(2), attachment_zone(1), attachment_zone(2), ...
    "implemented_unpromoted_phase1a", "high_exact_name_voltage_zone", ...
    'VariableNames', {'overlay_path_id','phase_id', ...
    'npcc_attachment_from_bus','npcc_attachment_to_bus', ...
    'source_attachment_from_bus','source_attachment_to_bus', ...
    'from_zone','to_zone','implementation_status','mapping_confidence'});

physical = branch_map(:, {'model_branch_row','model_from_bus','model_to_bus', ...
    'overlay_path_id','npcc_attachment_from_bus','npcc_attachment_to_bus', ...
    'source_model','source_case','source_branch_row','source_from_bus','source_to_bus', ...
    'source_circuit_id','source_r_pu','source_x_pu','source_b_pu', ...
    'source_rate_a_mva','source_rate_b_mva','source_rate_c_mva', ...
    'branch_classification','construction_method','residual_overlap_status', ...
    'dlr_eligible','dlr_data_status','mapping_confidence','implementation_status'});

te_rows = find(source_branch_rows == 1567 | source_branch_rows == 1568);
interface_name = repmat("Total_East_diagnostic", numel(te_rows), 1);
component_name = repmat("E_G_Coopers_Rock_Tavern", numel(te_rows), 1);
model_branch_row = physical_rows(te_rows);
operator_sign = -ones(numel(te_rows), 1);
source_branch_row = source_branch_rows(te_rows);
source_circuit_id = circuit_id(te_rows);
is_exact_public_operator = false(numel(te_rows), 1);
operator_status = repmat("partial_phase1a_component_pending_final_cutset", ...
    numel(te_rows), 1);
notes = repmat("Eastbound E-to-G is negative source from-end flow; full public Total East operator remains pending", ...
    numel(te_rows), 1);
operators = table(interface_name, component_name, model_branch_row, ...
    operator_sign, source_branch_row, source_circuit_id, ...
    is_exact_public_operator, operator_status, notes);
end

function rows = get_optional_rows(s, field)
rows = [];
if isfield(s, field), rows = s.(field)(:); end
end

function out = append_struct(out, entry)
if isempty(out), out = entry; else, out(end + 1) = entry; end
end
