function out=apply_compact_2025_partial_spc(base,options)
%APPLY_COMPACT_2025_PARTIAL_SPC Separately registered late-2025 approximation.
% Preserves the frozen 66-NY-bus parent as input. Reuses only its zero-injection
% Adirondack proxy as a new 345-kV station role, adds five station sections,
% and retires overlapping functional equivalents once. This is not as-built.
% Commissioning facts, parameter assumptions and thermal surrogates are
% separate. No dispatch/interface observations are read by this helper.
if nargin<1||isempty(base),base=apply_compact_2025_generation(apply_compact_2025_infrastructure());end
if nargin<2,options=struct();end
options=defaults(options);
p=base.candidate;root=fileparts(fileparts(fileparts(mfilename('fullpath'))));
assert(~isfield(p.userdata,'compact_2025_partial_spc'), ...
    'partial_spc:AlreadyApplied','The partial SPC overlay may be applied only once.');
assert(p.baseMVA==100&&size(p.bus,1)==160&&size(p.branch,1)==290 ...
    &&size(p.gen,1)==64&&sum(base.ny_bus_mask)==66&&isequal(p,base.full_candidate) ...
    &&isfield(p.userdata,'compact_2025_generation'), ...
    'partial_spc:Parent','Expected the unchanged generation-applied 160-full/66-NY-bus modern construction.');
po=p.userdata.compact_2025.options;
assert(po.impedance_scale==1&&po.charging_scale==1&&po.rating_scale==1&&po.include_announced_2025_rcc, ...
    'partial_spc:Parent','Apply sensitivities to this overlay only; the infrastructure parent must be nominal.');
keys=string(base.branch_keys(:));
assert(numel(keys)==size(p.branch,1)&&numel(unique(keys))==numel(keys), ...
    'partial_spc:Identity','The parent must have one unique stable key per branch.');
retired_keys=["NY2025:SMART_PATH:"+(1:4)';"NPCC_S7:BRANCH_ROW:220"];
[ok,retired]=ismember(retired_keys,keys);
assert(all(ok)&&isequal(p.branch(retired,1:2),[1220 48;1220 48;1220 44;1220 44;49 48]) ...
    &&all(p.branch(retired,11)==1), ...
    'partial_spc:RetirementIdentity','Expected four active Smart Path templates and the active Plattsburgh-Moses equivalent.');
[ok,parent47]=ismember("NPCC_S7:BRANCH_ROW:47",keys);
assert(ok&&isequal(p.branch(parent47,[1 2 11]),[44 48 0]), ...
    'partial_spc:RetirementIdentity','The retired original Moses-Porter equivalent must remain off.');
ir=base.infrastructure_branch_register;
[ok,irrows]=ismember(retired_keys(1:4),string(ir.branch_key));
assert(all(ok)&&isequal(p.branch(retired(1:4),[3:6 9:11]), ...
    [ir.r_pu(irrows),ir.x_pu(irrows),ir.b_pu(irrows),ir.rate_a_mva(irrows), ...
    ir.tap(irrows),ir.shift_degree(irrows),ir.status(irrows)]) ...
    &&isequal(p.branch(retired(5),1:13),[49 48 .0156 .1536 0 2500 0 0 1 0 1 -360 360]), ...
    'partial_spc:RetirementHardware','Predecessor hardware differs from the registered nominal parent.');
[ok,ad]=ismember(1220,p.bus(:,1));
assert(ok&&p.bus(ad,10)==230&&all(p.bus(ad,3:6)==0)&&~any(p.gen(:,1)==1220) ...
    &&nnz(p.branch(:,11)>0&(p.branch(:,1)==1220|p.branch(:,2)==1220))==4, ...
    'partial_spc:AdirondackRole','Only the added zero-injection four-leg Adirondack proxy may change voltage role.');
[ok,anchor_rows]=ismember([48;43;49],p.bus(:,1));
assert(all(ok)&&isequal(p.bus(anchor_rows,10),[230;345;115]), ...
    'partial_spc:LandingVoltage','MosesE230, Edic345 and Plattsburgh115 identities are required.');

status_path=fullfile(root,'output','compact_ny_2025','sources','infrastructure_cutoff_status_audit.csv');
source_path=fullfile(root,'output','compact_ny_2025','sources','infrastructure_status_source_manifest.csv');
status=read_strings(status_path);sources=read_strings(source_path);
evidence_keys=["SPC_MH2";"SPC_MH3";"SPC_HA2";"SPC_HW2";"SPC_LINE11";"SPC_LINE13";"SPC_XFMR_2025"];
[ok,ev]=ismember(evidence_keys,status.asset_key);
assert(all(ok)&&all(ismember(status.cutoff_status(ev),["energized_before_cutoff";"in_service_before_cutoff"])), ...
    'partial_spc:Commissioning','All included named SPC facilities require positive pre-cutoff commissioning evidence.');
expected_dates=["2025-10-08";"2025-10-26";"2025-10-13";"2025-10-02";"2025-10-08";"2025-11-17";"2025-10"];
assert(isequal(status.documented_event_date(ev),expected_dates), ...
    'partial_spc:Commissioning','The pinned commissioning milestones changed.');
assert(isequal(string(status.nominal_voltage_kv(ev)),["230";"230";"345";"345";"345";"345";"345/230"]), ...
    'partial_spc:Commissioning','The verified nominal-voltage evidence changed.');
assert(all(ismember(["SPC_HA1";"SPC_LINE12"],status.asset_key)), ...
    'partial_spc:Commissioning','Deferred 2026 facility records must remain visible.');

c=p;c.branch(retired,11)=0;
old_ad_row=p.bus(ad,:);old_ad_name=string(p.bus_name{ad});
c.bus(ad,10)=345;c.bus_name{ad}='ADIRONDACK 345 SPC PROXY';
ids=(9120:9124)';names=["HAVERSTOCK 230 SPC PROXY";"HAVERSTOCK 345 SPC PROXY"; ...
    "AUSTIN ROAD 345 SPC PROXY";"WILLIS ANNEX 345 SPC PROXY";"WILLIS ANNEX 230 SPC PROXY"];
kv=[230;345;345;345;230];zones=["D";"D";"E";"D";"D"];anchors=[48;48;43;48;48];
assert(~any(ismember(ids,p.bus(:,1))),'partial_spc:BusCollision','New station IDs collide with parent IDs.');
for k=1:numel(ids)
    j=find(p.bus(:,1)==anchors(k));r=p.bus(j,:);r(1)=ids(k);r(2)=1;r(3:6)=0;r(10)=kv(k);
    c.bus(end+1,:)=r;c.bus_name{end+1,1}=char(names(k));
    zid=double(char(zones(k)))-double('A')+1;
    md=struct('bus_id',ids(k),'physical_zone',char(zones(k)), ...
        'load_allocation_group',char(zones(k)),'nyiso_zone_name',char(zones(k)), ...
        'nyiso_zone_id',zid,'perform_zone_code',64+zid);
    c.userdata.ny_lite.transit_zone_metadata(end+1)=md;
end
c=attach_nyiso_zone_metadata(c);
busreg=table([1220;ids],["ADIRONDACK 345 SPC PROXY";names],[345;kv], ...
    ["E";zones],[44;anchors],[true;false(5,1)], ...
    ["replaced_existing_added_zero_injection230_proxy";repmat("new_zero_injection_station_section",5,1)], ...
    repmat("declared_compact_zone_allocation_not_verified_NYISO_station_zone",6,1), ...
    'VariableNames',{'model_bus','model_bus_name','base_kv','physical_zone','initial_voltage_anchor', ...
    'reused_parent_bus_id','role','zone_assignment_basis'});
busreg.source_device_identity_verified=false(6,1);
old_zone=string(p.userdata.nyiso_physical_zone(ad));
buschange=struct('model_bus',1220,'before_bus_row',old_ad_row,'after_bus_row',c.bus(ad,:), ...
    'before_name',old_ad_name,'after_name',string(c.bus_name{ad}),'before_zone',old_zone, ...
    'after_zone',string(c.userdata.nyiso_physical_zone(ad)), ...
    'before_role',"historical_230kV_Adirondack_station_template", ...
    'after_role',"declared345kV_new_station_proxy_reusing_model_ID_not_device_identity", ...
    'original_NPCC_bus',false,'all_injections_zero',true);

% Physical X and shunt susceptance per mile, BEFORE voltage-base conversion.
% Source circuits are historical templates; route length and geometry remain
% assumptions. R is independently derived from the declared conductor at75C.
t=base.historical_template_register;
[ok,ti]=ismember(["1220_1230_1";"1220_1232_1"],string(t.source_key));
assert(all(ok)&&all(t.from_base_kv(ti)==230)&&all(t.to_base_kv(ti)==230) ...
    &&isequal(t.x_pu(ti),[.10931;.0655])&&isequal(t.b_pu(ti),[.41705;.2499]) ...
    &&isequal(t.estimated_length_miles(ti),[105.5;63.2]), ...
    'partial_spc:TemplateIdentity','Historical230kV template X/B/length changed.');
lib=dlr_conductor_library;dr=find(lib.conductor_code=="DRAKE_795_ACSR");
assert(isscalar(dr)&&lib.r_reference_c(dr)==75&&lib.r_ref_ohm_m(dr)>0, ...
    'partial_spc:Conductor','Expected the pinned positive AC75 Drake surrogate.');
line_keys=["MH2";"MH3";"HA2";"HW2";"LINE11";"LINE13"];
ends=[48 9120;48 9120;9121 1220;9121 9123;9122 43;1220 9122];
lengths=[2;2;83.7;35;42.5;11.6];bundles=[1;1;2;2;2;2];line_kv=[230;230;345;345;345;345];
% Public planning summer A converted to three-phase MVA, used as a finite
% research screen/assumed equipment ceiling, not verified terminal ampacity.
amps=[1089;1089;2177;3119;3119;3119];templates=[1;1;1;1;2;2];
spec=table();
for k=1:6
    src=t(ti(templates(k)),:);zb_src=src.from_base_kv^2/p.baseMVA;
    zb_new=line_kv(k)^2/p.baseMVA;
    x_ohm_per_mile=src.x_pu*zb_src/src.estimated_length_miles;
    b_si_per_mile=src.b_pu/zb_src/src.estimated_length_miles;
    r_ohm=lib.r_ref_ohm_m(dr)*lengths(k)*1609.344/bundles(k);
    rxb=[r_ohm/zb_new,x_ohm_per_mile*lengths(k)/zb_new,b_si_per_mile*lengths(k)*zb_new];
    rate=sqrt(3)*line_kv(k)*amps(k)/1000;
    ss="SPC_"+line_keys(k)+";NYISO_2025_GOLD_BOOK";
    spec=add(spec,line_keys(k),ends(k,:),rxb,rate,0,"assumed_overhead_AC",ss, ...
        "catalog_AC75_R_planning_route_length_historical230_X_B_per_mile_rebased", ...
        "DRAKE_795_ACSR",bundles(k),lengths(k),src.source_key,true);
    spec.template_base_kv(end)=src.from_base_kv;spec.template_length_miles(end)=src.estimated_length_miles;
    spec.template_x_pu(end)=src.x_pu;spec.template_b_pu(end)=src.b_pu;
    spec.x_ohm_per_mile(end)=x_ohm_per_mile;spec.b_siemens_per_mile(end)=b_si_per_mile;
    spec.public_planning_summer_current_a(end)=amps(k);
end
% Explicit station transformers: own-base r=.005, x=.12 are assumptions.
% Ratings approximate public planning currents753A/2259A on the345-kV side.
tr_keys=["AT2";"AT3";"TR2"];tr_ends=[9120 9121;9120 9121;9123 9124];tr_mva=[450;450;1350];
for k=1:3
    spec=add(spec,tr_keys(k),tr_ends(k,:),[.005 .12 0]*p.baseMVA/tr_mva(k),tr_mva(k),1, ...
        "assumed_station_transformer","SPC_XFMR_2025;NYISO_OCT_OPERATIONS;NYISO_2025_GOLD_BOOK", ...
        "own450_or1350MVA_base_R005_X012_fixed_nominal_ratio_no_shunt_assumed", ...
        "",0,0,"",false);
end
% Relocate the original230-kV end while keeping the115/230-kV per-unit base
% and the complete regional series budget; no physical WRY/WPN claim.
r=p.branch(retired(5),:);
spec=add(spec,"PLATTS_REGIONAL_EQ",[49 9124],r(3:5),r(6),r(9), ...
    "inherited_regional_voltage_transforming_equivalent", ...
    "NPCC_S7:BRANCH_ROW:220;SPC_WRY1;SPC_WPN1;SPC_WPN2;SPC_W1", ...
    "relocate230kV_end_to_Willis_keep115_230_base_and_parent_R_X_B_whole_function_retired_once", ...
    "",0,nan,"NPCC_S7:BRANCH_ROW:220",false);
spec.shift_degree(end)=r(10);
spec.nominal_r_pu=spec.r_pu;spec.nominal_x_pu=spec.x_pu;spec.nominal_b_pu=spec.b_pu;
spec.nominal_rate_a_mva=spec.rate_a_mva;
adjust=spec.electrical_role~="inherited_regional_voltage_transforming_equivalent";
spec.r_pu(adjust)=spec.r_pu(adjust)*options.impedance_scale;
spec.x_pu(adjust)=spec.x_pu(adjust)*options.impedance_scale;
spec.b_pu(adjust)=spec.b_pu(adjust)*options.charging_scale;
spec.rate_a_mva(adjust)=spec.rate_a_mva(adjust)*options.rating_scale;
spec.model_branch_row=(size(p.branch,1)+(1:height(spec)))';
spec.status=ones(height(spec),1);spec.base_mva=repmat(p.baseMVA,height(spec),1);
[ok,f]=ismember(spec.from_bus,c.bus(:,1));[ok2,tt]=ismember(spec.to_bus,c.bus(:,1));assert(all(ok&ok2));
spec.from_base_kv=c.bus(f,10);spec.to_base_kv=c.bus(tt,10);
spec.equipment_limit_mva=spec.rate_a_mva;
spec.equipment_limit_policy=repmat("finite_reference_MVA_treated_as_assumed_equipment_ceiling_not_terminal_truth",height(spec),1);
spec.parameter_ground_truth_verified=false(height(spec),1);spec.physical_conductor_verified=false(height(spec),1);
spec.thermal_surrogate_qualified=false(height(spec),1);spec.circuits=ones(height(spec),1);
spec.conductor_choice_basis=repmat("none_nonthermal",height(spec),1);
spec.conductor_choice_basis(1:3)="planning_Drake_size_motivates_ACSR_surrogate_installed_conductor_unverified";
spec.conductor_choice_basis(4:6)="planning_ACSS_is_not_ACSR_library_uses_declared_Drake_ACSR_surrogate";
spec.resistance_reference_c=nan(height(spec),1);spec.resistance_reference_c(1:6)=75;
spec.effective_thermal_length_miles=nan(height(spec),1);
spec.effective_thermal_length_miles(1:6)=spec.length_miles(1:6)*options.impedance_scale;
br=[spec.from_bus spec.to_bus spec.r_pu spec.x_pu spec.b_pu ...
    repmat(spec.rate_a_mva,1,3) spec.tap spec.shift_degree spec.status repmat([-360 360],height(spec),1)];
if size(p.branch,2)>13,br(:,14:size(p.branch,2))=0;end
c.branch=[c.branch;br];keys=[keys;spec.branch_key];

[~,oldf]=ismember(p.branch(retired,1),p.bus(:,1));[~,oldt]=ismember(p.branch(retired,2),p.bus(:,1));
disposition=table(retired_keys,retired,p.branch(retired,1),p.branch(retired,2), ...
    p.bus(oldf,10),p.bus(oldt,10),ones(5,1),zeros(5,1), ...
    [repmat("whole_functional_replacement_not_individual_circuit_retirement_crosswalk",4,1); ...
    "relocated_regional_equivalent_whole_parent_row_retired"], ...
    [repmat(strjoin(spec.branch_key([1:3 5:9]),';'),4,1);strjoin(spec.branch_key([4 9 10]),';')], ...
    'VariableNames',{'parent_branch_key','parent_branch_row','historical_from_bus','historical_to_bus', ...
    'historical_from_base_kv','historical_to_base_kv','old_status','new_status','disposition','replacement_branch_keys'});
disposition.historical_endpoint_voltage_may_differ_from_current_bus=[true(4,1);false];
% Update the live status view while preserving exact predecessor rows/metadata.
ir.status(irrows)=0;ir.thermal_eligible(irrows)=false;ir.dlr_eligible(irrows)=false;

z=string(c.userdata.nyiso_physical_zone);ny=ismember(z,string(('A':'K')'));nyids=c.bus(ny,1);
nybr=ismember(c.branch(:,1),nyids)&ismember(c.branch(:,2),nyids);
active=c.branch(:,11)>0;[ok,f]=ismember(c.branch(active,1),c.bus(:,1));[ok2,tt]=ismember(c.branch(active,2),c.bus(:,1));
assert(all(ok&ok2),'partial_spc:Endpoints','Active endpoints are invalid.');
components=conncomp(graph(f,tt,[],size(c.bus,1)));
priorbus=p.bus;priorbus(ad,10)=345;priorbr=p.branch;priorbr(retired,11)=0;
[ok,keep]=ismember(["NPCC_S7:BRANCH_ROW:43";"NPCC_S7:BRANCH_ROW:46"; ...
    "NPCC_S7:BRANCH_ROW:52";"NPCC_S7:BRANCH_ROW:53"],string(base.branch_keys));
assert(all(ok),'partial_spc:SupportIdentity','Required Edic/Porter/Colton/Moses support keys are absent.');
gate_names=["original46_NPCC_NY_buses_preserved";"only_added_Adirondack_proxy_voltage_changes"; ...
    "all_parent_injections_shunts_generators_costs_preserved";"five_new_zero_injection_nodes"; ...
    "five_exact_predecessors_retired_once";"old_parent47_stays_off"; ...
    "71_NY_buses_under200";"connected_full_network";"all_record_endpoints_valid"; ...
    "voltage_transitions_have_explicit_transformers";"new_passive_finite_bounded_records"; ...
    "unique_stable_branch_keys";"Edic_Porter_Colton_support_unchanged"; ...
    "source11_downstate_circuits_unchanged";"no_2026_HA1_or_LINE12";"new_thermal_whitelist_exact6"];
passed=[all(ismember((37:82)',nyids));isequal(c.bus(1:160,:),priorbus); ...
    isequal(c.bus(1:160,3:6),p.bus(:,3:6))&&isequal(c.gen,p.gen)&&isequal(c.gencost,p.gencost); ...
    all(c.bus(161:end,3:6)==0,'all')&&~any(ismember(c.gen(:,1),ids)); ...
    isequal(c.branch(1:290,:),priorbr);c.branch(parent47,11)==0; ...
    sum(ny)==71&&sum(ny)<=200;numel(unique(components))==1; ...
    all(ismember(c.branch(:,1:2),c.bus(:,1)),'all'); ...
    all(spec.tap(spec.from_base_kv~=spec.to_base_kv)==1); ...
    all(isfinite(br),'all')&&all(spec.r_pu>0&spec.x_pu>0&spec.b_pu>=0&spec.rate_a_mva>0); ...
    numel(unique(keys))==numel(keys);isequal(c.branch(keep,:),p.branch(keep,:)); ...
    isequal(c.branch(247:257,:),p.branch(247:257,:)); ...
    ~any(ismember(spec.branch_key,["NY2025_SPC:HA1";"NY2025_SPC:LINE12"])); ...
    nnz(spec.thermal_surrogate_eligible)==6&&all(spec.thermal_surrogate_eligible(1:6))];
gates=table(gate_names,passed,'VariableNames',{'metric','passed'});
assert(all(gates.passed),'partial_spc:Validation','Partial SPC structural/accounting validation failed.');
c.userdata.compact_2025_partial_spc=struct('cutoff',"2025-12-31", ...
    'options',options,'retired_branch_keys',retired_keys,'new_branch_keys',spec.branch_key, ...
    'new_bus_ids',ids,'reused_Adirondack_model_bus',1220,'new_bus_count',5, ...
    'operating_scope',"fixed_year_end_topology_counterfactual_stress_cases_not_as_operated_hourly", ...
    'as_built_network',false,'exact_public_interface_definition',false, ...
    'electrical_baseline_qualified',false,'dlr_ready',false);
c.userdata.compact_npcc.ny_bus_count=sum(ny);
out=base;out.partial_spc_parent=p;out.candidate=c;out.full_candidate=c;
out.branch_keys=keys;out.ny_bus_mask=ny;out.ny_bus_ids=nyids;out.ny_branch_mask=nybr;
out.ny_generator_mask=ismember(c.gen(:,1),nyids);out.infrastructure_branch_register=ir;
out.partial_spc_branch_register=spec;out.partial_spc_bus_register=busreg;
out.partial_spc_bus_role_change=buschange;out.partial_spc_branch_dispositions=disposition;
out.partial_spc_predecessor_branch_matrix=p.branch(retired,:);
out.partial_spc_predecessor_infrastructure_register=base.infrastructure_branch_register(irrows,:);
out.partial_spc_parent_project_register=base.project_register;
pr=base.project_register;j=find(string(pr.project_id)=="SMART_PATH_CONNECT");
assert(isscalar(j),'partial_spc:ProjectIdentity','Expected one parent Smart Path Connect project record.');
pr.included(j)=true;pr.status_basis(j)="selected_partial2025_with2026_exclusions";
pr.commissioning_evidence_date(j)="2025-09_to11_partial_2026-03_to06_remaining";
pr.source_url(j)="https://documents.dps.ny.gov/public/MatterManagement/CaseMaster.aspx?MNO=21-T-0340&MatterSeq=65705";
j=find(string(pr.project_id)=="SMART_PATH");
pr.included(j)=false;pr.status_basis(j)="historical230_templates_retired_core_represented_by_partial_SPC";
out.project_register=pr;
out.partial_spc_parent_bus_map_2025=base.bus_map_2025;
bm=base.bus_map_2025;j=find(bm.model_bus==1220);
bm.base_kv(j)=345;bm.model_bus_name(j)="ADIRONDACK 345 SPC PROXY";
bm.source_bus_name_voltage_identity(j)=nan;
bm.injection_policy(j)="replacement_zero_injection345_proxy_not_historical230_device_identity";
out.bus_map_2025=bm;
out.partial_spc_parent_assumption_register=base.assumption_register;
ar=base.assumption_register;
j=find(string(ar.assumption)=="excluded_future");
ar.declaration(j)="CHPE_RCC_LongIslandCity_Propel_and_SPC_HA1_LINE12_2026_excluded_selected_partial_SPC2025_included";
out.assumption_register=ar;
out.partial_spc_commissioning_register=status(ev,:);
selected_source=startsWith(sources.source_id,"SPC_")|startsWith(sources.source_id,"NYISO_");
out.partial_spc_commissioning_sources=sources(selected_source,:);
out.partial_spc_source_manifest=manifest(root,status_path,source_path);
out.partial_spc_assumptions=table(["zone_assignment";"parameter_scope";"rating_scope"; ...
    "regional_equivalent";"support_network";"excluded_equipment";"thermal_scope";"operating_scope"], ...
    ["Haverstock_Willis_D_Adirondack_Austin_E_are_compact_proxy_allocations_not_verified_NYISO_bus_zones"; ...
    "catalog_AC75_R_historical_physical_X_B_per_mile_public_planning_lengths_all_declared_surrogates"; ...
    "planning_summer_A_to_MVA_and_transformer_ratings_are_finite_assumed_equipment_ceilings"; ...
    "Platts115_landing_keeps_parent115_230_voltage_transforming_R_X_budget_local_Willis_Ryan_Patnode_network_aggregated"; ...
    "Edic_Porter_Colton_support_retained_as_NPCC_equivalents_not_proved_late2025_physical_topology"; ...
    "HA1_and_Adirondack_Marcy12_2026_excluded_unverified_transitional230_paths_not_recreated"; ...
    "six_new_OH_surrogates_only_no_installed_conductor_claim_ACSS_design_uses_explicit_ACSR_surrogate"; ...
    "year_end2025_topology_applied_to_other2025_dispatch_hours_is_counterfactual_not_as_operated"], ...
    'VariableNames',{'assumption','declaration'});
out.partial_spc_validation=struct('pass',all(gates.passed),'gates',gates);
out.validation=out.partial_spc_validation;out.electrical_baseline_qualified=false;out.dlr_ready=false;
end

function s=add(s,key,ends,rxb,rate,tap,role,sources,basis,conductor,bundle,len,template,thermal)
r=table("NY2025_SPC:"+key,ends(1),ends(2),rxb(1),rxb(2),rxb(3),rate,tap,0, ...
    role,sources,basis,conductor,bundle,len,template,thermal,nan,nan,nan,nan,nan,nan,nan, ...
    'VariableNames',{'branch_key','from_bus','to_bus','r_pu','x_pu','b_pu','rate_a_mva', ...
    'tap','shift_degree','electrical_role','source_ids','parameter_basis','conductor_code','bundle_count', ...
    'length_miles','historical_template_key','thermal_surrogate_eligible','template_base_kv', ...
    'template_length_miles','template_x_pu','template_b_pu','x_ohm_per_mile','b_siemens_per_mile', ...
    'public_planning_summer_current_a'});
s=[s;r];
end

function o=defaults(o)
d=struct('impedance_scale',1,'charging_scale',1,'rating_scale',1);
assert(isstruct(o)&&isscalar(o)&&all(ismember(fieldnames(o),fieldnames(d))), ...
    'partial_spc:Options','Unknown partial SPC option.');
for f=string(fieldnames(d))',if ~isfield(o,f),o.(f)=d.(f);end,end
for f=string(fieldnames(d))'
    assert(isnumeric(o.(f))&&isscalar(o.(f))&&isreal(o.(f))&&isfinite(o.(f)), ...
        'partial_spc:Options','Sensitivity options must be finite real scalars.');
end
assert(o.impedance_scale>=.75&&o.impedance_scale<=1.25 ...
    &&o.charging_scale>=0&&o.charging_scale<=1.5&&o.rating_scale>=.8&&o.rating_scale<=1.2, ...
    'partial_spc:SensitivityBounds','Sensitivity must remain within preregistered finite ranges.');
end

function t=manifest(root,a,b)
files={a;b;mfilename('fullpath');which('dlr_conductor_library')};
if ~endsWith(files{3},'.m'),files{3}=[files{3} '.m'];end
artifact=strings(4,1);relative_path=artifact;sha256=artifact;
for k=1:4
    [~,name,ext]=fileparts(files{k});artifact(k)=string([name ext]);
    relative_path(k)=replace(string(files{k}),string(root)+filesep,"");
    relative_path(k)=replace(relative_path(k),"\","/");sha256(k)=hash_file(files{k});
end
t=table(["commissioning_status";"commissioning_sources";"partial_spc_builder";"conductor_surrogate"], ...
    artifact,relative_path,sha256,repmat("pinned_local_source_input_no_ignored_cache_dependency",4,1), ...
    'VariableNames',{'source_id','artifact','relative_path','sha256','use_policy'});
t.source_path=t.relative_path;t.sha256_lf_normalized=t.sha256;
t.hash_policy=repmat("SHA256_UTF8_source_bytes_with_CRLF_normalized_to_LF",height(t),1);
end

function h=hash_file(path)
fid=fopen(path,'rb');assert(fid>=0,'partial_spc:SourceFile','Cannot read source file.');
cleaner=onCleanup(@()fclose(fid)); %#ok<NASGU>
raw=fread(fid,Inf,'*uint8');raw=uint8(strrep(char(raw'),sprintf('\r\n'),sprintf('\n')));
md=java.security.MessageDigest.getInstance('SHA-256');
md.update(raw);h=lower(string(reshape(dec2hex(typecast(md.digest(),'uint8'),2).',1,[])));
end

function t=read_strings(path)
% Preserve mixed day/month/hour precision and slash-containing voltages.
o=detectImportOptions(path,'TextType','string');o=setvartype(o,o.VariableNames,'string');
t=readtable(path,o);
end
