function out=apply_ny_boundary_injections(normalized,boundary,options)
%APPLY_NY_BOUNDARY_INJECTIONS Separate native generation, gross load and ties.
% PD_effective=PD_gross-P_boundary and QD_effective=QD_gross-Q_boundary.
% Shared landing buses are aggregated with accumarray; removal uses exact
% source-generator rows/keys and never deletes native generators by bus ID.
% Reference placeholders are removed without injecting either P or Q.
if nargin<3,options=struct();end
define_constants;
assert(isstruct(normalized)&&isfield(normalized,'source')&&isfield(normalized,'generator_inventory'), ...
    'apply_ny_boundary_injections:NormalizedSource','Normalized original-source inventories required.');
m=normalized.source;
assert(~isfield(m,'userdata')||~isfield(m.userdata,'ny_boundary_application'), ...
    'apply_ny_boundary_injections:AlreadyApplied','Boundary assembly has already been applied.');
assert(isfield(boundary,'boundary_register')&&isfield(boundary,'reference_register'), ...
    'apply_ny_boundary_injections:Register','Boundary and reference registers are required.');
b=boundary.boundary_register;r=boundary.reference_register;records=[b;r];
required={'device_key','source_gen_row','source_bus','canonical_status', ...
    'is_external_exchange','p_injection_mw','q_injection_mvar','source_device_role'};
assert(all(ismember(required,records.Properties.VariableNames)), ...
    'apply_ny_boundary_injections:Schema','Injection register schema is incomplete.');
remove=double(records.source_gen_row);
assert(numel(unique(remove))==numel(remove)&&numel(unique(string(records.device_key)))==height(records)&& ...
    all(remove==fix(remove)&remove>=1&remove<=size(m.gen,1)), ...
    'apply_ny_boundary_injections:DuplicateIdentity','Each source device must be removed exactly once.');
assert(isequal(m.gen(remove,GEN_BUS),double(records.source_bus))&& ...
    isequal(m.gen(remove,GEN_STATUS),double(records.canonical_status)), ...
    'apply_ny_boundary_injections:SourceIdentity','Generator bus/status pointers changed.');
inventory=normalized.generator_inventory;
[known,gi]=ismember(string(records.device_key),string(inventory.device_key));
assert(all(known)&&isequal(double(inventory.source_gen_row(gi)),remove)&& ...
    all(string(inventory.source_device_role(gi))==string(records.source_device_role)), ...
    'apply_ny_boundary_injections:DeviceIdentity','Stable device identity or classification mismatch.');
expected=double(inventory.source_gen_row(ismember(string(inventory.source_device_role), ...
    ["external_boundary_proxy","reference_placeholder"])));
assert(isequal(sort(remove),sort(expected)), ...
    'apply_ny_boundary_injections:IncompleteRemoval','Every boundary/reference device must be accounted for.');
assert(all(logical(b.is_external_exchange))&&~any(logical(r.is_external_exchange))&& ...
    all(string(b.source_device_role)=="external_boundary_proxy")&& ...
    all(string(r.source_device_role)=="reference_placeholder")&& ...
    all(r.p_injection_mw==0&r.q_injection_mvar==0), ...
    'apply_ny_boundary_injections:ReferencePolicy','Reference placeholders must contribute no P/Q.');
inactive=b.canonical_status<=0;
assert(all(b.p_injection_mw(inactive)==0&b.q_injection_mvar(inactive)==0), ...
    'apply_ny_boundary_injections:InactiveInjection','Inactive source devices must inject zero P/Q.');
assert(all(isfinite(records.p_injection_mw)&isfinite(records.q_injection_mvar)), ...
    'apply_ny_boundary_injections:NonfiniteInjection','Boundary P/Q must be finite.');
assert(isequal(m.bus(:,BUS_I),boundary.source_bus_ids)&& ...
    isequal(m.bus(:,[PD QD]),boundary.gross_loads)&&size(m.gen,1)==boundary.source_gen_count, ...
    'apply_ny_boundary_injections:GrossLoadIdentity','Gross source loads or device count changed.');
[found,bi]=ismember(b.source_bus,m.bus(:,BUS_I));
assert(all(found),'apply_ny_boundary_injections:Landing','NY source landing identity missing.');
n=size(m.bus,1);p=accumarray(bi,double(b.p_injection_mw),[n,1]);
q=accumarray(bi,double(b.q_injection_mvar),[n,1]);
pd_gross=m.bus(:,PD);qd_gross=m.bus(:,QD);
m.bus(:,PD)=pd_gross-p;m.bus(:,QD)=qd_gross-q;
% Initial operating values come from the declared reproduced snapshot only.
snapshot=boundary.snapshot_case;
assert(isequal(snapshot.bus(:,BUS_I),m.bus(:,BUS_I))&& ...
    isequal(snapshot.gen(:,GEN_BUS),m.gen(:,GEN_BUS)), ...
    'apply_ny_boundary_injections:SnapshotIdentity','Snapshot source identity changed.');
br=double(b.source_gen_row);on=double(b.canonical_status>0);
assert(isequal(double(b.p_injection_mw),snapshot.gen(br,PG).*on)&& ...
    isequal(double(b.q_injection_mvar),snapshot.gen(br,QG).*on), ...
    'apply_ny_boundary_injections:FrozenSnapshot','Registered fixed PQ drifted from its declared snapshot.');
m.bus(:,[VM VA])=snapshot.bus(:,[VM VA]);
m.gen(:,[PG QG])=snapshot.gen(:,[PG QG]);
old_count=size(m.gen,1);keep=true(old_count,1);keep(remove)=false;m.gen=m.gen(keep,:);
% Any native generation sharing a landing remains a native PV/control bus.
affected=ismember(m.bus(:,BUS_I),records.source_bus);
active_native_buses=m.gen(m.gen(:,GEN_STATUS)>0,GEN_BUS);
m.bus(affected&~ismember(m.bus(:,BUS_I),active_native_buses),BUS_TYPE)=PQ;
if isfield(m,'gencost')&&~isempty(m.gencost)
    if size(m.gencost,1)==old_count,m.gencost=m.gencost(keep,:);
    elseif size(m.gencost,1)==2*old_count,m.gencost=m.gencost([keep;keep],:);
    else,error('apply_ny_boundary_injections:CostIdentity','Unknown generator cost row mapping.');end
end
metadata={'gen_name','genfuel','gentype'};
for k=1:numel(metadata)
    f=metadata{k};
    if isfield(m,f)
        assert(numel(m.(f))==old_count,'apply_ny_boundary_injections:Metadata','Generator metadata row mismatch.');
        value=m.(f);m.(f)=value(keep,:);
    end
end
native=inventory(ismember(inventory.source_gen_row,find(keep)),:);
[~,order]=sort(native.source_gen_row);native=native(order,:);
native.native_gen_row=(1:height(native))';
assert(height(native)==size(m.gen,1)&& ...
    ~any(ismember(string(native.source_device_role),["external_boundary_proxy","reference_placeholder"])), ...
    'apply_ny_boundary_injections:NativeClassification','Boundary devices remain in native generation.');
ledger=table(m.bus(:,BUS_I),pd_gross,qd_gross,p,q,m.bus(:,PD),m.bus(:,QD), ...
    'VariableNames',{'source_bus','pd_gross_mw','qd_gross_mvar','p_boundary_mw', ...
    'q_boundary_mvar','pd_effective_mw','qd_effective_mvar'});
accounting=table(sum(pd_gross),sum(qd_gross),sum(p),sum(q),sum(m.bus(:,PD)),sum(m.bus(:,QD)), ...
    max(abs(m.bus(:,PD)+p-pd_gross)),max(abs(m.bus(:,QD)+q-qd_gross)),height(b),height(r), ...
    'VariableNames',{'gross_pd_mw','gross_qd_mvar','external_p_injection_mw','external_q_injection_mvar', ...
    'effective_pd_mw','effective_qd_mvar','max_P_assembly_error_mw','max_Q_assembly_error_mvar', ...
    'external_records_removed','reference_records_removed'});
online=m.gen(:,GEN_STATUS)>0;
accounting.native_pg_mw=sum(m.gen(online,PG));
accounting.native_qg_mvar=sum(m.gen(online,QG));
rr=double(r.source_gen_row);ron=double(r.canonical_status>0);
accounting.removed_reference_snapshot_pg_mw=sum(snapshot.gen(rr,PG).*ron);
accounting.removed_reference_snapshot_qg_mvar=sum(snapshot.gen(rr,QG).*ron);
accounting.native_plus_boundary_minus_gross_p_mw=accounting.native_pg_mw+sum(p)-sum(pd_gross);
assert(accounting.max_P_assembly_error_mw<1e-9&&accounting.max_Q_assembly_error_mvar<1e-9);
if ~isfield(m,'userdata'),m.userdata=struct();end
m.userdata.ny_boundary_application=struct('snapshot_kind',boundary.snapshot_kind, ...
    'gross_pd_mw',pd_gross,'gross_qd_mvar',qd_gross,'boundary_p_mw',p,'boundary_q_mvar',q, ...
    'removed_device_keys',string(records.device_key),'reference_policy','removed_no_PQ_injection', ...
    'native_angle_reference_required',~any(m.bus(:,BUS_TYPE)==REF),'promotion_eligible',false);
out=struct('candidate',m,'boundary_register',b,'reference_register',r, ...
    'bus_injection_ledger',ledger,'native_generator_map',native,'accounting',accounting, ...
    'source_gen_keep',keep,'reference_support_added',false,'promotion_eligible',false);
if isfield(options,'write_outputs')&&options.write_outputs
    if ~isfield(options,'output_dir'),options.output_dir=fileparts(mfilename('fullpath'));end
    if ~isfolder(options.output_dir),mkdir(options.output_dir);end
    ny_lite_writetable_lf(ledger,fullfile(options.output_dir,'ny_bus_gross_effective_injections.csv'));
    ny_lite_writetable_lf(accounting,fullfile(options.output_dir,'ny_boundary_assembly_accounting.csv'));
    ny_lite_writetable_lf(native,fullfile(options.output_dir,'ny_native_generator_map.csv'));
end
end
