function outputs = build_ny_voltage_reference_sets(options)
%BUILD_NY_VOLTAGE_REFERENCE_SETS Build auditable voltage-control references.
%   Separates original NPCC VG fields, S1 OPF-solved voltage references,
%   current S7 model values, provisional PERFORM zonal aggregates, and
%   scenario boundary-equivalent references.

if nargin < 1, options = struct(); end
helper_dir = fileparts(mfilename('fullpath'));
case_dir = fileparts(helper_dir);
workspace_dir = fileparts(case_dir);
addpath(case_dir); addpath(helper_dir);
options = defaults(options, helper_dir, workspace_dir);
define_constants;

model = attach_nyiso_zone_metadata(loadcase(options.structural_case));
original = loadcase(options.original_case);
s1 = loadcase(options.s1_case);

references = table();
references = append_table(references, case_reference_rows(model, original, ...
    "ORIGINAL_NPCC_VG_REFERENCE", "original_npcc_vg_field", ...
    "npcc_original", "Original NPCC generator matrix VG", "unknown", ...
    "medium", "same retained bus number"));
references = append_table(references, case_reference_rows(model, s1, ...
    "S1_OPF_SOLVED_REFERENCE", "numerical_continuation_reference", ...
    "npcc_ny_lite_s1_acopf_feasible_uncalibrated", ...
    "S1 ACOPF result saved with opf.use_vg = 0", "S1 build", ...
    "high numerical; low physical", "same retained bus number"));
references = append_table(references, case_reference_rows(model, model, ...
    "CURRENT_S7_MODEL_REFERENCE", "current_model_vg_field", ...
    options.structural_case, "Current S7 generator matrix VG", "current", ...
    "high numerical; mixed provenance", "current model bus aggregation"));

[perform_rows, perform_zone_summary, perform_controls, perform_control_coverage, ...
    perform_classification_summary] = ...
    perform_reference_rows(model, options);
references = append_table(references, perform_rows);
boundary_rows = boundary_reference_rows(model, options);
references = append_table(references, boundary_rows);
references = sortrows(references, {'reference_set','model_bus'});

provenance = s1_provenance_rows(original, s1);
coverage = coverage_rows(model, references);
writetable(references, options.reference_file);
writetable(coverage, options.coverage_file);
writetable(provenance, options.s1_provenance_file);
writetable(perform_zone_summary, options.perform_zone_file);
writetable(perform_controls, options.perform_control_file);
writetable(perform_control_coverage, options.perform_control_coverage_file);
writetable(perform_classification_summary, ...
    options.perform_classification_summary_file);

outputs = struct('reference_file', options.reference_file, ...
    'coverage_file', options.coverage_file, ...
    's1_provenance_file', options.s1_provenance_file, ...
    'perform_zone_file', options.perform_zone_file, ...
    'perform_control_file', options.perform_control_file, ...
    'perform_control_coverage_file', options.perform_control_coverage_file, ...
    'perform_classification_summary_file', ...
    options.perform_classification_summary_file, ...
    'references', references, 'coverage', coverage, ...
    's1_provenance', provenance, 'perform_zone_summary', perform_zone_summary, ...
    'perform_controls', perform_controls, ...
    'perform_control_coverage', perform_control_coverage, ...
    'perform_classification_summary', perform_classification_summary);
end

function options = defaults(options, helper_dir, workspace_dir)
items = { ...
    'structural_case', 'npcc_ny_lite_s7_seven_interface_perform_direct_candidate'; ...
    'original_case', 'npcc_original'; ...
    's1_case', 'npcc_ny_lite_s1_acopf_feasible_uncalibrated'; ...
    'scenario_id', "S3_2019_SHOULDER_LIGHT_LOAD_PUBLIC"; ...
    'external_target_file', fullfile(helper_dir, 'ny_external_interface_targets.csv'); ...
    'perform_case_dir', fullfile(workspace_dir, 'PERFORM', ...
        'On Peak 2019 v23_Perform_NY', 'On Peak 2019 v23'); ...
    'perform_aux_dir', fullfile(workspace_dir, 'PERFORM', 'Auxilliary_Perform_NY'); ...
    'perform_raw_file', fullfile(workspace_dir, 'PERFORM', ...
        'On Peak 2019 v23_Perform_NY', 'On Peak 2019 v23', ...
        'NYISO_onpeak2019_v23_shuntsRgens.RAW'); ...
    'perform_raw_source_id', fullfile('PERFORM', 'On Peak 2019 v23_Perform_NY', ...
        'On Peak 2019 v23', 'NYISO_onpeak2019_v23_shuntsRgens.RAW'); ...
    'reference_file', fullfile(helper_dir, 'ny_voltage_reference_sets.csv'); ...
    'coverage_file', fullfile(helper_dir, 'ny_voltage_reference_coverage.csv'); ...
    's1_provenance_file', fullfile(helper_dir, 's1_opf_voltage_reference_provenance.csv'); ...
    'perform_zone_file', fullfile(helper_dir, 'perform_zonal_voltage_reference_summary.csv'); ...
    'perform_control_file', fullfile(helper_dir, 'perform_generator_voltage_controls.csv'); ...
    'perform_control_coverage_file', fullfile(helper_dir, 'perform_voltage_control_coverage.csv'); ...
    'perform_classification_summary_file', fullfile(helper_dir, ...
        'perform_voltage_control_classification_summary.csv')};
for k = 1:size(items, 1)
    if ~isfield(options, items{k, 1}), options.(items{k, 1}) = items{k, 2}; end
end
end

function rows = case_reference_rows(model, source, set_name, control_type, ...
        source_case, source_description, effective_date, confidence, mapping)
define_constants;
model = attach_nyiso_zone_metadata(model);
model_bus_ids = ny_generator_buses(model);
rows = table();
for k = 1:numel(model_bus_ids)
    bus_id = model_bus_ids(k);
    source_idx = find(source.gen(:, GEN_STATUS) > 0 & source.gen(:, GEN_BUS) == bus_id);
    if isempty(source_idx), continue; end
    weights = max(0, source.gen(source_idx, PMAX));
    if sum(weights) <= 0, weights = ones(numel(source_idx), 1); end
    weights = weights / sum(weights);
    vg = source.gen(source_idx, VG);
    source_record = source_description + "; generator rows " + ...
        join(string(source_idx(:)'), "|");
    rows = append_table(rows, reference_row(model, set_name, bus_id, ...
        sum(weights .* vg), min(vg), max(vg), control_type, source_case, ...
        source_record, effective_date, confidence, mapping, ...
        "MATPOWER VG is a local field; remote regulated-bus assignment is not encoded."));
end
end

function [rows, zone_summary, controls, control_coverage, ...
        classification_summary] = ...
        perform_reference_rows(model, options)
define_constants;
addpath(options.perform_case_dir);
perform = nyiso_On_Peak_v23_shunts_as_z_load;
mapping = readtable(fullfile(options.perform_aux_dir, ...
    'internal_NYISO_MOD2MAP.xlsx'), 'Sheet', 'BUS SUB', ...
    'VariableNamingRule', 'preserve');
control_metadata_file = fullfile(options.perform_case_dir, ...
    'GenCostTable4MATPOWERv23_ShuntsNotShown.csv');
control_import = detectImportOptions(control_metadata_file, ...
    'VariableNamingRule', 'preserve');
control_import = setvartype(control_import, 'GenID', 'string');
control_metadata = readtable(control_metadata_file, control_import);
[controls, control_coverage] = extract_perform_voltage_controls( ...
    options.perform_raw_file, options.perform_raw_source_id, mapping, perform, ...
    control_metadata);
classification_summary = classification_summary_rows(controls);
bus_zone = perform_nyiso_zone_letters(perform, perform.bus(:, BUS_I));
[gen_mapped, gen_bus_idx] = ismember(perform.gen(:, GEN_BUS), perform.bus(:, BUS_I));
gen_zone = strings(size(perform.gen, 1), 1);
gen_zone(gen_mapped) = bus_zone(gen_bus_idx(gen_mapped));
gen_fuel = lower(strtrim(string(perform.genfuel(:))));
native = perform.gen(:, GEN_STATUS) > 0 & gen_zone ~= "" & ...
    ~ismember(gen_fuel, ["import", "reference"]);

zone_summary = table();
for zone = string(('A':'K')')'
    idx = find(native & gen_zone == zone);
    if isempty(idx), continue; end
    weights = max(0, perform.gen(idx, PMAX));
    if sum(weights) <= 0, weights = ones(numel(idx), 1); end
    weights = weights / sum(weights);
    vg = perform.gen(idx, VG);
    row = table(zone, numel(idx), sum(perform.gen(idx, PMAX)), ...
        sum(weights .* vg), min(vg), max(vg), ...
        'VariableNames', {'zone','online_native_generator_count', ...
        'online_native_pmax_mw','pmax_weighted_vg_pu','min_vg_pu','max_vg_pu'});
    zone_summary = append_table(zone_summary, row);
end

for k = 1:height(zone_summary)
    ci = find(control_coverage.zone == zone_summary.zone(k), 1);
    if isempty(ci)
        zone_summary.raw_online_control_count(k, 1) = 0;
        zone_summary.raw_remote_regulation_count(k, 1) = 0;
        zone_summary.raw_missing_regulated_bus_count(k, 1) = 0;
    else
        zone_summary.raw_online_control_count(k, 1) = ...
            control_coverage.online_generator_count(ci);
        zone_summary.raw_remote_regulation_count(k, 1) = ...
            control_coverage.remote_regulation_count(ci);
        zone_summary.raw_missing_regulated_bus_count(k, 1) = ...
            control_coverage.missing_regulated_bus_count(ci);
    end
end

model = attach_nyiso_zone_metadata(model);
model_bus_ids = ny_generator_buses(model);
rows = table();
for k = 1:numel(model_bus_ids)
    bus_id = model_bus_ids(k);
    bi = find(model.bus(:, BUS_I) == bus_id, 1);
    zone = string(model.userdata.nyiso_physical_zone{bi});
    zi = find(zone_summary.zone == zone, 1);
    if isempty(zi), continue; end
    row = reference_row(model, ...
        "PERFORM_ZONE_AGGREGATE_REFERENCE", bus_id, ...
        zone_summary.pmax_weighted_vg_pu(zi), zone_summary.min_vg_pu(zi), ...
        zone_summary.max_vg_pu(zi), "provisional_zonal_vg_envelope", ...
        "PERFORM NYISO On Peak 2019 v23", ...
        "Native online generators in zone " + zone + ...
        "; PMAX-weighted converted VG with observed zonal min/max envelope", ...
        "2019 on-peak snapshot", "low", ...
        "NYISO-zone aggregate mapped to retained model bus", ...
        "RAW VS/IREG controls are extracted separately; this zonal aggregate does not preserve individual remote regulation in the reduced mapping.");
    row.remote_regulation_flag = "source_available_not_preserved_by_zonal_aggregate";
    rows = append_table(rows, row);
end
end

function [controls, coverage] = extract_perform_voltage_controls( ...
        raw_file, raw_source_id, ~, converted, control_metadata)
% Preserve source VS/IREG controls that are omitted by MATPOWER conversion.
define_constants;
[records, sections] = psse_read(raw_file, 0);
[data, warns] = psse_parse(records, sections, 0, 33); %#ok<ASGLU>
g = data.gen.num;
gt = data.gen.txt;

source_bus = g(:, 1);
generator_id = strip(erase(string(gt(:, 2)), "'"));
pg_mw = g(:, 3);
qg_mvar = g(:, 4);
qmax_mvar = g(:, 5);
qmin_mvar = g(:, 6);
voltage_target_pu = g(:, 7);
raw_ireg = str2double(string(gt(:, 8)));
raw_ireg(isnan(raw_ireg)) = 0;
status = g(:, 15);
pmax_mw = g(:, 17);
pmin_mw = g(:, 18);

regulated_bus = source_bus;
remote_mask = raw_ireg ~= 0;
regulated_bus(remote_mask) = abs(round(raw_ireg(remote_mask)));

source_zone = perform_nyiso_zone_letters(converted, source_bus);
regulated_zone = perform_nyiso_zone_letters(converted, regulated_bus);

raw_bus_id = data.bus.num(:, 1);
raw_bus_name = strip(erase(string(data.bus.txt(:, 2)), "'"));
[source_bus_found, source_bus_idx] = ismember(source_bus, raw_bus_id);
[regulated_bus_found, regulated_bus_idx] = ismember(regulated_bus, raw_bus_id);
source_bus_name = strings(size(source_bus));
regulated_bus_name = strings(size(source_bus));
source_bus_name(source_bus_found) = raw_bus_name(source_bus_idx(source_bus_found));
regulated_bus_name(regulated_bus_found) = raw_bus_name(regulated_bus_idx(regulated_bus_found));

remote_regulation = regulated_bus ~= source_bus;
mapped_to_nyiso_zone = ismember(source_zone, string(('A':'K')'));
source_id = string(strrep(char(raw_source_id), '\', '/'));

is_qs_record = upper(strtrim(generator_id)) == "QS";
converted_gen_index = nan(size(source_bus));
converted_genfuel = strings(size(source_bus));
converted_fuel = lower(strtrim(string(converted.genfuel(:))));
if height(control_metadata) ~= size(converted.gen, 1) || ...
        any(double(control_metadata.GEN_BUS) ~= converted.gen(:, GEN_BUS))
    error('PERFORM generator metadata is not aligned with the converted case.');
end
metadata_id = upper(strtrim(string(control_metadata.GenID)));
raw_id = upper(strtrim(generator_id));
mapped_converted = false(size(converted.gen, 1), 1);
for r = find(~is_qs_record(:))'
    converted_row = find(double(control_metadata.GEN_BUS) == source_bus(r) & ...
        metadata_id == raw_id(r));
    if numel(converted_row) ~= 1
        error(['PERFORM RAW generator key (%g, %s) maps to %d converted ' ...
            'metadata rows; expected exactly one.'], source_bus(r), raw_id(r), ...
            numel(converted_row));
    end
    converted_gen_index(r) = converted_row;
    converted_genfuel(r) = converted_fuel(converted_row);
    mapped_converted(converted_row) = true;
end
if ~all(mapped_converted) || ...
        sum(isfinite(converted_gen_index)) ~= size(converted.gen, 1)
    error('PERFORM RAW-to-converted generator mapping is not one-to-one.');
end
converted_status = nan(size(status));
non_qs = isfinite(converted_gen_index);
converted_status(non_qs) = converted.gen(converted_gen_index(non_qs), GEN_STATUS);
snapshot_effective_status = status;
snapshot_effective_status(non_qs) = converted_status(non_qs);
raw_converted_status_mismatch = non_qs & status ~= converted_status;

tol = 1e-6;
online = status > 0;
positive_active_capability = online & pmax_mw > tol;
zero_active_capability = online & abs(pmax_mw) <= tol & abs(pmin_mw) <= tol;
fixed_negative_active = online & pmax_mw < -tol & ...
    abs(pmax_mw - pmin_mw) <= tol;
reactive_only_qs = online & is_qs_record & zero_active_capability & ...
    qmax_mvar - qmin_mvar > tol;
fuel_boundary = ismember(converted_genfuel, ["import", "reference"]);
% Boundary/reference classification has precedence over storage heuristics.
% In particular, the PERFORM Marcy RF record has a negative-to-positive P
% range but is a reference-balance equivalent, not a physical storage unit.
storage_or_pumping = online & ~fuel_boundary & ...
    (contains(converted_genfuel, "storage") | ...
    contains(converted_genfuel, "pump") | (pmin_mw < -tol & pmax_mw > tol));
fixed_import_or_boundary_equivalent = online & ...
    (fixed_negative_active | fuel_boundary);
synchronous_condenser = online & ~is_qs_record & zero_active_capability & ...
    qmax_mvar - qmin_mvar > tol & ~fuel_boundary;
native_generator = online & positive_active_capability & ...
    ~fixed_import_or_boundary_equivalent & ~storage_or_pumping;
offline = ~online;

device_class = repmat("unclassified_generator_section_record", size(source_bus));
device_class(offline) = "offline";
device_class(online & native_generator) = "native_generator";
device_class(online & synchronous_condenser) = "synchronous_condenser";
device_class(online & storage_or_pumping) = "storage_or_pumping";
device_class(online & fixed_import_or_boundary_equivalent) = ...
    "fixed_import_or_boundary_equivalent";
device_class(online & reactive_only_qs) = "reactive_only_QS";

classification_rule = repmat("manual_review_required", size(source_bus));
classification_confidence = repmat("low", size(source_bus));
classification_rule(offline) = "RAW STAT is offline";
classification_confidence(offline) = "high";
classification_rule(native_generator) = ...
    "positive PMAX and converted fuel is not import/reference";
classification_confidence(native_generator) = "medium";
classification_rule(synchronous_condenser) = ...
    "zero P range with nonzero Q range and ID is not QS";
classification_confidence(synchronous_condenser) = "medium";
classification_rule(storage_or_pumping) = ...
    "negative-to-positive P range or storage/pump fuel label";
classification_confidence(storage_or_pumping) = "medium";
classification_rule(fixed_import_or_boundary_equivalent) = ...
    "converted import/reference fuel or fixed negative P";
classification_confidence(fixed_import_or_boundary_equivalent) = "high";
classification_rule(reactive_only_qs) = ...
    "ID QS with zero P capability and nonzero Q range";
classification_confidence(reactive_only_qs) = "high";
control_group_id = source_zone + "_REG_BUS_" + string(regulated_bus);
control_group_id(source_zone == "") = ...
    "UNMAPPED_REG_BUS_" + string(regulated_bus(source_zone == ""));

controls = table(source_bus, source_bus_name, generator_id, source_zone, ...
    pg_mw, qg_mvar, qmin_mvar, qmax_mvar, pmin_mw, pmax_mw, ...
    voltage_target_pu, raw_ireg, regulated_bus, regulated_bus_name, ...
    regulated_zone, remote_regulation, regulated_bus_found, status, ...
    converted_status, snapshot_effective_status, raw_converted_status_mismatch, ...
    mapped_to_nyiso_zone, converted_gen_index, converted_genfuel, ...
    device_class, native_generator, reactive_only_qs, ...
    fixed_import_or_boundary_equivalent, synchronous_condenser, ...
    storage_or_pumping, offline, positive_active_capability, ...
    fixed_negative_active, is_qs_record, control_group_id, ...
    classification_rule, classification_confidence, ...
    repmat("PERFORM PSS/E RAW rev33", size(source_bus)), ...
    repmat(source_id, size(source_bus)), ...
    'VariableNames', {'source_bus','source_bus_name','generator_id','source_zone', ...
    'pg_mw','qg_mvar','qmin_mvar','qmax_mvar','pmin_mw','pmax_mw', ...
    'voltage_target_pu','raw_ireg','regulated_bus','regulated_bus_name', ...
    'regulated_zone','remote_regulation','regulated_bus_found','status', ...
    'converted_status','snapshot_effective_status','raw_converted_status_mismatch', ...
    'mapped_to_nyiso_zone','converted_gen_index','converted_genfuel', ...
    'device_class','native_generator','reactive_only_QS', ...
    'fixed_import_or_boundary_equivalent','synchronous_condenser', ...
    'storage_or_pumping','offline','positive_active_capability', ...
    'fixed_negative_active','originated_from_shunt_as_generator_conversion', ...
    'control_group_id','classification_rule','classification_confidence', ...
    'source_format','source_file'});

coverage = table();
for zone = string(('A':'K')')'
    zi = controls.source_zone == zone & controls.status > 0;
    row = table(zone, sum(zi), sum(zi & controls.remote_regulation), ...
        sum(zi & ~controls.remote_regulation), ...
        sum(zi & ~controls.regulated_bus_found), ...
        sum(controls.pmax_mw(zi)), numel(unique(controls.source_bus(zi))), ...
        sum(zi & controls.reactive_only_QS), ...
        sum(zi & controls.positive_active_capability), ...
        sum(zi & controls.fixed_import_or_boundary_equivalent), ...
        sum(zi & controls.native_generator), ...
        'VariableNames', {'zone','online_generator_count', ...
        'remote_regulation_count','local_regulation_count', ...
        'missing_regulated_bus_count','online_pmax_mw', ...
        'distinct_source_bus_count','reactive_only_qs_count', ...
        'positive_active_capability_count', ...
        'fixed_import_or_boundary_equivalent_count','native_generator_count'});
    coverage = append_table(coverage, row);
end
end

function summary = classification_summary_rows(controls)
online_ak = controls.status > 0 & controls.mapped_to_nyiso_zone;
metrics = [ ...
    "raw_generator_section_records"; ...
    "online_a_k_generator_section_control_records"; ...
    "online_a_k_distinct_source_buses"; ...
    "online_a_k_reactive_only_qs_records"; ...
    "online_a_k_positive_active_capability_records"; ...
    "online_a_k_fixed_negative_active_records"; ...
    "online_a_k_remote_regulation_records"; ...
    "online_a_k_missing_regulated_bus_records"; ...
    "raw_converted_status_mismatch_records"; ...
    "converted_snapshot_online_a_k_control_records"; ...
    "converted_non_qs_mapping_records"];
values = [ ...
    height(controls); ...
    sum(online_ak); ...
    numel(unique(controls.source_bus(online_ak))); ...
    sum(online_ak & controls.reactive_only_QS); ...
    sum(online_ak & controls.positive_active_capability); ...
    sum(online_ak & controls.fixed_negative_active); ...
    sum(online_ak & controls.remote_regulation); ...
    sum(online_ak & ~controls.regulated_bus_found); ...
    sum(controls.raw_converted_status_mismatch); ...
    sum(controls.snapshot_effective_status > 0 & controls.mapped_to_nyiso_zone); ...
    sum(isfinite(controls.converted_gen_index))];
unit = repmat("records", numel(metrics), 1);
unit(3) = "buses";
notes = [ ...
    "All PSS/E RAW generator-section rows"; ...
    "Online records whose source bus maps to NYISO A-K"; ...
    "Distinct source buses among online A-K records"; ...
    "ID QS; zero P capability; nonzero Q range"; ...
    "Positive PMAX; includes native and positive import/reference records"; ...
    "PMIN equals PMAX below zero"; ...
    "IREG points to a nonlocal bus"; ...
    "Regulated bus absent from source RAW bus table"; ...
    "RAW STAT differs from converted MATPOWER GEN_STATUS"; ...
    "Converted-case status for non-QS records; RAW status for QS records"; ...
    "RAW non-QS rows aligned to converted PERFORM gen/genfuel rows"];
summary = table(metrics, values, unit, notes, ...
    'VariableNames', {'metric','value','unit','note'});
end

function rows = boundary_reference_rows(model, options)
targets = readtable(options.external_target_file, 'TextType', 'string', ...
    'VariableNamingRule', 'preserve');
targets = targets(string(targets.scenario_id) == string(options.scenario_id), :);
rows = table();
for bus_id = unique(targets.ny_boundary_bus(:))'
    idx = find(targets.ny_boundary_bus == bus_id);
    vg = targets.v_setpoint(idx);
    rows = append_table(rows, reference_row(model, ...
        "SHOULDER_BOUNDARY_EQUIVALENT_REFERENCE", bus_id, mean(vg), ...
        min(vg), max(vg), "boundary_equivalent_voltage_prior", ...
        "ny_external_interface_targets.csv", ...
        "Scenario " + string(options.scenario_id) + " target rows " + ...
        join(string(idx(:)'), "|"), "2025 public scenario", "low", ...
        "boundary schedule mapped directly to retained terminal", ...
        "Boundary-equivalent voltage prior is separate from internal generator schedules."));
end
end

function row = reference_row(model, set_name, bus_id, reference, ref_min, ...
        ref_max, control_type, source_case, source_record, effective_date, ...
        confidence, mapping, notes)
define_constants;
bi = find(model.bus(:, BUS_I) == bus_id, 1);
if isempty(bi)
    bus_name = "BOUNDARY_BUS_" + string(bus_id);
    zone = "";
else
    bus_name = string(strtrim(model.bus_name{bi}));
    zone = string(model.userdata.nyiso_physical_zone{bi});
end
device_class = "retained_generator_or_aggregate_proxy";
if bus_id == 78
    device_class = "zone_I_interface_voltage_support_proxy";
elseif bus_id >= 9000
    device_class = "added_zero_load_transit_or_supply_proxy";
elseif set_name == "SHOULDER_BOUNDARY_EQUIVALENT_REFERENCE"
    device_class = "external_boundary_equivalent";
end
row = table(string(set_name), "BUS_" + string(bus_id), bus_id, bus_name, ...
    zone, NaN, string(control_type), reference, ref_min, ref_max, ...
    (ref_max - ref_min) / 2, "not_encoded", "available_in_source_snapshot", ...
    string(source_case), string(source_record), string(effective_date), ...
    string(confidence), device_class, string(mapping), string(notes), ...
    'VariableNames', {'reference_set','generator_or_proxy_id','model_bus', ...
    'model_bus_name','model_zone','regulated_bus','control_type', ...
    'voltage_reference_pu','voltage_reference_min_pu', ...
    'voltage_reference_max_pu','voltage_deadband_pu', ...
    'remote_regulation_flag','scenario_status','source_case','source_record', ...
    'effective_date','confidence','device_class','mapping_method','notes'});
end

function rows = s1_provenance_rows(original, s1)
define_constants;
rows = table();
for g = 1:size(s1.gen, 1)
    bus_id = s1.gen(g, GEN_BUS);
    candidates = find(original.gen(:, GEN_BUS) == bus_id);
    if isempty(candidates), continue; end
    if isscalar(candidates)
        source_g = candidates;
    else
        occurrence = sum(s1.gen(1:g, GEN_BUS) == bus_id);
        source_g = candidates(min(occurrence, numel(candidates)));
    end
    original_vg = original.gen(source_g, VG);
    s1_vg = s1.gen(g, VG);
    row = table(g, source_g, bus_id, original_vg, s1_vg, s1_vg - original_vg, ...
        abs(s1_vg - original_vg) > 1e-10, ...
        "S1 saved from ACOPF solved case with opf.use_vg = 0", ...
        'VariableNames', {'s1_gen_index','original_gen_index','bus_id', ...
        'original_npcc_vg_pu','s1_saved_vg_pu','delta_vg_pu','changed', ...
        'provenance'});
    rows = append_table(rows, row);
end
end

function coverage = coverage_rows(model, references)
define_constants;
model_buses = ny_generator_buses(attach_nyiso_zone_metadata(model));
coverage = table();
for set_name = unique(references.reference_set, 'stable')'
    rows = references(references.reference_set == set_name, :);
    covered = intersect(model_buses, rows.model_bus);
    missing = setdiff(model_buses, covered);
    ce = rows(rows.model_bus == 78, :);
    ce_reference = NaN;
    ce_class = "not_available";
    if ~isempty(ce)
        ce_reference = ce.voltage_reference_pu(1);
        ce_class = ce.device_class(1);
    end
    row = table(set_name, numel(model_buses), numel(covered), numel(missing), ...
        join(string(missing(:)'), "|"), ce_reference, ce_class, ...
        'VariableNames', {'reference_set','current_model_generator_bus_count', ...
        'covered_bus_count','missing_bus_count','missing_model_bus_ids', ...
        'ce_ug_reference_pu','ce_ug_device_class'});
    coverage = append_table(coverage, row);
end
end

function bus_ids = ny_generator_buses(model)
define_constants;
online_bus_ids = unique(model.gen(model.gen(:, GEN_STATUS) > 0, GEN_BUS), 'stable');
bus_ids = zeros(0, 1);
for k = 1:numel(online_bus_ids)
    bi = find(model.bus(:, BUS_I) == online_bus_ids(k), 1);
    if ~isempty(bi) && string(model.userdata.nyiso_physical_zone{bi}) ~= ""
        bus_ids(end + 1, 1) = online_bus_ids(k); %#ok<AGROW>
    end
end
end

function out = append_table(out, row)
if isempty(row), return; end
if isempty(out), out = row; else, out = [out; row]; end
end
