function out = build_s13_phase1a_candidate(options)
%BUILD_S13_PHASE1A_CANDIDATE Build registers and structural-gate evidence.

if nargin < 1, options = struct(); end
% Phase 1A is an immutable checkpoint.  The advancing cumulative S13 case
% owns the canonical register sidecars, so a standalone Phase 1A rebuild is
% read-only unless a caller explicitly requests output regeneration.
if ~isfield(options, 'write_outputs'), options.write_outputs = false; end
if ~isfield(options, 'verbose'), options.verbose = true; end

helper_dir = fileparts(mfilename('fullpath'));
case_dir = fileparts(helper_dir);
addpath(case_dir); addpath(helper_dir);

parent = loadcase('npcc_ny_lite_s7_seven_interface_perform_direct_candidate');
[candidate, phase0_report] = apply_ny_core_phase0_corrections(parent, struct( ...
    'fit_reactance', false, 'verbose', false));
[candidate, phase1a_report] = add_npcc_perform_eg_corridor(candidate, struct( ...
    'write_registers', options.write_outputs, 'register_dir', helper_dir, ...
    'verbose', options.verbose));
candidate.userdata.s13 = struct( ...
    'metadata_schema_version', 2, ...
    'target_name', 'npcc_ny_lite_s13_npcc_augmented_2019', ...
    'status', 'phase1a_s13_full_construction_parent', ...
    'model_role', 'unpromoted_s13_candidate', ...
    'governing_hierarchy_role', 's13_full_construction_validation_parent', ...
    'downstream_operating_model', ...
        'npcc_ny_lite_s14_nyiso_dlr_operating_model', ...
    'dlr_delivery_eligible', false, ...
    'current_phase', 'phase1a', ...
    'structural_parent', ...
        'npcc_ny_lite_s7_seven_interface_perform_direct_candidate', ...
    'phase0_report', phase0_report, ...
    'overlay_report', phase1a_report, ...
    'phase_reports', struct('phase1a', phase1a_report), ...
    'phase1a_report', phase1a_report, ...
    'construction_source_qualified', false, ...
    'promotion_eligible', false, ...
    'construction_blockers', {{ ...
        'Phase 1B physical overlay pending', ...
        'Phase 1C physical overlay pending', ...
        'passive residual equivalents pending', ...
        'frozen solved S14 reduction-source state pending'}}, ...
    'promotion_blockers', {{ ...
        'S13-FULL role is permanently ineligible for DLR-model promotion'}});

validation = validate_s13_structural_preservation(struct( ...
    'candidate_case', candidate, ...
    'candidate_name', 'npcc_ny_lite_s13_npcc_augmented_2019', ...
    'write_outputs', options.write_outputs, ...
    'fail_on_structural', true));

out = struct('candidate', candidate, 'phase0_report', phase0_report, ...
    'overlay_report', phase1a_report, ...
    'phase_reports', struct('phase1a', phase1a_report), ...
    'phase1a_report', phase1a_report, 'validation', validation);
end
