function out=build_ny_boundary_register(normalized,options)
%BUILD_NY_BOUNDARY_REGISTER Fixed NY-side PQ schedules at PERFORM identities.
% Twenty external proxies are distinct from the Marcy reference placeholder.
% Source-generator rows are pointers only; device_key is the durable identity.
% options.snapshot_case may be a reproduced source PF with identical devices.
% External Q is a declared fixed snapshot assumption, not observed exchange.
if nargin<2,options=struct();end
if ~isfield(options,'write_outputs'),options.write_outputs=false;end
if ~isfield(options,'output_dir'),options.output_dir=fileparts(mfilename('fullpath'));end
define_constants;
assert(isstruct(normalized)&&isfield(normalized,'source')&& ...
    isfield(normalized,'boundary_reconciliation'), ...
    'build_ny_boundary_register:NormalizedSource','A normalized original PERFORM source is required.');
source=normalized.source;rec=normalized.boundary_reconciliation;
needed={'source_gen_row','source_bus','source_generator_id','device_key', ...
    'source_device_role','proposed_schedule_group','boundary_member', ...
    'canonical_status','raw_status','legacy_schedule_member'};
assert(istable(rec)&&all(ismember(needed,rec.Properties.VariableNames)), ...
    'build_ny_boundary_register:Schema','Boundary reconciliation schema is incomplete.');
rows=double(rec.source_gen_row);
assert(all(rows>=1&rows<=size(source.gen,1)&rows==fix(rows))&& ...
    numel(unique(rows))==height(rec)&&numel(unique(string(rec.device_key)))==height(rec), ...
    'build_ny_boundary_register:Identity','Duplicate or invalid source identity.');
assert(isequal(source.gen(rows,GEN_BUS),double(rec.source_bus))&& ...
    isequal(source.gen(rows,GEN_STATUS),double(rec.canonical_status)), ...
    'build_ny_boundary_register:SourceIdentity','Source bus/status pointers changed.');
expected_key="PERFORM2019:GEN:"+string(rec.source_bus)+":"+upper(strtrim(string(rec.source_generator_id)));
assert(isequal(string(rec.device_key),expected_key), ...
    'build_ny_boundary_register:DeviceKey','Device keys must retain original bus/unit identity.');
snapshot=source;snapshot_kind="canonical_converted_unsolved_PQ_values";
if isfield(options,'snapshot_case')
    snapshot=options.snapshot_case;
    assert(isstruct(snapshot)&&isfield(snapshot,'success')&& ...
        isscalar(snapshot.success)&&isfinite(snapshot.success)&&snapshot.success==1, ...
        'build_ny_boundary_register:Snapshot','A supplied snapshot must be a successful source PF.');
    snapshot_kind="reproduced_original_source_PF_fixed_PQ";
end
assert(snapshot.baseMVA==source.baseMVA&&size(snapshot.bus,1)==size(source.bus,1)&& ...
    size(snapshot.gen,1)==size(source.gen,1)&&size(snapshot.branch,1)==size(source.branch,1)&& ...
    isequal(snapshot.bus(:,BUS_I),source.bus(:,BUS_I))&& ...
    isequal(snapshot.gen(:,GEN_BUS),source.gen(:,GEN_BUS))&& ...
    isequal(snapshot.gen(:,GEN_STATUS),source.gen(:,GEN_STATUS)), ...
    'build_ny_boundary_register:SnapshotIdentity','Snapshot devices/status must match original source order.');
assert(isequal(snapshot.branch(:,1:13),source.branch(:,1:13))&& ...
    isequal(snapshot.bus(:,[PD QD GS BS BASE_KV]),source.bus(:,[PD QD GS BS BASE_KV])), ...
    'build_ny_boundary_register:SnapshotNetwork','Snapshot must preserve original network and gross injections.');
assert(all(isfinite(snapshot.gen(rows,[PG QG])),'all'), ...
    'build_ny_boundary_register:NonfiniteSchedule','Fixed boundary P/Q must be finite.');
external=logical(rec.boundary_member);
reference=string(rec.source_device_role)=="reference_placeholder";
assert(all(external|reference)&&~any(external&reference)&& ...
    all(string(rec.source_device_role(external))=="external_boundary_proxy"), ...
    'build_ny_boundary_register:Roles','Every candidate needs one unambiguous boundary/reference role.');
[found,bi]=ismember(rec.source_bus,source.bus(:,BUS_I));
assert(all(found),'build_ny_boundary_register:Landing','An original source landing bus is missing.');
zones=perform_nyiso_zone_letters(source,rec.source_bus);
assert(all(ismember(zones,string(('A':'K')'))), ...
    'build_ny_boundary_register:NYLanding','Every fixed injection must land at a registered NY source bus.');
active=source.gen(rows,GEN_STATUS)>0;
p=snapshot.gen(rows,PG).*active.*external;
q=snapshot.gen(rows,QG).*active.*external;
policy=repmat("apply_fixed_PQ_at_original_NY_bus",height(rec),1);
policy(~active&external)="inactive_zero_injection_keep_identity";
policy(reference)="remove_reference_placeholder_no_PQ_injection";
q_policy=repmat("declared_fixed_source_snapshot_Q_not_observed_exchange",height(rec),1);
q_policy(reference)="reference_Q_not_applied_requires_separate_explicit_support_policy";
confidence=repmat("source_device_identity_with_legacy_schedule_group",height(rec),1);
confidence(reference)="unresolved_reference_device_not_external_exchange";
register=table(string(rec.device_key),rows,double(rec.source_bus), ...
    upper(strtrim(string(rec.source_generator_id))),string(source.bus_name(bi)),zones, ...
    string(rec.source_device_role),string(rec.proposed_schedule_group), ...
    double(rec.raw_status),double(rec.canonical_status),active,external, ...
    source.gen(rows,PG),source.gen(rows,QG),snapshot.gen(rows,PG),snapshot.gen(rows,QG), ...
    p,q,policy,q_policy,confidence,repmat(snapshot_kind,height(rec),1), ...
    'VariableNames',{'device_key','source_gen_row','source_bus','source_generator_id', ...
    'ny_landing_bus_name','ny_zone','source_device_role','schedule_group','raw_status', ...
    'canonical_status','snapshot_active','is_external_exchange','source_pg_mw', ...
    'source_qg_mvar','snapshot_pg_mw','snapshot_qg_mvar','p_injection_mw','q_injection_mvar', ...
    'application_policy','reactive_policy','mapping_confidence','snapshot_kind'});
groups=unique(register.schedule_group(external),'stable');group_table=table();
for k=1:numel(groups)
    take=external&register.schedule_group==groups(k);
    group_table=[group_table;table(groups(k),sum(take),sum(active(take)),sum(p(take)),sum(q(take)), ...
        "positive_into_NY",'VariableNames',{'schedule_group','record_count','online_record_count', ...
        'p_injection_mw','q_injection_mvar','sign_convention'})]; %#ok<AGROW>
end
legacy=logical(rec.legacy_schedule_member);
summary=table(height(rec),sum(external),sum(reference),sum(legacy), ...
    sum(external&~legacy),sum(active&external),sum(~active&external), ...
    sum(p),sum(q),'VariableNames',{'classified_candidate_count','external_proxy_count', ...
    'reference_placeholder_count','legacy_schedule_record_count','omitted_legacy_external_count', ...
    'online_boundary_count','inactive_boundary_count','total_external_p_mw','total_external_q_mvar'});
out=struct('boundary_register',register(external,:),'reference_register',register(reference,:), ...
    'all_records',register,'reconciliation',rec,'summary',summary,'schedule_groups',group_table, ...
    'snapshot_case',snapshot,'snapshot_kind',snapshot_kind,'source_gen_count',size(source.gen,1), ...
    'source_bus_ids',source.bus(:,BUS_I),'gross_loads',source.bus(:,[PD QD]), ...
    'reference_policy','remove_no_injection','promotion_eligible',false);
if options.write_outputs
    if ~isfolder(options.output_dir),mkdir(options.output_dir);end
    names={'boundary_register','reference_register','reconciliation','summary','schedule_groups'};
    files={'ny_boundary_register.csv','ny_reference_placeholder_register.csv', ...
        'ny_boundary_reconciliation.csv','ny_boundary_summary.csv','ny_boundary_schedule_groups.csv'};
    for k=1:numel(names),ny_lite_writetable_lf(out.(names{k}),fullfile(options.output_dir,files{k}));end
end
end
