function out = build_row235_replacement(parent, options)
%BUILD_ROW235_REPLACEMENT Remove the proven Pleasant Valley/Wood Street duplicate.
% OUT = BUILD_ROW235_REPLACEMENT(PARENT,OPTIONS) accepts the full Phase 1B/C
% case before branch slicing or renumbering. Only parent branch 235 status
% changes. Existing physical rows 256/257 retain their individual ratings.
% The local source-equivalence proof uses matched terminal phasors, not a
% fitted residual or a claim that the complete candidate has a solved state.
if nargin<2,options=struct();end
if nargin<1 || isempty(parent)
    b=build_s13_phase1c_candidate(struct('write_outputs',false,'verbose',false));
    parent=b.candidate;
end
if ~isfield(options,'write_outputs'),options.write_outputs=false;end
h=fileparts(mfilename('fullpath'));root=fileparts(fileparts(h));
if ~isfield(options,'output_dir')
    options.output_dir=fullfile(root,'output','ny_only_package_b','row235_replacement');
end
assert(isstruct(parent) && isfield(parent,'branch') && size(parent.branch,1)>=257 ...
    && size(parent.branch,2)>=13,'row235:ParentLayout', ...
    'Pass the full Phase 1B/C parent before branch slicing.');
assert(~isfield(parent,'userdata') || ~isfield(parent.userdata,'row235_replacement'), ...
    'row235:AlreadyApplied','Row 235 replacement is already recorded.');
assert(parent.baseMVA==100,'row235:BaseMVA', ...
    'The audited source and parent both use 100 MVA.');

sr=[1391;1392];mr=[256;257];mb=[73;9002];sb=[651;902];
expected_source=[651 902 .00081 .01237 .31971 1216 2454 1804 0 0 1 0 0; ...
                 651 902 .00081 .01237 .31972 1216 2454 1804 0 0 1 0 0];
expected_parent=[73 9002 .000405 .006185 .63943 2432 4908 3608 0 0 1 -360 360];
assert(isequal(parent.branch(235,1:13),expected_parent),'row235:AggregateParameters', ...
    'Original row 235 identity, status, or parameters changed; replacement is not proven.');
physical=expected_source;physical(:,1:2)=repmat([73 9002],2,1);
physical(:,12:13)=repmat([-360 360],2,1);
assert(isequal(parent.branch(mr,1:13),physical),'row235:PhysicalParameters', ...
    'Existing physical rows 256/257 must match the two source circuits exactly.');
direct=find(all(parent.branch(:,1:2)==[73 9002],2) | ...
    all(parent.branch(:,1:2)==[9002 73],2));
assert(isequal(direct,[235;256;257]),'row235:DirectCircuitSet', ...
    'Unexpected additional or reordered branches between the replacement terminals.');

% Always reread the independently hash-pinned source. Caller-supplied source
% structs must not weaken the provenance check on this exact replacement.
n=normalize_perform_ny_source;src=n.source;
assert(src.baseMVA==100,'row235:BaseMVA','The pinned source base must be 100 MVA.');
assert(isequal(src.branch(sr,1:13),expected_source),'row235:SourceParameters', ...
    'Pinned source circuit values differ from the audited replacement.');

[found,bi]=ismember(mb,parent.bus(:,1));[source_found,si]=ismember(sb,src.bus(:,1));
assert(all(found & source_found) && numel(unique(parent.bus(:,1)))==size(parent.bus,1), ...
    'row235:BusIdentity','Mapped terminal IDs must be unique and present.');
assert(isequal(upper(strtrim(string(parent.bus_name(bi)))),["PLEASANT VLY";"WOOD STREET"]) ...
    && isequal(upper(strtrim(string(src.bus_name(si)))),["PLEASANT VALLEY";"WOOD STREET"]) ...
    && all(parent.bus(bi,10)==345) && all(src.bus(si,10)==345), ...
    'row235:BusIdentity','Terminal names/registered alias or base voltage changed.');
assert(isfield(parent,'userdata') && isfield(parent.userdata,'nyiso_physical_zone') ...
    && all(string(parent.userdata.nyiso_physical_zone(bi))=="G") ...
    && all(perform_nyiso_zone_letters(src,sb)=="G"), ...
    'row235:BusIdentity','Both original source and mapped terminals must be Zone G.');
assert(isfield(parent.userdata,'s13') && isfield(parent.userdata.s13,'overlay_report') ...
    && isfield(parent.userdata,'ny_lite') ...
    && isfield(parent.userdata.ny_lite,'perform_tieline_alignment_report') ...
    && isfield(parent.userdata.ny_lite,'perform_tieline_calibration_report'), ...
    'row235:Lineage','The historical aggregate/overlay lineage must be retained.');
alignment=parent.userdata.ny_lite.perform_tieline_alignment_report;
a=alignment(alignment.branch_index==235,:);
assert(height(a)==1 && a.branch_name=="PLEASANT_VLY_WOOD_STREET" ...
    && a.parameter_source=="PERFORM two-circuit parallel equivalent" ...
    && a.mode=="perform_rxb",'row235:Lineage','Aggregate source lineage is not the audited S7 alignment.');
calibration=parent.userdata.ny_lite.perform_tieline_calibration_report;
c=calibration(calibration.branch_index==235,:);
assert(height(c)==1 && c.impedance_scale==1 && c.b_fraction==1, ...
    'row235:Lineage','Exact replacement requires the unscaled full-B source equivalent.');
terminal_map=parent.userdata.s13.overlay_report.bus_map;
[found,mi]=ismember(mb,terminal_map.model_bus);
assert(all(found) && isequal(terminal_map.source_bus(mi),sb) ...
    && all(terminal_map.source_base_kv(mi)==345) ...
    && all(string(terminal_map.physical_zone(mi))=="G"), ...
    'row235:BusLineage','Registered parent-to-source terminal mappings changed.');
map=parent.userdata.s13.overlay_report.branch_map;
[found,mi]=ismember(mr,map.model_branch_row);
assert(all(found) && isequal(map.source_branch_row(mi),sr) ...
    && isequal(string(map.source_circuit_id(mi)),["1";"2"]) ...
    && isequal(map.source_from_bus(mi),[651;651]) ...
    && isequal(map.source_to_bus(mi),[902;902]), ...
    'row235:Lineage','Overlay row pointers must retain source bus/circuit identity.');
source_register=n.branch_inventory(sr,:);
assert(isequal(source_register.device_key,["PERFORM2019:AC:651:902:1";"PERFORM2019:AC:651:902:2"]) ...
    && all(source_register.individual_circuit_identity_resolved) ...
    && all(source_register.raw_canonical_parameters_match) ...
    && all(source_register.canonical_status==1 & source_register.raw_status==1), ...
    'row235:SourceIdentity','Source RAW identities must uniquely support the two active circuits.');

bus_map=table(mb,sb,string(parent.bus_name(bi)),string(src.bus_name(si)), ...
    parent.bus(bi,10),src.bus(si,10),["G";"G"], ...
    ["registered_PLEASANT_VLY_to_PLEASANT_VALLEY_alias";"exact_name_voltage_zone"], ...
    'VariableNames',{'parent_bus','source_bus','parent_bus_name','source_bus_name', ...
    'parent_base_kv','source_base_kv','physical_zone','mapping_basis'});
source_register.parent_branch_row=mr;
source_register.parent_from_bus=[73;73];source_register.parent_to_bus=[9002;9002];
source_register.source_base_mva=repmat(src.baseMVA,2,1);
source_register.parent_base_mva=repmat(parent.baseMVA,2,1);
source_register.source_angmin_deg=src.branch(sr,12);
source_register.source_angmax_deg=src.branch(sr,13);
source_register.parent_angmin_deg=parent.branch(mr,12);
source_register.parent_angmax_deg=parent.branch(mr,13);
source_register.angle_policy=repmat("source_0_0_and_parent_minus360_plus360_both_unrestricted",2,1);
source_register.disposition=repmat("retain_existing_physical_circuit_unchanged",2,1);
source_register.source_sha256_lf_normalized=repmat(n.canonical_sha256,2,1);

[yagg,~,~]=local_y(parent.branch(235,1:13));
[yphys,yf,yt]=local_y(parent.branch(mr,1:13));
[ysource,syf,syt]=local_y(src.branch(sr,1:13));
equivalence_error=max(abs(yagg-yphys),[],'all');
source_error=max(abs(yphys-ysource),[],'all');
assert(equivalence_error<1e-11 && source_error<1e-11,'row235:Admittance', ...
    'The aggregate must exactly equal the retained physical two-terminal stamp.');
tests=matched_flow_tests(parent,src,bi,si,yagg,yf,yt,syf,syt);
assert(all(tests.max_terminal_complex_power_error_mva<1e-8) ...
    && all(tests.source_physical_flow_error_mva<1e-8), ...
    'row235:MatchedFlow','Matched-terminal aggregate/source flow equivalence failed.');

candidate=parent;candidate.branch(235,11)=0;
% Solved branch outputs are not valid after topology edits. The helper only
% accepts unsolved parent rows, so it cannot silently publish stale flows.
assert(~isfield(parent,'success') || ~parent.success,'row235:SolvedParent', ...
    'Use a construction parent, not a solved case with stale branch outputs.');
assert(size(parent.branch,2)==13 || all(parent.branch(:,14:end)==0,'all'), ...
    'row235:SolvedParent','Nonzero stored branch flow outputs require a fresh unsolved parent.');
disposition=table(235,73,9002,651,902,"PLEASANT_VLY_WOOD_STREET", ...
    "exact_duplicate_of_existing_source_parallel_pair",1,0,"256;257","1391;1392", ...
    "deactivate_aggregate_retain_two_existing_physical_circuits",0,false, ...
    equivalence_error,"two_terminal_source_admittance_equivalence_only", ...
    "other_network_overlaps_require_separate_disposition", ...
    'VariableNames',{'parent_branch_row','parent_from_bus','parent_to_bus', ...
    'source_from_bus','source_to_bus','parent_branch_name','identity_class', ...
    'old_status','new_status','retained_parent_branch_rows','source_branch_rows', ...
    'disposition','residual_admittance_norm_pu','residual_fit_performed', ...
    'equivalence_error_pu','qualification_scope','global_network_status'});
affected=find(ismember(parent.branch(:,1),mb)|ismember(parent.branch(:,2),mb));
region=table(affected,parent.branch(affected,1),parent.branch(affected,2), ...
    parent.branch(affected,11),candidate.branch(affected,11), ...
    'VariableNames',{'parent_branch_row','parent_from_bus','parent_to_bus','old_status','new_status'});
region.disposition=repmat("incident_branch_preserved",height(region),1);
region.disposition(region.parent_branch_row==235)="exact_duplicate_aggregate_deactivated";
region.disposition(ismember(region.parent_branch_row,mr))="source_physical_circuit_retained";
candidate.userdata.row235_replacement=struct('schema_version',1, ...
    'status',"locally_exact_duplicate_removed",'parent_branch_row',235, ...
    'retained_parent_branch_rows',mr,'source_branch_rows',sr, ...
    'parent_terminal_ids',mb,'source_terminal_ids',sb,'residual_fit_performed',false, ...
    'residual_admittance_norm_pu',0,'electrical_baseline_qualified',false, ...
    'contemporary_validation_coverage',"none",'dlr_ready',false);
gates=table(["source_hash_pinned";"aggregate_lineage_verified";"source_circuits_unique"; ...
    "two_terminal_admittance_exact";"matched_flow_states_exact";"physical_rows_unchanged"; ...
    "only_aggregate_status_changed";"all_bus_and_gen_values_unchanged"; ...
    "source_ratings_retained_individually";"zero_residual_no_fit";"passive_retained_pair"], ...
    [true;true;true;equivalence_error<1e-11; ...
    all(tests.max_terminal_complex_power_error_mva<1e-8); ...
    isequal(candidate.branch(mr,:),parent.branch(mr,:)); ...
    nnz(candidate.branch~=parent.branch)==1 && candidate.branch(235,11)==0; ...
    isequal(candidate.bus,parent.bus)&&isequal(candidate.gen,parent.gen); ...
    isequal(candidate.branch(mr,6:8),src.branch(sr,6:8));true; ...
    min(real(eig((yphys+yphys')/2)))>=-1e-10], ...
    'VariableNames',{'check','passed'});
assert(all(gates.passed),'row235:Validation','Replacement conservation gate failed.');
out=struct('candidate',candidate,'disposition_register',disposition,'bus_map',bus_map, ...
    'source_branch_register',source_register,'affected_region_register',region, ...
    'matched_terminal_tests',tests,'source_manifest',n.source_manifest, ...
    'parent_aggregate_parameters',parent.branch(235,1:13), ...
    'local_admittance',struct('aggregate',yagg,'retained_physical',yphys, ...
    'source_physical',ysource,'parent_duplicate_pair',yagg+yphys, ...
    'candidate_pair',yphys,'residual',complex(zeros(2))), ...
    'validation',struct('pass',all(gates.passed),'all_passed',all(gates.passed), ...
    'gates',gates,'max_admittance_error_pu',equivalence_error, ...
    'max_matched_flow_error_mva',max(tests.max_terminal_complex_power_error_mva)), ...
    'electrical_baseline_qualified',false,'residual_fit_performed',false,'dlr_ready',false);
if options.write_outputs
    if ~isfolder(options.output_dir),mkdir(options.output_dir);end
    names=["disposition_register","bus_map","source_branch_register", ...
        "affected_region_register","matched_terminal_tests","source_manifest"];
    for name=names
        ny_lite_writetable_lf(out.(name),fullfile(options.output_dir,"row235_"+name+".csv"));
    end
    ny_lite_writetable_lf(gates,fullfile(options.output_dir,'row235_validation.csv'));
    save(fullfile(options.output_dir,'row235_replacement.mat'),'out');
end
end

function [y,yf,yt]=local_y(branch)
% The source and parent use the same direction; substitute local bus IDs.
branch(:,1)=1;branch(:,2)=2;
bus=zeros(2,13);bus(:,1)=[1;2];bus(:,2)=1;bus(:,8)=1;bus(:,10)=345;
[y,yf,yt]=makeYbus(100,bus,branch);
y=full(y);yf=full(yf);yt=full(yt);
end

function t=matched_flow_tests(parent,src,bi,si,yagg,yf,yt,syf,syt)
% Samples exercise both directions, charging at equal voltage, unequal
% magnitudes, and actual unsolved parent/source terminal initial values.
v=[1 1 0;1 1 8;1 1 -8;.94 1.06 20;1.06 .94 -20; ...
    .97 1.03 3;1.03 .97 -3;1.05 1.05 0; ...
    parent.bus(bi(1),8) parent.bus(bi(2),8) parent.bus(bi(1),9)-parent.bus(bi(2),9); ...
    src.bus(si(1),8) src.bus(si(2),8) src.bus(si(1),9)-src.bus(si(2),9)];
names=["equal_voltage_charging";"forward_transfer";"reverse_transfer"; ...
    "low_from_high_to";"high_from_low_to";"unequal_forward";"unequal_reverse"; ...
    "high_equal_voltage";"parent_initial_phasors";"source_initial_phasors"];
z=zeros(size(v,1),1);t=table(names,v(:,1),v(:,2),v(:,3),z,z,z,z,z,z,z,z,z,z,z,z, ...
    'VariableNames',{'sample','from_vm_pu','to_vm_pu','from_minus_to_angle_deg', ...
    'aggregate_from_p_mw','aggregate_from_q_mvar','aggregate_to_p_mw','aggregate_to_q_mvar', ...
    'physical_from_p_mw','physical_from_q_mvar','physical_to_p_mw','physical_to_q_mvar', ...
    'physical_p_loss_mw','physical_q_loss_mvar','max_terminal_complex_power_error_mva', ...
    'source_physical_flow_error_mva'});
for k=1:size(v,1)
    voltage=[v(k,1)*exp(1i*pi/180*v(k,3));v(k,2)];
    agg=100*voltage.*conj(yagg*voltage);
    pf=100*voltage(1).*conj(yf*voltage);pt=100*voltage(2).*conj(yt*voltage);
    spf=100*voltage(1).*conj(syf*voltage);spt=100*voltage(2).*conj(syt*voltage);
    phys=[sum(pf);sum(pt)];loss=sum(phys);
    t{k,5:16}=[real(agg(1)) imag(agg(1)) real(agg(2)) imag(agg(2)) ...
        real(phys(1)) imag(phys(1)) real(phys(2)) imag(phys(2)) ...
        real(loss) imag(loss) max(abs(agg-phys)) max(abs([pf-spf;pt-spt]))];
end
t.sample_role=repmat("algebraic_matched_terminal_test_not_a_solved_operating_state",height(t),1);
t.global_power_flow_verified=false(height(t),1);
end
