function out = build_s13_phase1b_candidate(options)
%BUILD_S13_PHASE1B_CANDIDATE Build the cumulative Phase 1B S13-FULL case.
%   Phase 1A is rebuilt read-only, Phase 1B appends only source-backed
%   physical rows, and the seven canonical register tables are formed as a
%   stable disjoint union. No parent admittance, shunt, dispatch, or control
%   value is fitted here. S13-FULL remains permanently ineligible for DLR
%   delivery; the future S14-NYISO case remains unbuilt.

if nargin < 1, options = struct(); end
if ~isfield(options, 'write_outputs'), options.write_outputs = true; end
if ~isfield(options, 'verbose'), options.verbose = true; end

helper_dir = fileparts(mfilename('fullpath'));
case_dir = fileparts(helper_dir);
addpath(case_dir); addpath(helper_dir);

phase1a = build_s13_phase1a_candidate(struct( ...
    'write_outputs', false, 'verbose', false));
candidate = phase1a.candidate;
[candidate, phase1b_report] = add_npcc_perform_upny_coned_detail( ...
    candidate, struct('verbose', options.verbose));
cumulative = merge_s13_overlay_reports(phase1a.phase1a_report, ...
    phase1b_report);

candidate.userdata.s13 = struct( ...
    'metadata_schema_version', 2, ...
    'target_name', 'npcc_ny_lite_s13_npcc_augmented_2019', ...
    'status', 'phase1b_s13_full_construction_checkpoint', ...
    'model_role', 'unpromoted_s13_candidate', ...
    'governing_hierarchy_role', 's13_full_construction_validation_parent', ...
    'downstream_operating_model', ...
        'npcc_ny_lite_s14_nyiso_dlr_operating_model', ...
    'dlr_delivery_eligible', false, ...
    'current_phase', 'phase1b', ...
    'structural_parent', ...
        'npcc_ny_lite_s7_seven_interface_perform_direct_candidate', ...
    'phase0_report', phase1a.phase0_report, ...
    'overlay_report', cumulative, ...
    'phase_reports', struct('phase1a', phase1a.phase1a_report, ...
        'phase1b', phase1b_report), ...
    'phase1a_report', phase1a.phase1a_report, ...
    'phase1b_report', phase1b_report, ...
    'construction_source_qualified', false, ...
    'promotion_eligible', false, ...
    'construction_blockers', {{ ...
        'Phase 1C physical overlay pending', ...
        'passive residual equivalents pending', ...
        'full-NPCC operating-source qualification pending', ...
        'frozen solved S14 reduction-source state pending'}}, ...
    'promotion_blockers', {{ ...
        'S13-FULL role is permanently ineligible for DLR-model promotion'}});

candidate.userdata.npcc_perform_overlay.current_phase = 'phase1b';
candidate.userdata.npcc_perform_overlay.phase1b_status = ...
    'implemented_unpromoted_artifact_validated_checkpoint';
candidate.userdata.npcc_perform_overlay.construction_source_qualified = false;
candidate.userdata.npcc_perform_overlay.promotion_eligible = false;
candidate.userdata.npcc_perform_overlay.dlr_delivery_eligible = false;

validation = validate_s13_structural_preservation(struct( ...
    'candidate_case', candidate, ...
    'candidate_name', 'npcc_ny_lite_s13_npcc_augmented_2019', ...
    'write_outputs', false, 'fail_on_structural', true));

if options.write_outputs
    write_canonical_registers(cumulative, helper_dir);
    ny_lite_writetable_lf(validation.gates, ...
        fullfile(helper_dir, 's13_structural_preservation.csv'));
end

out = struct('candidate', candidate, ...
    'phase0_report', phase1a.phase0_report, ...
    'overlay_report', cumulative, ...
    'phase_reports', candidate.userdata.s13.phase_reports, ...
    'phase1a_report', phase1a.phase1a_report, ...
    'phase1b_report', phase1b_report, ...
    'validation', validation);
end

function write_canonical_registers(report, output_dir)
files = struct( ...
    'bus_map', 'npcc_perform_overlay_bus_map.csv', ...
    'branch_map', 'npcc_perform_overlay_branch_map.csv', ...
    'residual_register', 'npcc_residual_equivalent_register.csv', ...
    'residual_shunt_register', 'npcc_residual_shunt_register.csv', ...
    'path_register', 'npcc_overlay_path_register.csv', ...
    'physical_register', 'npcc_added_physical_circuit_register.csv', ...
    'operator_map', 'npcc_2019_interface_operator_map.csv');
names = fieldnames(files);
for k = 1:numel(names)
    field = names{k};
    if ~isfield(report, field) || ~istable(report.(field))
        error('build_s13_phase1b_candidate:CanonicalRegister', ...
            'Cumulative report table %s is missing.', field);
    end
    ny_lite_writetable_lf(report.(field), ...
        fullfile(output_dir, files.(field)));
end
end
