function map = build_s11_interface_branch_map(mpc, output_file, write_output)
%BUILD_S11_INTERFACE_BRANCH_MAP Build source-named reduced interface operators.
%   The map distinguishes official monitored-circuit definitions from their
%   reduced cutset representations. Four public S11 calibration operators
%   are explicit retained-network cutsets. Total East, UPNY-ConEd, and
%   Dunwoodie South stay diagnostic because the 49-bus reduction does not
%   conserve their complete monitored-circuit definitions.

if nargin < 1 || isempty(mpc)
    error('build_s11_interface_branch_map:CaseRequired', ...
        'An S11 49-bus operating case is required.');
end
helper_dir = fileparts(mfilename('fullpath'));
if nargin < 2 || isempty(output_file)
    output_file = fullfile(helper_dir, 'nyiso_interface_branch_map.csv');
end
if nargin < 3 || isempty(write_output), write_output = true; end
validateattributes(write_output, {'logical','numeric'}, {'scalar'});
write_output = logical(write_output);
define_constants;

% interface, branch, reduced meter, sign, official source circuit set,
% public/source IDs, source branch rows, source meter description, date,
% confidence, calibration eligibility, zone boundary, positive direction,
% mapping note
specs = { ...
"Dysinger_East",27,"to",1, ...
 "Dysinger-Henrietta DH1/DH2; Niagara-Henrietta; 115/230-kV Dysinger elements", ...
 "DH1;DH2;NR;108;112;111;113;107;114;67;157-932", ...
 "2162;2163;2164;2252;multi-segment", ...
 "Official meters are circuit-specific; reduced cutset is evaluated at the A-side", ...
 "2022-06-23","medium",true,"A-B","A_to_B", ...
 "Many-to-one Rochester/Niagara aggregate; not a circuit-conserved operator"; ...
"Dysinger_East",63,"from",1, ...
 "Dysinger lower-voltage monitored paths represented by the reduced A-B remainder", ...
 "DE_LOWER_VOLTAGE_AGGREGATE","multi-segment", ...
 "Reduced cutset evaluated at the A-side", ...
 "2022-06-23","low",true,"A-B","A_to_B", ...
 "No one-to-one retained path for six Lockport circuits or Andover-Palmiter"; ...
"West_Central",23,"to",1, ...
 "Pannell Road-Clay PC1/PC2", "PC1;PC2", "2157;2158", ...
 "Official meter at Clay; reduced aggregate evaluated at the B-side", ...
 "2022-06-23","medium",true,"B-C","B_to_C", ...
 "Two source circuits collapse to one reduced 345-kV branch"; ...
"West_Central",24,"to",1, ...
 "Pannell-Farmington 4 and West Central 115-kV/transformer elements", ...
 "4;930;1/7;2;13;906;TB3;TR1;XF7;XF4", ...
 "2337;471;470;333;multi-segment", ...
 "Circuit-specific official meters; reduced cutset evaluated at the B-side", ...
 "2022-06-23","low",true,"B-C","B_to_C", ...
 "Incomplete many-to-one lower-voltage representation"; ...
"West_Central",28,"from",1, ...
 "West Central residual cutset including shared Dysinger elements 67 and 157-932", ...
 "WC_RESIDUAL;67;157-932", "multi-segment", ...
 "Reduced cutset evaluated at the B-side", ...
 "2022-06-23","low",true,"B-C","B_to_C", ...
 "Aggregate proxy only; source conservation not established"; ...
"Moses_South",8,"to",1, ...
 "Moses South seven-circuit public operator", ...
 "MSU1;MA1;MA2;4;5;13;3", "2143;2125;2126;920;921;866;851", ...
 "Official source-side meters; reduced retained-enclave boundary", ...
 "2022-06-23","low",true,"retained_enclave","enclave_outward", ...
 "Explicit conserved cut S={44,47,48}; many-to-one reduced component"; ...
"Moses_South",11,"to",1, ...
 "Moses South seven-circuit public operator", ...
 "MSU1;MA1;MA2;4;5;13;3", "2143;2125;2126;920;921;866;851", ...
 "Official source-side meters; reduced retained-enclave boundary", ...
 "2022-06-23","low",true,"retained_enclave","enclave_outward", ...
 "Explicit conserved cut S={44,47,48}; many-to-one reduced component"; ...
"Moses_South",14,"from",1, ...
 "Moses South seven-circuit public operator", ...
 "MSU1;MA1;MA2;4;5;13;3", "2143;2125;2126;920;921;866;851", ...
 "Official source-side meters; reduced retained-enclave boundary", ...
 "2022-06-23","low",true,"retained_enclave","enclave_outward", ...
 "Explicit conserved cut S={44,47,48}; many-to-one reduced component"; ...
"Moses_South",19,"to",1, ...
 "Moses South seven-circuit public operator", ...
 "MSU1;MA1;MA2;4;5;13;3", "2143;2125;2126;920;921;866;851", ...
 "Official source-side meters; reduced retained-enclave boundary", ...
 "2022-06-23","low",true,"retained_enclave","enclave_outward", ...
 "Explicit conserved cut S={44,47,48}; many-to-one reduced component"; ...
"Moses_South",62,"to",1, ...
 "Moses South seven-circuit public operator", ...
 "MSU1;MA1;MA2;4;5;13;3", "2143;2125;2126;920;921;866;851", ...
 "Official source-side meters; reduced retained-enclave boundary", ...
 "2022-06-23","low",true,"retained_enclave","enclave_outward", ...
 "Explicit conserved cut S={44,47,48}; many-to-one reduced component"; ...
"Central_East",4,"to",1, ...
 "Edic-New Scotland 14", "14", "1609", ...
 "Official sink meter at New Scotland; reduced cutset evaluated at the E-side", ...
 "2021-11-12","medium",true,"E-F","E_to_F", ...
 "Local PERFORM topology is pre-Segment-A; aggregate conservation unproved"; ...
"Central_East",8,"to",1, ...
 "Marcy-New Scotland 18", "18", "1612", ...
 "Official sink meter at New Scotland; reduced cutset evaluated at the E-side", ...
 "2021-11-12","medium",true,"E-F","E_to_F", ...
 "Source path is represented by a Porter/Marcy reduced proxy"; ...
"Central_East",10,"to",1, ...
 "Porter-Rotterdam 30/31; East Springfield-Inghams 7-942; PAR; R81; PV20", ...
 "30;31;7-942;PAR;R81;PV20", "1345;1346;935;unresolved", ...
 "Official sink meters; reduced cutset evaluated at the E-side", ...
 "2021-11-12","low",true,"E-F","E_to_F", ...
 "PAR/R81 unresolved and PV20 absent from the NY-only source"; ...
"Total_East_proxy",2,"from",1, ...
 "Partial F-G proxy for the official Total East composite", ...
 "TOTAL_EAST_PARTIAL_FG", "1606;1607", ...
 "Reduced F-side meter", "2022-06-23","low",false,"composite","eastbound", ...
 "Official Total East also includes Central East, PJM, ISONE, and Rockland elements"; ...
"Total_East_proxy",69,"from",1, ...
 "Fraser-Gilboa GF5-35 within the official Total East composite", ...
 "GF5-35", "2136", "Official Fraser-side meter; reduced Gilboa-side proxy", ...
 "2022-06-23","medium",false,"composite","eastbound", ...
 "Exact source circuit exists, but the remaining composite operator is incomplete"; ...
"UPNY_ConEd",51,"from",1, ...
 "Pleasant Valley-East Fishkill F36/F37 and unresolved UPNY-ConEd aggregate paths", ...
 "F36;F37;RFK305;BK1;BK2", "1389;1390;absent;1691", ...
 "Mixed official meters; reduced G-side meter", ...
 "2022-06-23","low",false,"G-H","G_to_H", ...
 "Aggregate retained path; source conservation not established"; ...
"UPNY_ConEd",52,"from",1, ...
 "UPNY-ConEd residual Pleasant Valley-Millwood aggregate path", ...
 "UPNY_RESIDUAL_2", "multi-segment", "Reduced G-side meter", ...
 "2022-06-23","low",false,"G-H","G_to_H", ...
 "No one-to-one source circuit identity"; ...
"UPNY_ConEd",56,"from",1, ...
 "Ladentown-Buchanan South Y88; Ramapo-Buchanan North Y94", ...
 "Y88;Y94", "1576;1738", "Official Buchanan/Ladentown meters normalized G-to-H", ...
 "2022-06-23","medium",false,"G-H","G_to_H", ...
 "Two source paths share an aggregate retained Buchanan corridor"; ...
"UPNY_ConEd",71,"from",1, ...
 "Pleasant Valley-Wood Street F30/F31 path, represented at Wood Street-Millwood circuit 1", ...
 "F30;F31;WM1", "1391;1392;1734", "Reduced Wood Street G-side meter", ...
 "2022-06-23","medium",false,"G-H","G_to_H", ...
 "Physical WM1 row is exact, but the complete public operator is unresolved"; ...
"UPNY_ConEd",83,"from",1, ...
 "Pleasant Valley-Wood Street F30/F31 path, represented at Wood Street-Millwood circuit 2", ...
 "F30;F31;WM2", "1391;1392;1735", "Reduced Wood Street G-side meter", ...
 "2022-06-23","medium",false,"G-H","G_to_H", ...
 "Physical WM2 row is exact, but the complete public operator is unresolved"; ...
"Dunwoodie_South",57,"from",1, ...
 "Sprain Brook-Dunwoodie South aggregate path", "71;72;99153", ...
 "1262;1263;1264;unresolved", "Reduced Dunwoodie I-side meter", ...
 "2022-06-23","low",false,"I-J","I_to_J", ...
 "Utility circuits are absent or collapsed in the 49-bus core"; ...
"Dunwoodie_South",59,"from",1, ...
 "Sprain Brook-West 49th M51/M52", "M51;M52", "1236;1237", ...
 "Official Sprain Brook meter; reduced I-side meter", ...
 "2022-06-23","low",false,"I-J","I_to_J", ...
 "Two source circuits collapse into aggregate downstate paths"; ...
"Dunwoodie_South",60,"from",1, ...
 "Sprain Brook-Tremont X28; Sprain Brook-Academy M29", ...
 "X28;M29", "1248;1249;1250;unresolved", ...
 "Official X28 sink meter; reduced I-side meter", ...
 "2022-06-23","low",false,"I-J","I_to_J", ...
 "Only a three-row 138-kV surrogate exists for the public 345-kV X28 circuit"; ...
"Dunwoodie_South",74,"from",1, ...
 "Dunwoodie-Sherman Creek 99031/99032", "99031;99032", "unresolved", ...
 "Reduced Dunwoodie I-side meter", "2022-06-23","low",false,"I-J","I_to_J", ...
 "No explicit source identity"; ...
"Dunwoodie_South",75,"from",1, ...
 "Lake Success-Jamaica 903", "903", "55;56", ...
 "Reduced Dunwoodie I-side meter", "2022-06-23","low",false,"I-J","I_to_J", ...
 "Source has a two-row 138-kV surrogate, not a conserved retained circuit"; ...
"Dunwoodie_South",76,"from",1, ...
 "Valley Stream-Jamaica 901L_M and remaining Jamaica ties", ...
 "901L_M", "1336;1337", "Reduced Dunwoodie I-side meter", ...
 "2022-06-23","low",false,"I-J","I_to_J", ...
 "Source is represented by two 69-kV rows and is not one-to-one retained"};

map = table();
for k = 1:size(specs, 1)
    b = double(specs{k, 2});
    if b < 1 || b > size(mpc.branch, 1) || mpc.branch(b, BR_STATUS) <= 0
        error('build_s11_interface_branch_map:BranchIndex', ...
            'Explicit operator branch %d is absent or offline.', b);
    end
    fb = mpc.branch(b, F_BUS); tb = mpc.branch(b, T_BUS);
    row = table(string(specs{k, 1}), string(specs{k, 5}), ...
        string(specs{k, 6}), string(specs{k, 3}), double(specs{k, 4}), ...
        fb, tb, b, "cutset:" + string(specs{k, 1}) + ":branch:" + string(b), ...
        string(specs{k, 9}), string(specs{k, 10}), logical(specs{k, 11}), ...
        string(specs{k, 1}), string(specs{k, 12}), string(specs{k, 13}), ...
        "NYISO Operating Study Appendix E plus PERFORM v23 source mapping", ...
        string(specs{k, 7}), string(specs{k, 8}), string(specs{k, 14}), ...
        'VariableNames', {'interface_name','source_monitored_circuit', ...
        'circuit_id','metered_end','sign','reduced_from_bus', ...
        'reduced_to_bus','reduced_branch_index','reduced_branch_or_cutset', ...
        'effective_date','mapping_confidence','calibration_eligible', ...
        'aggregate_name','zone_boundary','positive_direction','target_source', ...
        'source_branch_rows','source_meter_location','mapping_note'});
    map = append_row(map, row);
end
map = sortrows(map, {'interface_name','reduced_branch_index'});
validate_operator_signs(map, mpc);

expected = ["Dysinger_East";"West_Central";"Moses_South"; ...
    "Central_East";"Total_East_proxy";"UPNY_ConEd";"Dunwoodie_South"];
if ~all(ismember(expected, unique(map.interface_name)))
    error('build_s11_interface_branch_map:MissingOperator', ...
        'The explicit map does not cover all seven public interface records.');
end
required_calibration = expected(1:4);
eligible_names = unique(map.interface_name(map.calibration_eligible));
if ~all(ismember(required_calibration, eligible_names)) || ...
        any(ismember(expected(5:7), eligible_names))
    error('build_s11_interface_branch_map:CalibrationPolicy', ...
        ['The four source-traceable S11 operators must be calibration-' ...
        'eligible; incomplete Total East, UPNY-ConEd, and Dunwoodie ' ...
        'South operators must remain diagnostic.']);
end
if write_output
    out_dir = fileparts(output_file);
    if ~isempty(out_dir) && ~isfolder(out_dir)
        error('build_s11_interface_branch_map:OutputDirectory', ...
            'Output directory does not exist: %s', out_dir);
    end
    writetable(map, output_file);
end
end

function out = append_row(out, row)
if isempty(out), out = row; else, out = [out; row]; end
end

function validate_operator_signs(map, mpc)
% A terminal injection is positive in the desired transfer direction when
% it is metered at the source zone and negative when metered at the sink.
% Do not infer sign from "from"/"to" alone because several reduced rows are
% stored opposite to the public interface direction.
mpc = attach_nyiso_zone_metadata(mpc);
for k = 1:height(map)
    tokens = regexp(char(map.positive_direction(k)), ...
        '^([A-K])_to_([A-K])$', 'tokens', 'once');
    if isempty(tokens), continue; end
    if lower(map.metered_end(k)) == "from"
        meter_bus = map.reduced_from_bus(k);
    else
        meter_bus = map.reduced_to_bus(k);
    end
    bi = find(mpc.bus(:, 1) == meter_bus, 1);
    meter_zone = string(mpc.userdata.nyiso_physical_zone{bi});
    source_zone = string(tokens{1});
    sink_zone = string(tokens{2});
    if meter_zone == source_zone
        expected_sign = 1;
    elseif meter_zone == sink_zone
        expected_sign = -1;
    else
        error('build_s11_interface_branch_map:MeterZone', ...
            'Interface row %d meters zone %s outside %s.', ...
            k, meter_zone, map.zone_boundary(k));
    end
    if map.sign(k) ~= expected_sign
        error('build_s11_interface_branch_map:MeterSign', ...
            ['Interface row %d sign is inconsistent with its metered zone ' ...
            'and positive direction.'], k);
    end
end
end
