function outputs = build_s11_dlr_pf_case(scenario_id, options)
%BUILD_S11_DLR_PF_CASE Build one hard-feasible 49-bus S11 operating case.

if nargin < 1 || isempty(scenario_id)
    scenario_id = "S1_2025_SUMMER_PEAK_PUBLIC";
end
if nargin < 2, options = struct(); end
helper_dir = fileparts(mfilename('fullpath'));
case_dir = fileparts(helper_dir);
options = defaults(options, helper_dir, case_dir);
addpath(case_dir); addpath(helper_dir);
define_constants;
scenario_id = string(scenario_id);

source = loadcase(options.structural_case);
[mpc, reduction_report] = build_ny_only_equivalent_case(source);
[mpc, physical_map] = split_perform_parallel_corridors(mpc, ...
    struct('map_file', options.physical_map_file, ...
    'write_map', options.write_intermediate_maps));
if isempty(options.non_dlr_correction)
    correction_report = struct('status', 'not_applied', ...
        'dlr_frozen_exact', true, 'changed_branch_count', 0, ...
        'changed_bus_shunt_count', 0);
else
    [mpc, correction_report] = apply_s11_non_dlr_equivalent_correction( ...
        mpc, physical_map, options.non_dlr_correction);
end
[mpc, load_report] = apply_s11_public_loads(mpc, scenario_id, ...
    struct('target_file', options.load_target_file, ...
    'q_multiplier', options.q_multiplier, ...
    'use_raw_public_scale', options.use_raw_public_scale));
[mpc, external_report] = apply_s11_external_schedules(mpc, scenario_id, ...
    struct('target_file', options.external_target_file, ...
    'use_raw_public_scale', options.use_raw_public_scale, ...
    'q_mode', options.external_q_mode, ...
    'q_band_mvar', options.external_q_band_mvar));
[mpc, control_report] = apply_perform_controls_to_operating_case(mpc, ...
    struct('control_map_file', options.control_map_file));
[mapped_reference_gen, mapped_reference_zone] = ...
    mapped_operational_reference(control_report);

mpc.userdata.s11.status = 'candidate_pending_hard_validation';
mpc.userdata.s11.scenario_id = char(scenario_id);
mpc.userdata.s11.structural_source = char(options.structural_case);
mpc.userdata.s11.nominal_snapshot = char(scenario_id);
mpc.userdata.s11.q_multiplier = options.q_multiplier;
mpc.userdata.s11.public_scale = ternary(options.use_raw_public_scale, ...
    'raw_NYISO_MW', 'S7_similarity_scaled');
mpc.userdata.s11.dlr_scope = ['AC electrical operating point only; no ' ...
    'conductor, weather, thermal, sag, or dynamic-ampacity model.'];

interface_map = build_s11_interface_branch_map(mpc, options.interface_map_file, ...
    options.write_intermediate_maps);
closure_options = options.closure_options;
closure_options.interface_target_file = options.interface_target_file;
closure_options.interface_map_file = options.interface_map_file;
closure_options.interface_definitions = interface_map;
closure_options.reference_pickup_tolerance_mw = ...
    options.reference_pickup_tolerance_mw;
if ~isfield(closure_options, 'flow_tolerance_mw')
    closure_options.flow_tolerance_mw = options.interface_max_residual_mw;
end
if ~isfield(closure_options, 'interface_mae_tolerance_mw')
    closure_options.interface_mae_tolerance_mw = options.interface_mae_mw;
end
if ~isfield(closure_options, 'interface_bias_tolerance_mw')
    closure_options.interface_bias_tolerance_mw = options.interface_signed_bias_mw;
end
closure_options.active_gen_idx = control_report.active_dispatch_gen_idx;
closure_options.exclude_gen_idx = control_report.external_gen_idx;
closure_options.reference_gen_idx = mapped_reference_gen;
closure_options.reference_zone = mapped_reference_zone;
[dispatch_targets, closure] = ...
    derive_nyiso_zonal_net_injections_ac_iterative_s11( ...
    mpc, scenario_id, closure_options);
input_case = closure.final_case;
trusted_branch_mask = trusted_static_branch_mask(physical_map, input_case);
input_case.userdata.s11.trusted_static_branch_indices = ...
    find(trusted_branch_mask);

[standard_pf, q_pf, pf_diagnostics] = run_hard_pf_pair(input_case);
projection = struct('attempted', false, 'success', false, ...
    'reason', "not_required", 'result', struct());
if needs_projection(q_pf, pf_diagnostics, options, trusted_branch_mask)
    projection = project_s11_hard_ac_feasibility(input_case, options, ...
        trusted_branch_mask);
    if projection.success
        input_case = projection.input_case;
        [standard_pf, q_pf, pf_diagnostics] = run_hard_pf_pair(input_case);
    end
end

if ~isfield(q_pf, 'success') || ~logical(q_pf.success)
    error('build_s11_dlr_pf_case:HardFeasibility', ...
        'Q-limit-enforced AC power flow failed for %s.', scenario_id);
end
[dispatch_targets, final_dispatch] = refresh_final_dispatch_targets( ...
    dispatch_targets, input_case, q_pf, control_report, closure);
closure.post_projection_interface_table = ...
    recompute_final_interface_table(q_pf, closure);
metrics = validation_metrics(input_case, standard_pf, q_pf, ...
    closure, control_report, dispatch_targets, trusted_branch_mask, options);
if options.require_hard_limits && ...
        (metrics.voltage_violation_count > 0 || ...
        metrics.generator_p_violation_count > 0 || ...
        metrics.generator_q_violation_count > 0 || ...
        metrics.branch_overload_count > 0)
    error('build_s11_dlr_pf_case:HardLimits', ...
        ['Scenario %s has hard-limit violations after feasibility projection ' ...
        '(V=%d, P=%d, Q=%d, branch=%d).'], scenario_id, ...
        metrics.voltage_violation_count, metrics.generator_p_violation_count, ...
        metrics.generator_q_violation_count, ...
        metrics.branch_overload_count);
end
if options.require_operating_gates && ~metrics.all_operating_gates_pass
    error('build_s11_dlr_pf_case:OperatingGates', ...
        ['Scenario %s is hard-PF feasible but cannot be promoted: ' ...
         'closure=%d, interface MAE/max/bias=%.3f/%.3f/%.3f MW, ' ...
         'reference pickup=%.3f MW, source-balanced-prior redispatch=%.3f MW (%.3f%%).'], ...
        scenario_id, metrics.closure_converged, ...
        metrics.closure_interface_mae_mw, ...
        metrics.closure_max_calibrated_residual_mw, ...
        metrics.closure_signed_bias_mw, metrics.reference_pickup_mw, ...
        metrics.source_balanced_prior_to_final_redispatch_mw, ...
        metrics.redispatch_percent_of_load);
end

input_case.userdata.s11.status = 'hard_pf_feasible_candidate';
input_case.userdata.s11.validation_metrics = metrics;
input_case.userdata.s11.physical_circuit_map = physical_map;
input_case.userdata.s11.interface_branch_map = interface_map;
input_case.userdata.s11.dispatch_targets = dispatch_targets;
case_files = struct('input_file', "", 'solution_file', "");
if options.write_cases
    case_files = write_case_files(input_case, q_pf, scenario_id, options);
end

outputs = struct('scenario_id', scenario_id, 'input_case', input_case, ...
    'solution', q_pf, 'standard_pf', standard_pf, ...
    'reduction_report', reduction_report, 'physical_circuit_map', physical_map, ...
    'interface_branch_map', interface_map, 'load_report', load_report, ...
    'external_report', external_report, 'control_report', control_report, ...
    'correction_report', correction_report, ...
    'dispatch_targets', dispatch_targets, 'closure', closure, ...
    'final_dispatch', final_dispatch, ...
    'pf_diagnostics', pf_diagnostics, 'projection', projection, ...
    'metrics', metrics, 'case_files', case_files);
end

function options = defaults(options, helper_dir, case_dir)
items = { ...
    'structural_case', 'npcc_ny_lite_s7_seven_interface_perform_direct_candidate'; ...
    'load_target_file', fullfile(helper_dir, 'ny_zonal_load_targets.csv'); ...
    'external_target_file', fullfile(helper_dir, 'ny_external_interface_targets.csv'); ...
    'interface_target_file', fullfile(helper_dir, 'nyiso_public_interface_targets.csv'); ...
    'control_map_file', fullfile(helper_dir, 'perform_source_to_reduced_control_mapping.csv'); ...
    'interface_map_file', fullfile(helper_dir, 'nyiso_interface_branch_map.csv'); ...
    'physical_map_file', fullfile(helper_dir, 's11_physical_circuit_map.csv'); ...
    'non_dlr_correction', fullfile(helper_dir, ...
        's11_non_dlr_admittance_correction.mat'); ...
    'case_dir', case_dir; ...
    'q_multiplier', 1.0; ...
    'use_raw_public_scale', true; ...
    'external_q_mode', "fixed_zero"; ...
    'external_q_band_mvar', 0; ...
    'reference_pickup_tolerance_mw', 0.5; ...
    'hard_limit_tolerance_mva', 1e-3; ...
    'interface_mae_mw', 100; ...
    'interface_max_residual_mw', 200; ...
    'interface_signed_bias_mw', 50; ...
    'redispatch_percent_of_load', 10; ...
    'redispatch_hard_limit_mw', 3000; ...
    'redispatch_justification', ""; ...
    'require_hard_limits', true; ...
    'require_operating_gates', true; ...
    'project_on_limit_violation', true; ...
    'write_cases', false; ...
    'write_intermediate_maps', true; ...
    'opf_solver', "IPOPT"; ...
    'closure_options', struct()};
for k = 1:size(items,1)
    if ~isfield(options,items{k,1}), options.(items{k,1}) = items{k,2}; end
end
end

function [standard_pf, q_pf, diagnostics] = run_hard_pf_pair(mpc)
standard_pf = struct('success', false);
q_pf = struct('success', false);
standard_error = ""; q_error = "";
try
    standard_pf = runpf(mpc, mpoption('verbose',0,'out.all',0, ...
        'pf.enforce_q_lims',0));
catch ex
    standard_error = string(ex.message);
end
try
    q_pf = runpf(mpc, mpoption('verbose',0,'out.all',0, ...
        'pf.enforce_q_lims',1));
catch ex
    q_error = string(ex.message);
end
diagnostics = struct('standard_error', standard_error, 'q_error', q_error);
end

function tf = needs_projection(q_pf, diagnostics, options, trusted_branch_mask)
tf = ~isfield(q_pf,'success') || ~logical(q_pf.success);
if tf, return; end
if ~options.project_on_limit_violation, return; end
define_constants;
online = q_pf.gen(:,GEN_STATUS)>0;
v = q_pf.bus(:,VM) < q_pf.bus(:,VMIN)-1e-6 | ...
    q_pf.bus(:,VM) > q_pf.bus(:,VMAX)+1e-6;
    p = online & (q_pf.gen(:,PG) < q_pf.gen(:,PMIN)-options.hard_limit_tolerance_mva | ...
        q_pf.gen(:,PG) > q_pf.gen(:,PMAX)+options.hard_limit_tolerance_mva);
    q = online & (q_pf.gen(:,QG) < q_pf.gen(:,QMIN)-options.hard_limit_tolerance_mva | ...
        q_pf.gen(:,QG) > q_pf.gen(:,QMAX)+options.hard_limit_tolerance_mva);
s = max(hypot(q_pf.branch(:,PF),q_pf.branch(:,QF)), ...
    hypot(q_pf.branch(:,PT),q_pf.branch(:,QT)));
  rated = trusted_branch_mask & q_pf.branch(:,RATE_A)>0 & ...
      q_pf.branch(:,BR_STATUS)>0;
tf = any(v) || any(p) || any(q) || ...
    any(rated & s > q_pf.branch(:,RATE_A)+options.hard_limit_tolerance_mva);
if strlength(diagnostics.q_error) > 0, tf = true; end
end

function metrics = validation_metrics(input_case, standard_pf, q_pf, ...
        closure, control_report, dispatch_targets, trusted_branch_mask, options)
define_constants;
online = q_pf.gen(:,GEN_STATUS)>0;
vviol = q_pf.bus(:,VM)<q_pf.bus(:,VMIN)-1e-6 | ...
    q_pf.bus(:,VM)>q_pf.bus(:,VMAX)+1e-6;
pviol = online & (q_pf.gen(:,PG)<q_pf.gen(:,PMIN)-options.hard_limit_tolerance_mva | ...
    q_pf.gen(:,PG)>q_pf.gen(:,PMAX)+options.hard_limit_tolerance_mva);
qviol = online & (q_pf.gen(:,QG)<q_pf.gen(:,QMIN)-options.hard_limit_tolerance_mva | ...
    q_pf.gen(:,QG)>q_pf.gen(:,QMAX)+options.hard_limit_tolerance_mva);
s = max(hypot(q_pf.branch(:,PF),q_pf.branch(:,QF)), ...
    hypot(q_pf.branch(:,PT),q_pf.branch(:,QT)));
all_rated = q_pf.branch(:,RATE_A)>0 & q_pf.branch(:,BR_STATUS)>0;
rated = trusted_branch_mask & all_rated;
bover = rated & s>q_pf.branch(:,RATE_A)+options.hard_limit_tolerance_mva;
diagnostic_bover = all_rated & ...
    s>q_pf.branch(:,RATE_A)+options.hard_limit_tolerance_mva;
variable_q = online & q_pf.gen(:,QMAX)-q_pf.gen(:,QMIN)>1e-6;
qsat = variable_q & (abs(q_pf.gen(:,QG)-q_pf.gen(:,QMIN))<=1e-4 | ...
    abs(q_pf.gen(:,QG)-q_pf.gen(:,QMAX))<=1e-4);
initial_reg = ismember(input_case.bus(:,BUS_TYPE),[PV REF]);
pv_to_pq = initial_reg & q_pf.bus(:,BUS_TYPE)==PQ;
ref_bus = input_case.bus(input_case.bus(:,BUS_TYPE)==REF,BUS_I);
ref_gen = ismember(input_case.gen(:,GEN_BUS),ref_bus) & online;
ref_pickup = sum(q_pf.gen(ref_gen,PG)-input_case.gen(ref_gen,PG));
external = control_report.external_gen_idx;
external = external(external>=1 & external<=size(q_pf.gen,1));
internal = online; internal(external)=false;
total_load = sum(q_pf.bus(:,PD));
losses = sum(q_pf.gen(online,PG))-total_load;
if isfield(closure, 'post_projection_interface_table')
    interface_rows = closure.post_projection_interface_table;
else
    interface_rows = recompute_final_interface_table(q_pf, closure);
end
calibrated = logical(interface_rows.calibration_eligible);
final_interface_residual = interface_rows.final_ac_residual_mw(calibrated);
seed_redispatch = sum(abs(dispatch_targets.seed_to_final_redispatch_mw));
source_balanced_redispatch = sum(abs( ...
    dispatch_targets.source_balanced_prior_to_final_redispatch_mw));
source_redispatch = sum(abs( ...
    dispatch_targets.source_prior_to_final_redispatch_mw));
original_redispatch = sum(abs( ...
    dispatch_targets.original_to_final_redispatch_mw));
redispatch_percent = 100 * source_balanced_redispatch / max(total_load, eps);
redispatch_justified = strlength(strtrim(string( ...
    options.redispatch_justification))) > 0;
redispatch_pass = source_balanced_redispatch <= ...
    options.redispatch_hard_limit_mw && ...
    (redispatch_percent <= options.redispatch_percent_of_load || ...
    redispatch_justified);
interface_mae = mean(abs(final_interface_residual));
interface_max = max(abs(final_interface_residual));
interface_bias = mean(final_interface_residual);
interface_pass = interface_mae <= options.interface_mae_mw && ...
    interface_max <= options.interface_max_residual_mw && ...
    abs(interface_bias) <= options.interface_signed_bias_mw;
reference_pass = abs(ref_pickup)<options.reference_pickup_tolerance_mw;
hard_limit_pass = ~any(vviol) && ~any(pviol) && ~any(qviol) && ~any(bover);
closure_pass = logical(closure.converged) && interface_pass && reference_pass;
metrics = struct('standard_pf_success', success_flag(standard_pf), ...
    'q_limit_pf_success', success_flag(q_pf), ...
    'restoration_slack_mw', 0, 'restoration_slack_mvar', 0, ...
    'voltage_violation_count', sum(vviol), ...
    'generator_p_violation_count', sum(pviol), ...
    'generator_q_violation_count', sum(qviol), ...
    'branch_overload_count', sum(bover), ...
    'diagnostic_all_rated_branch_overload_count', sum(diagnostic_bover), ...
    'q_saturation_count', sum(qsat), ...
    'regulating_generator_count', sum(variable_q), ...
    'pv_to_pq_conversion_count', sum(pv_to_pq), ...
    'reference_pickup_mw', ref_pickup, ...
    'reference_pickup_pass', reference_pass, ...
    'total_load_mw', total_load, 'active_loss_mw', losses, ...
    'internal_generation_mw', sum(q_pf.gen(internal,PG)), ...
    'external_schedule_mw', sum(q_pf.gen(external,PG)), ...
    'min_voltage_pu', min(q_pf.bus(:,VM)), ...
    'max_voltage_pu', max(q_pf.bus(:,VM)), ...
    'max_branch_overload_mva', max([0;s(bover)-q_pf.branch(bover,RATE_A)]), ...
    'closure_converged', logical(closure.converged), ...
    'closure_max_calibrated_residual_mw', interface_max, ...
    'closure_interface_mae_mw', interface_mae, ...
    'closure_signed_bias_mw', interface_bias, ...
    'interface_gate_pass', interface_pass, ...
    'seed_to_final_redispatch_mw', seed_redispatch, ...
    'source_balanced_prior_to_final_redispatch_mw', ...
        source_balanced_redispatch, ...
    'source_prior_to_final_redispatch_mw', source_redispatch, ...
    'original_to_final_redispatch_mw', original_redispatch, ...
    'redispatch_percent_of_load', redispatch_percent, ...
    'redispatch_justified', redispatch_justified, ...
    'redispatch_gate_pass', redispatch_pass, ...
    'trusted_static_branch_count', sum(rated), ...
    'hard_limit_gate_pass', hard_limit_pass, ...
    'all_operating_gates_pass', success_flag(standard_pf) && ...
        success_flag(q_pf) && closure_pass && hard_limit_pass && ...
        redispatch_pass);
end

function rows = recompute_final_interface_table(result, closure)
if ~isfield(closure, 'interface_table') || isempty(closure.interface_table) || ...
        ~isfield(closure, 'interface_definitions') || ...
        isempty(closure.interface_definitions)
    error('build_s11_dlr_pf_case:InterfaceProvenance', ...
        'Final interface validation requires the closure table and definitions.');
end
rows = closure.interface_table;
flows = ny_lite_interface_flows(result, closure.interface_definitions);
flow_names = string({flows.interface_name})';
flow_types = string({flows.result_type})';
final_flow = nan(height(rows), 1);
for k = 1:height(rows)
    idx = find(flow_names == string(rows.interface_name(k)) & ...
        flow_types == "subpath");
    if numel(idx) ~= 1
        error('build_s11_dlr_pf_case:InterfaceResolution', ...
            'Final interface %s resolved to %d subpath records.', ...
            string(rows.interface_name(k)), numel(idx));
    end
    final_flow(k) = flows(idx).flow_mw;
end
rows.final_ac_flow_mw = final_flow;
rows.final_ac_residual_mw = final_flow-rows.target_flow_mw;
end

function [targets, diagnostics] = refresh_final_dispatch_targets( ...
        targets, scheduled_case, result, control_report, closure)
required = {'zone','original_scenario_generation_mw', ...
    'seeded_initial_generation_mw','target_generation_mw', ...
    'final_actual_generation_mw','original_to_final_redispatch_mw', ...
    'seed_to_final_redispatch_mw','final_generation_error_mw'};
if ~istable(targets) || ~all(ismember(required, ...
        targets.Properties.VariableNames)) || ...
        ~isfield(control_report, 'active_dispatch_gen_idx') || ...
        ~isstruct(closure) || ...
        ~isfield(closure, 'source_pg_prior_zonal_generation_mw') || ...
        ~isfield(closure, 'source_balance_prior_zonal_generation_mw') || ...
        ~isfield(closure, 'scenario_balance_prior_zonal_generation_mw')
    error('build_s11_dlr_pf_case:DispatchProvenance', ...
        'Final dispatch validation requires zonal seed and active-control provenance.');
end
zones = string(targets.zone(:));
active_idx = double(control_report.active_dispatch_gen_idx(:));
scheduled = active_zonal_generation(scheduled_case, active_idx, zones);
actual = active_zonal_generation(result, active_idx, zones);
seed = double(targets.seeded_initial_generation_mw(:));
original = double(targets.original_scenario_generation_mw(:));
source_prior = double(closure.source_pg_prior_zonal_generation_mw(:));
source_balance_prior = double( ...
    closure.source_balance_prior_zonal_generation_mw(:));
scenario_balance_prior = double( ...
    closure.scenario_balance_prior_zonal_generation_mw(:));
if numel(source_prior) ~= numel(zones) || ...
        numel(source_balance_prior) ~= numel(zones) || ...
        numel(scenario_balance_prior) ~= numel(zones) || ...
        any(~isfinite(source_prior)) || ...
        any(~isfinite(source_balance_prior)) || ...
        any(~isfinite(scenario_balance_prior))
    error('build_s11_dlr_pf_case:DispatchProvenance', ...
        'Closure dispatch priors are missing, nonfinite, or zone-misaligned.');
end
targets.target_generation_mw = scheduled;
targets.final_actual_generation_mw = actual;
targets.source_pg_prior_generation_mw = source_prior;
targets.source_balance_prior_generation_mw = source_balance_prior;
targets.scenario_balance_prior_generation_mw = scenario_balance_prior;
targets.original_to_final_redispatch_mw = actual-original;
targets.seed_to_final_redispatch_mw = actual-seed;
targets.source_prior_to_final_redispatch_mw = actual-source_prior;
targets.source_balanced_prior_to_final_redispatch_mw = ...
    actual-source_balance_prior;
targets.scenario_balanced_prior_to_final_redispatch_mw = ...
    actual-scenario_balance_prior;
targets.final_generation_error_mw = actual-scheduled;
if all(ismember({'pmin_mw','pmax_mw','at_pmin','at_pmax'}, ...
        targets.Properties.VariableNames))
    targets.at_pmin = abs(actual-targets.pmin_mw) <= 1e-6;
    targets.at_pmax = abs(actual-targets.pmax_mw) <= 1e-6;
end
diagnostics = struct('zones', zones, ...
    'active_dispatch_gen_idx', active_idx, ...
    'scheduled_zonal_generation_mw', scheduled, ...
    'actual_zonal_generation_mw', actual, ...
    'seed_to_final_redispatch_mw', actual-seed, ...
    'source_balanced_prior_to_final_redispatch_mw', ...
        actual-source_balance_prior, ...
    'scenario_balanced_prior_to_final_redispatch_mw', ...
        actual-scenario_balance_prior, ...
    'source_prior_to_final_redispatch_mw', actual-source_prior, ...
    'total_absolute_seed_to_final_redispatch_mw', sum(abs(actual-seed)), ...
    'total_absolute_source_balanced_prior_to_final_redispatch_mw', ...
        sum(abs(actual-source_balance_prior)), ...
    'total_absolute_scenario_balanced_prior_to_final_redispatch_mw', ...
        sum(abs(actual-scenario_balance_prior)), ...
    'total_absolute_source_prior_to_final_redispatch_mw', ...
        sum(abs(actual-source_prior)));
end

function generation = active_zonal_generation(mpc, active_idx, zones)
define_constants;
if any(~isfinite(active_idx) | active_idx < 1 | ...
        active_idx > size(mpc.gen, 1) | active_idx ~= fix(active_idx))
    error('build_s11_dlr_pf_case:ActiveDispatchIndex', ...
        'An active-dispatch generator index is invalid in the final case.');
end
mpc = attach_nyiso_zone_metadata(mpc);
online_idx = active_idx(mpc.gen(active_idx,GEN_STATUS)>0);
[found, bus_idx] = ismember(mpc.gen(online_idx,GEN_BUS), mpc.bus(:,BUS_I));
if any(~found)
    error('build_s11_dlr_pf_case:ActiveDispatchBus', ...
        'An active-dispatch generator bus is absent from the final case.');
end
gen_zone = upper(string(mpc.userdata.nyiso_physical_zone(bus_idx)));
generation = zeros(numel(zones), 1);
for k = 1:numel(zones)
    generation(k) = sum(mpc.gen(online_idx(gen_zone == ...
        upper(zones(k))),PG));
end
end

function trusted = trusted_static_branch_mask(branch_map, mpc)
define_constants;
if ismember('trusted_static_limit', branch_map.Properties.VariableNames)
    trusted = logical(branch_map.trusted_static_limit);
else
    trusted = branch_map.branch_classification == "physical_circuit";
end
trusted = trusted(:) & mpc.branch(:,BR_STATUS) > 0;
end

function value = success_flag(result)
value = isfield(result,'success') && logical(result.success);
end

function [gen_idx, zone] = mapped_operational_reference(control_report)
required_report = {'generator_report','active_dispatch_gen_idx'};
if ~isstruct(control_report) || ...
        ~all(isfield(control_report, required_report)) || ...
        ~istable(control_report.generator_report)
    error('build_s11_dlr_pf_case:MappedReference', ...
        'The control mapper did not return generator-level reference provenance.');
end
rows = control_report.generator_report;
required_columns = {'reduced_gen_index','zone', ...
    'is_native_active_control','is_operational_reference'};
if ~all(ismember(required_columns, rows.Properties.VariableNames))
    error('build_s11_dlr_pf_case:MappedReference', ...
        'The control report lacks operational-reference columns.');
end
mask = logical(rows.is_operational_reference) & ...
    logical(rows.is_native_active_control) & ...
    ismember(double(rows.reduced_gen_index), ...
        double(control_report.active_dispatch_gen_idx(:)));
candidates = unique(double(rows.reduced_gen_index(mask)));
if numel(candidates) ~= 1
    error('build_s11_dlr_pf_case:MappedReference', ...
        ['Exactly one source-backed native active control must be the ' ...
        'operational reference; found %d.'], numel(candidates));
end
gen_idx = candidates(1);
zones = unique(upper(string(rows.zone(mask & ...
    double(rows.reduced_gen_index) == gen_idx))));
if numel(zones) ~= 1 || strlength(zones) ~= 1
    error('build_s11_dlr_pf_case:MappedReference', ...
        'The mapped operational reference must have one NYISO zone.');
end
zone = zones(1);
end

function files = write_case_files(input_case, solution, scenario_id, options)
role = scenario_role(scenario_id);
files = struct('input_file', "", 'solution_file', "");
is_central = abs(options.q_multiplier-1)<1e-12;
if is_central && role == "summer_peak"
    files.input_file = string(fullfile(options.case_dir, ...
        'npcc_ny_lite_s11_dlr_pf_base_candidate_unvalidated.m'));
    files.solution_file = string(fullfile(options.case_dir, ...
        'npcc_ny_lite_s11_dlr_pf_solution_candidate_unvalidated.m'));
    write_s11_case_set_atomic([files.input_file; files.solution_file], ...
        {input_case; solution}, [false; true]);
elseif is_central && role == "winter_peak"
    files.solution_file = string(fullfile(options.case_dir, ...
        'npcc_ny_lite_s11_dlr_winter_candidate_unvalidated.m'));
    write_s11_case_set_atomic(files.solution_file, {solution}, true);
elseif is_central && role == "high_total_east"
    files.solution_file = string(fullfile(options.case_dir, ...
        'npcc_ny_lite_s11_dlr_high_total_east_candidate_unvalidated.m'));
    write_s11_case_set_atomic(files.solution_file, {solution}, true);
else
    qtag = sprintf('q%03d',round(100*options.q_multiplier));
    files.solution_file = string(fullfile(options.case_dir, sprintf( ...
        'npcc_ny_lite_s11_dlr_%s_%s_candidate_unvalidated.m',role,qtag)));
    write_s11_case_set_atomic(files.solution_file, {solution}, true);
end
end

function role = scenario_role(scenario_id)
switch string(scenario_id)
    case "S1_2025_SUMMER_PEAK_PUBLIC", role = "summer_peak";
    case "S2_2025_WINTER_PEAK_PUBLIC", role = "winter_peak";
    case "S5_2025_HIGH_TOTAL_EAST_PUBLIC", role = "high_total_east";
    otherwise
        role = lower(regexprep(string(scenario_id),'[^A-Za-z0-9]+','_'));
end
end

function value = ternary(condition, yes, no)
if condition, value = yes; else, value = no; end
end
