function out=build_compact_npcc_corridors(options)
%BUILD_COMPACT_NPCC_CORRIDORS Focused replacements on the NPCC benchmark.
% Keeps the S7/Phase-0 benchmark injections and controls. Two added, zero-
% injection source terminals and eleven source branches replace five old
% rows. This is a compact research corridor substitution, not a PERFORM
% operating-state transplant or an exact reduction of the whole source NY.
if nargin<1,options=struct();end
if ~isfield(options,'write_outputs'),options.write_outputs=false;end
h=fileparts(mfilename('fullpath'));root=fileparts(fileparts(h));addpath(fileparts(h));
if ~isfield(options,'output_dir'),options.output_dir=fullfile(root,'output','compact_npcc_corridors');end
assert(~isfield(options,'parent'),'compact_npcc:ParentOverride','Only the reproducible S7/Phase-0 parent is supported.');
p=loadcase('npcc_ny_lite_s7_seven_interface_perform_direct_candidate');
[p,phase0]=apply_ny_core_phase0_corrections(p,struct('fit_reactance',false,'verbose',false));
assert(isequal([size(p.bus,1) size(p.branch,1) size(p.gen,1)],[143 246 62]), ...
    'compact_npcc:Parent','Unexpected immutable benchmark parent dimensions.');
n=normalize_perform_ny_source;s=n.source;
assert(p.baseMVA==100&&s.baseMVA==100,'compact_npcc:Base','Both sources must use 100 MVA.');
sr=[1389;1390;1391;1392;1689;1690;1734;1735;1577;1576;1738];
source_bus=[651;858;902;897;1519;774;900];model_bus=[73;858;9002;74;76;774;77];
new_source=[858;774];retired=[88;89;94;235;236];
expected_retired=[73 74;73 74;76 77;73 9002;9002 74];
assert(isequal(p.branch(retired,1:2),expected_retired)&&all(p.branch(retired,11)==1), ...
    'compact_npcc:RetirementIdentity','The five retired rows do not match the registered endpoint identities.');
expected_pairs=[73 9002 .000405 .006185 .63943 2432 4908 3608 0 0 1 -360 360; ...
    9002 74 .000185 .002815 .29107 2432 4908 3608 0 0 1 -360 360];
assert(isequal(p.branch([235 236],1:13),expected_pairs), ...
    'compact_npcc:AggregateIdentity','The two S7 exact parallel equivalents changed.');
[found,si]=ismember(source_bus,s.bus(:,1));assert(all(found));
[old,parent_bus_row]=ismember(model_bus,p.bus(:,1));
names=upper(strtrim(string(s.bus_name(si))));
expected_names=["PLEASANT VALLEY";"E. FISHKILL";"WOOD STREET";"MILLWOOD";"RAMAPO";"LADENTOWN";"BUCHANAN"];
assert(isequal(names,expected_names)&&all(s.bus(si,10)==345), ...
    'compact_npcc:SourceTerminal','Source names or voltage classes changed.');
parent_names=strings(numel(source_bus),1);parent_names(old)=upper(strtrim(string(p.bus_name(parent_bus_row(old)))));
assert(isequal(parent_names(old),["PLEASANT VLY";"WOOD STREET";"MILLWOOD";"RAMAPO";"BUCHANAN"]) ...
    && all(p.bus(parent_bus_row(old),10)==345),'compact_npcc:TerminalAlias','Benchmark attachment identities changed.');
assert(all(n.branch_inventory.individual_circuit_identity_resolved(sr)) ...
    && all(n.branch_inventory.raw_canonical_parameters_match(sr)), ...
    'compact_npcc:CircuitIdentity','Selected source circuits require unique RAW electrical matches.');

c=p;
for k=1:numel(new_source)
    j=find(s.bus(:,1)==new_source(k));anchor=[73;76];source_anchor=[651;1519];
    q=find(p.bus(:,1)==anchor(k));r=find(s.bus(:,1)==source_anchor(k));
    row=s.bus(j,1:13);row(2)=1;row(3:6)=0;row(7)=p.bus(q,7);
    row(8)=row(8)*p.bus(q,8)/s.bus(r,8);row(9)=row(9)+p.bus(q,9)-s.bus(r,9);
    c.bus(end+1,:)=row;c.bus_name{end+1,1}=s.bus_name{j};
    entry=struct('bus_id',new_source(k),'physical_zone','G','load_allocation_group','G', ...
        'nyiso_zone_name','HUD VL','nyiso_zone_id',7,'perform_zone_code',71);
    c.userdata.ny_lite.transit_zone_metadata(end+1)=entry;
end
c=attach_nyiso_zone_metadata(c);c.branch(retired,11)=0;
br=s.branch(sr,1:13);[found,f]=ismember(br(:,1),source_bus);[found_t,t]=ismember(br(:,2),source_bus);
assert(all(found&found_t),'compact_npcc:Endpoint','Selected branch endpoint is outside the registered corridor.');
br(:,1)=model_bus(f);br(:,2)=model_bus(t);br(:,12)=-360;br(:,13)=360;
mr=(247:257)';c.branch=[c.branch;br];

bus_map=table(source_bus,model_bus,string(s.bus_name(si)),parent_names,s.bus(si,10), ...
    perform_nyiso_zone_letters(s,source_bus),~old, ...
    'VariableNames',{'source_bus','model_bus','source_bus_name','parent_bus_name','source_base_kv','physical_zone','added_terminal'});
bus_map.mapping_basis=["registered_Pleasant_Valley_name_alias";"new_original_source_terminal"; ...
    "exact_name_voltage";"exact_name_voltage";"exact_name_voltage"; ...
    "new_original_source_terminal";"exact_name_voltage"];
bus_map.operating_policy=repmat("retain_NPCC_benchmark_devices_source_devices_not_imported",height(bus_map),1);
bus_map.operating_policy(~old)="zero_injection_PQ_transit_terminal_source_devices_excluded";
physical=n.branch_inventory(sr,:);physical.model_branch_row=mr;
physical.model_from_bus=br(:,1);physical.model_to_bus=br(:,2);
physical.source_base_mva=repmat(s.baseMVA,height(physical),1);
physical.source_angle_min_deg=s.branch(sr,12);physical.source_angle_max_deg=s.branch(sr,13);
physical.model_angle_min_deg=br(:,12);physical.model_angle_max_deg=br(:,13);
physical.angle_policy=repmat("source_0_0_and_model_minus360_plus360_both_unrestricted",height(physical),1);
physical.source_sha256_lf_normalized=repmat(n.canonical_sha256,height(physical),1);
physical.replacement_family=[repmat("Pleasant_Valley_East_Fishkill_Wood_Millwood",8,1); ...
    repmat("Ramapo_Ladentown_Buchanan",3,1)];
physical.dlr_eligible=false(height(physical),1);
physical.thermal_identity_policy=repmat("electrical_source_identity_only_conductor_weather_and_equipment_type_unqualified",height(physical),1);

disposition=repmat("retained_NPCC_benchmark_equivalent",246,1);
disposition(234:246)="retained_S7_benchmark_delivery_equivalent_no_new_physical_identity_claim";
disposition([88 89 94])="retired_complete_corridor_function_assumed_response_change";
disposition([235 236])="retired_exact_source_parallel_aggregate";
parent_register=table((1:246)',p.branch(:,1),p.branch(:,2),p.branch(:,11),c.branch(1:246,11),disposition, ...
    'VariableNames',{'parent_branch_row','from_bus','to_bus','parent_status','candidate_status','disposition'});
parent_register.replacement_source_rows=repmat("",246,1);
parent_register.replacement_source_rows([88 89])="1389;1390;1391;1392;1689;1690;1734;1735";
parent_register.replacement_source_rows(94)="1577;1576;1738";
parent_register.replacement_source_rows(235)="1391;1392";
parent_register.replacement_source_rows(236)="1734;1735";
parent_register.residual_added=false(246,1);parent_register.dlr_eligible=false(246,1);

% Exact aggregation is established only for the two previously documented
% S7 source equivalents. Original NPCC rows88/89/94 are retired as entire
% corridor functions; their response changes are recorded, not fitted away.
exact=table();
for k=1:2
    oldrow=[235 236];rr={[249;250],[253;254]};ends={[73;9002],[9002;74]};
    yo=port_y(p,oldrow(k),ends{k});yn=port_y(c,rr{k},ends{k});
    states=[1 1 0;1 1 8;1 1 -8;.95 1.05 15;1.05 .95 -15;1.02 .98 3];
    flow_error=0;
    for j=1:size(states,1)
        v=[states(j,1)*exp(1i*pi/180*states(j,3));states(j,2)];
        flow_error=max(flow_error,max(abs(100*v.*conj((yo-yn)*v))));
    end
    row=table(oldrow(k),strjoin(string(rr{k}),';'),max(abs(yo-yn),[],'all'),flow_error, ...
        "exact_two_circuit_parallel_replacement",false, ...
        'VariableNames',{'parent_branch_row','physical_model_rows','max_admittance_error_pu', ...
        'max_matched_flow_error_mva','scope','residual_fit_performed'});
    exact=[exact;row]; %#ok<AGROW>
end
changed=table();oldsets={[88;89],[88;89;235;236],94};newsets={(247:254)',(247:254)',(255:257)'};
ends={[73;74],[73;74],[76;77]};labels=["original_NPCC_Pleasant_Valley_Millwood"; ...
    "complete_S7_Pleasant_Valley_Millwood_parallel_function";"original_NPCC_Ramapo_Buchanan"];
for k=1:3
    yo=port_y(p,oldsets{k},ends{k});yn=port_y(c,newsets{k},ends{k});residual=yo-yn;
    row=table(labels(k),strjoin(string(oldsets{k}),';'),strjoin(string(newsets{k}),';'), ...
        max(abs(yo-yn),[],'all'),abs(yn(1,2))/abs(yo(1,2)), ...
        min(real(eig((residual+residual')/2))),false,false, ...
        "entire_old_function_removed_no_original_response_equivalence_claim", ...
        'VariableNames',{'corridor','retired_parent_rows','physical_model_rows', ...
        'port_admittance_difference_pu','new_over_old_transfer_admittance', ...
        'unimplemented_difference_min_hermitian_eigenvalue','response_preserved', ...
        'residual_fit_performed','policy'});
    changed=[changed;row]; %#ok<AGROW>
end

excluded=source_exclusions(n,source_bus);
incident=find(ismember(s.branch(:,1),source_bus)|ismember(s.branch(:,2),source_bus));
omitted=n.branch_inventory(setdiff(incident,sr),:);
omitted.policy=repmat("outside_selected_corridor_not_copied_benchmark_network_retained",height(omitted),1);
z=string(c.userdata.nyiso_physical_zone);ny=ismember(z,string(('A':'K')'));ids=c.bus(ny,1);
nybr=ismember(c.branch(:,1),ids)&ismember(c.branch(:,2),ids);nygen=ismember(c.gen(:,1),ids);
assert(sum(ny)<=200,'compact_npcc:BusCap','NY study exceeds the hard 200-bus limit.');
expected=p.branch;expected(retired,11)=0;
gates=table(["frozen_source_manifest";"parent_dimensions";"all_parent_buses_unchanged"; ...
    "all_parent_generators_unchanged";"only_five_parent_status_changes";"two_zero_injection_terminals"; ...
    "eleven_source_circuits_exact";"unique_source_circuit_keys";"exact_S7_parallel_identities"; ...
    "no_fitted_residual_or_superimposed_retired_rows";"NY_bus_cap_and_counts"; ...
    "NY_branch_counts";"source_devices_excluded_not_added"], ...
    [n.validation.pass;size(p.bus,1)==143;isequal(c.bus(1:143,:),p.bus); ...
    isequal(c.gen,p.gen)&&isequal(c.gencost,p.gencost);isequal(c.branch(1:246,:),expected); ...
    all(c.bus(144:145,3:6)==0,'all')&&all(c.bus(144:145,2)==1); ...
    isequal(c.branch(mr,3:11),s.branch(sr,3:11));numel(unique(physical.device_key))==11; ...
    all(exact.max_admittance_error_pu<1e-11&exact.max_matched_flow_error_mva<1e-8); ...
    all(c.branch(retired,11)==0)&&~any(parent_register.residual_added); ...
    sum(ny)==51&&sum(ny)<=200&&size(c.bus,1)==145; ...
    sum(nybr)==92&&sum(nybr&c.branch(:,11)>0)==87;all(excluded.added_to_benchmark==false)], ...
    'VariableNames',{'metric','passed'});
assert(all(gates.passed),'compact_npcc:Validation','Compact corridor construction failed a preservation gate.');
keys=["NPCC_S7:BRANCH_ROW:"+string((1:246)');physical.device_key];
genkeys="NPCC_S7:GEN_ROW:"+string((1:size(c.gen,1))')+":BUS:"+string(c.gen(:,1));
c.userdata.compact_npcc=struct('model_role','NPCC_benchmark_with_focused_source_corridor_replacements', ...
    'power_scale','NPCC_benchmark_MW_not_PERFORM_actual_2019_MW','parent_bus_count',143, ...
    'added_bus_ids',new_source,'retired_parent_rows',retired,'physical_model_rows',mr, ...
    'source_branch_rows',sr,'ny_bus_limit',200,'ny_bus_count',sum(ny), ...
    'parent_devices_preserved',true,'source_devices_imported',false, ...
    'residual_fit_performed',false,'electrical_baseline_qualified',false,'dlr_ready',false);
out=struct('candidate',c,'full_candidate',c,'parent',p,'phase0_report',phase0, ...
    'source_inventory',n,'source_manifest',n.source_manifest,'bus_map',bus_map, ...
    'physical_branch_register',physical,'source_branch_map',physical, ...
    'parent_branch_disposition',parent_register,'source_device_exclusion_register',excluded, ...
    'source_connection_omission_register',omitted, ...
    'local_identity_tests',exact,'functional_replacement_comparison',changed, ...
    'ny_bus_ids',ids,'ny_bus_mask',ny,'ny_branch_mask',nybr,'ny_generator_mask',nygen, ...
    'branch_keys',keys,'generator_keys',genkeys,'retired_parent_rows',retired, ...
    'validation',struct('pass',all(gates.passed),'gates',gates), ...
    'power_scale','NPCC_benchmark_MW_not_PERFORM_actual_2019_MW', ...
    'electrical_baseline_qualified',false,'dlr_ready',false);
if options.write_outputs
    if ~isfolder(options.output_dir),mkdir(options.output_dir);end
    for field=["bus_map","physical_branch_register","parent_branch_disposition", ...
            "source_device_exclusion_register","source_connection_omission_register", ...
            "local_identity_tests","functional_replacement_comparison","source_manifest"]
        ny_lite_writetable_lf(out.(field),fullfile(options.output_dir,"compact_npcc_"+field+".csv"));
    end
    ny_lite_writetable_lf(gates,fullfile(options.output_dir,'compact_npcc_corridor_validation.csv'));
    save(fullfile(options.output_dir,'compact_npcc_full_construction.mat'),'out');
end
end

function y=port_y(m,rows,ports)
ids=unique(m.branch(rows,1:2));inside=setdiff(ids,ports);ids=[ports(:);inside(:)];
[found,bi]=ismember(ids,m.bus(:,1));assert(all(found));bus=m.bus(bi,1:13);bus(:,1)=(1:numel(ids))';bus(:,5:6)=0;
br=m.branch(rows,1:13);[~,br(:,1)]=ismember(br(:,1),ids);[~,br(:,2)]=ismember(br(:,2),ids);
y=full(makeYbus(m.baseMVA,bus,br));
if numel(ids)>2,y=y(1:2,1:2)-y(1:2,3:end)*(y(3:end,3:end)\y(3:end,1:2));end
end

function e=source_exclusions(n,buses)
s=n.source;[~,si]=ismember(buses,s.bus(:,1));nb=numel(buses);
e=table("PERFORM2019:BUS:"+string(buses),buses,nan(nb,1), ...
    repmat("source_bus_load_and_shunt",nb,1),ones(nb,1), ...
    s.bus(si,3),s.bus(si,4),s.bus(si,5),s.bus(si,6),false(nb,1), ...
    'VariableNames',{'device_key','source_bus','source_gen_row','device_family','canonical_status', ...
    'source_p_mw','source_q_mvar','source_gs_mw','source_bs_mvar','added_to_benchmark'});
g=n.generator_inventory(ismember(n.generator_inventory.source_bus,buses),:);ng=height(g);
e=[e;table(g.device_key,g.source_bus,g.source_gen_row,g.source_device_role,g.canonical_status, ...
    g.source_pg_mw,g.source_qg_mvar,zeros(ng,1),zeros(ng,1),false(ng,1), ...
    'VariableNames',e.Properties.VariableNames)];
e.raw_generator_status=[nan(nb,1);g.raw_status];
e.source_pmin_mw=[nan(nb,1);g.source_pmin_mw];e.source_pmax_mw=[nan(nb,1);g.source_pmax_mw];
e.source_qmin_mvar=[nan(nb,1);g.source_qmin_mvar];e.source_qmax_mvar=[nan(nb,1);g.source_qmax_mvar];
e.policy=repmat("excluded_preserve_inherited_NPCC_benchmark_injection_and_control_records",height(e),1);
end
