function out=build_ny_foundation_reference(normalized,boundary,options)
%BUILD_NY_FOUNDATION_REFERENCE Bounded actual-MW historical source benchmark.
% Native P priors are reproduced source outputs, not observations. Fixed
% gross demand, boundary PQ, shunts, branch parameters and source limits.
% Marcy RF is retired; a distinct finite research Q-only support is declared.
if nargin<3,options=struct();end
define_constants;
a=apply_ny_boundary_injections(normalized,boundary);c=a.candidate;
assert(height(boundary.reference_register)==1&&boundary.reference_register.source_bus==1263, ...
    'build_ny_foundation_reference:ReferenceIdentity','Expected original Marcy RF placeholder.');
native=a.native_generator_map;ng=size(c.gen,1);c.gen=c.gen(:,1:21);
ref=847;refgen=find(c.gen(:,GEN_BUS)==ref&c.gen(:,GEN_STATUS)>0,1);
assert(~isempty(refgen)&&c.gen(refgen,PMAX)>c.gen(refgen,PG), ...
    'build_ny_foundation_reference:NativeReference','Roseton native balancing headroom required.');
c.bus(c.bus(:,BUS_TYPE)==REF,BUS_TYPE)=PV;
c.bus(c.bus(:,BUS_I)==ref,BUS_TYPE)=REF;
support_key="RESEARCH2019:Q_SUPPORT:1263:MARCY";
support=zeros(1,21);marcy=find(c.bus(:,BUS_I)==1263);
support([GEN_BUS PG QG QMAX QMIN VG MBASE GEN_STATUS PMAX PMIN])= ...
    [1263 0 boundary.reference_register.snapshot_qg_mvar 900 -900 c.bus(marcy,VM) c.baseMVA 1 0 0];
c.gen=[c.gen;support];c.bus(marcy,BUS_TYPE)=PV;
% Cost is replaced by the reconstruction's explicit prior-only objective.
c.gencost=[2*ones(ng+1,1),zeros(ng+1,2),2*ones(ng+1,1),zeros(ng+1,2)];
for field={'gentype','genfuel','gen_name'}
    f=field{1};if isfield(c,f),c.(f)=[string(c.(f));"assumed_research_Q_support"];end
end
c=rmfield(c,intersect(fieldnames(c),{'order','success','et','iterations'}));
keys=[string(native.device_key);support_key];
prior=c.gen(:,PG);qprior=c.gen(:,QG);
support_register=table(support_key,1263,0,0,-900,900,"assumed", ...
    "finite_PV_Q_only_support_replaces_unresolved_RF_voltage_control", ...
    "round_900_MVAr_envelope_covers_reproduced_719_76_MVAr_absorption_with_margin", ...
    "not_a_verified_physical_device_or_contemporary_asset", ...
    'VariableNames',{'device_key','source_bus','pmin_mw','pmax_mw','qmin_mvar','qmax_mvar', ...
    'provenance','model_policy','bound_basis','limitation'});
controls=struct('Pg_prior_mw',prior,'Pg_sigma_mw',max(50,.25*(c.gen(:,PMAX)-c.gen(:,PMIN))));
% A fixed-control trial records the immediate consequence of retiring RF.
trial=runpf(c,mpoption('verbose',0,'out.all',0,'pf.enforce_q_lims',1,'pf.tol',1e-10));
audit_options=struct('generator_keys',keys,'branch_keys',normalized.branch_inventory.device_key);
trial_audit=audit_ny_ac_reference(trial,audit_options);
initial=c;if trial.success,initial=trial;end
r=reconstruct_ac_operating_point(initial,controls,struct('solver','matpower_prior'));
bounded_audit=audit_ny_ac_reference(r.result,audit_options);
replay_audit=audit_ny_ac_reference(r.fixed_input_pf,audit_options);
pf=r.fixed_input_pf;
native_on=c.gen(1:ng,GEN_STATUS)>0;
native_delta=pf.gen(1:ng,PG)-prior(1:ng);
dispatch=table((1:ng+1)',keys,c.gen(:,GEN_BUS),c.gen(:,GEN_STATUS)>0,prior,pf.gen(:,PG), ...
    pf.gen(:,PG)-prior,qprior,pf.gen(:,QG),pf.gen(:,QG)-qprior, ...
    'VariableNames',{'gen_row','device_key','source_bus','online','source_prior_pg_mw', ...
    'reconstructed_pg_mw','pg_movement_mw','source_prior_qg_mvar','reconstructed_qg_mvar','qg_movement_mvar'});
ref_rows=find(c.gen(:,GEN_BUS)==ref&c.gen(:,GEN_STATUS)>0);
reference_adjustment=table(ref_rows,keys(ref_rows),r.result.gen(ref_rows,PG),pf.gen(ref_rows,PG), ...
    pf.gen(ref_rows,PG)-r.result.gen(ref_rows,PG), ...
    'VariableNames',{'gen_row','device_key','bounded_pg_mw','replay_pg_mw','replay_adjustment_mw'});
gross=sum(a.bus_injection_ledger.pd_gross_mw);imports=sum(a.bus_injection_ledger.p_boundary_mw);
loss=replay_audit.summary.branch_loss_mw+replay_audit.summary.shunt_loss_mw;
native_total=sum(pf.gen(find(native_on),PG)); %#ok<FNDSB>
accounting=table(gross,imports,native_total,loss,native_total+imports-gross-loss, ...
    sum(abs(native_delta(native_on))),sum(native_delta(native_on)),0,pf.gen(end,PG),pf.gen(end,QG), ...
    'VariableNames',{'gross_load_mw','fixed_boundary_p_mw','native_generation_mw','total_loss_mw', ...
    'balance_error_mw','native_dispatch_l1_movement_mw','native_dispatch_net_movement_mw', ...
    'boundary_schedule_movement_mw','assumed_support_p_mw','assumed_support_q_mvar'});
accounting.native_reactive_l1_movement_mvar=sum(abs(pf.gen(find(native_on),QG)-qprior(find(native_on)))); %#ok<FNDSB>
accounting.max_voltage_movement_from_source_pu=max(abs(pf.bus(:,VM)-boundary.snapshot_case.bus(:,VM)));
frozen=isequal(c.branch(:,1:13),normalized.source.branch(:,1:13))&& ...
    isequal(pf.branch(:,1:13),c.branch(:,1:13))&& ...
    isequal(pf.bus(:,[PD QD GS BS VMIN VMAX]),c.bus(:,[PD QD GS BS VMIN VMAX]))&& ...
    isequal(pf.gen(:,[PMIN PMAX QMIN QMAX GEN_STATUS]),c.gen(:,[PMIN PMAX QMIN QMAX GEN_STATUS]));
passed=r.success&&bounded_audit.passed&&replay_audit.passed&&frozen&& ...
    abs(accounting.balance_error_mw)<1e-3&&abs(pf.gen(end,PG))<1e-6&& ...
    max(abs(reference_adjustment.replay_adjustment_mw))<1e-3;
out=struct('candidate',c,'application',a,'fixed_control_trial',trial, ...
    'fixed_control_trial_audit',trial_audit,'reconstruction',r,'bounded_audit',bounded_audit, ...
    'replay_audit',replay_audit,'result',pf,'generator_keys',keys, ...
    'support_register',support_register,'dispatch',dispatch,'accounting',accounting, ...
    'reference_adjustment',reference_adjustment,'parameters_frozen',frozen, ...
    'electrical_baseline_qualified',passed,'qualification_scope','assumed_2019_PERFORM_source_reference_only', ...
    'contemporary_validation_coverage','not_evaluated','dlr_ready',false, ...
    'minimum_relaxation_used',false,'fictitious_active_injection_mw',0, ...
    'internal_interface_fit_used',false,'source_controls',controls);
end
