function out=compare_ny_region_to_foundation(build,regional_pf,foundation_pf)
%COMPARE_NY_REGION_TO_FOUNDATION Compare two independently solved AC states.
% Each case uses its own voltages; this is not the matched-common-voltage
% branch identity test. Stored terminal powers are deliberately ignored.
% No error threshold, qualification decision, or response equivalence claim
% is implied. Original source circuit-identity limitations remain visible.
define_constants;
validate_case(regional_pf);validate_case(foundation_pf);
assert(regional_pf.baseMVA==foundation_pf.baseMVA,'ny_response:Base', ...
    'Source and candidate must use the declared common power base.');
bm=build.source_bus_map;em=build.source_branch_map;
assert(all(ismember({'source_bus','model_bus','mapping_kind'},bm.Properties.VariableNames)) && ...
    all(ismember({'source_branch_row','model_branch_row','device_key'},em.Properties.VariableNames)), ...
    'ny_response:MapSchema','Explicit bus and branch identity maps are required.');
assert(numel(unique(bm.source_bus))==height(bm) && ...
    numel(unique(em.source_branch_row))==height(em) && numel(unique(em.model_branch_row))==height(em), ...
    'ny_response:DuplicateMap','Source bus and copied branch mappings must be unique.');
[found,sbi]=ismember(bm.source_bus,foundation_pf.bus(:,BUS_I));
[target,rbi]=ismember(bm.model_bus,regional_pf.bus(:,BUS_I));
assert(all(found&target),'ny_response:BusMap','A mapped bus is absent from an operating result.');
exact=string(bm.mapping_kind)=="exact_source_region";
assert(any(exact)&&numel(unique(bm.model_bus(exact)))==nnz(exact), ...
    'ny_response:ExactRegion','The exact source region must have distinct mapped buses.');
assert(isequal(sort(bm.source_bus(exact)),sort(build.region_source_buses(:))), ...
    'ny_response:ExactRegion','Declared source-region membership differs from its mapping.');
assert(isequal(foundation_pf.bus(sbi(exact),BASE_KV),regional_pf.bus(rbi(exact),BASE_KV)), ...
    'ny_response:VoltageBase','Exact-region terminal voltage bases differ.');
source_ref=find(foundation_pf.bus(:,BUS_TYPE)==REF);region_ref=find(regional_pf.bus(:,BUS_TYPE)==REF);
assert(numel(source_ref)==1&&numel(region_ref)==1,'ny_response:Reference','Each solved case must have one reference.');
ref_source_id=foundation_pf.bus(source_ref,BUS_I);ref_model_id=regional_pf.bus(region_ref,BUS_I);
[found,refmap]=ismember(ref_source_id,bm.source_bus);
assert(found && exact(refmap) && bm.model_bus(refmap)==ref_model_id, ...
    'ny_response:Reference','Both cases must use the same mapped source reference.');

si=sbi(exact);ri=rbi(exact);source_id=bm.source_bus(exact);model_id=bm.model_bus(exact);
inventory=build.source_inventory.bus_inventory;
[found,k]=ismember(source_id,inventory.source_bus);assert(all(found));
sv=foundation_pf.bus(si,VM);rv=regional_pf.bus(ri,VM);
sa=foundation_pf.bus(si,VA);ra=regional_pf.bus(ri,VA);
sa_aligned=sa-foundation_pf.bus(source_ref,VA);ra_aligned=ra-regional_pf.bus(region_ref,VA);
dv=rv-sv;da=wrap_angle(ra_aligned-sa_aligned);
voltage=table(source_id,model_id,string(inventory.device_key(k)),foundation_pf.bus(si,BASE_KV), ...
    sv,rv,dv,sa,ra,sa_aligned,ra_aligned,da, ...
    'VariableNames',{'source_bus','model_bus','device_key','base_kv', ...
    'source_vm_pu','regional_vm_pu','delta_vm_pu','source_va_deg','regional_va_deg', ...
    'source_va_aligned_deg','regional_va_aligned_deg','delta_va_deg'});

sr=em.source_branch_row;rr=em.model_branch_row;
assert(all(sr==fix(sr)&sr>=1&sr<=size(foundation_pf.branch,1)) && ...
    all(rr==fix(rr)&rr>=1&rr<=size(regional_pf.branch,1)), ...
    'ny_response:BranchMap','Mapped branch rows are outside the supplied cases.');
sb=foundation_pf.branch(sr,1:13);rb=regional_pf.branch(rr,1:13);
[ff,fi]=ismember(sb(:,F_BUS),bm.source_bus);[tf,ti]=ismember(sb(:,T_BUS),bm.source_bus);
assert(all(ff&tf) && isequal(rb(:,[F_BUS T_BUS]),[bm.model_bus(fi) bm.model_bus(ti)]) && ...
    isequal(sb(:,3:13),rb(:,3:13)), ...
    'ny_response:BranchHardware','Copied branch endpoint orientation, electrical data or status differs.');
physical=build.source_inventory.branch_inventory;
[found,k]=ismember(sr,physical.source_branch_row);
assert(all(found) && isequal(string(em.device_key),string(physical.device_key(k))), ...
    'ny_response:BranchIdentity','Copied branch keys do not match the normalized source inventory.');
source_flow=terminal_values(foundation_pf);regional_flow=terminal_values(regional_pf);
assert(isequal(source_flow.from_kv(sr),regional_flow.from_kv(rr)) && ...
    isequal(source_flow.to_kv(sr),regional_flow.to_kv(rr)), ...
    'ny_response:VoltageBase','A copied crossing branch changed terminal voltage base.');
branch=table(sr,rr,string(em.device_key),sb(:,F_BUS),sb(:,T_BUS),rb(:,F_BUS),rb(:,T_BUS), ...
    sb(:,BR_STATUS)>0,string(physical.source_device_role(k)),string(physical.raw_circuit_id(k)), ...
    string(physical.identity_confidence(k)),logical(physical.individual_circuit_identity_resolved(k)), ...
    exact(fi)&exact(ti),xor(exact(fi),exact(ti)),source_flow.from_kv(sr),source_flow.to_kv(sr), ...
    'VariableNames',{'source_branch_row','model_branch_row','device_key','source_from_bus','source_to_bus', ...
    'model_from_bus','model_to_bus','online','source_device_role','raw_circuit_id','identity_confidence', ...
    'individual_circuit_identity_resolved','both_terminals_exact','crosses_aggregation_boundary','from_base_kv','to_base_kv'});
for name=["p_from_mw","q_from_mvar","p_to_mw","q_to_mvar","i_from_ka","i_to_ka"]
    branch.("source_"+name)=source_flow.(name)(sr);
    branch.("regional_"+name)=regional_flow.(name)(rr);
    branch.("delta_"+name)=regional_flow.(name)(rr)-source_flow.(name)(sr);
end
active=branch.online;
assert(any(active),'ny_response:NoActiveBranches','The copied branch comparison has no active records.');
dp=[branch.delta_p_from_mw(active);branch.delta_p_to_mw(active)];
dq=[branch.delta_q_from_mvar(active);branch.delta_q_to_mvar(active)];
di=[branch.delta_i_from_ka(active);branch.delta_i_to_ka(active)];
summary=table(height(voltage),height(branch),nnz(active),nnz(~active), ...
    nnz(active&branch.crosses_aggregation_boundary),nnz(~branch.individual_circuit_identity_resolved), ...
    root_mean_square(dv),max(abs(dv)),root_mean_square(da),max(abs(da)), ...
    root_mean_square(dp),max(abs(dp)),root_mean_square(dq),max(abs(dq)),root_mean_square(di),max(abs(di)), ...
    ref_source_id,ref_model_id, ...
    'VariableNames',{'exact_bus_count','copied_branch_count','active_copied_branch_count','inactive_copied_branch_count', ...
    'active_crossing_branch_count','branches_with_unresolved_individual_identity', ...
    'voltage_rmse_pu','voltage_max_abs_delta_pu','angle_rmse_deg','angle_max_abs_delta_deg', ...
    'terminal_p_rmse_mw','terminal_p_max_abs_delta_mw','terminal_q_rmse_mvar','terminal_q_max_abs_delta_mvar', ...
    'terminal_current_rmse_ka','terminal_current_max_abs_delta_ka','source_reference_bus','model_reference_bus'});
out=struct('exact_bus_voltage_comparison',voltage,'source_branch_comparison',branch,'summary',summary, ...
    'comparison_scope',"separate_historical_operating_states_at_corresponding_source_elements", ...
    'delta_convention',"regional_minus_foundation", ...
    'terminal_power_convention',"positive_from_each_terminal_bus_into_the_branch", ...
    'angle_policy',"each_state_relative_to_the_same_mapped_source_reference_then_wrapped_delta", ...
    'current_policy',"RMS_terminal_current_magnitude_from_own_Ybranch_V_and_terminal_base_kV", ...
    'summary_policy',"all_exact_buses_and_both_terminals_of_active_copied_branches_offline_rows_retained", ...
    'stored_terminal_flows_used',false,'qualification_assessed',false,'response_equivalence_assessed',false, ...
    'contemporary_validation_coverage',"none",'dlr_ready',false);
end

function validate_case(m)
assert(isstruct(m)&&isfield(m,'success')&&isequal(logical(m.success),true) && ...
    all(isfield(m,{'baseMVA','bus','branch'})) && size(m.bus,2)>=13&&size(m.branch,2)>=13, ...
    'ny_response:Unsolved','Supply both solved AC operating results.');
assert(isfinite(m.baseMVA)&&m.baseMVA>0&&numel(unique(m.bus(:,1)))==size(m.bus,1) && ...
    all(isfinite(m.bus(:,[8 9 10])),'all')&&all(m.bus(:,8)>0)&all(m.bus(:,10)>0), ...
    'ny_response:InvalidState','Bus IDs, phasors and voltage bases must be valid.');
end

function t=terminal_values(m)
% Reindex only local copies to preserve every external row and offline branch.
[found,f]=ismember(m.branch(:,1),m.bus(:,1));[target,to]=ismember(m.branch(:,2),m.bus(:,1));
assert(all(found&target),'ny_response:BranchEndpoint','Branch endpoint absent from case.');
b=m.bus;b(:,1)=(1:size(b,1))';br=m.branch(:,1:13);br(:,1:2)=[f to];
[~,Yf,Yt]=makeYbus(m.baseMVA,b,br);
v=m.bus(:,8).*exp(1i*m.bus(:,9)*pi/180);ifrom=Yf*v;ito=Yt*v;
sf=m.baseMVA*v(f).*conj(ifrom);st=m.baseMVA*v(to).*conj(ito);
fromkv=m.bus(f,10);tokv=m.bus(to,10);
t=struct('p_from_mw',real(sf),'q_from_mvar',imag(sf),'p_to_mw',real(st),'q_to_mvar',imag(st), ...
    'i_from_ka',abs(ifrom)*m.baseMVA./(sqrt(3)*fromkv), ...
    'i_to_ka',abs(ito)*m.baseMVA./(sqrt(3)*tokv),'from_kv',fromkv,'to_kv',tokv);
values=[real(sf) imag(sf) real(st) imag(st) t.i_from_ka t.i_to_ka];
assert(all(isfinite(values),'all'),'ny_response:NonfiniteFlow','Recomputed terminal quantities must be finite.');
end

function y=wrap_angle(x),y=mod(x+180,360)-180;end
function v=root_mean_square(x),v=sqrt(mean(x.^2));end
