function contract=compact_npcc_model_contract(candidate)
%COMPACT_NPCC_MODEL_CONTRACT Small NY-only benchmark with selected corridors.
% Independent of research_model_contract: no earlier historical contract or
% large regional reference changes meaning. A contract never qualifies PF.
% Optional candidate input checks the size/identity policy only.
contract=struct('schema_version',1,'model_role',"compact_NPCC_NY_electrical_testbed", ...
    'case_name',"npcc_ny_compact_dlr_testbed", ...
    'operating_network',"NY_only_with_fixed_boundary_PQ", ...
    'backbone_policy',"retain_original_NPCC_NY_backbone_with_selected_source_corridor_detail", ...
    'max_operating_bus_count',200,'planned_operating_bus_count',51, ...
    'planned_operating_branch_records',92,'planned_operating_active_branches',87, ...
    'planned_operating_generator_records',35,'original_NPCC_NY_bus_count',46, ...
    'planned_full_construction_bus_count',145,'planned_full_construction_branch_records',257, ...
    'planned_full_construction_active_branches',252, ...
    'power_base_mva',100,'power_scale',"NPCC_benchmark_MW", ...
    'gross_ny_benchmark_load_mw',10902.2198, ...
    'load_evidence_class',"assumed_inherited_NPCC_benchmark", ...
    'source_vintage',"NPCC_benchmark_with_selected_PERFORM_2019_corridors", ...
    'allow_automatic_PERFORM_regional_expansion',false, ...
    'allow_wholesale_PERFORM_operating_network_substitution',false, ...
    'allow_dense_Kron_network_as_operating_backbone',false, ...
    'preserve_original_NPCC_NY_buses',true,'preserve_historical_cases',true, ...
    'large_878_bus_candidate_role',"optional_historical_electrical_reference", ...
    'boundary_source',"matched_NPCC_benchmark_reference", ...
    'boundary_evidence_class',"reproduced_benchmark_snapshot_assumed_fixed_boundary", ...
    'boundary_control',"fixed_delivered_P_and_Q_at_NY_landings", ...
    'boundary_sign_convention',"positive_into_NY", ...
    'use_PERFORM_20_exchange_schedule_for_this_case',false, ...
    'allow_boundary_slack_or_voltage_control',false, ...
    'allow_synthetic_observations',false,'allow_assumed_research_baseline',true, ...
    'thermal_model_implemented',false,'electrical_baseline_qualified',false, ...
    'contemporary_validation_coverage',"not_claimed_benchmark",'dlr_ready',false, ...
    'physical_generator_capability_validated',false,'release_ready',false, ...
    'generator_capability_source',"inherited_S7_benchmark_including_existing_S4_changes", ...
    'structure_checked',false,'checked_operating_bus_count',NaN, ...
    'structure_check_scope',"bus_budget_and_original_bus_identity_only");
contract.original_NPCC_NY_bus_ids=(37:82)';
contract.construction_parent="S7_with_Phase0_rating_corrections";
contract.automatic_overlay_phases_excluded=["Phase1A_E_G";"Phase1C_downstate_mesh"];
contract.retained_parent_branch_rows=(1:246)';
contract.parent_branch_rows_deactivated=[88;89;94;235;236];
contract.selected_source_branch_rows=[1389;1390;1391;1392;1689;1690;1734;1735;1577;1576;1738];
contract.selected_corridor_groups=[repmat("Pleasant_Valley_EFishkill_Wood_Street_Millwood",8,1); ...
    repmat("Ramapo_Ladentown_Buchanan",3,1)];
contract.corridor_source_hash_lf_normalized= ...
    "f6ba2d787a4f22fcb7ae9f597cdd3111500d79921829a245d50e516c47e209ca";
contract.generator_classes=table(["original_NPCC_generation_aggregate";"S4_P_only_equivalent"], ...
    [21;14],["inherited_S7_aggregate_P_bounds_and_wide_Q_benchmark_envelope";"inherited_S7_active_power_equivalent_zero_Q"], ...
    ["assumed_benchmark_aggregate_not_verified_machine_capability";"assumed_active_power_equivalent_not_a_physical_unit"], ...
    false(2,1),'VariableNames',{'record_class','record_count','control_and_limit_interpretation', ...
    'evidence_scope','physical_machine_capability_verified'});
contract.generator_classes.inherited_S7_pmax_total_mw=[7992.895;9200];
contract.asset_classes=table(["source_AC_circuit_electrical_identity";"source_transformer"; ...
    "inherited_NPCC_nonthermal_equivalent";"fixed_boundary_PQ_record"],false(4,1), ...
    ["overhead_or_cable_realization_unverified";"transformer_not_an_overhead_conductor"; ...
     "aggregate_current_is_not_an_individual_conductor_current";"injection_record_is_not_a_thermal_branch"], ...
    'VariableNames',{'asset_class','thermal_eligible','thermal_exclusion_reason'});
contract.injection_accounting= ...
    "Keep gross benchmark load native/equivalent generation and boundary PQ separate; effective demand=gross demand-boundary injection exactly once";
contract.current_interpretation= ...
    "Recomputed model_branch_terminal_RMS_current_at_NPCC_benchmark_scale_not_verified_present_day_conductor_current";
contract.electrical_baseline_requirements=[ ...
    "At most 200 NY buses with all 46 original NPCC NY buses and only registered focused corridor changes"; ...
    "Matched benchmark load and boundary snapshot with each injection counted once"; ...
    "Explicit aggregate versus source-circuit roles and no unresolved double-counted active path"; ...
    "AC balance voltage ratings angle and declared benchmark P/Q envelopes audited including reference adjustment"; ...
    "Independent fixed-input replay without optimizer use or hidden load/capability changes"];
contract.qualification_rule= ...
    "Only independently audited operating artifacts can qualify the declared benchmark; this contract always returns unqualified";
contract.dlr_blockers=["Overhead/cable/conductor realization not validated"; ...
    "Resistance-temperature current/heating and weather model not implemented or verified"];
contract.reproduction_entry_point="run_compact_npcc_ny_testbed";
contract.replay_entry_point="replay_compact_npcc_ny_testbed";
contract.output_directory="output/compact_npcc_ny";

if nargin>0
    assert(isstruct(candidate)&&isfield(candidate,'bus')&&isnumeric(candidate.bus) && ...
        size(candidate.bus,2)>=1,'compact_npcc_model_contract:Candidate','A MATPOWER bus matrix is required.');
    ids=candidate.bus(:,1);count=numel(ids);
    assert(count<=contract.max_operating_bus_count,'compact_npcc_model_contract:BusLimit', ...
        'The compact operating case exceeds the hard 200-bus ceiling.');
    assert(all(isfinite(ids)&ids==fix(ids)&ids>0)&&numel(unique(ids))==count, ...
        'compact_npcc_model_contract:BusIdentity','Candidate bus IDs must be finite, positive, unique integers.');
    assert(all(ismember(contract.original_NPCC_NY_bus_ids,ids)), ...
        'compact_npcc_model_contract:OriginalNYBuses','All 46 original NPCC NY bus IDs must remain.');
    contract.structure_checked=true;contract.checked_operating_bus_count=count;
end
end
