function manifest=compact_dlr_code_manifest
%COMPACT_DLR_CODE_MANIFEST Executable and independent-fixture fingerprints.
root=fileparts(fileparts(fileparts(mfilename('fullpath'))));h="System Matpower Format/NY_Lite/";
names=["run_compact_ny_dlr_baseline.m";"replay_compact_ny_dlr_baseline.m"; ...
    "System Matpower Format/npcc_ny_2025_synthetic_dlr.m"; ...
    h+["compact_dlr_code_manifest.m";"compact_ny_dlr_research_contract.m";"compact_dlr_selection.m"; ...
    "dlr_conductor_library.m";"dlr_heat_balance.m";"dlr_steady_ampacity.m";"dlr_temperature_trace.m"; ...
    "build_dlr_corridor_realizations.m";"apply_dlr_temperature_resistance.m";"dlr_series_current_audit.m"; ...
    "dlr_series_constraint.m";"add_dlr_series_current_constraints.m";"solve_dlr_steady_operating_point.m"; ...
    "test_dlr_thermal_model.m";"test_dlr_electrical_consistency.m";"test_dlr_series_constraint.m"; ...
    "test_dlr_operating_guards.m";"fixtures/dlr_nrel_reference.csv";"fixtures/dlr_nrel_reference_manifest.json"]];
hashes=strings(numel(names),1);
for k=1:numel(names)
    bytes=unicode2native(strrep(fileread(fullfile(root,names(k))),sprintf('\r\n'),sprintf('\n')),'UTF-8');
    digest=java.security.MessageDigest.getInstance('SHA-256');digest.update(uint8(bytes));
    hashes(k)=lower(string(reshape(dec2hex(typecast(digest.digest(),'uint8'),2)',1,[])));
end
manifest=table(names,hashes,'VariableNames',{'relative_path','sha256_utf8_LF'});
end
