function c=compact_ny_dlr_research_contract
%COMPACT_NY_DLR_RESEARCH_CONTRACT Scope, never a substitute for artifact audits.
c=struct('model_family',"NPCC_derived_New_York_only",'infrastructure_cutoff',"2025-12-31", ...
    'maximum_operating_buses',200,'nominal_operating_buses',66,'original_NPCC_NY_bus_ids',(37:82)', ...
    'power_scale',"fixed_per_vintage_selected_summer_peak_equals10902.2197987MW", ...
    'boundaries',"ten_fixed_scheduled_P_channels_assumed_landings_and_zero_Q", ...
    'topology_policy',"explicit_replacements_and_assumed_station_corridors_no_wholesale_PERFORM_replacement", ...
    'generation_policy',"identified_scaled_events_within_unverified_regional_aggregates", ...
    'calibration',"four_2025_training_hours_seven_declared_interface_proxies", ...
    'heldout_prediction',"two_2025_hours_frozen_mean_training_dispatch_participation", ...
    'thermal_scope',"23_whitelisted_assumed_overhead_AC_corridors", ...
    'conductor_identity',"catalog_surrogates_not_verified_installed_conductors", ...
    'thermal_physics',"lumped_heat_balance_AC_resistance_temperature_dependence_exact_series_current", ...
    'excluded_thermal_assets',"cables_transformers_DC_boundaries_and_other_unrealized_equivalents", ...
    'weather_policy',"declared_synthetic_scenarios_not_observations", ...
    'exact_public_interface_operators',false,'observed_zonal_generation_validated',false, ...
    'as_built_network_validated',false,'dynamic_security_or_sag_clearance_validated',false, ...
    'qualification_requires_saved_AC_thermal_source_and_replay_audits',true);
end
