function c=compact_partial_spc_dlr_contract
%COMPACT_PARTIAL_SPC_DLR_CONTRACT Frozen synthetic conditions and claim scope.
weather=table(["static_reference";"windy_mild";"hot_low_wind";"cool_windy"], ...
    [40;25;40;5],[.61;2;.2;1],[90;90;0;90],[1000;800;1000;100],repmat(101325,4,1), ...
    false(4,1),'VariableNames',{'scenario_id','ambient_c','wind_m_s','wind_angle_deg','solar_w_m2','pressure_pa','observed_weather'});
c=struct('weather',weather,'electrical_variant_id',"nominal", ...
    'electrical_scenario_id',"S1_2025_SUMMER_PEAK_PUBLIC",'topology_as_of',"2025-12-31", ...
    'weather_observed',false,'physical_conductor_verified',false, ...
    'scope',"25_assumed_overhead_realizations_on_partial_SPC_year_end_topology", ...
    'temporal_scope',"earlier_2025_operating_inputs_are_counterfactual_stress_on_year_end_topology", ...
    'excluded',"retired_Smart_Path_cables_transformers_DC_boundaries_and_regional_equivalents", ...
    'historical_as_operated_validation',false,'fresh_holdout_validation',false, ...
    'dynamic_security_or_sag_clearance_validated',false);
end
