function t=compact_npcc_asset_register(build,assembly,result,audit)
%COMPACT_NPCC_ASSET_REGISTER Electrical terminal quantities for every NY row.
% Three-phase |S| and solved line-to-line voltage give RMS terminal amperes.
% These are model-terminal currents. Inherited equivalents are not physical
% conductors; source AC identity alone does not establish overhead/thermal data.
m=result;nb=size(m.bus,1);nr=size(m.branch,1);rows=(1:nr)';
assert(isfield(assembly,'branch_map')&&isfield(assembly,'candidate') ...
    && isfield(audit,'branch')&&all(isfield(build,{'branch_keys','physical_branch_register','full_candidate'})), ...
    'compact_asset:Schema','Construction, assembly and physical audit inputs are required.');
map=assembly.branch_map;ab=audit.branch;
assert(all(ismember({'model_branch_row','full_branch_row','branch_key'},map.Properties.VariableNames)) ...
    && all(ismember({'branch_row','device_key','from_bus','to_bus','online','from_mva','to_mva'},ab.Properties.VariableNames)), ...
    'compact_asset:Schema','Branch mapping or audit schema is incomplete.');
[found,mi]=ismember(rows,map.model_branch_row);[audited,ai]=ismember(rows,ab.branch_row);
assert(height(map)==nr&&height(ab)==nr&&all(found&audited) ...
    && numel(unique(map.model_branch_row))==nr&&numel(unique(ab.branch_row))==nr ...
    && numel(unique(map.full_branch_row))==nr, ...
    'compact_asset:RowIdentity','Each NY branch needs one unique full-case row and audited row.');
map=map(mi,:);ab=ab(ai,:);fr=map.full_branch_row;
assert(all(fr>=1&fr<=size(build.full_candidate.branch,1)&mod(fr,1)==0) ...
    && isequal(string(map.branch_key),string(build.branch_keys(fr))) ...
    && isequal(string(ab.device_key),string(map.branch_key)), ...
    'compact_asset:KeyIdentity','Stable branch keys differ between source construction, NY assembly and audit.');
assert(size(m.branch,2)>=13&&size(m.bus,2)>=13 ...
    && isscalar(m.baseMVA)&&isfinite(m.baseMVA)&&m.baseMVA>0 ...
    && isequal(m.baseMVA,assembly.candidate.baseMVA) ...
    && isequal(m.baseMVA,build.full_candidate.baseMVA) ...
    && isequal(m.branch(:,1:13),assembly.candidate.branch(:,1:13)) ...
    && isequal(m.branch(:,1:13),build.full_candidate.branch(fr,1:13)) ...
    && isequal(m.bus(:,[1 10]),assembly.candidate.bus(:,[1 10])), ...
    'compact_asset:FrozenHardware','Result branch parameters or bus voltage bases differ from the frozen construction.');
[ff,fi]=ismember(m.branch(:,1),m.bus(:,1));[tf,ti]=ismember(m.branch(:,2),m.bus(:,1));
on=m.branch(:,11)>0;
assert(numel(unique(m.bus(:,1)))==nb&&all(ff&tf) ...
    && isequal(ab.from_bus,m.branch(:,1))&&isequal(ab.to_bus,m.branch(:,2)) ...
    && isequal(logical(ab.online),on), ...
    'compact_asset:AuditIdentity','Audited endpoint/status identities do not match the solved NY case.');
sf=ab.from_mva;st=ab.to_mva;
assert(all(isfinite([sf;st]))&&all([sf;st]>=0)&&all(sf(~on)==0&st(~on)==0), ...
    'compact_asset:AuditPower','Audited apparent powers must be finite, nonnegative and zero offline.');
vf=m.bus(fi,8);vt=m.bus(ti,8);kf=m.bus(fi,10);kt=m.bus(ti,10);
assert(all(isfinite([vf(on);vt(on);kf(on);kt(on)])) ...
    && all([vf(on);vt(on);kf(on);kt(on)]>0), ...
    'compact_asset:Voltage','Active branch currents require positive solved voltage magnitudes and base kV.');
from_kv=vf.*kf;to_kv=vt.*kt;
from_amp=zeros(nr,1);to_amp=zeros(nr,1);
from_amp(on)=sf(on)*1000./(sqrt(3)*from_kv(on));
to_amp(on)=st(on)*1000./(sqrt(3)*to_kv(on));

physical=build.physical_branch_register;
assert(all(ismember({'model_branch_row','source_branch_row','device_key','source_device_role', ...
    'source_from_bus','source_to_bus'},physical.Properties.VariableNames)) ...
    && numel(unique(physical.model_branch_row))==height(physical), ...
    'compact_asset:SourceIdentity','Physical source row register is incomplete or duplicated.');
[source,si]=ismember(fr,physical.model_branch_row);
source_rows=nan(nr,1);source_from=source_rows;source_to=source_rows;
source_keys=repmat("",nr,1);source_kind=source_keys;
source_rows(source)=physical.source_branch_row(si(source));
source_from(source)=physical.source_from_bus(si(source));source_to(source)=physical.source_to_bus(si(source));
source_keys(source)=string(physical.device_key(si(source)));
source_kind(source)=string(physical.source_device_role(si(source)));
assert(all(source_keys(source)==string(map.branch_key(source))), ...
    'compact_asset:SourceIdentity','Source circuit keys do not match the assembled branch keys.');
role=repmat("inherited_NPCC_or_S7_equivalent",nr,1);
transformer=m.branch(:,9)~=0|m.branch(:,10)~=0|abs(kf-kt)>1e-9;
role(~source&transformer)="inherited_transformer_or_machine_connection_equivalent";
role(source)="source_AC_branch_electrical_copy";
role(source&source_kind=="two_winding_transformer")="source_transformer_electrical_copy";
interpretation=repmat("equivalent_terminal_RMS_current_not_a_physical_conductor_current",nr,1);
interpretation(source)="source_branch_terminal_RMS_current_equipment_and_conductor_interpretation_unverified";
interpretation(source&source_kind=="two_winding_transformer")= ...
    "source_transformer_terminal_RMS_current_not_overhead_line_ampacity";
qualified=isfield(audit,'passed')&&isequal(audit.passed,true) ...
    && isfield(m,'success')&&isscalar(m.success)&&m.success==1;
t=table(rows,fr,string(map.branch_key),source_rows,source_keys,source_from,source_to, ...
    m.branch(:,1),m.branch(:,2),role,source_kind,m.branch(:,3),m.branch(:,4),m.branch(:,5), ...
    m.branch(:,9),m.branch(:,10),m.branch(:,11),on,repmat(m.baseMVA,nr,1), ...
    kf,kt,vf,vt,from_kv,to_kv,m.branch(:,6),m.branch(:,7),m.branch(:,8), ...
    sf,st,from_amp,to_amp,repmat(qualified,nr,1),false(nr,1),false(nr,1),interpretation, ...
    'VariableNames',{'ny_branch_row','full_branch_row','branch_key','source_branch_row', ...
    'source_device_key','source_from_bus','source_to_bus','from_bus','to_bus','electrical_role', ...
    'source_device_role','r_pu','x_pu','b_pu','tap','shift_degree','status','online','base_mva', ...
    'from_base_kv','to_base_kv','from_vm_pu','to_vm_pu','from_solved_line_line_kv','to_solved_line_line_kv', ...
    'rate_a_mva','rate_b_mva','rate_c_mva','from_apparent_power_mva','to_apparent_power_mva', ...
    'from_terminal_rms_amp','to_terminal_rms_amp','power_flow_audit_passed', ...
    'thermal_eligible','dlr_eligible','current_interpretation'});
t.rate_a_applies_both_terminals=t.rate_a_mva>0;
t.from_loading_percent=nan(nr,1);t.to_loading_percent=nan(nr,1);
rated=t.rate_a_mva>0;t.from_loading_percent(rated)=100*sf(rated)./t.rate_a_mva(rated);
t.to_loading_percent(rated)=100*st(rated)./t.rate_a_mva(rated);
t.current_formula=repmat("I_RMS_A=abs(S_3phase_MVA)*1000/(sqrt(3)*VM_pu*base_kV)",nr,1);
t.rating_interpretation=repmat("static_MATPOWER_MVA_limit_at_each_terminal_not_verified_conductor_ampacity",nr,1);
end
