function inventory = contemporary_generator_inventory(mpc, source_case)
%CONTEMPORARY_GENERATOR_INVENTORY Account for inherited rows without redating.
% Blank contemporary capabilities intentionally block release; a bus name is
% not a unit identity and inherited equivalent capacity is not a 2026 rating.
if nargin < 2, source_case = "npcc_ny_lite_s13_npcc_augmented_2019"; end
n = size(mpc.gen,1); row = (1:n)';
inventory = table("inherited_gen_"+compose('%03d',row),row,mpc.gen(:,1), ...
    mpc.gen(:,8),mpc.gen(:,10),mpc.gen(:,9),mpc.gen(:,5),mpc.gen(:,4), ...
    repmat(string(source_case),n,1),repmat("historical_inherited",n,1), ...
    repmat("unmapped",n,1),repmat("unverified",n,1),nan(n,1),nan(n,1),nan(n,1),nan(n,1), ...
    repmat("2026-09-06",n,1),false(n,1), ...
    'VariableNames',{'accounting_id','source_gen_row','bus_id','inherited_status', ...
    'inherited_pmin_mw','inherited_pmax_mw','inherited_qmin_mvar','inherited_qmax_mvar', ...
    'source_case','parameter_provenance','contemporary_unit_id','contemporary_status', ...
    'contemporary_pmin_mw','contemporary_pmax_mw','contemporary_qmin_mvar','contemporary_qmax_mvar', ...
    'review_cutoff','release_eligible'});
end
