function out=extract_compact_ny_boundary(full,build,options)
%EXTRACT_COMPACT_NY_BOUNDARY NY-only NPCC benchmark with fixed tie-terminal PQ.
% The removed tie's solved power entering its NY terminal replaces that tie
% exactly at this operating point. It is not a contemporary interchange
% observation or an equivalent of external voltage/contingency response.
if nargin<3,options=struct();end
if ~isfield(options,'reference_bus'),options.reference_bus=42;end
define_constants;p=build.full_candidate;
assert(~any(isfield(full,{'userfcn','A','dcline'})), ...
    'compact_ny:CustomInputs','Custom constraints or DC devices require explicit accounting.');
assert(isequal(full.baseMVA,p.baseMVA)&& ...
    isequal(full.bus(:,[BUS_I PD QD GS BS BASE_KV VMIN VMAX]),p.bus(:,[BUS_I PD QD GS BS BASE_KV VMIN VMAX]))&& ...
    isequal(full.branch(:,1:13),p.branch(:,1:13))&& ...
    isequal(full.gen(:,[GEN_BUS GEN_STATUS PMIN PMAX QMIN QMAX]),p.gen(:,[GEN_BUS GEN_STATUS PMIN PMAX QMIN QMAX])), ...
    'compact_ny:FrozenFullHardware','Full reference must preserve declared benchmark hardware and injections.');
fa=audit_ny_ac_reference(full,struct('generator_keys',build.generator_keys,'branch_keys',build.branch_keys));
assert(fa.passed,'compact_ny:FullReference','A bounded and physically audited reference is required for these fixed boundary schedules.');
ny=logical(build.ny_bus_mask(:));ids=full.bus(ny,BUS_I);nb=nnz(ny);
assert(nb>0&&nb<=200&&numel(ny)==size(full.bus,1)&&isequal(ids,build.ny_bus_ids), ...
    'compact_ny:BusBudget','NY membership must be explicit and within the 200-bus cap.');
fny=ismember(full.branch(:,F_BUS),ids);tny=ismember(full.branch(:,T_BUS),ids);
inside=find(fny&tny);cut=find(xor(fny,tny));isfrom=fny(cut);
nybus=full.branch(cut,F_BUS);other=full.branch(cut,T_BUS);
nybus(~isfrom)=full.branch(cut(~isfrom),T_BUS);other(~isfrom)=full.branch(cut(~isfrom),F_BUS);
sp=full.branch(cut,PF);sq=full.branch(cut,QF);
sp(~isfrom)=full.branch(cut(~isfrom),PT);sq(~isfrom)=full.branch(cut(~isfrom),QT);
online=full.branch(cut,BR_STATUS)>0;sp(~online)=0;sq(~online)=0;
[found,li]=ismember(nybus,ids);assert(all(found));
bp=accumarray(li,-sp,[nb,1]);bq=accumarray(li,-sq,[nb,1]);
z=string(full.userdata.nyiso_physical_zone(:));[~,ny_full_row]=ismember(nybus,full.bus(:,BUS_I));
boundary=table("NPCC_BENCHMARK:BOUNDARY:"+string(cut),cut,nybus,other,isfrom,online,-sp,-sq,z(ny_full_row), ...
    repmat("fixed_matched_NY_terminal_PQ_positive_into_NY",numel(cut),1), ...
    repmat("assumed_NPCC_benchmark_reference_not_observed_interchange",numel(cut),1), ...
    'VariableNames',{'boundary_key','full_branch_row','ny_bus','neighbor_bus','ny_is_from_terminal','online', ...
    'p_injection_mw','q_injection_mvar','ny_zone','sign_and_model_policy','input_provenance'});
keepgen=ismember(full.gen(:,GEN_BUS),ids);gr=find(keepgen);
m=struct('version','2','baseMVA',full.baseMVA,'bus',full.bus(ny,1:13), ...
    'gen',full.gen(keepgen,1:21),'branch',full.branch(inside,1:13));
m.bus(:,PD)=m.bus(:,PD)-bp;m.bus(:,QD)=m.bus(:,QD)-bq;
assert(size(full.gencost,1)==size(full.gen,1),'compact_ny:Cost','Expected one active-power objective per full generator record.');
m.gencost=full.gencost(keepgen,:);m.bus_name=full.bus_name(ny);
reference=options.reference_bus;
assert(any(m.gen(:,GEN_BUS)==reference&m.gen(:,GEN_STATUS)>0&m.gen(:,PMAX)>m.gen(:,PMIN))&& ...
    any(gr<=48&m.gen(:,GEN_BUS)==reference), ...
    'compact_ny:Reference','Reference must be an online inherited NPCC NY aggregate with active range.');
m.bus(m.bus(:,BUS_TYPE)==REF,BUS_TYPE)=PV;
ref=find(m.bus(:,BUS_I)==reference);assert(isscalar(ref));m.bus(ref,BUS_TYPE)=REF;
m.bus(:,VA)=m.bus(:,VA)-m.bus(ref,VA);
m.userdata=struct('nyiso_physical_zone',{cellstr(z(ny))},'compact_npcc',struct( ...
    'model_role','preferred_compact_NPCC_NY_benchmark','max_operating_bus_count',200, ...
    'power_scale','NPCC_benchmark','footprint','NY_only_fixed_boundary_PQ', ...
    'reference_bus',reference,'electrical_baseline_qualified',false, ...
    'contemporary_validation_coverage','not_evaluated','dlr_ready',false));
ledger=table(ids,z(ny),full.bus(ny,PD),full.bus(ny,QD),bp,bq,m.bus(:,PD),m.bus(:,QD),m.bus(:,GS),m.bus(:,BS), ...
    'VariableNames',{'model_bus','zone','pd_gross_mw','qd_gross_mvar','p_boundary_mw','q_boundary_mvar', ...
    'pd_effective_mw','qd_effective_mvar','gs_mw','bs_mvar'});
role=repmat("S4_added_active_capacity_equivalent",numel(gr),1);role(gr<=48)="original_NPCC_aggregate_generator";
gm=table((1:numel(gr))',gr,string(build.generator_keys(gr)),m.gen(:,GEN_BUS),role, ...
    m.gen(:,GEN_STATUS)>0,m.gen(:,PG),m.gen(:,QG),m.gen(:,PMIN),m.gen(:,PMAX),m.gen(:,QMIN),m.gen(:,QMAX), ...
    repmat("inherited_benchmark_envelope_not_verified_plant_capability",numel(gr),1), ...
    'VariableNames',{'model_gen_row','full_gen_row','generator_key','model_bus','record_role','online', ...
    'pg_prior_mw','qg_prior_mvar','pmin_mw','pmax_mw','qmin_mvar','qmax_mvar','capability_provenance'});
branch_map=table((1:numel(inside))',inside,string(build.branch_keys(inside)), ...
    'VariableNames',{'model_branch_row','full_branch_row','branch_key'});
out=struct('candidate',m,'boundary_register',boundary,'bus_injection_ledger',ledger, ...
    'generator_register',gm,'branch_map',branch_map,'generator_keys',string(build.generator_keys(gr)), ...
    'branch_keys',string(build.branch_keys(inside)),'full_reference_audit',fa, ...
    'reference_bus',reference,'ny_bus_mask',ny,'full_gen_rows',gr,'full_branch_rows',inside, ...
    'boundary_response_equivalence_established',false,'electrical_baseline_qualified',false,'dlr_ready',false);
end
