function out=map_perform_injections_to_ny_candidate(candidate,n,foundation,options)
%MAP_PERFORM_INJECTIONS_TO_NY_CANDIDATE Replace all legacy injections once.
% Complete source-bus mapping controls every device family. Original PERFORM
% native record identities are retained; aggregate locations are assumptions.
% Foundation is the saved Package A artifact (mpc, generator_keys and gross
% boundary ledger). No optimization or new boundary schedule is introduced.
if nargin<4,options=struct();end
define_constants;
assert(isfield(options,'source_bus_map'),'ny_injection_map:MissingMap','Complete source_bus_map required.');
assert(~isfield(candidate,'userdata') || ~isfield(candidate.userdata,'ny_source_injection_mapping'), ...
    'ny_injection_map:AlreadyApplied','Legacy injection replacement was already applied.');
map=options.source_bus_map;required={'source_bus','model_bus','mapping_kind'};
assert(istable(map)&&all(ismember(required,map.Properties.VariableNames)), ...
    'ny_injection_map:MapSchema','Mapping needs source_bus, model_bus and mapping_kind.');
src=n.source;ref=foundation.mpc;keys=string(foundation.generator_keys(:));
assert(candidate.baseMVA==src.baseMVA && ref.baseMVA==src.baseMVA, ...
    'ny_injection_map:Base','Base-MVA changes require an explicit separate conversion.');
assert(height(map)==size(src.bus,1)&&numel(unique(map.source_bus))==height(map), ...
    'ny_injection_map:MapCoverage','Each canonical source bus must occur exactly once.');
[found,j]=ismember(src.bus(:,BUS_I),map.source_bus);assert(all(found),'ny_injection_map:MapCoverage','Source bus missing.');
map=map(j,:);[found,mi]=ismember(map.model_bus,candidate.bus(:,BUS_I));
assert(all(found)&&all(isfinite(map.model_bus))&&all(strlength(string(map.mapping_kind))>0), ...
    'ny_injection_map:MapTarget','Every source bus needs a declared existing model target.');
assert(numel(unique(candidate.bus(:,BUS_I)))==size(candidate.bus,1), ...
    'ny_injection_map:DuplicateModelBus','Model bus IDs must be unique.');
sz=string(n.bus_inventory.source_zone);
if isfield(options,'model_bus_zones'),mz=string(options.model_bus_zones(:));
elseif isfield(candidate,'userdata')&&isfield(candidate.userdata,'nyiso_physical_zone')
    mz=string(candidate.userdata.nyiso_physical_zone(:));
else,error('ny_injection_map:MissingZones','Explicit candidate NY bus zones are required.');end
assert(numel(mz)==size(candidate.bus,1)&&all(ismember(mz,string(('A':'K')'))) && all(mz(mi)==sz), ...
    'ny_injection_map:Zone','Source injections must remain within their declared NY zones.');

% Audit complete Package A gross and effective load snapshots before use.
ledger=foundation.gross_boundary_ledger;
assert(height(ledger)==size(src.bus,1)&&numel(unique(ledger.source_bus))==height(ledger), ...
    'ny_injection_map:FoundationLedger','Foundation bus ledger is incomplete or duplicated.');
[found,j]=ismember(src.bus(:,BUS_I),ledger.source_bus);assert(all(found));ledger=ledger(j,:);
assert(max(abs(ledger.pd_gross_mw-src.bus(:,PD)))<1e-8 && ...
    max(abs(ledger.qd_gross_mvar-src.bus(:,QD)))<1e-8 && ...
    max(abs(ledger.pd_effective_mw-(ledger.pd_gross_mw-ledger.p_boundary_mw)))<1e-8 && ...
    max(abs(ledger.qd_effective_mvar-(ledger.qd_gross_mvar-ledger.q_boundary_mvar)))<1e-8, ...
    'ny_injection_map:FoundationLedger','Foundation gross/effective accounting changed.');
[found,rbi]=ismember(src.bus(:,BUS_I),ref.bus(:,BUS_I));assert(all(found));
assert(isequal(ref.bus(rbi,[PD QD GS BS]),[ledger.pd_effective_mw ledger.qd_effective_mvar src.bus(:,[GS BS])]), ...
    'ny_injection_map:FoundationLedger','Foundation MATPOWER injections disagree with its ledger.');
native=n.generator_inventory(n.generator_inventory.native_generation_member,:);
[found,ri]=ismember(native.device_key,keys);
assert(all(found)&&numel(unique(keys))==numel(keys)&&numel(keys)==size(ref.gen,1), ...
    'ny_injection_map:FoundationIdentity','Foundation generator identities are invalid.');
assert(isequal(ref.gen(ri,GEN_BUS),native.source_bus) && ...
    isequal(ref.gen(ri,[PMIN PMAX QMIN QMAX GEN_STATUS]),src.gen(native.source_gen_row,[PMIN PMAX QMIN QMAX GEN_STATUS])), ...
    'ny_injection_map:NativeBounds','Native source identity/status/capability changed in foundation.');
support_key="RESEARCH2019:Q_SUPPORT:1263:MARCY";sr=find(keys==support_key);
assert(numel(sr)==1&&numel(keys)==height(native)+1&&ref.gen(sr,GEN_BUS)==1263 && ...
    isequal(ref.gen(sr,[PMIN PMAX QMIN QMAX GEN_STATUS]),[0 0 -900 900 1]), ...
    'ny_injection_map:Support','Only the separately declared Package A Q support may accompany native records.');
order=[ri;sr];device_keys=[native.device_key;support_key];ng=numel(order);
source_gen_bus=ref.gen(order,GEN_BUS);[found,gi]=ismember(source_gen_bus,src.bus(:,BUS_I));assert(all(found));

% Old candidate load, shunt and generator entries have no additive role.
m=candidate;oldbus=m.bus(:,[BUS_I PD QD GS BS]);oldgen=m.gen;
nb=size(m.bus,1);A=sparse(mi,(1:height(map))',1,nb,height(map));
pd=A*ledger.pd_gross_mw;qd=A*ledger.qd_gross_mvar;
pb=A*ledger.p_boundary_mw;qb=A*ledger.q_boundary_mvar;
m.bus(:,[PD QD GS BS])=[pd-pb qd-qb A*src.bus(:,GS) A*src.bus(:,BS)];
m.bus(:,BUS_TYPE)=PQ;
m.gen=ref.gen(order,1:21);m.gen(:,GEN_BUS)=map.model_bus(gi);
m.gen_name=device_keys;m.genfuel=[native.source_gen_fuel;"assumed_research_Q_support"];
m.gentype=[native.source_gen_type;"assumed_research_Q_support"];
m.gencost=[2*ones(ng,1),zeros(ng,2),2*ones(ng,1),zeros(ng,2)];
m=rmfield(m,intersect(fieldnames(m),{'order','success','et','iterations'}));

% A common proxy terminal has one voltage target. Source Q-range weights
% define a prior only; the bounded operating solve may subsequently move it.
original_vg=m.gen(:,VG);common_vg=original_vg;
on=m.gen(:,GEN_STATUS)>0;
for bus=unique(m.gen(on,GEN_BUS))'
    gr=find(on&m.gen(:,GEN_BUS)==bus);br=find(m.bus(:,BUS_I)==bus);
    w=max(m.gen(gr,QMAX)-m.gen(gr,QMIN),0);if sum(w)==0,w=ones(size(w));end
    vg=sum(w.*original_vg(gr))/sum(w);vg=min(max(vg,m.bus(br,VMIN)),m.bus(br,VMAX));
    m.gen(gr,VG)=vg;common_vg(gr)=vg;m.bus(br,VM)=vg;m.bus(br,BUS_TYPE)=PV;
end
source_ref=ref.bus(ref.bus(:,BUS_TYPE)==REF,BUS_I);
assert(numel(source_ref)==1,'ny_injection_map:Reference','One source foundation reference is required.');
[~,refi]=ismember(source_ref,src.bus(:,BUS_I));reference_bus=map.model_bus(refi);
if isfield(options,'reference_bus'),reference_bus=options.reference_bus;end
assert(nnz(m.bus(:,BUS_I)==reference_bus)==1 && any(on&m.gen(:,GEN_BUS)==reference_bus & m.gen(:,PMAX)>m.gen(:,PMIN)), ...
    'ny_injection_map:Reference','The reference must have native active-power balancing capability.');
m.bus(m.bus(:,BUS_I)==reference_bus,BUS_TYPE)=REF;

source_load=table(n.bus_inventory.device_key,src.bus(:,BUS_I),map.model_bus,sz,string(map.mapping_kind), ...
    ledger.pd_gross_mw,ledger.qd_gross_mvar,src.bus(:,GS),src.bus(:,BS), ...
    'VariableNames',{'device_key','source_bus','model_bus','zone','mapping_kind','pd_gross_mw','qd_gross_mvar','gs_mw','bs_mvar'});
generator_map=table((1:ng)',device_keys,[native.source_gen_row;NaN],source_gen_bus,m.gen(:,GEN_BUS), ...
    [native.source_device_role;"assumed_reactive_support"],sz(gi),string(map.mapping_kind(gi)), ...
    m.gen(:,GEN_STATUS),m.gen(:,PG),m.gen(:,QG),m.gen(:,PMIN),m.gen(:,PMAX),m.gen(:,QMIN),m.gen(:,QMAX), ...
    'VariableNames',{'model_gen_row','device_key','source_gen_row','source_bus','model_bus','source_device_role', ...
    'zone','mapping_kind','status','prior_pg_mw','prior_qg_mvar','pmin_mw','pmax_mw','qmin_mvar','qmax_mvar'});
control_map=table(device_keys,source_gen_bus,m.gen(:,GEN_BUS),m.gen(:,GEN_STATUS),original_vg,common_vg, ...
    repmat("local_PV_common_terminal_Q_span_weighted_reference_prior",ng,1), ...
    'VariableNames',{'device_key','source_bus','model_bus','status','source_reference_vg_pu','mapped_vg_pu','policy'});
control_map.raw_remote_control_omitted=[native.raw_remote_control_omitted;false];

boundary=n.boundary_reconciliation(n.boundary_reconciliation.boundary_member,:);
assert(height(boundary)==20&&numel(unique(boundary.source_bus))==20, ...
    'ny_injection_map:Boundary','The frozen 20 distinct-bus boundary records are required.');
[found,bi]=ismember(boundary.source_bus,src.bus(:,BUS_I));assert(all(found));
outside=true(size(src.bus,1),1);outside(bi)=false;
assert(all(ledger.p_boundary_mw(outside)==0)&all(ledger.q_boundary_mvar(outside)==0), ...
    'ny_injection_map:Boundary','Unregistered fixed boundary injection found.');
boundary.model_bus=map.model_bus(bi);boundary.mapping_kind=string(map.mapping_kind(bi));
boundary.p_injection_mw=ledger.p_boundary_mw(bi);boundary.q_injection_mvar=ledger.q_boundary_mvar(bi);
boundary.provenance=repmat("frozen_Package_A_reproduced_source_boundary_PQ_assumed_schedule",height(boundary),1);
assert(all(boundary.p_injection_mw(boundary.canonical_status<=0)==0) && ...
    all(boundary.q_injection_mvar(boundary.canonical_status<=0)==0), ...
    'ny_injection_map:InactiveBoundary','Inactive boundary records cannot inject.');
shunt=n.shunt_inventory;[~,sh]=ismember(shunt.source_bus,src.bus(:,BUS_I));
shunt.model_bus=map.model_bus(sh);shunt.mapping_kind=string(map.mapping_kind(sh));
shunt.model_representation=repmat("canonical_BS_once_no_QS_generator",height(shunt),1);
model_ledger=table(m.bus(:,BUS_I),mz,pd,qd,pb,qb,m.bus(:,PD),m.bus(:,QD),m.bus(:,GS),m.bus(:,BS), ...
    'VariableNames',{'model_bus','zone','pd_gross_mw','qd_gross_mvar','p_boundary_mw','q_boundary_mvar', ...
    'pd_effective_mw','qd_effective_mvar','gs_mw','bs_mvar'});
legacy_bus=array2table(oldbus,'VariableNames',{'model_bus','removed_pd_mw','removed_qd_mvar','removed_gs_mw','removed_bs_mvar'});
legacy_gen=table((1:size(oldgen,1))',oldgen(:,GEN_BUS),oldgen(:,PG),oldgen(:,QG),oldgen(:,GEN_STATUS), ...
    repmat("retired_legacy_candidate_injection_record",size(oldgen,1),1), ...
    'VariableNames',{'legacy_gen_row','legacy_bus','legacy_pg_mw','legacy_qg_mvar','legacy_status','action'});
zone_accounting=table();
for zone=string(('A':'K')')'
    s=sz==zone;t=mz==zone;gn=generator_map.zone==zone & generator_map.source_device_role~="assumed_reactive_support";
    sg=n.generator_inventory.source_zone==zone & n.generator_inventory.native_generation_member;
    row=table(zone,sum(ledger.pd_gross_mw(s)),sum(pd(t)),sum(ledger.qd_gross_mvar(s)),sum(qd(t)), ...
        sum(ledger.p_boundary_mw(s)),sum(pb(t)),sum(ledger.q_boundary_mvar(s)),sum(qb(t)), ...
        sum(src.bus(s,BS)),sum(m.bus(t,BS)),nnz(sg),nnz(gn), ...
        'VariableNames',{'zone','source_pd_gross_mw','mapped_pd_gross_mw','source_qd_gross_mvar','mapped_qd_gross_mvar', ...
        'source_boundary_p_mw','mapped_boundary_p_mw','source_boundary_q_mvar','mapped_boundary_q_mvar', ...
        'source_bs_mvar','mapped_bs_mvar','source_native_records','mapped_native_records'});
    row.source_gs_mw=sum(src.bus(s,GS));row.mapped_gs_mw=sum(m.bus(t,GS));
    row.source_native_prior_p_mw=sum(ref.gen(order(gn),PG).*on(gn));
    row.mapped_native_prior_p_mw=sum(m.gen(gn,PG).*on(gn));
    row.source_native_prior_q_mvar=sum(ref.gen(order(gn),QG).*on(gn));
    row.mapped_native_prior_q_mvar=sum(m.gen(gn,QG).*on(gn));
    row.source_online_native_pmin_mw=sum(ref.gen(order(gn),PMIN).*on(gn));
    row.mapped_online_native_pmin_mw=sum(m.gen(gn,PMIN).*on(gn));
    row.source_online_native_pmax_mw=sum(ref.gen(order(gn),PMAX).*on(gn));
    row.mapped_online_native_pmax_mw=sum(m.gen(gn,PMAX).*on(gn));
    row.source_online_native_qmin_mvar=sum(ref.gen(order(gn),QMIN).*on(gn));
    row.mapped_online_native_qmin_mvar=sum(m.gen(gn,QMIN).*on(gn));
    row.source_online_native_qmax_mvar=sum(ref.gen(order(gn),QMAX).*on(gn));
    row.mapped_online_native_qmax_mvar=sum(m.gen(gn,QMAX).*on(gn));
    zone_accounting=[zone_accounting;row]; %#ok<AGROW>
end
delta=[zone_accounting.source_pd_gross_mw-zone_accounting.mapped_pd_gross_mw; ...
    zone_accounting.source_qd_gross_mvar-zone_accounting.mapped_qd_gross_mvar; ...
    zone_accounting.source_boundary_p_mw-zone_accounting.mapped_boundary_p_mw; ...
    zone_accounting.source_boundary_q_mvar-zone_accounting.mapped_boundary_q_mvar; ...
    zone_accounting.source_bs_mvar-zone_accounting.mapped_bs_mvar; ...
    zone_accounting.source_native_records-zone_accounting.mapped_native_records; ...
    zone_accounting.source_gs_mw-zone_accounting.mapped_gs_mw; ...
    zone_accounting.source_native_prior_p_mw-zone_accounting.mapped_native_prior_p_mw; ...
    zone_accounting.source_native_prior_q_mvar-zone_accounting.mapped_native_prior_q_mvar; ...
    zone_accounting.source_online_native_pmin_mw-zone_accounting.mapped_online_native_pmin_mw; ...
    zone_accounting.source_online_native_pmax_mw-zone_accounting.mapped_online_native_pmax_mw; ...
    zone_accounting.source_online_native_qmin_mvar-zone_accounting.mapped_online_native_qmin_mvar; ...
    zone_accounting.source_online_native_qmax_mvar-zone_accounting.mapped_online_native_qmax_mvar];
assert(max(abs(delta))<1e-8,'ny_injection_map:Conservation','Source-to-model zonal accounting failed.');
assert(isequal(m.branch,candidate.branch),'ny_injection_map:Topology','Injection mapping cannot change branches.');
m.userdata.ny_source_injection_mapping=struct('source_hash',n.canonical_sha256, ...
    'policy','complete_legacy_injection_replacement','power_scale','historical_actual_mw', ...
    'native_records',height(native),'external_boundary_records',height(boundary), ...
    'research_support_records',1,'electrical_baseline_qualified',false);
out=struct('candidate',m,'source_bus_map',map,'source_load_ledger',source_load, ...
    'generator_map',generator_map,'generator_keys',device_keys,'control_map',control_map, ...
    'boundary_register',boundary,'shunt_register',shunt,'model_bus_ledger',model_ledger, ...
    'retired_legacy_bus_injections',legacy_bus,'retired_legacy_generators',legacy_gen, ...
    'zone_accounting',zone_accounting,'conservation_error_max',max(abs(delta)), ...
    'Pg_prior_mw',m.gen(:,PG),'Pg_sigma_mw',max(50,.25*(m.gen(:,PMAX)-m.gen(:,PMIN))), ...
    'reference_bus',reference_bus,'source_hash',n.canonical_sha256, ...
    'power_scale','historical_actual_mw','mapping_only',true,'electrical_baseline_qualified',false, ...
    'contemporary_validation_coverage','none','dlr_ready',false);
end
