function defs = ny_lite_interface_definitions(mpc, options)
%NY_LITE_INTERFACE_DEFINITIONS Load explicit S11 or legacy zone-cut operators.

if nargin < 1 || isempty(mpc), mpc = npcc_ny_lite_v2_topology; end
if nargin < 2, options = struct(); end
helper_dir = fileparts(mfilename('fullpath'));
if ~isfield(options, 'map_file')
    options.map_file = fullfile(helper_dir, 'nyiso_interface_branch_map.csv');
end
if ~isfield(options, 'force_legacy'), options.force_legacy = false; end

use_explicit = ~options.force_legacy && is_s11_case(mpc) && ...
    exist(options.map_file, 'file') == 2;
if use_explicit
    defs = explicit_definitions(mpc, options.map_file);
else
    defs = legacy_definitions(mpc);
end
end

function tf = is_s11_case(mpc)
tf = isfield(mpc, 'userdata') && isfield(mpc.userdata, 's11');
if ~tf
    tf = size(mpc.bus, 1) == 49 && size(mpc.branch, 1) == 83;
end
end

function defs = explicit_definitions(mpc, map_file)
define_constants;
tbl = readtable(map_file, 'TextType', 'string', ...
    'VariableNamingRule', 'preserve');
required = {'interface_name','source_monitored_circuit','circuit_id', ...
    'metered_end','sign','reduced_from_bus','reduced_to_bus', ...
    'reduced_branch_index','reduced_branch_or_cutset','effective_date', ...
    'mapping_confidence','calibration_eligible','aggregate_name', ...
    'zone_boundary','positive_direction','target_source'};
if ~all(ismember(required, tbl.Properties.VariableNames))
    error('ny_lite_interface_definitions:MapSchema', ...
        'Explicit interface map is missing required columns.');
end
defs = struct([]);
for k = 1:height(tbl)
    b = double(tbl.reduced_branch_index(k));
    if ~isfinite(b) || b < 1 || b > size(mpc.branch, 1) || ...
            mpc.branch(b, F_BUS) ~= double(tbl.reduced_from_bus(k)) || ...
            mpc.branch(b, T_BUS) ~= double(tbl.reduced_to_bus(k))
        error('ny_lite_interface_definitions:StaleOperator', ...
            'Explicit interface row %d does not resolve to its recorded branch.', k);
    end
    mend = lower(string(tbl.metered_end(k)));
    if mend == "from"
        metered = mpc.branch(b, F_BUS); flow_column = 'PF';
    elseif mend == "to"
        metered = mpc.branch(b, T_BUS); flow_column = 'PT';
    else
        error('ny_lite_interface_definitions:MeteredEnd', ...
            'Unknown metered_end %s in row %d.', mend, k);
    end
    fi = find(mpc.bus(:, BUS_I) == mpc.branch(b, F_BUS), 1);
    ti = find(mpc.bus(:, BUS_I) == mpc.branch(b, T_BUS), 1);
    rec = struct('interface_name', char(tbl.interface_name(k)), ...
        'aggregate_name', char(tbl.aggregate_name(k)), ...
        'zone_boundary', char(tbl.zone_boundary(k)), ...
        'positive_direction', char(tbl.positive_direction(k)), ...
        'branch_index', b, 'branch_from', mpc.branch(b, F_BUS), ...
        'branch_to', mpc.branch(b, T_BUS), ...
        'branch_from_name', bus_name(mpc, fi), ...
        'branch_to_name', bus_name(mpc, ti), 'metered_bus', metered, ...
        'metered_end', char(mend), 'flow_column', flow_column, ...
        'sign', double(tbl.sign(k)), 'original_or_added', 'explicit_s11', ...
        'candidate_name', char(tbl.circuit_id(k)), ...
        'target_source', char(tbl.target_source(k)), ...
        'source_monitored_circuit', char(tbl.source_monitored_circuit(k)), ...
        'circuit_id', char(tbl.circuit_id(k)), ...
        'reduced_branch_or_cutset', char(tbl.reduced_branch_or_cutset(k)), ...
        'effective_date', char(tbl.effective_date(k)), ...
        'mapping_confidence', char(tbl.mapping_confidence(k)), ...
        'calibration_eligible', logical(tbl.calibration_eligible(k)));
    if isempty(defs), defs = rec; else, defs(end+1) = rec; end %#ok<AGROW>
end
end

function defs = legacy_definitions(mpc)
% Preserve the pre-S11 behavior for older 143- and 49-bus workflows.
mpc = attach_nyiso_zone_metadata(mpc);
BR_STATUS = 11;
specs = { ...
 'Dysinger_East','Dysinger_East','A-B','A','B','A_to_B'; ...
 'West_Central','West_Central','B-C','B','C','B_to_C'; ...
 'Moses_South','Moses_South','D-E','D','E','D_to_E'; ...
 'Central_East','Central_East','E-F','E','F','E_to_F'; ...
 'Total_East_proxy','Total_East_proxy','F-G','F','G','F_to_G'; ...
 'UPNY_ConEd','UPNY_ConEd','G-H','G','H','G_to_H'; ...
 'Millwood_South','Millwood_South','H-I','H','I','H_to_I'; ...
 'Dunwoodie_South','Dunwoodie_South','I-J','I','J','I_to_J'; ...
 'ConEd_LIPA_IK','ConEd_LIPA_total','I-K','I','K','I_to_K'; ...
 'ConEd_LIPA_JK','ConEd_LIPA_total','J-K','J','K','J_to_K'};
fields = {'interface_name','aggregate_name','zone_boundary','positive_direction', ...
 'branch_index','branch_from','branch_to','branch_from_name','branch_to_name', ...
 'metered_bus','metered_end','flow_column','sign','original_or_added', ...
 'candidate_name','target_source'};
rows = {};
for b = 1:size(mpc.branch,1)
    if size(mpc.branch,2) >= BR_STATUS && mpc.branch(b,BR_STATUS) <= 0, continue; end
    fb = mpc.branch(b,1); tb = mpc.branch(b,2);
    fi = find(mpc.bus(:,1)==fb,1); ti = find(mpc.bus(:,1)==tb,1);
    fz = mpc.userdata.nyiso_physical_zone{fi};
    tz = mpc.userdata.nyiso_physical_zone{ti};
    for s = 1:size(specs,1)
        za = specs{s,4}; zb = specs{s,5};
        if strcmp(fz,za) && strcmp(tz,zb)
            metered = fb; mend = 'from'; fcol = 'PF';
        elseif strcmp(fz,zb) && strcmp(tz,za)
            metered = tb; mend = 'to'; fcol = 'PT';
        else
            continue;
        end
        rows(end+1,:) = {specs{s,1},specs{s,2},specs{s,3},specs{s,6}, ...
            b,fb,tb,bus_name(mpc,fi),bus_name(mpc,ti),metered,mend,fcol,1, ...
            'legacy_dynamic','','Matched PERFORM flow/PTDF target preferred'}; %#ok<AGROW>
    end
end
if isempty(rows)
    defs = cell2struct(cell(0,numel(fields)),fields,2);
else
    defs = cell2struct(rows,fields,2);
end
end

function name = bus_name(mpc, idx)
if isfield(mpc,'bus_name') && numel(mpc.bus_name) >= idx
    name = strtrim(mpc.bus_name{idx});
else
    name = sprintf('BUS_%d',mpc.bus(idx,1));
end
end
