function zones = nyiso_public_zone_map()
%NYISO_PUBLIC_ZONE_MAP Map P-58C names to NYISO A-K load zones.

zones = struct( ...
    'letter', {'A','B','C','D','E','F','G','H','I','J','K'}, ...
    'name', {'WEST','GENESE','CENTRL','NORTH','MHK VL','CAPITL', ...
             'HUD VL','MILLWD','DUNWOD','N.Y.C.','LONGIL'});
end
