function interfaces = nyiso_public_interface_map()
%NYISO_PUBLIC_INTERFACE_MAP Map P-32 public names to NY-lite proxy names.

interfaces = struct( ...
    'p32_name', {'DYSINGER EAST','WEST CENTRAL','MOSES SOUTH', ...
                 'CENTRAL EAST - VC','TOTAL EAST','UPNY CONED','SPR/DUN-SOUTH'}, ...
    'interface_name', {'Dysinger_East','West_Central','Moses_South', ...
                       'Central_East','Total_East_proxy','UPNY_ConEd','Dunwoodie_South'}, ...
    'aggregate_name', {'Dysinger_East','West_Central','Moses_South', ...
                       'Central_East','Total_East_proxy','UPNY_ConEd','Dunwoodie_South'}, ...
    'zone_boundary', {'A-B','B-C','D-E','E-F','F-G','G-H','I-J'}, ...
    'note', {'P-32 Dysinger East mapped to the reduced West-Genesee cut', ...
             'P-32 West Central mapped to the reduced Genesee-Central cut', ...
             'P-32 Moses South public interface', ...
             'P-32 Central East - VC mapped to NY-lite Central East proxy', ...
             'P-32 Total East mapped to NY-lite F-G proxy', ...
             'P-32 UPNY ConEd mapped to NY-lite G-H proxy', ...
             'P-32 Sprain Brook/Dunwoodie South mapped to NY-lite I-J proxy'});
end
