function map = nyiso_public_external_interface_map()
%NYISO_PUBLIC_EXTERNAL_INTERFACE_MAP Approximate P-32 external schedule mapping.
%   These are aggregate public schedules mapped onto retained NY boundary buses.
%   Positive P-32 flow is interpreted as import into NY for names of form X - NY.

fields = {'external_interface_name','p32_interface_name','ny_boundary_bus', ...
    'allocation_weight','direction_positive','q_mode','v_setpoint', ...
    'qmin_mvar','qmax_mvar','note'};
rows = { ...
    'HQ_NY_MOSES',      'SCH - HQ - NY', 48, 1.00, 'import_into_ny', 'limited_q_support', 1.03, -500, 500, 'Mapped to Moses East / northern HVDC proxy'; ...
    'NE_NY_NORTHFIELD', 'SCH - NE - NY', 37, 0.40, 'import_into_ny', 'limited_q_support', 1.03, -500, 500, 'Approximate New England path via New Scotland/Northfield'; ...
    'NE_NY_PV',         'SCH - NE - NY', 73, 0.60, 'import_into_ny', 'limited_q_support', 1.03, -500, 500, 'Approximate New England path via Pleasant Valley/Southington'; ...
    'OH_NY_NIAGARA',    'SCH - OH - NY', 54, 1.00, 'import_into_ny', 'limited_q_support', 1.03, -750, 750, 'Approximate Ontario/IESO path at Niagara West'; ...
    'PJM_NY_WATERCURE', 'SCH - PJ - NY', 66, 0.35, 'import_into_ny', 'limited_q_support', 1.03, -750, 750, 'Approximate PJM path via Homer City/Watcure'; ...
    'PJM_NY_WRHL',      'SCH - PJ - NY', 67, 0.15, 'import_into_ny', 'limited_q_support', 1.03, -500, 500, 'Approximate PJM path via E Tomano/WRHL'; ...
    'PJM_NY_RAMAPO',    'SCH - PJ - NY', 75, 0.25, 'import_into_ny', 'limited_q_support', 1.03, -500, 500, 'Approximate PJM path via Branchburg/Ramapo'; ...
    'PJM_NY_GOETHALS',  'SCH - PJ - NY', 81, 0.25, 'import_into_ny', 'limited_q_support', 1.03, -500, 500, 'Approximate PJM path via Linden/Goethals'};
map = cell2struct(rows, fields, 2);
end
