function contract = research_model_contract(mode)
%RESEARCH_MODEL_CONTRACT Explicit vintage and provenance for research cases.
% Declares the NY-only operating contract; it does not qualify a solved case.
% historical_2019 preserves its previous similarity-scaled meaning. The new
% historical_actual_mw mode never renormalizes the historical source powers.
if nargin < 1, mode = "contemporary_2026"; end
mode = string(mode);
if ~isscalar(mode) || ~ismember(mode, ["historical_2019", ...
        "historical_similarity_scaled","historical_actual_mw","contemporary_2026"])
    error('research_model_contract:Mode', 'Unknown research-case mode.');
end
contract = struct('schema_version', 2, 'mode', mode, ...
    'infrastructure_cutoff', "2026-09-06", ...
    'observation_valid_from_utc', "2026-06-23T04:00:00Z", ...
    'observation_valid_until_utc', "2026-09-07T04:00:00Z", ...
    'power_scale', "actual_mw", 'allow_synthetic_observations', false, ...
    'operating_network', "ny_only_explicit_boundary_injections", ...
    'external_npcc_qualification_required', false, ...
    'external_reduction_required', false, 'fixed_bus_count_required', false, ...
    'preserve_historical_cases', true, ...
    'preserve_original_record_in_provenance', true, ...
    'require_all_original_ny_elements_active', false, ...
    'allow_assumed_research_baseline', true, ...
    'boundary_sign_convention', "positive_into_NY_at_delivered_landing_terminal", ...
    'initial_boundary_control', "scheduled_P_and_declared_fixed_Q", ...
    'electrical_baseline_qualified', false, ...
    'contemporary_validation_coverage', "not_evaluated", 'dlr_ready', false, ...
    'allow_synthetic_corridor_realizations', true, ...
    'synthetic_implies_physical_provenance', false, ...
    'thermal_model_implemented', false, 'release_ready', false);
if ismember(mode,["historical_2019","historical_similarity_scaled","historical_actual_mw"])
    contract.infrastructure_cutoff = "2019-12-31";
    contract.observation_valid_from_utc = "2019-01-01T05:00:00Z";
    contract.observation_valid_until_utc = "2020-01-01T05:00:00Z";
    if mode ~= "historical_actual_mw"
        contract.power_scale = "historical_similarity_scaled";
    end
    contract.contemporary_validation_coverage = "not_applicable_historical_case";
end
contract.allowed_internal_dispositions = ["replace";"deactivate";"split";"aggregate";"retain"];
contract.internal_replacement_requirement = ...
    "Document old-element disposition and conserve assigned load generation shunts controls and boundary functions";
contract.boundary_accounting_requirement = ...
    "Keep gross load native generation and fixed boundary P/Q separate; assemble effective demand exactly once";
contract.branch_classes = table( ...
    ["physical_overhead_circuit";"synthetic_overhead_corridor"; ...
     "nonthermal_equivalent";"underground_or_submarine_cable"; ...
     "controlled_dc_import";"transformer"], ...
    [true;false;false;true;true;true], ...
    [true;true;false;false;false;false], ...
    'VariableNames', {'branch_class','requires_physical_identity','eligible_for_future_overhead_thermal_model'});
contract.thermal_eligibility_condition = ...
    "Explicit realization and resistance/current/heating validation required; class alone is insufficient";
contract.electrical_baseline_requirements = [ ...
    "No unresolved double counting or unexplained omitted injections"; ...
    "Declared finite native P/Q capability and explicit boundary allocation and fixed Q"; ...
    "AC balance and declared voltage rating and angle limits satisfied without fictitious injections"; ...
    "Independent replay with accounted reference adjustment and complete attempted-case outcomes"];
contract.electrical_baseline_blockers = "No independently qualified operating-result artifact supplied to this contract";
contract.contemporary_validation_requirements = [ ...
    "Contemporary asset-to-case mapping and electrical replacement parameters unresolved"; ...
    "Contemporary generator identity/status/capability crosswalk unresolved"; ...
    "Matched observations and held-out coverage limit contemporary validation claims"];
contract.dlr_blockers = "Conductor realization and independent electrothermal checks not completed";
contract.release_blockers = [contract.electrical_baseline_blockers;contract.dlr_blockers];
end
