function contract = research_model_contract(mode)
%RESEARCH_MODEL_CONTRACT Explicit vintage and provenance for research cases.
% This declares eligibility only; it does not instantiate or promote a case.
if nargin < 1, mode = "contemporary_2026"; end
mode = string(mode);
if ~isscalar(mode) || ~ismember(mode, ["historical_2019","contemporary_2026"])
    error('research_model_contract:Mode', 'Unknown research-case mode.');
end
contract = struct('schema_version', 1, 'mode', mode, ...
    'infrastructure_cutoff', "2026-09-06", ...
    'observation_valid_from_utc', "2026-06-23T04:00:00Z", ...
    'observation_valid_until_utc', "2026-09-07T04:00:00Z", ...
    'power_scale', "actual_mw", 'allow_synthetic_observations', false, ...
    'allow_synthetic_corridor_realizations', true, ...
    'synthetic_implies_physical_provenance', false, ...
    'thermal_model_implemented', false, 'release_ready', false);
if mode == "historical_2019"
    contract.infrastructure_cutoff = "2019-12-31";
    contract.observation_valid_from_utc = "2019-01-01T05:00:00Z";
    contract.observation_valid_until_utc = "2020-01-01T05:00:00Z";
    contract.power_scale = "historical_similarity_scaled";
end
contract.branch_classes = table( ...
    ["physical_overhead_circuit";"synthetic_overhead_corridor"; ...
     "nonthermal_equivalent";"underground_or_submarine_cable"; ...
     "controlled_dc_import";"transformer"], ...
    [true;false;false;true;true;true], ...
    [true;true;false;false;false;false], ...
    'VariableNames', {'branch_class','requires_physical_identity','eligible_for_future_overhead_thermal_model'});
contract.thermal_eligibility_condition = ...
    "Explicit realization and resistance/current/heating validation required; class alone is insufficient";
contract.release_blockers = [ ...
    "Contemporary asset-to-case mapping and electrical replacement parameters unresolved"; ...
    "Contemporary generator identity/status/capability crosswalk unresolved"; ...
    "Matched dispatch/interchange/voltage observations and held-out evidence required"];
end
