function outputs = run_s11_dlr_validation(options)
%RUN_S11_DLR_VALIDATION Build and gate the S11 DLR power-flow case set.
%   OUTPUTS = RUN_S11_DLR_VALIDATION(OPTIONS) validates the central-Q,
%   0.90-Q, and 1.10-Q variants of the S1, S2, and S5 public snapshots. It
%   also runs the 2019 PERFORM same-snapshot structural benchmark.
%
%   A scenario is included in the preliminary model set only when every
%   operating-point gate and the shared 2019 structural benchmark pass.
%   Failures are retained in the validation tables but are never relabeled
%   as accepted. No tolerance is relaxed in response to a failed case.
%
%   Common options:
%       build_cases        call BUILD_S11_DLR_PF_CASE (default true)
%       write_outputs      write the validation CSVs (default true)
%       fail_on_nominal    error after writing if nominal is not promoted
%                          (default true)
%       write_case_files   save only cases that pass every gate (default true)
%       build_options      options forwarded to BUILD_S11_DLR_PF_CASE
%       benchmark_options  options forwarded to the 2019 benchmark
%
%   With build_cases=false, existing case files are rechecked. Saved cases
%   that lack build-time dispatch provenance cannot pass the promotion gate.

if nargin < 1, options = struct(); end
helper_dir = fileparts(mfilename('fullpath'));
case_dir = fileparts(helper_dir);
options = defaults(options, helper_dir, case_dir);
validate_options(options);

addpath(case_dir);
addpath(helper_dir);
define_constants;

variants = build_variant_table(options);
[benchmark, benchmark_pass, benchmark_error] = run_benchmark(options);

records = repmat(summary_template(), height(variants), 1);
interface_validation = table();
gate_validation = table();
branch_report = table();
build_outputs = cell(height(variants), 1);

for k = 1:height(variants)
    scenario_id = variants.scenario_id(k);
    role = variants.role(k);
    q_multiplier = variants.q_multiplier(k);
    built = [];
    record = summary_template();
    record.scenario_id = scenario_id;
    record.role = role;
    record.q_multiplier = q_multiplier;
    record.is_central_q = abs(q_multiplier - 1) <= 1e-12;
    record.is_nominal = record.is_central_q && ...
        scenario_id == options.nominal_scenario_id;
    try
        if options.build_cases
            build_options = options.build_options;
            build_options.q_multiplier = q_multiplier;
            % The validation runner owns final exclusion and case writing.
            % Keep failed solved cases in memory for complete diagnostics.
            build_options.write_cases = false;
            build_options.require_operating_gates = false;
            if ~isfield(build_options, 'write_intermediate_maps')
                % A diagnostic/no-write validation must not mutate shared
                % provenance CSVs. In a publishing run, write the invariant
                % physical/interface maps once on the first variant only.
                build_options.write_intermediate_maps = ...
                    logical(options.write_outputs && k == 1);
            end
            if ~isfield(build_options, 'non_dlr_correction')
                build_options.non_dlr_correction = ...
                    options.non_dlr_correction_file;
            end
            built = build_s11_dlr_pf_case(scenario_id, build_options);
            provenance_complete = true;
            record.case_status = "built_and_validated";
        else
            built = load_existing_variant(scenario_id, role, q_multiplier, ...
                options);
            provenance_complete = built.provenance_complete;
            record.case_status = "loaded_and_rechecked";
        end
        record = assess_variant(record, built, provenance_complete, options);
        interface_rows = make_interface_rows(record, built, options);
        branch_rows = make_branch_rows(record, built, benchmark);
    catch ex
        record.build_success = false;
        record.case_status = "excluded_after_validation_failure";
        record.exception_identifier = string(ex.identifier);
        record.exception_message = string(ex.message);
        record.operating_gate_pass = false;
        record.included_in_preliminary_model_set = false;
        interface_rows = failed_interface_row(record);
        branch_rows = table();
    end

    record.structural_2019_pass = benchmark_pass;
    record.included_in_preliminary_model_set = ...
        record.operating_gate_pass && benchmark_pass;
    record.nominal_promotion_pass = false;
    if record.included_in_preliminary_model_set
        if record.is_nominal
            record.case_status = "promoted_preliminary_operating_case";
        elseif record.is_central_q
            record.case_status = "accepted_validation_case";
        else
            record.case_status = "accepted_reactive_load_sensitivity_case";
        end
        if options.build_cases && options.write_case_files
            try
                [built, case_files] = write_validated_case_files( ...
                    built, role, q_multiplier, options.case_dir);
                record.case_files_written = true;
                record.input_case_file = case_files.input_file;
                record.solution_case_file = case_files.solution_file;
            catch ex
                record.case_status = "excluded_after_case_write_failure";
                record.exception_identifier = string(ex.identifier);
                record.exception_message = string(ex.message);
                record.included_in_preliminary_model_set = false;
            end
        end
    elseif record.build_success
        record.case_status = "excluded_by_mandatory_gate";
    end
    if options.build_cases && options.write_case_files && ...
            ~record.case_files_written
        try
            invalidate_managed_case_files(role, q_multiplier, options.case_dir);
        catch ex
            record.case_status = "excluded_after_stale_case_invalidation_failure";
            record.exception_identifier = string(ex.identifier);
            record.exception_message = string(ex.message);
            record.included_in_preliminary_model_set = false;
        end
    end
    if exist('built', 'var') && isstruct(built)
        build_outputs{k} = built;
    end
    record.nominal_promotion_pass = record.is_nominal && ...
        record.included_in_preliminary_model_set && ...
        record.case_files_written;
    records(k) = record;

    interface_rows.structural_2019_pass(:) = benchmark_pass;
    interface_rows.included_in_preliminary_model_set(:) = ...
        record.included_in_preliminary_model_set;
    if ~isempty(branch_rows)
        branch_rows.structural_2019_pass(:) = benchmark_pass;
        branch_rows.included_in_preliminary_model_set(:) = ...
            record.included_in_preliminary_model_set;
    end
    interface_validation = append_table(interface_validation, interface_rows);
    branch_report = append_table(branch_report, branch_rows);
    gate_validation = append_table(gate_validation, ...
        make_variant_gate_rows(record, options));
end

% Keep the complete reduced 2019 branch solution in the current report as
% a diagnostic benchmark block. It is never an operating scenario and is
% therefore never marked as included in the preliminary model set.
benchmark_branch_rows = make_benchmark_branch_rows(benchmark, benchmark_pass);
branch_report = append_table(branch_report, benchmark_branch_rows);

summary = struct2table(records);
[benchmark_gate_rows, benchmark_summary_rows] = ...
    benchmark_validation_rows(benchmark, benchmark_pass, benchmark_error);
gate_validation = append_table(gate_validation, benchmark_gate_rows);
summary = [summary; benchmark_summary_rows];

% Add the shared structural gate and final inclusion status after all rows
% are available. This keeps operating and structural failures distinct.
for k = 1:height(variants)
    record = records(k);
    row = gate_row(record, "structural_benchmark", ...
        "2019_same_snapshot_all_gates", double(benchmark_pass), "flag", ...
        "==", 1, benchmark_pass, true, ...
        "Shared current, active-loss, and corrected net-network-Q gate.");
    gate_validation = append_table(gate_validation, row);
    row = gate_row(record, "overall", ...
        "included_in_preliminary_model_set", ...
        double(record.included_in_preliminary_model_set), "flag", "==", 1, ...
        record.included_in_preliminary_model_set, true, ...
        "Requires every operating gate and the shared 2019 benchmark.");
    gate_validation = append_table(gate_validation, row);
end

if isempty(branch_report)
    branch_report = empty_branch_report();
end

files = output_files(options.output_dir);
if options.write_outputs
    require_output_directory(options.output_dir);
    writetable(interface_validation, files.interface_validation);
    writetable(gate_validation, files.voltage_q_branch_validation);
    writetable(branch_report, files.branch_current_report);
    writetable(summary, files.dispatch_and_loss_summary);
end

nominal_idx = find(summary.scenario_id == options.nominal_scenario_id & ...
    summary.is_central_q, 1);
nominal_pass = ~isempty(nominal_idx) && ...
    summary.nominal_promotion_pass(nominal_idx);
outputs = struct( ...
    'variants', variants, ...
    'scenario_summary', summary, ...
    'interface_validation', interface_validation, ...
    'voltage_q_branch_validation', gate_validation, ...
    'branch_current_report', branch_report, ...
    'build_outputs', {build_outputs}, ...
    'benchmark', benchmark, ...
    'benchmark_pass', benchmark_pass, ...
    'benchmark_error', benchmark_error, ...
    'nominal_promotion_pass', nominal_pass, ...
    'included_scenario_count', nnz([records.included_in_preliminary_model_set]), ...
    'output_files', files, ...
    'outputs_written', logical(options.write_outputs));

if options.fail_on_nominal && ~nominal_pass
    error('run_s11_dlr_validation:NominalNotPromoted', ...
        ['The S1 central-Q case did not pass every mandatory operating and ' ...
        '2019 structural gate. Validation outputs were retained.']);
end
end

function options = defaults(options, helper_dir, case_dir)
items = { ...
    'scenario_ids', ["S1_2025_SUMMER_PEAK_PUBLIC"; ...
        "S2_2025_WINTER_PEAK_PUBLIC"; ...
        "S5_2025_HIGH_TOTAL_EAST_PUBLIC"]; ...
    'nominal_scenario_id', "S1_2025_SUMMER_PEAK_PUBLIC"; ...
    'q_multipliers', [1.0 0.90 1.10]; ...
    'build_cases', true; ...
    'write_outputs', true; ...
    'fail_on_nominal', true; ...
    'write_case_files', true; ...
    'run_2019_benchmark', true; ...
    'build_options', struct(); ...
    'benchmark_options', struct(); ...
    'non_dlr_correction_file', fullfile(helper_dir, ...
        's11_non_dlr_admittance_correction.mat'); ...
    'output_dir', helper_dir; ...
    'case_dir', case_dir; ...
    'physical_map_file', fullfile(helper_dir, 's11_physical_circuit_map.csv'); ...
    'interface_map_file', fullfile(helper_dir, 'nyiso_interface_branch_map.csv'); ...
    'interface_target_file', fullfile(helper_dir, 'nyiso_public_interface_targets.csv'); ...
    'use_raw_public_targets', true; ...
    'interface_mae_gate_mw', 100; ...
    'interface_max_residual_gate_mw', 200; ...
    'interface_signed_bias_gate_mw', 50; ...
    'reference_pickup_gate_mw', 1; ...
    'redispatch_gate_percent_of_load', 10; ...
    'redispatch_hard_limit_mw', 3000; ...
    'redispatch_justification', ""; ...
    'physical_circuit_count', 5; ...
    'expected_bus_count', 49; ...
    'expected_branch_count', 83; ...
    'q_saturation_preferred_percent', 20; ...
    'maximum_external_q_range_mvar', 0; ...
    'hard_limit_tolerance_mva', 1e-3; ...
    'numeric_tolerance', 1e-6};
for k = 1:size(items, 1)
    if ~isfield(options, items{k, 1})
        options.(items{k, 1}) = items{k, 2};
    end
end
options.scenario_ids = string(options.scenario_ids);
options.scenario_ids = options.scenario_ids(:);
options.nominal_scenario_id = string(options.nominal_scenario_id);
options.q_multipliers = double(options.q_multipliers(:)');
options.output_dir = char(options.output_dir);
options.case_dir = char(options.case_dir);
options.physical_map_file = char(options.physical_map_file);
options.interface_map_file = char(options.interface_map_file);
options.interface_target_file = char(options.interface_target_file);
options.non_dlr_correction_file = char(options.non_dlr_correction_file);
options.redispatch_justification = string(options.redispatch_justification);
end

function validate_options(options)
validateattributes(options.q_multipliers, {'numeric'}, ...
    {'vector','finite','positive'});
validateattributes(options.interface_mae_gate_mw, {'numeric'}, ...
    {'scalar','finite','positive'});
validateattributes(options.interface_max_residual_gate_mw, {'numeric'}, ...
    {'scalar','finite','positive'});
validateattributes(options.interface_signed_bias_gate_mw, {'numeric'}, ...
    {'scalar','finite','positive'});
validateattributes(options.reference_pickup_gate_mw, {'numeric'}, ...
    {'scalar','finite','positive','<=',1});
validateattributes(options.redispatch_gate_percent_of_load, {'numeric'}, ...
    {'scalar','finite','positive'});
validateattributes(options.redispatch_hard_limit_mw, {'numeric'}, ...
    {'scalar','finite','positive'});
validateattributes(options.maximum_external_q_range_mvar, {'numeric'}, ...
    {'scalar','finite','nonnegative'});
if ~isscalar(options.nominal_scenario_id)
    error('run_s11_dlr_validation:NominalScenario', ...
        'nominal_scenario_id must be scalar text.');
end
if ~isscalar(options.redispatch_justification)
    error('run_s11_dlr_validation:RedispatchJustification', ...
        'redispatch_justification must be scalar text.');
end
if ~ismember(options.nominal_scenario_id, options.scenario_ids)
    error('run_s11_dlr_validation:NominalScenario', ...
        'The nominal scenario must be in scenario_ids.');
end
if ~isstruct(options.build_options) || ~isstruct(options.benchmark_options)
    error('run_s11_dlr_validation:Options', ...
        'build_options and benchmark_options must be structs.');
end
end

function variants = build_variant_table(options)
n = numel(options.scenario_ids) * numel(options.q_multipliers);
scenario_id = strings(n, 1);
role = strings(n, 1);
q_multiplier = zeros(n, 1);
is_central_q = false(n, 1);
row = 0;
for s = 1:numel(options.scenario_ids)
    for q = 1:numel(options.q_multipliers)
        row = row + 1;
        scenario_id(row) = options.scenario_ids(s);
        role(row) = scenario_role(options.scenario_ids(s));
        q_multiplier(row) = options.q_multipliers(q);
        is_central_q(row) = abs(q_multiplier(row)-1) <= 1e-12;
    end
end
variants = table(scenario_id, role, q_multiplier, is_central_q);
end

function [benchmark, passed, error_text] = run_benchmark(options)
benchmark = struct();
passed = false;
error_text = "";
if ~options.run_2019_benchmark
    error_text = "2019 benchmark disabled; structural gate is unverified.";
    return;
end
benchmark_options = options.benchmark_options;
benchmark_options.write_output = options.write_outputs;
benchmark_options.output_file = fullfile(options.output_dir, ...
    's11_2019_same_snapshot_benchmark.csv');
if ~isfield(benchmark_options, 'non_dlr_correction')
    benchmark_options.non_dlr_correction = ...
        options.non_dlr_correction_file;
end
try
    benchmark = run_s11_2019_same_snapshot_benchmark(benchmark_options);
    correction_ward_audit = correction_ward_gate( ...
        benchmark_options.non_dlr_correction);
    benchmark.correction_ward_audit = correction_ward_audit;
    passed = isfield(benchmark, 'all_mandatory_gates_pass') && ...
        logical(benchmark.all_mandatory_gates_pass);
catch ex
    error_text = string(ex.identifier) + ": " + string(ex.message);
    benchmark = struct('exception_identifier', string(ex.identifier), ...
        'exception_message', string(ex.message));
end
end

function audit = correction_ward_gate(input)
audit = struct('required', false, 'metadata_present', false, ...
    'ward_nonworsening', true, 'pass', true, ...
    'baseline_complex_relative_frobenius_error', NaN, ...
    'corrected_complex_relative_frobenius_error', NaN, ...
    'note', "No non-DLR correction supplied; Ward correction gate not applicable.");
if isempty(input), return; end
audit.required = true;
if ischar(input) || isstring(input)
    data = load(char(input));
    if ~isfield(data, 'correction')
        audit.ward_nonworsening = false;
        audit.note = "Diagnostic unavailable: correction MAT-file lacks the correction variable.";
        return;
    end
    correction = data.correction;
else
    correction = input;
end
if ~isstruct(correction) || ~isfield(correction, 'ward_nonworsening')
    audit.ward_nonworsening = false;
    audit.note = "Diagnostic unavailable: correction lacks ward_nonworsening metadata.";
    return;
end
audit.metadata_present = true;
audit.ward_nonworsening = logical(correction.ward_nonworsening);
if isfield(correction, 'ward_summary') && istable(correction.ward_summary)
    rows = correction.ward_summary;
    quantity = string(rows.quantity);
    idx = find(quantity == "complex_relative_frobenius", 1);
    if ~isempty(idx)
        audit.baseline_complex_relative_frobenius_error = ...
            double(rows.baseline_value(idx));
        audit.corrected_complex_relative_frobenius_error = ...
            double(rows.fitted_value(idx));
    end
end
if audit.pass
    if audit.ward_nonworsening
        audit.note = "Diagnostic: local Ward-anchor relative Frobenius error is nonworsening.";
    else
        audit.note = "Diagnostic: empirical correction worsens the local Ward-anchor " + ...
            "relative Frobenius error; the plan's mandatory 2019 gates remain " + ...
            "circuit current, active loss, and net network Q.";
    end
else
    audit.note = "Diagnostic unavailable.";
end
end

function record = assess_variant(record, built, provenance_complete, options)
define_constants;
record.build_success = true;
record.dispatch_justification = options.redispatch_justification;
record.non_dlr_correction_file = string(options.non_dlr_correction_file);
if isfield(built, 'correction_report') && ...
        isfield(built.correction_report, 'correction')
    ward = correction_ward_gate(built.correction_report.correction);
    record.ward_nonworsening = ward.ward_nonworsening;
    record.baseline_ward_relative_frobenius_error = ...
        ward.baseline_complex_relative_frobenius_error;
    record.corrected_ward_relative_frobenius_error = ...
        ward.corrected_complex_relative_frobenius_error;
end
record.provenance_complete = logical(provenance_complete);
record.standard_pf_success = success_flag(built.standard_pf);
record.q_limit_pf_success = success_flag(built.solution);
if ~record.q_limit_pf_success
    error('run_s11_dlr_validation:QPF', ...
        'The Q-limit-enforced power flow did not converge.');
end
result = built.solution;
input_case = built.input_case;
allowed_reference_buses = [37 38 39 41 73 76 81];
regulating_bus_ids = input_case.bus( ...
    ismember(input_case.bus(:, BUS_TYPE), [PV REF]), BUS_I);
reference_bus_ids = input_case.bus( ...
    input_case.bus(:, BUS_TYPE) == REF, BUS_I);
record.regulating_bus_count = numel(regulating_bus_ids);
record.unexpected_regulating_bus_count = nnz( ...
    ~ismember(regulating_bus_ids, allowed_reference_buses));
record.operational_reference_bus = NaN;
if isscalar(reference_bus_ids)
    record.operational_reference_bus = reference_bus_ids(1);
end
record.mapped_operational_reference_bus = NaN;
if isfield(built, 'control_report') && ...
        isfield(built.control_report, 'generator_report') && ...
        istable(built.control_report.generator_report)
    control_rows = built.control_report.generator_report;
    required_reference_columns = {'retained_device_bus', ...
        'is_native_active_control','is_operational_reference'};
    if all(ismember(required_reference_columns, ...
            control_rows.Properties.VariableNames))
        mapped = logical(control_rows.is_native_active_control) & ...
            logical(control_rows.is_operational_reference);
        mapped_buses = unique(double( ...
            control_rows.retained_device_bus(mapped)));
        if isscalar(mapped_buses)
            record.mapped_operational_reference_bus = mapped_buses(1);
        end
    end
end
record.mapped_reference_control_match = ...
    isfinite(record.operational_reference_bus) && ...
    isfinite(record.mapped_operational_reference_bus) && ...
    record.operational_reference_bus == ...
    record.mapped_operational_reference_bus;
record.bus_count = size(result.bus, 1);
record.branch_count = size(result.branch, 1);
record.total_load_mw = sum(result.bus(:, PD));
record.total_generation_mw = sum(result.gen(result.gen(:, GEN_STATUS)>0, PG));
record.active_loss_mw = record.total_generation_mw-record.total_load_mw;
network = network_metrics(result);
record.net_network_q_mvar = network.net_network_q_mvar;
record.active_balance_identity_residual_mw = ...
    network.active_identity_residual_mw;
record.reactive_balance_identity_residual_mvar = ...
    network.reactive_identity_residual_mvar;

external = [];
if isfield(built, 'control_report') && ...
        isfield(built.control_report, 'external_gen_idx')
    external = built.control_report.external_gen_idx(:);
end
external = external(external >= 1 & external <= size(result.gen, 1));
online = result.gen(:, GEN_STATUS) > 0;
internal = online;
internal(external) = false;
record.internal_generation_mw = sum(result.gen(internal, PG));
record.external_schedule_mw = sum(result.gen(external, PG));

vviol = result.bus(:, VM) < result.bus(:, VMIN)-options.numeric_tolerance | ...
    result.bus(:, VM) > result.bus(:, VMAX)+options.numeric_tolerance;
qviol = online & (result.gen(:, QG) < ...
    result.gen(:, QMIN)-options.hard_limit_tolerance_mva | ...
    result.gen(:, QG) > result.gen(:, QMAX)+options.hard_limit_tolerance_mva);
pviol = online & (result.gen(:, PG) < ...
    result.gen(:, PMIN)-options.hard_limit_tolerance_mva | ...
    result.gen(:, PG) > result.gen(:, PMAX)+options.hard_limit_tolerance_mva);
smax = max(hypot(result.branch(:, PF), result.branch(:, QF)), ...
    hypot(result.branch(:, PT), result.branch(:, QT)));
rated = result.branch(:, RATE_A) > 0 & ...
    result.branch(:, BR_STATUS) > 0;
[trusted_rated, legacy_diagnostic_rated] = branch_limit_masks( ...
    size(result.branch, 1), built.physical_circuit_map, rated);
all_rated_over = rated & ...
    smax > result.branch(:, RATE_A)+options.numeric_tolerance;
trusted_over = trusted_rated & all_rated_over;
legacy_diagnostic_over = legacy_diagnostic_rated & all_rated_over;
loading_ratio = nan(size(smax));
loading_ratio(rated) = smax(rated)./result.branch(rated, RATE_A);
record.min_voltage_pu = min(result.bus(:, VM));
record.max_voltage_pu = max(result.bus(:, VM));
record.voltage_violation_count = nnz(vviol);
record.generator_p_violation_count = nnz(pviol);
record.generator_q_violation_count = nnz(qviol);
record.branch_overload_count = nnz(trusted_over);
record.max_branch_overload_mva = max([0; ...
    smax(trusted_over)-result.branch(trusted_over, RATE_A)]);
record.trusted_static_branch_count = nnz(trusted_rated);
record.trusted_static_branch_overload_count = nnz(trusted_over);
record.trusted_static_max_loading_ratio = max([0; ...
    loading_ratio(trusted_rated)]);
record.legacy_rated_diagnostic_branch_count = nnz(legacy_diagnostic_rated);
record.legacy_rated_diagnostic_overload_count = ...
    nnz(legacy_diagnostic_over);
record.legacy_rated_diagnostic_max_loading_ratio = max([0; ...
    loading_ratio(legacy_diagnostic_rated)]);
record.legacy_rated_diagnostic_max_overload_mva = max([0; ...
    smax(legacy_diagnostic_over)- ...
    result.branch(legacy_diagnostic_over, RATE_A)]);
record.all_rated_branch_count = nnz(rated);
record.all_rated_branch_overload_count = nnz(all_rated_over);
record.all_rated_max_loading_ratio = max([0; loading_ratio(rated)]);

variable_q = online & result.gen(:, QMAX)-result.gen(:, QMIN) > ...
    options.numeric_tolerance;
at_q_limit = abs(result.gen(:, QG)-result.gen(:, QMIN)) <= 1e-3 | ...
    abs(result.gen(:, QG)-result.gen(:, QMAX)) <= 1e-3;
record.regulating_generator_count = nnz(variable_q);
record.q_saturation_count = nnz(variable_q & at_q_limit);
if record.regulating_generator_count > 0
    record.q_saturation_percent = 100 * record.q_saturation_count / ...
        record.regulating_generator_count;
else
    record.q_saturation_percent = 0;
end
initial_reg_ids = input_case.bus( ...
    ismember(input_case.bus(:, BUS_TYPE), [PV REF]), BUS_I);
[found, result_idx] = ismember(initial_reg_ids, result.bus(:, BUS_I));
became_pq = false(size(found));
became_pq(found) = result.bus(result_idx(found), BUS_TYPE) == PQ;
record.pv_to_pq_conversion_count = nnz(became_pq);
record.placeholder_internal_q_limit_count = ...
    placeholder_internal_q_count(input_case, external, options.numeric_tolerance);
external_q_width = input_case.gen(external, QMAX)-input_case.gen(external, QMIN);
record.unrestricted_external_q_count = ...
    nnz(external_q_width > options.maximum_external_q_range_mvar + ...
    options.numeric_tolerance);
record.maximum_external_q_range_mvar = max([0; external_q_width]);

record.restoration_slack_mw = 0;
record.restoration_slack_mvar = 0;
if isfield(built, 'metrics')
    record.reference_pickup_mw = built.metrics.reference_pickup_mw;
else
    record.reference_pickup_mw = NaN;
end
if isfield(built, 'closure')
    closure = built.closure;
    if isfield(closure, 'converged'), record.closure_converged = closure.converged; end
    if isfield(closure, 'stop_reason'), record.closure_stop_reason = string(closure.stop_reason); end
    if isfield(closure, 'iteration_count'), record.closure_iteration_count = closure.iteration_count; end
    if isfield(closure, 'accepted_step_count'), record.accepted_step_count = closure.accepted_step_count; end
end
if isfield(built, 'projection')
    record.projection_attempted = logical(built.projection.attempted);
    record.projection_success = logical(built.projection.success);
end

[record.interface_mae_mw, record.interface_max_residual_mw, ...
    record.interface_signed_bias_mw] = interface_aggregate( ...
    built, record.scenario_id, options);
[record.original_dispatch_movement_mw, ...
    record.seed_dispatch_movement_mw, ...
    record.source_prior_dispatch_movement_mw, ...
    record.source_balanced_prior_dispatch_movement_mw, ...
    record.scenario_balanced_prior_dispatch_movement_mw] = ...
    dispatch_movement(built);
if record.total_load_mw > 0
    record.dispatch_movement_percent_of_load = ...
        100 * record.source_balanced_prior_dispatch_movement_mw / ...
        record.total_load_mw;
end

map = built.physical_circuit_map;
physical = string(map.branch_classification) == "physical_circuit";
ids = string(map.physical_circuit_id(physical));
record.physical_circuit_row_count = nnz(physical);
record.unique_physical_circuit_count = numel(unique(ids(strlength(ids)>0)));
record.one_branch_per_physical_circuit = ...
    record.physical_circuit_row_count == record.unique_physical_circuit_count && ...
    numel(unique(map.branch_index(physical))) == nnz(physical);

mandatory = [ ...
    record.provenance_complete; ...
    record.closure_converged; ...
    record.standard_pf_success; ...
    record.q_limit_pf_success; ...
    abs(record.restoration_slack_mw) <= options.numeric_tolerance; ...
    abs(record.restoration_slack_mvar) <= options.numeric_tolerance; ...
    record.voltage_violation_count == 0; ...
    record.generator_p_violation_count == 0; ...
    record.generator_q_violation_count == 0; ...
    record.trusted_static_branch_overload_count == 0; ...
    isfinite(record.reference_pickup_mw) && ...
        abs(record.reference_pickup_mw) < options.reference_pickup_gate_mw; ...
    isfinite(record.interface_mae_mw) && ...
        record.interface_mae_mw <= options.interface_mae_gate_mw; ...
    isfinite(record.interface_max_residual_mw) && ...
        record.interface_max_residual_mw <= ...
        options.interface_max_residual_gate_mw; ...
    isfinite(record.interface_signed_bias_mw) && ...
        abs(record.interface_signed_bias_mw) <= ...
        options.interface_signed_bias_gate_mw; ...
    record.placeholder_internal_q_limit_count == 0; ...
    record.unrestricted_external_q_count == 0; ...
    record.unexpected_regulating_bus_count == 0; ...
    record.mapped_reference_control_match; ...
    record.bus_count == options.expected_bus_count; ...
    record.branch_count == options.expected_branch_count; ...
    record.one_branch_per_physical_circuit && ...
        record.unique_physical_circuit_count == options.physical_circuit_count; ...
    isfinite(record.source_balanced_prior_dispatch_movement_mw) && ...
        record.source_balanced_prior_dispatch_movement_mw <= ...
        options.redispatch_hard_limit_mw; ...
    isfinite(record.dispatch_movement_percent_of_load) && ...
        (record.dispatch_movement_percent_of_load <= ...
        options.redispatch_gate_percent_of_load || ...
        strlength(strtrim(record.dispatch_justification)) > 0)];
record.operating_gate_pass = all(mandatory);
end

function built = load_existing_variant(scenario_id, role, q_multiplier, options)
file = existing_case_file(role, q_multiplier, options.case_dir);
if exist(file, 'file') ~= 2
    error('run_s11_dlr_validation:MissingCaseFile', ...
        'Existing S11 case file is missing: %s', file);
end
mpc = loadcase(file);
[standard_pf, q_pf] = run_pf_pair(mpc);
if ~success_flag(q_pf)
    error('run_s11_dlr_validation:ExistingCaseQPF', ...
        'Q-limit PF failed for existing case %s.', file);
end
if exist(options.physical_map_file, 'file') ~= 2
    error('run_s11_dlr_validation:MissingPhysicalMap', ...
        'The S11 physical-circuit map is missing.');
end
map = readtable(options.physical_map_file, 'TextType', 'string', ...
    'VariableNamingRule', 'preserve');
interface_table = reconstruct_interfaces(q_pf, scenario_id, options);
built = struct( ...
    'scenario_id', scenario_id, ...
    'input_case', mpc, ...
    'solution', q_pf, ...
    'standard_pf', standard_pf, ...
    'physical_circuit_map', map, ...
    'interface_branch_map', table(), ...
    'control_report', struct('external_gen_idx', []), ...
    'dispatch_targets', table(), ...
    'closure', struct('converged', false, ...
        'stop_reason', "saved_case_lacks_build_time_closure_provenance", ...
        'iteration_count', NaN, 'accepted_step_count', NaN, ...
        'interface_table', interface_table), ...
    'projection', struct('attempted', false, 'success', false), ...
    'metrics', struct('reference_pickup_mw', NaN), ...
    'case_files', struct('input_file', string(file), 'solution_file', ""), ...
    'provenance_complete', false);
end

function [standard_pf, q_pf] = run_pf_pair(mpc)
standard_pf = struct('success', false);
q_pf = struct('success', false);
try
    standard_pf = runpf(mpc, mpoption('verbose',0,'out.all',0, ...
        'pf.enforce_q_lims',0));
catch
end
try
    q_pf = runpf(mpc, mpoption('verbose',0,'out.all',0, ...
        'pf.enforce_q_lims',1));
catch
end
end

function file = existing_case_file(role, q_multiplier, case_dir)
central = abs(q_multiplier-1) <= 1e-12;
if central && role == "summer_peak"
    file = fullfile(case_dir, 'npcc_ny_lite_s11_dlr_pf_base.m');
elseif central && role == "winter_peak"
    file = fullfile(case_dir, 'npcc_ny_lite_s11_dlr_winter_validation.m');
elseif central && role == "high_total_east"
    file = fullfile(case_dir, ...
        'npcc_ny_lite_s11_dlr_high_total_east_validation.m');
else
    qtag = sprintf('q%03d', round(100*q_multiplier));
    file = fullfile(case_dir, sprintf( ...
        'npcc_ny_lite_s11_dlr_%s_%s_sensitivity.m', role, qtag));
end
end

function invalidate_managed_case_files(role, q_multiplier, case_dir)
% Remove only exact validator-owned S11 filenames for a variant that is not
% accepted in the current publishing run. This prevents a previously passing
% artifact from surviving a later failed gate and appearing current.
central = abs(q_multiplier-1) <= 1e-12;
if central && role == "summer_peak"
    paths = [string(fullfile(case_dir, ...
        'npcc_ny_lite_s11_dlr_pf_base.m')); ...
        string(fullfile(case_dir, ...
        'npcc_ny_lite_s11_dlr_pf_solution.m'))];
else
    paths = string(existing_case_file(role, q_multiplier, case_dir));
end
for k = 1:numel(paths)
    if exist(char(paths(k)), 'file') == 2
        delete(char(paths(k)));
    end
    if exist(char(paths(k)), 'file') == 2
        error('run_s11_dlr_validation:StaleCaseInvalidation', ...
            'Could not invalidate stale managed S11 case: %s', paths(k));
    end
end
end

function [built, files] = write_validated_case_files( ...
        built, role, q_multiplier, case_dir)
central = abs(q_multiplier-1) <= 1e-12;
input_case = mark_case_status(built.input_case, role, central);
solution = mark_case_status(built.solution, role, central);
files = struct('input_file', "", 'solution_file', "");
if central && role == "summer_peak"
    files.input_file = string(fullfile(case_dir, ...
        'npcc_ny_lite_s11_dlr_pf_base.m'));
    files.solution_file = string(fullfile(case_dir, ...
        'npcc_ny_lite_s11_dlr_pf_solution.m'));
    write_report = write_s11_case_set_atomic( ...
        [files.input_file; files.solution_file], ...
        {input_case; solution}, [false; true]);
elseif central && role == "winter_peak"
    files.solution_file = string(fullfile(case_dir, ...
        'npcc_ny_lite_s11_dlr_winter_validation.m'));
    write_report = write_s11_case_set_atomic( ...
        files.solution_file, {solution}, true);
elseif central && role == "high_total_east"
    files.solution_file = string(fullfile(case_dir, ...
        'npcc_ny_lite_s11_dlr_high_total_east_validation.m'));
    write_report = write_s11_case_set_atomic( ...
        files.solution_file, {solution}, true);
else
    qtag = sprintf('q%03d', round(100*q_multiplier));
    files.solution_file = string(fullfile(case_dir, sprintf( ...
        'npcc_ny_lite_s11_dlr_%s_%s_sensitivity.m', role, qtag)));
    write_report = write_s11_case_set_atomic( ...
        files.solution_file, {solution}, true);
end
built.input_case = input_case;
built.solution = solution;
built.case_files = files;
built.case_write_verification = write_report;
end

function mpc = mark_case_status(mpc, role, central)
if ~isfield(mpc, 'userdata'), mpc.userdata = struct(); end
if ~isfield(mpc.userdata, 's11'), mpc.userdata.s11 = struct(); end
if central && role == "summer_peak"
    mpc.userdata.s11.status = 'promoted_preliminary_operating_case';
elseif central
    mpc.userdata.s11.status = 'accepted_validation_case';
else
    mpc.userdata.s11.status = 'accepted_reactive_load_sensitivity_case';
end
mpc.userdata.s11.promotion_scope = ...
    'Methodological DLR AC operating model; no utility operating claim.';
end

function rows = reconstruct_interfaces(result, scenario_id, options)
defs = ny_lite_interface_definitions(result, ...
    struct('map_file', options.interface_map_file));
flow_records = ny_lite_interface_flows(result, defs);
flows = struct2table(flow_records);
flows = flows(string(flows.result_type) == "subpath", :);
targets = readtable(options.interface_target_file, 'TextType', 'string', ...
    'VariableNamingRule', 'preserve');
targets = targets(string(targets.scenario_id) == scenario_id, :);
names = string(flows.interface_name);
[found, idx] = ismember(names, string(targets.interface_name));
if ~all(found)
    error('run_s11_dlr_validation:InterfaceTarget', ...
        'One or more explicit S11 interfaces have no public target.');
end
if options.use_raw_public_targets
    target_value = double(targets.nyiso_flow_mw(idx));
    source = repmat("raw_NYISO_public", height(flows), 1);
else
    target_value = double(targets.target_flow_mw(idx));
    source = repmat("S7_similarity_scaled", height(flows), 1);
end
calibration = false(height(flows), 1);
for k = 1:height(flows)
    calibration(k) = any(strcmp({defs.interface_name}, char(names(k))) & ...
        [defs.calibration_eligible]);
end
rows = table(names, calibration, source, target_value, double(flows.flow_mw), ...
    double(flows.flow_mw)-target_value, ...
    'VariableNames', {'interface_name','calibration_eligible','target_source', ...
    'target_flow_mw','final_ac_flow_mw','final_ac_residual_mw'});
end

function [mae, maximum, bias] = interface_aggregate(built, scenario_id, options)
mae = NaN; maximum = NaN; bias = NaN;
if ~isfield(built, 'solution') || ~isstruct(built.solution)
    return;
end
rows = reconstruct_interfaces(built.solution, scenario_id, options);
if isempty(rows), return; end
mask = logical(rows.calibration_eligible);
residual = double(rows.final_ac_residual_mw(mask));
if isempty(residual), return; end
mae = mean(abs(residual));
maximum = max(abs(residual));
bias = mean(residual);
end

function [original, seed, source, source_balanced, scenario_balanced] = ...
        dispatch_movement(built)
original = NaN; seed = NaN; source = NaN;
source_balanced = NaN; scenario_balanced = NaN;
if isfield(built, 'dispatch_targets') && ~isempty(built.dispatch_targets)
    targets = built.dispatch_targets;
    if ismember('original_to_final_redispatch_mw', ...
            targets.Properties.VariableNames)
        original = sum(abs(targets.original_to_final_redispatch_mw));
    end
    if ismember('seed_to_final_redispatch_mw', ...
            targets.Properties.VariableNames)
        seed = sum(abs(targets.seed_to_final_redispatch_mw));
    end
    if ismember('source_prior_to_final_redispatch_mw', ...
            targets.Properties.VariableNames)
        source = sum(abs(targets.source_prior_to_final_redispatch_mw));
    end
    if ismember('source_balanced_prior_to_final_redispatch_mw', ...
            targets.Properties.VariableNames)
        source_balanced = sum(abs( ...
            targets.source_balanced_prior_to_final_redispatch_mw));
    end
    if ismember('scenario_balanced_prior_to_final_redispatch_mw', ...
            targets.Properties.VariableNames)
        scenario_balanced = sum(abs( ...
            targets.scenario_balanced_prior_to_final_redispatch_mw));
    end
end
end

function [trusted_rated, legacy_diagnostic_rated] = ...
        branch_limit_masks(branch_count, branch_map, rated)
trusted = false(branch_count, 1);
if isempty(branch_map) || ~istable(branch_map) || ...
        ~ismember('branch_index', branch_map.Properties.VariableNames) || ...
        ~ismember('branch_classification', branch_map.Properties.VariableNames)
    error('run_s11_dlr_validation:BranchMapSchema', ...
        'The physical-circuit map lacks branch indices or classifications.');
end
idx = double(branch_map.branch_index(:));
if any(~isfinite(idx) | idx<1 | idx>branch_count | idx~=fix(idx)) || ...
        numel(unique(idx))~=numel(idx)
    error('run_s11_dlr_validation:BranchMapIndex', ...
        'The physical-circuit map has invalid or duplicate branch indices.');
end
map_trusted = string(branch_map.branch_classification) == "physical_circuit";
if ismember('trusted_static_limit', branch_map.Properties.VariableNames)
    map_trusted = map_trusted | ...
        logical_map_values(branch_map.trusted_static_limit);
end
trusted(idx(map_trusted)) = true;
trusted_rated = trusted & rated(:);
legacy_diagnostic_rated = ~trusted & rated(:);
end

function values = logical_map_values(raw)
if islogical(raw)
    values = raw(:);
elseif isnumeric(raw)
    values = isfinite(raw(:)) & raw(:)~=0;
else
    text = lower(strtrim(string(raw(:))));
    values = ismember(text, ["true","1","yes","y"]);
end
end

function count = placeholder_internal_q_count(mpc, external_idx, tolerance)
define_constants;
internal = mpc.gen(:, GEN_STATUS)>0;
external_idx = external_idx(external_idx>=1 & external_idx<=numel(internal));
internal(external_idx) = false;
qmin = mpc.gen(:, QMIN); qmax = mpc.gen(:, QMAX);
placeholder = (abs(qmin+999)<=tolerance & abs(qmax-999)<=tolerance) | ...
    (abs(qmin+9999)<=tolerance & abs(qmax-9999)<=tolerance);
count = nnz(internal & placeholder);
end

function rows = make_interface_rows(record, built, options)
source = reconstruct_interfaces(built.solution, record.scenario_id, options);
n = height(source);
scenario_id = repmat(record.scenario_id, n, 1);
role = repmat(record.role, n, 1);
q_multiplier = repmat(record.q_multiplier, n, 1);
is_central_q = repmat(record.is_central_q, n, 1);
build_success = true(n, 1);
calibration_eligible = logical(source.calibration_eligible);
target_source = string(source.target_source);
target_flow_mw = double(source.target_flow_mw);
final_ac_flow_mw = double(source.final_ac_flow_mw);
residual_mw = double(source.final_ac_residual_mw);
per_interface_gate_mw = repmat(options.interface_max_residual_gate_mw, n, 1);
assessment = repmat("diagnostic", n, 1);
assessment(calibration_eligible & ...
    abs(residual_mw)<=options.interface_max_residual_gate_mw) = "pass";
assessment(calibration_eligible & ...
    abs(residual_mw)>options.interface_max_residual_gate_mw) = "fail";
aggregate_mae_mw = repmat(record.interface_mae_mw, n, 1);
aggregate_max_residual_mw = repmat(record.interface_max_residual_mw, n, 1);
aggregate_signed_bias_mw = repmat(record.interface_signed_bias_mw, n, 1);
interface_aggregate_gate_pass = repmat( ...
    record.interface_mae_mw<=options.interface_mae_gate_mw && ...
    record.interface_max_residual_mw<=options.interface_max_residual_gate_mw && ...
    abs(record.interface_signed_bias_mw)<=options.interface_signed_bias_gate_mw, n, 1);
operating_gate_pass = repmat(record.operating_gate_pass, n, 1);
structural_2019_pass = false(n, 1);
included_in_preliminary_model_set = false(n, 1);
exception_message = strings(n, 1);
rows = table(scenario_id, role, q_multiplier, is_central_q, build_success, ...
    string(source.interface_name), calibration_eligible, target_source, ...
    target_flow_mw, final_ac_flow_mw, residual_mw, per_interface_gate_mw, ...
    assessment, aggregate_mae_mw, aggregate_max_residual_mw, ...
    aggregate_signed_bias_mw, interface_aggregate_gate_pass, ...
    operating_gate_pass, structural_2019_pass, ...
    included_in_preliminary_model_set, exception_message, ...
    'VariableNames', interface_variable_names());
end

function row = failed_interface_row(record)
row = table(record.scenario_id, record.role, record.q_multiplier, ...
    record.is_central_q, false, "<scenario_build>", false, "", ...
    NaN, NaN, NaN, NaN, "fail", NaN, NaN, NaN, false, false, false, ...
    false, record.exception_message, ...
    'VariableNames', interface_variable_names());
end

function names = interface_variable_names()
names = {'scenario_id','role','q_multiplier','is_central_q', ...
    'build_success','interface_name','calibration_eligible','target_source', ...
    'target_flow_mw','final_ac_flow_mw','residual_mw', ...
    'per_interface_gate_mw','assessment','aggregate_mae_mw', ...
    'aggregate_max_residual_mw','aggregate_signed_bias_mw', ...
    'interface_aggregate_gate_pass','operating_gate_pass', ...
    'structural_2019_pass','included_in_preliminary_model_set', ...
    'exception_message'};
end

function rows = make_variant_gate_rows(record, options)
rows = table();
rows = append_table(rows, gate_row(record, "provenance", ...
    "build_time_dispatch_provenance", double(record.provenance_complete), ...
    "flag", "==", 1, record.provenance_complete, true, ...
    "Required to verify reference pickup and zonal dispatch movement."));
rows = append_table(rows, gate_row(record, "active_balance", ...
    "iterative_ac_closure_converged", double(record.closure_converged), ...
    "flag", "==", 1, record.closure_converged, true, ...
    "Requires selected interface and reference-pickup tolerances at termination."));
rows = append_table(rows, gate_row(record, "power_flow", ...
    "standard_ac_pf_success", double(record.standard_pf_success), ...
    "flag", "==", 1, record.standard_pf_success, true, "runpf without Q enforcement."));
rows = append_table(rows, gate_row(record, "power_flow", ...
    "q_limit_enforced_pf_success", double(record.q_limit_pf_success), ...
    "flag", "==", 1, record.q_limit_pf_success, true, ...
    "runpf with pf.enforce_q_lims=1."));
rows = append_table(rows, gate_row(record, "restoration", ...
    "maximum_restoration_slack", max(abs([record.restoration_slack_mw, ...
    record.restoration_slack_mvar])), "MW_or_MVAr", "==", 0, ...
    abs(record.restoration_slack_mw)<=options.numeric_tolerance && ...
    abs(record.restoration_slack_mvar)<=options.numeric_tolerance, true, ...
    "S11 has no P/Q/voltage/branch restoration slack variables."));
rows = append_table(rows, gate_row(record, "voltage", ...
    "physical_voltage_violation_count", record.voltage_violation_count, ...
    "count", "==", 0, record.voltage_violation_count==0, true, ...
    "Checks BUS VMIN/VMAX."));
rows = append_table(rows, gate_row(record, "active_power", ...
    "generator_p_limit_violation_count", record.generator_p_violation_count, ...
    "count", "==", 0, record.generator_p_violation_count==0, true, ...
    "Checks online PG against source-backed PMIN/PMAX."));
rows = append_table(rows, gate_row(record, "reactive_power", ...
    "generator_q_limit_violation_count", record.generator_q_violation_count, ...
    "count", "==", 0, record.generator_q_violation_count==0, true, ...
    "Checks online QG against physical QMIN/QMAX."));
rows = append_table(rows, gate_row(record, "branch", ...
    "trusted_static_branch_overload_count", ...
    record.trusted_static_branch_overload_count, ...
    "count", "==", 0, record.trusted_static_branch_overload_count==0, ...
    true, "Only mapped physical circuits and map rows explicitly marked " + ...
    "trusted_static_limit are blocking; RATE_A is not a DLR ampacity."));
rows = append_table(rows, gate_row(record, "branch", ...
    "trusted_static_max_loading_ratio", ...
    record.trusted_static_max_loading_ratio, "ratio", "<=", 1, ...
    record.trusted_static_max_loading_ratio<=1+options.numeric_tolerance, ...
    true, "Maximum MVA/RATE_A across trusted static-limit rows."));
rows = append_table(rows, diagnostic_row(record, "branch_diagnostic", ...
    "legacy_rated_equivalent_branch_count", ...
    record.legacy_rated_diagnostic_branch_count, "count", ...
    "Legacy nonzero RATE_A rows outside the trusted mask."));
rows = append_table(rows, diagnostic_row(record, "branch_diagnostic", ...
    "legacy_rated_equivalent_overload_count", ...
    record.legacy_rated_diagnostic_overload_count, "count", ...
    "Diagnostic only; does not block an S11 case."));
rows = append_table(rows, diagnostic_row(record, "branch_diagnostic", ...
    "legacy_rated_equivalent_max_loading_ratio", ...
    record.legacy_rated_diagnostic_max_loading_ratio, "ratio", ...
    "Diagnostic MVA/RATE_A ratio; legacy equivalent ratings are not trusted gates."));
rows = append_table(rows, diagnostic_row(record, "branch_diagnostic", ...
    "all_nonzero_rate_a_overload_count", ...
    record.all_rated_branch_overload_count, "count", ...
    "All legacy nonzero RATE_A rows, reported for continuity only."));
rows = append_table(rows, diagnostic_row(record, "branch_diagnostic", ...
    "all_nonzero_rate_a_max_loading_ratio", ...
    record.all_rated_max_loading_ratio, "ratio", ...
    "All legacy nonzero RATE_A rows, reported for continuity only."));
rows = append_table(rows, gate_row(record, "active_balance", ...
    "absolute_reference_pickup", abs(record.reference_pickup_mw), "MW", ...
    "<", options.reference_pickup_gate_mw, ...
    isfinite(record.reference_pickup_mw) && ...
    abs(record.reference_pickup_mw)<options.reference_pickup_gate_mw, true, ...
    "Final reference pickup must be strictly below 1 MW."));
rows = append_table(rows, gate_row(record, "interface", ...
    "calibrated_interface_mae", record.interface_mae_mw, "MW", "<=", ...
    options.interface_mae_gate_mw, isfinite(record.interface_mae_mw) && ...
    record.interface_mae_mw<=options.interface_mae_gate_mw, true, ...
    "Conceptual interfaces are excluded from this aggregate."));
rows = append_table(rows, gate_row(record, "interface", ...
    "maximum_calibrated_interface_residual", ...
    record.interface_max_residual_mw, "MW", "<=", ...
    options.interface_max_residual_gate_mw, ...
    isfinite(record.interface_max_residual_mw) && ...
    record.interface_max_residual_mw<=options.interface_max_residual_gate_mw, ...
    true, "Conceptual interfaces are diagnostic only."));
rows = append_table(rows, gate_row(record, "interface", ...
    "absolute_calibrated_interface_signed_bias", ...
    abs(record.interface_signed_bias_mw), "MW", "<=", ...
    options.interface_signed_bias_gate_mw, ...
    isfinite(record.interface_signed_bias_mw) && ...
    abs(record.interface_signed_bias_mw)<=options.interface_signed_bias_gate_mw, ...
    true, "Signed bias is averaged over calibration-eligible interfaces."));
rows = append_table(rows, gate_row(record, "reactive_power", ...
    "placeholder_internal_q_limit_count", ...
    record.placeholder_internal_q_limit_count, "count", "==", 0, ...
    record.placeholder_internal_q_limit_count==0, true, ...
    "Exact generic +/-999 and +/-9999 internal Q ranges are prohibited."));
rows = append_table(rows, gate_row(record, "boundary_reactive_power", ...
    "unrestricted_external_q_count", record.unrestricted_external_q_count, ...
    "count", "==", 0, record.unrestricted_external_q_count==0, true, ...
    sprintf('Every public external Q range must be <= %.6g MVAr wide.', ...
    options.maximum_external_q_range_mvar)));
rows = append_table(rows, gate_row(record, "structure", ...
    "bus_count", record.bus_count, "count", "==", ...
    options.expected_bus_count, record.bus_count==options.expected_bus_count, ...
    true, "Promoted operating core must have 49 buses."));
rows = append_table(rows, gate_row(record, "structure", ...
    "branch_count", record.branch_count, "count", "==", ...
    options.expected_branch_count, ...
    record.branch_count==options.expected_branch_count, true, ...
    "Two double-circuit corridors add two rows to the 81-branch core."));
rows = append_table(rows, gate_row(record, "structure", ...
    "one_model_branch_per_physical_circuit", ...
    record.unique_physical_circuit_count, "count", "==", ...
    options.physical_circuit_count, record.one_branch_per_physical_circuit && ...
    record.unique_physical_circuit_count==options.physical_circuit_count, ...
    true, "Five direct physical circuits must map one-to-one."));
rows = append_table(rows, gate_row(record, "control_provenance", ...
    "unexpected_regulating_bus_count", ...
    record.unexpected_regulating_bus_count, "count", "==", 0, ...
    record.unexpected_regulating_bus_count==0, true, ...
    "Only source-backed candidate buses 37, 38, 39, 41, 73, 76, and 81 may regulate."));
rows = append_table(rows, gate_row(record, "control_provenance", ...
    "mapped_operational_reference_match", ...
    double(record.mapped_reference_control_match), "flag", "==", 1, ...
    record.mapped_reference_control_match, true, ...
    "The PF reference bus must match the mapper's source-backed operational reference."));
rows = append_table(rows, gate_row(record, "dispatch", ...
    "source_balanced_prior_to_final_absolute_zonal_redispatch", ...
    record.dispatch_movement_percent_of_load, "percent_of_NY_load", "<=", ...
    options.redispatch_gate_percent_of_load, ...
    isfinite(record.dispatch_movement_percent_of_load) && ...
    (record.dispatch_movement_percent_of_load<= ...
    options.redispatch_gate_percent_of_load || ...
    strlength(strtrim(record.dispatch_justification))>0), true, ...
    "Uses the source-PG prior after a headroom-weighted PMIN/PMAX-constrained " + ...
    "total-generation balance adjustment; it includes the DC interface " + ...
    "inference and final AC closure. Any percentage override appears in " + ...
    "dispatch_justification."));
rows = append_table(rows, gate_row(record, "dispatch", ...
    "absolute_zonal_redispatch_hard_ceiling", ...
    record.source_balanced_prior_dispatch_movement_mw, "MW", "<=", ...
    options.redispatch_hard_limit_mw, ...
    isfinite(record.source_balanced_prior_dispatch_movement_mw) && ...
    record.source_balanced_prior_dispatch_movement_mw<= ...
    options.redispatch_hard_limit_mw, true, ...
    "Unconditional several-GW safeguard; justification cannot bypass this ceiling."));
rows = append_table(rows, diagnostic_row(record, "dispatch_diagnostic", ...
    "raw_2019_source_prior_to_final_absolute_zonal_movement", ...
    record.source_prior_dispatch_movement_mw, "MW", ...
    "Includes the non-zero total-generation change between the 2019 source and public scenario."));
rows = append_table(rows, diagnostic_row(record, "dispatch_diagnostic", ...
    "constrained_dc_seed_to_final_absolute_zonal_movement", ...
    record.seed_dispatch_movement_mw, "MW", ...
    "Reports only iterative AC refinement after the constrained-DC inference."));
rows = append_table(rows, diagnostic_row(record, "dispatch_diagnostic", ...
    "legacy_scenario_balanced_prior_to_final_absolute_zonal_movement", ...
    record.scenario_balanced_prior_dispatch_movement_mw, "MW", ...
    "Uses the legacy structural scenario PG after total-generation balancing; reported for comparison only."));
rows = append_table(rows, diagnostic_row(record, "dispatch_diagnostic", ...
    "legacy_structural_scenario_to_final_absolute_zonal_movement", ...
    record.original_dispatch_movement_mw, "MW", ...
    "Legacy S7 scenario PG is not the gate baseline because it is not balanced to the public snapshot."));
rows = append_table(rows, gate_row(record, "reactive_power_preferred", ...
    "regulating_groups_at_q_limits", record.q_saturation_percent, ...
    "percent", "<", options.q_saturation_preferred_percent, ...
    record.q_saturation_percent<options.q_saturation_preferred_percent, false, ...
    "Preferred rather than blocking for the preliminary case."));
rows = append_table(rows, gate_row(record, "operating_overall", ...
    "all_operating_point_gates", double(record.operating_gate_pass), ...
    "flag", "==", 1, record.operating_gate_pass, true, ...
    "Does not include the shared 2019 structural benchmark."));
end

function row = gate_row(record, category, metric, value, unit, comparator, ...
        threshold, passed, mandatory, note)
if mandatory
    if passed, assessment = "pass"; else, assessment = "fail"; end
else
    if passed, assessment = "preferred_pass"; else, assessment = "preferred_miss"; end
end
row = table(record.scenario_id, record.role, record.q_multiplier, ...
    record.is_central_q, string(category), string(metric), double(value), ...
    string(unit), string(comparator), double(threshold), logical(mandatory), ...
    assessment, string(note), string(record.exception_message), ...
    'VariableNames', {'scenario_id','role','q_multiplier','is_central_q', ...
    'category','metric','value','unit','comparator','threshold','mandatory', ...
    'assessment','note','exception_message'});
end

function row = diagnostic_row(record, category, metric, value, unit, note)
row = gate_row(record, category, metric, value, unit, "report_only", ...
    NaN, true, false, note);
row.assessment(:) = "diagnostic";
end

function rows = make_branch_rows(record, built, benchmark)
currents = compute_branch_currents_kA(built.solution, ...
    built.physical_circuit_map);
n = height(currents);
scenario_id = repmat(record.scenario_id, n, 1);
role = repmat(record.role, n, 1);
q_multiplier = repmat(record.q_multiplier, n, 1);
is_central_q = repmat(record.is_central_q, n, 1);
operating_gate_pass = repmat(record.operating_gate_pass, n, 1);
structural_2019_pass = false(n, 1);
included_in_preliminary_model_set = false(n, 1);
loading_mva = max(hypot(currents.pf_mw, currents.qf_mvar), ...
    hypot(currents.pt_mw, currents.qt_mvar));
rated = currents.branch_status>0 & currents.rate_a_mva>0;
[trusted_static_limit, legacy_diagnostic_rated] = branch_limit_masks( ...
    n, built.physical_circuit_map, rated);
loading_to_rate_a_ratio = nan(n, 1);
loading_to_rate_a_ratio(rated) = ...
    loading_mva(rated)./currents.rate_a_mva(rated);
static_rate_assessment = repmat("unrated_diagnostic", n, 1);
static_rate_assessment(trusted_static_limit & ...
    loading_mva<=currents.rate_a_mva+1e-6) = "trusted_pass";
static_rate_assessment(trusted_static_limit & ...
    loading_mva>currents.rate_a_mva+1e-6) = "trusted_fail";
static_rate_assessment(legacy_diagnostic_rated & ...
    loading_mva<=currents.rate_a_mva+1e-6) = "legacy_diagnostic_within";
static_rate_assessment(legacy_diagnostic_rated & ...
    loading_mva>currents.rate_a_mva+1e-6) = "legacy_diagnostic_overload";
rate_a_semantics = repmat("unrated_diagnostic", n, 1);
rate_a_semantics(trusted_static_limit) = ...
    "trusted_static_gate_not_dlr_ampacity";
rate_a_semantics(legacy_diagnostic_rated) = ...
    "legacy_equivalent_diagnostic_not_gate";
current_interpretation_eligible = ...
    currents.branch_classification == "physical_circuit";
current_interpretation = repmat("equivalent_current_diagnostic_only", n, 1);
current_interpretation(current_interpretation_eligible) = ...
    "mapped_physical_circuit_current";
benchmark_source_current_kA = nan(n, 1);
benchmark_reduced_current_kA = nan(n, 1);
benchmark_absolute_percent_error = nan(n, 1);
benchmark_assessment = repmat("not_applicable", n, 1);
if isstruct(benchmark) && isfield(benchmark, 'circuit_comparison')
    comparison = benchmark.circuit_comparison;
    [found, idx] = ismember(currents.physical_circuit_id, ...
        comparison.physical_circuit_id);
    benchmark_source_current_kA(found) = ...
        comparison.source_series_current_kA(idx(found));
    benchmark_reduced_current_kA(found) = ...
        comparison.reduced_series_current_kA(idx(found));
    benchmark_absolute_percent_error(found) = ...
        comparison.absolute_percent_error(idx(found));
    benchmark_assessment(found) = string(comparison.assessment(idx(found)));
end
rows = table(scenario_id, role, q_multiplier, is_central_q, ...
    operating_gate_pass, structural_2019_pass, ...
    included_in_preliminary_model_set, currents.branch_index, ...
    currents.from_bus, currents.to_bus, currents.from_bus_name, ...
    currents.to_bus_name, currents.branch_status, currents.pf_mw, ...
    currents.qf_mvar, currents.pt_mw, currents.qt_mvar, ...
    currents.from_terminal_kv, currents.to_terminal_kv, ...
    currents.from_terminal_current_kA, currents.to_terminal_current_kA, ...
    currents.series_current_kA, currents.rate_a_mva, loading_mva, ...
    loading_to_rate_a_ratio, trusted_static_limit, rate_a_semantics, ...
    static_rate_assessment, currents.branch_classification, ...
    currents.physical_circuit_id, currents.corridor_name, ...
    currents.source_circuit_id, currents.source_branch_index, ...
    current_interpretation_eligible, current_interpretation, ...
    benchmark_source_current_kA, benchmark_reduced_current_kA, ...
    benchmark_absolute_percent_error, benchmark_assessment, ...
    'VariableNames', branch_variable_names());
end

function rows = make_benchmark_branch_rows(benchmark, benchmark_pass)
rows = table();
if ~isstruct(benchmark) || ~isfield(benchmark, 'reduced_pf') || ...
        ~isfield(benchmark, 'physical_map') || ...
        ~success_flag(benchmark.reduced_pf)
    return;
end
record = summary_template();
record.scenario_id = "S11_2019_REDUCED_BENCHMARK";
record.role = "structural_benchmark_reduced";
record.q_multiplier = 1;
record.is_central_q = true;
record.operating_gate_pass = false;
built = struct('solution', benchmark.reduced_pf, ...
    'physical_circuit_map', benchmark.physical_map);
rows = make_branch_rows(record, built, benchmark);
rows.structural_2019_pass(:) = benchmark_pass;
rows.included_in_preliminary_model_set(:) = false;
end

function names = branch_variable_names()
names = {'scenario_id','role','q_multiplier','is_central_q', ...
    'operating_gate_pass','structural_2019_pass', ...
    'included_in_preliminary_model_set','branch_index','from_bus','to_bus', ...
    'from_bus_name','to_bus_name','branch_status','pf_mw','qf_mvar', ...
    'pt_mw','qt_mvar','from_terminal_kv','to_terminal_kv', ...
    'from_terminal_current_kA','to_terminal_current_kA','series_current_kA', ...
    'rate_a_mva','maximum_terminal_loading_mva','loading_to_rate_a_ratio', ...
    'trusted_static_limit','rate_a_semantics','static_rate_assessment', ...
    'branch_classification','physical_circuit_id','corridor_name', ...
    'source_circuit_id','source_branch_index', ...
    'current_interpretation_eligible','current_interpretation', ...
    'benchmark_source_series_current_kA', ...
    'benchmark_reduced_series_current_kA', ...
    'benchmark_absolute_percent_error','benchmark_assessment'};
end

function rows = empty_branch_report()
types = ["string","string","double","logical","logical","logical", ...
    "logical","double","double","double","string","string", ...
    repmat("double",1,13), "logical", repmat("string",1,6), ...
    "double","logical","string","double","double","double","string"];
rows = table('Size', [0 numel(types)], 'VariableTypes', cellstr(types), ...
    'VariableNames', branch_variable_names());
end

function [rows, summary_rows] = benchmark_validation_rows( ...
        benchmark, passed, error_text)
record = summary_template();
record.scenario_id = "PERFORM_2019_SAME_SNAPSHOT";
record.role = "structural_benchmark";
record.q_multiplier = 1;
record.is_central_q = true;
record.build_success = strlength(error_text)==0;
record.provenance_complete = record.build_success;
record.structural_2019_pass = passed;
record.operating_gate_pass = passed;
record.included_in_preliminary_model_set = false;
record.case_status = ternary(passed, ...
    "shared_structural_benchmark_pass", "shared_structural_benchmark_fail");
record.exception_message = error_text;
rows = table();
if isstruct(benchmark) && isfield(benchmark, 'summary')
    summary = benchmark.summary;
    gated = isfinite(summary.gate_percent);
    for k = find(gated(:))'
        ok = string(summary.assessment(k)) == "pass";
        note = string(summary.metric_name(k)) + ": " + string(summary.note(k));
        rows = append_table(rows, gate_row(record, ...
            "2019_" + string(summary.metric_type(k)), ...
            string(summary.metric_name(k)), ...
            double(summary.absolute_percent_error(k)), "percent_error", ...
            "<=", double(summary.gate_percent(k)), ok, true, note));
    end
    source_ok = logical(benchmark.source_pf_success);
    reduced_ok = logical(benchmark.reduced_pf_success);
    rows = append_table(rows, gate_row(record, "2019_power_flow", ...
        "source_q_limit_pf_success", double(source_ok), "flag", "==", 1, ...
        source_ok, true, "Unmodified source benchmark."));
    rows = append_table(rows, gate_row(record, "2019_power_flow", ...
        "reduced_q_limit_pf_success", double(reduced_ok), "flag", "==", 1, ...
        reduced_ok, true, "S11 49-bus same-snapshot benchmark."));
else
    rows = append_table(rows, gate_row(record, "2019_benchmark", ...
        "benchmark_execution_success", 0, "flag", "==", 1, false, true, ...
        "Benchmark did not complete; structural promotion gate fails."));
end
if isstruct(benchmark) && isfield(benchmark, 'correction_ward_audit')
    ward = benchmark.correction_ward_audit;
    rows = append_table(rows, diagnostic_row(record, "2019_ward_structure", ...
        "non_dlr_correction_ward_nonworsening", ...
        double(ward.ward_nonworsening), "flag", ward.note));
    rows = append_table(rows, diagnostic_row(record, ...
        "2019_ward_structure", "baseline_complex_relative_frobenius_error", ...
        ward.baseline_complex_relative_frobenius_error, "relative_error", ...
        "Five-anchor local Ward diagnostic before correction."));
    rows = append_table(rows, diagnostic_row(record, ...
        "2019_ward_structure", "corrected_complex_relative_frobenius_error", ...
        ward.corrected_complex_relative_frobenius_error, "relative_error", ...
        "Five-anchor local Ward diagnostic after correction; bus 9002 has " + ...
        "only four frozen physical incident rows in the fixed topology."));
end
rows = append_table(rows, gate_row(record, "2019_overall", ...
    "all_2019_structural_gates", double(passed), "flag", "==", 1, ...
    passed, true, "Five circuit currents, active loss, and corrected net Q must each be within 15%."));

summary_rows = repmat(summary_template(), 2, 1);
summary_rows(1) = record;
summary_rows(1).scenario_id = "PERFORM_2019_SOURCE";
summary_rows(1).role = "structural_benchmark_source";
summary_rows(2) = record;
summary_rows(2).scenario_id = "S11_2019_REDUCED";
summary_rows(2).role = "structural_benchmark_reduced";
if isstruct(benchmark) && isfield(benchmark, 'source_metrics')
    summary_rows(1).active_loss_mw = ...
        benchmark.source_metrics.active_network_loss_mw;
    summary_rows(1).net_network_q_mvar = ...
        benchmark.source_metrics.net_network_q_mvar;
    summary_rows(1).active_balance_identity_residual_mw = ...
        benchmark.source_metrics.active_identity_residual_mw;
    summary_rows(1).reactive_balance_identity_residual_mvar = ...
        benchmark.source_metrics.reactive_identity_residual_mvar;
    summary_rows(1).standard_pf_success = benchmark.source_pf_success;
    summary_rows(1).q_limit_pf_success = benchmark.source_pf_success;
    summary_rows(1).q_saturation_count = ...
        benchmark.source_q_status.q_saturation_count;
    summary_rows(1).regulating_generator_count = ...
        benchmark.source_q_status.variable_q_generator_count;
    summary_rows(1).q_saturation_percent = ...
        100*benchmark.source_q_status.q_saturation_fraction;
    summary_rows(1).pv_to_pq_conversion_count = ...
        benchmark.source_q_status.pv_to_pq_conversion_count;

    summary_rows(2).active_loss_mw = ...
        benchmark.reduced_metrics.active_network_loss_mw;
    summary_rows(2).net_network_q_mvar = ...
        benchmark.reduced_metrics.net_network_q_mvar;
    summary_rows(2).active_balance_identity_residual_mw = ...
        benchmark.reduced_metrics.active_identity_residual_mw;
    summary_rows(2).reactive_balance_identity_residual_mvar = ...
        benchmark.reduced_metrics.reactive_identity_residual_mvar;
    summary_rows(2).standard_pf_success = benchmark.reduced_pf_success;
    summary_rows(2).q_limit_pf_success = benchmark.reduced_pf_success;
    summary_rows(2).q_saturation_count = ...
        benchmark.reduced_q_status.q_saturation_count;
    summary_rows(2).regulating_generator_count = ...
        benchmark.reduced_q_status.variable_q_generator_count;
    summary_rows(2).q_saturation_percent = ...
        100*benchmark.reduced_q_status.q_saturation_fraction;
    summary_rows(2).pv_to_pq_conversion_count = ...
        benchmark.reduced_q_status.pv_to_pq_conversion_count;
    summary_rows(2).physical_circuit_row_count = ...
        benchmark.structure_validation.physical_circuit_count;
    summary_rows(2).unique_physical_circuit_count = ...
        benchmark.structure_validation.physical_circuit_count;
    if isfield(benchmark, 'correction_ward_audit')
        ward = benchmark.correction_ward_audit;
        summary_rows(2).ward_nonworsening = ward.ward_nonworsening;
        summary_rows(2).baseline_ward_relative_frobenius_error = ...
            ward.baseline_complex_relative_frobenius_error;
        summary_rows(2).corrected_ward_relative_frobenius_error = ...
            ward.corrected_complex_relative_frobenius_error;
    end
end
summary_rows = struct2table(summary_rows);
end

function metrics = network_metrics(result)
define_constants;
[loss, fchg, tchg] = get_losses(result);
online = result.gen(:, GEN_STATUS)>0;
series_p = sum(real(loss));
bus_p = sum(result.bus(:, GS).*result.bus(:, VM).^2);
active_network = series_p + bus_p;
active_balance = sum(result.gen(online, PG))-sum(result.bus(:, PD));
series_q = sum(imag(loss));
charging_q = sum(real(fchg+tchg));
bus_q = sum(result.bus(:, BS).*result.bus(:, VM).^2);
net_q = series_q-charging_q-bus_q;
q_balance = sum(result.gen(online, QG))-sum(result.bus(:, QD));
metrics = struct('active_network_loss_mw', active_network, ...
    'active_identity_residual_mw', active_balance-active_network, ...
    'net_network_q_mvar', net_q, ...
    'reactive_identity_residual_mvar', q_balance-net_q);
end

function row = summary_template()
row = struct( ...
    'scenario_id', "", 'role', "", 'q_multiplier', NaN, ...
    'is_central_q', false, 'is_nominal', false, ...
    'case_status', "not_run", 'build_success', false, ...
    'provenance_complete', false, 'standard_pf_success', false, ...
    'q_limit_pf_success', false, 'closure_converged', false, ...
    'closure_stop_reason', "", 'closure_iteration_count', NaN, ...
    'accepted_step_count', NaN, 'projection_attempted', false, ...
    'projection_success', false, 'bus_count', NaN, 'branch_count', NaN, ...
    'physical_circuit_row_count', NaN, ...
    'unique_physical_circuit_count', NaN, ...
    'one_branch_per_physical_circuit', false, ...
    'total_load_mw', NaN, 'total_generation_mw', NaN, ...
    'internal_generation_mw', NaN, 'external_schedule_mw', NaN, ...
    'active_loss_mw', NaN, 'net_network_q_mvar', NaN, ...
    'active_balance_identity_residual_mw', NaN, ...
    'reactive_balance_identity_residual_mvar', NaN, ...
    'reference_pickup_mw', NaN, 'restoration_slack_mw', NaN, ...
    'restoration_slack_mvar', NaN, 'min_voltage_pu', NaN, ...
    'max_voltage_pu', NaN, 'voltage_violation_count', NaN, ...
    'generator_p_violation_count', NaN, ...
    'generator_q_violation_count', NaN, 'branch_overload_count', NaN, ...
    'max_branch_overload_mva', NaN, ...
    'trusted_static_branch_count', NaN, ...
    'trusted_static_branch_overload_count', NaN, ...
    'trusted_static_max_loading_ratio', NaN, ...
    'legacy_rated_diagnostic_branch_count', NaN, ...
    'legacy_rated_diagnostic_overload_count', NaN, ...
    'legacy_rated_diagnostic_max_loading_ratio', NaN, ...
    'legacy_rated_diagnostic_max_overload_mva', NaN, ...
    'all_rated_branch_count', NaN, ...
    'all_rated_branch_overload_count', NaN, ...
    'all_rated_max_loading_ratio', NaN, ...
    'q_saturation_count', NaN, ...
    'regulating_generator_count', NaN, 'q_saturation_percent', NaN, ...
    'pv_to_pq_conversion_count', NaN, ...
    'regulating_bus_count', NaN, ...
    'unexpected_regulating_bus_count', NaN, ...
    'operational_reference_bus', NaN, ...
    'mapped_operational_reference_bus', NaN, ...
    'mapped_reference_control_match', false, ...
    'placeholder_internal_q_limit_count', NaN, ...
    'unrestricted_external_q_count', NaN, ...
    'maximum_external_q_range_mvar', NaN, ...
    'interface_mae_mw', NaN, 'interface_max_residual_mw', NaN, ...
    'interface_signed_bias_mw', NaN, ...
    'original_dispatch_movement_mw', NaN, ...
    'seed_dispatch_movement_mw', NaN, ...
    'source_prior_dispatch_movement_mw', NaN, ...
    'source_balanced_prior_dispatch_movement_mw', NaN, ...
    'scenario_balanced_prior_dispatch_movement_mw', NaN, ...
    'dispatch_movement_percent_of_load', NaN, ...
    'dispatch_justification', "", ...
    'non_dlr_correction_file', "", ...
    'ward_nonworsening', false, ...
    'baseline_ward_relative_frobenius_error', NaN, ...
    'corrected_ward_relative_frobenius_error', NaN, ...
    'operating_gate_pass', false, 'structural_2019_pass', false, ...
    'included_in_preliminary_model_set', false, ...
    'nominal_promotion_pass', false, ...
    'case_files_written', false, 'input_case_file', "", ...
    'solution_case_file', "", ...
    'exception_identifier', "", 'exception_message', "");
end

function files = output_files(output_dir)
files = struct( ...
    'interface_validation', fullfile(output_dir, ...
        's11_interface_validation.csv'), ...
    'voltage_q_branch_validation', fullfile(output_dir, ...
        's11_voltage_q_branch_validation.csv'), ...
    'branch_current_report', fullfile(output_dir, ...
        's11_branch_current_report.csv'), ...
    'dispatch_and_loss_summary', fullfile(output_dir, ...
        's11_dispatch_and_loss_summary.csv'), ...
    'benchmark_summary', fullfile(output_dir, ...
        's11_2019_same_snapshot_benchmark.csv'));
end

function require_output_directory(output_dir)
if ~isfolder(output_dir)
    error('run_s11_dlr_validation:OutputDirectory', ...
        'Output directory does not exist: %s', output_dir);
end
end

function role = scenario_role(scenario_id)
switch string(scenario_id)
    case "S1_2025_SUMMER_PEAK_PUBLIC"
        role = "summer_peak";
    case "S2_2025_WINTER_PEAK_PUBLIC"
        role = "winter_peak";
    case "S5_2025_HIGH_TOTAL_EAST_PUBLIC"
        role = "high_total_east";
    otherwise
        role = lower(regexprep(string(scenario_id), '[^A-Za-z0-9]+', '_'));
end
end

function value = success_flag(result)
value = isstruct(result) && isfield(result, 'success') && ...
    logical(result.success);
end

function out = append_table(out, rows)
if isempty(rows), return; end
if isempty(out), out = rows; else, out = [out; rows]; end
end

function value = ternary(condition, yes, no)
if condition, value = yes; else, value = no; end
end
