function outputs = run_s4_generation_alignment_diagnostics(options)
%RUN_S4_GENERATION_ALIGNMENT_DIAGNOSTICS Test S4 zonal generation alignment.
%
%   This runner compares S3 and first-pass S4 variants on the public
%   P+Q/public-external scenarios. It is diagnostic, not a final optimizer.

if nargin < 1, options = struct(); end
helper_dir = fileparts(mfilename('fullpath'));
case_dir = fileparts(helper_dir);
addpath(case_dir); addpath(helper_dir);

if ~isfield(options, 'target_file')
    options.target_file = fullfile(helper_dir, 'ny_external_interface_targets.csv');
end
if ~isfield(options, 'interface_target_file')
    options.interface_target_file = fullfile(helper_dir, 'nyiso_public_interface_targets.csv');
end
if ~isfield(options, 'capability_file')
    options.capability_file = fullfile(helper_dir, 'nyiso_generator_capability_targets.csv');
end
if ~isfield(options, 'generation_target_file')
    options.generation_target_file = fullfile(helper_dir, 'nyiso_zonal_generation_targets.csv');
end
if ~isfield(options, 'result_file')
    options.result_file = fullfile(helper_dir, 's4_generation_alignment_results.csv');
end
if ~isfield(options, 'residual_file')
    options.residual_file = fullfile(helper_dir, 's4_generation_alignment_interface_residuals.csv');
end
if ~isfield(options, 'zonal_dispatch_file')
    options.zonal_dispatch_file = fullfile(helper_dir, 's4_zonal_generation_dispatch.csv');
end
if ~isfield(options, 'device_dispatch_file')
    options.device_dispatch_file = fullfile(helper_dir, 's4_equivalent_device_dispatch.csv');
end
if ~isfield(options, 'summary_file')
    options.summary_file = fullfile(helper_dir, 's4_generation_alignment_summary.csv');
end
if ~isfield(options, 'archive_dir')
    options.archive_dir = fullfile(helper_dir, 'archives');
end
if ~isfield(options, 'make_archive'), options.make_archive = true; end

build_s4_generation_alignment_targets(struct( ...
    'capability_file', options.capability_file, ...
    'generation_target_file', options.generation_target_file, ...
    'zone_j_total_pmax_mw', 3000));

public_scenarios = readtable(fullfile(helper_dir, 'nyiso_public_scenarios.csv'), ...
    'TextType', 'string', 'VariableNamingRule', 'preserve');
generation_targets = readtable(options.generation_target_file, ...
    'TextType', 'string', 'VariableNamingRule', 'preserve');
cases = diagnostic_cases();

mpopt = mpoption( ...
    'verbose', 0, ...
    'out.all', 0, ...
    'opf.ac.solver', 'IPOPT', ...
    'opf.flow_lim', 'S', ...
    'opf.violation', 1e-6, ...
    'opf.use_vg', 0, ...
    'opf.ignore_angle_lim', 0);

result_rows = table();
residual_rows = table();
zonal_rows = table();
device_rows = table();

for c = 1:numel(cases)
    spec = cases(c);
    for s = 1:height(public_scenarios)
        scenario_id = string(public_scenarios.scenario_id(s));
        [row, residuals, zonal, devices] = run_one(scenario_id, spec, mpopt, ...
            generation_targets, options);
        result_rows = append_table(result_rows, row);
        residual_rows = append_table(residual_rows, residuals);
        zonal_rows = append_table(zonal_rows, zonal);
        device_rows = append_table(device_rows, devices);
    end
end

summary_rows = summarize_cases(result_rows, zonal_rows);
writetable(result_rows, options.result_file);
writetable(residual_rows, options.residual_file);
writetable(zonal_rows, options.zonal_dispatch_file);
writetable(device_rows, options.device_dispatch_file);
writetable(summary_rows, options.summary_file);

archive_file = "";
if options.make_archive
    if exist(options.archive_dir, 'dir') ~= 7, mkdir(options.archive_dir); end
    stamp = string(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
    archive_file = fullfile(options.archive_dir, ...
        "s4_generation_alignment_results_" + stamp + ".zip");
    files = {options.result_file, options.residual_file, ...
        options.zonal_dispatch_file, options.device_dispatch_file, ...
        options.summary_file, options.capability_file, ...
        options.generation_target_file, ...
        fullfile(helper_dir, 'run_s4_generation_alignment_diagnostics.m'), ...
        fullfile(helper_dir, 'build_s4_generation_alignment_targets.m'), ...
        fullfile(helper_dir, 'add_s4_zonal_capability_equivalents.m'), ...
        fullfile(helper_dir, 'add_zone_j_equivalent_supply.m'), ...
        fullfile(helper_dir, 'add_ny_downstate_delivery_spine.m'), ...
        fullfile(helper_dir, 'scale_ny_downstate_delivery_spine_impedance.m'), ...
        fullfile(helper_dir, 'nyiso_public_scenarios.csv'), ...
        fullfile(helper_dir, 'ny_zonal_load_targets.csv'), ...
        fullfile(helper_dir, 'ny_external_interface_targets.csv'), ...
        fullfile(helper_dir, 'nyiso_public_interface_targets.csv'), ...
        fullfile(case_dir, 'npcc_ny_lite_s4_generation_capability_aligned_uncalibrated.m')};
    files = files(cellfun(@(f) exist(f, 'file') == 2, files));
    zip(archive_file, files);
end

outputs = struct('result_file', options.result_file, ...
    'residual_file', options.residual_file, ...
    'zonal_dispatch_file', options.zonal_dispatch_file, ...
    'device_dispatch_file', options.device_dispatch_file, ...
    'summary_file', options.summary_file, ...
    'capability_file', options.capability_file, ...
    'generation_target_file', options.generation_target_file, ...
    'archive_file', archive_file, ...
    'result_row_count', height(result_rows), ...
    'residual_row_count', height(residual_rows), ...
    'zonal_row_count', height(zonal_rows), ...
    'device_row_count', height(device_rows));
end

function cases = diagnostic_cases()
cases = struct('case_id', {}, 'case_group', {}, 'include_s4', {}, ...
    'apply_abc_caps', {}, 'x_spine_multiplier', {}, ...
    'zone_j_pmax_mw', {}, 'zone_j_cost_c1', {}, 'zone_j_cost_c2', {}, ...
    's4_cost_c1', {}, 's4_cost_c2', {});
cases(end + 1) = make_case("S3_BASE_3GW", "s3_baseline", false, false, 1.00, 3000, 250, 0.02, 180, 0.02);
cases(end + 1) = make_case("S3_BASE_3GW_X0P75", "s3_baseline_x", false, false, 0.75, 3000, 250, 0.02, 180, 0.02);
cases(end + 1) = make_case("S4_EQUIV_ONLY", "s4_equiv_only", true, false, 1.00, 3000, 250, 0.02, 180, 0.02);
cases(end + 1) = make_case("S4_EQUIV_ONLY_X0P75", "s4_equiv_only_x", true, false, 0.75, 3000, 250, 0.02, 180, 0.02);
cases(end + 1) = make_case("S4_EQUIV_ABC_CAPS", "s4_equiv_abc_caps", true, true, 1.00, 3000, 250, 0.02, 180, 0.02);
cases(end + 1) = make_case("S4_EQUIV_ABC_CAPS_X0P75", "s4_equiv_abc_caps_x", true, true, 0.75, 3000, 250, 0.02, 180, 0.02);
end

function spec = make_case(case_id, case_group, include_s4, apply_abc_caps, x_mult, ...
    zone_j_pmax, zone_j_c1, zone_j_c2, s4_c1, s4_c2)
spec = struct('case_id', string(case_id), 'case_group', string(case_group), ...
    'include_s4', include_s4, 'apply_abc_caps', apply_abc_caps, ...
    'x_spine_multiplier', x_mult, 'zone_j_pmax_mw', zone_j_pmax, ...
    'zone_j_cost_c1', zone_j_c1, 'zone_j_cost_c2', zone_j_c2, ...
    's4_cost_c1', s4_c1, 's4_cost_c2', s4_c2);
end

function [row, residual_rows, zonal_rows, device_rows] = run_one(scenario_id, spec, mpopt, generation_targets, options)
define_constants;
status = "ok";
note = "";
try
    base = loadcase('npcc_ny_lite_s1_acopf_feasible_uncalibrated');
    [mpc, ~] = build_ny_only_equivalent_case(base);
    [mpc, ~] = add_ny_downstate_delivery_spine(mpc, 'full');
    [mpc, scale_report] = scale_ny_downstate_delivery_spine_impedance(mpc, ...
        spec.x_spine_multiplier, struct('include_gilboa_leeds', false));
    [mpc, ~] = apply_nyiso_zonal_loads(mpc, scenario_id, 1.0, ...
        struct('preserve_total_ny_load', true));
    [mpc, ext_report] = apply_nyiso_external_interface_injections(mpc, ...
        scenario_id, struct('target_file', options.target_file));
    if spec.include_s4
        [mpc, add_report] = add_s4_zonal_capability_equivalents(mpc, ...
            struct('include_zone_j', true, ...
            'zone_j_total_pmax_mw', spec.zone_j_pmax_mw, ...
            'zone_j_cost_c1', spec.zone_j_cost_c1, ...
            'zone_j_cost_c2', spec.zone_j_cost_c2, ...
            'equiv_cost_c1', spec.s4_cost_c1, ...
            'equiv_cost_c2', spec.s4_cost_c2, ...
            'q_abs_ratio', 0, ...
            'apply_upstate_participation_caps', spec.apply_abc_caps, ...
            'reclassify_ce_ug', true));
    else
        [mpc, add_report] = add_zone_j_equivalent_supply(mpc, ...
            struct('total_pmax_mw', spec.zone_j_pmax_mw, ...
            'q_abs_ratio', 0, ...
            'cost_c1', spec.zone_j_cost_c1, ...
            'cost_c2', spec.zone_j_cost_c2));
    end
    results = runopf(mpc, mpopt);
catch ME
    results = struct();
    scale_report = table();
    ext_report = table();
    add_report = table();
    status = "error";
    note = string(regexprep(ME.message, '\s+', ' '));
end

row = summarize_result(scenario_id, spec, status, note, results, scale_report, ...
    ext_report, add_report, options);
residual_rows = summarize_residuals(scenario_id, spec, status, results, options);
zonal_rows = summarize_zonal_dispatch(scenario_id, spec, status, results, generation_targets);
device_rows = summarize_device_dispatch(scenario_id, spec, status, results);
end

function row = summarize_result(scenario_id, spec, status, note, results, scale_report, ext_report, add_report, options)
define_constants;
names = result_columns();
if strcmp(status, "error") || ~isfield(results, 'bus')
    values = num2cell(NaN(1, numel(names) - 18));
    row = table(spec.case_id, spec.case_group, string(scenario_id), ...
        spec.include_s4, spec.apply_abc_caps, spec.x_spine_multiplier, ...
        spec.zone_j_pmax_mw, spec.zone_j_cost_c1, spec.zone_j_cost_c2, ...
        spec.s4_cost_c1, spec.s4_cost_c2, string(status), string(note), ...
        height(scale_report), height(add_report), ext_sum(ext_report, 'target_flow_mw'), ...
        ext_sum(ext_report, 'target_q_mvar'), values{:}, ...
        'VariableNames', names);
    return;
end
online = results.gen(:, GEN_STATUS) > 0;
sf = sqrt(results.branch(:, PF).^2 + results.branch(:, QF).^2);
st = sqrt(results.branch(:, PT).^2 + results.branch(:, QT).^2);
smax = max(sf, st);
rate = results.branch(:, RATE_A);
rated = rate > 0;
flows = ny_lite_interface_flows(results, ny_lite_interface_definitions(results));
[J, detail] = interface_objective_detail(scenario_id, results, options);
res = residual_map(detail);
[zj_pg, zj_pmax] = named_device_sums(results, 'zone_j');
[s4_pg, s4_pmax] = named_device_sums(results, 's4');
row = table(spec.case_id, spec.case_group, string(scenario_id), ...
    spec.include_s4, spec.apply_abc_caps, spec.x_spine_multiplier, ...
    spec.zone_j_pmax_mw, spec.zone_j_cost_c1, spec.zone_j_cost_c2, ...
    spec.s4_cost_c1, spec.s4_cost_c2, string(status), string(note), ...
    height(scale_report), height(add_report), ext_sum(ext_report, 'target_flow_mw'), ...
    ext_sum(ext_report, 'target_q_mvar'), double(results.success), raw_info(results), ...
    results.f, J, max(abs(detail.residual_mw), [], 'omitnan'), ...
    mean(abs(detail.residual_mw), 'omitnan'), size(results.bus, 1), ...
    size(results.branch, 1), size(results.gen, 1), sum(results.bus(:, PD)), ...
    sum(results.bus(:, QD)), sum(results.gen(online, PG)), sum(results.gen(online, QG)), ...
    zj_pg, zj_pmax, safe_div(zj_pg, zj_pmax), s4_pg, s4_pmax, safe_div(s4_pg, s4_pmax), ...
    min(results.bus(:, VM)), max(results.bus(:, VM)), ...
    sum(results.bus(:, VM) >= results.bus(:, VMAX) - 1e-5), ...
    sum(results.bus(:, VM) <= results.bus(:, VMIN) + 1e-5), ...
    sum(rated & smax > rate + 1e-6), max([0; smax(rated) - rate(rated)]), ...
    res.central_east, res.total_east, res.upny_coned, res.dunwoodie_south, ...
    res.moses_south, interface_flow(flows, 'Total_East_proxy'), ...
    interface_flow(flows, 'UPNY_ConEd'), interface_flow(flows, 'Dunwoodie_South'), ...
    'VariableNames', names);
end

function names = result_columns()
names = {'case_id','case_group','scenario_id','include_s4','apply_abc_caps', ...
    'x_spine_multiplier','zone_j_total_pmax_mw','zone_j_cost_c1', ...
    'zone_j_cost_c2','s4_equiv_cost_c1','s4_equiv_cost_c2', ...
    'status','note','scaled_branch_count','added_device_count', ...
    'boundary_target_p_mw','boundary_target_q_mvar','opf_success', ...
    'opf_raw_info','objective','interface_objective', ...
    'max_abs_interface_residual_mw','mean_abs_interface_residual_mw', ...
    'bus_count','branch_count','gen_count','total_pd_mw','total_qd_mvar', ...
    'total_pg_mw','total_qg_mvar','zone_j_equiv_pg_mw', ...
    'zone_j_equiv_pmax_mw','zone_j_fraction_pmax_used', ...
    's4_equiv_pg_mw','s4_equiv_pmax_mw','s4_fraction_pmax_used', ...
    'min_voltage','max_voltage','voltage_bound_count_high', ...
    'voltage_bound_count_low','branch_overload_count','max_branch_overload_mva', ...
    'central_east_residual_mw','total_east_residual_mw', ...
    'upny_coned_residual_mw','dunwoodie_south_residual_mw', ...
    'moses_south_residual_mw','total_east_proxy_flow_mw', ...
    'upny_coned_flow_mw','dunwoodie_south_flow_mw'};
end

function residual_rows = summarize_residuals(scenario_id, spec, status, results, options)
residual_rows = table();
if strcmp(status, "error") || ~isfield(results, 'branch'), return; end
[J, detail] = interface_objective_detail(scenario_id, results, options);
for k = 1:height(detail)
    row = table(spec.case_id, spec.case_group, string(scenario_id), ...
        spec.include_s4, spec.apply_abc_caps, spec.x_spine_multiplier, ...
        detail.interface_name(k), detail.lite_flow_mw(k), ...
        detail.target_flow_mw(k), detail.residual_mw(k), detail.scale_mw(k), ...
        detail.objective_term(k), J, ...
        'VariableNames', {'case_id','case_group','scenario_id','include_s4', ...
        'apply_abc_caps','x_spine_multiplier','interface_name','lite_flow_mw', ...
        'target_flow_mw','residual_mw','scale_mw','objective_term', ...
        'interface_objective_total'});
    residual_rows = append_table(residual_rows, row);
end
end

function zonal_rows = summarize_zonal_dispatch(scenario_id, spec, status, results, generation_targets)
zonal_rows = table();
if strcmp(status, "error") || ~isfield(results, 'bus'), return; end
define_constants;
results = attach_nyiso_zone_metadata(results);
zones = ["A","B","C","D","E","F","G","H","I","J","K"];
boundary_idx = excluded_boundary_generator_indices(results);
s4_idx = s4_generator_indices(results);
zj_idx = zone_j_generator_indices(results);
for z = zones
    bus_ids = zone_bus_ids(results, z);
    gen_idx = find(ismember(results.gen(:, GEN_BUS), bus_ids) & results.gen(:, GEN_STATUS) > 0);
    local_idx = setdiff(gen_idx, boundary_idx);
    load_mw = sum(results.bus(ismember(results.bus(:, BUS_I), bus_ids), PD));
    qload_mvar = sum(results.bus(ismember(results.bus(:, BUS_I), bus_ids), QD));
    all_pg = sum(results.gen(gen_idx, PG));
    local_pg = sum(results.gen(local_idx, PG));
    pmax = sum(results.gen(local_idx, PMAX));
    boundary_pg = sum(results.gen(intersect(gen_idx, boundary_idx), PG));
    s4_pg = sum(results.gen(intersect(gen_idx, s4_idx), PG));
    zj_pg = sum(results.gen(intersect(gen_idx, zj_idx), PG));
    target = generation_targets(generation_targets.scenario_id == string(scenario_id) & ...
        generation_targets.zone == z, :);
    if height(target) == 0
        target_load = NaN; target_export = NaN; target_gen = NaN; prior = NaN;
    else
        target_load = target.target_load_mw(1);
        target_export = target.target_net_export_mw(1);
        target_gen = target.target_generation_mw(1);
        prior = target.generation_prior_mw(1);
    end
    row = table(spec.case_id, spec.case_group, string(scenario_id), ...
        spec.include_s4, spec.apply_abc_caps, spec.x_spine_multiplier, z, ...
        load_mw, qload_mvar, all_pg, local_pg, boundary_pg, s4_pg, zj_pg, ...
        pmax, local_pg - load_mw, target_load, target_export, target_gen, ...
        prior, local_pg - target_gen, ...
        'VariableNames', {'case_id','case_group','scenario_id','include_s4', ...
        'apply_abc_caps','x_spine_multiplier','zone','load_mw','qload_mvar', ...
        'total_pg_mw','local_pg_excluding_boundary_mw','boundary_equiv_pg_mw', ...
        's4_equiv_pg_mw','zone_j_equiv_pg_mw','local_pmax_excluding_boundary_mw', ...
        'local_net_injection_mw','target_load_mw','target_net_export_mw', ...
        'target_generation_mw','generation_prior_mw','local_generation_residual_mw'});
    zonal_rows = append_table(zonal_rows, row);
end
end

function device_rows = summarize_device_dispatch(scenario_id, spec, status, results)
device_rows = table();
if strcmp(status, "error") || ~isfield(results, 'gen'), return; end
define_constants;
zone_j_devices = device_structs(results, 'zone_j');
s4_devices = device_structs(results, 's4');
devices = [zone_j_devices(:); s4_devices(:)];
for k = 1:numel(devices)
    gi = devices(k).gen_index;
    if gi < 1 || gi > size(results.gen, 1), continue; end
    row = table(spec.case_id, spec.case_group, string(scenario_id), ...
        spec.include_s4, spec.apply_abc_caps, spec.x_spine_multiplier, ...
        string(devices(k).device_group), string(devices(k).name), ...
        string(devices(k).zone), devices(k).bus_id, string(devices(k).bus_name), ...
        gi, results.gen(gi, PG), results.gen(gi, QG), results.gen(gi, PMAX), ...
        results.gen(gi, PMIN), results.gen(gi, QMAX), results.gen(gi, QMIN), ...
        safe_div(results.gen(gi, PG), results.gen(gi, PMAX)), ...
        'VariableNames', {'case_id','case_group','scenario_id','include_s4', ...
        'apply_abc_caps','x_spine_multiplier','device_group','device_name', ...
        'zone','bus_id','bus_name','gen_index','pg_mw','qg_mvar','pmax_mw', ...
        'pmin_mw','qmax_mvar','qmin_mvar','fraction_pmax_used'});
    device_rows = append_table(device_rows, row);
end
end

function summary = summarize_cases(rows, zonal_rows)
keys = unique(rows(:, {'case_id','case_group','include_s4','apply_abc_caps', ...
    'x_spine_multiplier','zone_j_total_pmax_mw','zone_j_cost_c1', ...
    'zone_j_cost_c2','s4_equiv_cost_c1','s4_equiv_cost_c2'}), 'rows');
summary = table();
for k = 1:height(keys)
    mask = rows.case_id == keys.case_id(k);
    subset = rows(mask, :);
    zmask = zonal_rows.case_id == keys.case_id(k);
    zsub = zonal_rows(zmask, :);
    downstate = ismember(zsub.zone, ["G", "J", "K"]);
    row = table(keys.case_id(k), keys.case_group(k), keys.include_s4(k), ...
        keys.apply_abc_caps(k), keys.x_spine_multiplier(k), ...
        height(subset), sum(subset.opf_success == 1), ...
        sum(subset.interface_objective, 'omitnan'), ...
        mean(subset.interface_objective, 'omitnan'), ...
        max(subset.max_abs_interface_residual_mw, [], 'omitnan'), ...
        mean(subset.zone_j_equiv_pg_mw, 'omitnan'), ...
        max(subset.zone_j_equiv_pg_mw, [], 'omitnan'), ...
        mean(subset.s4_equiv_pg_mw, 'omitnan'), ...
        max(subset.s4_equiv_pg_mw, [], 'omitnan'), ...
        mean(abs(zsub.local_generation_residual_mw), 'omitnan'), ...
        mean(abs(zsub.local_generation_residual_mw(downstate)), 'omitnan'), ...
        max(subset.branch_overload_count, [], 'omitnan'), ...
        max(subset.voltage_bound_count_high + subset.voltage_bound_count_low, [], 'omitnan'), ...
        'VariableNames', {'case_id','case_group','include_s4','apply_abc_caps', ...
        'x_spine_multiplier','scenario_count','success_count', ...
        'sum_interface_objective','mean_interface_objective', ...
        'max_abs_interface_residual_mw','mean_zone_j_equiv_pg_mw', ...
        'max_zone_j_equiv_pg_mw','mean_s4_equiv_pg_mw', ...
        'max_s4_equiv_pg_mw','mean_abs_zonal_generation_residual_mw', ...
        'mean_abs_downstate_generation_residual_mw','max_branch_overload_count', ...
        'max_voltage_bound_count'});
    summary = append_table(summary, row);
end
end

function [J, detail] = interface_objective_detail(scenario_id, results, options)
targets = read_public_interface_targets(scenario_id, options.interface_target_file);
flows = ny_lite_interface_flows(results, ny_lite_interface_definitions(results));
[J, detail] = interface_target_objective(flows, targets);
end

function out = residual_map(detail)
out = struct('central_east', NaN, 'total_east', NaN, 'upny_coned', NaN, ...
    'dunwoodie_south', NaN, 'moses_south', NaN);
for k = 1:height(detail)
    name = string(detail.interface_name(k));
    switch name
        case "Central_East"
            out.central_east = detail.residual_mw(k);
        case "Total_East_proxy"
            out.total_east = detail.residual_mw(k);
        case "UPNY_ConEd"
            out.upny_coned = detail.residual_mw(k);
        case "Dunwoodie_South"
            out.dunwoodie_south = detail.residual_mw(k);
        case "Moses_South"
            out.moses_south = detail.residual_mw(k);
    end
end
end

function devices = device_structs(results, group)
devices = struct('device_group', {}, 'name', {}, 'zone', {}, 'bus_id', {}, ...
    'bus_name', {}, 'gen_index', {});
if ~isfield(results, 'userdata') || ~isfield(results.userdata, 'ny_lite'), return; end
if strcmp(group, 'zone_j')
    field = 'zone_j_equivalent_supply';
    device_group = 'zone_j_equivalent';
else
    field = 's4_zonal_capability_equivalents';
    device_group = 's4_zonal_capability_equivalent';
end
if ~isfield(results.userdata.ny_lite, field), return; end
src = results.userdata.ny_lite.(field);
for k = 1:numel(src)
    devices(end + 1) = struct('device_group', device_group, ...
        'name', src(k).name, 'zone', src(k).zone, 'bus_id', src(k).bus_id, ...
        'bus_name', src(k).bus_name, 'gen_index', src(k).gen_index); %#ok<AGROW>
end
end

function idx = zone_j_generator_indices(results)
idx = [];
if isfield(results, 'userdata') && isfield(results.userdata, 'ny_lite') && ...
        isfield(results.userdata.ny_lite, 'zone_j_equivalent_supply')
    d = results.userdata.ny_lite.zone_j_equivalent_supply;
    if ~isempty(d), idx = [d.gen_index]; end
end
idx = idx(:);
end

function idx = s4_generator_indices(results)
idx = [];
if isfield(results, 'userdata') && isfield(results.userdata, 'ny_lite') && ...
        isfield(results.userdata.ny_lite, 's4_zonal_capability_equivalents')
    d = results.userdata.ny_lite.s4_zonal_capability_equivalents;
    if ~isempty(d), idx = [d.gen_index]; end
end
idx = idx(:);
end

function idx = excluded_boundary_generator_indices(results)
idx = [];
if isfield(results, 'userdata') && isfield(results.userdata, 'ny_only_equivalent') && ...
        isfield(results.userdata.ny_only_equivalent, 'external_equivalent_generators')
    tbl = results.userdata.ny_only_equivalent.external_equivalent_generators;
    if istable(tbl) && ismember('added_gen_index', tbl.Properties.VariableNames)
        idx = tbl.added_gen_index(:);
    end
end
end

function [pg, pmax] = named_device_sums(results, group)
define_constants;
if strcmp(group, 'zone_j')
    idx = zone_j_generator_indices(results);
else
    idx = s4_generator_indices(results);
end
idx = idx(idx >= 1 & idx <= size(results.gen, 1));
pg = sum(results.gen(idx, PG));
pmax = sum(results.gen(idx, PMAX));
end

function bus_ids = zone_bus_ids(results, zone)
bus_ids = [];
for i = 1:size(results.bus, 1)
    if isfield(results.userdata, 'nyiso_physical_zone') && ...
            numel(results.userdata.nyiso_physical_zone) >= i && ...
            strcmp(string(results.userdata.nyiso_physical_zone{i}), string(zone))
        bus_ids(end + 1) = results.bus(i, 1); %#ok<AGROW>
    end
end
end

function value = ext_sum(tbl, name)
if istable(tbl) && ismember(name, tbl.Properties.VariableNames)
    value = sum(tbl.(name));
else
    value = NaN;
end
end

function info = raw_info(results)
if isfield(results, 'raw') && isfield(results.raw, 'info')
    info = results.raw.info;
else
    info = NaN;
end
end

function value = interface_flow(flows, name)
idx = find(strcmp({flows.interface_name}, name), 1);
if isempty(idx), value = NaN; else, value = flows(idx).flow_mw; end
end

function value = safe_div(num, den)
if den == 0
    value = NaN;
else
    value = num / den;
end
end

function out = append_table(out, row)
if isempty(row), return; end
if isempty(out)
    out = row;
else
    out = [out; row]; %#ok<AGROW>
end
end
