function out = run_s13_phase1b_local_identity(options)
%RUN_S13_PHASE1B_LOCAL_IDENTITY Validate the exact Phase 1B local overlays.
%   This no-fit test solves two Phase 1B subnetworks independently. The
%   Q-limit-solved full PERFORM case supplies fixed boundary phasors and
%   fixed complex-power injections derived from each omitted network. A
%   zero-injection truncation is retained as a diagnostic only.

if nargin < 1, options = struct(); end

helper_dir = fileparts(mfilename('fullpath'));
case_dir = fileparts(helper_dir);
root = fileparts(case_dir);
perform_dir = fullfile(root, 'PERFORM', ...
    'On Peak 2019 v23_Perform_NY', 'On Peak 2019 v23');
options = defaults(options, helper_dir, perform_dir);
addpath(case_dir); addpath(helper_dir); addpath(perform_dir);
define_constants;

candidate = load_candidate(options.s13_case);
[phase1a_report, phase1b_report, cumulative_report] = ...
    phase_reports(candidate);
[phase1a_report_exact, phase1a_rows_exact] = ...
    assert_phase1a_immutable(candidate, phase1a_report);
candidate_fail_closed = fail_closed_status(candidate, phase1b_report);
if ~candidate_fail_closed
    error('run_s13_phase1b_local_identity:PromotionStatus', ...
        'The cumulative S13 candidate or Phase 1B report is not fail-closed.');
end

paths = path_specifications();
[physical_by_path, physical] = select_phase1b_physical( ...
    phase1b_report.physical_register, paths);

source_case = loadcase(options.source_case);
source_results = runpf(source_case, mpoption( ...
    'verbose', 0, 'out.all', 0, 'pf.enforce_q_lims', 1));
if ~source_results.success
    error('run_s13_phase1b_local_identity:SourcePF', ...
        'The full PERFORM Q-limit source power flow did not converge.');
end
source_phasors = evaluate_network_phasors(source_results);

source_rows = double(physical.source_branch_row);
source_from = double(physical.source_from_bus);
source_to = double(physical.source_to_bus);
model_rows = double(physical.model_branch_row);
model_from = double(physical.model_from_bus);
model_to = double(physical.model_to_bus);
assert_branch_mapping(source_results, candidate, source_rows, source_from, ...
    source_to, model_rows, model_from, model_to);
[raw_branch_row, raw_circuit_id] = raw_branch_identity( ...
    options.raw_file, source_results, source_rows);

identity = table();
omitted = table();
voltages = table();
path_results = repmat(struct( ...
    'overlay_path_id', "", ...
    'injection_results', struct(), ...
    'zero_injection_results', struct()), numel(paths), 1);
row_offset = 0;
for p = 1:numel(paths)
    spec = paths(p);
    physical_part = physical_by_path{p};
    local_bus = [spec.boundary_bus; spec.interior_bus];

    [omitted_part, equivalent_injection] = omitted_injection_table( ...
        source_results, source_phasors, spec.interior_bus, local_bus, ...
        spec.source_rows, spec.overlay_path_id);
    injection_case = build_local_case(source_results, local_bus, ...
        spec.boundary_bus, spec.interior_bus, spec.source_rows, ...
        equivalent_injection);
    injection_results = runpf(injection_case, mpoption( ...
        'verbose', 0, 'out.all', 0, 'pf.enforce_q_lims', 0));

    zero_case = build_local_case(source_results, local_bus, ...
        spec.boundary_bus, spec.interior_bus, spec.source_rows, ...
        zeros(numel(spec.interior_bus), 1));
    zero_results = runpf(zero_case, mpoption( ...
        'verbose', 0, 'out.all', 0, 'pf.enforce_q_lims', 0));

    rows = row_offset + (1:numel(spec.source_rows));
    identity_part = branch_identity_table(source_results, source_phasors, ...
        injection_results, zero_results, physical_part, ...
        raw_branch_row(rows), raw_circuit_id(rows), candidate, ...
        spec.overlay_path_id);
    voltage_part = voltage_table(source_results, injection_results, ...
        zero_results, candidate, cumulative_report.bus_map, local_bus, ...
        spec.boundary_bus, spec.overlay_path_id);
    if p == 1
        identity = identity_part;
        omitted = omitted_part;
        voltages = voltage_part;
    else
        identity = [identity; identity_part]; %#ok<AGROW>
        omitted = [omitted; omitted_part]; %#ok<AGROW>
        voltages = [voltages; voltage_part]; %#ok<AGROW>
    end
    path_results(p).overlay_path_id = spec.overlay_path_id;
    path_results(p).injection_results = injection_results;
    path_results(p).zero_injection_results = zero_results;
    row_offset = row_offset + numel(spec.source_rows);
end

[operator_validation, operator_status] = ...
    optional_operator_validation(candidate);
gates = gate_ledger(source_results, path_results, identity, omitted, ...
    voltages, phase1a_report_exact, phase1a_rows_exact, ...
    candidate_fail_closed, operator_status);
all_mandatory_pass = all(gates.pass(gates.mandatory));

files = struct( ...
    'local_identity', fullfile(options.output_dir, ...
        's13_phase1b_local_identity.csv'), ...
    'omitted_injections', fullfile(options.output_dir, ...
        's13_phase1b_local_omitted_injections.csv'), ...
    'terminal_voltages', fullfile(options.output_dir, ...
        's13_phase1b_terminal_voltage_comparison.csv'), ...
    'gate_ledger', fullfile(options.output_dir, ...
        's13_phase1b_gate_ledger.csv'));
if options.write_outputs
    if ~isfolder(options.output_dir)
        error('run_s13_phase1b_local_identity:OutputDirectory', ...
            'Output directory does not exist: %s', options.output_dir);
    end
    ny_lite_writetable_lf(identity, files.local_identity);
    ny_lite_writetable_lf(omitted, files.omitted_injections);
    ny_lite_writetable_lf(voltages, files.terminal_voltages);
    ny_lite_writetable_lf(gates, files.gate_ledger);
end

out = struct( ...
    'pass', all_mandatory_pass, ...
    'source_results', source_results, ...
    'path_results', path_results, ...
    'local_identity', identity, ...
    'omitted_injections', omitted, ...
    'terminal_voltages', voltages, ...
    'gate_ledger', gates, ...
    'phase1a_report_exact_match', phase1a_report_exact, ...
    'phase1a_physical_rows_bit_identical', phase1a_rows_exact, ...
    'candidate_fail_closed', candidate_fail_closed, ...
    'operator_validator_available', operator_status.available, ...
    'operator_mandatory_proxy_pass', operator_status.proxy_pass, ...
    'operator_validation', operator_validation, ...
    'zero_injection_is_gating', false, ...
    'residual_fit_performed', false, ...
    'promotion_performed', false, ...
    'files', files);

if options.verbose
    fprintf(['S13 Phase 1B local identity: %d/%d mandatory gates pass; ' ...
        'direct max P/Q %.3g/%.3g; local max P/Q %.3g/%.3g; ' ...
        'VM/VA %.3g/%.3g.\n'], nnz(gates.pass(gates.mandatory)), ...
        nnz(gates.mandatory), max(identity.direct_max_p_error_mw), ...
        max(identity.direct_max_q_error_mvar), ...
        max(identity.injection_max_p_error_mw), ...
        max(identity.injection_max_q_error_mvar), ...
        max(voltages.injection_vm_error_pu(voltages.terminal_role == ...
            "interior_pq")), ...
        max(voltages.injection_va_error_deg(voltages.terminal_role == ...
            "interior_pq")));
    fprintf(['  Zero-injection truncations are diagnostic only: max ' ...
        'VM/VA errors %.4g pu / %.4g deg.\n'], ...
        max(voltages.zero_injection_vm_error_pu), ...
        max(voltages.zero_injection_va_error_deg));
end

if options.fail_on_gate && ~all_mandatory_pass
    failed = gates.gate_id(gates.mandatory & ~gates.pass);
    error('run_s13_phase1b_local_identity:GateFailure', ...
        'Mandatory Phase 1B local-identity gates failed: %s', ...
        strjoin(cellstr(failed), ', '));
end
end

function options = defaults(options, helper_dir, perform_dir)
if ~isfield(options, 'write_outputs'), options.write_outputs = true; end
if ~isfield(options, 'fail_on_gate'), options.fail_on_gate = true; end
if ~isfield(options, 'verbose'), options.verbose = true; end
if ~isfield(options, 'output_dir'), options.output_dir = helper_dir; end
if ~isfield(options, 's13_case')
    options.s13_case = 'npcc_ny_lite_s13_npcc_augmented_2019';
end
if ~isfield(options, 'source_case')
    options.source_case = 'nyiso_On_Peak_v23_shunts_as_z_load';
end
if ~isfield(options, 'raw_file')
    options.raw_file = fullfile(perform_dir, ...
        'NYISO_onpeak2019_v23_shuntsRgens.RAW');
end
end

function candidate = load_candidate(case_spec)
if isstruct(case_spec)
    candidate = case_spec;
else
    candidate = loadcase(case_spec);
end
end

function [phase1a, phase1b, cumulative] = phase_reports(candidate)
if ~isfield(candidate, 'userdata') || ~isfield(candidate.userdata, 's13') || ...
        ~isstruct(candidate.userdata.s13) || ...
        ~isscalar(candidate.userdata.s13)
    error('run_s13_phase1b_local_identity:MissingS13Metadata', ...
        'The candidate does not contain scalar S13 metadata.');
end
s13 = candidate.userdata.s13;
if ~isfield(s13, 'phase_reports') || ~isstruct(s13.phase_reports) || ...
        ~isscalar(s13.phase_reports) || ...
        ~all(isfield(s13.phase_reports, {'phase1a','phase1b'}))
    error('run_s13_phase1b_local_identity:MissingPhaseReports', ...
        'The cumulative candidate must contain Phase 1A and Phase 1B reports.');
end
phase1a = s13.phase_reports.phase1a;
phase1b = s13.phase_reports.phase1b;
required = {'phase_id','physical_register','bus_map', ...
    'construction_source_qualified','promotion_eligible'};
if ~isstruct(phase1b) || ~isscalar(phase1b) || ...
        ~all(isfield(phase1b, required)) || ...
        string(phase1b.phase_id) ~= "phase1b" || ...
        ~istable(phase1b.physical_register) || ~istable(phase1b.bus_map)
    error('run_s13_phase1b_local_identity:InvalidPhase1BReport', ...
        'The Phase 1B report is incomplete or has the wrong phase identity.');
end
if ~isfield(s13, 'overlay_report') || ~isstruct(s13.overlay_report) || ...
        ~isscalar(s13.overlay_report) || ...
        ~isfield(s13.overlay_report, 'bus_map') || ...
        ~istable(s13.overlay_report.bus_map)
    error('run_s13_phase1b_local_identity:CumulativeBusMap', ...
        'The cumulative overlay bus map is required for reused terminals.');
end
cumulative = s13.overlay_report;
end

function [report_exact, rows_exact] = ...
        assert_phase1a_immutable(candidate, candidate_report)
checkpoint = build_s13_phase1a_candidate(struct( ...
    'write_outputs', false, 'verbose', false));
fresh = checkpoint.candidate;
fresh_report = checkpoint.phase_reports.phase1a;
report_exact = isequaln(candidate_report, fresh_report);
if ~report_exact
    error('run_s13_phase1b_local_identity:Phase1AReportChanged', ...
        'The cumulative candidate Phase 1A report differs from a fresh checkpoint.');
end
rows = double(fresh_report.physical_register.model_branch_row);
rows_exact = isequal(candidate_report.physical_register.model_branch_row, ...
    fresh_report.physical_register.model_branch_row) && ...
    size(candidate.branch, 1) >= max(rows) && ...
    size(candidate.branch, 2) >= size(fresh.branch, 2) && ...
    isequaln(candidate.branch(rows, 1:size(fresh.branch, 2)), ...
        fresh.branch(rows, :));
if ~rows_exact
    error('run_s13_phase1b_local_identity:Phase1APhysicalRowsChanged', ...
        'One or more immutable Phase 1A physical branch rows changed.');
end
end

function pass = fail_closed_status(candidate, phase1b)
s13 = candidate.userdata.s13;
pass = is_false_scalar(s13, 'construction_source_qualified') && ...
    is_false_scalar(s13, 'promotion_eligible') && ...
    is_false_scalar(phase1b, 'construction_source_qualified') && ...
    is_false_scalar(phase1b, 'promotion_eligible');
end

function pass = is_false_scalar(value, field)
pass = isfield(value, field) && isscalar(value.(field)) && ...
    (islogical(value.(field)) || isnumeric(value.(field))) && ...
    isfinite(double(value.(field))) && ~logical(value.(field));
end

function paths = path_specifications()
paths = struct( ...
    'overlay_path_id', {"phase1b_pv_wood_mesh", ...
        "phase1b_ramapo_buchanan_path"}, ...
    'boundary_bus', {[651; 902], [1519; 900]}, ...
    'interior_bus', {858, 774}, ...
    'source_rows', {[1389; 1390; 1391; 1392; 1689; 1690], ...
        [1577; 1576; 1738]});
end

function [parts, combined] = select_phase1b_physical(physical, paths)
required = {'overlay_path_id','source_branch_row','source_from_bus', ...
    'source_to_bus','source_circuit_id','model_branch_row', ...
    'model_from_bus','model_to_bus'};
if ~istable(physical) || ~all(ismember(required, ...
        physical.Properties.VariableNames))
    error('run_s13_phase1b_local_identity:PhysicalRegister', ...
        'The Phase 1B physical register has an invalid schema.');
end
parts = cell(numel(paths), 1);
expected_total = 0;
for p = 1:numel(paths)
    spec = paths(p);
    selected = zeros(numel(spec.source_rows), 1);
    for k = 1:numel(spec.source_rows)
        found = find(string(physical.overlay_path_id) == ...
            spec.overlay_path_id & double(physical.source_branch_row) == ...
            spec.source_rows(k));
        if numel(found) ~= 1
            error('run_s13_phase1b_local_identity:PhysicalRowIdentity', ...
                'Path %s source row %d appears %d times; expected one.', ...
                spec.overlay_path_id, spec.source_rows(k), numel(found));
        end
        selected(k) = found;
    end
    parts{p} = physical(selected, :);
    expected_total = expected_total + numel(spec.source_rows);
end
combined = vertcat(parts{:});
if height(physical) ~= expected_total || ...
        numel(unique(double(combined.model_branch_row))) ~= expected_total
    error('run_s13_phase1b_local_identity:PhysicalRowSet', ...
        'The Phase 1B report must contain exactly the nine specified rows.');
end
end

function assert_branch_mapping(source, candidate, source_rows, source_from, ...
        source_to, model_rows, model_from, model_to)
define_constants;
if any(source_rows < 1 | source_rows > size(source.branch, 1)) || ...
        any(model_rows < 1 | model_rows > size(candidate.branch, 1))
    error('run_s13_phase1b_local_identity:BranchRowRange', ...
        'A registered source or S13 branch row is out of range.');
end
if ~isequal(source.branch(source_rows, [F_BUS T_BUS]), ...
        [source_from source_to]) || ...
        ~isequal(candidate.branch(model_rows, [F_BUS T_BUS]), ...
        [model_from model_to])
    error('run_s13_phase1b_local_identity:BranchEndpoint', ...
        'A registered source or S13 branch endpoint changed.');
end
cols = [BR_R BR_X BR_B RATE_A RATE_B RATE_C TAP SHIFT BR_STATUS];
if ~isequaln(candidate.branch(model_rows, cols), ...
        source.branch(source_rows, cols))
    error('run_s13_phase1b_local_identity:BranchParameterControl', ...
        'A Phase 1B physical branch parameter or control differs from source.');
end
end

function q = evaluate_network_phasors(results)
define_constants;
internal = ext2int(results);
[~, Yf, Yt] = makeYbus(internal.baseMVA, internal.bus, internal.branch);
V = internal.bus(:, VM) .* exp(1j * pi/180 * internal.bus(:, VA));
If = Yf * V;
It = Yt * V;
Sf = V(internal.branch(:, F_BUS)) .* conj(If) * internal.baseMVA;
St = V(internal.branch(:, T_BUS)) .* conj(It) * internal.baseMVA;
on = internal.order.branch.status.on(:);
nl = size(results.branch, 1);
q.If = complex(zeros(nl, 1));
q.It = complex(zeros(nl, 1));
q.Sf = complex(zeros(nl, 1));
q.St = complex(zeros(nl, 1));
q.If(on) = If; q.It(on) = It; q.Sf(on) = Sf; q.St(on) = St;
end

function [rows, Seq] = omitted_injection_table(results, phasors, ...
        interior_bus, local_bus, retained_rows, path_id)
define_constants;
n = numel(interior_bus);
overlay_path_id = repmat(path_id, n, 1);
source_bus_name = strings(n, 1);
source_vm_pu = zeros(n, 1); source_va_deg = zeros(n, 1);
source_pd_mw = zeros(n, 1); source_qd_mvar = zeros(n, 1);
source_gs_mw = zeros(n, 1); source_bs_mvar = zeros(n, 1);
online_generator_count = zeros(n, 1);
retained_incident_count = zeros(n, 1);
omitted_incident_count = zeros(n, 1);
omitted_branch_rows = strings(n, 1);
unregistered_local_branch_count = zeros(n, 1);
retained_I = complex(zeros(n, 1));
omitted_I = complex(zeros(n, 1));
Seq = complex(zeros(n, 1));
retained_S = complex(zeros(n, 1));
source_zero_device_pass = false(n, 1);
partition_pass = false(n, 1);

for k = 1:n
    id = interior_bus(k);
    bi = find(results.bus(:, BUS_I) == id, 1);
    if isempty(bi)
        error('run_s13_phase1b_local_identity:InteriorBus', ...
            'Source interior bus %d is missing.', id);
    end
    source_bus_name(k) = bus_name(results, bi);
    source_vm_pu(k) = results.bus(bi, VM);
    source_va_deg(k) = results.bus(bi, VA);
    source_pd_mw(k) = results.bus(bi, PD);
    source_qd_mvar(k) = results.bus(bi, QD);
    source_gs_mw(k) = results.bus(bi, GS);
    source_bs_mvar(k) = results.bus(bi, BS);
    online_generator_count(k) = nnz(results.gen(:, GEN_BUS) == id & ...
        results.gen(:, GEN_STATUS) > 0);
    source_zero_device_pass(k) = ...
        all(abs(results.bus(bi, [PD QD GS BS])) <= 1e-10) && ...
        online_generator_count(k) == 0;

    incident = find(results.branch(:, BR_STATUS) > 0 & ...
        (results.branch(:, F_BUS) == id | results.branch(:, T_BUS) == id));
    retained = incident(ismember(incident, retained_rows));
    omitted_rows = incident(~ismember(incident, retained_rows));
    retained_incident_count(k) = numel(retained);
    omitted_incident_count(k) = numel(omitted_rows);
    omitted_branch_rows(k) = join(string(omitted_rows(:)'), ';');
    both_local = ismember(results.branch(omitted_rows, F_BUS), local_bus) & ...
        ismember(results.branch(omitted_rows, T_BUS), local_bus);
    unregistered_local_branch_count(k) = nnz(both_local);
    partition_pass(k) = ~isempty(retained) && ~isempty(omitted_rows) && ...
        unregistered_local_branch_count(k) == 0;

    retained_I(k) = bus_terminal_current(results, phasors, retained, id);
    omitted_I(k) = bus_terminal_current(results, phasors, omitted_rows, id);
    voltage = results.bus(bi, VM) * ...
        exp(1j*pi/180*results.bus(bi, VA));
    Seq(k) = voltage * conj(-omitted_I(k)) * results.baseMVA;
    retained_S(k) = voltage * conj(retained_I(k)) * results.baseMVA;
end

kcl = retained_I + omitted_I;
rows = table(overlay_path_id, interior_bus, source_bus_name, source_vm_pu, ...
    source_va_deg, source_pd_mw, source_qd_mvar, source_gs_mw, ...
    source_bs_mvar, online_generator_count, retained_incident_count, ...
    omitted_incident_count, omitted_branch_rows, ...
    unregistered_local_branch_count, real(retained_I), imag(retained_I), ...
    real(omitted_I), imag(omitted_I), real(-omitted_I), imag(-omitted_I), ...
    real(Seq), imag(Seq), real(retained_S), imag(retained_S), abs(kcl), ...
    abs(retained_S - Seq), source_zero_device_pass, partition_pass, ...
    repmat("source_derived_fixed_complex_power", n, 1), ...
    'VariableNames', {'overlay_path_id','source_bus','source_bus_name', ...
    'source_vm_pu','source_va_deg','source_pd_mw','source_qd_mvar', ...
    'source_gs_mw','source_bs_mvar','online_generator_count', ...
    'retained_incident_count','omitted_incident_count', ...
    'omitted_source_branch_rows','unregistered_local_branch_count', ...
    'retained_current_real_pu','retained_current_imag_pu', ...
    'omitted_current_real_pu','omitted_current_imag_pu', ...
    'equivalent_injection_current_real_pu', ...
    'equivalent_injection_current_imag_pu','equivalent_injection_p_mw', ...
    'equivalent_injection_q_mvar','retained_terminal_p_mw', ...
    'retained_terminal_q_mvar','source_kcl_residual_current_pu', ...
    'injection_closure_error_mva','source_zero_device_pass', ...
    'network_partition_pass','injection_policy'});
end

function I = bus_terminal_current(results, phasors, branch_rows, bus_id)
define_constants;
I = complex(0);
for r = branch_rows(:)'
    if results.branch(r, F_BUS) == bus_id
        I = I + phasors.If(r);
    elseif results.branch(r, T_BUS) == bus_id
        I = I + phasors.It(r);
    else
        error('run_s13_phase1b_local_identity:IncidentBranch', ...
            'Branch row %d is not incident on bus %d.', r, bus_id);
    end
end
end

function local = build_local_case(source, local_bus, boundary_bus, ...
        interior_bus, source_rows, Seq)
define_constants;
[found, source_bi] = ismember(local_bus, source.bus(:, BUS_I));
if ~all(found)
    error('run_s13_phase1b_local_identity:LocalBus', ...
        'One or more local source buses are missing.');
end
local = struct('version', '2', 'baseMVA', source.baseMVA);
local.bus = source.bus(source_bi, :);
local.branch = source.branch(source_rows, 1:ANGMAX);
local.bus(:, [PD QD GS BS]) = 0;
local.bus(ismember(local.bus(:, BUS_I), boundary_bus), BUS_TYPE) = REF;
local.bus(ismember(local.bus(:, BUS_I), interior_bus), BUS_TYPE) = PQ;
for k = 1:numel(interior_bus)
    bi = find(local.bus(:, BUS_I) == interior_bus(k), 1);
    local.bus(bi, PD) = -real(Seq(k));
    local.bus(bi, QD) = -imag(Seq(k));
end
ngcol = max(size(source.gen, 2), 21);
local.gen = zeros(numel(boundary_bus), ngcol);
for k = 1:numel(boundary_bus)
    bi = find(local.bus(:, BUS_I) == boundary_bus(k), 1);
    local.gen(k, GEN_BUS) = boundary_bus(k);
    local.gen(k, QMAX) = 1e6;
    local.gen(k, QMIN) = -1e6;
    local.gen(k, VG) = local.bus(bi, VM);
    local.gen(k, MBASE) = local.baseMVA;
    local.gen(k, GEN_STATUS) = 1;
    local.gen(k, PMAX) = 1e6;
    local.gen(k, PMIN) = -1e6;
end
if isfield(source, 'bus_name'), local.bus_name = source.bus_name(source_bi); end
end

function [raw_rows, raw_ids] = raw_branch_identity(raw_file, source, source_rows)
define_constants;
if ~isfile(raw_file)
    error('run_s13_phase1b_local_identity:RawFile', ...
        'The PERFORM RAW source file is missing: %s', raw_file);
end
[records, sections] = psse_read(raw_file, 0);
[data, ~] = psse_parse(records, sections, 0, 33);
raw_num = data.branch.num;
raw_txt = data.branch.txt;
raw_rows = nan(numel(source_rows), 1);
raw_ids = strings(numel(source_rows), 1);
for k = 1:numel(source_rows)
    sr = source_rows(k);
    f = source.branch(sr, F_BUS);
    t = source.branch(sr, T_BUS);
    params = source.branch(sr, [BR_R BR_X BR_B]);
    parameter_match = max(abs(raw_num(:, 4:6) - params), [], 2) <= 1e-10;
    match = find(raw_num(:, 1) == f & raw_num(:, 2) == t & parameter_match);
    if numel(match) ~= 1
        error('run_s13_phase1b_local_identity:RawBranchIdentity', ...
            ['Source branch row %d (%d-%d) maps to %d RAW rows; ' ...
             'expected exactly one.'], sr, f, t, numel(match));
    end
    raw_rows(k) = match;
    raw_ids(k) = upper(strtrim(erase(string(raw_txt{match, 3}), "'")));
end
end

function tbl = branch_identity_table(source, phasors, injection, zero, ...
        physical, raw_rows, raw_ids, candidate, path_id)
define_constants;
sr = double(physical.source_branch_row);
mr = double(physical.model_branch_row);
n = height(physical);
overlay_path_id = repmat(path_id, n, 1);
source_flow = source.branch(sr, PF:QT);
direct_flow = [real(phasors.Sf(sr)) imag(phasors.Sf(sr)) ...
    real(phasors.St(sr)) imag(phasors.St(sr))];
injection_flow = injection.branch(:, PF:QT);
zero_flow = zero.branch(:, PF:QT);
direct_error = direct_flow - source_flow;
injection_error = injection_flow - source_flow;
zero_error = zero_flow - source_flow;

[~, source_fi] = ismember(source.branch(sr, F_BUS), source.bus(:, BUS_I));
[~, source_ti] = ismember(source.branch(sr, T_BUS), source.bus(:, BUS_I));
from_current = abs(phasors.If(sr)) .* source.baseMVA ./ ...
    (sqrt(3) * source.bus(source_fi, BASE_KV));
to_current = abs(phasors.It(sr)) .* source.baseMVA ./ ...
    (sqrt(3) * source.bus(source_ti, BASE_KV));

orientation_match = source.branch(sr, F_BUS) == physical.source_from_bus & ...
    source.branch(sr, T_BUS) == physical.source_to_bus & ...
    candidate.branch(mr, F_BUS) == physical.model_from_bus & ...
    candidate.branch(mr, T_BUS) == physical.model_to_bus;
ckt_identity_match = raw_ids == string(physical.source_circuit_id);
cols = [BR_R BR_X BR_B RATE_A RATE_B RATE_C TAP SHIFT BR_STATUS];
source_values = source.branch(sr, cols);
candidate_values = candidate.branch(mr, cols);
parameter_control_match = all(candidate_values == source_values | ...
    (isnan(candidate_values) & isnan(source_values)), 2);
direct_p = max(abs(direct_error(:, [1 3])), [], 2);
direct_q = max(abs(direct_error(:, [2 4])), [], 2);
injection_p = max(abs(injection_error(:, [1 3])), [], 2);
injection_q = max(abs(injection_error(:, [2 4])), [], 2);

tbl = table(overlay_path_id, sr, source.branch(sr, F_BUS), ...
    source.branch(sr, T_BUS), string(physical.source_circuit_id), ...
    raw_rows, raw_ids, mr, double(physical.model_from_bus), ...
    double(physical.model_to_bus), source_flow(:,1), source_flow(:,2), ...
    source_flow(:,3), source_flow(:,4), direct_flow(:,1), direct_flow(:,2), ...
    direct_flow(:,3), direct_flow(:,4), direct_error(:,1), ...
    direct_error(:,2), direct_error(:,3), direct_error(:,4), ...
    injection_flow(:,1), injection_flow(:,2), injection_flow(:,3), ...
    injection_flow(:,4), injection_error(:,1), injection_error(:,2), ...
    injection_error(:,3), injection_error(:,4), zero_flow(:,1), ...
    zero_flow(:,2), zero_flow(:,3), zero_flow(:,4), zero_error(:,1), ...
    zero_error(:,2), zero_error(:,3), zero_error(:,4), from_current, ...
    to_current, direct_p, direct_q, injection_p, injection_q, ...
    orientation_match, ckt_identity_match, parameter_control_match, ...
    direct_p <= 1e-6 & direct_q <= 1e-6, ...
    injection_p <= 0.05 & injection_q <= 0.10, ...
    repmat("diagnostic_only_not_gating", n, 1), ...
    'VariableNames', {'overlay_path_id','source_branch_row', ...
    'source_from_bus','source_to_bus','source_circuit_id','raw_branch_row', ...
    'raw_circuit_id','s13_model_branch_row','s13_model_from_bus', ...
    's13_model_to_bus','source_pf_mw','source_qf_mvar','source_pt_mw', ...
    'source_qt_mvar','direct_pf_mw','direct_qf_mvar','direct_pt_mw', ...
    'direct_qt_mvar','direct_pf_error_mw','direct_qf_error_mvar', ...
    'direct_pt_error_mw','direct_qt_error_mvar','injection_pf_mw', ...
    'injection_qf_mvar','injection_pt_mw','injection_qt_mvar', ...
    'injection_pf_error_mw','injection_qf_error_mvar', ...
    'injection_pt_error_mw','injection_qt_error_mvar', ...
    'zero_injection_pf_mw','zero_injection_qf_mvar', ...
    'zero_injection_pt_mw','zero_injection_qt_mvar', ...
    'zero_injection_pf_error_mw','zero_injection_qf_error_mvar', ...
    'zero_injection_pt_error_mw','zero_injection_qt_error_mvar', ...
    'source_from_terminal_current_ka','source_to_terminal_current_ka', ...
    'direct_max_p_error_mw','direct_max_q_error_mvar', ...
    'injection_max_p_error_mw','injection_max_q_error_mvar', ...
    'orientation_match','raw_circuit_identity_match', ...
    's13_parameter_control_identity_match','direct_phasor_identity_pass', ...
    'injection_solution_branch_pass','zero_injection_acceptance_role'});
end

function tbl = voltage_table(source, injection, zero, candidate, bus_map, ...
        source_bus, boundary_bus, path_id)
define_constants;
n = numel(source_bus);
overlay_path_id = repmat(path_id, n, 1);
source_bus_name = strings(n, 1);
terminal_role = repmat("interior_pq", n, 1);
terminal_role(ismember(source_bus, boundary_bus)) = "fixed_boundary";
s13_model_bus = nan(n, 1); s13_model_bus_row = nan(n, 1);
s13_inherited_vm_pu = nan(n, 1); s13_inherited_va_deg = nan(n, 1);
source_vm_pu = nan(n, 1); source_va_deg = nan(n, 1);
injection_vm_pu = nan(n, 1); injection_va_deg = nan(n, 1);
zero_vm_pu = nan(n, 1); zero_va_deg = nan(n, 1);
for k = 1:n
    sb = source_bus(k);
    si = find(source.bus(:, BUS_I) == sb);
    ii = find(injection.bus(:, BUS_I) == sb);
    zi = find(zero.bus(:, BUS_I) == sb);
    mi = find(double(bus_map.source_bus) == sb);
    if any([numel(si), numel(ii), numel(zi), numel(mi)] ~= 1)
        error('run_s13_phase1b_local_identity:VoltageMapping', ...
            'Voltage mapping for path %s source bus %d is not unique.', ...
            path_id, sb);
    end
    source_bus_name(k) = bus_name(source, si);
    s13_model_bus(k) = double(bus_map.model_bus(mi));
    model_row = find(candidate.bus(:, BUS_I) == s13_model_bus(k), 1);
    if isempty(model_row)
        error('run_s13_phase1b_local_identity:CandidateBus', ...
            'Mapped S13 bus %.0f is missing.', s13_model_bus(k));
    end
    s13_model_bus_row(k) = model_row;
    s13_inherited_vm_pu(k) = candidate.bus(s13_model_bus_row(k), VM);
    s13_inherited_va_deg(k) = candidate.bus(s13_model_bus_row(k), VA);
    source_vm_pu(k) = source.bus(si, VM);
    source_va_deg(k) = source.bus(si, VA);
    injection_vm_pu(k) = injection.bus(ii, VM);
    injection_va_deg(k) = injection.bus(ii, VA);
    zero_vm_pu(k) = zero.bus(zi, VM);
    zero_va_deg(k) = zero.bus(zi, VA);
end

tbl = table(overlay_path_id, source_bus, source_bus_name, terminal_role, ...
    s13_model_bus, s13_model_bus_row, source_vm_pu, source_va_deg, ...
    injection_vm_pu, injection_va_deg, ...
    abs(injection_vm_pu-source_vm_pu), ...
    abs(angle_difference(injection_va_deg, source_va_deg)), ...
    zero_vm_pu, zero_va_deg, abs(zero_vm_pu-source_vm_pu), ...
    abs(angle_difference(zero_va_deg, source_va_deg)), ...
    s13_inherited_vm_pu, s13_inherited_va_deg, ...
    repmat("mapping_only_not_source_operating_comparison", n, 1), ...
    repmat("diagnostic_only_not_gating", n, 1), ...
    'VariableNames', {'overlay_path_id','source_bus','source_bus_name', ...
    'terminal_role','s13_model_bus','s13_model_bus_row','source_vm_pu', ...
    'source_va_deg','injection_vm_pu','injection_va_deg', ...
    'injection_vm_error_pu','injection_va_error_deg', ...
    'zero_injection_vm_pu','zero_injection_va_deg', ...
    'zero_injection_vm_error_pu','zero_injection_va_error_deg', ...
    's13_inherited_vm_pu','s13_inherited_va_deg', ...
    's13_inherited_snapshot_role','zero_injection_acceptance_role'});
end

function [validation, status] = optional_operator_validation(candidate)
status = struct('available', false, 'proxy_pass', false, ...
    'role_pass', false, 'mandatory_rows_pass', false);
validation = struct('available', false);
if exist('validate_s13_phase1b_upny_operator', 'file') == 0
    return;
end
validation = validate_s13_phase1b_upny_operator(struct( ...
    'candidate_case', candidate, 'write_outputs', false, ...
    'fail_on_gate', true, 'verbose', false));
required = {'pass','mandatory_proxy_pass','exact_public_operator', ...
    'promotion_eligible','gate_ledger'};
if ~isstruct(validation) || ~all(isfield(validation, required)) || ...
        ~istable(validation.gate_ledger) || ...
        ~all(ismember({'mandatory_for_phase1b_proxy','pass'}, ...
        validation.gate_ledger.Properties.VariableNames))
    error('run_s13_phase1b_local_identity:OperatorValidatorContract', ...
        'The Phase 1B operator validator returned an invalid contract.');
end
mandatory_rows = logical( ...
    validation.gate_ledger.mandatory_for_phase1b_proxy);
status.available = true;
status.mandatory_rows_pass = all(validation.gate_ledger.pass(mandatory_rows));
status.proxy_pass = logical(validation.pass) && ...
    logical(validation.mandatory_proxy_pass) && status.mandatory_rows_pass;
status.role_pass = ~logical(validation.exact_public_operator) && ...
    ~logical(validation.promotion_eligible);
end

function gates = gate_ledger(source, path_results, identity, omitted, ...
        voltages, phase1a_report_exact, phase1a_rows_exact, ...
        candidate_fail_closed, operator)
rows = { ...
    "phase1b_all", "source_q_limit_pf_converged", double(source.success), ...
        1, "==", true, logical(source.success), ...
        "full PERFORM Q-limit reference"; ...
    "phase1b_all", "phase1a_report_exact_match", ...
        double(phase1a_report_exact), 1, "==", true, ...
        phase1a_report_exact, "fresh immutable Phase 1A builder"; ...
    "phase1b_all", "phase1a_physical_rows_bit_identical", ...
        double(phase1a_rows_exact), 1, "==", true, phase1a_rows_exact, ...
        "full immutable Phase 1A branch rows"; ...
    "phase1b_all", "candidate_remains_fail_closed", ...
        double(candidate_fail_closed), 1, "==", true, ...
        candidate_fail_closed, "no residual fit or promotion"; ...
    "phase1b_all", "source_and_model_orientation_exact", ...
        double(all(identity.orientation_match)), 1, "==", true, ...
        all(identity.orientation_match), "registered source and model endpoints"; ...
    "phase1b_all", "raw_circuit_identity_exact", ...
        double(all(identity.raw_circuit_identity_match)), 1, "==", true, ...
        all(identity.raw_circuit_identity_match), ...
        "RAW endpoint R/X/B and circuit identity"; ...
    "phase1b_all", "s13_parameter_controls_exact", ...
        double(all(identity.s13_parameter_control_identity_match)), ...
        1, "==", true, ...
        all(identity.s13_parameter_control_identity_match), ...
        "R/X/B ratings tap shift and status"};

for p = 1:numel(path_results)
    path_id = path_results(p).overlay_path_id;
    id_rows = identity.overlay_path_id == path_id;
    injection_rows = omitted.overlay_path_id == path_id;
    voltage_rows = voltages.overlay_path_id == path_id;
    interior = voltage_rows & voltages.terminal_role == "interior_pq";
    boundary = voltage_rows & voltages.terminal_role == "fixed_boundary";
    injection = path_results(p).injection_results;
    rows(end+1,:) = {path_id, "source_interior_zero_device_status", ...
        double(all(omitted.source_zero_device_pass(injection_rows))), ...
        1, "==", true, ...
        all(omitted.source_zero_device_pass(injection_rows)), ...
        "PD/QD/GS/BS and online generators"}; %#ok<AGROW>
    rows(end+1,:) = {path_id, "omitted_network_partition_valid", ...
        double(all(omitted.network_partition_pass(injection_rows))), ...
        1, "==", true, ...
        all(omitted.network_partition_pass(injection_rows)), ...
        "no unregistered branch internal to local buses"}; %#ok<AGROW>
    value = max(omitted.source_kcl_residual_current_pu(injection_rows));
    rows(end+1,:) = {path_id, "source_kcl_residual_current_pu", ...
        value, 1e-7, "<=", true, value <= 1e-7, ...
        "retained plus omitted terminal current"}; %#ok<AGROW>
    value = max(identity.direct_max_p_error_mw(id_rows));
    rows(end+1,:) = {path_id, "direct_max_p_error_mw", value, ...
        1e-6, "<=", true, value <= 1e-6, ...
        "Yf/Yt phasor recomputation"}; %#ok<AGROW>
    value = max(identity.direct_max_q_error_mvar(id_rows));
    rows(end+1,:) = {path_id, "direct_max_q_error_mvar", value, ...
        1e-6, "<=", true, value <= 1e-6, ...
        "Yf/Yt phasor recomputation"}; %#ok<AGROW>
    rows(end+1,:) = {path_id, "injection_local_pf_converged", ...
        double(injection.success), 1, "==", true, ...
        logical(injection.success), "two fixed boundary phasors"}; %#ok<AGROW>
    value = max(identity.injection_max_p_error_mw(id_rows));
    rows(end+1,:) = {path_id, "injection_max_p_error_mw", value, ...
        0.05, "<=", true, value <= 0.05, ...
        "source-derived omitted-network injection"}; %#ok<AGROW>
    value = max(identity.injection_max_q_error_mvar(id_rows));
    rows(end+1,:) = {path_id, "injection_max_q_error_mvar", value, ...
        0.10, "<=", true, value <= 0.10, ...
        "source-derived omitted-network injection"}; %#ok<AGROW>
    value = max(voltages.injection_vm_error_pu(interior));
    rows(end+1,:) = {path_id, "injection_max_interior_vm_error_pu", ...
        value, 1e-5, "<=", true, value <= 1e-5, ...
        "single interior physical terminal"}; %#ok<AGROW>
    value = max(voltages.injection_va_error_deg(interior));
    rows(end+1,:) = {path_id, "injection_max_interior_va_error_deg", ...
        value, 0.001, "<=", true, value <= 0.001, ...
        "single interior physical terminal"}; %#ok<AGROW>
    value = max(voltages.injection_vm_error_pu(boundary));
    rows(end+1,:) = {path_id, "fixed_boundary_vm_error_pu", ...
        value, 1e-10, "<=", true, value <= 1e-10, ...
        "exact source boundary magnitudes"}; %#ok<AGROW>
    value = max(voltages.injection_va_error_deg(boundary));
    rows(end+1,:) = {path_id, "fixed_boundary_va_error_deg", ...
        value, 1e-9, "<=", true, value <= 1e-9, ...
        "exact source boundary angles"}; %#ok<AGROW>
end

rows(end+1,:) = {"phase1b_upny_operator", ...
    "operator_mandatory_proxy_pass", double(operator.proxy_pass), ...
    1, "==", operator.available, operator.proxy_pass, ...
    "optional validator mandatory proxy rows"};
rows(end+1,:) = {"phase1b_upny_operator", ...
    "operator_remains_nonpublic_unpromoted", double(operator.role_pass), ...
    1, "==", operator.available, operator.role_pass, ...
    "exact public operator and promotion both remain false"};
gates = cell2table(rows, 'VariableNames', {'overlay_path_id','gate_id', ...
    'metric_value','limit','comparator','mandatory','pass','notes'});
gates.overlay_path_id = string(gates.overlay_path_id);
gates.gate_id = string(gates.gate_id);
gates.comparator = string(gates.comparator);
gates.notes = string(gates.notes);
end

function d = angle_difference(a, b)
d = mod(a - b + 180, 360) - 180;
end

function name = bus_name(mpc, row)
name = "BUS_" + string(mpc.bus(row, 1));
if isfield(mpc, 'bus_name'), name = strtrim(string(mpc.bus_name{row})); end
end
