function out = run_s13_phase1a_oracle_comparison(options)
%RUN_S13_PHASE1A_ORACLE_COMPARISON Orchestrate the no-fit S13.1 evidence.
%   Stage A is executed through RUN_S13_PHASE1A_LOCAL_IDENTITY. Stage B/C
%   remain fail-closed until ASSESS_S13_PHASE1A_COMMON_INPUT_READINESS
%   establishes a frozen common operating baseline. Unexecuted metrics are
%   persisted as NaN with explicit blocked reasons; no comparison value is
%   inferred from a different operating point.

if nargin < 1, options = struct(); end
helper_dir = fileparts(mfilename('fullpath'));
case_dir = fileparts(helper_dir);
options = defaults(options, helper_dir);
addpath(case_dir); addpath(helper_dir);

local = run_s13_phase1a_local_identity(struct( ...
    'write_outputs', false, 'fail_on_gate', false, 'verbose', false));
readiness = assess_s13_phase1a_common_input_readiness(struct( ...
    'write_outputs', false, 'fail_on_not_ready', false, 'verbose', false));

blocked_reason = "Frozen common S12/S13 baseline unavailable: " + ...
    strjoin(readiness.blockers, "; ");
same_snapshot = same_snapshot_manifest(local, blocked_reason);
cut_flows = cut_flow_manifest(blocked_reason);
physical_circuits = physical_circuit_evidence(local, blocked_reason);
heldout = heldout_manifest(local, blocked_reason);
heldout_metrics = heldout_metric_manifest(local, heldout, blocked_reason);
gates = oracle_gate_ledger(local, readiness, same_snapshot, cut_flows, ...
    physical_circuits, heldout, heldout_metrics);

all_required_pass = all(gates.passed(gates.required));
stage_b_executed = any(same_snapshot.execution_status == "executed");
stage_c_executed = any(heldout.execution_status == "executed");
electrically_validated = local.pass && readiness.ready && ...
    stage_b_executed && stage_c_executed && all_required_pass;

files = struct( ...
    'same_snapshot', fullfile(options.output_dir, ...
        's13_phase1a_same_snapshot_comparison.csv'), ...
    'cut_flow', fullfile(options.output_dir, ...
        's13_phase1a_cut_flow_comparison.csv'), ...
    'physical_circuit', fullfile(options.output_dir, ...
        's13_phase1a_physical_circuit_comparison.csv'), ...
    'heldout_response', fullfile(options.output_dir, ...
        's13_phase1a_heldout_response.csv'), ...
    'heldout_metric_manifest', fullfile(options.output_dir, ...
        's13_phase1a_heldout_metric_manifest.csv'), ...
    'gate_ledger', fullfile(options.output_dir, ...
        's13_phase1a_oracle_gate_ledger.csv'));
if options.write_outputs
    if ~isfolder(options.output_dir)
        error('run_s13_phase1a_oracle_comparison:OutputDirectory', ...
            'Output directory does not exist: %s', options.output_dir);
    end
    ny_lite_writetable_lf(same_snapshot, files.same_snapshot);
    ny_lite_writetable_lf(cut_flows, files.cut_flow);
    ny_lite_writetable_lf(physical_circuits, files.physical_circuit);
    ny_lite_writetable_lf(heldout, files.heldout_response);
    ny_lite_writetable_lf(heldout_metrics, files.heldout_metric_manifest);
    ny_lite_writetable_lf(gates, files.gate_ledger);
end

if electrically_validated
    status = "electrically_validated_unpromoted_checkpoint";
else
    status = "unpromoted_fail_closed_pending_common_baseline";
end

out = struct( ...
    'model_role', "unpromoted_s13_candidate", ...
    'status', status, ...
    'promotion_eligible', false, ...
    'electrically_validated', logical(electrically_validated), ...
    'all_required_gates_pass', logical(all_required_pass), ...
    'stage_a_executed', true, ...
    'stage_a_pass', logical(local.pass), ...
    'stage_b_executed', logical(stage_b_executed), ...
    'stage_c_executed', logical(stage_c_executed), ...
    'common_input_ready', logical(readiness.ready), ...
    'blocked_reason', blocked_reason, ...
    'local_identity', local, ...
    'common_input_readiness', readiness, ...
    'same_snapshot_comparison', same_snapshot, ...
    'cut_flow_comparison', cut_flows, ...
    'physical_circuit_comparison', physical_circuits, ...
    'heldout_response', heldout, ...
    'heldout_metric_manifest', heldout_metrics, ...
    'gate_ledger', gates, ...
    'passing_gate_count', nnz(gates.passed), ...
    'gate_count', height(gates), ...
    'files', files, ...
    'outputs_written', logical(options.write_outputs));

if options.verbose
    fprintf(['S13.1 oracle orchestration: %s; gates %d/%d pass; ' ...
        'Stage A=%d, Stage B executed=%d, Stage C executed=%d.\n'], ...
        status, out.passing_gate_count, out.gate_count, local.pass, ...
        stage_b_executed, stage_c_executed);
    if ~electrically_validated
        fprintf('  fail-closed: %s\n', blocked_reason);
    end
end

if options.fail_on_incomplete && ~electrically_validated
    error('run_s13_phase1a_oracle_comparison:Incomplete', ...
        'The S13.1 oracle comparison remains fail-closed: %s', blocked_reason);
end
end

function options = defaults(options, helper_dir)
if ~isfield(options, 'write_outputs'), options.write_outputs = true; end
if ~isfield(options, 'output_dir'), options.output_dir = helper_dir; end
if ~isfield(options, 'verbose'), options.verbose = true; end
if ~isfield(options, 'fail_on_incomplete'), options.fail_on_incomplete = false; end
options.write_outputs = logical(options.write_outputs);
options.verbose = logical(options.verbose);
options.fail_on_incomplete = logical(options.fail_on_incomplete);
end

function rows = same_snapshot_manifest(local, reason)
metric_id = [ ...
    "standard_pf_success"; "q_limit_pf_success"; ...
    "complete_E_G_cut_flow"; "complete_E_F_cut_flow"; ...
    "E_G_eastbound_share"; "internal_NY_active_loss"; ...
    "whole_system_active_loss"; "net_network_q_absorption"; ...
    "existing_DLR_current_max_error"; ...
    "added_physical_branch_overload_count"];
metric_group = ["power_flow"; "power_flow"; "cut_flow"; "cut_flow"; ...
    "flow_split"; "loss"; "loss"; "reactive_balance"; ...
    "current"; "thermal"];
location = ["S12_and_S13"; "S12_and_S13"; "E_to_G"; "E_to_F"; ...
    "E_F_and_E_G"; "internal_NY_only"; "model_whole_system_diagnostic"; ...
    "internal_NY_network"; "five_legacy_circuit_operators"; ...
    "seven_Phase1A_branches"];
unit = ["flag"; "flag"; "MW"; "MW"; "percent"; "MW"; "MW"; ...
    "MVAr"; "percent"; "count"];
gate_rule = ["both_equal_1"; "both_equal_1"; ...
    "absolute_error_le_150_MW_or_15_percent_and_correct_direction"; ...
    "diagnostic"; "absolute_error_le_10_percentage_points"; ...
    "absolute_percent_error_le_15"; "diagnostic_only_not_cross_model_gate"; ...
    "diagnostic"; "maximum_error_le_15_percent"; "equal_0"];
gating = [true; true; true; false; true; true; false; false; true; true];

terminal = local.terminal_voltages;
for k = 1:height(terminal)
    metric_id(end+1, 1) = "terminal_VM_" + ...
        clean_token(terminal.source_bus_name(k)); %#ok<AGROW>
    metric_group(end+1, 1) = "terminal_voltage"; %#ok<AGROW>
    location(end+1, 1) = string(terminal.source_bus_name(k)); %#ok<AGROW>
    unit(end+1, 1) = "pu"; %#ok<AGROW>
    gate_rule(end+1, 1) = "absolute_error_le_0.02_pu"; %#ok<AGROW>
    gating(end+1, 1) = true; %#ok<AGROW>
    metric_id(end+1, 1) = "terminal_aligned_VA_" + ...
        clean_token(terminal.source_bus_name(k)); %#ok<AGROW>
    metric_group(end+1, 1) = "terminal_angle"; %#ok<AGROW>
    location(end+1, 1) = string(terminal.source_bus_name(k)); %#ok<AGROW>
    unit(end+1, 1) = "degree"; %#ok<AGROW>
    gate_rule(end+1, 1) = "EDIC_aligned_absolute_error_le_2_deg"; %#ok<AGROW>
    gating(end+1, 1) = true; %#ok<AGROW>
end
n = numel(metric_id);
rows = table(metric_id, metric_group, location, unit, ...
    nan(n, 1), nan(n, 1), nan(n, 1), nan(n, 1), gate_rule, gating, ...
    repmat("blocked", n, 1), repmat(string(reason), n, 1), ...
    repmat("not_executed_no_common_baseline", n, 1), ...
    'VariableNames', {'metric_id','metric_group','location','unit', ...
    's12_value','s13_value','absolute_error','absolute_percent_error', ...
    'gate_rule','gating','execution_status','blocked_reason', ...
    'evidence_policy'});
end

function rows = cut_flow_manifest(reason)
cut_id = ["complete_E_G_zone_cut"; "complete_E_F_zone_cut"; ...
    "E_G_share_of_EF_plus_EG"; "Central_East_diagnostic"; ...
    "Total_East_diagnostic"];
positive_direction = ["E_to_G"; "E_to_F"; "eastbound_share"; ...
    "E_to_F"; "west_A_to_E_toward_east_F_to_K"];
operator_policy = [ ...
    "all_active_branches_crossing_the_nonintersecting_E_G_boundary"; ...
    "all_active_branches_crossing_the_nonintersecting_E_F_boundary"; ...
    "E_G_divided_by_E_G_plus_E_F_using_eastbound_complete_cuts"; ...
    "source_backed_diagnostic_not_public_flow_closure"; ...
    "nonintersecting_diagnostic_operator_pending_common_baseline"];
unit = ["MW"; "MW"; "percent"; "MW"; "MW"];
gate_rule = ["absolute_error_le_150_MW_or_15_percent_and_correct_direction"; ...
    "diagnostic"; "absolute_error_le_10_percentage_points"; ...
    "diagnostic"; "diagnostic"];
gating = [true; false; true; false; false];
n = numel(cut_id);
rows = table(cut_id, positive_direction, operator_policy, unit, ...
    nan(n, 1), nan(n, 1), nan(n, 1), nan(n, 1), gate_rule, gating, ...
    repmat("blocked", n, 1), repmat(string(reason), n, 1), ...
    'VariableNames', {'cut_id','positive_direction','operator_policy', ...
    'unit','s12_flow_or_share','s13_flow_or_share','absolute_error', ...
    'absolute_percent_error','gate_rule','gating','execution_status', ...
    'blocked_reason'});
end

function rows = physical_circuit_evidence(local, reason)
id = local.local_identity;
source_current = compute_branch_currents_kA(local.source_results);
s12_current = compute_branch_currents_kA(local.s12_results);
injection_current = compute_branch_currents_kA(local.injection_results);
n = height(id);
physical_circuit_id = "PERFORM_" + string(id.source_from_bus) + "_" + ...
    string(id.source_to_bus) + "_CKT_" + string(id.raw_circuit_id);
source_series_current_kA = ...
    source_current.series_current_kA(id.source_branch_row);
s12_series_current_kA = ...
    s12_current.series_current_kA(id.s12_reduced_branch_row);
stage_a_local_series_current_kA = injection_current.series_current_kA((1:n)');
s12_source_current_error_percent = percent_error( ...
    source_series_current_kA, s12_series_current_kA);
stage_a_local_current_error_percent = percent_error( ...
    source_series_current_kA, stage_a_local_series_current_kA);
stage_a_pass = id.orientation_match & id.raw_circuit_identity_match & ...
    id.s13_parameter_identity_match & id.direct_phasor_identity_pass & ...
    id.injection_solution_branch_pass & id.s12_readonly_oracle_branch_pass;
rows = table(physical_circuit_id, id.source_branch_row, ...
    id.source_from_bus, id.source_to_bus, string(id.raw_circuit_id), ...
    id.s12_reduced_branch_row, id.s13_model_branch_row, ...
    source_series_current_kA, s12_series_current_kA, ...
    stage_a_local_series_current_kA, s12_source_current_error_percent, ...
    stage_a_local_current_error_percent, id.direct_max_p_error_mw, ...
    id.direct_max_q_error_mvar, id.injection_max_p_error_mw, ...
    id.injection_max_q_error_mvar, id.s12_max_p_error_mw, ...
    id.s12_max_q_error_mvar, stage_a_pass, ...
    'VariableNames', {'physical_circuit_id','source_branch_row', ...
    'source_from_bus','source_to_bus','source_circuit_id', ...
    's12_reduced_branch_row','s13_model_branch_row', ...
    'source_series_current_kA','s12_series_current_kA', ...
    'stage_a_local_series_current_kA','s12_source_current_error_percent', ...
    'stage_a_local_current_error_percent','direct_max_p_error_mw', ...
    'direct_max_q_error_mvar','stage_a_injection_max_p_error_mw', ...
    'stage_a_injection_max_q_error_mvar','s12_max_p_error_mw', ...
    's12_max_q_error_mvar','stage_a_pass'});
rows.common_baseline_id = ...
    repmat("pending_frozen_common_s12_s13_baseline", n, 1);
rows.common_baseline_flow_orientation = ...
    repmat("source_from_bus_to_source_to_bus", n, 1);
future_numeric_fields = { ...
    'common_baseline_s12_pf_mw', ...
    'common_baseline_s12_qf_mvar', ...
    'common_baseline_s12_pt_mw', ...
    'common_baseline_s12_qt_mvar', ...
    'common_baseline_s12_series_current_kA', ...
    'common_baseline_s13_pf_mw', ...
    'common_baseline_s13_qf_mvar', ...
    'common_baseline_s13_pt_mw', ...
    'common_baseline_s13_qt_mvar', ...
    'common_baseline_s13_series_current_kA', ...
    'common_baseline_pf_error_mw', ...
    'common_baseline_qf_error_mvar', ...
    'common_baseline_pt_error_mw', ...
    'common_baseline_qt_error_mvar', ...
    'common_baseline_series_current_error_kA', ...
    'common_baseline_current_error_percent'};
for k = 1:numel(future_numeric_fields)
    rows.(future_numeric_fields{k}) = nan(n, 1);
end
rows.system_current_gate_percent = repmat(15, n, 1);
rows.system_comparison_status = repmat("blocked", n, 1);
rows.blocked_reason = repmat(string(reason), n, 1);
rows.evidence_role = repmat( ...
    "real_StageA_and_readonly_S12_evidence_only", n, 1);
end

function rows = heldout_manifest(local, reason)
perturbation_id = ["E_TO_G_P250"; "E_TO_G_N250"; ...
    "E_TO_G_P500"; "E_TO_G_N500"; "F_TO_G_P250"; ...
    "F_TO_G_N250"; "ZONE_E_LOAD_P5"; "ZONE_E_LOAD_N5"; ...
    "ZONE_G_LOAD_P5"; "ZONE_G_LOAD_N5"; ...
    "COOPERS_ROCK_TAVERN_CKT1_OUTAGE"; ...
    "COOPERS_ROCK_TAVERN_CKT2_OUTAGE"];
family = [repmat("balanced_zonal_transfer", 6, 1); ...
    repmat("balanced_zonal_load_change", 4, 1); ...
    repmat("physical_circuit_outage", 2, 1)];
source_zone = [repmat("E", 4, 1); repmat("F", 2, 1); ...
    repmat("", 6, 1)];
sink_zone = [repmat("G", 6, 1); repmat("", 6, 1)];
transfer_mw = [250; -250; 500; -500; 250; -250; nan(6, 1)];
load_zone = [repmat("", 6, 1); repmat("E", 2, 1); ...
    repmat("G", 2, 1); repmat("", 2, 1)];
load_change_percent = [nan(6, 1); 5; -5; 5; -5; nan(2, 1)];
outaged_source_branch_row = [nan(10, 1); 1567; 1568];
outaged_s12_branch_row = nan(12, 1);
outaged_s13_branch_row = nan(12, 1);
for k = 11:12
    hit = find(local.local_identity.source_branch_row == ...
        outaged_source_branch_row(k), 1);
    outaged_s12_branch_row(k) = ...
        local.local_identity.s12_reduced_branch_row(hit);
    outaged_s13_branch_row(k) = ...
        local.local_identity.s13_model_branch_row(hit);
end
n = numel(perturbation_id);
rows = table(perturbation_id, family, source_zone, sink_zone, transfer_mw, ...
    load_zone, load_change_percent, outaged_source_branch_row, ...
    outaged_s12_branch_row, outaged_s13_branch_row, ...
    repmat("frozen_common_no_fit_baseline", n, 1), ...
    repmat("pending_common_balancing_gsk_not_frozen", n, 1), ...
    false(n, 1), repmat("blocked", n, 1), ...
    nan(n, 1), nan(n, 1), nan(n, 1), nan(n, 1), nan(n, 1), ...
    nan(n, 1), nan(n, 1), repmat("not_evaluated", n, 1), ...
    repmat("blocked", n, 1), ...
    repmat(string(reason), n, 1), ...
    'VariableNames', {'perturbation_id','family','source_zone','sink_zone', ...
    'transfer_mw','load_zone','load_change_percent', ...
    'outaged_source_branch_row','outaged_s12_branch_row', ...
    'outaged_s13_branch_row','required_baseline','balancing_policy_id', ...
    'refit_performed', ...
    'execution_status','s12_pf_success','s13_pf_success', ...
    'oracle_E_G_cut_delta_mw','s13_E_G_cut_delta_mw', ...
    'E_G_cut_delta_error_percent','maximum_physical_delta_I_error_percent', ...
    'response_regression_slope','current_change_direction_pass', ...
    'gate_status','blocked_reason'});
end

function rows = heldout_metric_manifest(local, heldout, reason)
identity = local.local_identity;
terminal = local.terminal_voltages;
n_circuit = height(identity);
n_terminal = height(terminal);

circuit_id = "PERFORM_" + string(identity.source_from_bus) + "_" + ...
    string(identity.source_to_bus) + "_CKT_" + ...
    string(identity.raw_circuit_id);
circuit_entity = repelem(circuit_id, 3, 1);
circuit_metric = repmat(["delta_pf_mw"; "delta_qf_mvar"; ...
    "delta_series_current_kA"], n_circuit, 1);
circuit_group = repmat(["physical_circuit_flow"; ...
    "physical_circuit_flow"; "physical_circuit_current"], n_circuit, 1);
circuit_unit = repmat(["MW"; "MVAr"; "kA"], n_circuit, 1);
circuit_direction = repmat(["source_from_bus_to_source_to_bus"; ...
    "source_from_bus_to_source_to_bus"; ...
    "unsigned_series_current_magnitude"], n_circuit, 1);
circuit_rule = repmat(["diagnostic_response_evidence"; ...
    "diagnostic_response_evidence"; ...
    "delta_error_le_15_percent_and_correct_direction"], n_circuit, 1);
circuit_gating = repmat([false; false; true], n_circuit, 1);

terminal_id = "PERFORM_" + string(terminal.source_bus) + "_" + ...
    clean_token(terminal.source_bus_name);
terminal_entity = repelem(terminal_id, 2, 1);
terminal_metric = repmat(["delta_vm_pu"; "delta_aligned_va_deg"], ...
    n_terminal, 1);
terminal_group = repmat(["terminal_voltage"; "terminal_angle"], ...
    n_terminal, 1);
terminal_unit = repmat(["pu"; "degree"], n_terminal, 1);
terminal_direction = repmat(["voltage_magnitude"; ...
    "EDIC_aligned_angle_change"], n_terminal, 1);
terminal_rule = repmat(["diagnostic_response_evidence"; ...
    "diagnostic_response_evidence"], n_terminal, 1);
terminal_gating = false(2*n_terminal, 1);

system_entity = ["complete_E_G_zone_cut"; "complete_E_F_zone_cut"; ...
    "internal_NY_active_loss"];
system_metric = ["delta_E_G_cut_mw"; "delta_E_F_cut_mw"; ...
    "delta_internal_NY_active_loss_mw"];
system_group = ["system_cut_flow"; "system_cut_flow"; "system_loss"];
system_unit = ["MW"; "MW"; "MW"];
system_direction = ["E_to_G_positive"; "E_to_F_positive"; ...
    "positive_network_active_loss"];
system_rule = ["delta_error_le_15_percent"; ...
    "diagnostic_response_evidence"; "diagnostic_response_evidence"];
system_gating = [true; false; false];

entity_type_base = [repmat("physical_circuit", 3*n_circuit, 1); ...
    repmat("terminal", 2*n_terminal, 1); repmat("system", 3, 1)];
entity_id_base = [circuit_entity; terminal_entity; system_entity];
metric_id_base = [circuit_metric; terminal_metric; system_metric];
metric_group_base = [circuit_group; terminal_group; system_group];
unit_base = [circuit_unit; terminal_unit; system_unit];
direction_base = [circuit_direction; terminal_direction; system_direction];
gate_rule_base = [circuit_rule; terminal_rule; system_rule];
gating_base = [circuit_gating; terminal_gating; system_gating];

source_branch_base = [repelem(identity.source_branch_row, 3, 1); ...
    nan(2*n_terminal+3, 1)];
s12_branch_base = [repelem(identity.s12_reduced_branch_row, 3, 1); ...
    nan(2*n_terminal+3, 1)];
s13_branch_base = [repelem(identity.s13_model_branch_row, 3, 1); ...
    nan(2*n_terminal+3, 1)];
source_bus_base = [nan(3*n_circuit, 1); ...
    repelem(terminal.source_bus, 2, 1); nan(3, 1)];
s12_bus_base = [nan(3*n_circuit, 1); ...
    repelem(terminal.s12_reduced_bus_row, 2, 1); nan(3, 1)];
s13_bus_base = [nan(3*n_circuit, 1); ...
    repelem(terminal.s13_model_bus, 2, 1); nan(3, 1)];

metric_count = numel(metric_id_base);
scenario_index = repelem((1:height(heldout))', metric_count, 1);
rows = heldout(scenario_index, {'perturbation_id','family','source_zone', ...
    'sink_zone','transfer_mw','load_zone','load_change_percent', ...
    'outaged_source_branch_row','outaged_s12_branch_row', ...
    'outaged_s13_branch_row','required_baseline','balancing_policy_id', ...
    'refit_performed'});
scenario_count = height(heldout);
rows.entity_type = repmat(entity_type_base, scenario_count, 1);
rows.entity_id = repmat(entity_id_base, scenario_count, 1);
rows.metric_id = repmat(metric_id_base, scenario_count, 1);
rows.metric_group = repmat(metric_group_base, scenario_count, 1);
rows.unit = repmat(unit_base, scenario_count, 1);
rows.positive_direction_or_alignment = ...
    repmat(direction_base, scenario_count, 1);
rows.source_branch_row = repmat(source_branch_base, scenario_count, 1);
rows.s12_reduced_branch_row = repmat(s12_branch_base, scenario_count, 1);
rows.s13_model_branch_row = repmat(s13_branch_base, scenario_count, 1);
rows.source_bus = repmat(source_bus_base, scenario_count, 1);
rows.s12_reduced_bus_row = repmat(s12_bus_base, scenario_count, 1);
rows.s13_model_bus = repmat(s13_bus_base, scenario_count, 1);
rows.oracle_model = repmat("S12_reference_oracle", height(rows), 1);
rows.candidate_model = repmat("S13_unpromoted_candidate", height(rows), 1);
future_value_fields = {'oracle_baseline_value','oracle_perturbed_value', ...
    'oracle_delta_value','s13_baseline_value','s13_perturbed_value', ...
    's13_delta_value','delta_absolute_error','delta_error_percent'};
for k = 1:numel(future_value_fields)
    rows.(future_value_fields{k}) = nan(height(rows), 1);
end
rows.direction_match_status = repmat("not_evaluated", height(rows), 1);
rows.gate_rule = repmat(gate_rule_base, scenario_count, 1);
rows.gating = repmat(gating_base, scenario_count, 1);
rows.execution_status = repmat("blocked", height(rows), 1);
rows.gate_status = repmat("blocked", height(rows), 1);
rows.blocked_reason = repmat(string(reason), height(rows), 1);
rows.evidence_policy = repmat( ...
    "manifest_only_no_common_baseline_no_inferred_values", height(rows), 1);
end

function gates = oracle_gate_ledger(local, readiness, same_snapshot, ...
        cut_flows, physical, heldout, heldout_metrics)
gates = table();
for k = 1:height(local.gate_ledger)
    g = local.gate_ledger(k, :);
    gates = append_gate(gates, "stage_a_local_identity", g.gate_id, ...
        "executed_metric", g.metric_value, g.limit, g.comparator, ...
        g.mandatory, g.pass, g.notes, "");
end
for k = 1:height(readiness.gates)
    g = readiness.gates(k, :);
    gates = append_gate(gates, "stage_b_common_input", g.gate_id, ...
        "readiness_prerequisite", double(g.actual), 1, "==", ...
        g.required, g.actual, g.evidence, ...
        blocked_if_false(g.actual, "common_input_prerequisite_not_met"));
end

reason = same_snapshot.blocked_reason(1);
stage_b = { ...
    'frozen_common_baseline_available', 'prerequisite', NaN, NaN, 'defined'; ...
    'paired_standard_pf_executed', 'execution', NaN, 1, '=='; ...
    'paired_q_limit_pf_executed', 'execution', NaN, 1, '=='; ...
    'correct_E_G_flow_direction', 'system_response', NaN, 1, '=='; ...
    'complete_E_G_cut_error', 'system_response', NaN, 15, '<=percent_or_150MW'; ...
    'individual_physical_circuit_error', 'system_response', NaN, 15, '<='; ...
    'E_F_E_G_split_error_percentage_points', 'system_response', NaN, 10, '<='; ...
    'added_terminal_voltage_error_pu', 'system_response', NaN, 0.02, '<='; ...
    'added_terminal_aligned_angle_error_deg', 'system_response', NaN, 2, '<='; ...
    'internal_NY_active_loss_error_percent', 'system_response', NaN, 15, '<='; ...
    'legacy_DLR_current_error_percent', 'system_response', NaN, 15, '<='; ...
    'added_physical_branch_overload_count', 'system_response', NaN, 0, '=='};
for k = 1:size(stage_b, 1)
    gates = append_gate(gates, "stage_b_same_snapshot", stage_b{k, 1}, ...
        stage_b{k, 2}, stage_b{k, 3}, stage_b{k, 4}, stage_b{k, 5}, ...
        true, false, "Not evaluated without the frozen common baseline.", reason);
end

detail_complete = heldout_detail_schema_complete(heldout_metrics, heldout);
manifest_complete = height(heldout) == 12 && ...
    numel(unique(heldout.perturbation_id)) == 12 && detail_complete;
no_refit = all(~heldout.refit_performed) && ...
    all(~heldout_metrics.refit_performed);
gates = append_gate(gates, "stage_c_heldout", ...
    "requested_perturbation_manifest_complete", "manifest", ...
    double(manifest_complete), 1, "==", true, manifest_complete, ...
    "All requested perturbations have the complete 432-row metric schema.", ...
    blocked_if_false(manifest_complete, "perturbation_manifest_incomplete"));
gates = append_gate(gates, "stage_c_heldout", "no_refit_policy", ...
    "policy", double(no_refit), 1, "==", true, no_refit, ...
    "No perturbation may refit S13.", ...
    blocked_if_false(no_refit, "refit_policy_violated"));
stage_c = { ...
    'all_heldout_runs_executed', NaN, 1, '=='; ...
    'physical_current_change_direction_all', NaN, 1, '=='; ...
    'maximum_physical_delta_I_error_percent', NaN, 15, '<='; ...
    'E_G_cut_delta_P_error_percent', NaN, 15, '<='; ...
    'response_regression_slope', NaN, 0.85, 'within_0.85_1.15'};
for k = 1:size(stage_c, 1)
    gates = append_gate(gates, "stage_c_heldout", stage_c{k, 1}, ...
        "blocked_metric", stage_c{k, 2}, stage_c{k, 3}, stage_c{k, 4}, ...
        true, false, "Not evaluated without the frozen common baseline.", ...
        heldout.blocked_reason(1));
end

tables_built = height(same_snapshot) > 0 && height(cut_flows) == 5 && ...
    height(physical) == 7 && height(heldout) == 12 && ...
    height(heldout_metrics) == 432;
gates = append_gate(gates, "orchestration", "six_output_tables_built", ...
    "artifact", double(tables_built), 1, "==", true, tables_built, ...
    "All six output schemas, including this ledger, are constructed.", ...
    blocked_if_false(tables_built, "output_schema_incomplete"));
gates = append_gate(gates, "orchestration", "promotion_remains_false", ...
    "safety_policy", 1, 1, "==", true, true, ...
    "This runner cannot promote or tag S13.", "");
end

function pass = heldout_detail_schema_complete(rows, heldout)
expected_metric = ["delta_pf_mw"; "delta_qf_mvar"; ...
    "delta_series_current_kA"; "delta_vm_pu"; ...
    "delta_aligned_va_deg"; "delta_E_G_cut_mw"; ...
    "delta_E_F_cut_mw"; "delta_internal_NY_active_loss_mw"];
expected_count = [84; 84; 84; 72; 72; 12; 12; 12];
pass = height(rows) == 432 && ...
    isequal(unique(rows.perturbation_id, 'stable'), heldout.perturbation_id) && ...
    all(strlength(rows.balancing_policy_id) > 0) && ...
    all(~rows.refit_performed) && all(rows.execution_status == "blocked") && ...
    all(rows.gate_status == "blocked");
for k = 1:numel(expected_metric)
    pass = pass && nnz(rows.metric_id == expected_metric(k)) == ...
        expected_count(k);
end
future_fields = {'oracle_baseline_value','oracle_perturbed_value', ...
    'oracle_delta_value','s13_baseline_value','s13_perturbed_value', ...
    's13_delta_value','delta_absolute_error','delta_error_percent'};
for k = 1:numel(future_fields)
    pass = pass && all(isnan(rows.(future_fields{k})));
end
keys = rows.perturbation_id + "|" + rows.entity_type + "|" + ...
    rows.entity_id + "|" + rows.metric_id;
pass = pass && numel(unique(keys)) == height(rows);
for k = 1:height(heldout)
    scenario = rows.perturbation_id == heldout.perturbation_id(k);
    physical = scenario & rows.entity_type == "physical_circuit";
    terminal = scenario & rows.entity_type == "terminal";
    system = scenario & rows.entity_type == "system";
    pass = pass && nnz(scenario) == 36 && nnz(physical) == 21 && ...
        nnz(terminal) == 12 && nnz(system) == 3 && ...
        numel(unique(rows.entity_id(physical))) == 7 && ...
        numel(unique(rows.entity_id(terminal))) == 6 && ...
        numel(unique(rows.entity_id(system))) == 3;
end
end

function out = append_gate(out, stage, id, kind, value, limit, comparator, ...
        required, passed, evidence, blocked_reason)
if passed
    status = "pass";
elseif strlength(string(blocked_reason)) > 0
    status = "blocked_fail_closed";
else
    status = "fail";
end
row = table(string(stage), string(id), string(kind), double(value), ...
    double(limit), string(comparator), logical(required), logical(passed), ...
    status, string(evidence), string(blocked_reason), ...
    'VariableNames', {'stage','gate_id','gate_kind','metric_value','limit', ...
    'comparator','required','passed','status','evidence','blocked_reason'});
if isempty(out), out = row; else, out = [out; row]; end
end

function reason = blocked_if_false(flag, value)
if flag, reason = ""; else, reason = string(value); end
end

function value = clean_token(value)
value = upper(regexprep(strtrim(string(value)), '[^A-Z0-9]+', '_'));
value = regexprep(value, '^_|_$', '');
end

function error_percent = percent_error(reference, value)
error_percent = nan(size(reference));
finite = isfinite(reference) & isfinite(value);
nonzero = finite & abs(reference) > 1e-12;
error_percent(nonzero) = 100 * abs(value(nonzero)-reference(nonzero)) ./ ...
    abs(reference(nonzero));
both_zero = finite & abs(reference) <= 1e-12 & ...
    abs(value-reference) <= 1e-12;
error_percent(both_zero) = 0;
end
