function out = run_s13_phase1a_local_identity(options)
%RUN_S13_PHASE1A_LOCAL_IDENTITY Validate the exact Phase-1A local overlay.
%   This is a no-fit electrical identity test. It uses the Q-limit-solved
%   full PERFORM case as the source reference, recomputes terminal flows for
%   the seven copied branches from the solved complex voltages, and solves a
%   six-bus local network with EDIC and RAMAPO held at their source phasors.
%
%   The four interior buses have zero source PD/QD/GS/BS and no online
%   generators, but they are not zero-injection buses after the rest of the
%   PERFORM network is removed. Therefore, the exact local solve includes
%   fixed complex-power injections derived from the omitted incident-network
%   currents. A second zero-injection solve is retained only as a diagnostic;
%   it never contributes to the acceptance gates.

if nargin < 1, options = struct(); end

helper_dir = fileparts(mfilename('fullpath'));
case_dir = fileparts(helper_dir);
root = fileparts(case_dir);
perform_dir = fullfile(root, 'PERFORM', ...
    'On Peak 2019 v23_Perform_NY', 'On Peak 2019 v23');
options = defaults(options, helper_dir, perform_dir);
addpath(case_dir); addpath(helper_dir); addpath(perform_dir);
define_constants;

candidate = loadcase(options.s13_case);
overlay = overlay_report(candidate);
physical = overlay.physical_register;
physical = physical(physical.overlay_path_id == ...
    "phase1a_e_g_edic_ramapo", :);
if height(physical) ~= 7
    error('run_s13_phase1a_local_identity:PhysicalRegister', ...
        'The Phase-1A E-G path must contain exactly seven physical rows.');
end

source_case = loadcase(options.source_case);
source_results = runpf(source_case, mpoption( ...
    'verbose', 0, 'out.all', 0, 'pf.enforce_q_lims', 1));
if ~source_results.success
    error('run_s13_phase1a_local_identity:SourcePF', ...
        'The full PERFORM Q-limit source power flow did not converge.');
end

source_rows = double(physical.source_branch_row);
source_from = double(physical.source_from_bus);
source_to = double(physical.source_to_bus);
model_rows = double(physical.model_branch_row);
model_from = double(physical.model_from_bus);
model_to = double(physical.model_to_bus);

assert_branch_mapping(source_results, candidate, source_rows, source_from, ...
    source_to, model_rows, model_from, model_to);
source_phasors = evaluate_network_phasors(source_results);

boundary_bus = [1233; 1519];
interior_bus = [1228; 1222; 1567; 772];
local_bus = [boundary_bus; interior_bus];

[omitted, equivalent_injection] = omitted_injection_table( ...
    source_results, source_phasors, interior_bus, local_bus, source_rows);

injection_case = build_local_case(source_results, local_bus, boundary_bus, ...
    interior_bus, source_rows, equivalent_injection);
injection_results = runpf(injection_case, mpoption( ...
    'verbose', 0, 'out.all', 0, 'pf.enforce_q_lims', 0));

zero_case = build_local_case(source_results, local_bus, boundary_bus, ...
    interior_bus, source_rows, zeros(numel(interior_bus), 1));
zero_results = runpf(zero_case, mpoption( ...
    'verbose', 0, 'out.all', 0, 'pf.enforce_q_lims', 0));

[raw_branch_row, raw_circuit_id] = raw_branch_identity( ...
    options.raw_file, source_results, source_rows);

[s12_results, s12_branch_rows, s12_bus_rows] = s12_snapshot( ...
    options.s12_workspace, source_results, source_rows, local_bus);

identity = branch_identity_table(source_results, source_phasors, ...
    injection_results, zero_results, s12_results, physical, ...
    raw_branch_row, raw_circuit_id, s12_branch_rows, candidate);
voltages = voltage_table(source_results, injection_results, zero_results, ...
    s12_results, candidate, overlay.bus_map, local_bus, boundary_bus, ...
    s12_bus_rows);

gates = gate_ledger(source_results, injection_results, s12_results, ...
    identity, omitted, voltages);
all_mandatory_pass = all(gates.pass(gates.mandatory));

files = struct( ...
    'local_identity', fullfile(options.output_dir, ...
        's13_phase1a_local_identity.csv'), ...
    'omitted_injections', fullfile(options.output_dir, ...
        's13_phase1a_local_omitted_injections.csv'), ...
    'terminal_voltages', fullfile(options.output_dir, ...
        's13_phase1a_terminal_voltage_comparison.csv'));
if options.write_outputs
    if ~isfolder(options.output_dir)
        error('run_s13_phase1a_local_identity:OutputDirectory', ...
            'Output directory does not exist: %s', options.output_dir);
    end
    ny_lite_writetable_lf(identity, files.local_identity);
    ny_lite_writetable_lf(omitted, files.omitted_injections);
    ny_lite_writetable_lf(voltages, files.terminal_voltages);
end

out = struct( ...
    'pass', all_mandatory_pass, ...
    'source_results', source_results, ...
    'injection_results', injection_results, ...
    'zero_injection_results', zero_results, ...
    's12_results', s12_results, ...
    'local_identity', identity, ...
    'omitted_injections', omitted, ...
    'terminal_voltages', voltages, ...
    'gate_ledger', gates, ...
    'zero_injection_is_gating', false, ...
    'files', files);

if options.verbose
    fprintf(['S13 Phase-1A local identity: %d/%d mandatory gates pass; ' ...
        'direct max P/Q %.3g/%.3g; local max P/Q %.3g/%.3g; ' ...
        'VM/VA %.3g/%.3g.\n'], nnz(gates.pass(gates.mandatory)), ...
        nnz(gates.mandatory), ...
        max(identity.direct_max_p_error_mw), ...
        max(identity.direct_max_q_error_mvar), ...
        max(identity.injection_max_p_error_mw), ...
        max(identity.injection_max_q_error_mvar), ...
        max(voltages.injection_vm_error_pu(voltages.terminal_role == ...
            "interior_pq")), ...
        max(voltages.injection_va_error_deg(voltages.terminal_role == ...
            "interior_pq")));
    fprintf(['  Zero-injection truncation is diagnostic only: max VM/VA ' ...
        'errors %.4g pu / %.4g deg.\n'], ...
        max(voltages.zero_injection_vm_error_pu), ...
        max(voltages.zero_injection_va_error_deg));
end

if options.fail_on_gate && ~all_mandatory_pass
    failed = gates.gate_id(gates.mandatory & ~gates.pass);
    error('run_s13_phase1a_local_identity:GateFailure', ...
        'Mandatory local-identity gates failed: %s', ...
        strjoin(cellstr(failed), ', '));
end
end

function options = defaults(options, helper_dir, perform_dir)
if ~isfield(options, 'write_outputs'), options.write_outputs = true; end
if ~isfield(options, 'fail_on_gate'), options.fail_on_gate = true; end
if ~isfield(options, 'verbose'), options.verbose = true; end
if ~isfield(options, 'output_dir'), options.output_dir = helper_dir; end
if ~isfield(options, 's13_case')
    options.s13_case = 'npcc_ny_lite_s13_npcc_augmented_2019';
end
if ~isfield(options, 'source_case')
    options.source_case = 'nyiso_On_Peak_v23_shunts_as_z_load';
end
if ~isfield(options, 'raw_file')
    options.raw_file = fullfile(perform_dir, ...
        'NYISO_onpeak2019_v23_shuntsRgens.RAW');
end
if ~isfield(options, 's12_workspace')
    options.s12_workspace = fullfile(helper_dir, ...
        's12_reduction_workspace.mat');
end
end

function report = overlay_report(candidate)
if ~isfield(candidate, 'userdata') || ~isfield(candidate.userdata, 's13')
    error('run_s13_phase1a_local_identity:MissingS13Metadata', ...
        'The candidate does not contain S13 metadata.');
end
s13 = candidate.userdata.s13;
if isfield(s13, 'overlay_report')
    report = s13.overlay_report;
elseif isfield(s13, 'phase1a_report')
    report = s13.phase1a_report;
else
    error('run_s13_phase1a_local_identity:MissingOverlayReport', ...
        'The candidate does not contain an overlay report.');
end
required = {'physical_register', 'bus_map'};
for k = 1:numel(required)
    if ~isfield(report, required{k}) || ~istable(report.(required{k}))
        error('run_s13_phase1a_local_identity:MissingOverlayTable', ...
            'Overlay report table %s is missing.', required{k});
    end
end
end

function assert_branch_mapping(source, candidate, source_rows, source_from, ...
        source_to, model_rows, model_from, model_to)
define_constants;
if any(source_rows < 1 | source_rows > size(source.branch, 1)) || ...
        any(model_rows < 1 | model_rows > size(candidate.branch, 1))
    error('run_s13_phase1a_local_identity:BranchRowRange', ...
        'A registered source or S13 branch row is out of range.');
end
source_endpoints = source.branch(source_rows, [F_BUS T_BUS]);
model_endpoints = candidate.branch(model_rows, [F_BUS T_BUS]);
if ~isequal(source_endpoints, [source_from source_to]) || ...
        ~isequal(model_endpoints, [model_from model_to])
    error('run_s13_phase1a_local_identity:BranchEndpoint', ...
        'A registered source or S13 branch endpoint changed.');
end
cols = [BR_R BR_X BR_B RATE_A RATE_B RATE_C TAP SHIFT BR_STATUS];
if any(abs(candidate.branch(model_rows, cols) - ...
        source.branch(source_rows, cols)) > 1e-12, 'all')
    error('run_s13_phase1a_local_identity:BranchParameter', ...
        'A copied S13 physical branch no longer matches its source row.');
end
end

function q = evaluate_network_phasors(results)
define_constants;
internal = ext2int(results);
[~, Yf, Yt] = makeYbus(internal.baseMVA, internal.bus, internal.branch);
V = internal.bus(:, VM) .* exp(1j * pi/180 * internal.bus(:, VA));
If = Yf * V;
It = Yt * V;
Sf = V(internal.branch(:, F_BUS)) .* conj(If) * internal.baseMVA;
St = V(internal.branch(:, T_BUS)) .* conj(It) * internal.baseMVA;
on = internal.order.branch.status.on(:);
nl = size(results.branch, 1);
q.If = complex(zeros(nl, 1));
q.It = complex(zeros(nl, 1));
q.Sf = complex(zeros(nl, 1));
q.St = complex(zeros(nl, 1));
q.If(on) = If; q.It(on) = It; q.Sf(on) = Sf; q.St(on) = St;
q.active_external_rows = on;
end

function [rows, Seq] = omitted_injection_table(results, phasors, ...
        interior_bus, local_bus, retained_rows)
define_constants;
n = numel(interior_bus);
source_bus_name = strings(n, 1);
source_vm_pu = zeros(n, 1); source_va_deg = zeros(n, 1);
source_pd_mw = zeros(n, 1); source_qd_mvar = zeros(n, 1);
source_gs_mw = zeros(n, 1); source_bs_mvar = zeros(n, 1);
online_generator_count = zeros(n, 1);
retained_incident_count = zeros(n, 1);
omitted_incident_count = zeros(n, 1);
omitted_branch_rows = strings(n, 1);
unregistered_local_branch_count = zeros(n, 1);
retained_I = complex(zeros(n, 1));
omitted_I = complex(zeros(n, 1));
Seq = complex(zeros(n, 1));
retained_S = complex(zeros(n, 1));
source_zero_device_pass = false(n, 1);
partition_pass = false(n, 1);

for k = 1:n
    id = interior_bus(k);
    bi = find(results.bus(:, BUS_I) == id, 1);
    if isempty(bi)
        error('run_s13_phase1a_local_identity:InteriorBus', ...
            'Source interior bus %d is missing.', id);
    end
    source_bus_name(k) = bus_name(results, bi);
    source_vm_pu(k) = results.bus(bi, VM);
    source_va_deg(k) = results.bus(bi, VA);
    source_pd_mw(k) = results.bus(bi, PD);
    source_qd_mvar(k) = results.bus(bi, QD);
    source_gs_mw(k) = results.bus(bi, GS);
    source_bs_mvar(k) = results.bus(bi, BS);
    online_generator_count(k) = nnz(results.gen(:, GEN_BUS) == id & ...
        results.gen(:, GEN_STATUS) > 0);
    source_zero_device_pass(k) = ...
        all(abs(results.bus(bi, [PD QD GS BS])) <= 1e-10) && ...
        online_generator_count(k) == 0;

    incident = find(results.branch(:, BR_STATUS) > 0 & ...
        (results.branch(:, F_BUS) == id | results.branch(:, T_BUS) == id));
    retained = incident(ismember(incident, retained_rows));
    omitted = incident(~ismember(incident, retained_rows));
    retained_incident_count(k) = numel(retained);
    omitted_incident_count(k) = numel(omitted);
    omitted_branch_rows(k) = join(string(omitted(:)'), ';');
    both_local = ismember(results.branch(omitted, F_BUS), local_bus) & ...
        ismember(results.branch(omitted, T_BUS), local_bus);
    unregistered_local_branch_count(k) = nnz(both_local);
    partition_pass(k) = ~isempty(retained) && ~isempty(omitted) && ...
        unregistered_local_branch_count(k) == 0;

    retained_I(k) = bus_terminal_current(results, phasors, retained, id);
    omitted_I(k) = bus_terminal_current(results, phasors, omitted, id);
    Seq(k) = results.bus(bi, VM) * ...
        exp(1j*pi/180*results.bus(bi, VA)) * conj(-omitted_I(k)) * ...
        results.baseMVA;
    retained_S(k) = results.bus(bi, VM) * ...
        exp(1j*pi/180*results.bus(bi, VA)) * conj(retained_I(k)) * ...
        results.baseMVA;
end

kcl = retained_I + omitted_I;
rows = table(interior_bus, source_bus_name, source_vm_pu, source_va_deg, ...
    source_pd_mw, source_qd_mvar, source_gs_mw, source_bs_mvar, ...
    online_generator_count, retained_incident_count, omitted_incident_count, ...
    omitted_branch_rows, unregistered_local_branch_count, ...
    real(retained_I), imag(retained_I), real(omitted_I), imag(omitted_I), ...
    real(-omitted_I), imag(-omitted_I), real(Seq), imag(Seq), ...
    real(retained_S), imag(retained_S), abs(kcl), ...
    abs(retained_S - Seq), source_zero_device_pass, partition_pass, ...
    repmat("source_derived_fixed_complex_power", n, 1), ...
    'VariableNames', {'source_bus','source_bus_name','source_vm_pu', ...
    'source_va_deg','source_pd_mw','source_qd_mvar','source_gs_mw', ...
    'source_bs_mvar','online_generator_count','retained_incident_count', ...
    'omitted_incident_count','omitted_source_branch_rows', ...
    'unregistered_local_branch_count','retained_current_real_pu', ...
    'retained_current_imag_pu','omitted_current_real_pu', ...
    'omitted_current_imag_pu','equivalent_injection_current_real_pu', ...
    'equivalent_injection_current_imag_pu', ...
    'equivalent_injection_p_mw','equivalent_injection_q_mvar', ...
    'retained_terminal_p_mw','retained_terminal_q_mvar', ...
    'source_kcl_residual_current_pu','injection_closure_error_mva', ...
    'source_zero_device_pass','network_partition_pass','injection_policy'});
end

function I = bus_terminal_current(results, phasors, branch_rows, bus_id)
define_constants;
I = complex(0);
for r = branch_rows(:)'
    if results.branch(r, F_BUS) == bus_id
        I = I + phasors.If(r);
    elseif results.branch(r, T_BUS) == bus_id
        I = I + phasors.It(r);
    else
        error('run_s13_phase1a_local_identity:IncidentBranch', ...
            'Branch row %d is not incident on bus %d.', r, bus_id);
    end
end
end

function local = build_local_case(source, local_bus, boundary_bus, ...
        interior_bus, source_rows, Seq)
define_constants;
[found, source_bi] = ismember(local_bus, source.bus(:, BUS_I));
if ~all(found)
    error('run_s13_phase1a_local_identity:LocalBus', ...
        'One or more local source buses are missing.');
end
local = struct('version', '2', 'baseMVA', source.baseMVA);
local.bus = source.bus(source_bi, :);
local.branch = source.branch(source_rows, 1:ANGMAX);
local.bus(:, [PD QD GS BS]) = 0;
local.bus(ismember(local.bus(:, BUS_I), boundary_bus), BUS_TYPE) = REF;
local.bus(ismember(local.bus(:, BUS_I), interior_bus), BUS_TYPE) = PQ;
for k = 1:numel(interior_bus)
    bi = find(local.bus(:, BUS_I) == interior_bus(k), 1);
    local.bus(bi, PD) = -real(Seq(k));
    local.bus(bi, QD) = -imag(Seq(k));
end
ngcol = max(size(source.gen, 2), 21);
local.gen = zeros(numel(boundary_bus), ngcol);
for k = 1:numel(boundary_bus)
    bi = find(local.bus(:, BUS_I) == boundary_bus(k), 1);
    local.gen(k, GEN_BUS) = boundary_bus(k);
    local.gen(k, QMAX) = 1e6;
    local.gen(k, QMIN) = -1e6;
    local.gen(k, VG) = local.bus(bi, VM);
    local.gen(k, MBASE) = local.baseMVA;
    local.gen(k, GEN_STATUS) = 1;
    local.gen(k, PMAX) = 1e6;
    local.gen(k, PMIN) = -1e6;
end
if isfield(source, 'bus_name')
    local.bus_name = source.bus_name(source_bi);
end
end

function [raw_rows, raw_ids] = raw_branch_identity(raw_file, source, source_rows)
define_constants;
if ~isfile(raw_file)
    error('run_s13_phase1a_local_identity:RawFile', ...
        'The PERFORM RAW source file is missing: %s', raw_file);
end
[records, sections] = psse_read(raw_file, 0);
[data, ~] = psse_parse(records, sections, 0, 33);
raw_num = data.branch.num;
raw_txt = data.branch.txt;
raw_rows = nan(numel(source_rows), 1);
raw_ids = strings(numel(source_rows), 1);
for k = 1:numel(source_rows)
    sr = source_rows(k);
    f = source.branch(sr, F_BUS);
    t = source.branch(sr, T_BUS);
    params = source.branch(sr, [BR_R BR_X BR_B]);
    parameter_match = max(abs(raw_num(:, 4:6) - params), [], 2) <= 1e-10;
    match = find(raw_num(:, 1) == f & raw_num(:, 2) == t & ...
        parameter_match);
    if numel(match) ~= 1
        error('run_s13_phase1a_local_identity:RawBranchIdentity', ...
            ['Source branch row %d (%d-%d) maps to %d RAW branch rows; ' ...
            'expected exactly one.'], sr, f, t, numel(match));
    end
    raw_rows(k) = match;
    raw_ids(k) = upper(strtrim(erase(string(raw_txt{match, 3}), "'")));
end
end

function [result, branch_rows, bus_rows] = s12_snapshot( ...
        workspace_file, source, source_rows, source_bus)
define_constants;
if ~isfile(workspace_file)
    error('run_s13_phase1a_local_identity:S12Workspace', ...
        'The S12 reduction workspace is missing: %s', workspace_file);
end
ws = load(workspace_file, 'red', 'src2red_branch', 'retained_ids');
required = {'red', 'src2red_branch', 'retained_ids'};
for k = 1:numel(required)
    if ~isfield(ws, required{k})
        error('run_s13_phase1a_local_identity:S12WorkspaceField', ...
            'S12 workspace field %s is missing.', required{k});
    end
end
reduced = ws.red;
if size(reduced.gen, 1) ~= size(source.gen, 1)
    error('run_s13_phase1a_local_identity:S12GeneratorAlignment', ...
        'S12 and source generator rows are not aligned.');
end
for g = 1:size(reduced.gen, 1)
    if reduced.gen(g, GEN_STATUS) > 0
        reduced.gen(g, PG) = source.gen(g, PG);
        reduced.gen(g, QG) = source.gen(g, QG);
        reduced.gen(g, VG) = reduced.bus(reduced.gen(g, GEN_BUS), VM);
    end
end
result = runpf(reduced, mpoption('verbose', 0, 'out.all', 0));
branch_rows = double(ws.src2red_branch(source_rows));
bus_rows = nan(numel(source_bus), 1);
for k = 1:numel(source_bus)
    bus_rows(k) = find(ws.retained_ids == source_bus(k), 1);
end
end

function tbl = branch_identity_table(source, phasors, injection, zero, ...
        s12, physical, raw_rows, raw_ids, s12_rows, candidate)
define_constants;
sr = double(physical.source_branch_row);
mr = double(physical.model_branch_row);
n = height(physical);
source_flow = source.branch(sr, PF:QT);
direct_flow = [real(phasors.Sf(sr)) imag(phasors.Sf(sr)) ...
    real(phasors.St(sr)) imag(phasors.St(sr))];
injection_flow = injection.branch(:, PF:QT);
zero_flow = zero.branch(:, PF:QT);
s12_flow = s12.branch(s12_rows, PF:QT);
direct_error = direct_flow - source_flow;
injection_error = injection_flow - source_flow;
zero_error = zero_flow - source_flow;
s12_error = s12_flow - source_flow;

[~, source_fi] = ismember(source.branch(sr, F_BUS), source.bus(:, BUS_I));
[~, source_ti] = ismember(source.branch(sr, T_BUS), source.bus(:, BUS_I));
from_current = abs(phasors.If(sr)) .* source.baseMVA ./ ...
    (sqrt(3) * source.bus(source_fi, BASE_KV));
to_current = abs(phasors.It(sr)) .* source.baseMVA ./ ...
    (sqrt(3) * source.bus(source_ti, BASE_KV));

orientation_match = source.branch(sr, F_BUS) == physical.source_from_bus & ...
    source.branch(sr, T_BUS) == physical.source_to_bus & ...
    candidate.branch(mr, F_BUS) == physical.model_from_bus & ...
    candidate.branch(mr, T_BUS) == physical.model_to_bus;
ckt_identity_match = raw_ids == string(physical.source_circuit_id);
cols = [BR_R BR_X BR_B RATE_A RATE_B RATE_C TAP SHIFT BR_STATUS];
s13_parameter_identity_match = ...
    max(abs(candidate.branch(mr, cols) - source.branch(sr, cols)), [], 2) ...
    <= 1e-12;
direct_p = max(abs(direct_error(:, [1 3])), [], 2);
direct_q = max(abs(direct_error(:, [2 4])), [], 2);
injection_p = max(abs(injection_error(:, [1 3])), [], 2);
injection_q = max(abs(injection_error(:, [2 4])), [], 2);
s12_p = max(abs(s12_error(:, [1 3])), [], 2);
s12_q = max(abs(s12_error(:, [2 4])), [], 2);

tbl = table(sr, source.branch(sr, F_BUS), source.branch(sr, T_BUS), ...
    string(physical.source_circuit_id), raw_rows, raw_ids, s12_rows, mr, ...
    double(physical.model_from_bus), double(physical.model_to_bus), ...
    source_flow(:,1), source_flow(:,2), source_flow(:,3), source_flow(:,4), ...
    direct_flow(:,1), direct_flow(:,2), direct_flow(:,3), direct_flow(:,4), ...
    direct_error(:,1), direct_error(:,2), direct_error(:,3), direct_error(:,4), ...
    injection_flow(:,1), injection_flow(:,2), ...
    injection_flow(:,3), injection_flow(:,4), ...
    injection_error(:,1), injection_error(:,2), ...
    injection_error(:,3), injection_error(:,4), ...
    s12_flow(:,1), s12_flow(:,2), s12_flow(:,3), s12_flow(:,4), ...
    s12_error(:,1), s12_error(:,2), s12_error(:,3), s12_error(:,4), ...
    zero_flow(:,1), zero_flow(:,2), zero_flow(:,3), zero_flow(:,4), ...
    zero_error(:,1), zero_error(:,2), zero_error(:,3), zero_error(:,4), ...
    from_current, to_current, direct_p, direct_q, injection_p, injection_q, ...
    s12_p, s12_q, orientation_match, ckt_identity_match, ...
    s13_parameter_identity_match, ...
    direct_p <= 1e-6 & direct_q <= 1e-6, ...
    injection_p <= 0.05 & injection_q <= 0.10, ...
    s12_p <= 0.20 & s12_q <= 0.20, ...
    repmat("diagnostic_only_not_gating", n, 1), ...
    'VariableNames', {'source_branch_row','source_from_bus','source_to_bus', ...
    'source_circuit_id','raw_branch_row','raw_circuit_id', ...
    's12_reduced_branch_row','s13_model_branch_row','s13_model_from_bus', ...
    's13_model_to_bus','source_pf_mw','source_qf_mvar','source_pt_mw', ...
    'source_qt_mvar','direct_pf_mw','direct_qf_mvar','direct_pt_mw', ...
    'direct_qt_mvar','direct_pf_error_mw','direct_qf_error_mvar', ...
    'direct_pt_error_mw','direct_qt_error_mvar','injection_pf_mw', ...
    'injection_qf_mvar','injection_pt_mw','injection_qt_mvar', ...
    'injection_pf_error_mw','injection_qf_error_mvar', ...
    'injection_pt_error_mw','injection_qt_error_mvar','s12_pf_mw', ...
    's12_qf_mvar','s12_pt_mw','s12_qt_mvar','s12_pf_error_mw', ...
    's12_qf_error_mvar','s12_pt_error_mw','s12_qt_error_mvar', ...
    'zero_injection_pf_mw','zero_injection_qf_mvar', ...
    'zero_injection_pt_mw','zero_injection_qt_mvar', ...
    'zero_injection_pf_error_mw','zero_injection_qf_error_mvar', ...
    'zero_injection_pt_error_mw','zero_injection_qt_error_mvar', ...
    'source_from_terminal_current_ka','source_to_terminal_current_ka', ...
    'direct_max_p_error_mw','direct_max_q_error_mvar', ...
    'injection_max_p_error_mw','injection_max_q_error_mvar', ...
    's12_max_p_error_mw','s12_max_q_error_mvar','orientation_match', ...
    'raw_circuit_identity_match','s13_parameter_identity_match', ...
    'direct_phasor_identity_pass','injection_solution_branch_pass', ...
    's12_readonly_oracle_branch_pass','zero_injection_acceptance_role'});
end

function tbl = voltage_table(source, injection, zero, s12, candidate, ...
        bus_map, source_bus, boundary_bus, s12_bus_rows)
define_constants;
n = numel(source_bus);
source_bus_name = strings(n, 1);
terminal_role = repmat("interior_pq", n, 1);
terminal_role(ismember(source_bus, boundary_bus)) = "fixed_boundary";
s13_model_bus = nan(n, 1); s13_model_bus_row = nan(n, 1);
s13_inherited_vm_pu = nan(n, 1); s13_inherited_va_deg = nan(n, 1);
source_vm_pu = nan(n, 1); source_va_deg = nan(n, 1);
injection_vm_pu = nan(n, 1); injection_va_deg = nan(n, 1);
zero_vm_pu = nan(n, 1); zero_va_deg = nan(n, 1);
s12_vm_pu = nan(n, 1); s12_va_deg = nan(n, 1);
for k = 1:n
    sb = source_bus(k);
    si = find(source.bus(:, BUS_I) == sb, 1);
    ii = find(injection.bus(:, BUS_I) == sb, 1);
    zi = find(zero.bus(:, BUS_I) == sb, 1);
    mi = find(bus_map.source_bus == sb, 1);
    if any(cellfun(@isempty, {si, ii, zi, mi}))
        error('run_s13_phase1a_local_identity:VoltageMapping', ...
            'Voltage mapping for source bus %d is incomplete.', sb);
    end
    source_bus_name(k) = bus_name(source, si);
    s13_model_bus(k) = bus_map.model_bus(mi);
    s13_model_bus_row(k) = find(candidate.bus(:, BUS_I) == ...
        s13_model_bus(k), 1);
    s13_inherited_vm_pu(k) = candidate.bus(s13_model_bus_row(k), VM);
    s13_inherited_va_deg(k) = candidate.bus(s13_model_bus_row(k), VA);
    source_vm_pu(k) = source.bus(si, VM);
    source_va_deg(k) = source.bus(si, VA);
    injection_vm_pu(k) = injection.bus(ii, VM);
    injection_va_deg(k) = injection.bus(ii, VA);
    zero_vm_pu(k) = zero.bus(zi, VM);
    zero_va_deg(k) = zero.bus(zi, VA);
    s12_vm_pu(k) = s12.bus(s12_bus_rows(k), VM);
    s12_va_deg(k) = s12.bus(s12_bus_rows(k), VA);
end

tbl = table(source_bus, source_bus_name, terminal_role, s13_model_bus, ...
    s13_model_bus_row, s12_bus_rows, source_vm_pu, source_va_deg, ...
    injection_vm_pu, injection_va_deg, ...
    abs(injection_vm_pu-source_vm_pu), ...
    abs(angle_difference(injection_va_deg, source_va_deg)), ...
    s12_vm_pu, s12_va_deg, abs(s12_vm_pu-source_vm_pu), ...
    abs(angle_difference(s12_va_deg, source_va_deg)), ...
    zero_vm_pu, zero_va_deg, abs(zero_vm_pu-source_vm_pu), ...
    abs(angle_difference(zero_va_deg, source_va_deg)), ...
    s13_inherited_vm_pu, s13_inherited_va_deg, ...
    repmat("mapping_only_not_source_operating_comparison", n, 1), ...
    repmat("diagnostic_only_not_gating", n, 1), ...
    'VariableNames', {'source_bus','source_bus_name','terminal_role', ...
    's13_model_bus','s13_model_bus_row','s12_reduced_bus_row', ...
    'source_vm_pu','source_va_deg','injection_vm_pu','injection_va_deg', ...
    'injection_vm_error_pu','injection_va_error_deg','s12_vm_pu', ...
    's12_va_deg','s12_vm_error_pu','s12_va_error_deg', ...
    'zero_injection_vm_pu','zero_injection_va_deg', ...
    'zero_injection_vm_error_pu','zero_injection_va_error_deg', ...
    's13_inherited_vm_pu','s13_inherited_va_deg', ...
    's13_inherited_snapshot_role','zero_injection_acceptance_role'});
end

function gates = gate_ledger(source, injection, s12, identity, omitted, voltages)
interior = voltages.terminal_role == "interior_pq";
boundary = voltages.terminal_role == "fixed_boundary";
rows = { ...
    'source_q_limit_pf_converged', double(source.success), 1, '==', true, ...
        source.success, 'full PERFORM Q-limit reference'; ...
    'source_and_model_orientation_exact', double(all(identity.orientation_match)), ...
        1, '==', true, all(identity.orientation_match), 'registered row endpoints'; ...
    'raw_circuit_identity_exact', double(all(identity.raw_circuit_identity_match)), ...
        1, '==', true, all(identity.raw_circuit_identity_match), ...
        'RAW oriented endpoint R/X/B and CKT'; ...
    's13_physical_parameters_exact', double(all(identity.s13_parameter_identity_match)), ...
        1, '==', true, all(identity.s13_parameter_identity_match), ...
        'copied R/X/B/rating/tap/shift/status'; ...
    'source_interior_zero_device_status', ...
        double(all(omitted.source_zero_device_pass)), 1, '==', true, ...
        all(omitted.source_zero_device_pass), 'PD/QD/GS/BS and online generators'; ...
    'omitted_network_partition_valid', ...
        double(all(omitted.network_partition_pass)), 1, '==', true, ...
        all(omitted.network_partition_pass), 'no unregistered local branch'; ...
    'source_kcl_residual_current_pu', ...
        max(omitted.source_kcl_residual_current_pu), 1e-7, '<=', true, ...
        max(omitted.source_kcl_residual_current_pu) <= 1e-7, ...
        'retained plus omitted terminal current'; ...
    'direct_max_p_error_mw', max(identity.direct_max_p_error_mw), ...
        1e-6, '<=', true, max(identity.direct_max_p_error_mw) <= 1e-6, ...
        'Yf/Yt phasor recomputation'; ...
    'direct_max_q_error_mvar', max(identity.direct_max_q_error_mvar), ...
        1e-6, '<=', true, max(identity.direct_max_q_error_mvar) <= 1e-6, ...
        'Yf/Yt phasor recomputation'; ...
    'injection_local_pf_converged', double(injection.success), 1, '==', true, ...
        injection.success, 'two fixed boundary phasors'; ...
    'injection_max_p_error_mw', max(identity.injection_max_p_error_mw), ...
        0.05, '<=', true, max(identity.injection_max_p_error_mw) <= 0.05, ...
        'source-derived omitted-network injections'; ...
    'injection_max_q_error_mvar', max(identity.injection_max_q_error_mvar), ...
        0.10, '<=', true, max(identity.injection_max_q_error_mvar) <= 0.10, ...
        'source-derived omitted-network injections'; ...
    'injection_max_interior_vm_error_pu', ...
        max(voltages.injection_vm_error_pu(interior)), 1e-5, '<=', true, ...
        max(voltages.injection_vm_error_pu(interior)) <= 1e-5, ...
        'four interior buses'; ...
    'injection_max_interior_va_error_deg', ...
        max(voltages.injection_va_error_deg(interior)), 0.001, '<=', true, ...
        max(voltages.injection_va_error_deg(interior)) <= 0.001, ...
        'four interior buses'; ...
    'fixed_boundary_vm_error_pu', ...
        max(voltages.injection_vm_error_pu(boundary)), 1e-10, '<=', true, ...
        max(voltages.injection_vm_error_pu(boundary)) <= 1e-10, ...
        'EDIC and RAMAPO'; ...
    'fixed_boundary_va_error_deg', ...
        max(voltages.injection_va_error_deg(boundary)), 1e-9, '<=', true, ...
        max(voltages.injection_va_error_deg(boundary)) <= 1e-9, ...
        'EDIC and RAMAPO'; ...
    's12_readonly_pf_converged', double(s12.success), 1, '==', true, ...
        s12.success, 'unmodified S12 reduction workspace'; ...
    's12_retained_branch_mapping_complete', ...
        double(all(identity.s12_reduced_branch_row > 0)), 1, '==', true, ...
        all(identity.s12_reduced_branch_row > 0), 'seven retained source rows'; ...
    's12_max_p_error_mw', max(identity.s12_max_p_error_mw), 0.20, '<=', true, ...
        max(identity.s12_max_p_error_mw) <= 0.20, 'read-only oracle consistency'; ...
    's12_max_q_error_mvar', max(identity.s12_max_q_error_mvar), 0.20, '<=', true, ...
        max(identity.s12_max_q_error_mvar) <= 0.20, 'read-only oracle consistency'};
gates = cell2table(rows, 'VariableNames', {'gate_id','metric_value', ...
    'limit','comparator','mandatory','pass','notes'});
gates.gate_id = string(gates.gate_id);
gates.comparator = string(gates.comparator);
gates.notes = string(gates.notes);
end

function d = angle_difference(a, b)
d = mod(a - b + 180, 360) - 180;
end

function name = bus_name(mpc, row)
name = "BUS_" + string(mpc.bus(row, 1));
if isfield(mpc, 'bus_name')
    name = strtrim(string(mpc.bus_name{row}));
end
end
