function outputs = run_s8_1_capability_feasibility_certificate(options)
%RUN_S8_1_CAPABILITY_FEASIBILITY_CERTIFICATE Audit shoulder P capability.
%   Uses the final S8 shoulder AC sensitivity matrix to certify the minimum
%   worst engineering-normalized interface residual under alternative A/B/C
%   capability envelopes. Each linear proposal is then applied to the full
%   nonlinear AC PF on the direct-PERFORM S7 topology.

if nargin < 1, options = struct(); end
helper_dir = fileparts(mfilename('fullpath'));
case_dir = fileparts(helper_dir);
addpath(case_dir); addpath(helper_dir);
options = defaults(options, helper_dir);

scenario_id = string(options.scenario_id);
zones = string(('A':'K')');
interfaces = readtable(options.interface_file, 'TextType', 'string', ...
    'VariableNamingRule', 'preserve');
interfaces = interfaces(string(interfaces.scenario_id) == scenario_id, :);
zonal = readtable(options.zonal_file, 'TextType', 'string', ...
    'VariableNamingRule', 'preserve');
zonal = zonal(string(zonal.scenario_id) == scenario_id, :);
sensitivity = readtable(options.sensitivity_file, 'TextType', 'string', ...
    'VariableNamingRule', 'preserve');
sensitivity = sensitivity(string(sensitivity.scenario_id) == scenario_id, :);
if height(interfaces) ~= 7 || height(zonal) ~= 11 || isempty(sensitivity)
    error('S8.1 inputs are incomplete for scenario %s.', scenario_id);
end

last_iteration = max(sensitivity.iteration);
sensitivity = sensitivity(sensitivity.iteration == last_iteration, :);
interface_names = string(interfaces.interface_name);
generation = vector_by_zone(zonal, zones, 'target_generation_mw');
pmin = vector_by_zone(zonal, zones, 'pmin_mw');
current_pmax = vector_by_zone(zonal, zones, 'pmax_mw');
residual = interfaces.operational_ac_residual_mw;
accuracy = interfaces.accuracy_scale_mw;
K = response_matrix(sensitivity, interface_names, zones);

summary_rows = table();
residual_rows = table();
dual_rows = table();
relaxation_rows = table();
recheck_rows = table();
proposal_rows = table();

for cap_factor = options.abc_cap_factors
    envelope_name = "ABC_CAP_" + token(cap_factor);
    pmax = capability_envelope(current_pmax, zones, cap_factor, ...
        options.inherited_abc_cap_factor);
    strict = solve_minimax(K, residual, accuracy, generation, pmin, pmax);
    [strict_recheck, strict_detail] = nonlinear_recheck(scenario_id, ...
        zones, generation + strict.delta_generation_mw, pmax, options);
    strict_recheck = addvars(strict_recheck, envelope_name, cap_factor, ...
        "strict_min_eta", 'After', 'scenario_id', ...
        'NewVariableNames', {'envelope_name','abc_cap_factor','solution_type'});

    srow = summary_row(scenario_id, envelope_name, cap_factor, ...
        "strict_min_eta", strict, pmax, strict_recheck);
    summary_rows = append_table(summary_rows, srow);
    residual_rows = append_table(residual_rows, residual_table( ...
        scenario_id, envelope_name, "strict_min_eta", interface_names, ...
        residual, strict.predicted_residual_mw, accuracy, strict_detail));
    dual_rows = append_table(dual_rows, dual_table(scenario_id, ...
        envelope_name, "strict_min_eta", zones, generation, pmin, pmax, ...
        strict));
    proposal_rows = append_table(proposal_rows, proposal_table( ...
        scenario_id, envelope_name, "strict_min_eta", zones, generation, ...
        pmin, pmax, strict.delta_generation_mw, zeros(numel(zones), 1)));
    recheck_rows = append_table(recheck_rows, strict_recheck);

    relaxed = solve_minimum_relaxation(K, residual, accuracy, generation, ...
        pmin, pmax, zones, options.relaxation_zones);
    relaxed_pmax = pmax + relaxed.capability_relaxation_mw;
    [relaxed_recheck, relaxed_detail] = nonlinear_recheck(scenario_id, ...
        zones, generation + relaxed.delta_generation_mw, relaxed_pmax, options);
    relaxed_recheck = addvars(relaxed_recheck, envelope_name, cap_factor, ...
        "minimum_abc_relaxation_eta1", 'After', 'scenario_id', ...
        'NewVariableNames', {'envelope_name','abc_cap_factor','solution_type'});
    rrow = summary_row(scenario_id, envelope_name, cap_factor, ...
        "minimum_abc_relaxation_eta1", relaxed, relaxed_pmax, relaxed_recheck);
    summary_rows = append_table(summary_rows, rrow);
    residual_rows = append_table(residual_rows, residual_table( ...
        scenario_id, envelope_name, "minimum_abc_relaxation_eta1", ...
        interface_names, residual, relaxed.predicted_residual_mw, accuracy, ...
        relaxed_detail));
    relaxation_rows = append_table(relaxation_rows, relaxation_table( ...
        scenario_id, envelope_name, zones, relaxed));
    proposal_rows = append_table(proposal_rows, proposal_table( ...
        scenario_id, envelope_name, "minimum_abc_relaxation_eta1", zones, ...
        generation, pmin, relaxed_pmax, relaxed.delta_generation_mw, ...
        relaxed.capability_relaxation_mw));
    recheck_rows = append_table(recheck_rows, relaxed_recheck);
end

local_diagnostics = local_west_central_diagnostics(K, residual, accuracy, ...
    generation, pmin, current_pmax, interface_names);
availability_status = scenario_availability_status(scenario_id, zones, ...
    options.scenario_availability_file);

writetable(summary_rows, options.summary_file);
writetable(residual_rows, options.residual_file);
writetable(dual_rows, options.dual_file);
writetable(relaxation_rows, options.relaxation_file);
writetable(proposal_rows, options.proposal_file);
writetable(recheck_rows, options.recheck_file);
writetable(local_diagnostics, options.local_diagnostic_file);
writetable(availability_status, options.availability_status_file);

outputs = struct('summary_file', options.summary_file, ...
    'residual_file', options.residual_file, 'dual_file', options.dual_file, ...
    'relaxation_file', options.relaxation_file, ...
    'proposal_file', options.proposal_file, 'recheck_file', options.recheck_file, ...
    'local_diagnostic_file', options.local_diagnostic_file, ...
    'availability_status_file', options.availability_status_file, ...
    'scenario_id', scenario_id, 'sensitivity_iteration', last_iteration, ...
    'summary', summary_rows, 'local_diagnostics', local_diagnostics);
end

function options = defaults(options, helper_dir)
items = { ...
    'scenario_id', "S3_2019_SHOULDER_LIGHT_LOAD_PUBLIC"; ...
    'structural_case', 'npcc_ny_lite_s7_seven_interface_perform_direct_candidate'; ...
    'abc_cap_factors', [0.8 0.9 1.0]; ...
    'inherited_abc_cap_factor', 0.8; ...
    'relaxation_zones', ["A"; "B"; "C"]; ...
    'interface_file', fullfile(helper_dir, 's8_structural_vs_operational_interface_residuals.csv'); ...
    'zonal_file', fullfile(helper_dir, 's8_final_zonal_generation.csv'); ...
    'sensitivity_file', fullfile(helper_dir, 's8_ac_sensitivity_history.csv'); ...
    'external_target_file', fullfile(helper_dir, 'ny_external_interface_targets.csv'); ...
    'interface_target_file', fullfile(helper_dir, 'nyiso_public_interface_targets.csv'); ...
    'interface_scale_file', fullfile(helper_dir, 'nyiso_interface_objective_scales.csv'); ...
    'scenario_availability_file', fullfile(helper_dir, 'nyiso_scenario_available_capability.csv'); ...
    'summary_file', fullfile(helper_dir, 's8_1_capability_envelope_summary.csv'); ...
    'residual_file', fullfile(helper_dir, 's8_1_capability_interface_residuals.csv'); ...
    'dual_file', fullfile(helper_dir, 's8_1_capability_bound_duals.csv'); ...
    'relaxation_file', fullfile(helper_dir, 's8_1_capability_relaxation.csv'); ...
    'proposal_file', fullfile(helper_dir, 's8_1_capability_redispatch_proposals.csv'); ...
    'recheck_file', fullfile(helper_dir, 's8_1_capability_nonlinear_recheck.csv'); ...
    'local_diagnostic_file', fullfile(helper_dir, 's8_1_west_central_local_diagnostics.csv'); ...
    'availability_status_file', fullfile(helper_dir, 's8_1_scenario_availability_status.csv')};
for k = 1:size(items, 1)
    if ~isfield(options, items{k, 1}), options.(items{k, 1}) = items{k, 2}; end
end
end

function value = token(x)
value = replace(string(sprintf('%.3g', x)), '.', 'p');
end

function vector = vector_by_zone(tbl, zones, variable)
vector = zeros(numel(zones), 1);
for z = 1:numel(zones)
    idx = find(string(tbl.zone) == zones(z), 1);
    if isempty(idx), error('Zone %s is missing.', zones(z)); end
    vector(z) = tbl.(variable)(idx);
end
end

function K = response_matrix(tbl, interfaces, zones)
K = zeros(numel(interfaces), numel(zones));
for m = 1:numel(interfaces)
    for z = 1:numel(zones)
        idx = find(string(tbl.interface_name) == interfaces(m) & ...
            string(tbl.perturbed_zone) == zones(z), 1);
        if ~isempty(idx), K(m, z) = tbl.sensitivity_mw_per_mw(idx); end
    end
end
end

function pmax = capability_envelope(current, zones, factor, inherited_factor)
pmax = current;
abc = ismember(zones, ["A"; "B"; "C"]);
base_target = current(abc) / inherited_factor;
pmax(abc) = base_target * factor;
end

function solution = solve_minimax(K, residual, accuracy, generation, pmin, pmax)
nz = numel(generation);
f = [zeros(nz, 1); 1];
A = [K, -accuracy; -K, -accuracy];
b = [-residual; residual];
Aeq = [ones(1, nz), 0];
beq = 0;
lb = [pmin - generation; 0];
ub = [pmax - generation; Inf];
opts = optimoptions('linprog', 'Display', 'none');
[x, fval, exitflag, output, lambda] = linprog(f, A, b, ...
    Aeq, beq, lb, ub, opts);
if exitflag <= 0
    error('S8.1 strict minimax LP failed: %s', output.message);
end
solution = struct('exitflag', exitflag, 'objective', fval, ...
    'eta', x(end), 'delta_generation_mw', x(1:nz), ...
    'capability_relaxation_mw', zeros(nz, 1), ...
    'predicted_residual_mw', residual + K * x(1:nz), ...
    'upper_bound_dual', lambda.upper(1:nz), ...
    'lower_bound_dual', lambda.lower(1:nz), ...
    'capability_constraint_lp_dual', zeros(nz, 1), ...
    'capability_constraint_secondary_qp_dual', zeros(nz, 1));
end

function solution = solve_minimum_relaxation(K, residual, accuracy, ...
        generation, pmin, pmax, zones, allowed_zones)
nz = numel(generation);
nm = numel(residual);
% First stage: minimum added capability needed to enter every accuracy band.
f = [zeros(nz, 1); ones(nz, 1)];
Aflow = [K, zeros(nm, nz); -K, zeros(nm, nz)];
bflow = [accuracy - residual; accuracy + residual];
Acap = [eye(nz), -eye(nz)];
bcap = pmax - generation;
A = [Aflow; Acap];
b = [bflow; bcap];
Aeq = [ones(1, nz), zeros(1, nz)];
beq = 0;
lb = [pmin - generation; zeros(nz, 1)];
ub = [inf(nz, 1); inf(nz, 1)];
ub(nz + find(~ismember(zones, allowed_zones))) = 0;
opts = optimoptions('linprog', 'Display', 'none');
[x1, fval, exitflag, output, lambda1] = linprog(f, A, b, ...
    Aeq, beq, lb, ub, opts);
if exitflag <= 0
    error('S8.1 minimum-relaxation LP failed: %s', output.message);
end
lp_dual = capability_dual(lambda1, nm, nz);

% Second stage: retain the minimum relaxation and choose a minimum-norm
% redispatch so the nonlinear recheck is not driven to an arbitrary LP corner.
A2 = [A; zeros(1, nz), ones(1, nz)];
b2 = [b; fval + 1e-6];
H = blkdiag(diag(1 ./ max(100, pmax).^2), 1e-8 * eye(nz));
qopts = optimoptions('quadprog', 'Display', 'none');
[x, ~, qexit, ~, lambda] = quadprog(H, zeros(2 * nz, 1), ...
    A2, b2, Aeq, beq, lb, ub, x1, qopts);
if qexit <= 0
    x = x1;
    lambda = lambda1;
end
delta = x(1:nz);
relaxation = x(nz + 1:end);
solution = struct('exitflag', exitflag, 'objective', sum(relaxation), ...
    'eta', max(abs((residual + K * delta) ./ accuracy)), ...
    'delta_generation_mw', delta, ...
    'capability_relaxation_mw', relaxation, ...
    'predicted_residual_mw', residual + K * delta, ...
    'upper_bound_dual', zeros(nz, 1), 'lower_bound_dual', zeros(nz, 1), ...
    'capability_constraint_lp_dual', lp_dual, ...
    'capability_constraint_secondary_qp_dual', ...
    capability_dual(lambda, nm, nz));
end

function values = capability_dual(lambda, nm, nz)
values = zeros(nz, 1);
if isstruct(lambda) && isfield(lambda, 'ineqlin') && ...
        numel(lambda.ineqlin) >= 2 * nm + nz
    values = lambda.ineqlin(2 * nm + (1:nz));
end
end

function tbl = summary_row(scenario_id, envelope, factor, solution_type, ...
        solution, pmax, recheck)
tbl = table(scenario_id, envelope, factor, solution_type, solution.exitflag, ...
    solution.eta, solution.objective, ...
    max(abs(solution.predicted_residual_mw)), ...
    sum(solution.capability_relaxation_mw), ...
    sum(solution.capability_relaxation_mw(1:3)), ...
    sum(pmax(1:3)), recheck.pf_success, ...
    recheck.reporting_interface_objective, ...
    recheck.max_abs_interface_residual_mw, ...
    recheck.reference_adjustment_mw, recheck.min_voltage_pu, ...
    recheck.max_voltage_pu, recheck.voltage_violation_count, ...
    recheck.branch_overload_count, recheck.max_branch_overload_mva, ...
    recheck.generator_p_violation_count, recheck.max_generator_p_violation_mw, ...
    recheck.generator_q_violation_count, recheck.max_generator_q_violation_mvar, ...
    recheck.q_enforced_pf_success, ...
    'VariableNames', {'scenario_id','envelope_name','abc_cap_factor', ...
    'solution_type','linear_exitflag','minimum_eta', ...
    'linear_objective','linear_max_abs_residual_mw', ...
    'total_capability_relaxation_mw','abc_capability_relaxation_mw', ...
    'abc_total_pmax_mw','nonlinear_pf_success', ...
    'nonlinear_reporting_objective','nonlinear_max_abs_residual_mw', ...
    'nonlinear_reference_adjustment_mw','nonlinear_min_voltage_pu', ...
    'nonlinear_max_voltage_pu','nonlinear_voltage_violation_count', ...
    'nonlinear_branch_overload_count','nonlinear_max_branch_overload_mva', ...
    'nonlinear_generator_p_violation_count', ...
    'nonlinear_max_generator_p_violation_mw', ...
    'nonlinear_generator_q_violation_count', ...
    'nonlinear_max_generator_q_violation_mvar', ...
    'nonlinear_q_enforced_pf_success'});
end

function tbl = residual_table(scenario_id, envelope, solution_type, names, ...
        base_residual, linear_residual, accuracy, nonlinear_detail)
n = numel(names);
nonlinear_residual = nan(n, 1);
for k = 1:n
    idx = find(string(nonlinear_detail.interface_name) == names(k), 1);
    if ~isempty(idx), nonlinear_residual(k) = nonlinear_detail.residual_mw(idx); end
end
tbl = table(repmat(scenario_id, n, 1), repmat(envelope, n, 1), ...
    repmat(solution_type, n, 1), names, base_residual, linear_residual, ...
    linear_residual ./ accuracy, nonlinear_residual, ...
    nonlinear_residual ./ accuracy, accuracy, ...
    'VariableNames', {'scenario_id','envelope_name','solution_type', ...
    'interface_name','base_residual_mw','linear_predicted_residual_mw', ...
    'linear_normalized_residual','nonlinear_residual_mw', ...
    'nonlinear_normalized_residual','accuracy_scale_mw'});
end

function tbl = dual_table(scenario_id, envelope, solution_type, zones, ...
        generation, pmin, pmax, solution)
tol = 1e-5;
final_generation = generation + solution.delta_generation_mw;
tbl = table(repmat(scenario_id, numel(zones), 1), ...
    repmat(envelope, numel(zones), 1), ...
    repmat(solution_type, numel(zones), 1), zones, generation, pmin, pmax, ...
    final_generation, abs(final_generation - pmin) <= tol, ...
    abs(final_generation - pmax) <= tol, solution.lower_bound_dual, ...
    solution.upper_bound_dual, ...
    'VariableNames', {'scenario_id','envelope_name','solution_type','zone', ...
    'base_generation_mw','pmin_mw','pmax_mw','linear_generation_mw', ...
    'at_pmin','at_pmax','pmin_shadow_value','pmax_shadow_value'});
end

function tbl = relaxation_table(scenario_id, envelope, zones, solution)
tbl = table(repmat(scenario_id, numel(zones), 1), ...
    repmat(envelope, numel(zones), 1), zones, ...
    solution.capability_relaxation_mw, ...
    solution.capability_constraint_lp_dual, ...
    solution.capability_constraint_secondary_qp_dual, ...
    'VariableNames', {'scenario_id','envelope_name','zone', ...
    'required_capability_relaxation_mw', ...
    'first_stage_lp_capability_dual', ...
    'second_stage_qp_capability_dual'});
end

function tbl = proposal_table(scenario_id, envelope, solution_type, zones, ...
        generation, pmin, pmax, delta, relaxation)
tbl = table(repmat(scenario_id, numel(zones), 1), ...
    repmat(envelope, numel(zones), 1), ...
    repmat(solution_type, numel(zones), 1), zones, generation, delta, ...
    generation + delta, pmin, pmax, relaxation, ...
    'VariableNames', {'scenario_id','envelope_name','solution_type','zone', ...
    'base_generation_mw','delta_generation_mw','proposed_generation_mw', ...
    'pmin_mw','effective_pmax_mw','capability_relaxation_mw'});
end

function diagnostic = local_west_central_diagnostics(K, residual, accuracy, ...
        generation, pmin, pmax, interface_names)
wc = find(interface_names == "West_Central", 1);
other = setdiff((1:numel(interface_names))', wc);
nz = numel(generation);
lb = pmin - generation;
ub = pmax - generation;
opts = optimoptions('linprog', 'Display', 'none');

% Maximize correction in the required positive direction, ignoring all
% other interface residuals.
f = -K(wc, :)';
[d1, ~, exit1] = linprog(f, [], [], ones(1, nz), 0, lb, ub, opts);
correction_unconstrained = K(wc, :) * d1;

% Repeat while retaining the other six interfaces inside their bands.
A = [K(other, :); -K(other, :)];
b = [accuracy(other) - residual(other); accuracy(other) + residual(other)];
[d2, ~, exit2] = linprog(f, A, b, ones(1, nz), 0, lb, ub, opts);
correction_banded = NaN;
if exit2 > 0, correction_banded = K(wc, :) * d2; end
diagnostic = table("ABC_CAP_0p8", residual(wc), exit1, ...
    correction_unconstrained, residual(wc) + correction_unconstrained, ...
    exit2, correction_banded, residual(wc) + correction_banded, ...
    'VariableNames', {'envelope_name','base_west_central_residual_mw', ...
    'west_only_exitflag','maximum_west_central_correction_mw', ...
    'west_only_remaining_residual_mw','other_six_banded_exitflag', ...
    'banded_west_central_correction_mw','banded_remaining_residual_mw'});
end

function status = scenario_availability_status(scenario_id, zones, file)
available = false;
complete = false;
if exist(file, 'file') == 2
    tbl = readtable(file, 'TextType', 'string', 'VariableNamingRule', 'preserve');
    required = {'scenario_id','zone','available_pmax_mw'};
    available = all(ismember(required, tbl.Properties.VariableNames));
    if available
        rows = tbl(string(tbl.scenario_id) == scenario_id, :);
        complete = height(rows) == numel(zones) && ...
            all(ismember(zones, string(rows.zone))) && ...
            all(isfinite(rows.available_pmax_mw));
    end
end
if complete
    state = "available_not_yet_promoted";
    note = "Input exists and can be added as a separate envelope.";
else
    state = "not_run_missing_independent_input";
    note = "No complete 2025 hour-specific unit availability/commitment " + ...
        "table is present. Static Gold Book capability is not treated as " + ...
        "scenario availability.";
end
[~, input_name, input_ext] = fileparts(file);
input_id = "System Matpower Format/NY_Lite/" + string(input_name) + ...
    string(input_ext);
status = table(scenario_id, input_id, available, complete, state, note, ...
    'VariableNames', {'scenario_id','expected_input_file','schema_detected', ...
    'complete_scenario_rows','status','note'});
end

function [metrics, detail] = nonlinear_recheck(scenario_id, zones, ...
        proposed_generation, zonal_pmax, options)
define_constants;
base = loadcase(options.structural_case);
[gsk, ~] = build_perform_npcc_generation_shift_keys(base);
[core, ~] = build_ny_only_equivalent_case(base);
[core, ~] = align_npcc_generation_capacity_to_perform_gsk(core, gsk);
core = set_zonal_pmax(core, zones, zonal_pmax);
[core, ~] = apply_nyiso_zonal_loads(core, scenario_id, 1.0, ...
    struct('preserve_total_ny_load', true));
pfopt = mpoption('verbose', 0, 'out.all', 0, 'pf.enforce_q_lims', 0);
schedule = proposed_generation;
pmin = zonal_pmin(core, zones);
loss_iterations = 0;
for k = 1:5
    [scheduled_core, ~] = apply_perform_generation_allocation(core, ...
        table(zones, schedule, ...
        'VariableNames', {'zone','target_generation_mw'}), gsk);
    [mpc, ext] = apply_nyiso_external_interface_injections( ...
        scheduled_core, scenario_id, ...
        struct('target_file', options.external_target_file));
    mpc = set_zone_reference(mpc, ext.added_gen_index, "J");
    result = runpf(mpc, pfopt);
    if ~result.success
        metrics = failed_recheck(scenario_id);
        detail = empty_detail();
        return;
    end
    physical = physical_metrics(result, ext.added_gen_index, sum(schedule));
    loss_iterations = k;
    adjustment = physical.reference_adjustment_mw;
    if abs(adjustment) <= 0.1, break; end
    alpha = loss_participation(schedule, pmin, zonal_pmax, adjustment);
    required_total = sum(schedule) + adjustment;
    schedule = project_total(schedule + alpha * adjustment, ...
        pmin, zonal_pmax, required_total);
end
targets = read_public_interface_targets(scenario_id, ...
    options.interface_target_file);
flows = ny_lite_interface_flows(result, ny_lite_interface_definitions(result));
[objective, detail] = interface_target_objective_balanced(flows, targets, ...
    struct('scale_file', options.interface_scale_file, 'min_scale_mw', 500));
physical = physical_metrics(result, ext.added_gen_index, sum(schedule));
try
    qresult = runpf(mpc, mpoption('verbose', 0, 'out.all', 0, ...
        'pf.enforce_q_lims', 1));
    q_success = logical(qresult.success);
catch
    q_success = false;
end
metrics = table(scenario_id, true, objective, ...
    max(abs(detail.residual_mw)), physical.reference_adjustment_mw, ...
    physical.min_voltage_pu, physical.max_voltage_pu, ...
    physical.voltage_violation_count, physical.branch_overload_count, ...
    physical.max_branch_overload_mva, physical.generator_p_violation_count, ...
    physical.max_generator_p_violation_mw, physical.generator_q_violation_count, ...
    physical.max_generator_q_violation_mvar, q_success, loss_iterations, ...
    'VariableNames', recheck_names());
end

function pmin = zonal_pmin(mpc, zones)
define_constants;
mpc = attach_nyiso_zone_metadata(mpc);
[mapped, bi] = ismember(mpc.gen(:, GEN_BUS), mpc.bus(:, BUS_I));
gen_zone = strings(size(mpc.gen, 1), 1);
gen_zone(mapped) = string(mpc.userdata.nyiso_physical_zone(bi(mapped)));
online = mpc.gen(:, GEN_STATUS) > 0;
pmin = zeros(numel(zones), 1);
for z = 1:numel(zones)
    pmin(z) = sum(mpc.gen(online & gen_zone == zones(z), PMIN));
end
end

function alpha = loss_participation(generation, pmin, pmax, adjustment)
if adjustment >= 0
    reserve = max(0, pmax - generation);
else
    reserve = max(0, generation - pmin);
end
if sum(reserve) <= 1e-9, reserve = max(0, pmax - pmin); end
alpha = reserve / sum(reserve);
end

function projected = project_total(seed, lower, upper, total)
scale = max(100, upper - lower);
C = diag(1 ./ scale);
d = C * seed;
opts = optimoptions('lsqlin', 'Display', 'off', 'Algorithm', 'interior-point');
[projected, ~, ~, exitflag, output] = lsqlin(C, d, [], [], ...
    ones(1, numel(seed)), total, lower, upper, ...
    min(max(seed, lower), upper), opts);
if exitflag <= 0
    error('S8.1 nonlinear loss projection failed: %s', output.message);
end
end

function mpc = set_zonal_pmax(mpc, zones, targets)
define_constants;
mpc = attach_nyiso_zone_metadata(mpc);
[mapped, bi] = ismember(mpc.gen(:, GEN_BUS), mpc.bus(:, BUS_I));
gen_zone = strings(size(mpc.gen, 1), 1);
gen_zone(mapped) = string(mpc.userdata.nyiso_physical_zone(bi(mapped)));
online = mpc.gen(:, GEN_STATUS) > 0;
for z = 1:numel(zones)
    idx = find(online & gen_zone == zones(z));
    if isempty(idx)
        if targets(z) > 1e-6
            error('Zone %s has no online generators for PMAX target %.3f.', ...
                zones(z), targets(z));
        end
        continue;
    end
    current = sum(mpc.gen(idx, PMAX));
    if current <= 0
        if targets(z) > 1e-6, error('Zone %s has zero PMAX.', zones(z)); end
        continue;
    end
    mpc.gen(idx, PMAX) = mpc.gen(idx, PMAX) * targets(z) / current;
    mpc.gen(idx, PMIN) = min(mpc.gen(idx, PMIN), mpc.gen(idx, PMAX));
end
end

function mpc = set_zone_reference(mpc, external_idx, zone_name)
define_constants;
mpc = attach_nyiso_zone_metadata(mpc);
[mapped, bi] = ismember(mpc.gen(:, GEN_BUS), mpc.bus(:, BUS_I));
zone = strings(size(mpc.gen, 1), 1);
zone(mapped) = string(mpc.userdata.nyiso_physical_zone(bi(mapped)));
mask = mpc.gen(:, GEN_STATUS) > 0 & zone == zone_name;
mask(external_idx) = false;
idx = find(mask);
qrange = mpc.gen(idx, QMAX) - mpc.gen(idx, QMIN);
if any(qrange > 1e-6), idx = idx(qrange > 1e-6); end
[~, k] = max(mpc.gen(idx, PMAX) - mpc.gen(idx, PG));
mpc = set_scenario_reference_bus(mpc, idx(k), ...
    struct('require_external', false));
end

function metrics = physical_metrics(results, external_idx, scheduled_internal)
define_constants;
results = attach_nyiso_zone_metadata(results);
[mapped, bi] = ismember(results.gen(:, GEN_BUS), results.bus(:, BUS_I));
zone = strings(size(results.gen, 1), 1);
zone(mapped) = string(results.userdata.nyiso_physical_zone(bi(mapped)));
online = results.gen(:, GEN_STATUS) > 0;
internal = online & zone ~= "";
internal(external_idx) = false;
sf = hypot(results.branch(:, PF), results.branch(:, QF));
st = hypot(results.branch(:, PT), results.branch(:, QT));
smax = max(sf, st);
rated = results.branch(:, RATE_A) > 0 & results.branch(:, BR_STATUS) > 0;
over = max(0, smax - results.branch(:, RATE_A));
vviol = results.bus(:, VM) < results.bus(:, VMIN) - 1e-6 | ...
    results.bus(:, VM) > results.bus(:, VMAX) + 1e-6;
pviol = max(max(0, results.gen(:, PMIN) - results.gen(:, PG)), ...
    max(0, results.gen(:, PG) - results.gen(:, PMAX)));
qviol = max(max(0, results.gen(:, QMIN) - results.gen(:, QG)), ...
    max(0, results.gen(:, QG) - results.gen(:, QMAX)));
metrics = struct('reference_adjustment_mw', ...
    sum(results.gen(internal, PG)) - scheduled_internal, ...
    'min_voltage_pu', min(results.bus(:, VM)), ...
    'max_voltage_pu', max(results.bus(:, VM)), ...
    'voltage_violation_count', sum(vviol), ...
    'branch_overload_count', sum(rated & over > 1e-6), ...
    'max_branch_overload_mva', max([0; over(rated)]), ...
    'generator_p_violation_count', sum(pviol > 1e-6), ...
    'max_generator_p_violation_mw', max([0; pviol]), ...
    'generator_q_violation_count', sum(qviol > 1e-6), ...
    'max_generator_q_violation_mvar', max([0; qviol]));
end

function tbl = failed_recheck(scenario_id)
values = {scenario_id, false, NaN, NaN, NaN, NaN, NaN, NaN, NaN, ...
    NaN, NaN, NaN, NaN, NaN, false, NaN};
tbl = cell2table(values, 'VariableNames', recheck_names());
end

function detail = empty_detail()
detail = table(strings(0, 1), zeros(0, 1), zeros(0, 1), ...
    'VariableNames', {'interface_name','residual_mw','objective_term'});
end

function names = recheck_names()
names = {'scenario_id','pf_success','reporting_interface_objective', ...
    'max_abs_interface_residual_mw','reference_adjustment_mw', ...
    'min_voltage_pu','max_voltage_pu','voltage_violation_count', ...
    'branch_overload_count','max_branch_overload_mva', ...
    'generator_p_violation_count','max_generator_p_violation_mw', ...
    'generator_q_violation_count','max_generator_q_violation_mvar', ...
    'q_enforced_pf_success','loss_closure_iterations'};
end

function out = append_table(out, row)
if isempty(row), return; end
if isempty(out), out = row; else, out = [out; row]; end
end
