function outputs = run_s9b_reference_continuation_audit(options)
%RUN_S9B_REFERENCE_CONTINUATION_AUDIT Refine and stress-test S9b onset.
%   Runs bidirectional warm and cold S1-reference sweeps, perturbed transition
%   starts, and a compact comparison across four voltage-reference sets.

if nargin < 1, options = struct(); end
helper_dir = fileparts(mfilename('fullpath'));
case_dir = fileparts(helper_dir);
addpath(case_dir); addpath(helper_dir);
options = defaults(options, helper_dir);
build_ny_voltage_reference_sets;

summary = table(); slacks = table(); external_q = table(); interfaces = table();

refined = struct('voltage_reference_sets', "S1_OPF_SOLVED_REFERENCE", ...
    'boundary_q_modes', ["present_limited_q"; "fixed_scenario_q"; ...
    "no_discretionary_q"], 'reference_weights', options.refined_weights, ...
    'sweep_directions', ["increasing"; "decreasing"], ...
    'start_modes', ["warm"; "cold"], 'write_outputs', false);
out = run_s9b_ac_feasibility_restoration(refined);
[summary, slacks, external_q, interfaces] = append_outputs(summary, slacks, ...
    external_q, interfaces, out, "S1_REFINED_BIDIRECTIONAL");

perturbed = struct('voltage_reference_sets', "S1_OPF_SOLVED_REFERENCE", ...
    'boundary_q_modes', "present_limited_q", ...
    'reference_weights', options.refined_weights, ...
    'sweep_directions', "increasing", 'start_modes', "perturbed", ...
    'perturbation_ids', [1; 2], 'write_outputs', false);
out = run_s9b_ac_feasibility_restoration(perturbed);
[summary, slacks, external_q, interfaces] = append_outputs(summary, slacks, ...
    external_q, interfaces, out, "S1_PERTURBED_STARTS");

comparison = struct('voltage_reference_sets', ...
    ["S1_OPF_SOLVED_REFERENCE"; "ORIGINAL_NPCC_VG_REFERENCE"; ...
    "PERFORM_ZONE_AGGREGATE_REFERENCE"; "CURRENT_S7_MODEL_REFERENCE"], ...
    'boundary_q_modes', "present_limited_q", ...
    'reference_weights', options.comparison_weights, ...
    'sweep_directions', "increasing", 'start_modes', "warm", ...
    'write_outputs', false);
out = run_s9b_ac_feasibility_restoration(comparison);
[summary, slacks, external_q, interfaces] = append_outputs(summary, slacks, ...
    external_q, interfaces, out, "REFERENCE_SET_COMPARISON");

brackets = onset_brackets(summary);
writetable(summary, options.summary_file);
writetable(slacks, options.slack_file);
writetable(external_q, options.external_q_file);
writetable(interfaces, options.interface_file);
writetable(brackets, options.bracket_file);
outputs = struct('summary', summary, 'slacks', slacks, ...
    'external_q', external_q, 'interface_residuals', interfaces, ...
    'onset_brackets', brackets, 'summary_file', options.summary_file, ...
    'slack_file', options.slack_file, 'external_q_file', options.external_q_file, ...
    'interface_file', options.interface_file, 'bracket_file', options.bracket_file);
end

function options = defaults(options, helper_dir)
items = { ...
    'refined_weights', (0.800:0.0025:0.825)'; ...
    'comparison_weights', [0; 0.5; 0.75; 0.8; 0.825; 0.9; 1.0]; ...
    'summary_file', fullfile(helper_dir, 's9b_reference_continuation_summary.csv'); ...
    'slack_file', fullfile(helper_dir, 's9b_reference_continuation_slacks.csv'); ...
    'external_q_file', fullfile(helper_dir, 's9b_reference_continuation_external_q.csv'); ...
    'interface_file', fullfile(helper_dir, 's9b_reference_continuation_interfaces.csv'); ...
    'bracket_file', fullfile(helper_dir, 's9b_reference_onset_brackets.csv')};
for k = 1:size(items, 1)
    if ~isfield(options, items{k, 1}), options.(items{k, 1}) = items{k, 2}; end
end
end

function [summary, slacks, external_q, interfaces] = append_outputs( ...
        summary, slacks, external_q, interfaces, out, group_name)
summary = append_table(summary, tag(out.summary, group_name));
slacks = append_table(slacks, tag(out.slacks, group_name));
external_q = append_table(external_q, tag(out.external_q, group_name));
interfaces = append_table(interfaces, tag(out.interface_residuals, group_name));
end

function tbl = tag(tbl, group_name)
if isempty(tbl), return; end
tbl = addvars(tbl, repmat(string(group_name), height(tbl), 1), 'Before', 1, ...
    'NewVariableNames', 'audit_group');
end

function brackets = onset_brackets(summary)
keys = unique(summary(:, {'audit_group','voltage_reference_set', ...
    'boundary_q_mode'}), 'rows');
brackets = table();
for k = 1:height(keys)
    rows = summary(summary.audit_group == keys.audit_group(k) & ...
        summary.voltage_reference_set == keys.voltage_reference_set(k) & ...
        summary.boundary_q_mode == keys.boundary_q_mode(k), :);
    weights = unique(rows.reference_weight);
    hard = false(numel(weights), 1);
    restored = false(numel(weights), 1);
    for j = 1:numel(weights)
        at_weight = rows(abs(rows.reference_weight - weights(j)) < 1e-10, :);
        hard(j) = any(at_weight.hard_attempt_success);
        restored(j) = any(string(at_weight.termination_class) == ...
            "restored_nonzero_slack");
    end
    last_hard = NaN;
    first_restored = NaN;
    if any(hard), last_hard = max(weights(hard)); end
    if any(restored), first_restored = min(weights(restored)); end
    row = table(keys.audit_group(k), keys.voltage_reference_set(k), ...
        keys.boundary_q_mode(k), last_hard, first_restored, ...
        numel(weights), sum(hard), sum(restored), ...
        'VariableNames', {'audit_group','voltage_reference_set', ...
        'boundary_q_mode','highest_weight_with_any_hard_success', ...
        'lowest_weight_with_any_nonzero_restoration', ...
        'tested_weight_count','hard_success_weight_count', ...
        'nonzero_restoration_weight_count'});
    brackets = append_table(brackets, row);
end
end

function out = append_table(out, row)
if isempty(row), return; end
if isempty(out), out = row; else, out = [out; row]; end
end
