function report=test_research_model_contract
%TEST_RESEARCH_MODEL_CONTRACT Preserve scale semantics and independent claims.
legacy=research_model_contract('historical_2019');
scaled=research_model_contract('historical_similarity_scaled');
actual=research_model_contract('historical_actual_mw');
current=research_model_contract('contemporary_2026');
assert(legacy.power_scale=="historical_similarity_scaled" && ...
    scaled.power_scale==legacy.power_scale && ...
    actual.power_scale=="actual_mw" && current.power_scale=="actual_mw");
assert(actual.infrastructure_cutoff==legacy.infrastructure_cutoff && ...
    actual.observation_valid_from_utc==legacy.observation_valid_from_utc && ...
    actual.observation_valid_until_utc==legacy.observation_valid_until_utc && ...
    current.infrastructure_cutoff~=actual.infrastructure_cutoff);
assert(actual.allow_assumed_research_baseline && ~actual.allow_synthetic_observations && ...
    ~actual.external_npcc_qualification_required && ~actual.external_reduction_required && ...
    ~actual.fixed_bus_count_required && ~actual.require_all_original_ny_elements_active && ...
    actual.preserve_historical_cases && actual.preserve_original_record_in_provenance);
assert(~actual.electrical_baseline_qualified && ~actual.dlr_ready && ~actual.release_ready && ...
    actual.contemporary_validation_coverage=="not_applicable_historical_case" && ...
    current.contemporary_validation_coverage=="not_evaluated");
assert(all(ismember(["replace";"deactivate";"split";"aggregate"],actual.allowed_internal_dispositions)));
try
    research_model_contract('ambiguous_historical');
    error('test_research_model_contract:MissingError','Unknown mode was accepted.');
catch e
    assert(strcmp(e.identifier,'research_model_contract:Mode'));
end
report=table(["legacy_scale_meaning_preserved";"actual_MW_has_separate_historical_mode"; ...
    "NY_only_build_has_no_external_prerequisite";"assumptions_do_not_claim_observations_or_qualification"; ...
    "internal_replacement_preserves_provenance_contract";"unknown_mode_rejected"], ...
    true(6,1),'VariableNames',{'test','passed'});
disp(report);
end
