function out = test_s13_phase1a_common_input_readiness()
%TEST_S13_PHASE1A_COMMON_INPUT_READINESS Focused fail-closed audit test.

audit = assess_s13_phase1a_common_input_readiness(struct( ...
    'write_outputs', false, 'verbose', false));

assert(~audit.ready && audit.readiness_status == "not_ready_fail_closed", ...
    'The Phase 1A common input must remain fail-closed.');
assert(~audit.promotion_eligible && ...
    ~audit.validated_full_npcc_tie_controller, ...
    'The readiness audit cannot promote S13 or invent a tie controller.');
assert(height(audit.common_input_spec) == 66 && ...
    numel(unique(audit.common_input_spec.scenario_id)) == 6, ...
    'Expected six scenarios times eleven zones.');
assert(height(audit.external_schedule_map) == 54 && ...
    numel(unique(audit.external_schedule_map.s12_p32_group)) == 9, ...
    'Expected six scenarios times nine S12 P-32 groups.');
assert(isequal(sort(audit.tie_audit.all_boundary_branch_rows(:)), ...
    [25; 32; 63; 64; 72; 80; 83; 93; 99; 221]), ...
    'The S13 full-NPCC tie-row inventory changed.');
assert(all(audit.external_schedule_map.validated_s13_tie_controller == 0), ...
    'No external schedule row may claim a validated S13 tie controller.');
assert(any(audit.common_input_spec.zone == "H" & ...
    ~audit.common_input_spec.s13_generation_representable), ...
    'The known nonrepresentable Zone-H generation prior was not detected.');
assert(gate_value(audit.gates, "no_s12_boundary_injections_added_to_s13"), ...
    'The no-boundary-injection invariant must pass.');
assert(gate_value(audit.gates, "parent_branch_rxb_frozen") && ...
    gate_value(audit.gates, "added_physical_branch_rxb_source_exact"), ...
    'No-fit R/X/B invariants must pass.');

out = struct('pass', true, 'readiness_status', audit.readiness_status, ...
    'passing_gate_count', sum(audit.gates.actual), ...
    'gate_count', height(audit.gates));
end

function value = gate_value(gates, id)
idx = find(gates.gate_id == string(id), 1);
assert(~isempty(idx), 'Missing readiness gate %s.', string(id));
value = gates.actual(idx);
end
