function out = test_s13_phase1a_oracle_artifact_consistency()
%TEST_S13_PHASE1A_ORACLE_ARTIFACT_CONSISTENCY Verify all committed evidence.

validation = validate_s13_phase1a_oracle_artifact_consistency(struct( ...
    'fail_on_mismatch', true, 'verbose', false));
assert(validation.all_artifacts_match && ...
    validation.matching_artifact_count == 12 && ...
    validation.artifact_count == 12, ...
    'Expected all twelve S13.1 evidence artifacts to match exactly.');
assert(all(validation.checks.schema_order_match) && ...
    all(validation.checks.content_match) && ...
    all(validation.checks.canonical_lf_match), ...
    'Schema, rendered content, and canonical LF checks must all pass.');
assert(~validation.promotion_eligible && ...
    validation.oracle_status == ...
    "unpromoted_fail_closed_pending_common_baseline", ...
    'Artifact consistency cannot promote the incomplete S13.1 comparison.');

out = struct('pass', true, ...
    'matching_artifact_count', validation.matching_artifact_count, ...
    'artifact_count', validation.artifact_count, ...
    'oracle_status', validation.oracle_status);
end
