function out = test_s13_phase1a_local_identity(options)
%TEST_S13_PHASE1A_LOCAL_IDENTITY Focused Stage-A electrical identity test.

if nargin < 1, options = struct(); end
if ~isfield(options, 'verbose'), options.verbose = true; end

result = run_s13_phase1a_local_identity(struct( ...
    'write_outputs', false, 'fail_on_gate', true, 'verbose', false));

expected_source_rows = [2137; 2131; 2154; 2133; 1567; 1568; 1571];
expected_interior = [1228; 1222; 1567; 772];
assert(result.pass, 'Stage-A local identity did not pass.');
assert(height(result.local_identity) == 7 && ...
    isequal(result.local_identity.source_branch_row, expected_source_rows), ...
    'The seven source physical branch rows changed.');
assert(height(result.omitted_injections) == 4 && ...
    isequal(result.omitted_injections.source_bus, expected_interior), ...
    'The four interior omitted-injection rows changed.');
assert(height(result.terminal_voltages) == 6, ...
    'The local terminal-voltage table must contain six buses.');
assert(all(result.local_identity.orientation_match) && ...
    all(result.local_identity.raw_circuit_identity_match) && ...
    all(result.local_identity.s13_parameter_identity_match), ...
    'Source/RAW/S13 physical identity changed.');

parallel = ismember(result.local_identity.source_branch_row, [1567; 1568]);
assert(isequal(result.local_identity.raw_circuit_id(parallel), ["1"; "2"]), ...
    'Coopers Corner-Rock Tavern CKT1/CKT2 identity changed.');
assert(all(result.omitted_injections.source_zero_device_pass) && ...
    all(result.omitted_injections.network_partition_pass), ...
    'The source zero-device or omitted-network partition invariant failed.');
assert(all(result.local_identity.direct_phasor_identity_pass) && ...
    all(result.local_identity.injection_solution_branch_pass), ...
    'Direct phasor or injection-supported branch identity failed.');
assert(all(result.local_identity.s12_readonly_oracle_branch_pass), ...
    'The read-only S12 retained-branch comparison failed.');
assert(~result.zero_injection_is_gating && ...
    all(result.local_identity.zero_injection_acceptance_role == ...
        "diagnostic_only_not_gating") && ...
    all(result.terminal_voltages.zero_injection_acceptance_role == ...
        "diagnostic_only_not_gating"), ...
    'The zero-injection truncation must remain non-gating.');
assert(all(result.gate_ledger.pass(result.gate_ledger.mandatory)), ...
    'One or more mandatory Stage-A gates failed.');

out = struct('pass', true, ...
    'mandatory_gate_count', nnz(result.gate_ledger.mandatory), ...
    'direct_max_p_error_mw', ...
        max(result.local_identity.direct_max_p_error_mw), ...
    'direct_max_q_error_mvar', ...
        max(result.local_identity.direct_max_q_error_mvar), ...
    'injection_max_p_error_mw', ...
        max(result.local_identity.injection_max_p_error_mw), ...
    'injection_max_q_error_mvar', ...
        max(result.local_identity.injection_max_q_error_mvar), ...
    'injection_max_vm_error_pu', ...
        max(result.terminal_voltages.injection_vm_error_pu), ...
    'injection_max_va_error_deg', ...
        max(result.terminal_voltages.injection_va_error_deg), ...
    's12_max_p_error_mw', ...
        max(result.local_identity.s12_max_p_error_mw), ...
    's12_max_q_error_mvar', ...
        max(result.local_identity.s12_max_q_error_mvar), ...
    'zero_injection_max_vm_error_pu', ...
        max(result.terminal_voltages.zero_injection_vm_error_pu), ...
    'zero_injection_max_va_error_deg', ...
        max(result.terminal_voltages.zero_injection_va_error_deg));

if options.verbose
    fprintf(['S13 Phase-1A local identity test passed: %d mandatory gates; ' ...
        'direct P/Q %.3g/%.3g; injection P/Q %.3g/%.3g; ' ...
        'VM/VA %.3g/%.3g; S12 P/Q %.3g/%.3g.\n'], ...
        out.mandatory_gate_count, out.direct_max_p_error_mw, ...
        out.direct_max_q_error_mvar, out.injection_max_p_error_mw, ...
        out.injection_max_q_error_mvar, out.injection_max_vm_error_pu, ...
        out.injection_max_va_error_deg, out.s12_max_p_error_mw, ...
        out.s12_max_q_error_mvar);
    fprintf(['  Zero-injection diagnostic only: max VM/VA %.4g pu / ' ...
        '%.4g deg.\n'], out.zero_injection_max_vm_error_pu, ...
        out.zero_injection_max_va_error_deg);
end
end
