function out = test_s13_phase1b_local_identity(options)
%TEST_S13_PHASE1B_LOCAL_IDENTITY Focused no-fit Phase 1B identity test.

if nargin < 1, options = struct(); end
if ~isfield(options, 'verbose'), options.verbose = true; end

runner_options = struct( ...
    'write_outputs', false, 'fail_on_gate', true, 'verbose', false);
forward = {'s13_case','source_case','raw_file','output_dir'};
for k = 1:numel(forward)
    if isfield(options, forward{k})
        runner_options.(forward{k}) = options.(forward{k});
    end
end
result = run_s13_phase1b_local_identity(runner_options);

pv_wood = "phase1b_pv_wood_mesh";
ramapo_buchanan = "phase1b_ramapo_buchanan_path";
expected_path = [repmat(pv_wood, 6, 1); repmat(ramapo_buchanan, 3, 1)];
expected_source_rows = [1389; 1390; 1391; 1392; 1689; 1690; ...
    1577; 1576; 1738];
expected_raw_ids = ["1"; "2"; "1"; "2"; "1"; "2"; "1"; "1"; "1"];

assert(result.pass, 'The Phase 1B local identity did not pass.');
assert(height(result.local_identity) == 9 && ...
    isequal(result.local_identity.overlay_path_id, expected_path) && ...
    isequal(result.local_identity.source_branch_row, expected_source_rows), ...
    'The nine Phase 1B source physical rows or path assignments changed.');
assert(isequal(result.local_identity.raw_circuit_id, expected_raw_ids), ...
    'The Phase 1B RAW circuit IDs changed.');
assert(height(result.omitted_injections) == 2 && ...
    isequal(result.omitted_injections.overlay_path_id, ...
        [pv_wood; ramapo_buchanan]) && ...
    isequal(result.omitted_injections.source_bus, [858; 774]), ...
    'The Phase 1B interior omitted-injection rows changed.');
assert(height(result.terminal_voltages) == 6 && ...
    nnz(result.terminal_voltages.overlay_path_id == pv_wood) == 3 && ...
    nnz(result.terminal_voltages.overlay_path_id == ramapo_buchanan) == 3, ...
    'Each Phase 1B local voltage table must contain three terminals.');

assert(all(result.local_identity.orientation_match) && ...
    all(result.local_identity.raw_circuit_identity_match) && ...
    all(result.local_identity.s13_parameter_control_identity_match), ...
    'Source, RAW, or cumulative-S13 physical identity changed.');
assert(all(result.omitted_injections.source_zero_device_pass) && ...
    all(result.omitted_injections.network_partition_pass), ...
    'A source zero-device or omitted-network partition invariant failed.');
assert(all(result.local_identity.direct_phasor_identity_pass) && ...
    all(result.local_identity.injection_solution_branch_pass), ...
    'Direct phasor or injection-supported branch identity failed.');
assert(all(result.terminal_voltages.injection_vm_error_pu( ...
    result.terminal_voltages.terminal_role == "interior_pq") <= 1e-5) && ...
    all(result.terminal_voltages.injection_va_error_deg( ...
    result.terminal_voltages.terminal_role == "interior_pq") <= 0.001), ...
    'An interior terminal voltage identity gate failed.');

assert(result.phase1a_report_exact_match && ...
    result.phase1a_physical_rows_bit_identical, ...
    'The immutable Phase 1A report or physical rows changed.');
assert(result.candidate_fail_closed && ~result.residual_fit_performed && ...
    ~result.promotion_performed, ...
    'The local identity test must not fit residuals or promote S13.');
assert(~result.zero_injection_is_gating && ...
    all(result.local_identity.zero_injection_acceptance_role == ...
        "diagnostic_only_not_gating") && ...
    all(result.terminal_voltages.zero_injection_acceptance_role == ...
        "diagnostic_only_not_gating"), ...
    'The zero-injection truncations must remain non-gating diagnostics.');

identity_names = string(result.local_identity.Properties.VariableNames);
voltage_names = string(result.terminal_voltages.Properties.VariableNames);
assert(~any(startsWith(identity_names, "s12")) && ...
    ~any(startsWith(voltage_names, "s12")), ...
    'The Phase 1B local identity must not include an S12 comparison.');
assert(all(result.gate_ledger.pass(result.gate_ledger.mandatory)), ...
    'One or more mandatory Phase 1B local-identity gates failed.');

if exist('validate_s13_phase1b_upny_operator', 'file') ~= 0
    assert(result.operator_validator_available && ...
        result.operator_mandatory_proxy_pass, ...
        'The available Phase 1B operator validator proxy did not pass.');
    operator = result.operator_validation;
    mandatory = operator.gate_ledger.mandatory_for_phase1b_proxy;
    assert(operator.pass && operator.mandatory_proxy_pass && ...
        all(operator.gate_ledger.pass(mandatory)) && ...
        ~operator.exact_public_operator && ~operator.promotion_eligible, ...
        'The Phase 1B operator proxy role or fail-closed status changed.');
end

out = struct('pass', true, ...
    'mandatory_gate_count', nnz(result.gate_ledger.mandatory), ...
    'direct_max_p_error_mw', ...
        max(result.local_identity.direct_max_p_error_mw), ...
    'direct_max_q_error_mvar', ...
        max(result.local_identity.direct_max_q_error_mvar), ...
    'injection_max_p_error_mw', ...
        max(result.local_identity.injection_max_p_error_mw), ...
    'injection_max_q_error_mvar', ...
        max(result.local_identity.injection_max_q_error_mvar), ...
    'injection_max_vm_error_pu', ...
        max(result.terminal_voltages.injection_vm_error_pu), ...
    'injection_max_va_error_deg', ...
        max(result.terminal_voltages.injection_va_error_deg), ...
    'zero_injection_max_vm_error_pu', ...
        max(result.terminal_voltages.zero_injection_vm_error_pu), ...
    'zero_injection_max_va_error_deg', ...
        max(result.terminal_voltages.zero_injection_va_error_deg), ...
    'operator_validator_available', result.operator_validator_available, ...
    'operator_mandatory_proxy_pass', result.operator_mandatory_proxy_pass);

if options.verbose
    fprintf(['S13 Phase 1B local identity test passed: %d mandatory gates; ' ...
        'direct P/Q %.3g/%.3g; injection P/Q %.3g/%.3g; ' ...
        'VM/VA %.3g/%.3g.\n'], out.mandatory_gate_count, ...
        out.direct_max_p_error_mw, out.direct_max_q_error_mvar, ...
        out.injection_max_p_error_mw, out.injection_max_q_error_mvar, ...
        out.injection_max_vm_error_pu, out.injection_max_va_error_deg);
    fprintf(['  Zero-injection diagnostics only: max VM/VA %.4g pu / ' ...
        '%.4g deg; operator validator available/pass %d/%d.\n'], ...
        out.zero_injection_max_vm_error_pu, ...
        out.zero_injection_max_va_error_deg, ...
        out.operator_validator_available, out.operator_mandatory_proxy_pass);
end
end
