function out = test_s13_phase1a_oracle_comparison()
%TEST_S13_PHASE1A_ORACLE_COMPARISON Focused fail-closed orchestration test.

result = run_s13_phase1a_oracle_comparison(struct( ...
    'write_outputs', false, 'verbose', false));

assert(result.stage_a_executed && result.stage_a_pass, ...
    'Verified Stage-A evidence must execute and pass.');
assert(~result.common_input_ready && ~result.stage_b_executed && ...
    ~result.stage_c_executed, ...
    'Stage B/C must remain blocked without a frozen common baseline.');
assert(~result.promotion_eligible && ~result.electrically_validated && ...
    result.status == "unpromoted_fail_closed_pending_common_baseline", ...
    'The orchestration result must remain explicitly unpromoted.');

assert(height(result.same_snapshot_comparison) == 22 && ...
    all(result.same_snapshot_comparison.execution_status == "blocked") && ...
    all(isnan(result.same_snapshot_comparison.s12_value)) && ...
    all(isnan(result.same_snapshot_comparison.s13_value)), ...
    'The 22 Stage-B manifest rows must be blocked NaN evidence.');
assert(height(result.cut_flow_comparison) == 5 && ...
    all(isnan(result.cut_flow_comparison.s12_flow_or_share)) && ...
    all(isnan(result.cut_flow_comparison.s13_flow_or_share)), ...
    'Cut-flow values cannot be invented before the common baseline exists.');

physical = result.physical_circuit_comparison;
assert(height(physical) == 7 && all(physical.stage_a_pass) && ...
    all(isfinite(physical.source_series_current_kA)) && ...
    all(isfinite(physical.s12_series_current_kA)) && ...
    all(isfinite(physical.stage_a_local_series_current_kA)) && ...
    all(isnan(physical.common_baseline_s13_series_current_kA)), ...
    'Physical-circuit output must separate real Stage-A evidence from blocked Stage B.');
future_physical = {'common_baseline_s12_pf_mw', ...
    'common_baseline_s12_qf_mvar','common_baseline_s12_pt_mw', ...
    'common_baseline_s12_qt_mvar', ...
    'common_baseline_s12_series_current_kA','common_baseline_s13_pf_mw', ...
    'common_baseline_s13_qf_mvar','common_baseline_s13_pt_mw', ...
    'common_baseline_s13_qt_mvar', ...
    'common_baseline_s13_series_current_kA','common_baseline_pf_error_mw', ...
    'common_baseline_qf_error_mvar','common_baseline_pt_error_mw', ...
    'common_baseline_qt_error_mvar', ...
    'common_baseline_series_current_error_kA', ...
    'common_baseline_current_error_percent'};
assert(all(ismember(future_physical, physical.Properties.VariableNames)), ...
    'Physical-circuit common-baseline schema is incomplete.');
for k = 1:numel(future_physical)
    assert(all(isnan(physical.(future_physical{k}))), ...
        'Unexecuted common-baseline physical evidence must remain NaN.');
end
assert(all(physical.system_comparison_status == "blocked"), ...
    'Physical-circuit system evidence must remain blocked.');

heldout = result.heldout_response;
expected = ["E_TO_G_P250"; "E_TO_G_N250"; "E_TO_G_P500"; ...
    "E_TO_G_N500"; "F_TO_G_P250"; "F_TO_G_N250"; ...
    "ZONE_E_LOAD_P5"; "ZONE_E_LOAD_N5"; "ZONE_G_LOAD_P5"; ...
    "ZONE_G_LOAD_N5"; "COOPERS_ROCK_TAVERN_CKT1_OUTAGE"; ...
    "COOPERS_ROCK_TAVERN_CKT2_OUTAGE"];
assert(height(heldout) == 12 && isequal(heldout.perturbation_id, expected), ...
    'The requested held-out perturbation manifest changed.');
assert(all(heldout.execution_status == "blocked") && ...
    all(heldout.balancing_policy_id == ...
    "pending_common_balancing_gsk_not_frozen") && ...
    all(~heldout.refit_performed) && ...
    all(isnan(heldout.oracle_E_G_cut_delta_mw)) && ...
    all(isnan(heldout.s13_E_G_cut_delta_mw)), ...
    'Held-out rows must remain no-refit blocked NaN evidence.');
assert(isequal(heldout.outaged_source_branch_row(11:12), [1567; 1568]) && ...
    all(isfinite(heldout.outaged_s12_branch_row(11:12))) && ...
    all(isfinite(heldout.outaged_s13_branch_row(11:12))), ...
    'CKT1/CKT2 outage identities must be durable and mapped.');

detail = result.heldout_metric_manifest;
assert(height(detail) == 432 && ...
    nnz(detail.entity_type == "physical_circuit") == 252 && ...
    nnz(detail.entity_type == "terminal") == 144 && ...
    nnz(detail.entity_type == "system") == 36, ...
    'Held-out detail must contain 12 scenarios times 36 metrics.');
expected_metric_id = ["delta_pf_mw"; "delta_qf_mvar"; ...
    "delta_series_current_kA"; "delta_vm_pu"; ...
    "delta_aligned_va_deg"; "delta_E_G_cut_mw"; ...
    "delta_E_F_cut_mw"; "delta_internal_NY_active_loss_mw"];
expected_metric_count = [84; 84; 84; 72; 72; 12; 12; 12];
for k = 1:numel(expected_metric_id)
    assert(nnz(detail.metric_id == expected_metric_id(k)) == ...
        expected_metric_count(k), ...
        'Held-out metric cardinality changed for %s.', expected_metric_id(k));
end
keys = detail.perturbation_id + "|" + detail.entity_type + "|" + ...
    detail.entity_id + "|" + detail.metric_id;
assert(numel(unique(keys)) == 432 && ...
    all(detail.balancing_policy_id == ...
    "pending_common_balancing_gsk_not_frozen") && ...
    all(~detail.refit_performed) && ...
    all(detail.execution_status == "blocked") && ...
    all(isnan(detail.oracle_delta_value)) && ...
    all(isnan(detail.s13_delta_value)), ...
    'Held-out detail must be unique, balanced-policy explicit, and fail-closed.');
for k = 1:height(heldout)
    scenario = detail.perturbation_id == heldout.perturbation_id(k);
    assert(nnz(scenario) == 36, ...
        'Each held-out perturbation must define exactly 36 metrics.');
end
assert(endsWith(result.files.heldout_metric_manifest, ...
    's13_phase1a_heldout_metric_manifest.csv'), ...
    'Held-out detail output path is not exposed by the runner.');

assert(result.gate_count == 59 && result.passing_gate_count == 38 && ...
    ~result.all_required_gates_pass, ...
    'Expected the audited fail-closed 38/59 gate result.');

out = struct('pass', true, 'passing_gate_count', result.passing_gate_count, ...
    'gate_count', result.gate_count, 'status', result.status);
end
