function out = test_s12_interface_snapshot_sums(options)
%TEST_S12_INTERFACE_SNAPSHOT_SUMS Check operator and sidecar freshness.

if nargin < 1, options = struct(); end
if ~isfield(options, 'verbose'), options.verbose = true; end

helper_dir = fileparts(mfilename('fullpath'));
generated = s12_generate_interface_snapshot_sums(struct( ...
    'write_output', false, 'verbose', false));
persisted = readtable(fullfile(helper_dir, ...
    's12_interface_snapshot_sums.csv'), 'TextType', 'string', ...
    'VariableNamingRule', 'preserve');
operator_csv = readtable(fullfile(helper_dir, ...
    's12_interface_operators.csv'), 'TextType', 'string', ...
    'VariableNamingRule', 'preserve');

expected_variables = {'interface_name', 'circuit_count', ...
    'source_snapshot_mw', 'reduced_snapshot_mw'};
assert(isequal(persisted.Properties.VariableNames, expected_variables), ...
    'S12 snapshot-sum sidecar schema changed unexpectedly.');
assert(height(persisted) == height(generated.summary), ...
    'S12 snapshot-sum sidecar row count is stale.');

persisted = sortrows(persisted, 'interface_name');
recomputed = sortrows(generated.summary, 'interface_name');
assert(isequal(persisted.interface_name, recomputed.interface_name), ...
    'S12 snapshot-sum interface membership is stale.');
assert(isequal(persisted.circuit_count, recomputed.circuit_count), ...
    'S12 snapshot-sum circuit counts are stale.');
source_error = max(abs(persisted.source_snapshot_mw - ...
    recomputed.source_snapshot_mw));
reduced_error = max(abs(persisted.reduced_snapshot_mw - ...
    recomputed.reduced_snapshot_mw));
assert(source_error <= 1e-9 && reduced_error <= 1e-9, ...
    'S12 snapshot-sum MW values are stale.');

expected_te_source_rows = sort([935; 1345; 1346; 1567; 1568; 1609; 1612; 2136]);
te_generated = generated.operator( ...
    generated.operator.interface_name == "Total_East_proxy", :);
te_csv = operator_csv(operator_csv.interface_name == "Total_East_proxy", :);
te_sidecar = persisted(persisted.interface_name == "Total_East_proxy", :);
assert(height(te_generated) == 8 && height(te_csv) == 8 && ...
    height(te_sidecar) == 1 && te_sidecar.circuit_count == 8, ...
    'Total_East_proxy must be represented by exactly eight circuits.');
assert(isequal(sort(te_generated.source_branch), expected_te_source_rows) && ...
    isequal(sort(te_csv.source_branch), expected_te_source_rows), ...
    'Total_East_proxy source-circuit membership changed unexpectedly.');

out = struct('pass', true, 'interface_count', height(persisted), ...
    'total_east_circuit_count', te_sidecar.circuit_count, ...
    'max_source_error_mw', source_error, ...
    'max_reduced_error_mw', reduced_error);
if options.verbose
    fprintf(['S12 interface snapshot sidecar passed: %d interfaces; ' ...
        'Total_East_proxy = %d circuits; max errors %.3g / %.3g MW.\n'], ...
        out.interface_count, out.total_east_circuit_count, ...
        out.max_source_error_mw, out.max_reduced_error_mw);
end
end
