function out = validate_s13_phase1b_smoke(options)
%VALIDATE_S13_PHASE1B_SMOKE Inherited-snapshot AC diagnostics through 1B.
%   Standard and Q-limit PF results are reported for the S7/Phase-0 parent,
%   immutable Phase 1A checkpoint, and cumulative Phase 1B checkpoint. This
%   is not a common-2019 operating comparison or a promotion gate.

if nargin < 1, options = struct(); end
if ~isfield(options, 'write_outputs'), options.write_outputs = true; end
if ~isfield(options, 'fail_on_standard_pf')
    options.fail_on_standard_pf = true;
end
if ~isfield(options, 'verbose'), options.verbose = true; end

helper_dir = fileparts(mfilename('fullpath'));
case_dir = fileparts(helper_dir);
addpath(case_dir); addpath(helper_dir);
define_constants;

s7 = loadcase('npcc_ny_lite_s7_seven_interface_perform_direct_candidate');
s7 = apply_ny_core_phase0_corrections(s7, struct( ...
    'fit_reactance', false, 'verbose', false));
phase1a = build_s13_phase1a_candidate(struct( ...
    'write_outputs', false, 'verbose', false));
phase1b = build_s13_phase1b_candidate(struct( ...
    'write_outputs', false, 'verbose', false));
cases = {s7, phase1a.candidate, phase1b.candidate};
case_id = ["s7_phase0_parent"; "s13_phase1a_checkpoint"; ...
    "s13_phase1b_checkpoint"];
current_phase = ["phase0"; "phase1a"; "phase1b"];

summary = table();
pfopt = mpoption('verbose', 0, 'out.all', 0);
qopt = mpoption('verbose', 0, 'out.all', 0, 'pf.enforce_q_lims', 1);
for k = 1:numel(cases)
    result = runpf(cases{k}, pfopt);
    qresult = runpf(cases{k}, qopt);
    online = result.gen(:, GEN_STATUS) > 0;
    q_violation = max(max(result.gen(:, QG) - result.gen(:, QMAX), 0), ...
        max(result.gen(:, QMIN) - result.gen(:, QG), 0));
    q_violation(~online) = 0;
    upny_proxy_mw = NaN;
    if k == 3
        op = cases{k}.userdata.s13.phase_reports.phase1b.operator_map;
        upny_proxy_mw = sum(op.operator_sign .* ...
            result.branch(op.model_branch_row, PF));
    end
    row = table(case_id(k), current_phase(k), ...
        "inherited_s7_snapshot_smoke_not_2019", ...
        size(result.bus, 1), size(result.branch, 1), size(result.gen, 1), ...
        logical(result.success), logical(qresult.success), ...
        nnz(q_violation > 1e-6), max(q_violation, [], 'omitnan'), ...
        min(result.bus(:, VM)), max(result.bus(:, VM)), ...
        sum(result.branch(:, PF) + result.branch(:, PT)), upny_proxy_mw, ...
        false, false, ...
        'VariableNames', {'case_id','current_phase','snapshot_scope', ...
        'bus_count','branch_count','generator_count','standard_pf_success', ...
        'q_limit_pf_success','standard_pf_q_limit_violation_count', ...
        'max_standard_pf_q_limit_violation_mvar','min_vm_pu','max_vm_pu', ...
        'active_loss_mw','upny_coned_345kv_proxy_mw', ...
        'construction_source_qualified','promotion_eligible'});
    summary = [summary; row]; %#ok<AGROW>
end

standard_pf_all_pass = all(summary.standard_pf_success);
if options.write_outputs
    ny_lite_writetable_lf(summary, ...
        fullfile(helper_dir, 's13_phase1b_smoke_validation.csv'));
end
out = struct('summary', summary, ...
    'standard_pf_all_pass', standard_pf_all_pass, ...
    'q_limit_pf_all_pass', all(summary.q_limit_pf_success), ...
    'construction_source_qualified', false, 'promotion_eligible', false);

if options.verbose
    fprintf(['S13 Phase-1B inherited-snapshot smoke: standard PF %d/%d; ' ...
        'Q-limit PF %d/%d; no operating or promotion claim.\n'], ...
        nnz(summary.standard_pf_success), height(summary), ...
        nnz(summary.q_limit_pf_success), height(summary));
end
if options.fail_on_standard_pf && ~standard_pf_all_pass
    error('validate_s13_phase1b_smoke:StandardPF', ...
        'One or more inherited-snapshot standard PF cases failed.');
end
end
