function out=validate_ny_region_replacement(source,parent,build,options)
%VALIDATE_NY_REGION_REPLACEMENT Audit a declared source-region replacement.
% Exactness applies to source-region devices and copied crossing branches at
% common terminal voltages. It does not establish upstate-aggregation response
% identity, global AC feasibility, public-interface completeness or DLR readiness.
if nargin<4,options=struct();end
if ~isfield(options,'fail_on_error'),options.fail_on_error=true;end
if ~isfield(options,'tolerance'),options.tolerance=1e-10;end
if ~isfield(options,'accounting_tolerance'),options.accounting_tolerance=1e-8;end
m=build.candidate;bm=build.source_bus_map;em=build.source_branch_map;
retired=build.retired_branch_register;kept=build.retained_parent_branch_map;
region=build.region_source_buses(:);sid=source.bus(:,1);mid=m.bus(:,1);
replacement_zones=string(('G':'K')');
if isfield(build,'replacement_zones'),replacement_zones=string(build.replacement_zones(:));end
assert(all(ismember(replacement_zones,string(('A':'K')'))) && ...
    numel(unique(replacement_zones))==numel(replacement_zones) && ...
    all(ismember(string(('G':'K')'),replacement_zones)), ...
    'ny_region:ReplacementZones','Declared replacement zones must be distinct A-K zones containing G-K.');
assert(all(ismember({'source_bus','model_bus','zone','mapping_kind'},bm.Properties.VariableNames)), ...
    'ny_region:BusMapSchema','Source bus map is incomplete.');
assert(all(ismember({'source_branch_row','model_branch_row'},em.Properties.VariableNames)), ...
    'ny_region:BranchMapSchema','Source branch map is incomplete.');
assert(all(ismember({'parent_branch_row','disposition'},retired.Properties.VariableNames)) && ...
    all(ismember({'parent_branch_row','model_branch_row'},kept.Properties.VariableNames)), ...
    'ny_region:DispositionSchema','Parent disposition mapping is incomplete.');
assert(numel(unique(sid))==numel(sid)&&numel(unique(mid))==numel(mid), ...
    'ny_region:DuplicateBus','Source/model IDs must be unique.');
assert(all(ismember(region,sid))&&numel(unique(region))==numel(region)&&~isempty(region), ...
    'ny_region:Region','Invalid source-region membership.');
[all_source_map,sr]=ismember(bm.source_bus,sid);[all_model_map,mr]=ismember(bm.model_bus,mid);
assert(all(all_source_map&all_model_map)&&numel(unique(bm.source_bus))==height(bm), ...
    'ny_region:BusMapIdentity','Source bus mapping is missing or duplicated.');
assert(all(em.source_branch_row>=1&em.source_branch_row<=size(source.branch,1)) && ...
    all(em.model_branch_row>=1&em.model_branch_row<=size(m.branch,1)) && ...
    numel(unique(em.source_branch_row))==height(em)&&numel(unique(em.model_branch_row))==height(em), ...
    'ny_region:BranchMapIdentity','Branch identities must be valid and unique.');
assert(all(retired.parent_branch_row>=1&retired.parent_branch_row<=size(parent.branch,1)) && ...
    all(kept.parent_branch_row>=1&kept.parent_branch_row<=size(parent.branch,1)) && ...
    all(kept.model_branch_row>=1&kept.model_branch_row<=size(m.branch,1)), ...
    'ny_region:ParentRows','Parent disposition rows are invalid.');
gates=table();
sz=perform_nyiso_zone_letters(source);
gates=gate(gates,"power_base_unchanged",source.baseMVA==m.baseMVA && source.baseMVA==parent.baseMVA, ...
    "Source, candidate and inherited network use the same power base.");
gates=gate(gates,"all_source_bus_mappings_accounted_once", ...
    isequal(sort(bm.source_bus),sort(sid)),"Every source bus is mapped exactly once, including upstate injections.");
core=sid(ismember(sz,replacement_zones));
gates=gate(gates,"all_declared_replacement_source_buses_in_region",all(ismember(core,region)), ...
    "Every source bus in a declared replacement zone is exact; additional satellites are permitted.");
exact=string(bm.mapping_kind)=="exact_source_region";
gates=gate(gates,"exact_region_mapping_complete",isequal(sort(bm.source_bus(exact)),sort(region)) && ...
    numel(unique(bm.model_bus(exact)))==sum(exact),"Exact source region has one distinct model bus per source bus.");
gates=gate(gates,"source_zone_metadata_preserved",all(string(bm.zone)==sz(sr)), ...
    "Source zones stay source zones even for satellites outside the declared replacement zones.");
gates=gate(gates,"exact_region_voltage_classes", ...
    isequal(source.bus(sr(exact),[10 12 13]),m.bus(mr(exact),[10 12 13])), ...
    "Exact source-region base kV and voltage limits are unchanged.");
required=find(ismember(source.branch(:,1),region)|ismember(source.branch(:,2),region));
gates=gate(gates,"all_source_internal_and_crossing_records_mapped", ...
    isequal(sort(em.source_branch_row),required), ...
    "Every internal and crossing source record is copied once, including offline records.");
[ff,fmap]=ismember(source.branch(em.source_branch_row,1),bm.source_bus);
[tt,tmap]=ismember(source.branch(em.source_branch_row,2),bm.source_bus);
assert(all(ff&tt),'ny_region:UnmappedBranchEndpoint','Copied branch endpoint has no bus mapping.');
expected=source.branch(em.source_branch_row,1:13);
expected(:,1)=bm.model_bus(fmap);expected(:,2)=bm.model_bus(tmap);
actual=m.branch(em.model_branch_row,1:13);
gates=gate(gates,"copied_source_electrical_parameters_and_status",isequaln(expected,actual), ...
    "Endpoints are mapped; R/X/B, ratings, tap, phase, status and angle fields are copied without fitting.");
gates=gate(gates,"crossing_endpoint_voltage_classes", ...
    all(source.bus(sr(fmap),10)==m.bus(mr(fmap),10)) && ...
    all(source.bus(sr(tmap),10)==m.bus(mr(tmap),10)), ...
    "Every crossing preserves endpoint base kV; unmatched lower-voltage ports require source expansion.");
% A retained coarse endpoint may represent multiple upstream source nodes,
% but none may alias an exact region node or create an unregistered self-loop.
gates=gate(gates,"region_ids_disjoint_from_aggregated_ports", ...
    ~any(ismember(bm.model_bus(exact),bm.model_bus(~exact))) && ...
    all(actual(:,1)~=actual(:,2)),"No aggregated upstate port aliases a retained source region bus.");
assert(isfield(parent,'userdata')&&isfield(parent.userdata,'nyiso_physical_zone'), ...
    'ny_region:ParentZones','Registered parent NYISO zone metadata is required.');
pz=string(parent.userdata.nyiso_physical_zone(:));pids=parent.bus(:,1);
preplaced=pids(ismember(pz,replacement_zones));
pretained=pids(ismember(pz,setdiff(string(('A':'K')'),replacement_zones)));
replaced_rows=find(ismember(parent.branch(:,1),preplaced)|ismember(parent.branch(:,2),preplaced));
retained_rows=find(ismember(parent.branch(:,1),pretained)&ismember(parent.branch(:,2),pretained));
gates=gate(gates,"every_inherited_replacement_incident_row_retired", ...
    all(ismember(replaced_rows,retired.parent_branch_row)) && ~any(ismember(replaced_rows,kept.parent_branch_row)), ...
    "Retire every inherited branch incident on a declared replacement zone, including old equivalents.");
gates=gate(gates,"retained_parent_rows_preserved", ...
    isequal(sort(kept.parent_branch_row),retained_rows) && ...
    isequaln(parent.branch(kept.parent_branch_row,1:13),m.branch(kept.model_branch_row,1:13)), ...
    "Parent branches between retained NY zones remain electrically unchanged.");
[upfound,upmodel]=ismember(pretained,mid);[~,upsource]=ismember(pretained,pids);
gates=gate(gates,"retained_parent_voltage_classes_and_limits_preserved",all(upfound) && ...
    isequal(parent.bus(upsource,[10 12 13]),m.bus(upmodel,[10 12 13])), ...
    "Retained NPCC bus voltage bases and limits remain unchanged.");
disposition=build.parent_branch_disposition;
gates=gate(gates,"parent_branch_disposition_is_total_and_disjoint", ...
    isequal(sort(disposition.parent_branch_row),(1:size(parent.branch,1))') && ...
    isequal(sort(retired.parent_branch_row),replaced_rows) && ...
    all(strlength(string(retired.disposition))>0) && ...
    all(strlength(string(disposition.disposition))>0) && ...
    isequal(sort(disposition.parent_branch_row(string(disposition.disposition)=="retained_upstate_NPCC_parameters")),retained_rows), ...
    "Every historical row has one disposition; regional replacements and external removals are distinct.");
gates=gate(gates,"candidate_branch_provenance_is_total_and_disjoint", ...
    isequal(sort([em.model_branch_row;kept.model_branch_row]),(1:size(m.branch,1))'), ...
    "Every candidate branch is a registered source copy or an unchanged parent branch.");
gates=gate(gates,"candidate_bus_provenance_is_total_and_disjoint", ...
    isequal(sort([pretained;bm.model_bus(exact)]),sort(mid)), ...
    "Candidate buses contain exactly the declared retained parent buses and exact source-region buses.");
active=m.branch(:,11)>0;
[valid_from,from_row]=ismember(m.branch(active,1),mid);
[valid_to,to_row]=ismember(m.branch(active,2),mid);
valid_endpoints=valid_from&valid_to;
network=graph(from_row(valid_endpoints),to_row(valid_endpoints),[],numel(mid));
component_count=max(conncomp(network));
gates=gate(gates,"active_network_is_connected",all(valid_endpoints)&&component_count==1, ...
    "All candidate buses belong to one active-branch component, and every active endpoint exists.");
gates=audit_provenance(gates,parent,build,pretained,preplaced);
% Form both branch stamps independently at one declared common model phasor.
% Upstate source terminals mapped to one anchor receive that same phasor.
vc=m.bus(:,8).*exp(1j*m.bus(:,9)*pi/180);
vs=source.bus(:,8).*exp(1j*source.bus(:,9)*pi/180);vs(sr)=vc(mr);
[sf,st,si]=branch_values(source,em.source_branch_row,vs);
[cf,ct,ci]=branch_values(m,em.model_branch_row,vc);
flow_error=max(abs([sf-cf;st-ct]));current_error=max(abs(si-ci),[],'all');
gates=gate(gates,"matched_common_voltage_branch_power_identity", ...
    isfinite(flow_error)&&flow_error<=options.tolerance, ...
    "Matched source/candidate branch terminal complex power; no upstream response identity is inferred.");
gates=gate(gates,"matched_common_voltage_branch_current_identity", ...
    isfinite(current_error)&&current_error<=options.tolerance, ...
    "Both-end kA uses each source/model terminal base kV.");
[gates,accounting_error]=audit_injections(gates,source,build,bm,sr,mr,options.accounting_tolerance);
out=struct('gates',gates,'passed',all(gates.passed), ...
    'common_voltage_max_complex_power_error_mva',flow_error, ...
    'common_voltage_max_current_error_ka',current_error, ...
    'region_source_bus_count',numel(region),'source_branch_record_count',height(em), ...
    'replacement_zones',replacement_zones,'retained_parent_bus_count',numel(pretained), ...
    'active_network_component_count',component_count, ...
    'upstate_aggregation_identity_established',false,'operating_point_qualified',false, ...
    'injection_and_control_conservation_evaluated',true, ...
    'source_mapping_max_accounting_error',accounting_error,'dlr_ready',false);
if options.fail_on_error
    assert(out.passed,'ny_region:Validation','Region replacement failed: %s', ...
        strjoin(gates.metric(~gates.passed),', '));
end
end

function gates=audit_provenance(gates,p,b,retained_buses,replaced_buses)
% A correct electrical matrix does not excuse false device identities or
% altered historical values in the reviewable retirement ledgers.
define_constants;
em=b.source_branch_map;kept=b.retained_parent_branch_map;r=b.retired_branch_register;
inventory=b.source_inventory.branch_inventory;d=b.parent_branch_disposition;
expected_keys=strings(size(b.candidate.branch,1),1);
source_keys=string(inventory.device_key(em.source_branch_row));
parent_keys="NPCC_PARENT:BRANCH:"+string(kept.parent_branch_row);
expected_keys(em.model_branch_row)=source_keys;expected_keys(kept.model_branch_row)=parent_keys;
gates=gate(gates,"branch_provenance_keys_match_source_and_parent", ...
    isequal(string(em.device_key),source_keys) && isequal(string(kept.device_key),parent_keys) && ...
    isequal(string(b.branch_keys(:)),expected_keys) && numel(unique(expected_keys))==numel(expected_keys), ...
    "Source/parent branch row identities agree with every exported candidate branch key.");
rr=r.parent_branch_row;dr=d.parent_branch_row;
retired_values=[r.parent_from_bus r.parent_to_bus r.r_pu r.x_pu r.b_pu r.rate_a_mva r.rate_b_mva ...
    r.rate_c_mva r.tap r.shift_deg r.original_status r.angle_min_deg r.angle_max_deg];
retirement_ok=isequal(retired_values,p.branch(rr,1:13)) && ...
    all(r.new_active_contribution==0) && ...
    all(string(r.alternative_policy)=="historical_parent_kept_as_explicit_alternative_not_superimposed") && ...
    isequal([d.parent_from_bus d.parent_to_bus d.parent_status],p.branch(dr,[F_BUS T_BUS BR_STATUS]));
gates=gate(gates,"retired_branch_values_and_zero_contribution_preserved",retirement_ok, ...
    "Retirement records preserve the original endpoints/parameters/status and declare zero active contribution.");
ids=[retained_buses;replaced_buses];lb=b.retired_legacy_bus_injections;lg=b.retired_legacy_generators;
[found,bi]=ismember(lb.parent_bus,p.bus(:,BUS_I));
assert(all(found),'ny_region:LegacyBusIdentity','Legacy bus ledger has an unknown parent bus.');
expected_gen=find(ismember(p.gen(:,GEN_BUS),ids));gr=lg.parent_gen_row;
assert(all(gr>=1&gr<=size(p.gen,1)&mod(gr,1)==0), ...
    'ny_region:LegacyGeneratorRows','Legacy generator ledger has an invalid parent row.');
gates=gate(gates,"legacy_NY_injection_retirement_is_complete_and_original", ...
    isequal(sort(lb.parent_bus),sort(ids)) && ...
    isequal([lb.retired_pd_mw lb.retired_qd_mvar lb.retired_gs_mw lb.retired_bs_mvar],p.bus(bi,[PD QD GS BS])) && ...
    isequal(sort(gr),expected_gen) && ...
    isequal([lg.parent_bus lg.old_pg_mw lg.old_qg_mvar lg.old_pmin_mw lg.old_pmax_mw lg.old_qmin_mvar lg.old_qmax_mvar], ...
        p.gen(gr,[GEN_BUS PG QG PMIN PMAX QMIN QMAX])) && ...
    all(strlength(string(lg.disposition))>0), ...
    "All historical NY bus injections and generator records are archived once with original values.");
end

function [gates,maxerr]=audit_injections(gates,s,b,bm,sr,mr,tol)
% Source case and frozen Package A inputs are the references. Allocation
% summaries cannot establish their own correctness by repeating candidate data.
define_constants;
m=b.candidate;a=b.allocation;n=b.source_inventory;f=b.foundation;
nb=size(m.bus,1);ns=size(s.bus,1);A=sparse(mr,sr,1,nb,ns);
assert(isfield(m,'userdata')&&isfield(m.userdata,'nyiso_physical_zone'), ...
    'ny_region:ModelZones','Candidate physical zones are required.');
mz=string(m.userdata.nyiso_physical_zone(:));sz=perform_nyiso_zone_letters(s);
gates=gate(gates,"source_injections_remain_in_source_zone", ...
    numel(mz)==nb && all(mz(mr)==sz(sr)),"Source loads, shunts and devices retain their source NY zones.");
sl=a.source_load_ledger;ml=a.model_bus_ledger;br=a.boundary_register;gm=a.generator_map;cm=a.control_map;
fl=f.gross_boundary_ledger;fg=f.mpc.gen;fk=string(f.generator_keys(:));
[ok,li]=ismember(s.bus(:,BUS_I),sl.source_bus);
[mf,mi]=ismember(m.bus(:,BUS_I),ml.model_bus);
[ff,fi]=ismember(s.bus(:,BUS_I),fl.source_bus);
assert(all(ok)&&all(mf)&&all(ff)&&height(sl)==ns&&height(fl)==ns&&height(ml)==nb && ...
    numel(unique(sl.source_bus))==ns && numel(unique(fl.source_bus))==ns && numel(unique(ml.model_bus))==nb, ...
    'ny_region:InjectionLedgerIdentity','Source/foundation/model load ledger coverage is invalid.');
sl=sl(li,:);ml=ml(mi,:);fl=fl(fi,:);
[mapped,source_order]=ismember(s.bus(:,BUS_I),bm.source_bus);assert(all(mapped));
source_model_bus=bm.model_bus(source_order);
source_load=[sl.pd_gross_mw sl.qd_gross_mvar sl.gs_mw sl.bs_mvar];
maxerr=max(abs(source_load-s.bus(:,[PD QD GS BS])),[],'all');
gates=gate(gates,"source_gross_load_and_shunt_ledger_matches_original", ...
    maxerr<=tol && isequal(sl.model_bus,source_model_bus), ...
    "Original gross P/Q and canonical GS/BS occur exactly once at each mapped source location.");
fd=max(abs([fl.pd_gross_mw-s.bus(:,PD);fl.qd_gross_mvar-s.bus(:,QD)]));
expected_boundary=n.boundary_reconciliation(n.boundary_reconciliation.boundary_member,:);
[bf,bi]=ismember(br.source_bus,s.bus(:,BUS_I));
assert(all(bf),'ny_region:BoundaryIdentity','Boundary source identity is invalid.');
outside=~ismember(s.bus(:,BUS_I),expected_boundary.source_bus);
boundary_ok=height(br)==height(expected_boundary)&&numel(unique(br.source_bus))==height(br) && ...
    isequal(sort(br.source_bus),sort(expected_boundary.source_bus)) && ...
    isequal(br.model_bus,source_model_bus(bi)) && ...
    all(fl.p_boundary_mw(outside)==0) && all(fl.q_boundary_mvar(outside)==0);
[found,expected_order]=ismember(br.source_bus,expected_boundary.source_bus);
assert(all(found),'ny_region:BoundaryIdentity','Unregistered boundary source identity.');
inactive=expected_boundary.canonical_status(expected_order)<=0;
bd=max(abs([br.p_injection_mw-fl.p_boundary_mw(bi);br.q_injection_mvar-fl.q_boundary_mvar(bi)]));
gates=gate(gates,"fixed_boundary_PQ_matches_frozen_foundation", ...
    boundary_ok&&fd<=tol&&bd<=tol && all(br.p_injection_mw(inactive)==0) && all(br.q_injection_mvar(inactive)==0), ...
    "Boundary P/Q matches separately frozen Package A inputs, including zero offline contributions.");
gross=A*s.bus(:,[PD QD]);boundary=A*[fl.p_boundary_mw fl.q_boundary_mvar];
expected=[gross-boundary A*s.bus(:,[GS BS])];
ledger_values=[ml.pd_gross_mw ml.qd_gross_mvar ml.p_boundary_mw ml.q_boundary_mvar ...
    ml.pd_effective_mw ml.qd_effective_mvar ml.gs_mw ml.bs_mvar];
ld=max(abs(ledger_values-[gross boundary expected]),[],'all');
cd=max(abs(m.bus(:,[PD QD GS BS])-expected),[],'all');
gates=gate(gates,"candidate_load_boundary_shunt_conservation",cd<=tol&&ld<=tol, ...
    "Candidate demand equals mapped source gross demand less fixed boundary P/Q; no legacy injection survives.");
native=n.generator_inventory(n.generator_inventory.native_generation_member,:);
nr=gm.source_gen_row(isfinite(gm.source_gen_row));
ng=size(m.gen,1);
gates=gate(gates,"native_generator_identity_coverage", ...
    isequal(sort(nr),sort(native.source_gen_row)) && ...
    isequal(sort(gm.model_gen_row),(1:ng)') && numel(unique(gm.device_key))==height(gm), ...
    "Every native source record is mapped once; model generator identities are total and disjoint.");
assert(all(gm.model_gen_row>=1&gm.model_gen_row<=ng&mod(gm.model_gen_row,1)==0), ...
    'ny_region:GeneratorRows','Generator model rows must be valid integers.');
[kf,ki]=ismember(string(gm.device_key),fk);[gf,gi]=ismember(gm.source_bus,s.bus(:,BUS_I));
assert(all(kf&gf)&&numel(unique(fk))==numel(fk)&&numel(fk)==size(fg,1), ...
    'ny_region:GeneratorIdentity','Mapped generators must match separate frozen foundation keys.');
native_mask=isfinite(gm.source_gen_row);source_rows=gm.source_gen_row(native_mask);
assert(all(source_rows>=1&source_rows<=size(s.gen,1)&mod(source_rows,1)==0), ...
    'ny_region:GeneratorSourceRows','Source generator rows must be valid integers.');
g=m.gen(gm.model_gen_row,:);fgen=fg(ki,:);
[nk,ni]=ismember(gm.device_key(native_mask),native.device_key);
native_ok=all(nk) && isequal(gm.source_gen_row(native_mask),native.source_gen_row(ni)) && ...
    isequal(gm.source_bus(native_mask),s.gen(source_rows,GEN_BUS)) && ...
    isequal(g(native_mask,[GEN_STATUS PMIN PMAX QMIN QMAX]),s.gen(source_rows,[GEN_STATUS PMIN PMAX QMIN QMAX]));
gates=gate(gates,"native_device_status_and_capability_unchanged",native_ok, ...
    "Native record key, source bus, online status and all P/Q limits match original source values.");
support=~native_mask;
support_ok=sum(support)==1 && gm.device_key(support)=="RESEARCH2019:Q_SUPPORT:1263:MARCY" && ...
    gm.source_bus(support)==1263 && ...
    isequal(g(support,[PG GEN_STATUS PMIN PMAX QMIN QMAX]),[0 1 0 0 -900 900]);
gates=gate(gates,"only_declared_bounded_Q_support_added",support_ok, ...
    "The one separately identified Marcy support is active-power zero and bounded to plus/minus 900 MVAr.");
gd=max(abs(g(:,[PG QG])-fgen(:,[PG QG])),[],'all');
gates=gate(gates,"candidate_dispatch_priors_match_frozen_foundation", ...
    gd<=tol && isequal(g(:,GEN_BUS),source_model_bus(gi)) && ...
    isequal(gm.model_bus,g(:,GEN_BUS)) && isequal(fgen(:,GEN_BUS),gm.source_bus), ...
    "Mapped dispatch priors come from frozen Package A native/support identities at declared mapped locations.");
map_values=[gm.status gm.prior_pg_mw gm.prior_qg_mvar gm.pmin_mw gm.pmax_mw gm.qmin_mvar gm.qmax_mvar];
gates=gate(gates,"generator_register_matches_candidate", ...
    isequal(map_values,g(:,[GEN_STATUS PG QG PMIN PMAX QMIN QMAX])) && ...
    all(string(gm.zone)==sz(gi)) && all(string(gm.mapping_kind)==string(bm.mapping_kind(source_order(gi)))), ...
    "Generator register values match independently checked model records and source mapping.");
[cf,ci]=ismember(gm.device_key,cm.device_key);
assert(all(cf)&&height(cm)==height(gm)&&numel(unique(cm.device_key))==height(cm), ...
    'ny_region:ControlIdentity','Control map must match all unique generator keys.');
cm=cm(ci,:);vg=fgen(:,VG);on=g(:,GEN_STATUS)>0;
for bus=unique(g(on,GEN_BUS))'
    rows=find(on&g(:,GEN_BUS)==bus);r=find(m.bus(:,BUS_I)==bus);
    w=max(g(rows,QMAX)-g(rows,QMIN),0);if sum(w)==0,w=ones(size(w));end
    target=sum(w.*vg(rows))/sum(w);target=min(max(target,m.bus(r,VMIN)),m.bus(r,VMAX));vg(rows)=target;
end
control_error=max(abs([g(:,VG)-vg;cm.mapped_vg_pu-vg;cm.source_reference_vg_pu-fgen(:,VG)]));
ref=m.bus(m.bus(:,BUS_TYPE)==REF,BUS_I);
reference_ok=numel(ref)==1 && ref==a.reference_bus && ...
    any(on & native_mask & g(:,GEN_BUS)==ref & g(:,PMAX)>g(:,PMIN));
expected_type=repmat(PQ,nb,1);expected_type(ismember(m.bus(:,BUS_I),g(on,GEN_BUS)))=PV;
if numel(ref)==1,expected_type(m.bus(:,BUS_I)==ref)=REF;end
gates=gate(gates,"declared_local_voltage_control_and_native_reference", ...
    control_error<=tol && isequal(cm.source_bus,gm.source_bus) && ...
    isequal(cm.model_bus,gm.model_bus) && isequal(cm.status,g(:,GEN_STATUS)) && ...
    all(string(cm.policy)=="local_PV_common_terminal_Q_span_weighted_reference_prior") && ...
    isequal(m.bus(:,BUS_TYPE),expected_type) && reference_ok, ...
    "Co-located PV priors use finite Q-span weights and one declared bounded native reference.");
maxerr=max([maxerr fd bd ld cd gd control_error]);
end

function gates=gate(gates,name,passed,description)
gates=[gates;table(string(name),logical(passed),string(description), ...
    'VariableNames',{'metric','passed','description'})];
end

function [sf,st,current]=branch_values(m,rows,v)
bus=m.bus;ids=bus(:,1);bus(:,1)=(1:size(bus,1))';
br=m.branch(rows,1:13);[~,br(:,1)]=ismember(br(:,1),ids);[~,br(:,2)]=ismember(br(:,2),ids);
[~,Yf,Yt]=makeYbus(m.baseMVA,bus,br);cf=Yf*v;ct=Yt*v;
sf=m.baseMVA*v(br(:,1)).*conj(cf);st=m.baseMVA*v(br(:,2)).*conj(ct);
current=[abs(cf)*m.baseMVA./(sqrt(3)*bus(br(:,1),10)), ...
    abs(ct)*m.baseMVA./(sqrt(3)*bus(br(:,2),10))];
end
