function out=validate_perform_ny_inventory(n)
%VALIDATE_PERFORM_NY_INVENTORY No role may become implicit native capacity.
m=n.source;b=n.bus_inventory;l=n.branch_inventory;g=n.generator_inventory;
s=n.shunt_inventory;a=n.shunt_alias_inventory;c=n.control_inventory;
q=n.boundary_reconciliation;names=strings(0,1);passed=false(0,1);
add("canonical_record_counts",height(b)==1576&&height(l)==2371&&height(g)==615);
add("bus_keys_unique",numel(unique(b.device_key))==height(b)&&numel(unique(b.source_bus))==height(b));
add("branch_keys_unique",numel(unique(l.device_key))==height(l));
add("generator_bus_unit_keys_unique",numel(unique(g.device_key))==height(g) && ...
    all(g.device_key=="PERFORM2019:GEN:"+string(g.source_bus)+":"+g.source_generator_id));
add("bus_inventory_covers_source",isequal(b.source_bus_row,(1:size(m.bus,1))')&&isequal(b.source_bus,m.bus(:,1)));
add("branch_inventory_covers_source",isequal(l.source_branch_row,(1:size(m.branch,1))') && ...
    isequal(l.source_from_bus,m.branch(:,1)) && isequal(l.source_to_bus,m.branch(:,2)));
add("generator_inventory_covers_source",isequal(g.source_gen_row,(1:size(m.gen,1))')&&isequal(g.source_bus,m.gen(:,1)));
add("canonical_parameters_preserved",isequal([l.source_r_pu l.source_x_pu l.source_b_pu],m.branch(:,3:5)) && ...
    isequal([b.gross_pd_mw b.gross_qd_mvar b.source_gs_mw b.source_bs_mvar],m.bus(:,3:6)) && ...
    isequal([g.source_pg_mw g.source_qg_mvar g.source_qmax_mvar g.source_qmin_mvar],m.gen(:,2:5)));
add("canonical_status_preserved",isequal(g.canonical_status,m.gen(:,8))&&isequal(l.canonical_status,m.branch(:,11)));
add("source_generator_bounds_preserved",isequal([g.source_pmin_mw g.source_pmax_mw ...
    g.source_qmin_mvar g.source_qmax_mvar g.source_voltage_target_pu],m.gen(:,[10 9 5 4 6])));
add("source_bus_and_branch_limits_preserved",isequal([b.source_vmin_pu b.source_vmax_pu],m.bus(:,[13 12])) && ...
    isequal([l.source_rate_a_mva l.source_rate_b_mva l.source_rate_c_mva l.source_tap l.source_shift_deg],m.branch(:,6:10)));
add("all_buses_in_NY_zones",all(ismember(b.source_zone,string(('A':'K')'))));
roles=["native_generation","native_pumped_storage","native_energy_storage", ...
    "external_boundary_proxy","reference_placeholder","unresolved_generator_role"];
add("generator_roles_exhaustive",all(ismember(g.source_device_role,roles)));
add("native_membership_excludes_all_proxies",all(g.native_generation_member==startsWith(g.source_device_role,"native_")) && ...
    nnz(g.native_generation_member)==594 && nnz(g.source_device_role=="external_boundary_proxy")==20 && ...
    nnz(g.source_device_role=="reference_placeholder")==1);
add("Marcy_reference_not_native",nnz(g.source_bus==1263 & g.source_generator_id=="RF" & ...
    g.source_device_role=="reference_placeholder" & ~g.native_generation_member)==1);
add("placeholder_Q_never_native",all(~g.native_generation_member(g.q_bounds_are_placeholder)));
add("placeholder_Q_flags_match_source",isequal(g.q_bounds_are_placeholder,max(abs(m.gen(:,4:5)),[],2)>=9000));
add("branch_families_cover_RAW",nnz(l.source_device_role=="two_winding_transformer")==144 && height(l)==2371);
add("no_implicit_overhead_classification",~any(l.overhead_thermal_eligible));
add("ambiguous_parallel_circuit_identity_disclosed",all(contains(l.raw_identity_candidates( ...
    ~l.individual_circuit_identity_resolved),";")) && all(l.identity_confidence( ...
    ~l.individual_circuit_identity_resolved)=="electrically_identical_parallel_assignment_not_unique_physical_identity"));
add("34_shunts_counted_once",height(s)==34&&height(a)==34&&all(s.already_in_canonical_bus_BS) && ...
    ~any(s.add_as_generator)&&~any(a.present_in_canonical_gen)&&all(a.present_in_canonical_bus_BS) && ...
    ~any(ismember(g.device_key,a.alternative_generator_key)));
[found,bi]=ismember(s.source_bus,m.bus(:,1));
add("BINIT_alias_matches_canonical_BS",all(found) && isequal(s.canonical_bs_mvar,m.bus(bi,6)) && ...
    abs(sum(s.canonical_bs_mvar)-sum(m.bus(:,6)))<1e-9);
add("controls_unique_and_counted",height(c)==615+144+34&&numel(unique(c.control_key))==height(c));
add("RAW_remote_control_conversion_explicit",isequal(g.canonical_regulated_bus,g.source_bus) && ...
    isequal(g.raw_remote_control_omitted,g.regulated_bus~=g.canonical_regulated_bus) && ...
    all(c.regulated_bus(1:height(g))==g.source_bus) && ...
    isequal(c.raw_remote_control_omitted(1:height(g)),g.raw_remote_control_omitted));
add("no_inferred_transformer_or_shunt_regulation",~any(c.canonical_enabled( ...
    c.source_control_role=="fixed_transformer_tap_no_automatic_control" | ...
    c.source_control_role=="static_BINIT_switched_control_disabled")));
add("boundary_21_candidates_20_imports_19_legacy",height(q)==21&&nnz(q.boundary_member)==20&&nnz(q.legacy_schedule_member)==19);
add("bus69_omission_explicit",nnz(q.source_bus==69 & q.source_generator_id=="X" & ...
    q.boundary_member & ~q.legacy_schedule_member & q.canonical_status==0 & ...
    q.proposed_schedule_group=="SCH - PJ - NY")==1);
add("reference_is_not_external_schedule",all(~q.boundary_member(q.source_device_role=="reference_placeholder")) && ...
    all(q.proposed_schedule_group(q.source_device_role=="reference_placeholder")=="UNASSIGNED_REFERENCE"));
[found,gi]=ismember(q.device_key,g.device_key);
add("boundary_identity_matches_generator_inventory",all(found) && ...
    isequal(q.source_gen_row,g.source_gen_row(gi)) && isequal(q.source_bus,g.source_bus(gi)) && ...
    isequal(q.source_device_role,g.source_device_role(gi)) && isequal(q.canonical_status,g.canonical_status(gi)));
add("offline_boundary_effective_PQ_zero",all(q.effective_pg_mw(q.canonical_status<=0)==0) && ...
    all(q.effective_qg_mvar(q.canonical_status<=0)==0));
add("source_roles_have_explicit_treatment",all(strlength(g.recommended_treatment)>0) && ...
    all(strlength(b.electrical_role)>0)&&all(strlength(l.source_device_role)>0));
add("no_qualification_from_inventory",~n.electrical_baseline_qualified&&~n.dlr_ready&& ...
    ~n.operating_point_solved&&~n.electrical_parameters_modified&&n.source_immutable && ...
    n.source_vintage=="PERFORM_NY_2019_v23"&&n.power_scale=="historical_actual_mw" && ...
    n.contemporary_validation_coverage=="none");
gates=table(names,passed,'VariableNames',{'gate','passed'});
out=struct('pass',all(passed),'gates',gates,'inventory_only',true,'electrical_baseline_qualified',false);
    function add(name,ok)
        names(end+1,1)=name;passed(end+1,1)=logical(ok);
    end
end
