function out = validate_s13_structural_preservation(options)
%VALIDATE_S13_STRUCTURAL_PRESERVATION Gate S13-FULL identity and provenance.
%   The default candidate is the cumulative full-NPCC construction parent.
%   Structural preservation can pass while qualification as the S14 reduction
%   source remains false. S13-FULL is never promotion-eligible itself.

if nargin < 1, options = struct(); end
if ~isfield(options, 'candidate_case')
    options.candidate_case = 'npcc_ny_lite_s13_npcc_augmented_2019';
end
if ~isfield(options, 'candidate_name')
    if isstruct(options.candidate_case)
        options.candidate_name = 'provided_s13_candidate';
    else
        options.candidate_name = char(options.candidate_case);
    end
end
if ~isfield(options, 'write_outputs'), options.write_outputs = true; end
if ~isfield(options, 'fail_on_structural'), options.fail_on_structural = true; end
if ~isfield(options, 'output_file')
    options.output_file = fullfile(fileparts(mfilename('fullpath')), ...
        's13_structural_preservation.csv');
end

helper_dir = fileparts(mfilename('fullpath'));
case_dir = fileparts(helper_dir);
addpath(case_dir); addpath(helper_dir);
define_constants;

original = loadcase('npcc_original');
s7 = loadcase('npcc_ny_lite_s7_seven_interface_perform_direct_candidate');
phase0_parent = apply_ny_core_phase0_corrections(s7, struct( ...
    'fit_reactance', false, 'verbose', false));
if isstruct(options.candidate_case)
    candidate = options.candidate_case;
else
    candidate = loadcase(options.candidate_case);
end

model_name = string(options.candidate_name);
[s13_metadata, s13_metadata_ok, s13_metadata_detail] = ...
    validate_s13_metadata(candidate);
model_role = "<missing>";
if isfield(s13_metadata, 'model_role')
    [candidate_role, candidate_role_ok] = scalar_text_value( ...
        s13_metadata.model_role);
    if candidate_role_ok
        model_role = candidate_role;
    else
        model_role = "<invalid>";
    end
end

rows = empty_gate_table();
rows = add_gate(rows, model_name, model_role, "provenance", ...
    "s13_metadata_coherence", ...
    "S13-FULL construction role, supported phase, cumulative and per-phase reports agree", ...
    s13_metadata_detail, s13_metadata_ok, true, true, ...
    "overlay_report is the cumulative source of truth; phase_reports stores " + ...
    "per-phase evidence; phase1a_report is a compatibility alias.");
rows = add_gate(rows, model_name, model_role, "source_baseline", ...
    "original_npcc_dimensions", "140 buses / 233 branches", ...
    sprintf('%d buses / %d branches', size(original.bus, 1), ...
    size(original.branch, 1)), ...
    size(original.bus, 1) == 140 && size(original.branch, 1) == 233, ...
    true, true, "Frozen source identity expected by the S13-FULL policy.");
rows = add_gate(rows, model_name, model_role, "structural_parent", ...
    "s7_dimensions", "143 buses / 246 branches / 62 generators", ...
    sprintf('%d buses / %d branches / %d generators', size(s7.bus, 1), ...
    size(s7.branch, 1), size(s7.gen, 1)), ...
    isequal([size(s7.bus, 1), size(s7.branch, 1), size(s7.gen, 1)], ...
    [143 246 62]), true, true, "S7 remains the NPCC structural provenance case.");

original_bus_rows_stable = size(candidate.bus, 1) >= 140 && ...
    isequal(candidate.bus(1:140, BUS_I), original.bus(:, BUS_I));
rows = add_gate(rows, model_name, model_role, "structural_preservation", ...
    "original_bus_row_identity", "all 140 original rows unchanged in position and ID", ...
    sprintf('%d of 140 row IDs match', count_matching_bus_rows(candidate, original)), ...
    original_bus_rows_stable, true, true, ...
    "Row identity is stronger than unordered bus membership.");

parent_bus_names_stable = has_stable_parent_bus_names(candidate, phase0_parent);
rows = add_gate(rows, model_name, model_role, "structural_preservation", ...
    "parent_bus_names_stable", ...
    "all 143 S7/Phase-0 normalized bus names unchanged", ...
    string(parent_bus_names_stable), parent_bus_names_stable, true, true, ...
    "Name identity is part of the attachment and provenance policy.");

original_branch_rows_stable = size(candidate.branch, 1) >= 233 && ...
    isequal(candidate.branch(1:233, [F_BUS T_BUS]), ...
    original.branch(:, [F_BUS T_BUS]));
rows = add_gate(rows, model_name, model_role, "structural_preservation", ...
    "original_branch_row_identity", ...
    "all 233 original rows retain ordered endpoints", ...
    sprintf('%d of 233 row endpoint identities match', ...
    count_matching_branch_rows(candidate, original, 233)), ...
    original_branch_rows_stable, true, true, ...
    "Parallel circuits are traced by stable row identity, not endpoint set alone.");

s7_bus_rows_stable = size(candidate.bus, 1) >= 143 && ...
    isequal(candidate.bus(1:143, BUS_I), s7.bus(:, BUS_I));
s7_branch_rows_stable = size(candidate.branch, 1) >= 246 && ...
    isequal(candidate.branch(1:246, [F_BUS T_BUS]), ...
    s7.branch(:, [F_BUS T_BUS]));
rows = add_gate(rows, model_name, model_role, "append_only", ...
    "s7_bus_rows_preserved", "first 143 S7 bus IDs unchanged", ...
    string(s7_bus_rows_stable), s7_bus_rows_stable, true, true, ...
    "All new physical terminals must be appended.");
rows = add_gate(rows, model_name, model_role, "append_only", ...
    "s7_branch_rows_preserved", "first 246 S7 branch endpoints unchanged", ...
    string(s7_branch_rows_stable), s7_branch_rows_stable, true, true, ...
    "Residualization may change registered R/X/B but never endpoints or row identity.");

fixed_bus_columns = [BUS_I BUS_TYPE BUS_AREA BASE_KV ZONE VMAX VMIN];
parent_bus_controls_stable = size(candidate.bus, 1) >= 143 && ...
    max(abs(candidate.bus(1:143, fixed_bus_columns) - ...
    phase0_parent.bus(:, fixed_bus_columns)), [], 'all') <= 1e-12;
fixed_branch_columns = [F_BUS T_BUS RATE_A RATE_B RATE_C TAP SHIFT ...
    BR_STATUS ANGMIN ANGMAX];
parent_branch_controls_stable = size(candidate.branch, 1) >= 246 && ...
    max(abs(candidate.branch(1:246, fixed_branch_columns) - ...
    phase0_parent.branch(:, fixed_branch_columns)), [], 'all') <= 1e-12;
original_online_rows = find(phase0_parent.branch(1:233, BR_STATUS) > 0);
original_online_still_active = size(candidate.branch, 1) >= 233 && ...
    all(candidate.branch(original_online_rows, BR_STATUS) > 0);
fixed_generator_columns = [GEN_BUS QMAX QMIN VG MBASE GEN_STATUS PMAX PMIN ...
    PC1 PC2 QC1MIN QC1MAX QC2MIN QC2MAX RAMP_AGC RAMP_10 RAMP_30 ...
    RAMP_Q APF];
generator_identity_stable = size(candidate.gen, 1) == size(phase0_parent.gen, 1) && ...
    max(abs(candidate.gen(:, fixed_generator_columns) - ...
    phase0_parent.gen(:, fixed_generator_columns)), [], 'all') <= 1e-12 && ...
    required_field_equal(candidate, phase0_parent, 'gencost') && ...
    optional_field_equal(candidate, phase0_parent, 'gentype') && ...
    optional_field_equal(candidate, phase0_parent, 'genfuel');
rows = add_gate(rows, model_name, model_role, "structural_preservation", ...
    "parent_bus_structural_controls", ...
    "S7/Phase-0 bus type area zone base-kV and limits unchanged", ...
    string(parent_bus_controls_stable), parent_bus_controls_stable, true, true, ...
    "Operating PD/QD/VM/VA are excluded from this identity comparison.");
rows = add_gate(rows, model_name, model_role, "structural_preservation", ...
    "parent_branch_status_and_controls", ...
    "S7/Phase-0 status tap shift and angle bounds unchanged", ...
    string(parent_branch_controls_stable), parent_branch_controls_stable, ...
    true, true, "Residualization may alter only registered R/X/B rows.");
rows = add_gate(rows, model_name, model_role, "structural_preservation", ...
    "original_online_branches_active", "all originally online rows remain active", ...
    string(original_online_still_active), original_online_still_active, ...
    true, true, "Outages belong in validation scenarios, not the base candidate.");
rows = add_gate(rows, model_name, model_role, "device_identity", ...
    "generator_capability_and_identity", ...
    "all 62 S7 generator identities limits capabilities costs and type/fuel retained", ...
    string(generator_identity_stable), generator_identity_stable, true, true, ...
    "PG/QG may change by operating point; fixed device fields remain traceable.");

transit_ok = all(ismember([9001; 9002; 9003], candidate.bus(:, BUS_I)));
rows = add_gate(rows, model_name, model_role, "structural_preservation", ...
    "s7_transit_buses_present", "9001|9002|9003", ...
    join(string(intersect([9001; 9002; 9003], candidate.bus(:, BUS_I))), "|"), ...
    transit_ok, true, true, "All three S7 transit buses must remain.");

[overlay, has_overlay] = overlay_metadata(candidate);
rows = add_gate(rows, model_name, model_role, "provenance", ...
    "overlay_metadata_present", "row-aligned S13 overlay metadata", ...
    string(has_overlay), has_overlay, true, true, ...
    "Free-text provenance alone is insufficient.");

added_bus_count = max(size(candidate.bus, 1) - 143, 0);
added_branch_count = max(size(candidate.branch, 1) - 246, 0);
registered_bus_count = 0; registered_branch_count = 0;
if has_overlay
    registered_bus_count = numel(overlay.added_bus_ids);
    registered_branch_count = numel(overlay.physical_branch_rows);
end
bus_registration_ok = has_overlay && added_bus_count == registered_bus_count && ...
    numel(unique(overlay.added_bus_ids)) == registered_bus_count && ...
    isequal(sort(overlay.added_bus_ids(:)), ...
    sort(candidate.bus(144:end, BUS_I))) && ...
    isequal(overlay.added_bus_rows(:), (144:size(candidate.bus, 1))');
branch_registration_ok = has_overlay && ...
    added_branch_count == registered_branch_count && ...
    isequal(overlay.physical_branch_rows(:), (247:size(candidate.branch, 1))');
rows = add_gate(rows, model_name, model_role, "provenance", ...
    "added_bus_registration", sprintf('%d appended buses with one map row each', ...
    added_bus_count), sprintf('%d appended / %d registered', ...
    added_bus_count, registered_bus_count), bus_registration_ok, true, true, ...
    "Every appended bus must be uniquely registered.");
rows = add_gate(rows, model_name, model_role, "provenance", ...
    "added_branch_registration", sprintf('%d appended branches with one map row each', ...
    added_branch_count), sprintf('%d appended / %d registered', ...
    added_branch_count, registered_branch_count), branch_registration_ok, ...
    true, true, "Every appended branch must be uniquely registered.");

overlay_identity_ok = has_overlay && ...
    string(overlay.target_model) == "npcc_ny_lite_s13_npcc_augmented_2019" && ...
    string(overlay.model_role) == "unpromoted_s13_candidate" && ...
    ismember(string(overlay.current_phase), ...
    ["phase1a","phase1b","phase1c","phase1d"]) && ...
    string(overlay.structural_parent) == ...
    "npcc_ny_lite_s7_seven_interface_perform_direct_candidate" && ...
    string(overlay.source_model) == "full_PERFORM_2019_case" && ...
    string(overlay.source_case) == ...
    "PERFORM/On Peak 2019 v23_Perform_NY/On Peak 2019 v23/" + ...
    "nyiso_On_Peak_v23_shunts_as_z_load.m";
rows = add_gate(rows, model_name, model_role, "provenance", ...
    "overlay_model_and_source_identity", ...
    "S13-FULL over S7 sourced only from full PERFORM 2019", ...
    string(overlay_identity_ok), overlay_identity_ok, true, true, ...
    "Candidate-supplied promoted/S12/Ward labels fail this gate.");

[branch_map, has_branch_map] = branch_map_from_candidate(candidate);
[bus_map, has_bus_map] = bus_map_from_candidate(candidate);
[path_register, has_path_register] = path_register_from_candidate(candidate);
perform_source = load_perform_source(helper_dir);
base_mva_ok = original.baseMVA == 100 && s7.baseMVA == 100 && ...
    phase0_parent.baseMVA == 100 && candidate.baseMVA == 100 && ...
    perform_source.baseMVA == 100;
rows = add_gate(rows, model_name, model_role, "base_identity", ...
    "common_base_mva", "NPCC parent candidate and PERFORM source all use 100 MVA", ...
    sprintf('original=%g s7=%g candidate=%g source=%g', original.baseMVA, ...
    s7.baseMVA, candidate.baseMVA, perform_source.baseMVA), ...
    base_mva_ok, true, true, ...
    "Copied per-unit impedances are meaningful only on the common base.");
source_exact = has_branch_map && has_bus_map && has_overlay && has_path_register && ...
    validate_source_exactness(candidate, branch_map, overlay, ...
    bus_map, path_register, perform_source);
rows = add_gate(rows, model_name, model_role, "source_exactness", ...
    "added_physical_r_x_b_and_ratings", ...
    "all registered rows match direct PERFORM R/X/B and RATE_A/B/C", ...
    string(source_exact), source_exact, true, true, ...
    "Physical rows may not be empirically retuned.");
bus_source_and_area_ok = has_bus_map && has_path_register && ...
    validate_bus_source_and_area(candidate, bus_map, path_register, perform_source);
rows = add_gate(rows, model_name, model_role, "source_exactness", ...
    "added_bus_source_and_npcc_area_mapping", ...
    "source IDs/names/base-kV retained and NPCC areas inherited from attachments", ...
    string(bus_source_and_area_ok), bus_source_and_area_ok, true, true, ...
    "PERFORM areas 69/71 remain provenance metadata, not NPCC control areas.");
attachment_name_match = has_bus_map && ...
    validate_attachment_name_match(candidate, bus_map, perform_source);
rows = add_gate(rows, model_name, model_role, "source_exactness", ...
    "attachment_name_match", ...
    "EDIC and RAMAPO attachment names match PERFORM after normalization", ...
    string(attachment_name_match), attachment_name_match, true, true, ...
    "Voltage and zone agreement do not replace exact-name attachment evidence.");
source_zero_injection_ok = has_bus_map && ...
    validate_source_zero_injection(bus_map, perform_source);
rows = add_gate(rows, model_name, model_role, "source_exactness", ...
    "source_added_terminals_zero_injection", ...
    "all appended terminals have zero source PD/QD/GS/BS", ...
    string(source_zero_injection_ok), source_zero_injection_ok, true, true, ...
    "Candidate zero injection must be supported by the PERFORM source rows.");

phase1a_minimum_ok = has_branch_map && has_bus_map && ...
    all(ismember([1228; 1222; 1567; 772], bus_map.model_bus)) && ...
    all(ismember([2137; 2131; 2154; 2133; 1567; 1568; 1571], ...
    branch_map.source_branch_row));
rows = add_gate(rows, model_name, model_role, "phase1a_minimum", ...
    "source_backed_e_g_overlay_present", ...
    "four Phase-1A terminals and seven direct source rows remain present", ...
    string(phase1a_minimum_ok), phase1a_minimum_ok, true, true, ...
    "Later Phase 1B/1C paths may append additional registered rows.");

phase1a_checkpoint_ok = s13_metadata_ok && ...
    isfield(s13_metadata.phase_reports, 'phase1a') && ...
    validate_phase1a_checkpoint(s13_metadata.phase_reports.phase1a, ...
    phase0_parent, helper_dir);
rows = add_gate(rows, model_name, model_role, "phase1a_immutability", ...
    "phase1a_report_rebuild_identity", ...
    "stored Phase-1A report exactly matches an independent S7 plus Phase-0 rebuild", ...
    string(phase1a_checkpoint_ok), phase1a_checkpoint_ok, true, true, ...
    "Later topology phases may append cumulative evidence but may not rewrite Phase 1A.");

[physical_register, has_physical_register] = physical_from_candidate(candidate);
physical_required = {'model_branch_row','model_from_bus','model_to_bus', ...
    'overlay_path_id','npcc_attachment_from_bus','npcc_attachment_to_bus', ...
    'source_model','source_case','source_branch_row','source_from_bus', ...
    'source_to_bus','source_circuit_id','source_r_pu','source_x_pu', ...
    'source_b_pu','source_rate_a_mva','source_rate_b_mva', ...
    'source_rate_c_mva','branch_classification','construction_method', ...
    'residual_overlap_status','dlr_eligible','dlr_data_status', ...
    'mapping_confidence','implementation_status'};
projection_ok = has_branch_map && has_physical_register && ...
    isequal(physical_register.Properties.VariableNames, physical_required) && ...
    height(physical_register) == height(branch_map) && ...
    isequal(physical_register.model_branch_row, branch_map.model_branch_row) && ...
    isequaln(physical_register, branch_map(:, ...
    physical_required));
dlr_mapping_ok = has_branch_map && ...
    all(~branch_map.dlr_eligible | ...
    branch_map.dlr_data_status == "complete_conductor_weather_mapping");
classification_ok = has_branch_map && projection_ok && dlr_mapping_ok && ...
    all(branch_map.branch_classification == "physical_circuit") && ...
    ~any(branch_map.dlr_eligible & ...
    branch_map.branch_classification ~= "physical_circuit");
rows = add_gate(rows, model_name, model_role, "dlr_scope", ...
    "only_physical_rows_can_be_dlr_eligible", "true", ...
    string(classification_ok), classification_ok, true, true, ...
    "Eligibility requires one-to-one registration and completed conductor/weather mapping.");

s12_marker = has_s12_marker(candidate);
s12_source_leak = has_branch_map && any(contains(lower(branch_map.source_model), "s12"));
kron_method_leak = has_branch_map && any(contains( ...
    lower(branch_map.construction_method), ["ward", "kron"]), 'all');
no_s12_leak = source_exact && branch_registration_ok && ...
    ~s12_marker && ~s12_source_leak && ~kron_method_leak;
rows = add_gate(rows, model_name, model_role, "model_hierarchy", ...
    "no_s12_kron_admittance", "no S12 markers sources or Ward/Kron construction", ...
    string(no_s12_leak), no_s12_leak, true, true, ...
    "S12 may supply reference evidence but never S13-FULL or S14 network admittance rows.");

changed_rxb = find(any(abs(candidate.branch(1:246, [BR_R BR_X BR_B]) - ...
    s7.branch(:, [BR_R BR_X BR_B])) > 1e-12, 2));
[residual_register, has_residual_register] = residual_from_candidate(candidate);
[residual_coverage_ok, registered_residual_rows] = ...
    validate_residual_register(candidate, phase0_parent, residual_register, ...
    has_residual_register, changed_rxb);
residual_class_policy_ok = has_residual_register && ...
    validate_residual_class_policy(residual_register, changed_rxb);
rows = add_gate(rows, model_name, model_role, "admittance_policy", ...
    "residual_candidate_class_policy", ...
    "direct overlaps separated from frozen adjacent calibration candidates", ...
    string(residual_class_policy_ok), residual_class_policy_ok, true, true, ...
    "Rows 40/42 need paired response evidence and strong regularization before adjustment.");
rows = add_gate(rows, model_name, model_role, "admittance_policy", ...
    "changed_parent_r_x_b_registered", ...
    "every changed S7 R/X/B row appears in the residual register", ...
    sprintf('%d changed / %d registered', numel(changed_rxb), ...
    numel(intersect(changed_rxb, registered_residual_rows))), ...
    residual_coverage_ok, true, true, ...
    "Phase 0 ratings-only changes do not alter R/X/B.");

changed_shunt_rows = find(any(abs(candidate.bus(1:143, [GS BS]) - ...
    phase0_parent.bus(:, [GS BS])) > 1e-12, 2));
[shunt_register, has_shunt_register] = residual_shunt_from_candidate(candidate);
[shunt_coverage_ok, registered_shunt_rows] = ...
    validate_residual_shunt_register(candidate, phase0_parent, ...
    shunt_register, has_shunt_register, changed_shunt_rows);
rows = add_gate(rows, model_name, model_role, "admittance_policy", ...
    "changed_parent_shunts_registered", ...
    "every changed S7 GS/BS row appears in the residual-shunt register", ...
    sprintf('%d changed / %d registered', numel(changed_shunt_rows), ...
    numel(intersect(changed_shunt_rows, registered_shunt_rows))), ...
    shunt_coverage_ok, true, true, ...
    "Phase 1A freezes shunts; later passive residual shunts require evidence.");

full_npcc = all(ismember(original.bus(:, BUS_I), candidate.bus(:, BUS_I))) && ...
    original_branch_rows_stable;
rows = add_gate(rows, model_name, model_role, "network_form", ...
    "full_npcc_not_boundary_equivalent", "all original NPCC buses and branch rows", ...
    string(full_npcc), full_npcc, true, true, ...
    "An NY-only equivalent cannot pass this gate.");

% Construction qualification is fail-closed until Phase 1B/1C, passive
% internal residualization, and a frozen solved reduction-source state are
% artifact-backed. Independent S12 response and public-hour operating gates
% belong to S14 promotion, not S13-FULL construction qualification.
phase1b_complete = s13_metadata_ok && ...
    validate_phase1b_minimum(candidate, s13_metadata);
phase1c_complete = s13_metadata_ok && ...
    isfield(s13_metadata.phase_reports, 'phase1c');
construction_validator_available = false;
rows = add_gate(rows, model_name, model_role, "construction_readiness", ...
    "dedicated_construction_validator_available", "implemented and artifact-backed", ...
    "not_implemented_fail_closed", construction_validator_available, ...
    false, true, "A separate S13-FULL construction validator must be implemented first.");
rows = add_gate(rows, model_name, model_role, "construction_readiness", ...
    "phase1b_physical_overlay_complete", "complete and artifact-backed", ...
    pending_or_complete(phase1b_complete, "pending_phase1b"), ...
    phase1b_complete, false, true, ...
    "UPNY-ConEd physical detail must be present before S14 retention freezes.");
rows = add_gate(rows, model_name, model_role, "construction_readiness", ...
    "phase1c_physical_overlay_complete", "complete and artifact-backed", ...
    pending_or_complete(phase1c_complete, "pending_phase1c"), ...
    phase1c_complete, false, true, ...
    "Downstate H-J/K-J physical detail must be present before S14 retention freezes.");
rows = add_gate(rows, model_name, model_role, "construction_readiness", ...
    "passive_residualization_complete", "complete and passive", ...
    overlay_status_value(overlay, has_overlay, 'residualization_status'), ...
    false, false, true, "Pending dedicated artifact-backed validation.");
rows = add_gate(rows, model_name, model_role, "construction_readiness", ...
    "s14_reduction_source_state_complete", ...
    "frozen solved source state with bounded controls", ...
    overlay_status_value(overlay, has_overlay, 's14_reduction_source_status'), ...
    false, false, true, ...
    "The external multi-port must be derived from a reproducible solved S13-FULL state.");

all_structural = all(rows.pass(rows.mandatory_for_structure));
all_construction = all(rows.pass(rows.mandatory_for_construction_qualification));
if options.write_outputs
    ny_lite_writetable_lf(rows, options.output_file);
end

out = struct('model_name', model_name, 'model_role', model_role, ...
    'gates', rows, 'all_structural_gates_pass', all_structural, ...
    'all_construction_gates_pass', all_construction, ...
    'construction_source_qualified', all_structural && all_construction, ...
    'all_promotion_gates_pass', false, ... % compatibility: S13 never promotes
    'promotion_eligible', false, ...
    'candidate_size', [size(candidate.bus, 1), size(candidate.branch, 1), ...
    size(candidate.gen, 1)], 'output_file', string(options.output_file));

if options.fail_on_structural && ~all_structural
    failed = rows.metric(rows.mandatory_for_structure & ~rows.pass);
    error('validate_s13_structural_preservation:StructuralGateFailed', ...
        'S13 structural gates failed: %s', strjoin(cellstr(failed), ', '));
end
end

function rows = empty_gate_table()
rows = table(strings(0,1), strings(0,1), strings(0,1), strings(0,1), ...
    strings(0,1), strings(0,1), false(0,1), false(0,1), false(0,1), ...
    false(0,1), ...
    strings(0,1), 'VariableNames', {'model_name','model_role','category', ...
    'metric','expected','measured','pass','mandatory_for_structure', ...
    'mandatory_for_construction_qualification','mandatory_for_promotion','note'});
end

function rows = add_gate(rows, model_name, model_role, category, metric, ...
        expected, measured, passed, structural, construction, note)
row = table(string(model_name), string(model_role), string(category), ...
    string(metric), string(expected), string(measured), logical(passed), ...
    logical(structural), logical(construction), false, string(note), ...
    'VariableNames', rows.Properties.VariableNames);
rows = [rows; row];
end

function n = count_matching_bus_rows(candidate, original)
nmax = min(size(candidate.bus, 1), size(original.bus, 1));
n = nnz(candidate.bus(1:nmax, 1) == original.bus(1:nmax, 1));
end

function n = count_matching_branch_rows(candidate, original, expected)
nmax = min([size(candidate.branch, 1), size(original.branch, 1), expected]);
n = nnz(all(candidate.branch(1:nmax, 1:2) == original.branch(1:nmax, 1:2), 2));
end

function [overlay, ok] = overlay_metadata(candidate)
overlay = struct(); ok = false;
if isfield(candidate, 'userdata') && ...
        isfield(candidate.userdata, 'npcc_perform_overlay')
    overlay = candidate.userdata.npcc_perform_overlay;
    needed = {'target_model','model_role','current_phase','structural_parent','source_model', ...
        'source_case','added_bus_rows','added_bus_ids','physical_branch_rows', ...
        'source_branch_rows','residualization_status','same_snapshot_status', ...
        'heldout_response_status','public_hour_status', ...
        's14_reduction_source_status','construction_source_qualified', ...
        'promotion_eligible'};
    ok = all(isfield(overlay, needed));
end
end

function [metadata, ok, detail] = validate_s13_metadata(candidate)
metadata = struct();
ok = false;
detail = "missing userdata.s13 metadata";
if ~isfield(candidate, 'userdata') || ~isfield(candidate.userdata, 's13') || ...
        ~isstruct(candidate.userdata.s13) || ~isscalar(candidate.userdata.s13)
    return;
end
metadata = candidate.userdata.s13;
required = {'metadata_schema_version','model_role','governing_hierarchy_role', ...
    'downstream_operating_model','dlr_delivery_eligible', ...
    'construction_source_qualified','promotion_eligible','current_phase', ...
    'overlay_report','phase_reports','phase1a_report'};
if ~all(isfield(metadata, required)) || ~isstruct(metadata.overlay_report) || ...
        ~isscalar(metadata.overlay_report) || ~isstruct(metadata.phase_reports) || ...
        ~isscalar(metadata.phase_reports) || ~isstruct(metadata.phase1a_report) || ...
        ~isscalar(metadata.phase1a_report)
    detail = "missing role, phase, cumulative report, per-phase report, or alias";
    return;
end
[role, role_scalar] = scalar_text_value(metadata.model_role);
[governing_role, governing_role_scalar] = ...
    scalar_text_value(metadata.governing_hierarchy_role);
[downstream_model, downstream_model_scalar] = ...
    scalar_text_value(metadata.downstream_operating_model);
schema_version_ok = isnumeric(metadata.metadata_schema_version) && ...
    isscalar(metadata.metadata_schema_version) && ...
    isfinite(metadata.metadata_schema_version) && ...
    metadata.metadata_schema_version == 2;
[phase, phase_scalar] = scalar_text_value(metadata.current_phase);
supported = ["phase1a","phase1b","phase1c","phase1d"];
phase_present = false;
if phase_scalar && ismember(phase, supported)
    phase_present = isfield(metadata.phase_reports, char(phase));
end
phase1a_present = isfield(metadata.phase_reports, 'phase1a') && ...
    isstruct(metadata.phase_reports.phase1a) && ...
    isscalar(metadata.phase_reports.phase1a);
alias_ok = phase1a_present && ...
    isequaln(metadata.phase1a_report, metadata.phase_reports.phase1a);
phase_reports_ok = false;
active_phases = strings(0, 1);
if phase_present
    current_index = find(supported == phase, 1);
    active_phases = supported(1:current_index);
    phase_reports_ok = true;
    for k = 1:current_index
        field = char(supported(k));
        if ~isfield(metadata.phase_reports, field) || ...
                ~validate_phase_report(metadata.phase_reports.(field), ...
                supported(k), metadata.overlay_report)
            phase_reports_ok = false;
            break;
        end
    end
end
cumulative_ok = phase_reports_ok && validate_cumulative_phase_union( ...
    metadata.phase_reports, active_phases, metadata.overlay_report);
overlay_ok = false;
if isfield(candidate.userdata, 'npcc_perform_overlay') && ...
        isstruct(candidate.userdata.npcc_perform_overlay) && ...
        isscalar(candidate.userdata.npcc_perform_overlay)
    overlay_metadata = candidate.userdata.npcc_perform_overlay;
    overlay_required = {'model_role','current_phase', ...
        'construction_source_qualified','promotion_eligible'};
    if all(isfield(overlay_metadata, overlay_required))
        [overlay_role, overlay_role_scalar] = ...
            scalar_text_value(overlay_metadata.model_role);
        [overlay_phase, overlay_phase_scalar] = ...
            scalar_text_value(overlay_metadata.current_phase);
        overlay_ok = role_scalar && phase_scalar && overlay_role_scalar && ...
            overlay_phase_scalar && overlay_role == role && ...
            overlay_phase == phase && ...
            is_false_scalar(overlay_metadata.construction_source_qualified) && ...
            is_false_scalar(overlay_metadata.promotion_eligible);
    end
end
hierarchy_ok = schema_version_ok && governing_role_scalar && ...
    governing_role == "s13_full_construction_validation_parent" && ...
    downstream_model_scalar && downstream_model == ...
    "npcc_ny_lite_s14_nyiso_dlr_operating_model" && ...
    is_false_scalar(metadata.dlr_delivery_eligible) && ...
    is_false_scalar(metadata.construction_source_qualified) && ...
    is_false_scalar(metadata.promotion_eligible);
ok = role_scalar && role == "unpromoted_s13_candidate" && hierarchy_ok && ...
    phase_present && phase1a_present && alias_ok && phase_reports_ok && ...
    cumulative_ok && overlay_ok;
detail = "schema_version=" + metadata_detail_value(metadata.metadata_schema_version) + ...
    "; compatibility_role=" + metadata_detail_value(metadata.model_role) + ...
    "; governing_role=" + metadata_detail_value(metadata.governing_hierarchy_role) + ...
    "; downstream=" + metadata_detail_value(metadata.downstream_operating_model) + ...
    "; dlr_delivery_eligible=" + metadata_detail_value(metadata.dlr_delivery_eligible) + ...
    "; construction_source_qualified=" + ...
    metadata_detail_value(metadata.construction_source_qualified) + ...
    "; promotion_eligible=" + metadata_detail_value(metadata.promotion_eligible) + ...
    "; phase=" + metadata_detail_value(metadata.current_phase) + ...
    "; current_phase_report=" + string(phase_present) + ...
    "; phase1a_alias=" + string(alias_ok) + ...
    "; phase_reports=" + string(phase_reports_ok) + ...
    "; cumulative=" + string(cumulative_ok) + ...
    "; overlay_metadata=" + string(overlay_ok);
end

function ok = validate_phase_report(report, phase, cumulative)
tables = {'bus_map','branch_map','residual_register', ...
    'residual_shunt_register','path_register','physical_register','operator_map'};
keys = {{'model_bus'},{'model_branch_row'},{'model_branch_row'},{'model_bus'}, ...
    {'overlay_path_id'},{'model_branch_row'}, ...
    {'interface_name','component_name','model_branch_row', ...
    'source_branch_row','source_circuit_id'}};
ok = isstruct(report) && isscalar(report) && isfield(report, 'phase_id') && ...
    isfield(report, 'construction_source_qualified') && ...
    isfield(report, 'promotion_eligible');
if ~ok, return; end
[report_phase, report_phase_scalar] = scalar_text_value(report.phase_id);
[expected_phase, expected_phase_scalar] = scalar_text_value(phase);
ok = ok && report_phase_scalar && expected_phase_scalar && ...
    report_phase == expected_phase && ...
    is_false_scalar(report.construction_source_qualified) && ...
    is_false_scalar(report.promotion_eligible) && isstruct(cumulative) && ...
    isscalar(cumulative);
if ~ok, return; end
for k = 1:numel(tables)
    name = tables{k}; key = keys{k};
    if ~isfield(report, name) || ~istable(report.(name)) || ...
            ~isfield(cumulative, name) || ~istable(cumulative.(name)) || ...
            ~isequal(report.(name).Properties.VariableNames, ...
            cumulative.(name).Properties.VariableNames) || ...
            ~all(ismember(key, report.(name).Properties.VariableNames)) || ...
            ~all(ismember(key, cumulative.(name).Properties.VariableNames))
        ok = false;
        return;
    end
    report_key = phase_table_key(report.(name), key);
    cumulative_key = phase_table_key(cumulative.(name), key);
    [found, location] = ismember(report_key, cumulative_key);
    if numel(unique(report_key)) ~= numel(report_key) || ...
            numel(unique(cumulative_key)) ~= numel(cumulative_key) || ...
            ~all(found) || ...
            ~isequaln(report.(name), cumulative.(name)(location, :))
        ok = false;
        return;
    end
end
ok = ~isempty(report.branch_map) && ~isempty(report.path_register);
end

function key = phase_table_key(value, columns)
key = strings(height(value), 1);
for k = 1:numel(columns)
    part = string(value.(columns{k}));
    part = replace(part, "|", "||");
    key = key + "|" + part;
end
end

function ok = validate_cumulative_phase_union(phase_reports, phases, cumulative)
tables = {'bus_map','branch_map','residual_register', ...
    'residual_shunt_register','path_register','physical_register','operator_map'};
keys = {{'model_bus'},{'model_branch_row'},{'model_branch_row'},{'model_bus'}, ...
    {'overlay_path_id'},{'model_branch_row'}, ...
    {'interface_name','component_name','model_branch_row', ...
    'source_branch_row','source_circuit_id'}};
ok = isstruct(cumulative) && isscalar(cumulative) && ~isempty(phases);
if ~ok, return; end
for k = 1:numel(tables)
    name = tables{k};
    if ~isfield(cumulative, name) || ~istable(cumulative.(name))
        ok = false;
        return;
    end
    combined = cumulative.(name)([], :);
    owned_keys = strings(0, 1);
    for p = 1:numel(phases)
        field = char(phases(p));
        if ~isfield(phase_reports, field) || ...
                ~isfield(phase_reports.(field), name) || ...
                ~istable(phase_reports.(field).(name)) || ...
                ~isequal(phase_reports.(field).(name).Properties.VariableNames, ...
                cumulative.(name).Properties.VariableNames)
            ok = false;
            return;
        end
        part = phase_reports.(field).(name);
        part_keys = phase_table_key(part, keys{k});
        if numel(unique(part_keys)) ~= numel(part_keys) || ...
                any(ismember(part_keys, owned_keys))
            ok = false;
            return;
        end
        owned_keys = [owned_keys; part_keys]; %#ok<AGROW>
        combined = [combined; part]; %#ok<AGROW>
    end
    if ~isequaln(combined, cumulative.(name))
        ok = false;
        return;
    end
end
end

function [map, ok] = branch_map_from_candidate(candidate)
map = table(); ok = false;
if isfield(candidate, 'userdata') && isfield(candidate.userdata, 's13') && ...
        isfield(candidate.userdata.s13, 'overlay_report') && ...
        isfield(candidate.userdata.s13.overlay_report, 'branch_map')
    map = candidate.userdata.s13.overlay_report.branch_map;
    ok = istable(map) && ~isempty(map);
end
end

function [map, ok] = bus_map_from_candidate(candidate)
map = table(); ok = false;
if isfield(candidate, 'userdata') && isfield(candidate.userdata, 's13') && ...
        isfield(candidate.userdata.s13, 'overlay_report') && ...
        isfield(candidate.userdata.s13.overlay_report, 'bus_map')
    map = candidate.userdata.s13.overlay_report.bus_map;
    ok = istable(map) && ~isempty(map);
end
end

function [map, ok] = path_register_from_candidate(candidate)
map = table(); ok = false;
if isfield(candidate, 'userdata') && isfield(candidate.userdata, 's13') && ...
        isfield(candidate.userdata.s13, 'overlay_report') && ...
        isfield(candidate.userdata.s13.overlay_report, 'path_register')
    map = candidate.userdata.s13.overlay_report.path_register;
    ok = istable(map) && ~isempty(map);
end
end

function [reg, ok] = residual_from_candidate(candidate)
reg = table(); ok = false;
if isfield(candidate, 'userdata') && isfield(candidate.userdata, 's13') && ...
        isfield(candidate.userdata.s13, 'overlay_report') && ...
        isfield(candidate.userdata.s13.overlay_report, 'residual_register')
    reg = candidate.userdata.s13.overlay_report.residual_register;
    ok = istable(reg);
end
end

function [reg, ok] = physical_from_candidate(candidate)
reg = table(); ok = false;
if isfield(candidate, 'userdata') && isfield(candidate.userdata, 's13') && ...
        isfield(candidate.userdata.s13, 'overlay_report') && ...
        isfield(candidate.userdata.s13.overlay_report, 'physical_register')
    reg = candidate.userdata.s13.overlay_report.physical_register;
    ok = istable(reg) && ~isempty(reg);
end
end

function [reg, ok] = residual_shunt_from_candidate(candidate)
reg = table(); ok = false;
if isfield(candidate, 'userdata') && isfield(candidate.userdata, 's13') && ...
        isfield(candidate.userdata.s13, 'overlay_report') && ...
        isfield(candidate.userdata.s13.overlay_report, 'residual_shunt_register')
    reg = candidate.userdata.s13.overlay_report.residual_shunt_register;
    ok = istable(reg);
end
end

function src = load_perform_source(helper_dir)
case_dir = fileparts(helper_dir);
root = fileparts(case_dir);
perform_dir = fullfile(root, 'PERFORM', ...
    'On Peak 2019 v23_Perform_NY', 'On Peak 2019 v23');
addpath(perform_dir);
src = nyiso_On_Peak_v23_shunts_as_z_load;
end

function ok = validate_phase1a_checkpoint(stored, phase0_parent, helper_dir)
try
    [~, rebuilt] = add_npcc_perform_eg_corridor(phase0_parent, struct( ...
        'write_registers', false, 'register_dir', helper_dir, ...
        'verbose', false));
    ok = isequaln(stored, rebuilt);
catch
    ok = false;
end
end

function ok = validate_phase1b_minimum(candidate, metadata)
ok = false;
if ~isfield(metadata, 'phase_reports') || ...
        ~isfield(metadata.phase_reports, 'phase1b')
    return;
end
report = metadata.phase_reports.phase1b;
required_tables = {'bus_map','branch_map','residual_register','path_register', ...
    'physical_register','operator_map'};
if ~isstruct(report) || ~isscalar(report) || ...
        ~all(isfield(report, required_tables)) || ...
        ~all(cellfun(@(f) istable(report.(f)), required_tables)) || ...
        ~isfield(report, 'operator_detail') || ~istable(report.operator_detail)
    return;
end
required_source_rows = [1389; 1390; 1391; 1392; 1689; 1690; ...
    1577; 1576; 1738];
required_operator_rows = [1389; 1390; 1391; 1392; 1576; 1738];
required_paths = ["phase1b_pv_wood_mesh"; ...
    "phase1b_ramapo_buchanan_path"];
ok = all(ismember([858; 774], report.bus_map.model_bus)) && ...
    isequal(sort(report.branch_map.source_branch_row), ...
    sort(required_source_rows)) && ...
    isequal(sort(report.operator_map.source_branch_row), ...
    sort(required_operator_rows)) && ...
    all(ismember([94; 235], report.residual_register.model_branch_row)) && ...
    all(ismember(required_paths, report.path_register.overlay_path_id)) && ...
    all(ismember([858; 774], candidate.bus(:, 1))) && ...
    all(report.operator_map.is_exact_public_operator == false) && ...
    isfield(report, 'generation_audit') && istable(report.generation_audit) && ...
    isfield(report, 'terminal_reuse_audit') && ...
    istable(report.terminal_reuse_audit) && ...
    all(ismember({'source_branch_row','operator_membership', ...
    'cutset_from_side','cutset_to_side','is_exact_public_operator'}, ...
    report.operator_detail.Properties.VariableNames)) && ...
    isequal(sort(report.operator_detail.source_branch_row( ...
    report.operator_detail.operator_membership)), ...
    sort(required_operator_rows)) && ...
    all(~report.operator_detail.is_exact_public_operator);
end

function ok = validate_source_exactness(candidate, map, overlay, bus_map, paths, src)
define_constants;
required = {'model_branch_row','model_from_bus','model_to_bus', ...
    'overlay_path_id','npcc_attachment_from_bus','npcc_attachment_to_bus', ...
    'source_model','source_case','source_branch_row','source_from_bus', ...
    'source_to_bus','source_r_pu','source_x_pu','source_b_pu', ...
    'source_rate_a_mva','source_rate_b_mva','source_rate_c_mva', ...
    'source_circuit_id','branch_classification','construction_method'};
path_required = {'overlay_path_id','npcc_attachment_from_bus', ...
    'npcc_attachment_to_bus','source_attachment_from_bus', ...
    'source_attachment_to_bus'};
if ~all(ismember(required, map.Properties.VariableNames)) || ...
        ~all(ismember(path_required, paths.Properties.VariableNames)) || ...
        numel(unique(paths.overlay_path_id)) ~= height(paths)
    ok = false;
    return;
end
rows = map.model_branch_row;
source_rows = map.source_branch_row;
expected_rows = (247:size(candidate.branch, 1))';
ok = isequal(sort(rows(:)), expected_rows) && ...
    numel(unique(rows)) == height(map) && ...
    numel(unique(source_rows)) == height(map) && ...
    isequal(rows(:), overlay.physical_branch_rows(:)) && ...
    isequal(source_rows(:), overlay.source_branch_rows(:)) && ...
    all(rows >= 1 & rows <= size(candidate.branch, 1)) && ...
    all(source_rows >= 1 & source_rows <= size(src.branch, 1));
if ~ok, return; end

source_endpoints = src.branch(source_rows, [F_BUS T_BUS]);
model_endpoints = candidate.branch(rows, [F_BUS T_BUS]);
ok = isequal(source_endpoints, [map.source_from_bus map.source_to_bus]) && ...
    isequal(model_endpoints, [map.model_from_bus map.model_to_bus]) && ...
    all(map.source_model == "full_PERFORM_2019_case") && ...
    all(map.source_case == "PERFORM/On Peak 2019 v23_Perform_NY/" + ...
    "On Peak 2019 v23/nyiso_On_Peak_v23_shunts_as_z_load.m") && ...
    all(map.branch_classification == "physical_circuit") && ...
    all(map.construction_method == ...
    "direct_perform_electrical_copy_neutral_angle_bounds");
if ~ok, return; end

for k = 1:height(map)
    pi = find(paths.overlay_path_id == map.overlay_path_id(k), 1);
    fmi = find(bus_map.source_bus == map.source_from_bus(k), 1);
    tmi = find(bus_map.source_bus == map.source_to_bus(k), 1);
    if isempty(pi) || ...
            isempty(fmi) || isempty(tmi) || ...
            map.model_from_bus(k) ~= bus_map.model_bus(fmi) || ...
            map.model_to_bus(k) ~= bus_map.model_bus(tmi) || ...
            map.npcc_attachment_from_bus(k) ~= paths.npcc_attachment_from_bus(pi) || ...
            map.npcc_attachment_to_bus(k) ~= paths.npcc_attachment_to_bus(pi)
        ok = false;
        return;
    end
end

phase1a_rows = [2137; 2131; 2154; 2133; 1567; 1568; 1571];
phase1a_circuits = ["1"; "1"; "1"; "1"; "1"; "2"; "1"];
for k = 1:numel(phase1a_rows)
    mi = find(source_rows == phase1a_rows(k), 1);
    if isempty(mi) || map.source_circuit_id(mi) ~= phase1a_circuits(k)
        ok = false;
        return;
    end
end
if any(strlength(map.source_circuit_id) == 0)
    ok = false;
    return;
end

mapped_source = [map.source_r_pu, map.source_x_pu, map.source_b_pu, ...
    map.source_rate_a_mva, map.source_rate_b_mva, map.source_rate_c_mva];
actual_source = src.branch(source_rows, ...
    [BR_R BR_X BR_B RATE_A RATE_B RATE_C]);
actual_candidate = candidate.branch(rows, ...
    [BR_R BR_X BR_B RATE_A RATE_B RATE_C]);
source_controls = src.branch(source_rows, [TAP SHIFT BR_STATUS]);
candidate_controls = candidate.branch(rows, [TAP SHIFT BR_STATUS]);
ok = max(abs(mapped_source - actual_source), [], 'all') <= 1e-12 && ...
    max(abs(actual_candidate - actual_source), [], 'all') <= 1e-12 && ...
    max(abs(candidate_controls - source_controls), [], 'all') <= 1e-12 && ...
    all(candidate.branch(rows, ANGMIN) == -360) && ...
    all(candidate.branch(rows, ANGMAX) == 360);
end

function ok = validate_bus_source_and_area(candidate, map, paths, src)
define_constants;
zone_metadata = nyiso_zone_metadata;
required = {'model_bus','model_bus_name','model_action','source_model', ...
    'source_case','source_bus','source_bus_name','source_base_kv', ...
    'source_area','source_vm_pu','source_va_deg','model_area', ...
    'source_pd_mw','source_qd_mvar','source_gs_mw','source_bs_mvar', ...
    'physical_zone','overlay_path_id', ...
    'npcc_attachment_bus','source_attachment_bus','terminal_electrical_policy'};
if ~all(ismember(required, map.Properties.VariableNames)) || isempty(map) || ...
        numel(unique(map.model_bus)) ~= height(map) || ...
        numel(unique(map.source_bus)) ~= height(map) || ...
        ~all(ismember({'from_zone','to_zone'}, paths.Properties.VariableNames)) || ...
        ~isfield(candidate, 'userdata') || ...
        ~isfield(candidate.userdata, 'nyiso_physical_zone') || ...
        ~isfield(candidate.userdata, 'perform_zone_code') || ...
        numel(candidate.userdata.nyiso_physical_zone) ~= size(candidate.bus, 1) || ...
        numel(candidate.userdata.perform_zone_code) ~= size(candidate.bus, 1)
    ok = false;
    return;
end
added_ids = candidate.bus(144:end, BUS_I);
added_map = map.model_bus(map.model_action == "appended_physical_terminal");
ok = isequal(sort(added_map), sort(added_ids)) && ...
    all(map.source_model == "full_PERFORM_2019_case") && ...
    all(map.source_case == "PERFORM/On Peak 2019 v23_Perform_NY/" + ...
    "On Peak 2019 v23/nyiso_On_Peak_v23_shunts_as_z_load.m") && ...
    all(ismember(map.overlay_path_id, paths.overlay_path_id));
if ~ok, return; end
for k = 1:height(map)
    mi = find(candidate.bus(:, BUS_I) == map.model_bus(k), 1);
    si = find(src.bus(:, BUS_I) == map.source_bus(k), 1);
    ai = find(candidate.bus(:, BUS_I) == map.npcc_attachment_bus(k), 1);
    asi = find(src.bus(:, BUS_I) == map.source_attachment_bus(k), 1);
    pi = find(paths.overlay_path_id == map.overlay_path_id(k), 1);
    if isempty(mi) || isempty(si) || isempty(ai) || isempty(asi) || isempty(pi)
        ok = false;
        return;
    end
    expected_zone = "";
    if ~isempty(pi) && map.npcc_attachment_bus(k) == paths.npcc_attachment_from_bus(pi)
        expected_zone = paths.from_zone(pi);
    elseif ~isempty(pi) && map.npcc_attachment_bus(k) == paths.npcc_attachment_to_bus(pi)
        expected_zone = paths.to_zone(pi);
    end
    source_zone_index = find([zone_metadata.perform_zone_code] == ...
        src.bus(si, ZONE), 1);
    source_zone_letter = "";
    if ~isempty(source_zone_index)
        source_zone_letter = string(zone_metadata(source_zone_index).letter);
    end
    if expected_zone == "" || source_zone_letter == "" || ...
            map.physical_zone(k) ~= expected_zone || ...
            map.physical_zone(k) ~= source_zone_letter || ...
            candidate.bus(mi, BUS_AREA) ~= map.model_area(k) || ...
            candidate.bus(mi, BUS_AREA) ~= candidate.bus(ai, BUS_AREA) || ...
            candidate.bus(mi, ZONE) ~= src.bus(si, ZONE) || ...
            candidate.userdata.perform_zone_code(mi) ~= candidate.bus(mi, ZONE) || ...
            string(candidate.userdata.nyiso_physical_zone{mi}) ~= map.physical_zone(k) || ...
            abs(candidate.bus(mi, BASE_KV) - src.bus(si, BASE_KV)) > 1e-12 || ...
            abs(map.source_base_kv(k) - src.bus(si, BASE_KV)) > 1e-12 || ...
            map.source_area(k) ~= src.bus(si, BUS_AREA) || ...
            abs(map.source_vm_pu(k) - src.bus(si, VM)) > 1e-12 || ...
            abs(map.source_va_deg(k) - src.bus(si, VA)) > 1e-12 || ...
            abs(map.source_pd_mw(k) - src.bus(si, PD)) > 1e-12 || ...
            abs(map.source_qd_mvar(k) - src.bus(si, QD)) > 1e-12 || ...
            abs(map.source_gs_mw(k) - src.bus(si, GS)) > 1e-12 || ...
            abs(map.source_bs_mvar(k) - src.bus(si, BS)) > 1e-12 || ...
            map.source_bus_name(k) ~= string(strtrim(src.bus_name{si})) || ...
            map.model_bus_name(k) ~= string(strtrim(candidate.bus_name{mi}))
        ok = false;
        return;
    end
    if map.model_action(k) == "appended_physical_terminal"
        if map.terminal_electrical_policy(k) ~= ...
                "pq_zero_injection_source_limits" || ...
                candidate.bus(mi, BUS_TYPE) ~= PQ || ...
                any(abs(candidate.bus(mi, [PD QD GS BS])) > 1e-12) || ...
                any(abs(src.bus(si, [PD QD GS BS])) > 1e-12) || ...
                abs(candidate.bus(mi, VMAX) - src.bus(si, VMAX)) > 1e-12 || ...
                abs(candidate.bus(mi, VMIN) - src.bus(si, VMIN)) > 1e-12
            ok = false;
            return;
        end
    elseif map.model_action(k) == "retained_existing_npcc_attachment"
        if map.terminal_electrical_policy(k) ~= "retained_npcc_unchanged"
            ok = false;
            return;
        end
    elseif map.model_action(k) == "retained_existing_npcc_attachment_proxy"
        if map.terminal_electrical_policy(k) ~= ...
                "retained_npcc_control_and_injection_not_source_copied"
            ok = false;
            return;
        end
    else
        ok = false;
        return;
    end
end

for k = 1:height(paths)
    mf = find(candidate.bus(:, BUS_I) == paths.npcc_attachment_from_bus(k), 1);
    mt = find(candidate.bus(:, BUS_I) == paths.npcc_attachment_to_bus(k), 1);
    sf = find(src.bus(:, BUS_I) == paths.source_attachment_from_bus(k), 1);
    st = find(src.bus(:, BUS_I) == paths.source_attachment_to_bus(k), 1);
    if isempty(mf) || isempty(mt) || isempty(sf) || isempty(st) || ...
            abs(candidate.bus(mf, BASE_KV) - src.bus(sf, BASE_KV)) > 1e-12 || ...
            abs(candidate.bus(mt, BASE_KV) - src.bus(st, BASE_KV)) > 1e-12
        ok = false;
        return;
    end
end
end

function [ok, registered_rows] = validate_residual_register( ...
        candidate, parent, reg, exists, changed_rows)
define_constants;
registered_rows = [];
required = {'model_branch_row','from_bus','to_bus','original_r_pu', ...
    'original_x_pu','original_b_pu','classification','overlap_scope', ...
    'adjustment_evidence_requirement','adjustment_evidence_status', ...
    'regularization_policy', ...
    'fitted_r_pu','fitted_x_pu','fitted_b_pu','fit_objective', ...
    'residual_resistance_nonnegative','passivity_min_eigenvalue', ...
    'passivity_gate_pass','fit_status','passivity_status','dlr_eligible','freeze'};
ok = exists && istable(reg) && ~isempty(reg) && ...
    isequal(reg.Properties.VariableNames, required) && ...
    numel(unique(reg.model_branch_row)) == height(reg) && ...
    all(reg.model_branch_row >= 1 & reg.model_branch_row <= 246);
if ~ok, return; end
registered_rows = reg.model_branch_row(:);
ok = all(ismember(changed_rows, registered_rows)) && ...
    isequal(parent.branch(registered_rows, [F_BUS T_BUS]), ...
    [reg.from_bus reg.to_bus]) && ...
    max(abs(parent.branch(registered_rows, [BR_R BR_X BR_B]) - ...
    [reg.original_r_pu reg.original_x_pu reg.original_b_pu]), [], 'all') <= 1e-12 && ...
    all(ismember(reg.classification, ["physical_overlap_residual_candidate", ...
    "adjacent_equivalent_calibration_candidate"])) && ...
    all(~reg.dlr_eligible);
if ~ok, return; end
for k = 1:height(reg)
    row = reg.model_branch_row(k);
    changed = ismember(row, changed_rows);
    if changed
        ok = isfinite(reg.fitted_r_pu(k)) && isfinite(reg.fitted_x_pu(k)) && ...
            isfinite(reg.fitted_b_pu(k)) && isfinite(reg.fit_objective(k)) && ...
            reg.fit_objective(k) >= 0 && reg.fitted_r_pu(k) >= 0 && ...
            islogical(reg.residual_resistance_nonnegative) && ...
            reg.residual_resistance_nonnegative(k) && ...
            isfinite(reg.passivity_min_eigenvalue(k)) && ...
            reg.passivity_min_eigenvalue(k) >= -1e-9 && ...
            islogical(reg.passivity_gate_pass) && reg.passivity_gate_pass(k) && ...
            reg.fit_status(k) == "complete" && reg.passivity_status(k) == "pass" && ...
            max(abs(candidate.branch(row, [BR_R BR_X BR_B]) - ...
            [reg.fitted_r_pu(k) reg.fitted_x_pu(k) reg.fitted_b_pu(k)])) <= 1e-12;
    else
        ok = max(abs(candidate.branch(row, [BR_R BR_X BR_B]) - ...
            parent.branch(row, [BR_R BR_X BR_B]))) <= 1e-12;
    end
    if ~ok, return; end
end
end

function ok = validate_residual_class_policy(reg, changed_rows)
required = {'model_branch_row','classification','adjustment_evidence_requirement', ...
    'adjustment_evidence_status','regularization_policy','freeze'};
ok = istable(reg) && all(ismember(required, reg.Properties.VariableNames)) && ...
    islogical(reg.freeze);
if ~ok, return; end
physical = reg.classification == "physical_overlap_residual_candidate";
adjacent = reg.classification == "adjacent_equivalent_calibration_candidate";
ok = all(ismember([34; 36], reg.model_branch_row(physical))) && ...
    all(ismember([40; 42], reg.model_branch_row(adjacent))) && ...
    all(reg.adjustment_evidence_requirement(physical) == ...
    "source_topology_overlap_and_passivity") && ...
    all(ismember(reg.adjustment_evidence_status(physical), ...
    ["source_topology_overlap_registered", "pass"])) && ...
    all(reg.regularization_policy(physical) == "passive_residual_fit") && ...
    all(~reg.freeze(physical)) && ...
    all(reg.adjustment_evidence_requirement(adjacent) == ...
    "paired_multi_snapshot_response_and_passivity");
if ~ok, return; end
for k = find(adjacent)'
    changed = ismember(reg.model_branch_row(k), changed_rows);
    if changed
        ok = reg.adjustment_evidence_status(k) == ...
            "paired_multi_snapshot_response_pass" && ...
            reg.regularization_policy(k) == ...
            "strong_deviation_penalty_applied" && ~reg.freeze(k);
    else
        ok = (reg.adjustment_evidence_status(k) == ...
            "pending_paired_response_evidence" && ...
            reg.regularization_policy(k) == ...
            "strong_deviation_penalty_required" && reg.freeze(k)) || ...
            (reg.adjustment_evidence_status(k) == ...
            "paired_multi_snapshot_response_pass" && ...
            reg.regularization_policy(k) == ...
            "strong_deviation_penalty_applied" && ~reg.freeze(k));
    end
    if ~ok, return; end
end
end

function [ok, registered_rows] = validate_residual_shunt_register( ...
        candidate, parent, reg, exists, changed_rows)
define_constants;
registered_rows = [];
required = {'model_bus','original_gs_mw_at_v1','original_bs_mvar_at_v1', ...
    'fitted_gs_mw_at_v1','fitted_bs_mvar_at_v1','fit_status', ...
    'passivity_status','provenance','passivity_gate_pass'};
ok = exists && istable(reg) && ...
    isequal(reg.Properties.VariableNames, required);
if ~ok, return; end
if isempty(reg)
    ok = isempty(changed_rows);
    return;
end
[found, registered_rows] = ismember(reg.model_bus, parent.bus(:, BUS_I));
ok = all(found) && numel(unique(reg.model_bus)) == height(reg) && ...
    all(ismember(changed_rows, registered_rows)) && ...
    max(abs(parent.bus(registered_rows, [GS BS]) - ...
    [reg.original_gs_mw_at_v1 reg.original_bs_mvar_at_v1]), [], 'all') <= 1e-12;
if ~ok, return; end
for k = 1:height(reg)
    row = registered_rows(k);
    changed = ismember(row, changed_rows);
    if changed
        ok = isfinite(reg.fitted_gs_mw_at_v1(k)) && ...
            isfinite(reg.fitted_bs_mvar_at_v1(k)) && ...
            islogical(reg.passivity_gate_pass) && reg.passivity_gate_pass(k) && ...
            reg.fit_status(k) == "complete" && reg.passivity_status(k) == "pass" && ...
            strlength(reg.provenance(k)) > 0 && ...
            max(abs(candidate.bus(row, [GS BS]) - ...
            [reg.fitted_gs_mw_at_v1(k) reg.fitted_bs_mvar_at_v1(k)])) <= 1e-12;
    else
        ok = max(abs(candidate.bus(row, [GS BS]) - ...
            parent.bus(row, [GS BS]))) <= 1e-12;
    end
    if ~ok, return; end
end
end

function tf = has_s12_marker(candidate)
tf = false;
if ~isfield(candidate, 'userdata'), return; end
names = lower(string(fieldnames(candidate.userdata)));
tf = any(startsWith(names, "s12"));
end

function tf = has_stable_parent_bus_names(candidate, parent)
tf = isfield(candidate, 'bus_name') && isfield(parent, 'bus_name') && ...
    numel(candidate.bus_name) >= 143 && numel(parent.bus_name) == 143 && ...
    isequal(normalize_bus_names(candidate.bus_name(1:143)), ...
    normalize_bus_names(parent.bus_name));
end

function ok = validate_attachment_name_match(candidate, map, src)
ok = isfield(candidate, 'bus_name') && isfield(src, 'bus_name') && ...
    all(ismember({'model_bus','source_bus','model_action','model_bus_name', ...
    'source_bus_name'}, map.Properties.VariableNames));
if ~ok, return; end
attachment = find(startsWith(map.model_action, ...
    "retained_existing_npcc_attachment"));
phase1a_pairs = [43 1233; 76 1519];
actual_pairs = [map.model_bus(attachment) map.source_bus(attachment)];
ok = ~isempty(attachment) && ...
    all(ismember(phase1a_pairs, actual_pairs, 'rows'));
if ~ok, return; end
for k = attachment'
    mi = find(candidate.bus(:, 1) == map.model_bus(k), 1);
    si = find(src.bus(:, 1) == map.source_bus(k), 1);
    if isempty(mi) || isempty(si)
        ok = false;
        return;
    end
    model_name = normalize_bus_names(candidate.bus_name(mi));
    source_name = normalize_bus_names(src.bus_name(si));
    ok = attachment_names_equivalent(model_name, source_name, ...
        map.model_bus(k), map.source_bus(k)) && ...
        normalize_bus_names(map.model_bus_name(k)) == model_name && ...
        normalize_bus_names(map.source_bus_name(k)) == source_name;
    if ~ok, return; end
end
end

function ok = attachment_names_equivalent(model_name, source_name, ...
        model_bus, source_bus)
ok = model_name == source_name;
if ok, return; end
% The original NPCC case abbreviates Pleasant Valley as PLEASANT VLY.
ok = model_bus == 73 && source_bus == 651 && ...
    model_name == "PLEASANT VLY" && source_name == "PLEASANT VALLEY";
end

function ok = validate_source_zero_injection(map, src)
define_constants;
required = {'source_bus','model_action','source_pd_mw','source_qd_mvar', ...
    'source_gs_mw','source_bs_mvar'};
ok = all(ismember(required, map.Properties.VariableNames));
if ~ok, return; end
added = find(map.model_action == "appended_physical_terminal");
ok = ~isempty(added);
if ~ok, return; end
for k = added'
    si = find(src.bus(:, BUS_I) == map.source_bus(k), 1);
    if isempty(si)
        ok = false;
        return;
    end
    source_values = src.bus(si, [PD QD GS BS]);
    mapped_values = [map.source_pd_mw(k) map.source_qd_mvar(k) ...
        map.source_gs_mw(k) map.source_bs_mvar(k)];
    ok = max(abs(source_values), [], 'all') <= 1e-12 && ...
        max(abs(mapped_values - source_values), [], 'all') <= 1e-12;
    if ~ok, return; end
end
end

function names = normalize_bus_names(values)
names = upper(strtrim(string(values(:))));
end

function tf = optional_field_equal(a, b, field)
tf = isfield(a, field) == isfield(b, field);
if tf && isfield(a, field)
    tf = isequaln(a.(field), b.(field));
end
end

function tf = required_field_equal(a, b, field)
tf = isfield(a, field) && isfield(b, field) && ...
    isequaln(a.(field), b.(field));
end

function tf = is_false_scalar(value)
tf = isscalar(value) && ...
    ((islogical(value) && ~value) || ...
    (isnumeric(value) && isfinite(value) && value == 0));
end

function [value, ok] = scalar_text_value(raw)
value = "<invalid>";
ok = false;
if isstring(raw)
    if isscalar(raw) && ~ismissing(raw) && strlength(raw) > 0
        value = raw;
        ok = true;
    end
elseif ischar(raw) && isrow(raw) && ~isempty(raw)
    value = string(raw);
    ok = true;
end
end

function value = metadata_detail_value(raw)
[value, ok] = scalar_text_value(raw);
if ok
    return;
end
if (islogical(raw) || isnumeric(raw)) && isscalar(raw)
    value = string(raw);
    return;
end
value = "<invalid:" + string(class(raw)) + ":" + ...
    strjoin(string(size(raw)), "x") + ">";
end

function value = pending_or_complete(complete, pending_value)
if complete
    value = "complete";
else
    value = string(pending_value);
end
end

function v = overlay_status_value(overlay, exists, field)
if exists && isfield(overlay, field)
    v = string(overlay.(field));
else
    v = "missing";
end
end
