function out=export_compact_network(options)
%EXPORT_COMPACT_NETWORK Isolated historical compact comparison inputs.
% No power flow, optimization, interface-target fit, or historical overwrite.
% The 51-bus gross NPCC construction is exported before any 2025 overlay.
% Two Indian Point placements isolate released allocation from compact roles.
if nargin<1,options=struct();end
root=fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(fullfile(root,'System Matpower Format','NY_Lite'));
if ~isfield(options,'write_outputs'),options.write_outputs=true;end
if ~isfield(options,'output_dir'),options.output_dir=fullfile(root,'output','nygrid_compact_2019','compact');end
if ~isfield(options,'export_current_inputs'),options.export_current_inputs=true;end
gamma=0.358662225381536;define_constants;
b=build_compact_npcc_corridors;assert(b.validation.pass);
ny=b.ny_bus_mask;br=b.ny_branch_mask;ge=b.ny_generator_mask;c=b.candidate;
m=struct('version','2','baseMVA',c.baseMVA,'bus',c.bus(ny,1:13), ...
    'branch',c.branch(br,1:13),'gen',c.gen(ge,1:21), ...
    'bus_name',{c.bus_name(ny)},'userdata',struct('nyiso_physical_zone',{c.userdata.nyiso_physical_zone(ny)}));
keys=string(b.branch_keys(br));gkeys=string(b.generator_keys(ge));
assert(isequal([size(m.bus,1) size(m.branch,1) sum(m.branch(:,BR_STATUS)>0) size(m.gen,1)],[51 92 87 35]));
assert(all(ismember((37:82)',m.bus(:,BUS_I)))&&m.baseMVA==100);
% This exported network carries gross loads and NO old reference-boundary
% negative loads. Incoming snapshot schedules must be subtracted exactly once.
m.bus(m.bus(:,BUS_TYPE)==REF,BUS_TYPE)=PV;m.bus(m.bus(:,BUS_I)==42,BUS_TYPE)=REF;
m.gencost=[2*ones(35,1),zeros(35,2),3*ones(35,1),zeros(35,3)];
parent=struct('candidate',m,'branch_keys',keys,'generator_keys',gkeys);
parent.operators=compact_nyiso_interface_operator_variant(m,keys);
parent.legacy_operators=compact_nyiso_interface_operators(m,keys);
parent.reference_policy="native_42_balances_losses_not_Indian_Point_observation";
parent.power_policy="gross_NPCC_benchmark_load_no_frozen_boundary_injection";
variants=struct('paper74',fleet(parent,74,gamma),'physical77',fleet(parent,77,gamma));

zone_file=fullfile(root,'tmp','nygrid_2019_reproduction','upstream','Data','npcc.csv');
paper=readtable(zone_file,'TextType','string');[found,ix]=ismember(m.bus(:,BUS_I),paper.idx);
paper_zone=repmat("not_in_released_NPCC_allocation",51,1);paper_zone(found)=string(paper.zone(ix(found)));
metadata=table((1:51)',m.bus(:,BUS_I),string(m.bus_name),m.bus(:,BASE_KV), ...
    string(m.userdata.nyiso_physical_zone(:)),paper_zone,found, ...
    ismember(m.bus(:,BUS_I),(37:82)'),m.bus(:,PD),m.bus(:,QD), ...
    'VariableNames',{'bus_row','bus_id','compact_bus_name','base_kv','compact_physical_zone', ...
    'paper_allocation_zone','paper_identity_found','original_46_NPCC_NY_bus','parent_gross_pd_mw','parent_gross_qd_mvar'});
metadata.zone_roles_differ=found&metadata.compact_physical_zone~=paper_zone;
metadata.zone_policy=repmat("separate_allocation_and_physical_roles_neither_relabelled",51,1);
branch_map=table((1:92)',find(br),keys,m.branch(:,F_BUS),m.branch(:,T_BUS),m.branch(:,BR_STATUS), ...
    'VariableNames',{'branch_row','full_branch_row','branch_key','from_bus','to_bus','status'});
branch_map.role=repmat("inherited_NPCC_or_S7_equivalent",92,1);
branch_map.role(startsWith(keys,"PERFORM2019:AC:"))="source_circuit_electrical_parameters";
source_files={fullfile(root,'scripts','nygrid_compact_2019','export_compact_network.m'); ...
    fullfile(root,'scripts','nygrid_compact_2019','test_export_compact_network.m'); ...
    fullfile(root,'System Matpower Format','NY_Lite','build_compact_npcc_corridors.m'); ...
    fullfile(root,'System Matpower Format','NY_Lite','compact_nyiso_interface_operator_variant.m'); ...
    fullfile(root,'System Matpower Format','NY_Lite','compact_nyiso_interface_operators.m'); ...
    fullfile(root,'System Matpower Format','NY_Lite','nyiso_bus_zone_map.m');zone_file; ...
    fullfile(root,'tmp','nygrid_2019_reproduction','upstream','updateOpCond.m')};
source_manifest=manifest(source_files,root);
out=struct('parent',parent,'variants',variants,'gamma2019',gamma,'bus_metadata',metadata, ...
    'branch_map',branch_map,'source_manifest',source_manifest,'construction_source_manifest',b.source_manifest, ...
    'historical_topology_policy',"pre_2025_51_bus_compact_research_variant_not_as_built_2019_claim", ...
    'current_2025_baseline_modified',false,'new_power_flows_run',false,'new_optimizations_run',false, ...
    'public_operator_exact',false,'electrical_baseline_qualified',false);
if options.export_current_inputs
    [out.selected_inputs,out.input_bus_rows,out.input_generator_rows,out.input_zone_rows,out.input_source_manifest]=current_inputs(out,root);
    out.tests=test_export_compact_network(out);
end
if options.write_outputs
    folder=options.output_dir;
    assert(contains(strrep(folder,'\','/'),'/nygrid_compact_2019/'), ...
        'compact_2019:OutputScope','Write only to a separate nygrid_compact_2019 comparison folder.');
    if ~isfolder(folder),mkdir(folder);end
    write(folder,'bus_metadata.csv',metadata);write(folder,'branch_identity_map.csv',branch_map);
    write(folder,'source_manifest.csv',source_manifest);write(folder,'construction_source_manifest.csv',b.source_manifest);
    write(folder,'current_operator_members.csv',parent.operators.members);
    write(folder,'current_operator_registry.csv',parent.operators.registry);
    write(folder,'current_operator_gaps.csv',parent.operators.coverage_gaps);
    write(folder,'legacy_operator_members.csv',parent.legacy_operators.members);
    write(folder,'fleet_paper74.csv',variants.paper74.fleet_register);
    write(folder,'fleet_physical77.csv',variants.physical77.fleet_register);
    network_data=struct('gamma2019',gamma,'baseMVA',100,'parent',plain(parent), ...
        'paper74',plain(variants.paper74),'physical77',plain(variants.physical77), ...
        'bus_ids',m.bus(:,BUS_I),'bus_names',{cellstr(metadata.compact_bus_name)}, ...
        'compact_physical_zones',{cellstr(metadata.compact_physical_zone)}, ...
        'paper_allocation_zones',{cellstr(metadata.paper_allocation_zone)}, ...
        'current_interface_names',{cellstr(parent.operators.names)}, ...
        'current_from_coefficients',full(parent.operators.from_coefficients), ...
        'current_to_coefficients',full(parent.operators.to_coefficients), ...
        'current_dc_coefficients',full(parent.operators.from_coefficients-parent.operators.to_coefficients), ...
        'legacy_from_coefficients',full(parent.legacy_operators.from_coefficients), ...
        'legacy_to_coefficients',full(parent.legacy_operators.to_coefficients));
    save(fullfile(folder,'compact_network.mat'),'out','network_data','-v7');
    if options.export_current_inputs
        write(folder,'export_tests.csv',out.tests);
        selected_inputs=out.selected_inputs;input_data=cell(numel(selected_inputs),1);
        for k=1:numel(selected_inputs)
            q=selected_inputs{k};input_data{k}=struct('scenario_id',char(q.scenario_id), ...
                'timestamp',char(q.timestamp),'gamma2019',gamma,'paper74',plain(q.paper74), ...
                'physical77',plain(q.physical77),'source_prior_zone_mw',q.source_prior_zone_mw, ...
                'historical_unrepresented_source_mw',q.historical_unrepresented_source_mw, ...
                'remaining_unallocated_source_mw',q.remaining_unallocated_source_mw, ...
                'gross_pd_mw',q.bus_rows.pd_gross_mw,'gross_qd_mvar',q.bus_rows.qd_gross_mvar, ...
                'boundary_p_mw',q.bus_rows.p_boundary_mw,'boundary_q_mvar',q.bus_rows.q_boundary_mvar, ...
                'legacy_raw_pg_by_bus_mw',q.bus_rows.legacy_raw_source_pg_mw, ...
                'legacy_bounded_prior_pg_by_bus_mw',q.bus_rows.legacy_bounded_prior_pg_mw, ...
                'legacy_solved_pg_by_bus_mw',q.bus_rows.legacy_solved_pg_mw);
        end
        save(fullfile(folder,'current_input_snapshots.mat'),'selected_inputs','input_data','-v7');
        write(folder,'current_input_bus_rows.csv',out.input_bus_rows);
        write(folder,'current_input_generator_rows.csv',out.input_generator_rows);
        write(folder,'current_input_zone_rows.csv',out.input_zone_rows);
        write(folder,'current_input_source_manifest.csv',out.input_source_manifest);
    end
    description=struct('gamma2019',gamma,'gamma_policy','one_fixed_2019_summer_peak_public_to_benchmark_factor', ...
        'network_bus_count',51,'branch_records',92,'active_branches',87,'parent_generator_records',35, ...
        'historical_generator_records',37,'current_2025_bus_count',71, ...
        'power_scale','benchmark_MW_all_transferred_public_P_and_targets_multiply_gamma_once', ...
        'reactive_policy','inherited_benchmark_load_Q_and_controls_new_nuclear_Q_assumed_0.95pf_at_Pmax', ...
        'source_time_policy','existing_P32_forward_hold_hour_mean_maxgap600s_not_paper_raw_arithmetic_sample_mean', ...
        'target_policy','no_interface_values_read_or_used_by_export_source_prior_adapter_targets_NaN', ...
        'fleet_policy','paper74_primary_literal_allocation_physical77_separate_spatial_sensitivity', ...
        'qualification','raw_source_inputs_preserved_even_outside_bounds_no_new_AC_or_historical_topology_qualification');
    fid=fopen(fullfile(folder,'export_description.json'),'w');assert(fid>0);fprintf(fid,'%s\n',jsonencode(description,'PrettyPrint',true));fclose(fid);
    files=dir(folder);names={files(~[files.isdir]).name};names=names(~strcmp(names,'output_manifest.csv'));
    write(folder,'output_manifest.csv',manifest(cellfun(@(s)fullfile(folder,s),names,'UniformOutput',false),folder));
end
end

function v=fleet(parent,landing,gamma)
define_constants;assert(ismember(landing,[74 77]));v=parent;m=parent.candidate;
assert(~any(m.gen(:,GEN_BUS)==landing&m.gen(:,GEN_STATUS)>0&m.gen(:,PMAX)>0), ...
    'compact_2019:FleetOverlap','An existing online active generator already occupies the proposed nuclear terminal.');
assert(~any(startsWith(parent.generator_keys,"NY2019:INDIAN_POINT")),'compact_2019:DuplicateFleet','Fleet already restored.');
pub=[1025.9;1039.9];cap=gamma*pub;qcap=cap*tan(acos(.95));
g=zeros(2,21);g(:,GEN_BUS)=landing;g(:,PMAX)=cap;g(:,QMAX)=qcap;g(:,QMIN)=-qcap;
g(:,VG)=1;g(:,MBASE)=100;g(:,GEN_STATUS)=1;
v.candidate.gen=[m.gen;g];v.candidate.gencost=[m.gencost;repmat([2 0 0 3 0 0 0],2,1)];
v.candidate.bus(m.bus(:,BUS_I)==landing,BUS_TYPE)=PV;
v.generator_keys=[parent.generator_keys;"NY2019:INDIAN_POINT:2";"NY2019:INDIAN_POINT:3"];
policy="released_NYgrid_2019_allocation_bus74";if landing==77,policy="compact_Buchanan_physical_zoneH_sensitivity";end
v.fleet_register=table(v.generator_keys(end-1:end),(36:37)',repmat(landing,2,1),pub,repmat(gamma,2,1),cap,-qcap,qcap, ...
    repmat(policy,2,1),repmat("NYgrid_updateOpCond_2019_Capnuclear_1025.9_1039.9",2,1), ...
    repmat("assumed_symmetric_Q_at_0.95_power_factor_and_Pmax_not_verified_capability_curve",2,1), ...
    repmat("PG_initial_zero_snapshot_source_prior_assigned_later_PMIN0_no_mustrun_claim",2,1), ...
    'VariableNames',{'generator_key','generator_row','model_bus','source_public_pmax_mw','gamma2019', ...
    'benchmark_pmax_mw','assumed_qmin_mvar','assumed_qmax_mvar','landing_policy','capacity_source', ...
    'reactive_assumption','dispatch_policy'});
v.fleet_landing=landing;v.fleet_vintage=2019;v.fleet_restoration_qualified_as_observed=false;
assert(isequal(v.candidate.branch,m.branch)&&isequal(v.candidate.bus(:,[BUS_I PD QD GS BS BASE_KV VMIN VMAX]),m.bus(:,[BUS_I PD QD GS BS BASE_KV VMIN VMAX])));
end

function [selected,buses,gens,zones,sources]=current_inputs(out,root)
define_constants;ids=["S2_2019_WINTER_PEAK_PUBLIC";"S3_2019_SHOULDER_LIGHT_LOAD_PUBLIC"; ...
    "S4_2019_HIGH_NYC_LI_LOAD_PUBLIC";"S1_2019_SUMMER_PEAK_PUBLIC";"S6_2019_LOW_TOTAL_EAST_PUBLIC"];
folder=fullfile(root,'output','compact_ny_2025','generation_reconstruction');
files=cellstr(fullfile(folder,ids,'source_prior_evidence.mat'));sources=manifest(files,root);
selected=cell(5,1);buses=table();gens=table();zones=table();
for k=1:5
    d=load(files{k},'snapshot','fit');s=d.snapshot;
    assert(s.snapshot.vintage==2019&&abs(s.snapshot.scale_factor_gamma-out.gamma2019)<1e-15);
    assert(d.fit.electrical_baseline_qualified&&~d.fit.internal_interface_fit_used);
    assert(isequal(s.candidate.bus(:,BUS_I),out.parent.candidate.bus(:,BUS_I)) ...
        &&isequal(s.branch_keys,out.parent.branch_keys)&&isequal(s.generator_keys,out.parent.generator_keys), ...
        'compact_2019:SourceIdentity','Existing source inputs must belong to the same pre-2025 compact identity inventory.');
    assert(isequal(s.candidate.branch(:,1:13),out.parent.candidate.branch(:,1:13)), ...
        'compact_2019:SourceTopology','A 2019 source input unexpectedly contains a topology overlay.');
    g=s.independent_prior_generator_ledger;z=s.independent_prior_zone_ledger;ledger=s.bus_injection_ledger;
    [ok,gi]=ismember(g.model_bus,ledger.model_bus);assert(all(ok));n=height(ledger);
    rows=ledger;rows.scenario_id=repmat(ids(k),n,1);rows.timestamp=repmat(string(s.snapshot.timestamp),n,1);
    rows.legacy_raw_source_pg_mw=accumarray(gi,g.raw_prior_mw,[n 1]);
    rows.legacy_bounded_prior_pg_mw=accumarray(gi,g.bounded_prior_mw,[n 1]);
    rows.legacy_solved_pg_mw=accumarray(gi,d.fit.result.gen(:,PG),[n 1]);
    h=z.zone=="H";assert(nnz(h)==1&&z.online_generator_count(h)==0);
    missing=z.unallocated_source_prior_mw(h);assert(abs(missing-z.source_prior_benchmark_mw(h))<1e-7);
    p=struct('scenario_id',ids(k),'timestamp',string(s.snapshot.timestamp),'bus_rows',rows, ...
        'source_prior_zone_mw',z.source_prior_benchmark_mw,'historical_unrepresented_source_mw',sum(z.total_unrepresented_prior_mw), ...
        'remaining_unallocated_source_mw',sum(z.unallocated_source_prior_mw)-missing, ...
        'legacy_source_qualified_fit',d.fit.electrical_baseline_qualified, ...
        'time_policy',"existing_forward_hold_mean_not_released_paper_raw_sample_mean");
    for name=["paper74","physical77"]
        v=out.variants.(name);q=s;q.candidate=v.candidate;q.generator_keys=v.generator_keys;
        q.candidate.bus(:,[PD QD])=[ledger.pd_effective_mw ledger.qd_effective_mvar];
        cap=v.candidate.gen(end-1:end,PMAX);share=cap/sum(cap);raw=[g.raw_prior_mw;missing*share];
        q.candidate.gen(:,PG)=raw;q.Pg_prior_mw=raw;
        q.Pg_sigma_mw=[s.Pg_sigma_mw;z.zone_sigma_mw(h)*sqrt(share)];
        q.operators=out.parent.operators;q.interface_targets=table(q.operators.names,nan(7,1), ...
            'VariableNames',{'interface_name','target_flow_mw'});
        q.snapshot.default_campaign_interface_fit_allowed=false;
        q.snapshot.dataset_split="source_only_prediction";
        q.prior_method="unclipped_existing_2019_zonal_source_assignment_plus_explicit_Indian_Point_H_restoration";
        q.restored_H_policy="combined_zone_H_source_prior_assigned_to_two_nuclear_comparison_proxies_not_unit_observation";
        q.accounting_error_mw=max(abs(q.candidate.bus(:,PD)-(ledger.pd_gross_mw-ledger.p_boundary_mw)));
        q.source_unallocated_mw=p.remaining_unallocated_source_mw;q.source_dispatch_clipped=false;
        q.electrical_baseline_qualified=false;q.fleet_register=v.fleet_register;
        assert(abs(sum(raw)+p.remaining_unallocated_source_mw-sum(z.source_prior_benchmark_mw))<1e-7, ...
            'compact_2019:GenerationAccounting','Unclipped generation and explicit unallocated ledger must preserve all source MW.');
        p.(name)=q;
        gg=table(repmat(ids(k),37,1),repmat(name,37,1),(1:37)',q.generator_keys, ...
            q.candidate.gen(:,GEN_BUS),raw,raw/out.gamma2019,q.candidate.gen(:,PMIN),q.candidate.gen(:,PMAX), ...
            raw<q.candidate.gen(:,PMIN)|raw>q.candidate.gen(:,PMAX),repmat(false,37,1), ...
            'VariableNames',{'scenario_id','fleet_variant','generator_row','generator_key','bus_id', ...
            'raw_source_pg_benchmark_mw','raw_source_pg_public_mw','pmin_mw','pmax_mw','raw_prior_outside_bounds','dispatch_clipped'});
        gg.allocation_basis=repmat("existing_zonal_source_prior_inherited_within_zone_headroom_allocation",37,1);
        gg.allocation_basis(end-1:end)="combined_H_source_total_capacity_shared_between_nuclear_proxies_not_observed_unit_dispatch";
        gens=[gens;gg]; %#ok<AGROW>
    end
    selected{k}=p;buses=[buses;rows];zones=[zones;z]; %#ok<AGROW>
end
end

function p=plain(v)
m=v.candidate;p=struct('baseMVA',m.baseMVA,'bus',m.bus,'gen',m.gen,'branch',m.branch, ...
    'gencost',m.gencost,'bus_names',{m.bus_name},'branch_keys',{cellstr(v.branch_keys)}, ...
    'generator_keys',{cellstr(v.generator_keys)});
if isfield(v,'Pg_prior_mw'),p.Pg_prior_mw=v.Pg_prior_mw;p.Pg_sigma_mw=v.Pg_sigma_mw;end
end
function t=manifest(files,root)
files=cellstr(string(files(:)));paths=strings(numel(files),1);hash=paths;
for k=1:numel(files),paths(k)=strrep(erase(files{k},[root filesep]),'\','/');hash(k)=ny_reference_file_sha256(files{k});end
t=table(paths,hash,'VariableNames',{'relative_path','sha256'});
end
function write(folder,name,t)
ny_lite_writetable_lf(t,fullfile(folder,name));
end
