function export_reference_snapshot
%EXPORT_REFERENCE_SNAPSHOT Export released reconstruction components unchanged.
root=fileparts(fileparts(fileparts(mfilename('fullpath'))));
folder=fullfile(root,'output','nygrid_compact_2019','reference');
if ~isfolder(folder),mkdir(folder);end
cached=fullfile(root,'tmp','nygrid_2019_reproduction','cached_upstream');
toolbox=fullfile(root,'tmp','nygrid_2019_reproduction','reduction_toolbox','mirror');
old=pwd;clean=onCleanup(@()cd(old));cd(cached);
addpath(genpath(cached),toolbox,'-begin');
% Reuse the saved, unmodified modifyMPC result to avoid touching its artifacts.
source=fullfile(root,'output','nygrid_2019','unmodified_smoke_mirror_legacy.mat');
d=load(source,'base');base=d.base;
times=[datetime(2019,1,8,15,0,0);datetime(2019,1,21,18,0,0); ...
    datetime(2019,4,21,4,0,0);datetime(2019,7,17,16,0,0); ...
    datetime(2019,7,20,16,0,0);datetime(2019,7,27,2,0,0)];
snapshots=cell(numel(times),1);
for k=1:numel(times)
    t=times(k);evalc('m=updateOpCond(base,t,false,false,true);');
    [r,ok]=rundcpf(m,mpoption('verbose',0,'out.all',0,'exp.use_legacy_core',1));
    assert(ok,'reference_export:PF','Released DC replay failed.');
    loadData=allocateLoad(t,'weighted',true);g=allocateGen(t,'lm',true);
    [fuel,inter,lims,nuclear,hydro,prices]=readOpCond(t,true);
    renew=importRenewableGen(fullfile('Data','RenewableGen.csv'));
    nw=height(g);assert(nw==227&&isequal(m.gen(1:nw,1),g.BusName));
    wind=fuel.GenMW(fuel.FuelCategory=="Wind");other=fuel.GenMW(fuel.FuelCategory=="Other Renewables");
    ng_nuclear=6;ng_hydro=nnz(renew.PgHydroCap);
    native_count=nw+ng_nuclear+ng_hydro;
    s=struct('timestamp',char(string(t,'yyyy-MM-dd''T''HH:mm:ss')), ...
        'input_case',m,'result_case',r,'gross_bus_ids',loadData.idx, ...
        'gross_pd_mw',loadData.PD,'gross_qd_mvar',loadData.QD, ...
        'renewable_bus_ids',renew.BusID,'wind_capacity_mw',renew.PgWindCap, ...
        'other_capacity_mw',renew.PgOtherCap, ...
        'wind_injection_mw',wind*renew.PgWindCap/sum(renew.PgWindCap), ...
        'other_injection_mw',other*renew.PgOtherCap/sum(renew.PgOtherCap), ...
        'thermal_source_recorded_pg_mw',g.hourlyGen,'thermal_model_bus',g.BusName, ...
        'thermal_ptid',{cellstr(string(g.PTID))},'thermal_name',{cellstr(string(g.NYISOName))}, ...
        'thermal_allocated_pg_mw',m.gen(1:nw,2), ...
        'native_generator_rows',(1:native_count)', ...
        'nuclear_generator_rows',(nw+(1:ng_nuclear))', ...
        'hydro_generator_rows',(nw+ng_nuclear+(1:ng_hydro))', ...
        'statewide_hydro_mw',fuel.GenMW(fuel.FuelCategory=="Hydro"), ...
        'statewide_nuclear_mw',fuel.GenMW(fuel.FuelCategory=="Nuclear"), ...
        'monthly_st_lawrence_capacity_factor',hydro.stlCF, ...
        'monthly_st_lawrence_generation_mw',hydro.stlCF*856, ...
        'fuel_names',{cellstr(string(fuel.FuelCategory))},'fuel_mw',fuel.GenMW, ...
        'external_and_interface_names',{cellstr(string(inter.InterfaceName))}, ...
        'external_and_interface_mw',inter.FlowMWH, ...
        'positive_interface_limits_mw',lims.PositiveLimitMWH, ...
        'negative_interface_limits_mw',lims.NegativeLimitMWH);
    snapshots{k}=s;
    fprintf('Exported %s grossload=%.6f nativegens=%d\n',s.timestamp,sum(loadData.PD),native_count);
end
save(fullfile(folder,'matched_snapshot_components.mat'),'snapshots','source','-v7');
end
