function out=run_restored_fleet_ac_checkpoint(options)
%RUN_RESTORED_FLEET_AC_CHECKPOINT Three preregistered source-prior AC tests.
% No Marcy edits and no interface objective. Preserve all failed attempts.
if nargin<1,options=struct();end
root=fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(fullfile(root,'System Matpower Format','NY_Lite'));
if ~isfield(options,'output_dir'),options.output_dir=fullfile(root,'output','nygrid_compact_2019','ac_checkpoint');end
folder=options.output_dir;assert(endsWith(strrep(folder,'\','/'),'/nygrid_compact_2019/ac_checkpoint'), ...
    'compact_2019_ac:OutputScope','Use the isolated historical AC checkpoint folder.');
define_constants;input_folder=fullfile(root,'output','nygrid_compact_2019','compact');
file=fullfile(input_folder,'current_input_snapshots.mat');
manifest=readtable(fullfile(input_folder,'output_manifest.csv'),'TextType','string');
row=manifest.relative_path=="current_input_snapshots.mat";input_hash=ny_reference_file_sha256(file);
assert(nnz(row)==1&&manifest.sha256(row)==input_hash,'compact_2019_ac:InputFingerprint','Historical input artifact hash differs.');
d=load(file,'selected_inputs');
ids=["S2_2019_WINTER_PEAK_PUBLIC";"S3_2019_SHOULDER_LIGHT_LOAD_PUBLIC";"S1_2019_SUMMER_PEAK_PUBLIC"];
policy=struct('selection',"preregistered_winter_shoulder_summer_source_input_hours", ...
    'fleet_variant',"paper74",'primary_solver',"MIPS",'primary_start',0, ...
    'fallback',"strict_IPOPT_start0_only_if_primary_fails_physical_qualification", ...
    'fit_interfaces',false,'prior_weight',1,'source_dispatch_clipped',false, ...
    'Marcy_AC_qualification',"not_attempted_unqualified_R_B_ratings_in_DC_hypothesis", ...
    'qualification_scope',"restored_2019_source_prior_bounded_AC_on_unchanged_51_bus_network", ...
    'fixed_dispatch_claim',false,'historical_flow_calibration_claim',false);
code=code_manifest(root);
if ~isfolder(folder),mkdir(folder);end
summary=table();attempts=table();bus_movement=table();gen_movement=table();flows=table();cases=cell(3,1);
for k=1:3
    match=cellfun(@(s)string(s.scenario_id)==ids(k),d.selected_inputs);assert(nnz(match)==1);
    s=d.selected_inputs{find(match,1)}.paper74;
    assert(all(isnan(s.interface_targets.target_flow_mw))&&~s.snapshot.default_campaign_interface_fit_allowed ...
        &&~s.source_dispatch_clipped&&abs(s.source_unallocated_mw)<1e-7);
    assert(size(s.candidate.bus,1)==51&&size(s.candidate.gen,1)==37&&size(s.candidate.branch,1)==92 ...
        &&sum(s.candidate.branch(:,BR_STATUS)>0)==87);
    sf=fullfile(folder,char(ids(k)));if ~isfolder(sf),mkdir(sf);end
    % A separate reference-balancing PF diagnoses the raw-prior state. It
    % cannot preserve total generator P when source supply and demand differ.
    raw=s.candidate;raw.success=false;raw.branch(:,PF:QT)=0;raw_error="";
    try,raw=runpf(s.candidate,mpoption('verbose',0,'out.all',0,'pf.enforce_q_lims',1,'pf.tol',1e-10));
    catch err,raw_error=string(err.identifier)+": "+string(err.message);end
    raw=plain(raw);ao=struct('branch_keys',s.branch_keys,'generator_keys',s.generator_keys);
    raw_audit=audit_ny_ac_reference(raw,ao);
    fits=cell(0,1);solvers="MIPS";
    for j=1:2
        if j==2
            if fits{1}.electrical_baseline_qualified||~have_feature('ipopt'),break;end
            solvers(j)="IPOPT";
        end
        fit=fit_compact_partial_spc_operating_snapshot(s,struct('solver',char(solvers(j)), ...
            'opf_start',0,'fit_interfaces',false,'prior_weight',1,'mips_cost_multiplier',1));
        fits{j}=fit;ar=attempt_row(ids(k),j,fit);attempts=[attempts;ar]; %#ok<AGROW>
        save(fullfile(sf,sprintf('attempt_%d_%s.mat',j,solvers(j))),'fit','ar','-v7');
        write(sf,sprintf('attempt_%d_%s_audit.csv',j,solvers(j)),fit.audit.summary);
        if fit.electrical_baseline_qualified,break;end
    end
    chosen=numel(fits);fit=fits{chosen};r=fit.result;nr=size(r.bus,1);ng=size(r.gen,1);
    [ok,gix]=ismember(r.gen(:,GEN_BUS),r.bus(:,BUS_I));assert(all(ok));
    prior=accumarray(gix,s.Pg_prior_mw,[nr 1]);solved=accumarray(gix,r.gen(:,PG),[nr 1]);
    bm=table(repmat(ids(k),nr,1),r.bus(:,BUS_I),string(r.bus_name),string(r.userdata.nyiso_physical_zone), ...
        prior,solved,solved-prior,s.candidate.bus(:,VM),r.bus(:,VM),r.bus(:,VM)-s.candidate.bus(:,VM), ...
        'VariableNames',{'scenario_id','bus_id','bus_name','compact_zone','raw_source_pg_mw','solved_pg_mw', ...
        'pg_departure_mw','initial_vm_pu','solved_vm_pu','vm_departure_pu'});
    gm=table(repmat(ids(k),ng,1),(1:ng)',s.generator_keys,r.gen(:,GEN_BUS),s.Pg_prior_mw,r.gen(:,PG), ...
        r.gen(:,PG)-s.Pg_prior_mw,s.candidate.gen(:,QG),r.gen(:,QG),r.gen(:,QG)-s.candidate.gen(:,QG), ...
        s.candidate.gen(:,PMIN),s.candidate.gen(:,PMAX),s.candidate.gen(:,QMIN),s.candidate.gen(:,QMAX), ...
        'VariableNames',{'scenario_id','gen_row','generator_key','bus_id','raw_prior_pg_mw','solved_pg_mw', ...
        'pg_departure_mw','initial_qg_mvar','solved_qg_mvar','qg_departure_mvar','pmin_mw','pmax_mw','qmin_mvar','qmax_mvar'});
    f=s.operators.from_coefficients*r.branch(:,PF)+s.operators.to_coefficients*r.branch(:,PT);
    ft=table(repmat(ids(k),7,1),repmat(string(s.snapshot.timestamp),7,1),s.operators.names,f,f/s.snapshot.scale_factor_gamma, ...
        repmat(fit.electrical_baseline_qualified,7,1),false(7,1),false(7,1), ...
        'VariableNames',{'scenario_id','timestamp','interface_name','model_flow_benchmark_mw','model_flow_public_scale_mw', ...
        'electrical_qualified','used_in_optimizer','exact_public_operator'});
    a=fit.audit.summary;on=s.candidate.gen(:,GEN_STATUS)>0;
    row=table(ids(k),string(s.snapshot.timestamp),s.snapshot.scale_factor_gamma,fit.solver,chosen, ...
        raw.success,raw_audit.passed,max(abs(raw.gen(on,PG)-s.Pg_prior_mw(on))), ...
        fit.electrical_baseline_qualified,fit.network_and_injections_frozen, ...
        sum(s.bus_injection_ledger.pd_gross_mw),sum(s.bus_injection_ledger.p_boundary_mw), ...
        sum(s.Pg_prior_mw),sum(r.gen(on,PG)),sum(abs(r.gen(on,PG)-s.Pg_prior_mw(on))), ...
        max(abs(r.gen(on,PG)-s.Pg_prior_mw(on))),sum(abs(gm.qg_departure_mvar(on))),max(abs(bm.vm_departure_pu)), ...
        a.max_nodal_p_mismatch_mw,a.max_nodal_q_mismatch_mvar, ...
        fit.independent_replay_dispatch_adjustment_mw,fit.independent_replay_voltage_adjustment_pu, ...
        false,false,false,raw_error, ...
        'VariableNames',{'scenario_id','timestamp','gamma2019','selected_solver','selected_attempt', ...
        'raw_prior_PF_success','raw_prior_PF_physical_audit_pass','raw_prior_PF_max_reference_adjustment_mw', ...
        'bounded_AC_qualified','network_loads_boundaries_capabilities_frozen','gross_load_mw','boundary_injection_mw', ...
        'raw_source_generation_mw','solved_generation_mw','dispatch_L1_movement_mw','max_unit_dispatch_movement_mw', ...
        'Q_dispatch_L1_movement_mvar','max_voltage_movement_pu','max_P_mismatch_mw','max_Q_mismatch_mvar', ...
        'fresh_PF_Pg_adjustment_mw','fresh_PF_VM_adjustment_pu','interface_objective_used', ...
        'Marcy_DC_topology_AC_qualified','bounds_relaxed','raw_prior_PF_error'});
    summary=[summary;row];bus_movement=[bus_movement;bm];gen_movement=[gen_movement;gm];flows=[flows;ft]; %#ok<AGROW>
    evidence=struct('snapshot',s,'raw_prior_PF',raw,'raw_prior_PF_audit',raw_audit,'raw_prior_PF_error',raw_error, ...
        'attempts',{fits},'selected_attempt',chosen,'fit',fit,'summary',row);
    cases{k}=evidence;save(fullfile(sf,'evidence.mat'),'evidence','-v7');
    write(sf,'raw_prior_PF_audit.csv',raw_audit.summary);write(sf,'bounded_audit.csv',fit.bounded_audit.summary);
    write(sf,'fresh_PF_audit.csv',fit.audit.summary);write(sf,'fresh_PF_bus_audit.csv',fit.audit.bus);
    write(sf,'fresh_PF_branch_audit.csv',fit.audit.branch);write(sf,'fresh_PF_generator_audit.csv',fit.audit.generator);
    write(sf,'generator_movement.csv',gm);write(sf,'bus_movement.csv',bm);write(sf,'interface_flows.csv',ft);
end
assert(ny_reference_file_sha256(file)==input_hash&&isequal(code_manifest(root),code), ...
    'compact_2019_ac:ConcurrentChange','Input or executing code changed during the checkpoint.');
out=struct('policy',policy,'cases',{cases},'summary',summary,'attempts',attempts, ...
    'bus_movement',bus_movement,'generator_movement',gen_movement,'interface_flows',flows, ...
    'input_sha256',input_hash,'code_manifest',code,'all_three_qualified',all(summary.bounded_AC_qualified), ...
    'Marcy_DC_topology_AC_qualified',false);
save(fullfile(folder,'restored_fleet_ac_checkpoint.mat'),'out','-v7');
write(folder,'summary.csv',summary);write(folder,'attempts.csv',attempts);write(folder,'bus_movement.csv',bus_movement);
write(folder,'generator_movement.csv',gen_movement);write(folder,'interface_flows.csv',flows);write(folder,'code_manifest.csv',code);
files=dir(fullfile(folder,'**','*'));files=files(~[files.isdir]);paths=strings(numel(files),1);hashes=paths;
for j=1:numel(files),f=fullfile(files(j).folder,files(j).name);paths(j)=strrep(erase(f,[folder filesep]),'\','/');hashes(j)=ny_reference_file_sha256(f);end
keep=paths~="output_manifest.csv";write(folder,'output_manifest.csv',table(paths(keep),hashes(keep),'VariableNames',{'relative_path','sha256'}));
end

function t=attempt_row(id,j,f)
a=f.bounded_audit.summary;
t=table(id,j,f.solver,f.bounded_result.success,f.bounded_audit.passed,f.audit.passed, ...
    f.electrical_baseline_qualified,a.max_nodal_p_mismatch_mw,a.max_nodal_q_mismatch_mvar, ...
    f.solver_error,f.replay_error,'VariableNames',{'scenario_id','attempt','solver','solver_success', ...
    'bounded_audit_pass','fresh_PF_audit_pass','qualified','max_P_mismatch_mw','max_Q_mismatch_mvar','solver_error','replay_error'});
end
function t=code_manifest(root)
names=["run_restored_fleet_ac_checkpoint";"fit_compact_partial_spc_operating_snapshot"; ...
    "audit_ny_ac_reference";"runopf";"runpf";"makeYbus";"mpoption"];
paths=strings(numel(names),1);hashes=paths;
for j=1:numel(names),p=which(names(j));assert(~isempty(p));paths(j)=strrep(erase(p,[root filesep]),'\','/');hashes(j)=ny_reference_file_sha256(p);end
t=table(names,paths,hashes,'VariableNames',{'function_name','path','sha256'});
end
function write(folder,name,t),ny_lite_writetable_lf(t,fullfile(folder,name));end
function m=plain(m)
keep=intersect(fieldnames(m),{'version','baseMVA','bus','gen','branch','gencost','bus_name','success','userdata'});
m=rmfield(m,setdiff(fieldnames(m),keep));
end
